### ISSUE TITLE
Bing Streetside data not showing 

### ISSUE THREAD

**Issue by elevenchars** [openstreetmap/iD#10074]
### URL

https://www.openstreetmap.org/edit#map=17/30.42430/-97.76190

### How to reproduce the issue?

1. Open iD in an area where Bing Streetside data should be visible
2. Enable "Bing Streetside" in map data tab
3. Observe that nothing loads

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/iD/assets/11055681/953afcfa-fb98-489b-9c5a-b191f1a70231)

It looks like all of the requests for the bubbles are returning 401.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.3

### Which browsers are you seeing this problem on?

Firefox

**Comment by elevenchars** [comment]
See https://github.com/facebook/Rapid/issues/1305

**Comment by jjiglesiasg** [comment]
![Screenshot (159)](https://github.com/openstreetmap/iD/assets/22849578/61be5101-d091-41ca-8184-c95bcfc1445a)

OSM Data not loading in ID or if load a portion and then move the screen area, no data is shown.

https://www.openstreetmap.org/edit#map=19/-16.50479/-68.13016

**Comment by k-yle** [comment]
@jjiglesiasg that's because the OSM API [has been intermittently unavailable](https://prometheus.openstreetmap.org/d/5rTT87FMk/web-site?orgId=1&refresh=1m&from=1705987783000&to=now&viewPanel=23) over the past 24 hours

**Comment by dankarran** [comment]
I've been seeing this issue recently as well, often getting 401 errors in the console when trying to enable the Streetside layer. It still works occasionally, but generally not.

**Comment by FinixFighter** [comment]
I still have the issue (Brave browser)

**Comment by dankarran** [comment]
I tried creating myself a test key in the [Bing Maps Dev Center](https://www.microsoft.com/en-us/maps/bing-maps/create-a-bing-maps-key), and I still get a 401 when trying to access the API, suggesting this may be an issue with the Bing Maps API as a whole rather than an issue specific to the key that iD (and Rapid) is using.

**Comment by dankarran** [comment]
I was lucky enough to get some StreetSide bubbles on one editing session this morning, but then it stopped working again.

The Bing Maps website is using a different URL to get the StreetSide bubble metadata, so I wonder if they've made some updates to this (apparently undocumented) API:

https://t.ssl.ak.tiles.virtualearth.net/tiles/cmd/StreetSideBubbleMetaData?count=500&north=[n]&south=[s]&east=[e]&west=[w]&key=[key]&g=[g?]

rather than

https://dev.virtualearth.net/mapcontrol/HumanScaleServices/GetBubbles.ashx?appkey=[key]&c=2000&e=[e]&n=[n]&s=[s]&w=[w]&jsCallback=jsonpCache.wbmjFaCxteJmxNB

Note that the document structure is slightly different as well, as the new one doesn't have a jsCallback parameter.

**Comment by dankarran** [comment]
I've added a PR (#10100) which requests bubble metadata from the new URL, if anybody is able to give it a look over?

I emailed osm@microsoft.com on Friday to let them know about the issue, and they are looking into the root cause.

@bhousel has applied a similar fix to the Rapid editor (https://github.com/facebook/Rapid/commit/2a8ce9947fd76b67e579df4867b20bf85d2780f4) which is already live and seems to be working well.

**Comment by danieldegroot2** [comment]
Sidenote: Report link bottom right used to give the [`bubbleid`](https://wiki.openstreetmap.org/wiki/Key:bubbleid). It now gives the full request URL as value instead. So I suppose I'll not use it anymore (not that any data consumers have used it so far).
