### ISSUE TITLE
"Best image" should be aerial, not other categories

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#10090]
### Description

In NRW there are two data layer marked as "best", one ALKIS and one aerial imagery.

It looks like the system picks the first "best" imagery of any category sorted by name.

However, I think it should look for a "best" image of category aerial imagery first and only then fall back to a list of all "best" layers.

Test area: https://www.openstreetmap.org/edit#map=18/50.82658/6.35559

### Screenshots

<img width="751" alt="image" src="https://github.com/openstreetmap/iD/assets/111561/99fe495a-8821-44a5-8ff8-98e9020dfcf5">

**Comment by tordans** [comment]
I marked this as "good first issue" because I assume that the part of the code that handels the layer that is selected by default should be straight forward to find and adjust as described above. But I did not look into it myself, yet.

**Comment by bhousel** [comment]
This is an issue for editor-layer-index, not iD

**Comment by tordans** [comment]
> This is an issue for editor-layer-index, not iD

@bhousel Only if ELI defines that the "best" option should only be applied to aerial imagery. The Alkis layer is in fact the best of it's category. 

I don't think it unreasonable to specify a "best" per category.

Unfortunately, [ELI's documentation](https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md?plain=1) on the topic of category and "best" ist not that extensive.

---

What are your concerns in adding this check in iD/Rapid?

**Comment by bhousel** [comment]
> What are your concerns in adding this check in iD/Rapid?

If the data is set up wrongly in the source, it should be fixed there, not by the imagery consumers.   

`best` does have a [well defined meaning](https://github.com/osmlab/editor-layer-index/issues/130#issuecomment-229060048), (it's a local override to the global Bing default), and it shouldn't be set for a source that's not orthoimagery for tracing.

**Comment by tordans** [comment]
@bhousel thanks for your insight. I do not consider the `best` flag well documented and as such defined. But I agree with your definition and will try to find the time to suggest upstream changes to improve the docs and fix the wrong usage. I now remember that I ran into the same issue 2018 but that staled in its research state https://github.com/osmlab/editor-layer-index/issues/538.

Note to self: This https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json#L109-L112 will also have to change to clarify the intended usage of "best" as "local override to the global Bing default".

I will close this issue here.

**Comment by Nekzuris** [comment]
To this day it's still defined as "Whether this imagery is the best source for the region" in [ELI schema](https://github.com/osmlab/editor-layer-index/blob/fc916e20846ca21210a6674e291747f58aefe16c/schema.json#L126-L128) and in [iD API](https://github.com/openstreetmap/iD/blob/develop/API.md#:~:text=the%20imagery%20terms-,best,-%2D%20If%20set%20to) :

> `best` - If set to `true`, this imagery is considered "better than Bing" and may be chosen by default when iD starts. Will display with a star in the background imagery list. Defaults to `false`

This is a bit problematic because LiDAR hillshade is objectively the best ortho-corrected layer we have and the only one for tracing precise paths and rivers in forests, but I can't mark it as best because it shouldn't be selected as the default. 
Best and default are two different things. It shouldn't be a problem to have multiple best layers for a region, especially in two different categories, and the logic to not show elevation layers as default should be handled in iD, see https://github.com/osmlab/editor-layer-index/pull/2765#discussion_r2313784574
