### ISSUE TITLE
Disable warning when "Disused Railway crosses Service Road"

### ISSUE THREAD

**Issue by dreua** [openstreetmap/iD#10126]
**Describe the bug**
I get a lot of warnings with `railway=disused` crossing paths and streets. According to the railway lifecycle it should not be tagged razed or abandoned but disused because the rails are still there.

**To Reproduce**
1. Goto https://www.openstreetmap.org/edit?way=236263986

**Expected behavior**
Don't care about the potential crossing, it is disused anyway.

**Screenshots**
![image](https://github.com/openstreetmap/id-tagging-schema/assets/15114715/1b7bf481-00c1-4a02-a50b-0ba12f64b63a)

**Additional context**
This is common in former industrial areas which have been converted to residential areas. The rails may stay in place for their industrial looks or because it is just cheaper than removing them. They are fully embedded in asphalt or paving stones in many places therefor not relevant for any routing purpose. They have no value as an infrastructure element any more and it therefore wouldn't make sense to add crossings.

https://wiki.openstreetmap.org/wiki/Tag:railway=disused
https://wiki.openstreetmap.org/wiki/Railways#Life-cycle

**Comment by qugebert** [comment]
I think this issue belongs to [iD](https://github.com/openstreetmap/iD), because validation in done [there](https://github.com/openstreetmap/iD/blob/develop/modules/validations/crossing_ways.js)

**Comment by tyrasd** [comment]
my 2 cents: if the rails are fully embedded in concrete or asphalt, they should not be considered `railway=disused`, because as you said the rails are only left there (i.e. recycled/upcycled to become a part of the road surface) because of financial and esthetic reasons. thus, `railway=abandoned` should be a more appropriate tag in this case.

removing the validation for missing crossings of roads and proper `railway=disused` would be quite definitely counterproductive.

**Comment by dreua** [comment]
Thanks for the feedback. I usually take the wiki as source of truth for tagging questions but in this case it might be better to change the wiki instead if the validator.
