### ISSUE TITLE
Add population and data source fields to isolated dwelling preset

### ISSUE THREAD

**Issue by heragnar** [openstreetmap/iD#10229]
### Description

The isolated dwelling preset does not provide fields to capture the population count, population date or the source of that population data.  Although these nodes typically only have 1 or 2 residents, it is still valuable to be able to record the precise population and its data source.

The OSM documentation indicates that these isolated dwelling places have the same characteristics as any other populated place, so it would be helpful if the iD editor treated them in a consistent manner by including population and data source input fields without requiring users to manually add the information through raw tags.

### Screenshots

The isolated dwelling preset only displays the name field:
![isolated](https://github.com/openstreetmap/iD/assets/130934952/cf5776b2-2899-40ad-bee8-e5bb6b740b32)

While other populated place presets like "Hamlet" show population-related fields:
![hamlet](https://github.com/openstreetmap/iD/assets/130934952/437944c3-cbdc-4d44-9571-48e9f0021552)

**Comment by RAytoun** [comment]
I believe that when you start adding the number of people that are living
in a specific dwelling then you are adding personal information. Population
count should be anonymous and limited to an area.

**Comment by tordans** [comment]
@heragnar this issue needs to be moved to https://github.com/openstreetmap/id-tagging-schema/issues which is where the "Presets" are managed for multiple editors.

@RAytoun Personally I don't see any privacy issue here since no person can be identified with this information. In any case, we should check the wiki recommendations or have this discussion on the forum. That is the better place than the issue trackers which are more concerned with how to add it (given the community documented "if" to add it).
