### ISSUE TITLE
Truncate Strava Heatmap custom URL to prevent exposing user's personal API key

### ISSUE THREAD

**Issue by nc011** [openstreetmap/iD#10252]
### Description

Strava Heatmap can be used as a background in the iD editor, using the custom URL feature. As required by Strava, the custom URL contains the user's private API keys.

iD editor currently adds any custom background URLs, in full, to the ``imagery_used`` key in changesets. iD editor therefore exposes the user's private Strava API keys. This opens up the keys to exploitation and presumably goes against Strava's T&Cs.

iD editor should truncate the Strava Heatmap custom URL to remove the user's private API key details, e.g.,

``https://heatmap-external-{switch:a,b,c}.strava.com/tiles-auth/ACTIVITY/COLOR/{zoom}/{x}/{y}.png?Key-Pair-Id=MYVALUE&Policy=MYVALUE&Signature=MYVALUE``

should only be saved as 

``https://heatmap-external-{switch:a,b,c}.strava.com/tiles-auth/ACTIVITY/COLOR/{zoom}/{x}/{y}.png``

**Comment by tyrasd** [comment]
As of #10007, iD already removes the `Signature=…` part of the Strava heatmap layer when used as a custom background layer.[^1]  I assumed that the other two parameters are the same for all users, aren't they?

[^1]: and because the `Policy` string is very long, it is always truncated in the output, making it unusable for anyone trying to steal credentials. [example](https://www.openstreetmap.org/changeset/142676563)

**Comment by nc011** [comment]
> I assumed that the other two parameters are the same for all users, aren't they?

Ah, I had assumed not but I think you may be correct. I performed a [recent edit](https://www.openstreetmap.org/changeset/152322974) and the values are the same as in your example. 

> and because the Policy string is very long, it is always truncated in the output, making it unusable for anyone trying to steal credentials. [example](https://www.openstreetmap.org/changeset/142676563) [↩](https://github.com/openstreetmap/iD/issues/10252#user-content-fnref-1-bdb8a58d831318f64de375b01b849798)

Good point.

I think this can be closed then.
