### ISSUE TITLE
Bing imagery viewer not working

### ISSUE THREAD

**Issue by hb0nd** [openstreetmap/iD#10259]
### How to reproduce the issue?

1. enable bing imagery viewer
2. select an imagery point
3. the viewer sometimes flashes the imagery, before showing a white screen with an error.
4. ticking the high resolution box freezes the whole editor.

### Screenshot(s) or anything else?

![Screenshot from 2024-05-26 12-47-33](https://github.com/openstreetmap/iD/assets/26939824/316cf652-91bd-46e7-8beb-359b98f815f3)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.29.0

### Which browsers are you seeing this problem on?

Firefox

**Comment by hb0nd** [comment]
the error is "the file {data:image/*} could not be accessed."

**Comment by tyrasd** [comment]
As this feature still works fine on externally hosted instances of iD (e.g. https://ideditor-release.netlify.app), this bug must have something to do with the integration into the OSM website. Most likely this was caused by https://github.com/openstreetmap/openstreetmap-website/pull/4627 – I'm taking a look right now

**Comment by tyrasd** [comment]
fixed upstream with https://github.com/openstreetmap/openstreetmap-website/pull/4840

**Comment by hb0nd** [comment]
thank you! 😊
