### ISSUE TITLE
Streetside (photo overlays) working intermittently

### ISSUE THREAD

**Issue by hb0nd** [openstreetmap/iD#10341]
### How to reproduce the issue?

unable to consistently reproduce

### Screenshot(s) or anything else?

Enabling bing streetside etc doesn't work, the lines are not displayed to click on.
Nothing in console.

![image](https://github.com/user-attachments/assets/8cbfc512-ba81-4627-b7f4-d7a867bc4e29)

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.30.0-dev

### Which browsers are you seeing this problem on?

Firefox

**Comment by tyrasd** [comment]
As of today, Bing Streetside works fine for me. It was probably an upstream issue on Bing's side; i.d.k. maybe a temporary service outage, or we hit the quota for our API key? Anyway, I don't think there's not much we can do here.

**Comment by hb0nd** [comment]
it does seem to be ok now 👍️

**Comment by tyrasd** [comment]
I was able to reproduce the issue today. Sometimes, requests to the Bing Streetside API are returning results in the wrong JSON format. :roll_eyes: Instead of the [documented](https://learn.microsoft.com/en-us/bingmaps/articles/getting-streetside-tiles-from-imagery-metadata) properties `lat`, `lon`, `he`, … it returns JSON with `latitude`, `longitude`, `heading`, etc.

![image](https://github.com/user-attachments/assets/3f8ba64a-dcd5-4913-9474-03939621dd9d)

What's very odd is that this does seem to really intermittent: Sometimes the same request does return the "correct" expected JSON format. Not sure what's going on. Perhaps some servers on Bing's API backend are running an incorrect version of the API. I've noticed that when the API result contains a `traceId` in the following format it seems to return the right JSON schema: `fc2a44deec03df4d11af488bebe71671|DU00003071|0.0.0.1`. And if the `traceId` looks like this, the results are in the incorrect format: `807ceb6dbaac366418ac04313c20737b`.

//cc @mbrzakovic do you maybe know someone from the Bing Maps team who could take a look at this?
