### ISSUE TITLE
Panoramax: Image not found

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10368]
### How to reproduce the issue?

Ref #9941 

The following error is returned numerous times.

```
data.geopf.fr/wmts?S…RMAT=image%2Fjpeg:1 
 GET https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER…TRIXSET=PM&TILEMATRIX=20&TILEROW=586927&TILECOL=685326&FORMAT=image%2Fjpeg 404 (Not Found)
Image		
(anonymous)	@	attr.js:31
jA	@	each.js:5
QA	@	attr.js:53
y	@	tile_layer.js:205
w	@	tile_layer.js:139
(anonymous)	@	on.js:3
error		
(anonymous)	@	on.js:42
jA	@	each.js:5
fS	@	on.js:65
y	@	tile_layer.js:206
g	@	tile_layer.js:93
GA	@	call.js:4
f	@	background.js:145
GA	@	call.js:4
oe	@	map.js:684
m	@	debounce.js:95
b	@	debounce.js:178
$	@	map.js:632
call	@	dispatch.js:57
zoom	@	zoom_pan.js:192
(anonymous)	@	zoom_pan.js:163
s	@	schedule.js:136
Pf	@	timer.js:61
GS	@	timer.js:71
requestAnimationFrame		
yg	@	timer.js:108
YQ	@	timer.js:96
GS	@	timer.js:74
requestAnimationFrame		
yg	@	timer.js:108
YQ	@	timer.js:96
GS	@	timer.js:74
requestAnimationFrame		
yg	@	timer.js:108
YQ	@	timer.js:96
GS	@	timer.js:74
requestAnimationFrame		
yg	@	timer.js:108
restart	@	timer.js:39
Q1	@	timer.js:52
eK	@	schedule.js:59
K1	@	schedule.js:19
vC	@	transition.js:36
ne	@	map.js:757
ge	@	map.js:788
Op.O.centerEase	@	map.js:932
(anonymous)	@	panoramax.js:595
(anonymous)	@	on.js:3
```

(it is usually harmless error, but feel free to check)

Chrome 127.0.6533.89 on Windows 10

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.30.0-dev

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
`GET https://data.geopf.fr/wmts?SERVICE=WMTS` :arrow_left: this indicates that the problem is caused by a (WMTS) background layer. It seems like this particular service is [configured](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/fr/BDOrthoIGN.geojson?short_path=e83f65a#L16) up to zoom level 21, but fails to load zoom 20 tiles in Paris. This is not necessarily a problem, as the service could have higher resolution imagery in other parts of France.

**Comment by danieldegroot2** [comment]
Yes, the URL said ORTHO before and now mentioned Panoramax in the details so I was unsure.
