### ISSUE TITLE
Panoramax: Becomes a blur when switching between imagery

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10362]
### How to reproduce the issue?

Ref #9941 

Occasionally on switching from Panoramax imagery to Mapillary or Bing and back, or through images too quickly perhaps, Panoramax becomes a -zoomed in- blur.
workaround: reload page

Sidenote: Similar to Mapillary, which can also becomes pixelated blur. (issue(s) already exist)

Chrome 127.0.6533.73 on Windows 10

### Screenshot(s) or anything else?

![image](https://github.com/user-attachments/assets/c6a36a22-ae17-4179-8798-77bf9bb3667e)

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.30.0-dev

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
I can reproduce this issue easily at the following location when switching between mapillary and panoramax 360° photos:

https://ideditor.netlify.app/#map=20.55/48.84149/2.57693&photo=panoramax/98c886c2-11a5-48fa-bcd9-378e1aa0d027&photo_overlay=streetside,panoramax

I noticed that resizing the panellum viewer fixes the blurriness. Here' the [code](https://github.com/openstreetmap/iD/blob/8b68f07/modules/services/pannellum_photo.js#L50) handling the resize event. Just a guess, but perhaps the problem is that while a viewer is hidden it has a size of "0x0", and therefore improperly scales the photos. I stirred around a little bit in the code, and found that switching the following two lines seems to resolve the issue: https://github.com/openstreetmap/iD/blob/b4eaeb3/modules/services/panoramax.js#L489-L490 – @mattiapezzotti can you take a deeper look please?

**Comment by mattiapezzotti** [comment]
I tried to replicate the bug, but I can't get it consistently.
It is something involving the frame, since it is shared between multiple providers; but I am not sure if it is a size issue, since the frame does not actually change if you change services (if you enlarge the frame for panoramax, it will keep the same size for mapillary and bing as well).

Swapping the two lines of code does not seem to work; I will check the frame class better.

**Comment by tyrasd** [comment]
> Swapping the two lines of code does not seem to work

True, it also does not work here for me when testing it now again. I must have been "lucky" that one time. :shrug:

**Comment by tyrasd** [comment]
>  I can't get it consistently.

For me the following does it quite consistently (testing in Chromium v127): Open the above URL -> select the filter to only show 360° photos -> select either a Bing Streetside or Panoramax photo -> resize the viewer a little bit -> click on an image of the other provider -> blurred :boom: .  The initial resize seems to be relevant to trigger this for whatever reason.

**Comment by mattiapezzotti** [comment]
Ok so I think i found the issue, when resizing the pannellum all the hidden pannellum get a 0 width and a 0 height size. I just forced a resize whenever an image gets selected. For some reason this only fixes on Panoramax but not on Bing Streetside, maybe it is handled in another way idk

**Comment by tyrasd** [comment]
> this only fixes on Panoramax

yeah, I would think that a similar fix as #10385 would also be needed for the other street level imagery providers that are not yet using the `panellum_photo.js` module, but instead manage their own panellum scenes. For bing streetside it would be around [here](https://github.com/openstreetmap/iD/blob/develop/modules/services/streetside.js#L822) for example. Or, better, it would be good if these services would be switched to use the `panellum_photo.js` module.

**Comment by danieldegroot2** [comment]
@tyrasd I would like to suggest editing title 'Panoramax' => 'Street level imagery', and reopening this issue.

---

See also
- https://github.com/facebook/Rapid/issues/1736
- [message by A35K (GER-BAV) on OSM World Discord ( `#id-and-rapid` )](https://discord.com/channels/413070382636072960/782592770849505281/1399819730453532773))
