### ISSUE TITLE
Panoramax: Bubble colour has low contrast with Mapilio

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10364]
### How to reproduce the issue?

Ref #9941

Zoom into center of Paris. Try to immediately tell Panoramax and Mapilio apart.
Panoramax (darkblue) only has limited contrast with Mapilio (slightly lighter blue).
This can be difficult, especially for (semi-)colourblind users. (though maybe some can already modify this knowing it should be a different element)

Chrome 127.0.6533.73 on Windows 10

### Screenshot(s) or anything else?

Zoomed out on centre of Paris.
![image](https://github.com/user-attachments/assets/bce10507-f975-4697-bc2c-11dde38c4e6f)
A typical intersection
![image](https://github.com/user-attachments/assets/32667359-384d-4e7b-b335-2427c0700bb3)

### Which deployed environments do you see the issue in?

Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.30.0-dev

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
Yeah, the colors are indeed too similar. I've changed it to the orange used on panoramax.xyz. That one is however also quite similar to another color we already use: the regional streetlevel images from Norway (#9509). I've made that one a more red to solve that.

before: ![grafik](https://github.com/user-attachments/assets/71ddb1a5-78d8-46a5-9785-0d659d53dd7c) :arrow_right: after: ![grafik](https://github.com/user-attachments/assets/e6150ee3-36f5-4a98-99f4-bfb44bcd1e6f)

PS: There's now also a legend in the layer selection UI, so that one can immediately see which color corresponds to which service:

![grafik](https://github.com/user-attachments/assets/4291e012-e759-4f3d-9abf-caff87681113)
