### ISSUE TITLE
Can't load http layer because the request is converted to https

### ISSUE THREAD

**Issue by Nekzuris** [openstreetmap/iD#10427]
### URL

https://www.openstreetmap.org/edit#map=13/43.76229/7.38307

### How to reproduce the issue?

1. Open the editor over Monaco https://www.openstreetmap.org/edit#map=13/43.76229/7.38307
2. Set this custom layer [http://ks3.repetto.org/hillshade_multidirectional_bilinear/{zoom}/{x}/{y}.png](http://ks3.repetto.org/hillshade_multidirectional_bilinear/%7Bzoom%7D/%7Bx%7D/%7By%7D.png)

### Screenshot(s) or anything else?

![image](https://github.com/user-attachments/assets/35ed63fe-cd77-43dc-8d60-da3d8fe1a82a)

I've tried multiple browsers, without extensions, different devices, even my phone, nothing worked.
Other people have reported that it works fine for them.
Might by related to leaflet: https://github.com/Leaflet/Leaflet/issues/7337

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.2

**Comment by Nekzuris** [comment]
Okay, I found the issue, it's the browser settings with mixed content.

Allow it on Firefox in `about:config`, set `security.mixed_content.upgrade_display_content` to false
Chrome: https://stackoverflow.com/questions/18321032/how-to-get-chrome-to-allow-mixed-content

**Comment by danieldegroot2** [comment]
This URL returns an error for me because it is unreachable, and/or prohibited to be accessed outside the country it originates from.

**Attention!**

OpenStreetMap editors should only be used for editing OpenStreetMap data, or for reference in doing such.
They are not a replacement for GIS applications, or a way to view/use/distribute/... proprietary data other than that allowed by the application. Regardless, doing so is likely in violation of their terms of use.

Could you link to the relevant website(s) (e.g. information/metadata/licensing page) for this imagery layer, please?
You seem to be trying to use proprietary data (copyright) which is prohibited in OpenStreetMap.
You should use a [compatible source](https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility).
i.e. any source returned in the right sidebar => layer menu, i.e. BDOrtho.

Monaco does not seem to have any specific indexed, provided, or waived layers
(where agency has allowed or agreed with use)
See also https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe
(country code for monaco should be 'mc')

Or, is this an existing layer not accessible from your country?
Or, is it perhaps a custom server which you use to host i.e. Copernicus DEM or similar?

If it is compatible, but not yet discussed, please discuss it on the community forum and local channels
https://community.openstreetmap.org/
https://openstreetmap.community/
(do not do this if you are unsure about the license)

Also, could you link to your OpenStreetMap profile, please? I do not find a user by your GitHub username.

Questions also raised by description of application used...
![image](https://github.com/user-attachments/assets/62ce2f2c-40b3-4dea-9236-a0a0eb05b569)

**Comment by danieldegroot2** [comment]
Additional context from OSM World Discord
https://discord.com/channels/413070382636072960/574786080197443615/1276574395279736885

> Works fine in JOSM

> bhousel [US-NJ] — Today at 6:22 PM
> yeah for a while Chrome has been moving towards this, it will convert http to https (especially if the page is loaded over https)
> https://blog.chromium.org/2023/08/towards-https-by-default.html

> adlan2001 [MY-JHB] — Today at 7:11 PM
> I think I faced similar HTTP/HTTPS issue. Just that I hosted my own imageries using GeoServer in my own AWS EC2 instance.
> 
> Work fine in JOSM, but not in iD and Vespucci.

**Comment by Nekzuris** [comment]
I'm not trying to use iD as a GIS, sorry for the confusion. The layer is a hillshade of RGE ALTI from the French IGN, and it's perfectly fine to use in OSM.
https://geoservices.ign.fr/rgealti
This layer was previously available directly from ign.fr but isn't currently due to technical changes on their site.

**Comment by danieldegroot2** [comment]
Okay, thanks for clarifying. (edit: original comment now hidden as off-topic)
