### ISSUE TITLE
Remove background imagery `Baden-Würrtemberg DOP20`

### ISSUE THREAD

**Issue by cvzi** [openstreetmap/iD#10486]
### URL

https://www.openstreetmap.org/edit#map=16/49.28448/9.70822

### How to reproduce the issue?

There is currently a layer called `Baden-Würrtemberg DOP20` suggested as the best imagery for the state Baden-Württemberg in Germany. 
In the license url for the layer https://wiki.openstreetmap.org/wiki/DE:Permissions/Luftbild_Baden-W%C3%BCrrtemberg it says that the government agency is checking the license but there is no permission (yet).
This layer should be removed until there is a permission

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.3

**Comment by cvzi** [comment]
Seems this was already removed from the layer index, see https://github.com/osmlab/editor-layer-index/pull/2513 but included in release 2.30.3

**Comment by tyrasd** [comment]
Argh… It was removed from the `sources` directory, but not in the "compiled" [`imagery.json`](https://github.com/osmlab/editor-layer-index/blob/gh-pages/imagery.json).  Turns out another PR in ELI had broken the deploy action in the meantime (see https://github.com/osmlab/editor-layer-index/pull/2513#issuecomment-2395480565 for some additional details). It should be fixed now, and I'll create a new patch release for iD tomorrow.

**Comment by tyrasd** [comment]
fixed in iD v2.30.4
