### ISSUE TITLE
Error while loading iD at https://www.openstreetmap.org/id

### ISSUE THREAD

**Issue by Nekzuris** [openstreetmap/iD#10592]
### URL

https://www.openstreetmap.org/id

### How to reproduce the issue?

Visit https://www.openstreetmap.org/id and open the console:
Firefox: `TypeError: parent.$ is undefined`
Chrome: `TypeError: Cannot read properties of undefined (reading 'throttle')`

I'm not sure if iD is intended to be used with this URL, but everything seems to work except for this.

I think it's because jQuery is loaded in the parent page at https://www.openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.4

### Which browsers are you seeing this problem on?

Chrome, Firefox

**Comment by tyrasd** [comment]
I can confirm the error message, but the problem seems to originate from the integration code on the osm-website [repo](https://github.com/openstreetmap/openstreetmap-website/blob/7b05c1c060f3f85f47413ec7db984180514d3ba6/app/assets/javascripts/id.js#L31). Will look into it to provide a fix for it. Luckily the bug does not seem to hinder the functionality of iD on osm.org.
