### ISSUE TITLE
Nudge with arrow keys

### ISSUE THREAD

**Issue by iandees** [openstreetmap/iD#1348]
A cartographer mapping at the editathon suggested that iD have a "nudge" with the keyboard for fine-grained adjustment to node or way positions.

**Comment by bhousel** [comment]
Closing as stale.  Let's keep the arrow keys for nudging the viewport, not adjusting points.  People can zoom in if they want to do fine adjustments.

**Comment by DavidMetcalfe** [comment]
@bhousel Why not keep nudging for the viewport and allow nudging of nodes or way positions with a modifier key + arrows? Zooming in alone is not sufficient for fine adjustments if we want to constrain the adjustment to a single axis.

**Comment by bhousel** [comment]
> @bhousel Why not keep nudging for the viewport and allow nudging of nodes or way positions with a modifier key + arrows? Zooming in alone is not sufficient for fine adjustments if we want to constrain the adjustment to a single axis.

Oh yeah I've thought about this more and I like what other drawing programs like Illustrator do.  To the extent that we can, we should just do whatever they do.

However I also don't have a ton of energy to work on new features for iD, so I'm setting boundaries with my time and only working only on things that I think will matter in the long term.  Right now my focus is on splitting up the iD code into pieces, so that we can make it easier to develop new map editors and other tools.

**Comment by DavidMetcalfe** [comment]
All good. If I find the time, I might have a go at a rough implementation as well.

**Comment by 1ec5** [comment]
In a drawing program, the canvas is typically aligned so that you’re more likely to want to nudge directly up/down/left/right. I think nudging would still be useful in iD but a little bit more frustrating than in a drawing program, because often you’re trying to move something more diagonally. For example, you might trace a building’s roof from aerial imagery, then move the area diagonally to align it to the building’s foundation.

Canvas rotation shouldn’t block a nudge tool from landing, but consider this a nudge to anyone who’s interested in tackling #4954.
