### ISSUE TITLE
Warn before deleting a member of a relation [$15]

### ISSUE THREAD

**Issue by yvecai** [openstreetmap/iD#1461]
User can delete a relation member without warning.
Either deletion should not be allowed at all, or an explicit message should pop.

**Comment by malenki** [comment]
In the German OSM Forum I created [a thread][1] to collect issues matching this topic.
During the last ten days the following was reported:

 * [Holes in two route-relations][2] by deleting way 26437943
 * [Two broken boundary relations][3] by deleting way 31751249.
 * [Boundary of Vietnam broken][4] by deleting way 284917953 
 * [MP broken by deleting outer way][5] by deleting way 316233710 


  [1]: http://forum.openstreetmap.org/viewtopic.php?id=29097
  [2]: https://www.openstreetmap.org/changeset/27198654
  [3]: https://www.openstreetmap.org/changeset/27703195
  [4]: http://www.openstreetmap.org/changeset/27645747
  [5]: https://www.openstreetmap.org/changeset/27804739

**Comment by malenki** [comment]
* [outer way of MP deleted][1]
* [outer way of another MP deleted][2]



  [1]: http://osm.mapki.com/history/way.php?id=128164904
  [2]: http://www.openstreetmap.org/way/263216117

**Comment by Nakaner** [comment]
New examples are:
* https://www.openstreetmap.org/changeset/28025148
* http://www.openstreetmap.org/changeset/27767580

This issue is already open. The German community is happy that new users join OpenStreetMap every day but the price we (the mappers) pay reaches its upper limit. Relations break easily if the editor does not warn its users. Relations are important for geocoding (boundary relations).

README.md says:
> It lets you do the most basic tasks while not breaking other people's data.

This is wrong at the moment. Please keep this in mind that iD exists to help the community, not to harm it.

iD is [still](https://github.com/openstreetmap/iD/issues/542) (thank you for fixing it) the synonym for bad changes. The German mapping community expects you to fix this issue. It is almost two years old!

I suggest you to:
(1) either prevent such damaging relation-related changes 
* by disabling deletions of ways which belong to relations
* by disabling deletion of whole relations
* by disabling splitting and merging of ways which belong to a relation (not necassary if iD already cares about this)

(2) or add methods to ensure that edits do not break relations
* by good visible warnings during editing that the user breaks something (kerosin [proposed nice texts](https://github.com/openstreetmap/iD/issues/2503#issue-53966817))
* If the user presses "ignore, I'm an expert", he should see another warning (like the current one below changeset comment field) which warns "You are going to upload one defect multipolygon. [Repair/Show]() | [Ignore]()" and below all warnings "Ignoring warnings might get you into truble with the community." (you might use a more friendly text)

**Comment by PolyglotOpenstreetmap** [comment]
I fully agree with Michael Reichert's message. It could, of course, also be
route and other types of relations, which are being broken.

How difficult can it really be to show a warning message to users? And if
design decisions are not contributing to improvement of the data, they'll
have to be reconsidered.

Polyglot

2015-01-19 17:13 GMT+01:00 Michael Reichert <notifications@github.com>:

**Comment by brycenesbitt** [comment]
iD is positioned as the easy editor meant to bring beginners into OSM editing.  As such this is a big deal.  An iD user who breaks something is having a bad experience, not to mention the people who have to come after and fix it up.

**Comment by malenki** [comment]
- Way 263216117 [got deleted][1] in [changeset 27938908][2], thus leaving an MP without "outer" way
 - Way 321167794 [got deleted][3], breaking administrative boundaries
 - the same with [way 88170786][4] in [changeset 27767580][5]
 - the same with [way 169707074][6] in [changeset 28410448][7]
 - the same with [way 34733073][8] in [changeset 28539851][9] 
 - the same with [way 54582818][10] in [changeset 28706773][11]
 - in [changeset 27771827][12] several ways get deleted thus removing them from a hiking route
 - the same with [changeset 27790997][13]


  [1]: http://www.openstreetmap.org/way/263216117
  [2]: http://www.openstreetmap.org/changeset/27938908
  [3]: http://www.openstreetmap.org/way/321167794
  [4]: http://www.openstreetmap.org/way/88170786
  [5]: http://www.openstreetmap.org/changeset/27767580
  [6]: https://www.openstreetmap.org/way/169707074
  [7]: https://www.openstreetmap.org/changeset/28410448
  [8]: http://www.openstreetmap.org/way/34733073
  [9]: http://www.openstreetmap.org/changeset/28539851
  [10]: http://www.openstreetmap.org/way/54582818
  [11]: http://www.openstreetmap.org/changeset/28706773
  [12]: https://www.openstreetmap.org/changeset/27771827
  [13]: https://www.openstreetmap.org/changeset/27790997

**Comment by Skippern** [comment]
With Changeset comments I think it is a more bad experience for the beginning user getting complaints from us who are maintaining areas, then a warning banner when they are about to break something.

When I see change sets with **bad** data I do not check to see what editor they use or how much experience they have, I quickly post a comment on the changeset informing them about the damage and kindly ask them to fix it themselves. I think if iD gave a friendly warning at the time of edit, the beginners would be aware of the situation instead of getting an (at times) angry message from some total stranger.

Often it is the same users I see doing the same mistakes or damages within the area I monitor, and almost always it turns out to be done with iD.

**Comment by Skippern** [comment]
In a relatively short editing spree, a somewhat experienced user broke several relations I had used a week or so putting in place. This *experienced* user are mainly using iD, and instead of iD notifying him when breaking relations, I have to do that job and remind him. This user edits all over Brazil, not only the area I monitor, so it is likely that he have broken even more relations without me noticing. I've had enough of reminders to him, and are just about starting to revert any changeset he touches containing relations, either until iD sort things out with themselves, or this user changes to a **proper** editor.

Lists of change sets for today:
* [28772895](http://www.openstreetmap.org/changeset/28772895) - See discussion with user in Portuguese.
* [28763811](http://www.openstreetmap.org/changeset/28763811)
* [28771057](http://www.openstreetmap.org/changeset/28771057)
* [28771413](http://www.openstreetmap.org/changeset/28771413)
* [28771622](http://www.openstreetmap.org/changeset/28771622)
* [28777518](http://www.openstreetmap.org/changeset/28777518)
* [28777467](http://www.openstreetmap.org/changeset/28777467)
* [28772181](http://www.openstreetmap.org/changeset/28772181)
* [28773889](http://www.openstreetmap.org/changeset/28773889)

**Comment by naoliv** [comment]
I pay another cake for whoever fix this.

**Comment by tmcw** [comment]
Since a few people asked for context that would be useful if they wanted to solve this issue:

## User Experience

Going to assume / best guess that the desired UX is

* click on feature within relation to delete
* click delete
* have to confirm whether you want to delete a member of a relation

This brings up the issues that

* deleting members of relations repeatedly will be a chore
* lots of objects are in relations and _should_ be deletable without incident.

Would love to see clever solutions to those.

Anyway

## The code:

* [the code that encapsulates a delete operation in terms of when it's available, the history annotation it provides, and how it appears in the ui](https://github.com/openstreetmap/iD/blob/master/js/id/operations/delete.js)
* [the code that actually deletes an object](https://github.com/openstreetmap/iD/blob/master/js/id/actions/delete_multiple.js)
* [a previous commit that disabled deleting incomplete relations](https://github.com/openstreetmap/iD/commit/da9602795cdc0585e5ec2ce74617eb4d822f27ec) that would be good as example of the kind of change
* [the modal component](https://github.com/openstreetmap/iD/blob/60af39c7da0be3df17ee2b8257469bbbaeff283f/js/id/ui/modal.js) and [an example of its usage as a yes / no confirmation](https://github.com/openstreetmap/iD/blob/60af39c7da0be3df17ee2b8257469bbbaeff283f/js/id/ui/restore.js)

Basic jist would be to hook into [the delete operation](https://github.com/openstreetmap/iD/blob/60af39c7da0be3df17ee2b8257469bbbaeff283f/js/id/operations/delete.js#L5), [check to see if the things being deleted have parent relations](https://github.com/openstreetmap/iD/blob/60af39c7da0be3df17ee2b8257469bbbaeff283f/js/id/core/graph.js#L66-L68), and ask for confirmation with an iD.ui.Modal if so.

**Comment by systemed** [comment]
Right. The PR I've submitted above is pretty much the same, but it requires the user to expressly remove the way from the relations rather than using a modal, because (he says glibly) modals are often not great UI - experience with P2 is that people just click whatever gets the modal out of the way fastest.

By prompting the user (in the tooltip) to expressly remove the way from the parent relation, it makes clear what's happening, giving the opportunity for a "wait, maybe I don't want to do that" moment.

**Comment by naoliv** [comment]
@systemed seems a good approach

**Comment by Skippern** [comment]
@systemed I like that approach. That is slightly stricter than the approach in **JOSM**, I cannot vouch for how it is done in other desktop editors, **Go Map!!** have completely disabled deleting and cutting, so there is no risk for this, and I guess other mobile editors follow the same line (also not fully to my knowledge). It is actually tempting to install **Merkaartor** to see how it is handled there.

**Comment by jfirebaugh** [comment]
Fixed by #2526. @bhousel and @naoliv, I'll leave it to you to arrange cake delivery to @systemed.

**Comment by bhousel** [comment]
sweet! :cake: 

@systemed can go to [bountysource](https://www.bountysource.com/issues/903043-warn-before-deleting-a-member-of-a-relation), claim his $15, then buy a cake.

Or you can also buy something else, or pay it forward to another opensource project if that's what you want...

**Comment by naoliv** [comment]
I've sent him an e-mail asking the best way to pay my part.

**Comment by yvecai** [comment]
Congratulation to all, lobbyists, bounty hunters included :)

On 12 février 2015 20:17:55 UTC+01:00, "Nelson A. de Oliveira" <notifications@github.com> wrote:
>I've sent him an e-mail asking the best way to pay my part.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openstreetmap/iD/issues/1461#issuecomment-74133622

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by ftrebien** [comment]
I don't think this has been properly handled yet. The user cannot DELETE a way that belongs to a relation, but he/she can still combine that way with other ways without getting any warning saying the relation (that was previously fine) makes no sense at all after combining its members. Just tried on a bus route and a district boundary, all I needed to do was to combine two streets, one member to a relation, the other not a member. The resulting relation has the combined way as a member, which would be ok if the user got a warning that the relation could become broken. JOSM handles this very nicely by warning the user and letting him/her choose to accept or not the consequences. In the way iD currently handles this, the user never knows that he/she has broken something. I see a pattern here: issue 2358 is analogous, but for tags. How hard is it really to just display a warning for the users? I'm sure nobody has the intention of breaking data, so why be against adding a simple warning?

**Comment by PolyglotOpenstreetmap** [comment]
I totally agree with you. It seems like the developers op iD either don't
understand the data model of OSM, but why would one want to develop an
editor of said data without understanding it?

They seem to have 'principles' which according to them are more important
than the data. But in reality nothing is more important than the data, when
you're developing an editor for it. The data and the time wasted by other
users who constantly need to patrol and try to mend everything broken by
users of an editor which is really broken.

So, I'll keep trying to convince users to start using a real editor as
quickly as possible, as iD is really doing them a disservice. One of these
days I'm going to get on my soapbox and write a blog entry about it. It's
really unbelievable this is still a problem, after all this time.

Polyglot

2015-06-26 9:40 GMT+02:00 ftrebien <notifications@github.com>:

**Comment by systemed** [comment]
@ftrebien @PolyGlotOpenstreetmap thank you for reminding me why I was so relieved to step down from maintaining the default OSM editor. (Basically, you two were the reason.)

**Comment by tmcw** [comment]
This issue, titled "Warn before deleting a member of a relation", is closed, because iD warns before deleting a member of a relation. If you'd like to continue insulting the volunteers who make this free and open source editor so that you can use it, do so on the correct ticket, #2358, or, even better, become one of them and stop trolling.

Locking this ticket.
