### ISSUE TITLE
Empty Changesets

### ISSUE THREAD

**Issue by EdLoach** [openstreetmap/iD#1483]
Causing no harm, so low priority, and I've not been able to reproduce the behaviour after spotting http://www.openstreetmap.org/browse/changeset/16127242 - I had assumed it would be as simple as adding an object and removing it again, but whether I delete it or click Undo the Save button and Ctrl-S seem to be doing nothing.

**Comment by bhousel** [comment]
It's easy to create an empty changeset by editing only tags that eventually get stripped by [iD.actions.DiscardTags](https://github.com/openstreetmap/iD/blob/master/js/id/actions/discard_tags.js).

e.g. add a tag like 'created_by' and save.

Because #2611 will introduce another way of creating an empty changeset (make an edit that conflicts with another user and choose not to save it), I'm going to add some guard code to save.js to prevent empty changesets from getting saved.
