### ISSUE TITLE
Suggest (new and senior) editors to provide a meaningful edit summary

### ISSUE THREAD

**Issue by grinapo** [openstreetmap/iD#1488]
As iD went live lots of people appearig out of nowhere and making (mostly useful) edits. What I have observer was that the edits with (empty) summary skyrocketed. This is pretty bad for QA work as we cannot even guess sometimes what the editor wanted to do.

It would be nice to suggest editors to provide a few words about what they were thinking they were doing.

Right now it says "Brief description of your contributions".

I'd suggest something along the lines of ``Please briefly describe your contribution to help fellow editors to easily browse and verify your edits (like "adding POIs around Whateverland",  "adding new roads from satellite imagery" or "fixing road geometry using gps tracks").''

**Comment by fvzmtklj** [comment]
Please make changeset comments mandatory. Good practice should be baked into all software, especially those used by new users most of whom will not be bothered to read the wiki.

This is a critical issue that's eating up time and resources for mappers that could be doing more productive things.

**Comment by fred702** [comment]
This problem is not going away. Like JOSM, iD should pester users to input *something* so at least they realize their behavior is contrary to community standards. Instead, many new users are treating empty comments as the norm. I appreciate how accessible iD has made OSM, but the defaults really need to be more beneficial to the community.

Here are just a few examples.
https://www.openstreetmap.org/user/thisishap/history
https://www.openstreetmap.org/user/RVA_101/history
https://www.openstreetmap.org/user/JudeD/history
https://www.openstreetmap.org/user/llee4PRI/history
https://www.openstreetmap.org/user/mtblocal1/history
https://www.openstreetmap.org/user/Hobgoblin3/history
https://www.openstreetmap.org/user/formula155/history
https://www.openstreetmap.org/user/crshortt/history


There's also the problem of creating too many changesets per editing session, but that's another issue.

**Comment by jfirebaugh** [comment]
@fred702 Have you tried reaching out to any of those users with a friendly note explaining how the community uses edit summaries and what a good one looks like?

**Comment by fred702** [comment]
@jfirebaugh I have, but that approach doesn't scale given the size of the globe and rate of new users. Perhaps Mapbox could hire some more employees to handle that task.

**Comment by bhousel** [comment]
Given what a distraction this issue has become, I've decided to just add the code so that the save button is disabled if there is no comment and enabled if there is some text in the comment.
