### ISSUE TITLE
Display photos on map

### ISSUE THREAD

**Issue by datendelphin** [openstreetmap/iD#1502]
A popular way of taking notes while mapping is by taking pictures. But in order to efficiently use those notes, the pictures should be shown on the map where they were taken.

There are cameras which already record GPS position, there the exif tag could be evaluated.

The more precise way to locate pictures on the map would be by correlating them to the GPS trace with the recorded time.

**Comment by simonpoole** [comment]
@bhousel Just to give another use case where having drag and drop of fotos would make things far easier:  the typical mapping party with limited outbound bandwith (so uploading to mapillary is too slow, which it likely is in any case in a time limited event scenario) and the mappers have a variety of equipment in use (so upload would require copying to the desktop and using the mapillary upload scripts). 

Copying pictures to the desktop and then dragging and dropping them to iD to see location and orientation would be so much simpler than firing up JOSM (with the requiste instructions and so on).

**Comment by bhousel** [comment]
@simonpoole I agree about the usefulness of the feature, and nobody is against the idea of supporting drag-and-drop local photos onto iD, we just don't have the developer bandwidth to make it happen right now.. You are the only person since 2013 who has brought it up.   

That said, we have more people contributing to iD lately who might be looking for a project to take on, so I'll reopen for now and maybe somebody will pick it up and implement it.  If that happens, I'd happily merge a PR.  That would require:
 
- [ ] add layer 'local photos' which works like 'local gpx'
- [ ] add dragdrop handler
- [ ] vendor in the exif parsing library
- [ ] make sure the existing dragdrop handler that handles gpx files is ok
- [ ] add rendering code and css for the images thumbnails maybe using mapillary markers as inspiration

**Comment by hctomio** [comment]
The possibility to add one geographic photo once a time would already help with our edits.
As is done with the tracks.

**Comment by joepie91** [comment]
> I agree about the usefulness of the feature, and nobody is against the idea of supporting drag-and-drop local photos onto iD, we just don't have the developer bandwidth to make it happen right now.. You are the only person since 2013 who has brought it up.

Just putting in my +1 here - this would be very useful for me. I'm a semi-hobbyist mapper; I do occasionally take a GPS track (through OsmAnd) and I collect photos of simple things that I want to add in iD later (benches, trashbins, shop information), etc. - but it very much needs to remain a hobby for me, and I don't want to invest a lot of time into learning a complex editor with non-obvious UI, making iD pretty much the only suitable option for me that I've seen.

I'm currently working around it with a [tool that I quickly threw together](https://geojson.cryto.net/), but having to drag-and-drop GeoJSON files and then constantly needing to match them up to the originating photos is still surprisingly much hassle, and it turns this sort of data entry into a "when I get around to it" sort of thing rather than "right when I get home". It would make it a lot easier if I could sidestep the "handling two related files" process and just drop photos on the map directly.

I might have a stab at a PR for it myself at some point, but can't promise anything - like I said, it needs to remain a hobby for me :)

(Especially considering the widespread ownership of GPS-capable smartphones nowadays, this could probably be considered more of a beginner feature now than it might have been when this issue was originally created.)

**Comment by simonpoole** [comment]
@tyrasd I've added a GSoC project for this https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2022/Project_ideas#iD_editor It would be nice if you could potentially mentor it.

**Comment by pedjas** [comment]
It is year 2022 and this is still not resolved?

Mapillary is now commercialized and out of picture. We do need simple way to see locally saved georeferenced photographs to get info that we need to insert into map.

**Comment by tmcw** [comment]
I still get notifications for these issues, and am not particularly involved in the project anymore, but here's my 2c:

Since 2013, thousands of pull requests have been merged into iD. Maintainers have come and gone, and the same with funding sources. Lots of work has happened, and people have poured time into it.

There are a few issues like this one, discussed for years, almost a decade. The discussion of the opening hours field in #974 is an epic. Almost 50 comments. Lots of folks surprised it hasn't been fixed, and throwing in their opinion that it should be simple to fix. Years of comments.

The answer is this:

A project like this has a few maintainers who have limited time and resources and they try to work on the absolutely most-critical, highest-return-on-investment issues they can. There's some wiggle room in judging what's important and what's not, but if you look at the [CHANGELOG](https://github.com/openstreetmap/iD/blob/develop/CHANGELOG.md), well, a lot of that seems pretty important. Security fixes, fixes to the essential tagging infrastructure, and so on. It's hard to pick something in the changelog that seems unimportant or not worthwhile.

Outside of maintainers time, there are some contributors, who care deeply enough about a feature to implement it, and they contribute that feature or change. If you look at the contribution graphs, there are people like Thomas Hervey, who worked on KeepRight support. That certainly wasn't easy, especially with having to onboard onto the project and learn all the conventions and get all the PRs reviewed and merged. But he and others have made the commitment to get it done.

But issues like this one, and like opening hours, don't get finished for the simple reason that nobody does them. They're big chunks of work that aren't critical enough to be a priority for maintainers. And the people who want them enough to ask for them in the issue tracker - well, they don't want them enough to put in the work and implement them, or they don't have the skills, or don't want to put in the work to acquire the skills to implement them.

That's just how it works out. These issue threads could have 50 comments, or 500. It doesn't really matter how many comments there are. Until someone does it, it won't be done.

**Comment by simonpoole** [comment]
It should be noted that this years GSOC projects included one working on this issue. Not sure how far it has progressed, but one way or another we'll find out soon.

**Comment by JesseWeinstein** [comment]
Is this not mostly handled by StreetComplete's feature that lets you take a picture when adding a note, and stores the resulting pictures only until the note is resolved?

**Comment by simonpoole** [comment]
Nope. This is mostly about -not- having to rely on a service provided by a third party.

**Comment by nontech** [comment]
Hey all, as part of GSoC 2022, I added this feature. 
You can have a look at - [PR 9291](https://github.com/openstreetmap/iD/pull/9291)

**Comment by tyrasd** [comment]
The work on this which was started during last year's gscoc project (#9291) and has now finally been fully implemented in iD:

<p>
<img src="https://github.com/openstreetmap/iD/assets/1927298/3b09cfe3-006e-4c5c-95be-a179fb23667c" width="350"/>
<br>
<img src="https://github.com/openstreetmap/iD/assets/1927298/295ad78a-d4df-41ac-9d53-905520f736c2" width="450"/>
<br>
<img src="https://github.com/openstreetmap/iD/assets/1927298/d9c37298-5961-4759-8e92-6125f2d241ea" width="450"/>
</p>


This works for jpegs (and in theory also pngs) which have a gps location metadata in their EXIF metadata. Georeferencing photos using a GPS trace would be nice to have in the future, but as it is possible to do that using [external tools](https://wiki.openstreetmap.org/wiki/Geotagging_Source_Photos), it's not crucial functionality at the moment.

**Comment by joepie91** [comment]
Excellent news, thanks @nontech for implementing it!

**Comment by pedjas** [comment]
Great! Man, this is awesome!
