### ISSUE TITLE
disable merges that would damage relations

### ISSUE THREAD

**Issue by jfirebaugh** [openstreetmap/iD#1512]
Certain merge operations are unambiguously wrong, e.g.:
- merging ways participating in the 'from' and 'to' roles of a restriction
- merging ways that are members of different multipolygon relations

We should investigate if it is possible to reliably distinguish such merges from safe merges, and disable the operation in those cases while providing a message in the tooltip explaining why it's disabled.

**Comment by bagage** [comment]
Would these uses cases be disabled as well:

* merging ways of different types (`highway=secondary` and `highway=residential` for instance) 
* merging items of different names (both names not empty)
* merging ways of different speed limits

Actually, most merges where values are different should not be done without warning the user first?

**Comment by jfirebaugh** [comment]
@bagage: you're looking for #2358.

**Comment by jfirebaugh** [comment]
Note that this is already partially implemented: many cases where merging would damage relations are already prohibited by iD. This issue is still open because the behavior could be extended to cover more cases.

**Comment by AntMadeira** [comment]
Hi there.
I've just read https://github.com/openstreetmap/iD/issues/1461 and https://github.com/openstreetmap/iD/issues/2358 and got here, which is exactly the problem I want to bring about (again). I hope it is ok. If not, please move it to a new issue.

Recently, there were 8 editions in Portugal which damaged major relations. This was done by a mapper that merged ways and changed those relations unwittingly (I presume). Even I have to pay a lot of attention when merging something, because there's no warning about merging elements which belong to different relations. and I know I damaged some relations in this way when I started mapping with iD.
I think this is a huge flaw and should be tackled to prevent further damaging to OSM data all over the world. If iD already warns about deleting relations or part of relations, why not warn when there's a merging going on?

Regards.
