### ISSUE TITLE
Follow a path

### ISSUE THREAD

**Issue by oskarlin** [openstreetmap/iD#1614]
In other mapping software like ArcGIS and OCAD there is an option for following a polyline/polygon when creating a new object instead of adding all nodes one by one.

This function would be amazing and time saving if iD had it!

**Comment by bhousel** [comment]
I'm reading this issue as being like the Follow Line feature in JOSM/Potlatch2.

**Comment by int-ua** [comment]
Looks like it should be enough to just select first and last node you want from a path segment, isn't it? Maybe three nodes if it's a closed shape to determine direction.

**Comment by Thue** [comment]
bhousel made a good point in IRC, which deserves consideration, so I want to preserve for posterity: "it could just be a key that connects the next point, and you can repeatedly press it to connect more points."

**Comment by 1ec5** [comment]
The logic in #3539 for staying on the same line will come in handy here.

**Comment by grischard** [comment]
https://josm.openstreetmap.de/wiki/Help/Action/FollowLine has  an example of how this works in JOSM.

The DWG has recently been in discussions with an user who was mapping everything as multipolygons, because splitting a way into segments and building an MP in iD is easier than manually following big parts of another line. Having this feature would directly help this user's mapping.

**Comment by IcyMidnight** [comment]
I've come across some mapping tasks for this as well. It would be nice to click a node (A) on a complicated poly, click the next node (B) and tap some key (f for "follow"?) and have new nodes added to follow in the direction A->B->....

**Comment by slhh** [comment]
We should also support to follow a path with constant distance. Otherwise, we would encourage users to glue landuses to highways.

**Comment by BjornRasmussen** [comment]
I have an idea for how this could be integrated well into the current UI: 

Start drawing a line like this, and then `shift-click` on the the point farther along the way you want to follow:
![image](https://user-images.githubusercontent.com/37753777/57037501-565c7380-6c25-11e9-996d-39857b84722b.png)


The result would look like this:
![image](https://user-images.githubusercontent.com/37753777/57037517-5f4d4500-6c25-11e9-81ea-4e282cc962ab.png)

The behavior would also work when drawing areas.

This is different from JOSM where you just click F to continue drawing along the current way, but it seems like a better solution for iD since users would not have to hold down F for a certain amount of time.

**Comment by famo** [comment]
> I have an idea for how this could be integrated well into the current UI:
> 
> Start drawing a line like this, and then `shift-click` on the the point farther along the way you want to follow:

Looks like a very sane and time efficient method to me. I would really like to see this implemented in iD! 😃

**Comment by kaligrafy** [comment]
Here is a [patch](https://gist.github.com/kaligrafy/c7b907a4cf6bf7866b46ca6a9c2a2600) and two gist: one for the [action](https://gist.github.com/kaligrafy/5ad25e6a4ce1e0809623f1fac7700501) and one for the [operation](https://gist.github.com/kaligrafy/886b25c24a73195b05b9d3ba33e99894).
This patch and code is for the v3_prototype branch.

You must first select the target way (the one that will follow the source way), then the source way, then the starting point, then the ending point. There must not be any other point between the start point and end point on the target way, and both points must be connected to both the source and target ways. I did not create an icon in the toolbar nor any test or specs yet, but it is functional until someone finds the time to complete the code.

**Comment by quincylvania** [comment]
@kaligrafy Looks cool! Could you create a branch and draft pull request for what you've done so far? It's hard to work with code in gists.

Also, we're not updating the `v3-prototype` branch so this will need to go into `develop`, but only a few minor changes are needed for that.

**Comment by kaligrafy** [comment]
OK, I'll try with the develop branch and add a pull request. I tested it a bit more this morning. It works most of the time, but there can be some issues when following can be done on two sides.

**Comment by quincylvania** [comment]
@kaligrafy Let me know if you need any assistance! I can help with the code issues once the PR is up.

**Comment by kaligrafy** [comment]
I am working on a second action called smooth to add automatic curves to lines. When I'm done with it, I will review the code and provide a pull request for both actions.

The follow action does not work all the time (it fails when there are two sides to choose from or when the first point and last points are the starting and ending nodes of the target line). I will try to fix them.

I have a question: where is the code that loads the icon for the action? Where should I put the svg icon and where can I link it to the action? Thanks!

**Comment by kaligrafy** [comment]
Now the gist is fixed for any kind of ways for source and target (closed, not closed, clockwise, counterclockwise) and no need to select the two intersecting points if there are only two between the source and target ways. I will post a pull request soon.

**Comment by quincylvania** [comment]
> Now the gist is fixed for any kind of ways for source and target (closed, not closed, clockwise, counterclockwise) and no need to select the two intersecting points if there are only two between the source and target ways.

Great! Looking forward to the PR.

> I am working on a second action called smooth to add automatic curves to lines.

Sounds interesting, but please make a separate PR since it's not related to following a path. 

> Where should I put the svg icon and where can I link it to the action?

Simply put the file under [svg/iD-sprite/operations/](https://github.com/openstreetmap/iD/tree/develop/svg/iD-sprite/operations) with the operation ID and it will be loaded automatically. Don't worry about the icon too much, we can work on that later.

**Comment by kaligrafy** [comment]
Manual:

- First select the target way (the one that willl follow)
- Then select the source way (the one to follow)
If only 2 points intersect both the source and target ways, just press the F key.
If more than 2 points intersect both source and target ways:
- Add the starting intersection point to the selection
- Add the ending intersection point to the selection
- Press the F key.

**Comment by pardthemonster** [comment]
@kaligrafy: Any plans to resolve conflict PR [#7649](https://github.com/openstreetmap/iD/pull/7649) or rather re-implement this greatly needed feature on the latest iD?

**Comment by kaligrafy** [comment]
Well, unfrotunalty, I don't have the time right now to do that, but fell free to try to fix it if you think it could be usefull on the short term. Thanks!

**Comment by kaligrafy** [comment]
I would keep this issue open, since my method is very different from the merged one. I still think we should add mine too. I use it everyday on my fork.

**Comment by kaligrafy** [comment]
My follow operation can use a beginning and an end points and follow in between, which is way faster on complex polygons. However, the merged version is really useful for short segments though
