### ISSUE TITLE
Add point to line/area feature

### ISSUE THREAD

**Issue by Mashin6** [openstreetmap/iD#1711]
I would suggest adding "Add point" option in the pop-up menu after clicking anywhere on line or area boundary. 

If the line is very long, it gets annoying to scroll and look for not so good visible circle in the middle of the line and then scroll back.

**Comment by OleLaursen** [comment]
What about supporting a modifier key so you could for instance Ctrl-click instead of double click? Or hover and press a key like +?

I often end up adding a bunch of points to refine a way, and double clicking gets really tedious - double click is also bound to zooming, so often I'll ending up zooming instead of adding a point. Potlatch supports shift-click and it works really well for this kind of workload.

**Comment by bhousel** [comment]
> What about supporting a modifier key so you could for instance Ctrl-click instead of double click?

I like this idea... It would be a clever way of solving both this issue and #2272 if holding the modifier key shows what the geometry would look like with the point added at the mouse cursor (using `iD.geo.chooseEdge` to choose where to insert the point), then clicking actually adds the point.  It could work for both ways or areas.

**Comment by bhousel** [comment]
> So either it will be well introduced in Walkthrough and help, or a new menu button would be added.

Closing here, as this is now introduced in the walkthrough, post #3921

**Comment by yaugenka** [comment]
There are a lot of rivers in our country which are drawn very badly. See an example pic attached.
They can be hundreds of kilemeters long, so you can imagine how painful it is to fix them.
Until this feature is done, is there at least some workarrown solution to improve the redrawing? e.g. cut the line and some hidden possibility to delete the entire new piece even if part of it is out of view?
![default](https://user-images.githubusercontent.com/14937001/36762705-fd4db942-1c35-11e8-9985-248f81207041.png)
