### ISSUE TITLE
Add/modify the same tag to multiple selected objects

### ISSUE THREAD

**Issue by smsm1** [openstreetmap/iD#1761]
Would it be possible to select multiple road segments and then to edit the tags for all of the selected items, such as setting the maxspeed or sidewalk tag?

**Comment by mapninja** [comment]
+1 to this idea. Would cut editing time in half on creating building footprints for HOT tasks, like the current Nepal effort.

**Comment by bhousel** [comment]
> Would cut editing time in half on creating building footprints for HOT tasks, like the current Nepal effort.

I was actually doing the same thing last night to test the new release, and I totally agree - we can do better.

I'm bumping this issue and #528 to the front of the my queue, because of the time it can save in tracing building outlines.

**Comment by cromlyngames** [comment]
@bhousel just had to square off then label as building 150 odd buildings in one of the missingmaps tasks. 
Let me know if there's any way I can help on this. Happy to code but coming in cold.

**Comment by sharazam** [comment]
So yeah, what happened to this? It's been a year ... UI wise, it should just auto-apply the last selected type instead of the white, feature-less area. Or at least have an option in the options menu to enable this behaviour.

**Comment by bhousel** [comment]
> It's been a year

Yeah, we've done a lot in the last year, check the CHANGELOG.

> Or at least have an option in the options menu to enable this behaviour.

iD don't have an options menu.  I'm going to add one in #3123, then this feature will have a place to be.

Anyway, we're tracking these issues as priorities on the [project tracker](https://github.com/openstreetmap/iD/projects/1).  I'll get to them soonish.

**Comment by pietervdvn** [comment]
Hello,

What is the current state of this issue? Has work already started on this? If so, where can we find it?

We are willing to spend some time on it - we badly need the feature. This would also mean that the code would be pull-requested back if there is still an interest in this.

However, then we would like a little guidance on how to implement it.

**Comment by bhousel** [comment]
Hey @pietervdvn ... If you really badly need the feature, use an editor like JOSM.

We're really not able to hand-hold new contributors right now.   The dev team is heads-down preparing the v2.15 release, and after that, our focus for the forseeable future will be working on iD v3.

**Comment by pietervdvn** [comment]
No problem, I do understand your sentiment.

is this feature still on the roadmap? (As: if I would be able to figure it all out by myself and send a PR, would it be accepted?)

If not, perhaps this issue should be closed.

**Comment by bhousel** [comment]
> is this feature still on the roadmap? 

Yes

> (As: if I would be able to figure it all out by myself and send a PR, would it be accepted?)

It would be helpful to run your proposal by us first and make sure its compatible with the UI we are targeting for v3.  The new UI already supports adding favorite and recently used presets to the ribbon in the top bar - this might be enough for your needs.  (It's different from literally "applying a tag to multiple objects" but it will vastly speed up mapping of similar features).

**Comment by pietervdvn** [comment]
I've seen that new design already on your staging server, it is pretty cool.

But that is not what we need. We have a custom iD-fork inhouse, we plan roadworks with it. The users would like to select a bunch of streets at once and mark them all as 'construction' and similar.

The very vague and not-thought-out idea ATM is:
- Select multiple features (e.g. roads)
- Figure out which common preset fields they have (e.g. oneway, surface, ...)
- Show what the current values are and how much features have each value
- Offer some option to overwrite all the values for that field

For the 'all-tags' field, something similar
- Show all the tags that any feature has
- Show what values they have and an option to overwrite them all
- Adding a new field in that case would add the tag to all the values.

Perhaps a restriction should be put in place that only features of the same kind can be selected (thus: only nodes, only ways or only areas can be modified as well).

For now, I think that editing multiple relations at the same time is very out of scope for this issue.

What do you think?

**Comment by quincylvania** [comment]
@pietervdvn That sounds fairly straightforward from a general UI perspective. The main consideration right now is that iD is about to undergo significant breaking changes in both its UI and architecture for v3, so it's somewhat risky to tangentially work on big changes to existing components.

**Comment by slhh** [comment]
@pietervdvn 
The option to overwrite should include cloning an existing value to the other elements. In addition the user should be able to override specific values (or missing ones) only. Deleting specific values should also be possible.

> Perhaps a restriction should be put in place that only features of the same kind can be selected (thus: only nodes, only ways or only areas can be modified as well).

Closed way areas and multipolygons should be considered as the same kind.

Some usecases require multiple kinds to be selected, e.g:

- Select a single element of different kind as a template to clone its field/tag values.
- Select all stop positions and platforms of a bus station to keep their tags consistent.

Instead of restricting the selection to a single kind, I would recommend to list existing values separately per feature kind, and also offer controls to overwrite separately per feature kind.

**Comment by 1ec5** [comment]
> a tag which is shared by all objects, but with different values. The value field is shown greyed out as long as it is untouched. Once its value is changed, it is shown as usual and applied to all objects.

This is how I’d imagine the UI would look when selecting multiple features, some of which lack a key or have different values for a key. It’s nothing too novel; just a slavish copy of the standard multiple selection affordance on the Mac, also found in Potlatch and Potlatch 2:

![multiple](https://user-images.githubusercontent.com/1231218/57119820-e8e23d00-6d21-11e9-8bbd-efc1d440d57b.png)

To simplify things at first, I’d imagine we could get away with hiding the fields and even the preset selector. The list of relations could be a union of all the relations that the selcted features are members of. Clicking the back button (or something else?) could take the user back to the list of selected features that exists today.

Some operations would not be possible with this approach, like adding all the selected features to a relation when one of the features is already a member of that relation. But the right way to expose those operations is less obvious than the basic multiple selection UI.

**Comment by BjornRasmussen** [comment]
How about keep the current view that shows the selected objects, and then add an area underneath called `shared tags` that can be expanded by the user if they care about tag

**Comment by quincylvania** [comment]
I'm going to do this for v3, targeting something along the lines of @1ec5's mockup.

**Comment by slhh** [comment]
Before editing multile objects, the user should be really aware which objects are selected. Therefore, I agree with @BjornRasmussen to place an unfoldable tagging section below the normal multiselection list. I like the mockup of @1ec5 for the tagging section, but overwriting or deleting values without viewing them should not be supported. The existing values might unexpectedly contain important information.

Clicking in the Multiple Values field of a key should instead unfold a section below the key, listing one existing value per line, including a delete button per line to delete the specific value. In case the selection contains different geometry types, separate delete buttons per used geometry type should be offered on each line.

Typing in the Multiple Values field should be applied to objects where the key is missing. Dragging an existing value to the Multiple Values field of the same key should be supported to spread the value over the untagged objects.

A special case of Multiple Values is where a single value is either present or not. In this case the value can be shown e.g. in parenthesis instead of Multiple Values, a direct delete or overwriting is acceptable then.

**Comment by quincylvania** [comment]
I did this! Now when you select multiple features the raw tag editor is shown below the selected feature list. Edits are applied to all the features.

The `Multiple Values` placeholder is shown when there are different values for the same key or a key isn't present on every feature. The suggestion list is populated with the existing values, making it easy to review what values you're overwriting. I think this is a good balance between simplicity and safety.

![multiedit demo](https://user-images.githubusercontent.com/2046746/61737933-3685a900-ad57-11e9-9ac1-3a5c69b130ac.gif)

It works especially well after repeat-drawing, when all added features are selected together by default.

![multiedit after repeat demo](https://user-images.githubusercontent.com/2046746/61737934-371e3f80-ad57-11e9-9c70-b0d39296ddd7.gif)

While field and relation multi-editing were mentioned in this thread, the original issue was about tags alone and I'm considering that complete. We can open additional issues for remaining work.
