### ISSUE TITLE
Tutorial edits leaking into live data

### ISSUE THREAD

**Issue by iandees** [openstreetmap/iD#1795]
Not sure if these are really bugs in iD, but I thought I'd point them out. These are all new users that used iD to make edits in the US (specifically Three Rivers, MI) and also in international, seemingly unrelated places.

- http://www.openstreetmap.org/browse/changeset/17046530
- http://www.openstreetmap.org/browse/changeset/17511654
- http://www.openstreetmap.org/browse/changeset/17590046
- http://www.openstreetmap.org/browse/changeset/17694142
- http://www.openstreetmap.org/browse/changeset/17649048
- http://www.openstreetmap.org/browse/changeset/17688847
- http://www.openstreetmap.org/browse/changeset/17736462

Is this park part of the tutorial?

**Comment by SomeoneElseOSM** [comment]
For info, another one:
http://www.openstreetmap.org/changeset/28612726

**Comment by bhousel** [comment]
I was actually just able to save some data from the iD tutorial, but it's tricky!  Here's what I did:

1.  Draw some stuff (e.g. a line)
2.  The tutorial may try to remove your stuff, but you can switch to a different step and switch back before the stuff that you just drew clears away.
3.  Although the save mode click handler is disabled, you can still enter save mode with ⌘-S.. Oops!
4.  There may be a curtain over the save button, but with clever panning and zooming you can get around that.

 
![tutorial_issue](https://cloud.githubusercontent.com/assets/38784/6047121/98ab25c0-ac75-11e4-9d69-bb39e97e5f3a.gif)

**Comment by SomeoneElseOSM** [comment]
One other thought - rather than the method above, is it possible that some of these edits are due to people being left post-tutorial sat over Three Rivers and think that they're still in "test mode" somehow?  These changesets:

http://www.openstreetmap.org/changeset/25610557
http://www.openstreetmap.org/changeset/28475387

don't contain the characteristic "an edit in Three Rivers and then an edit somewhere else". I can't reproduce this though - when I tried editing "for the first time" at a location in the UK I got taken back there as expected at the end of the tutorial.

Of course, people "doodle" in OSM all the time in all OSM editors and arguably having iD restrict initial doodlings makes it much easier to tidy up!

**Comment by bhousel** [comment]
> One other thought - rather than the method above, is it possible that some of these edits are due to people being left post-tutorial sat over Three Rivers and think that they're still in "test mode" somehow?

It could be.. I don't necessarily think the thing I did was how the edits are happening, but we do need to put some more defensive code into the tutorial.

**Comment by SomeoneElseOSM** [comment]
Just for info (in case more examples might lead to an "aha" moment about these) another one:

http://www.openstreetmap.org/changeset/28868015

**Comment by bhousel** [comment]
I think 9cb53a1 will help reduce the amount of confused users.  

Users were likely reloading the page (e.g with Cmd-R) and getting put back into Three Rivers, thinking they are still in the tutorial.
