### ISSUE TITLE
Add exit_to field for highway=motorway_junction objects

### ISSUE THREAD

**Issue by WillPittenger** [openstreetmap/iD#1878]
exit_to is a common key for motorway junction objects.  I figure iD should examine the other end(s) of the ramp in question (assuming the node is the start of a *_link way).

**Comment by 1ec5** [comment]
Adoption of `exit_to`, `exit_to:left`, and `exit_to:right` plateaued in late 2012, whereas `destination` and variants like `destination:ref` and `destination:street` have had much greater momentum since then and are used [much more frequently](https://taginfo.openstreetmap.org/compare/destination/exit_to):

[![taghistory](https://user-images.githubusercontent.com/1231218/28561296-b319aaa2-70d2-11e7-8ed2-6347b441a656.png)](http://taghistory.raifer.tech/)

OSRM developers have [explained](https://www.openstreetmap.org/user/daniel-j-h/diary/40555) why `exit_to` is ill-suited for routing engines. Mappers in the U.S. have known of `exit_to`’s limitations for quite some time; there are junctions where even `exit_to:left` and `exit_to:right` aren’t enough to fully express all the branches’ destinations.

#4178 proposes adding destination fields as an alternative to the feature requested in this issue.

**Comment by bhousel** [comment]
Thanks for the analysis @1ec5 .. looks like #4178 is the preferred way forward 👍
