### ISSUE TITLE
iD seems to allow creation of null-value keys

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/iD#1894]
In this changeset: http://www.openstreetmap.org/browse/changeset/18326575
From version 2 to 3: http://www.openstreetmap.org/browse/way/241884256/history

there is the creation of natural=""

**Comment by danieldegroot2** [comment]
> Yeah, that may be the best route. I was trying fix it in the tag control itself, but that turned out to be tricky, because you want to allow empty values temporarily, while adding a new tag or editing related tags.

@tyrasd If possible, would displaying (soft) warning on save screen be useful as is already done with empty objects?

**Comment by tyrasd** [comment]
@danieldegroot2 Could you please elaborate what benefit such a warning would have? The only one I could think of is when a user had the intention to fill in a particular tag, but then got distracted with something else, forgot about it and never returned back to it. I don't think that's a common enough situation to warrant a dedicated warning…

**Comment by danieldegroot2** [comment]
>  Could you please elaborate what benefit such a warning would have?

A tag is always a key=value pair. If I create a GitHub issue and only fill in the title, it does not allow the user to submit an empty issue. (also, the other way around, when cancelling, it warns data will be lost)

For completely empty objects there is a warning(, preventing upload).

---

A warning for empty values has potential to improve data quality instead of the alternative solutions, which might lower it.
(either they upload low quality data or completely lose [potentially useful data](https://wiki.openstreetmap.org/wiki/Good_practice#Don't_remove_tags_that_you_don't_understand));
some of it may be useless, but an empty object warning also gives option to manually delete individual data.

| Solution | Application | Contributor | Data | Validator(/User) |
| --- | --- | --- | --- | --- |
| Empty object | ❌ hidden | ❔ effort<br/>(recoverable) | ❔ data<br/>(stale, low quality) | ❌effort<br/>(more effort) |
| Delete data | ❌ hidden<br/>(+unfeasible) | ❌ effort<br/>(not recoverable) | ❔ data<br/>(less bad data) | ❌effort<br/>(more effort for i.e. HOT validators) |
| Dedicated warning | ✅ more noticeable | ✅ more aware | ✅(/❔) better quality<br/>((+)less bad data) | ✅(/❔)  less effort<br/>(+might help resolve location of other data) |

(contributor checking data is more valuable then validator checking afterwards with little/no prior detailed (local) knowledge)

> when a user had the intention to fill in a particular tag, but then got distracted with something else, forgot about it and never returned back to it.

...which happens for empty objects too.
(most people do not use a dozen empty objects as guidelines to align buildings like I tend to do, but)
users might add a dozen POI, copy some tags or check later they used correct tag for objects, remove some values, but not be able to fill it all out right away, or forget to (as you mention), or accidently miss, reselecting an object.

> I don't think that's a common enough situation

Well, yes, I agree - it is less common. (it is understandable if the following is a minor inconvenience);

In the long term such editor produces plenty of empty objects. Other editor applications will hide this POI, leaving it as stale data. Other contributors need to take time to figure out what it is or delete it (eventhough a script could be written for this, like for typos); deprecations(/typos) are other minor but common problem in the long term which editor contributes to resolving at contributor-level.

my suggestion was phrased like '(soft) warning' because it sits between warning (something inappropriate which editor will already prevent, i.e. completely empty object) and [low-severity suggestion](https://github.com/openstreetmap/iD/pull/11020) (something which is inaccurate, but not directly inappropriate).

---

There might also be a bug; sometimes completely empty objects might still upload, possibly because validation queue is running (and device is slow);
https://github.com/bryceco/GoMap/issues/851#issuecomment-2884984434 (and iD repo issue linked below it)
(avoiding empty objects can make it easier to tell bugs apart from user error)

---

(sidenote: other editor applications might (fully) allow uploading empty data, but it is assumed this is an independent discussion, and/or there is no concensus this is impossible to prevent / desired behaviour.)
