### ISSUE TITLE
Support Internet Explorer 11

### ISSUE THREAD

**Issue by EdLoach** [openstreetmap/iD#1908]
![idonie11](https://f.cloud.github.com/assets/2599812/1368009/a7f65c36-3974-11e3-867b-ba7138c54cd7.PNG)

Icons don't show. I had a similar issue during the tutorial, which I think meant I got stuck, but other Windows 8.1 teething issues meant my network connection kept dying - taken me about two days to get it stable enough to post this feature after a brief comment on #osm-dev before my network connection first died.

**Comment by bhousel** [comment]
Quick update on this issue... None of the IE versions support referencing an external svg file in a `<use>` element.  However the changes made in #2811 fix this issue, because we now bring the svg sprite file inline: we use `d3.xhr` to load the sprite svgs contents directly into the `<defs>` section.  This allows us to do a bunch of clever css styling tricks on the svg symbols, and gives us IE support as a side benefit.

I'm leaving this ticket open because there is still an issue with oneway markers, and potential fix described in #2571.  But this is awesome that we are very close to being able to support IE11.

**Comment by HolgerJeromin** [comment]
SVG External files are supported in the latest update :-)
http://blogs.windows.com/msedgedev/2015/11/16/introducing-edgehtml-13-our-first-platform-update-for-microsoft-edge/

perhaps this update gives some progress for iD.
