### ISSUE TITLE
Zoom to selected object

### ISSUE THREAD

**Issue by hajo4** [openstreetmap/iD#1998]
Panning is quite slow, so when I need to go any distance,
I tend to zoom out (--), pan to center my target, then zoom in (++).
But often, that still misses the target by a screenwidth, 
and so requires panning again.

It would be useful, if the selected object could be centered after the zoom.
Maybe only as an option, e.g. when zooming with shift.

**Comment by bhousel** [comment]
Closing this because 1. the minimap is draggable to move viewport quickly to a new location and 2. cmd/control key modifiers now allow for faster zooming (with +/-) and panning (with arrow keys).

Also, zooming with the mousewheel will center on wherever the mouse is positioned.  I don't know if it was always this way, or if it's new functionality since I upgraded D3 a few months ago.
