### ISSUE TITLE
incomplete ways after restoring

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/iD#2142]
After #2135 the graph can contain incomplete ways (i.e. ways where one or more of its nodes are not present in the graph - just like incomplete relations) under certain circumstances. For example:

1. Have a multipolygon (or route, …) relation that spans over two data tiles A and B (way w1 is completely in A)
2. while editing in region A, split way w1
3. abort the mapping session, restore from region B
4. the graph will now contain the multipolygon relation, way w1 and the split remainder (say way w-1), but not any of the nodes of w1 and w-1.

I noticed that this causes problems with the current multipolygon code: it causes `entity nxxx not found` exceptions during [`graph.childNodes()`](https://github.com/openstreetmap/iD/blob/master/js/id/geo/multipolygon.js#L80) because some nodes are in fact missing.

I'm not sure how to fix this properly. A possible fix (for the multipolgon case) would be to add something like the following to the [relation member filter](https://github.com/openstreetmap/iD/blob/master/js/id/geo/multipolygon.js#L80):

    … && graph.entity(member.id).nodes.every(function(node) { graph.hasEntity(node.id); });

Another fix would be to include all involved (but most of the time unchanged) childNodes in the localStorages saves. But this would potentially quite blow up the amount of data to be stored.

Also, I'm not sure if similar exceptions could come up in other modules, too?

**Comment by bhousel** [comment]
from @pnorman 
> The nodes and way/full calls are pretty fast now that they're running on cgimap. Could we just fetch whatever we need to complete what's incomplete?

I'm planning to fix this with `nodes` call to fetch the missing nodes. 

from @jfirebaugh 
> iD must block the UI while the nodes are downloaded.

I found with conflict resolution that `nodes` calls are pretty fast (certainly faster than loading tiles, which is what iD would otherwise be doing).  Also I think having iD pause a few seconds after the user chooses "restore" is acceptable.

> Both nodes and way/full are "current state only" -- there's no way to request particular versions or points in time. So we'd need to think about a conflict resolution strategy for cases where nodes were added or deleted. 

Existing conflict resolution will handle added nodes (the user just won't see them until they save and see the conflict resolution UI).  

If the `nodes` call returns that the node has been deleted, I can replace it with a local new node, so the renderer doesn't choke on "entity not found" errors.  Conflict resolution will catch this too and prompt the user whether to keep the node or remove it.

**Comment by bhousel** [comment]
Today I realized:

1. I never actually implemented the "iD must block the UI while the nodes are downloaded." part of this..
2. Adding temp nodes to avoid Entity Not Found errors doesn't work because the temp nodes won't have `loc`, which is essential in a lot of other parts of the code (area/extent calculation)
3. Blocking UI alone is insufficient because the missing childnodes are loaded asynchronously and in batches, triggering map redraws.  So I needed to block both UI and redrawing while these missing child nodes are loaded asynchronously.

This was implemented in a393248, 970a5de and fixes a lot of the Entity Not Found errors that can occur after the user restores their history.
