### ISSUE TITLE
Further country specific customization of address fields

### ISSUE THREAD

**Issue by hlaw** [openstreetmap/iD#2254]
In relation to #2252, using translation to incorporate country-specific placeholder to provide tagging info may work in the case when a language is closely tied to a single country, but not possible in general. Now that we have a vehicle to tailor the address presets per country, I think it would be useful to generalize the `address-formats.json` file a bit to allow further country specific customization - such as:
- placeholders to including country specific tips
- tool tips if necessary for further details (rather than enlarging the fields for placeholders)
- OR a link to the country specific page for address format 
- (relative) width of the fields (currently hardcoded)
- whether a field should be a combo box returning names of nearby features, 
- and if so,
  - what to search for (presently also hardcoded, e.g. addr:city will look for place=city/town/village)
  - probably extent of area to look for place=\* nodes (if using Nominatim) 

Something like (just for example):

``` json
{"countryCodes": ["vi"],
 "link" : [{"vi" : "Vi:Key:addr"}] ,
 "format":[[{"field":"housename", 
                  "placeholder":"Housename",
                  "width" : 1,
                  "combo" : false}] ,
           [{"field":"street", 
                  "placeholder":"Alley/street",
                  "width" : 2,
                  "combo" : true,
                  "matchtags" : ["highway"],
                  "values"  : ["name:vi", "name"]},
            {"field":"city", 
                  "placeholder":"City/Province",
                  "width" : 1,
                  "combo" : true,
                  "matchtags" : ["place=city", "place=province"],
                  "values"  : ["ref", "name:vi", "name"],
                  "Nominatim" : 10}], 
            ...
           ]
}
```

**Comment by 1ec5** [comment]
(Cross-posting from https://github.com/openstreetmap/iD/pull/3639#issuecomment-270469622, since that’s a closed PR with little visibility.)

The Japanese address format added in #3712 is a perfect example of why we need the ability to translate the placeholders on a per-country basis. In Vietnamese, `addr:county` must be translated as “huyện” for Japan. But the same tag is also used in [many other countries](http://taginfo.openstreetmap.org/keys/addr%3Acounty#map) for administrative units that would be translated as “quận”, “hạt”, or “xứ”, where “huyện” would refer to a distinct administrative unit somewhere else in the hierarchy.

**Comment by bhousel** [comment]
(Cross-posting my response 😆 )

Oh yeah I should have updated this ticket, but after looking at #3712, I do understand why this is important. addr:quarter and addr:province just look really out of place in a Japanese address.

**Comment by Natsuyasumi** [comment]
(Also a cross-post)

The whole Japanese address system is complicated. To show this I've made this graph:
```
addr:province                PREFECTURE
                            /          \
addr:county                /        DISTRICT
                          /         /     \
addr:city               CITY     TOWN   VILLAGE
                           |       |    /
addr:suburb               WARD     |___/  
                             \    /
                              \__/
                               |
                              /\
                             /  \ 
addr:quarter            MACHI   OUAZA
                         |         |
                         |         |
addr:neighbourhood     CHOUME      AZA
                             \____/
                               |
                               /\
                              /  \
addr:block_number        BLOCK    \
                          |        \
                          |         \
addr:housenumber      HOUSE NO.    LOT NO. + sometimes LOT NO. EXTENSION
```
It has the common English translations of all fields. As you see the `addr:quarter` and `addr:neighbourhood` have completly different purposes than in other countries. The `addr:province`, `addr:county` `addr:suburb` have different names. And please note that Choume, Block and House No./Lot No. are all numeric, so a `123` placeholder for House No. is completly misleading.

That's why the country-specific placeholders are needed in Japan.

**Comment by bhousel** [comment]
I think this was done in #3643
