### ISSUE TITLE
Unable to re-order existing or new members that belong to a relation

### ISSUE THREAD

**Issue by sogko** [openstreetmap/iD#2283]
According to [OSM wiki](http://wiki.openstreetmap.org/wiki/Relation)

```
 A relation ... an _ordered_ list of one or more nodes and/or ways as members...
```

I'm unable to set the order of relation members through the editor.
I'm not sure if this is because this is not in the current featureset or I might be missing something.

**Comment by bhousel** [comment]
This is a hard problem, but I do consider it a bug.  iD tries to order relation members for you, but I'm not sure if it gets it right, and I'm not sure whether it works for relations like bus routes, etc.

**Comment by 1ec5** [comment]
Only `type=route` relations are documented to have ordered members; by contrast, the order of members in a [`type=multipolygon`](https://wiki.openstreetmap.org/wiki/Relation:multipolygon) relation explicitly does _not_ matter. For multipolygons and probably [waterways](https://wiki.openstreetmap.org/wiki/Relation:waterway) as well, member arranging is a purely matter of tidiness, not correctness.

I was mildly concerned that iD could munge bus routes that backtrack or form loops example, but it appears to have done the right thing in [this changeset](http://www.openstreetmap.org/changeset/32400887) when I drew [a bus route relation](http://www.openstreetmap.org/relation/5171467) that travels over the same road twice.

Whatever the solution to this issue, please keep the automatic member arranging, because as I user I’d never have enough context to be able to rearrange a non-spatial list in spatial order myself.

**Comment by bhousel** [comment]
Thanks for looking into this @1ec5!   

I'll remove the bug label because it sounds like the existing code does handle loopy routes.

For anyone wanting to take a closer look at iD's way joining code, the places to look are:

* [`actionAddMember`](https://github.com/openstreetmap/iD/blob/3f024d0b95e3adf1aba49bd33cf3b528ebee4381/modules/actions/add_member.js#L12), which calls...
* [`osmJoinWays`](https://github.com/openstreetmap/iD/blob/3f024d0b95e3adf1aba49bd33cf3b528ebee4381/modules/osm/multipolygon.js#L78)

**Comment by slhh** [comment]
> I was mildly concerned that iD could munge bus routes that backtrack or form loops, but it appears to have done the right thing in this changeset when I extended a bus route relation to travel over the same road twice.

@1ec5 This is a quite bad example for testing, because it isn't using the current public transport tagging scheme, which is already 5 years old.

The current scheme doesn't use forward and backward roles. In addition the bidirectional part of Coleman avenue, which is used twice, needs to be in the route twice.

According to the current tagging scheme, there are two groups of members:

1. stop and platform roles
2. highway/railway etc. members, which shouldn't use any role.

Within each group the sequence of members is well defined, but any group can come first or the sequences can be merged.
Autosorting is not possible, at least not in all cases, because the sequence of the members within each group contains relevant information.

Merging of two members of the second group is valid, if these members appear in consecutive pairs only (one ore multiple times) and the merged member is placed at all positions of these pairs within second group. This means a stop or platform between the two members to be merged doesn't matter, the merged way can just be placed at any side of it.

@bhousel What does iD do in view of autosorting? Where is the code located?

**Comment by bhousel** [comment]
> What does iD do in view of autosorting? Where is the code located?

My previous comment links to the `osmJoinWays` code.. It seems to attempt join the member ways head-to-tail, but I didn't write that code, and am not familiar with it.

**Comment by quincylvania** [comment]
Is there interest in adding manual drag-and-drop ordering to the members list?

**Comment by bhousel** [comment]
> Is there interest in adding manual drag-and-drop ordering to the members list?

yes definitely 👍

**Comment by bhousel** [comment]
There are probably some good D3 drag-to-sort examples that you can use for inspiration
e.g. http://bl.ocks.org/AlessandraSozzi/9aff786dd04515d6b028

**Comment by quincylvania** [comment]
@bhousel Thanks! Might attempt it this weekend.

**Comment by quincylvania** [comment]
You can now drag-and-drop to reorder!

![drag and drop members demo](https://user-images.githubusercontent.com/2046746/54449094-b9508480-4723-11e9-9f6a-8c52cf6be8fc.gif)

**Comment by BjornRasmussen** [comment]
Moving the relation members from the top to the bottom can get hard when the relation has a lot of members.  Would it be possible to start slowly scrolling the map towards the top or bottom when the user drags the relation member to the top or bottom and then holds it there? 
This would feel very similar to how the "move" feature works in the map area - when you drag a node to the edge of the map, the map moves to let you drop the node off the edge of the map.

**Comment by BjornRasmussen** [comment]
Also, it would be good if a small gap or other indication could be left behind when you start dragging a member to a new spot - once you start dragging the member, it is pretty much impossible to tell where it was before.  This makes returning the member to the right place hard if you had accidentally started dragging it, and it also makes it easier to keep track of how many places you have shifted the member.
