### ISSUE TITLE
Please make the scale bar metric

### ISSUE THREAD

**Issue by valleyofdawn** [openstreetmap/iD#2351]
Or at least double metric/English just like the Mapnik slippy map itself.
This would serve the majority editors, which are not from the US.

**Comment by richlv** [comment]
just for the record - used en-GB in my settings, and it worked.
@rory, if you still get imperial units, check your settings in osm, i believe they override whatever the browser sends.

**Comment by bhousel** [comment]
Yes, iD tries to detect the user's locale from the browser, but this can be overridden by openstreetmap.org settings..  I've found that it is somewhat common for `en-GB` users to have `en-US` in their openstreetmap.org settings.

So anyway I just pushed a change so that now clicking on the scale will toggle the units that it uses:

![scale_units](https://cloud.githubusercontent.com/assets/38784/15216987/7a3831b8-1827-11e6-9271-e493ef1b262b.gif)

Hope this helps some!

**Comment by richlv** [comment]
that's really nice - thank you :)

**Comment by rory** [comment]
I get metres now. When I click on the scale, nothing happens, but I don't care about that feature anyway.

**Comment by bhousel** [comment]
@rory This change hasn't been released to openstreetmap.org yet.  You can preview early features by using the iD here:  https://openstreetmap.us/iD/master
