### ISSUE TITLE
Too many accidental deletions by iD users, please implement some type of warning

### ISSUE THREAD

**Issue by drgweber** [openstreetmap/iD#2452]
Dear Colleagues

I frequently find iD users deleting extensive amount of data. Most of them when queried tell me that they did not notice they were deleting something. 

I do not usually edit with iD, but when I tested deleting something with iD I was concerned that I received no warning at all. I only saw a list of changes, but I guess that if the user has made dozens of changes eventual deletions may not be easily noticeable. 

Here is a recent case:
http://osmhv.openstreetmap.de/changeset.jsp?id=26933417
where we had not other option but to revert.

I can list many more cases of accidental deletions if you like.

Could you please implement a warning feature? Especially in regard to relations?

many thanks for your attention

Gerald

**Comment by drgweber** [comment]
A similar issue may have been discussed in  #1461, #1460, #2014, but the example below shows that the problem remains unresolved.

https://www.openstreetmap.org/changeset/29895207

which is yet another case where a new user in his first and only edit deleted numerous objects.

Please find a way to prevent this. On possibility would be to implement a expertise level, something like a "beginner", "intermediate", "expert". New users could be automatically set to "beginner"  and being prevented to delete any objects, something like that. Users could than change their settings themselves to a higher level when they feel more confident.

**Comment by Skippern** [comment]
I am struggling with another issue with iD, but it might be related to translations and help rather than user level, and that is new iD users creating new ways on top of other ways adding information in `name` or `note` that belong in other tags in the already existing road. For example creating a new way on top of a `highway=residential` with `name=unpaved road` or `name=road without sidewalks`.

Since I am not an iD user I am not familiar with how this information is presented. Either tags such as `surface`, `sidewalk`, etc might be too hidden for new users, or translations (these users are not english speakers) might be vague.
