### ISSUE TITLE
building polygon splitting can create inconsistent data

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#2485]
See https://help.openstreetmap.org/questions/39706/an-error-occurred-while-trying-to-save . Given the maze of polygons that the buildings ended up being, it is unclear what exactly happen, however iD might need to give at least some indication how the user should proceed.

<blockquote>
This is the error message:<br/>
Placeholder Relation not found for reference -6 in relation -3.
</blockquote>

**Comment by bhousel** [comment]
I think this is the same root cause as #3208, which now contains more info, so I'll close here.

Basically we need to reorder the relations that are added to the osmchange file before uploading, to make sure that the relations that appear earlier in the file do not reference relations that appear later in the file.
