### ISSUE TITLE
A half-drawn way is lost if you zoom out too far

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/iD#2499]
You can zoom out too far in iD and it says "Zoom in to edit", but if you were half way through drawing a way, and you decide to zoom out to this level, then your work on the way is lost.

Usually work on one particular way doesn't represent a lot of work, but I noticed this bug when trying to trace this wiggly river for example http://www.openstreetmap.org/edit#map=16/-34.1686/146.6723  (Something which can be a lot of clicking effort, but over a wide-range, and relatively low zoom) 

I guess a good fix would be to let you carry on where you left off, if you just zoom back in.

**Comment by jfirebaugh** [comment]
What's supposed to happen is that there's a message saying "Cannot zoom out in current mode" and the zoom is prevented. Looks like that's working for mouse zooms but not for the +/- buttons.

**Comment by talllguy** [comment]
I've also lost some work this way, as @harry-wood described. I feel like in the past, the error would restrict zooming out further because I used to do a hard pull on the wheel to get to max editing zoom quickly. The error message would display and halt my zoom at the right place. Hope that is helpful.
