### ISSUE TITLE
Add shop=houseware preset

### ISSUE THREAD

**Issue by math1985** [openstreetmap/iD#2509]
Would it be possible to add a shop=household preset?

Example of Blokker, a Dutch household store:

![Blokker](http://www.ijsselmonde-online.nl/nex/sites/default/files/profielen/Virano/blokker.jpg)

**Comment by ImreSamu** [comment]
@bhousel 

I am little bit confused seeing an "Undocumented Tag", 
because I need to write hungarian help about this keys.   :(

my suggestion : no add new keys to the iD Editor without wiki documentation.

----

acording the osm wiki the   Tag:shop=household   ->   "Undocumented Tag" 
* http://wiki.openstreetmap.org/wiki/Tag:shop=household
* http://taginfo.openstreetmap.org/tags/shop=household

the shop=houseware is more frequent tag. ( Description: "Shop selling small household items" )
* http://taginfo.openstreetmap.org/tags/shop=houseware
* http://wiki.openstreetmap.org/wiki/Tag:shop=houseware
* http://wiki.openstreetmap.org/wiki/Key:shop  (  shop=houseware )

**Comment by jfirebaugh** [comment]
Agree, this should be `shop=houseware`, not `shop=household`.

**Comment by math1985** [comment]
I agree, thanks for the correction.
