### ISSUE TITLE
Should not suggest no_u_turn restrictions with the same way as 'to' and 'from'

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#2527]
We are seeing an increase of wrong and unneeded `no_u_turn` with the same way (street) in `from` and `to`.

iD has a nice-to-use and nice-to-click interface, but it's wrongly suggesting and allowing to create these `no_u_turn`s with a single click.
![2](https://cloud.githubusercontent.com/assets/982338/6168127/99e12928-b2a9-11e4-8a2d-0167595a8a18.png)

We are also seeing users creating 4 (four!) `no_u_turn`, one for each street arriving at the crossing node:
![3](https://cloud.githubusercontent.com/assets/982338/6168109/4ca9ebc2-b2a9-11e4-9ed1-88afa68cc6bc.png)

`no_u_turn` like this should not be suggested nor allowed by iD.

**Comment by SK53** [comment]
I dont see why this is wrong. For instance this http://mapillary.com/map/im/QFWuwwDNWWK5X7DJjWLGww location has a signed "No U-turn" but the highway is represented by a single way. Therefore allowing the to and from members of the relation to be the same way seems a sensible way to map the information.

**Comment by naoliv** [comment]
There is a split there. If it's not represented as two distinct ways then it should have at least a [traffic_calming=island](http://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Disland)

What I am saying and seeing is where there isn't any kind of split, separeted ways or islands.

**Comment by jfirebaugh** [comment]
@naoliv As @SK53 suggests, there is noting wrong _per se_ with this type of turn restriction -- there are plenty of places in the world where such restrictions are signed. Are you mapping in a jurisdiction where U-turns are prohibited by default, or the errors you a referring to intersections where U-turns are in fact permitted? In either case I think a better solution is to contact the mappers in question and explain why it is wrong to map the restriction in those particular cases.

**Comment by talllguy** [comment]
In the first screenshot, a U Turn movement would be unsafe (and perhaps illegal) as the driver would be turned against traffic. The southbound traffic would have no expectation of an oncoming vehicle. Most likely there'd be a No Left Turn arrow for that northbound driver, thus also prohibiting the U Turn.

That is why it is (in my opinion) best to leave editors with local knowledge make these judgement calls as the signage on the ground might be more clear.

As for the second screenshot, it is legal in my jurisdiction to make a U Turn there, unless there is a sign prohibiting it. If there is a municipal restriction over a whole area, then it could be appropriate for editors to add those no_u_turn restrictions en masse.

**Comment by Skippern** [comment]
No u_turn to self should be resolved differently than relation, as it would be an action needed for the entire road and not just the intersection. According to Brazilian traffic law it is forbidden to do a u_turn on any part of the road with a completely drawn yellow divider line, the same as for `overtaking=no`. Similar laws exists in most countries. The routing engines should rather start adopting this instead of allowing `no_u_turn` relations to point back at self. If relation is the advised solution for this, than we end up with `no_u_turn` relations about anywhere where a way is split. This topic of self return is better dealt with an improvement of tagging. I suggest disallowing this in editor tools, not only in `iD` (if you absolutely need it most editors understanding relations will allow you to hand draw it and override any tools).

**Comment by naoliv** [comment]
@jfirebaugh indeed it's not _wrong_ but it's inducing users to unnecessarily create `no_u_turn` relations for every highway segment they see (because, like Skipper said, it's forbidden to make U-turns here and they start to map this).
It's comparable to include `bridge=no` in every highway segment, since they aren't bridge.
It's not wrong but clearly unnecessary and unneeded.

**Comment by bhousel** [comment]
I'm closing this issue, as it is common practice to tag any signed restrictions, and `no_u_turn` like the ones described above are frequently signed, at least in many parts of the world.  And having the restriction there doesn't hurt anything.

If it is unnecessary to add these restrictions where you live, I think a better approach is to update the wiki for your part of the world with mapping guidelines, and politely guide new mappers if they make mistakes.

For example, see [what the NYC mapping community does](http://wiki.openstreetmap.org/wiki/New_York,_New_York).

**Comment by jgpacker** [comment]
For future reference: The problem with adding unnecessary relations is that it can make editing these objects harder.

I agree that it makes sense to add such a relation when it is signed like that.

**Comment by naoliv** [comment]
People don't read (or ignore) the messages we send to them (even less they read the wiki or other documentation).
Sometimes we are seeing cases like this:
![U-turns](https://cloud.githubusercontent.com/assets/982338/6690009/7c01c158-cc9c-11e4-83ff-b714d520e10c.png)

Simple residential streets, no signs of any kind but people are adding one `no_u_turn` restriction for every way arriving at a crossing.
People click on the no U-turn icon because it's easily available at the screen.

Could some features not be displayed/enabled for some areas or languages?

**Comment by Skippern** [comment]
I must agree with @naoliv on this, where I edit, 99% of all `no_u_turn` restrictions are not signed, and some people put in totally meaningless turning restrictions. Often cleaning up this takes a lot of time as each destruction have to be manually verified. IMO a first step would be to disallow turning restriction turning back on self, and if really needed allowing it in a form of `expert mode`

**Comment by molotokk** [comment]
The problem with such kind of restrictions is that people startto split long ways in each intersection and creating a no_u_turn restriction on each.  This causes incorrect nam rendering on map.

**Comment by dleonard0** [comment]
I'd like to comment that under [Queensland's road rules](http://www.legislation.qld.gov.au/LEGISLTN/CURRENT/T/TrantOpRURR09.pdf#page=46) U-turns are prohibited at all traffic lights. So it is natural to want to add a no_u_turn restriction, just so automatic routing works. Even though there is no physical sign. A related problem is the existence of physical "U-turn permitted" signs (not uncommon) for which there seems no way to tag.

**Comment by Skippern** [comment]
As several indicates, tags of "U-turn to self" is a result of undesired routing behaviour. Instead of allowing this tagging, routing engines should not have this behaviour, and if they continue with this kind of routing, their routing rules should be fixed, (i.e. bug report to OSRM), and in the rare case where this actually make a sensible routing a way of tagging to support this should be sought ( `restriction=u_turn_allowed` )? These "U-turn to self" in many cases end up as **tagging for the routing engine** which should be considered the same type behaviour as **tagging for the renderer** - instead of adapting the way of tagging to get the desired behaviour out of the routing engine, we should seek the routing engines to fit the way we *should* tag.

Also for cases such as the **Queensland's road rules**, if large area is not treated right in a routing engine, seek to get the routing engine behaviour corrected in their rules, either as a global route, or as a regional rule. I don't think OSRM supports regional routes at the moment, but if enough demand for this exists, I am sure it will be implemented.

**Comment by naoliv** [comment]
It makes me sad to see this in the map:
![](https://cloud.githubusercontent.com/assets/982338/15309569/69cb20ac-1bbe-11e6-9f3d-64ee68832b97.png)

**Comment by SK53** [comment]
I fully appreciate the annoyance of such editing practices for Brazilian mappers. However, certainly in the UK such turns are rarely prohibited & it makes sense that they be mapped **when signed**. I presume the driver for mapping things in this way is the behaviour of routing engines. So what can we do to help folk in Brazil? 

- Document this as clearly as possible on the wiki. I've made a [first stab ](http://wiki.openstreetmap.org/w/index.php?title=Relation%3Arestriction&type=revision&diff=1302921&oldid=1290726)

- Find out which routing engines are causing problems & see if local/regional rules can be implemented. (My garmin can be set to disallow U-turns for instance).

- Create a fork of iD for Brazilian use. How to host this would be another problem.

**Comment by Skippern** [comment]
I have done a lot of routing simulation with Garmin, both with BaseCamp and on a Nüvi50 unit, and no simulation have told me to do u-turn onto same road in intersections. I know the issue might be different with a "missed turn" case, but havn't found a way to simulate this. I have on purpose at times when out driving asked for routing to a different destination than where I am actually going, where the Garmin unit constantly will recalculate the route, though all u-turn scenarios I have encountered until now is going around blocks or similar. "Avoid U-Turn" is not enabled on any of my simulations.

Though I have been instructed to do u-turn back on duplicated highway, where the Garmin unit reads it as two 90º turns with 3 meter distance between. In such cases, if u-turn is prohibited I expect tagging of it.
