### ISSUE TITLE
Remove support for building=* on nodes

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/iD#2529]
iD 1.7.0 allows building=hotel, building=retail and a lot of other building=* tags for nodes.

![snapshot](https://cloud.githubusercontent.com/assets/6830724/6177293/50943a04-b2fd-11e4-9cad-28c5df3139b8.png)

Following to the wiki, building=* is used only on ways, not on nodes.

iD should therefor remove support for building=* on nodes.

**Comment by jfirebaugh** [comment]
The wiki says otherwise. [`building=hotel`](http://wiki.openstreetmap.org/wiki/Tag:building%3Dhotel), [`building=apartments`](http://wiki.openstreetmap.org/wiki/Tag:building%3Dapartments), [`building=school`](http://wiki.openstreetmap.org/wiki/Tag:building%3Dschool), etc. -- all list node as supported.

**Comment by sommerluk** [comment]
@jfirebaugh 

Okay, I see.

When submitting the bug report, I had looked at the german wiki page, where nodes are not allowed.

Now, I see that they are allowed In the english wiki.

Strange difference …
