### ISSUE TITLE
Addresses in Colombia

### ISSUE THREAD

**Issue by angoca** [openstreetmap/iD#2536]
Hi,

I have a website with the address in Colombia. However, they are not complete not precise. I would like to add your editor in my website, by showing a pop-up asking just the right address with all necessary fields. However, I do not want to put the whole iD editor, because it is complex for common users.

I would like you to guide me what parts of the code could be interested for me.

Street addresses in Colombia are quite complicated, and there is a big interest to included this information in OpenStreetMap. By putting the editor in my website, I could increase the correct information in OSM about Colombia.

Cheers

**Comment by jgpacker** [comment]
I believe you are looking for something similar to this: http://onosm.org/
However this simply adds a well-formatted [Note](http://wiki.openstreetmap.org/wiki/Notes) in OSM instead of adding/changing an object.

It's repository is at [osmlab/onosm.org](//github.com/osmlab/onosm.org). You are encouraged to take a look at some forks, such as [sabas/suosm](//github.com/sabas/suosm)
