### ISSUE TITLE
House outlines tend to disappear while editing

### ISSUE THREAD

**Issue by BonzaiThePenguin** [openstreetmap/iD#2539]
Not sure what's up with this, but I was convinced that house outline were hidden *by design* until I noticed they suddenly show up if I pan to specific parts of a map. If I pan even a few pixels to the side the house outlines disappear again.

http://ivideoapp.com/random/OpenStreetMapBug.mov

The further the zoom level, the more likely the house outlines are to suddenly disappear. Unfortunately we kinda need these outlines to figure out which parts of the map still need to be filled out!

**Comment by BonzaiThePenguin** [comment]
Just noticed via https://github.com/openstreetmap/iD/issues/2532 that this is seriously a design decision and can't be disabled. I can't emphasize enough that we need to be able to see the house outlines so we can fill in the missing areas. Also having it linked to the number of buildings visible in the viewport rather than the zoom level is just silly.

![screen shot 2015-02-20 at 7 05 20 pm](https://cloud.githubusercontent.com/assets/1899757/6311629/a79efd34-b933-11e4-8782-79373dbb26be.png)

I guess my recommendation would be to link it to the zoom level rather than object count, and allow people to opt out of automatic hidden features if needed.

**Comment by BonzaiThePenguin** [comment]
Here are two changes I want to make to the project:

1. instead of auto-hiding objects, disable editing for them while continuing to draw them. This may require the addition of non-editable states for house outlines and points of interest, like making the disabled areas light gray and the POIs tiny unclickable dots. Roads should also continue to be drawn at the furthest zoom levels, as right now the map becomes completely empty and tells you to zoom in to begin.

2. link the auto-hide (or auto-disable) behavior to the zoom level rather than the viewport object count. The current behavior felt like an unintended bug to me.

No changes would need to be made to the "visible features" panel, other than perhaps the wording. Editors would still be allowed to explicitly hide certain features (completely disable rendering), and there wouldn't be a need to override the autohide feature since editing at the further zoom levels would be impossible anyway. We just really need a way to view the density of the existing information so we have some way of knowing which areas need more work!

**Comment by jfirebaugh** [comment]
@BonzaiThePenguin -- Sorry for the frustrating editing experience. Let me explain the thinking behind this change.

The existing behavior is primarily due to the limits of rendering SVG in the browser. At a certain density of features, there's just no way that iD can show everything and still be responsive. Poor performance has been a frequent complaint about iD, and so the auto-hiding behavior is an effort to improve that.

Linking the auto-hide behavior to the zoom level has its own disadvantages -- in dense areas, iD would become very slow to respond, while in sparse areas it would end up hiding features that it's perfectly capable of rendering quickly.

An in between state, where features are rendered in a simplified way and non-editable, is a possibility (in fact it's something we've been working on for [large features](https://github.com/openstreetmap/iD/pull/2442)). But it takes time and someone to implement.

I can suggest one workaround that should allow you to see which areas need more work even at zoom levels where iD doesn't display any features: switch to the "OpenStreetMap (Mapnik)" background layer. Then you can see all the buildings that are present, exactly as they appear on official OSM.org tiles.

**Comment by BonzaiThePenguin** [comment]
I did notice that the editor becomes incredibly slow by the time I've added about 100 new objects to the map in a single edit, but haven't experienced slowdown in other areas. Anything I should look out for and possibly help optimize?

**Comment by BonzaiThePenguin** [comment]
?

Also, the OpenStreetMap layer isn't a suitable workaround since you can't use it at the same time as the satellite imagery. It lets me see where houses are currently drawn, but without the satellite overlay I can't see where houses *need* to be drawn. D'oh!

**Comment by bhousel** [comment]
I took a look at some of the feature matching code again today and decided that I probably did lock down the internals a bit too strictly.  So I added an accessor (see 29e1554) to allow future plugins to change the way the feature matching code works.

You can try this now on http://openstreetmap.us/iD/master
Open a javascript console and enter:
```javascript
f = id.features().features();
f.buildings.defaultMax = f.buildings.currentMax = 99999;
id.map().pan([0,0]);   // just a redraw
```

We don't have any plans to change the UI at this time, but hopefully this will give you a workaround so that you can see all the buildings you need to.  If we ever do introduce a plugin system, it would be pretty straightforward to write a "Show Me Everything" plugin that does what the above code does. 

Please let me know if this works for you, and if this issue can be closed..

**Comment by bgirardot** [comment]
Is there any way the feature to auto hide object could be me a preference? I run mapathons and it is very confusing for new mappers and leads to a fair number of duplicated buildings and worried mappers. I also hear similar feedback from others who run a lot of mapathons with new mappers.
