### ISSUE TITLE
Don't add unnecessary `motor_vehicle` tag to highways

### ISSUE THREAD

**Issue by AhmedShawon92** [openstreetmap/iD#2545]
If I add any road with iD editor, there's a tag called `motor_vehicle=yes/no`. But JOSM detects this tag as unnecessary and issue WARNING while validating. I've contacted with JOSM forum and they said "This isn't a JOSM problem. This tag is unnecessary and iD shouldn't ask for it." My ticket number in JOSM forum is 11190.

**Comment by mkoniecz** [comment]
link to josm ticket: https://josm.openstreetmap.de/ticket/11190

**Comment by bhousel** [comment]
iD doesn't automatically add this tag.  It would only be present if a user explicitly tags a highway with it.  The access field displays "yes" in grey because that is the implied value.  But a user can change it to any explicit value that they want to.

I think in this case if you find a new user who is adding unnecessary tags, it's best to reach out to them with a note and politely tell them that they don't need to do that.

**Comment by naoliv** [comment]
Can't iD discard/ignore `motor_vehicle=yes` when used together on some kinds of highways? (from residential to motorway)

I am seeing a similar case to #2908, where the user think that he needs to explicitly say that the highway allows motor vehicles (ie, he doesn't know that it's implicit that the highway already allows it).
