### ISSUE TITLE
The join button ("+") should avoid segments with conflicting attributes

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#2577]
The join button ("+") should avoid segments with conflicting attributes, like different speed limits,  two ways/one way/reverse one way, paved/unpaved, and so on.  Or at least warn about the conflict.  It is a common mistake to see a street split in segments and join them to "optimize" the map, causing loss of carefully gathered information.

**Comment by pmailkeey** [comment]
I agree there is an issue here but this ability can also be useful - in combining data. When multiple items are selected, they are listed in the side panel - but only their names and what they are is shown. The side panel ought to show conflicting data so that users see what data issues there are before combining things together.

I've used the feature to show me how to tag a wall with a fence on the top of it into one line - by creating two lines, one of each type then using the + feature to combine them.

**Comment by afmenez** [comment]
Sorry, your example does not have conflicting tags.  But I like your
suggestion: maybe showing the conflicts on the side panel and allowing the
user to join the segments anyway could be a good compromise.

**Comment by bhousel** [comment]
Yes, I agree we need to do something about this.. It's actually already in issue tracker as #908
