### ISSUE TITLE
Old account still used after logout and reauth with new account

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2588]
Been off-line for a few mins - save failed.
Back on line but still get the same error message.
Tried reloading page and 'restoring' edits that neither works nor clears the error.
iD beta not uploading data.
iD via OSM interface works fine.

**Comment by bhousel** [comment]
It's kind of hard to tell from the description what went wrong.  I did just try making some edits from the iD master on http://openstreetmap.us/iD/master and things seemed ok...

**Comment by pmailkeey** [comment]
try an edit and save while not connected to the internet. Then reconnect to thte net and see how it recovers - or not !

**Comment by pmailkeey** [comment]
Hi Bryan,

I've a couple of accounts with OSM - a second one as I couldn't log into
the first at one time - I now run both but prefer to use the original -
which is what I've switched to with OSM. I wanted to switch in iD as well -
so logged out. However, following an OSM edit, it asked for login
permission to save edits to the map. Despite it appearing to want to login
on my preferred account I ended up being logged back in on the wrong one -
effectively I've now accessed an account without entering id or password.
As I guessed this was down to cookies, I've cleared osm.us/iD cookies and
tried again - and this time it has logged into to osm using the actively
open id. So maybe forcing a logout of iD should clear the appropriate
cookie. Otherwise, someone who thinks they've logged out securely would
find that the next person to use iD on that computer would find themselves
being logged in as the previous person.


-- 
Mike.
@millomweb <https://sites.google.com/site/millomweb/index/introduction> -
For all your info on Millom and South Copeland
via *the area's premier website - *

*currently unavailable due to ongoing harassment of me, my family, property
& pets*

T&Cs <https://sites.google.com/site/pmailkeey/e-mail>

**Comment by bhousel** [comment]
> try an edit and save while not connected to the internet. Then reconnect to the net and see how it recovers - or not!

I tried this by 1. disabling wifi, 2. attempt save, get message about checking internet connection, 3 enable wifi, 4. attempt save and everything seems fine.

> I've now accessed an account without entering id or password.
> As I guessed this was down to cookies, I've cleared osm.us/iD cookies and
> tried again - and this time it has logged into to osm using the actively
> open id.

This is just how OAuth works - iD uses your openstreetmap.org login for authentication, so you would need to log out from there in order to switch accounts.

**Comment by pmailkeey** [comment]
Well I don't think anyone else would accept this situation !

**Comment by bhousel** [comment]
We can't make it work any other way.  OAuth is a way of asking another site for permission to do things using your account.

For example if you log into Giphy using your Facebook credentials, then you decide you're done and log out of Giphy, it doesn't log you out of Facebook too.  In fact it can't do that because, due to the same origin policy, Giphy can not touch Facebook's cookies. This is just how cookies and OAuth work.

**Comment by pmailkeey** [comment]
The problem is logging out of iD doesn't clear local cookies - which allows it to log in as the previous user no matter who's using it.

**Comment by emacsen** [comment]
@pmailkeey it doesn't clear out osm.org's cookies, that's true. While iD is osm.org's current default editor, iD can and does run on other sites. It can't always be expected to clear out cookies for another site. I'm not sure it's possible for it to clear out osm.org's cookies (though I am sure someone else reading this will know for sure).

**Comment by pmailkeey** [comment]
"it doesn't clear out osm.org's cookies, that's true."

The point is, iD doesn't clear out iD's cookies ! On logout request in iD iD should clear it's own cookies  -or at least the userid cookie.

**Comment by pmailkeey** [comment]
Having used my browser's cookie-deleting option, I deleted ONLY iD cookies. Using iD after that, causes it to log in to the correct account active in OSM.

**Comment by bhousel** [comment]
Ok, I did some more testing and there is definitely an issue with keeping the original account around after using logout and getting prompted to accept OAuth for the new account.  Thanks for your persistence @pmailkeey, sorry I didn't understand the issue initially...

**Comment by bhousel** [comment]
@pmailkeey can you please test again on http://openstreetmap.us/iD/master/ to see if this issue is fixed now? You will need to open iD in a new browser tab, or refresh the page to get the new code.

It wasn't cookies (we don't even use them), but `iD.Connection` was in fact caching a `userDetails` object across logout/login.

This was what I did to test:
1. perform some edits.
2. logout with button at bottom right
3. attempt to save
4. iD will present the "Authorize access to your account" OAuth dialog from openstreetmap.org.  On this popup it does tell you which user you are logged in as, but you can use the hamburger menu in top right to logout and login with a different account on openstreetmap.org.
5. click "Save changes"
6. you will return to iD in save mode using the selected account. (not the original account as before)

**Comment by pmailkeey** [comment]
I'm using osm.us only for iD and Chrome reports 4 cookies from there including "lock" from iD/master:

![image](https://cloud.githubusercontent.com/assets/11827386/7279822/9a3cd84c-e916-11e4-891c-af0201633f55.png)

It'd be one of these that I removed to clear the old account use persistence.

**Comment by pmailkeey** [comment]
Yep, I'm happy with it now. 

One can log out of OSM and keep using the login on iD but once one logs out of iD, a new login is demanded whether or not OSM has been logged into or not.
