### ISSUE TITLE
Don't try to unzorro ways that are overly connected

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2598]
![image](https://cloud.githubusercontent.com/assets/11827386/7235311/5b3348b2-e785-11e4-8fec-07437e917dcd.png)

Is an interesting effect. I was hoping the white circularish line would slide along the yellow - but the yellow/white node is fixed (slides in Version 1.7) but the white line slides along that. With further movement, the effect in the right-hand image happens !

**Comment by bhousel** [comment]
Yes, because you only tried to move the circular guideline, the unzorroing code made new points to try to preserve the shape of the service road (which looks silly because of how connected they are).

If you select both the circle and the service road and move them together, I think it would work correctly, right?

P.S.. Please try to give this issue a better name, ok?
