### ISSUE TITLE
area:highway=residential - is not showing as an area

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/iD#2627]
Nothing more to add other than can it be made to display as an area ?

Similarly but different, junction=roundabout shows as an area when it's a line - can this be corrected tooooo ?

**Comment by bhousel** [comment]
> `area:highway=residential` - is not showing as an area

I'm surprised there are over 14,000 of these `area:highway=*`.  It looks proposed but not approved.
http://taginfo.openstreetmap.org/keys/?key=area%3Ahighway

> `junction=roundabout` shows as an area when it's a line

I think this was fixed in 1.7.1.  I see `junction=roundabout` as a line now, and `junction=anything else` as an area.

**Comment by pmailkeey** [comment]
With iD I've always chose area, highway, residential as that's what's been offered by iD - and works (is rendered on the standard map) as opposed to area:highway - residential - which seems to be an equivalent but doesn't work !

**Comment by polarbearing** [comment]
No they are not equivalent. 

highway=* plus an additional area=yes is used for the occasional non-linear highway features, such as the pedestrian area, or the asphalted service square in front of an industrial building. 

area:highway=yes has been proposed, but not yet widely accepted, for kerb-to-kerb filling of land occupied by linear highways, such as you map in Millom currently. It is not supported for rendering on the general OSM map, as you have been told here: https://github.com/gravitystorm/openstreetmap-carto/issues/1514 

The OSM data however are not only used by this one map rendering, there are other rendering styles and data consumers that rely on correct data. Therefore, please do not abuse the area tag just to force a particular renderer to paint something in a visual style you prefer. 

This is all based on open software, so you can always fork the carto style, change to your needs, feed it into tilemill to render it for your purposes, or set up your own tileserver presenting your different rendering.

**Comment by pmailkeey** [comment]
I just use what I'm offered to achieve the desired results. As to why a second similar tag is needed when there's already one that works, I don't know. Area=yes, highway=residential ticks all the boxes for appropriateness irrespective of your opinions. It is a highway and it is an area - so the data is not wrong, it must be something else.

**Comment by jgpacker** [comment]
Not sure if this got clear, but `area:highway=*` and (`highway=*` + `area=yes`) are indeed two different things, and their meaning only overlap in exceptional cases (e.g. `highway=pedestrian`).

**Comment by bhousel** [comment]
> Not sure if this got clear, but area:highway=* and (highway=* + area=yes) are indeed two different things, and their meaning only overlap in exceptional cases (e.g. highway=pedestrian).

I haven't decided what to do about this yet. 
* `highway=* + area=yes` will always look right in iD because of the `area=yes`
* but `area:highway=*` would need a special preset built for it..

It's definitely an area, but there a handful of other area-like tags that we don't render as areas.  For example, `building:part` used in 3D mapping would probably look terrible and overwhelm the svg renderer if we made all of the micromapped building parts as areas. 

Also it's not an approved tag.  I guess my strong preference is for highway micromappers to just use [`landuse=highway`](http://wiki.openstreetmap.org/wiki/Proposed_features/landuse%3Dhighway) like the railway people use [`landuse=railway`](http://wiki.openstreetmap.org/wiki/Tag:landuse%3Drailway).  `landuse=highway` is also not approved, but at least it's consistent with how other tags work and doesn't need any special treatment.

**Comment by pmailkeey** [comment]
Surely area:highway=* is inflexibly horrible ? Area=yes can be attached to anything.

**Comment by jgpacker** [comment]
They simply are two different things. 

The tag `area:highway=*` is meant to be used to detail the area of a highway for the renderer. The highway should also be mapped normally in this case, because the area only details the shape and is not "routable".

The tag `highway=*`+`area=yes` is used in exceptional cases where the highway can't reasonably be mapped as a way  (usually used for pedestrian plazas and squares).

And may I ask how `area:highway=*` is inflexible?

**Comment by pmailkeey** [comment]
"The tag area:highway=* is meant to be used to detail the area of a highway for the renderer."

We don't map for the renderer.

"The tag highway=*+area=yes is used in exceptional cases where the highway can't reasonably be mapped as a way (usually used for pedestrian plazas and squares)."

Big spaces are no different from small ones. A space with no obstacles would be mapped with a node in the middle and ways going off in each different direction.

"And may I ask how area:highway=* is inflexible?"

for each area you'd need a different tag whereas area=yes is one tag suitable for all applications.

**Comment by bhousel** [comment]
I added a preset for it and called it "Road Surface".

@pmailkeey when you get a chance, please change the areas you have mapped as `highway=* + area=yes` to use this preset `area:highway=*` instead.

**Comment by pmailkeey** [comment]
I've now got area:highway=yes , highway=track. So that's no benefit.
The disbenefit is that the area:highways don't show on the standard map - so I'll stick with area=highway and highway=* for the time being.
