### ISSUE TITLE
Can't save changes in ID after Windows update

### ISSUE THREAD

**Issue by ArAge67** [openstreetmap/iD#2645]
Hi!

During editing in ID 'Windows Update' caused an auto restart of my laptop. Now everytime I open ID editor in Chrome I got a popup with two possibilities: "Restore changes' or delete them. Of course I want to save my changes but pressing the 'restore' button does do nothing. 
If I close this popup and press 'Ctrl+S' all my changes are shown on the left hand side and a blue 'Save' button is visible. But pressing this button doesn't do anything too. 
Is there a way of saving my changes or are they simply lost?

Best regards
ArAge

**Comment by bhousel** [comment]
There are a handful of weird "restore changes" bugs that will hopefully be fixed in the next release soon.

I have gotten stuck in this same way before, and here is a procedure that may work (it will sound weird):

* Move the map far away from a place that has anything that you have edited (an easy way to do this is just change the lat/lng in the url)
* Reload the page (control-R) - your browser will probably prompt for confirmation, say yes.
* Now you should have a fresh iD - try again choosing "Restore Changes"
* Try to save - you should again see a summary of your changes in the left sidebar
* Before hitting the blue save button, click on each change to review it - iD will show it to you and (importantly) load the map around the vicinity of your edits (you do need to let the map load completely each time)
* Finally click the blue save button..

Let me know if this works..

**Comment by ArAge67** [comment]
Yes it works! Thank you very much. This saves me a lot of extra re-work.

Btw sometimes it was difficult to see what kind of change I made when I started to review them (step 5 of your procedure). Now it's just a brown line or circle around the change. Maybe a slight improvement could be a blinking brown line or just another fancy color to make it more visible.

Anyway thanks again for your help!

**Comment by bhousel** [comment]
> Btw sometimes it was difficult to see what kind of change I made when I started to review them (step 5 of your procedure). Now it's just a brown line or circle around the change. Maybe a slight improvement could be a blinking brown line or just another fancy color to make it more visible.

Oh yeah, it can be hard to see the selection halo sometimes. This is actually issue #1814.  My thought for solving it is similar to what you said above - but not make it blink, maybe just make it 'breathe' a little.

> Anyway thanks again for your help!

Glad I could help..
