### ISSUE TITLE
overly agressive url-encoding if a field contains text including links

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/iD#2657]
When one enters some text which includes a URL into a field (e.g. *note* or *fixme*), the whole text gets percent-escaped (e.g. all whitespace transformed to `%20`). This automatic escaping should (at least) not be active if the field's value doesn't start with what looks like a URL.

**Comment by 1ec5** [comment]
iD seems to be URL-encoding _every_ field containing a URL if _any_ field is edited. This is causing `source` tags to become incomprehensible, because they often contain URLs along with other text:

```
source=TIGER/Line%C2%AE%202008%20Place%20Shapefiles%20(http://www.census.gov/geo/www/tiger/)
```

**Comment by 1ec5** [comment]
This regression was introduced in 420647f5034083db905b5bf320e7c21b52379a3f for #2323. `cleanVal()` is called on every tag when any tag is edited. It mostly makes sense to strip spaces after semicolons that aggressively (except in the `note` and `description` fields…), but I think it may be too aggressive for other types of canonicalization.

Anyhow, the errant escaping is due to [treating the entire tag value as a URL](https://github.com/openstreetmap/iD/commit/420647f5034083db905b5bf320e7c21b52379a3f#diff-1688af40bff607fe1b6cb0078a3e0ceaR154) if “http” occurs anywhere inside:

```js
var cleaned = "TIGER/Line® 2008 Place Shapefiles (http://www.census.gov/geo/www/tiger/)";
cleaned = cleaned.replace(/[^\w\+\-\.\/\?\[\]\(\)~!@#$%&*',:;=]/g, encodeURIComponent);
// => TIGER/Line%C2%AE%202008%20Place%20Shapefiles%20(http://www.census.gov/geo/www/tiger/)
```

/cc @bhousel

**Comment by bhousel** [comment]
Yes, the url escaping ended up too aggressive because I didn't want to whitelist keys to apply it too (think of all the `facebook`, `instagram`, `google_plus` tags people add for their businesses).

Would it be better maybe if I change it to only urlencode if the value begins with `http` (instead of just containing it anywhere in the value)?

**Comment by 1ec5** [comment]
> Yes, the url escaping ended up too aggressive because I didn't want to whitelist keys to apply it too (think of all the `facebook`, `instagram`, `google_plus` tags people add for their businesses).

Taginfo says `contact:facebook` and the like are more common. These sites also don’t tend to have the escaping issues that random `website`s may.

> Would it be better maybe if I change it to only urlencode if the value begins with `http` (instead of just containing it anywhere in the value)?

I think that’d be OK. It’d also cover any `source` tag that consists entirely of a URL.

**Comment by tyrasd** [comment]
> Would it be better maybe if I change it to only urlencode if the value begins with http (instead of just containing it anywhere in the value)?

+1
