### ISSUE TITLE
Add preset for "storage_tank".  100,000 uses in the database

### ISSUE THREAD

**Issue by brycenesbitt** [openstreetmap/iD#2662]
There are 100,000 storage tanks in OSM.  Could iD grow a preset for this also?
Here's the matching JOSM preset:

        <item name="Storage Tank" icon="presets/storage_tank.png" type="node,closedway">
            <key key="man_made" value="storage_tank" />
            <optional>
                <reference ref="name_operator" />
                <combo key="building" text="Building" values="storage_tank" values_context="building" />
                <combo key="content"  text="Content" values="fuel,manure,oil,sewage,silage,
                slurry,water,wine" values_context="content" />
                <text key="height" text="Height (meters)" length="7" />
            </optional>
        </item>

The oddity here is that storage tanks are tagged both as buildings and as man_made.

**Comment by bhousel** [comment]
> There are 100,000 storage tanks in OSM. Could iD grow a preset for this also?

Sure, makes sense to me..

> The oddity here is that storage tanks are tagged both as buildings and as man_made.

Yeah, kind of odd, but not really.  In OSM, "building" often means "structure" (in the building construction code sense).

**Comment by brycenesbitt** [comment]
@bhousel is "water" in that preset as a search term?  A very common storage tank is a water storage tank which is not raised like a water_tower.

Also how does the preset code work to cause this node to get both man_made=storage_tank+building=storage_tank by default?  The JOSM syntax is clear, I'm not quite following the iD case.

**Comment by bhousel** [comment]
> @bhousel is "water" in that preset as a search term? A very common storage tank is a water storage tank which is not raised like a water_tower.

I didn't add "water" originally, but I can add it - I assumed people were using `man_made=water_tower` for that.

> Also how does the preset code work to cause this node to get both man_made=storage_tank+building=storage_tank by default? The JOSM syntax is clear, I'm not quite following the iD case.

The `building_area` field attached to this preset is special because it adds a `building=yes` tag to the preset only if it is an area.  I could make a field that does `building=storage_tank` instead, but I really don't want to open the floodgates and have to create new fields for all the different kinds of `building=*`.  

In the back of my mind I have some ideas for a better `building` field that can incorporate some smarter code and let users set more building attributes, so may revisit it later..

**Comment by bhousel** [comment]
added "water" to terms list in 4a47a73

**Comment by brycenesbitt** [comment]
Thanks.  A water tank is indeed distinct from a water tower.  The towers
are raised above the ground, and often landmarks.
