### ISSUE TITLE
Unable to Unlock tasks. 

### ISSUE THREAD

**Issue by SuzanReed** [openstreetmap/iD#2666]
After finishing a tile it won't unlock. Going back to the tile, images have been doubled or tripled. Fixing them, then going back to the Tasking Manager, the tile still won't unlock. Many tries and waiting for the server (waiting 60 to 120 seconds), still won't unlock. 

Internet speed is fast. 

OS 10.6.8 Firefox MacBook Pro
http://tasks.hotosm.org/project/689#task/65

**Comment by bhousel** [comment]
iD doesn't have any integration with the HOTOSM task manager to lock or unlock tasks, so the issue you are seeing is between your computer and the task manager.  You could try opening this issue with the task manager project [here](https://github.com/hotosm/osm-tasking-manager2).  

If when unlocking a task you need to wait 60-120 seconds for a response from their server, I'm afraid there is something wrong with your internet connection.  Troubleshooting issues like this is really tricky because it can be anything from a bad cable at your ISP to malware on your computer.

**Comment by SuzanReed** [comment]
Thank you for responding. I must have incorrectly described. The wait time 
was something I tried, but it didn't work. I pinged my Internet connection 
and it's exceptionly fast. Thanks again.

Suzan
