### ISSUE TITLE
in iD.ui.TagReference, use locale passed in from container even if a different one is detected..

### ISSUE THREAD

**Issue by bagage** [openstreetmap/iD#2672]
It might be voluntary, but currently almost all of the interface is translated except "i" extra information hints which refer to the wiki.

For instance [aerian cable (JPG)](http://oi62.tinypic.com/hx26uf.jpg) uses description from [wikipedia key:name article](http://wiki.openstreetmap.org/wiki/Key:name) but I think that it should take the user language description instead of English (if available), isn't it? In French it should display ` L'étiquette name permet de nommer un élément.` for instance.

**Comment by bhousel** [comment]
The code in [iD.ui.TagReference](https://github.com/openstreetmap/iD/blob/master/js/id/ui/tag_reference.js#L8-L31) does fallback from your local language to English if a local wiki page is not available.

When iD presents an English page, you can click on it and at the top of the page you will see all of the localized versions that are available.  For example, I can see that there is no French page in the wiki for [Aerialway](http://wiki.openstreetmap.org/wiki/Key:aerialway). 

So really the best thing to do in this situation is to translate the wiki page.  This is great too because the efforts spent will benefit the wider OpenStreetMap community, not just the iD users.

**Comment by bagage** [comment]
Hmmm, I do not think it is working. Translation is available in `french` ([primary road](http://wiki.openstreetmap.org/wiki/Tag:highway=primary) for instance) but iD still use English translation. 
Maybe is it a typo, `iD.ui.TagReference` expects to find `French` but it gets `french`?

**Comment by bhousel** [comment]
Oh, ok, I see the screenshot now, and yes, that should probably link to the [French power=line page](http://wiki.openstreetmap.org/wiki/FR:Tag:power%3Dline).

![](http://oi62.tinypic.com/hx26uf.jpg)  

(btw, It's usually better to just drag images onto a Github issue, rather than using a photo sharing site)

Can you open a developer console, type this, and send the output:
`JSON.stringify(iD.detect())`

**Comment by bagage** [comment]
On your URL, everything it is English (because of `.us` domain?). Query returns:

> {"browser":"Firefox","version":"38.0","support":true,"opera":false,"locale":"en-US","filedrop":true,"os":"linux","platform":"Linux"}

I'd like to do the same on [openstreetmap.org](openstreetmap.org) but iD is not defined (still searching howto do the same though :)).

**Comment by bhousel** [comment]
Thanks that is helpful!    On the `openstreetmap.us` site, everything is English because iD detected the `en-US` locale in the request sent by Firefox. [Look here](http://superuser.com/questions/131968/changing-http-accept-language/131969) for more information on how to set which languages Firefox will request.

On the main openstreetmap.org site, things will be a little different because that website passes your preferred languages to iD running in an iframe.  So there is probably an issue for us to fix where iD detects one locale and gets passed a different one, but objects already created are stuck using the initial detected locale.

**Comment by bagage** [comment]
Indeed, adding French language there fix the problem. My OS is in French, but iceweasel/firefox was in English, so openstreetmap gave me a mix of both :). On my side everything is OK now that I added the language, but you may keep this issue open I guess?

**Comment by bhousel** [comment]
Yes, I'm leaving it open because I want to make extra sure iD is using the locale preference passed to it from openstreetmap.org, even when it detects a different one..
