### ISSUE TITLE
There are clouds on this are

### ISSUE THREAD

**Issue by omidgharib** [openstreetmap/iD#2673]
In satellite mode there are clouds on this area and you can't see roads and so on.
https://www.openstreetmap.org/edit#map=14/36.2947/59.6404

**Comment by bhousel** [comment]
We can't remove the clouds - at this spot they are part of the imagery that we fetch from Bing.

But you can switch which imagery provider iD uses.  In this area, Mapbox Satellite looks better. The available list is in the "Background" pane and can be switched like this:   
![screenshot 2015-06-02 07 55 27](https://cloud.githubusercontent.com/assets/38784/7935184/cfb05c28-08fc-11e5-8a02-032789a45cdb.png)

**Comment by omidgharib** [comment]
@bhousel Thank you so much.

**Comment by jidanni** [comment]
Please allow choosing other dates of Bing imagery.
That would solve the cloud issue in areas without other imagery.

**Comment by jidanni** [comment]
I will never be able to add roads to 24.195986,120.875145 .

**Comment by bhousel** [comment]
> I will never be able to add roads to 24.195986,120.875145 .

In this case both Bing and Mapbox are sourcing their imagery from Digital Globe, and yes there are unfortunately clouds in the images.  

Here are some ways to report this issue:
For Mapbox Satellite layer: Use this imagery request tool: https://www.mapbox.com/labs/request to zoom to the location with the issue and draw a box around it.
For Bing Satellite layer: Open the location in https://www.bing.com/maps and click the "Report a problem" link on the sidebar.

**Comment by jidanni** [comment]
All I know is in Google one has a choice of dates, and is never stuck
with only the current imagery.

OK I reported it to the Mapbox, and think I was able to report it to
Bing via their Feedback link, though the window closed rather fast
making it seem like I pressed cancel rather than submit. Also Bing only
has a Chinese interface for me despite setting it to English.

**Comment by bhousel** [comment]
> All I know is in Google one has a choice of dates, and is never stuck with only the current imagery.

Thank you for reporting the issue with Mapbox and Bing.  I don't think the [Bing Imagery API](https://msdn.microsoft.com/en-us/library/ff701721.aspx) gives us the option to fetch older imagery, but it would be cool if they did support that.

**Comment by jidanni** [comment]
Yes please suggest to them to make it possible,
else there is a very real danger,
that there you are the organizer of an OSM map event,
with a classroom full of people, who signed up weeks in advance,
and what was all planned out and tested turns out to be now one big
cloud this morning, due to an update, with no way to back out, as we see
in my case where they are all getting their stuff from one source anyway.
