### ISSUE TITLE
Deleting an address doesn't delete addr:country

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#2698]
When deleting an address by clicking on the wastepaper bin icon in the address form, addr:country (if present) doesn't get deleted from the object in question.

While I can understand the reasons for this (likely it doesn't delete anything that is not displayed in the form), it is slightly unexpected behaviour if you are simply intending to delete an address.

**Comment by bhousel** [comment]
Yeah intuitively I would also expect that `addr:*` should be deleted.

**Comment by bhousel** [comment]
Ok I see what happened.  The same thing is happening with `addr:state`.  And both the delete and revert buttons are both not working for many of the `addr:` tags.

The address field has been localized since #2246 but the preset file still contains the [old values for the keys](https://github.com/openstreetmap/iD/blob/master/data/presets/fields/address.json#L3-L9).  These `keys` are not used for display, but they are used by the delete and revert buttons to know which fields should get affected.
