### ISSUE TITLE
Warn if user enters wrong formatted phone numbers

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/iD#2704]
Please warn the user if he enters a wrong formatted phone number (`phone=*`). See the [specification at OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:phone).

Example: `+49 721 976 70135` is wrong, `+49 721 97670135` would be right. https://www.openstreetmap.org/node/3595384084/history

**Comment by bhousel** [comment]
I've thought about this some more and I don't think we should do this. 

Forcing ITU-T E.164 on new users is more likely to annoy people than to actually help.  Despite what the wiki suggests, nobody actually thinks of phone numbers this way.

**Comment by dieterdreist** [comment]
I agree that nitpicking on excessive space is likely a bit too much for an editor aiming at the occassional contributor (in the end, they don't really harm). But it would be great to suggest the country code should be entered (most or at least many phone numbers are entered in the national format, leading to many man hours of work by pedantic mappers to correct these).

Btw: if you were to also check the first digit after the country code (because many countries omit the leading zero in this case, e.g. Germany), please be aware that Italy requires the leading zero even with the country code prefixed. Example German local number (from above): "0721 / 97670135" while in Italy 06.12345678 becomes "+39 06 12345678"

**Comment by pnorman** [comment]
Somewhat a duplicate of #3495
