### ISSUE TITLE
Display labels on vertex

### ISSUE THREAD

**Issue by franckt** [openstreetmap/iD#2709]
Currently, nodes with name tag display label but vertex do not display label
So nodes that make a highway=footway for example hide node with name
How can it be updated ?

**Comment by bhousel** [comment]
I added this today.  It's especially useful for transit stops.

Vertex labels are treated just like point labels, except that they are not drawn at low zoom (z16) because vertices are not drawn with icons at low zoom.

<img width="316" alt="screenshot 2016-12-07 16 56 47" src="https://cloud.githubusercontent.com/assets/38784/20988457/d5dd627e-bc9e-11e6-8f8e-360ac43e433d.png">
