### ISSUE TITLE
Feature filter should restrict editing filtered feature?

### ISSUE THREAD

**Issue by geohacker** [openstreetmap/iD#2711]
This came up a lot during validating Nepal mapping tasks. For zoom level 16-17 buildings are hidden, but users can still draw new buildings, this causes duplicates and overlaps - just because they don't see the existing buildings. 

![screen shot 2015-06-26 at 10 13 16](https://cloud.githubusercontent.com/assets/371666/8379205/6a6a7b2a-1bec-11e5-8cf7-ccdc7bbcfd32.png)
_drawing a building while buildings are hidden_

![screen shot 2015-06-26 at 10 13 38](https://cloud.githubusercontent.com/assets/371666/8379212/71c5ee22-1bec-11e5-87f4-96a8c4c56892.png)
_overlapping building when zoomed in_

May be we should restrict editing/adding features that are already filtered? 
@bhousel thoughts?

**Comment by bhousel** [comment]
Yes I agree we should try to make this better.  It is confusing that the feature filters don't apply to the newly drawn features - I made it work that way because I didn't want them to just disappear immediately from view.

I have to think a bit on how to improve it, because things don't start out being the feature they end up as.  e.g. When you start drawing a building, it's just an untagged area, and doesn't become a building until later when you pick a building preset, and by that time it's too late to not let the user draw it.  In fact the problem is more complicated because picking anything with the `building_area` field gets defaulted to having a building tag (like many shops or amenities).

**Comment by planemad** [comment]
How about we tone down the visibility of the filtered object to the extent a user knows there is an object at the location, instead of hiding it completely.

**Comment by bhousel** [comment]
> How about we tone down the visibility of the filtered object to the extent a user knows there is an object at the location, instead of hiding it completely.

Part of the reason we need to hide them completely is because of svg performance - specifically fill.  So if you are filtering several thousand buildings, even drawing them opaque will make iD unusable.

I'm leaning more towards noting that they are filtered in the preset menu somehow..  ugly mockup:

<img width="600" alt="hidden_presets" src="https://cloud.githubusercontent.com/assets/38784/11787091/fd4e7c9c-a257-11e5-96f1-67055fee463b.png">

I'm not too crazy about it.  But it would be a hint to the user that either means "don't be surprised if you pick this thing and it immediately disappears" - or - "you can't pick this because of the active filter".

**Comment by planemad** [comment]
@bhousel this is good, and on selecting the preset, zoom the map to the minimum level to make the chosen feature visible. By now the user would already have one duplicate building that they might have to delete, but this would avoid any further duplication.

**Comment by slhh** [comment]
@bhousel 
In case svg performance for fill is the problem, how about rendering the buildings for lower zoom levels as outline only. A few more levels seem to be sufficient because nobody would draw a building at a really low zoom level.

**Comment by danstowell** [comment]
Hi - I think we just got bitten by this in mapping an area in Indonesia - example https://www.openstreetmap.org/changeset/64965662#map=18/-6.37468/105.82721 Very likely that this user drew duplicate buildings because they hadn't zoomed in to see the existing ones.

I'm not too hot on the greying-out-presets option but it's better than nothing - alternatively I wonder if there's some way to render a simplified low res something, to indicate that "there are buildings in this area" - e.g. the building infill colour, simply appearing vaguely in e.g. square mini-areas...? Just thoughts out loud.

**Comment by bhousel** [comment]
#3741 is probably the best solution.  We could render the areas with canvas which has much better fill performance than svg.  Then if a user wants to edit something, swap it from the canvas to the svg layer for interactivity.

**Comment by bhousel** [comment]
Moved to #5876
