### ISSUE TITLE
Conflict dialog shows incorrect conflicting user

### ISSUE THREAD

**Issue by ToeBee** [openstreetmap/iD#2735]
I just conflicted with another user while editing way [10576362](http://www.openstreetmap.org/way/10576362). The changeset that I'm in conflict with is [changeset 32686501](http://www.openstreetmap.org/changeset/32686501). It is nothing more than a change to the name=* tag by user j03lar50n. I edited the geometry and added other things in the area as well as changing the name tag. However here is what iD is showing me:

![id_bug](https://cloud.githubusercontent.com/assets/348948/8737148/8876a9f6-2be4-11e5-8044-ef7f7a2ec479.png)

woodpeck_fixbot hasn't opened a changeset in 3 years and has never touched this particular way at all so I'm not sure how that user name ended up in the conflict dialog.

**Comment by bhousel** [comment]
Yeah I have seen the occasional conflict with woodpeck_fixbot too when I was testing and never could figure out why until now.

It's because of how we lump all the childnode changes together when a parent way is changed.   In this case, the parent way had the conflict, but we need to check all the childnodes also.  You must have moved a childnode that had not been moved since woodpeck_fixbot, and [this code](https://github.com/openstreetmap/iD/blob/master/js/id/actions/merge_remote_changes.js#L103-L107) noticed the difference and flagged it incorrectly as a conflict.  

By the way, if if weren't for this bug, iD probably would have just let the change though safely without a warning.  If two users happen to change a way to the same name, there is really no tag conflict and iD considers it a 'safe' merge.

**Comment by bhousel** [comment]
Fixed in 4c6b75a, thanks @ToeBee!
