### ISSUE TITLE
warn on uploading highway=yes

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#2744]
While further testing for #2742 i saw the possibility to get a `highway=yes` via entering the german "Strasse" and selecting "Straße/Weg" of the preset system. 
There i could enter a type of way (residential, trunk,...), but i am not sure if the whole interface is needed, as the entries are not translated.
Furthermore iD does not force me to select something and does not prevent me or warn me from uploading a osm way with the tag `highway=yes`.

**Comment by bhousel** [comment]
> There i could select a type of way (residential, trunk,...), but i am not sure if the whole interface is needed, as the entries are not translated.

I'm not sure which interface you mean here - the raw tag editor?  Can you share a screenshot?  We can't translate the keys and values that appear in the raw tag editor because they can be anything that anyone in OpenStreetMap makes up.

> Furthermore iD does not force me to select something and does not prevent me or warn me from uploading a osm way with the tag highway=yes.

You're right, we don't warn a user if they enter something with the raw tag editor that doesn't exist within the defined preset system, and I don't think we should.  Free tagging is one of the core design decisions of OpenStreetMap, for better or worse, so users are totally allowed to enter tags which may seem dumb to us more experienced mappers.

**Comment by HolgerJeromin** [comment]
The sequence to get to this situation (in german iD, as i found no way to switch to english):

![github2744](https://cloud.githubusercontent.com/assets/2410353/8955764/01276f1a-35f0-11e5-92d9-2b9ea21f84e9.png)

And after that, enter nothing into the "Typ" field, which seems optional as the other fields. So click save.
At least the highway tag should have a white list to not produce a warning.

**Comment by HolgerJeromin** [comment]
Another solution would be removing the Entry "Straße/Weg", as its very possible to lead to an error. We have the generic "line" entry (with no tags), if a user has knowledge.

**Comment by bhousel** [comment]
Thanks, I see what it is now.. You're finding the generic [highway.json](https://github.com/openstreetmap/iD/blob/master/data/presets/presets/highway.json) preset, which I agree should not be searchable.
