### ISSUE TITLE
feature request: autocompletion for tags

### ISSUE THREAD

**Issue by javiribera** [openstreetmap/iD#2748]
These tags are not being autocompleted when typing in the iD editor:

- button_operated https://wiki.openstreetmap.org/wiki/Key:button_operated
- traffic_signals:*** https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Traffic_signals_for_pedestrians

![screenshot from 2015-08-10 21 38 45](https://cloud.githubusercontent.com/assets/5376776/9188261/52234daa-3fa8-11e5-9e50-cb77a401b840.png)

**Comment by bhousel** [comment]
The code in [`taginfo.js`](https://github.com/openstreetmap/iD/blob/522e593f112d3c628604a54a2d0ca0bae11dc5c3/js/id/services/taginfo.js) is doing a few things that we should maybe adjust:

* `shorten` cuts the query down to only the first 3 characters, so above examples would search `but` or `tra`.   This is done to cut down on extra requests to taginfo, but because of debouncing and caching, seems unnecessary.
* `popularKeys` only shows a key if it has at least 10000 uses.  This seems too high to me, and both `button_operated` and `traffic_signals` have a little over 5000.
* `popularValues` will also show less popular values if they have a wiki page. `popularKeys` should have this behavior too.
