### ISSUE TITLE
feature request: remind users to save periodically

### ISSUE THREAD

**Issue by kriscarle** [openstreetmap/iD#2749]
Remind users to save after a certain number of edits or a certain amount of time. 

We've noticed in our mapathons for http://loggingroads.org that users (especially new users) don't always realize that they need to save periodically and end up with a large number of edits that 1) slows the browser down and 2) are more likely to have conflicts with other mappers in the mapathon.

**Comment by d1g** [comment]
Suggestion 1 (soft warning): add glow to "Save" button when number of *changes* (adds/edits/deletions) is over 100/200/other magic number

Suggestion 2 (aggressive warning): add glow to class "layer-layer layer-data" (main edit window in iD) over 1000/2000/... edits

http://jsfiddle.net/XUC5q/1/ - [box-shadow](http://guillee.tumblr.com/post/475773360/css-glow-effects-with-box-shadow)
http://codepen.io/NobodyRocks/pen/qzfoc - random css3 variants


UX considerations: 
* user(s) may be unaware that *high number of edits slows their editing process* - they should be informed *after soft and hard warning* that their editor is slow due to unsaved edits. 
* zooming and panning vast areas without editing/save/unloaded data - may also result is slower iD - how does iD behaves in this scenario? What is suggested to end user?
* auto-commit after 3km map swipe might be an option You may also add "autocommit=yes" or "autocommit=hardwarning"  or "autocommit=featurex"   in changeset tags.

**Comment by SHARCRASH** [comment]
I totally agree with you guys, the more time an edit is opened, the more chances there will be for a conflict... I often end up with large edits but not because i'm a beginner. It happens when i'm trying to convert massive of interconnected areas into MP while using other existing elements, such as ways for example.
I do this to :
- easier to create complex areas
- make areas of multiple elements more clear while keeping its precision (less parallel or interconnected lines)
- lowering data usage
- since Mapnik changed its Forest & Wood tiles with a transparency, the transparency will over tile the inner element if no relation is defined, many user plotted inner areas without relations, so now proper MP integration will be needed to be set or there will be errors of intersecting lines in OSMi (in my home country Luxembourg, it's often near zero errors)
- last but not least, for future edits in those MP i noticed that it's way easier and less time consuming, full beneficial. 

Usually I'm between 100 and 224 (today). Large number of edits because in between i do little improvements on other elements i encounter during the main area I'm working on.

**I'd recommend a soft warning.**

OT
Also... I think there is a bug I'm going to report on a new post. During those +/-224 edits, i got a set of prompt selections for conflicts (22 in total) but some were not for edits that happened at the same time during mine, I believe some were about the former edits that were already in place, other indeed from a user that edited the same elements in between. Also after having compared all prompts, I encountered a second set of prompt selections (3 oft them), which i responded again but at the saving they were endlessly restarting the second set. Had to save the XML... *sigh*

**Comment by vespax** [comment]
Soft warning would be useful.  A 'glow' may not alert the user enough.  Maybe a pulsating glow in the number of edits callout to give more attention the action.  I would suggest a the alert have an option of 50/100/200 edits to avoid conflicts in active mapping areas.

**Comment by systemed** [comment]
If it helps, the way P2 does it is by adding a "minutes elapsed" count to the Save button (when edits have been unsaved after 5 minutes or more). Then, at 20 minutes and at 5-minute intervals thereafter, a non-modal 'floating alert' appears to say "20 minutes since last save - please save regularly".

**Comment by bhousel** [comment]
Every time I think about this issue, I think that if the save button did more and more interesting things the higher the count got, I would probably keep pushing that count as high as I could to see what would happen next. 

I'm also one of those people that waits until the gas gauge is way past empty before filling the car back up with gas.

**Comment by tanerochris** [comment]
Following, from d1g suggestions, which think is  good and would love to add that ,the save button, preferably the count tooltip could glow green,transit to some other color ,and in extreme case we get an alert, asking the user to save and reasons why they should save their work.I am new to open street map and I would love to work on this given that its labeled get-started.

**Comment by bhousel** [comment]
> Following, from d1g suggestions, which I think is good and would love to add that ,the save button, preferably the count tooltip could glow green,transit to some other color ,and in extreme case we get an alert, asking the user to save and reasons why they should save their work.I am new to open street map and I would love to work on this given that its labeled get-started.

Great!  This is an excellent first issue to tackle..

The code to change is [around here](https://github.com/openstreetmap/iD/blob/d17f22eb7dde299c8b763a092dcd4900673f974a/js/id/ui/save.js#L53) in `save.js`.  This is a callback the updates the button state anytime the map is changed.

By default, the buttons are css `background: white`.  Try to adjust the styling on the button and the count next to it.  The current styling is determined by [this css](https://github.com/openstreetmap/iD/blob/d17f22eb7dde299c8b763a092dcd4900673f974a/css/app.css#L452-L486).  iD uses [D3.js](https://d3js.org/) for managing the DOM, so you'll need to understand how that works.

For now, lets keep it simple and calculate a background color that goes from `#fff` at 0 edits down to `#ff8` at 50 edits and `#f88` at 100+ edits.  It'll slowly turn the button yellow, then orange, then red. 

No alerts, no glows, no flashing, etc..

**Comment by bhousel** [comment]
This was merged today!  Thanks @tanerochris

![save warning](https://cloud.githubusercontent.com/assets/38784/15365242/861b0026-1ced-11e6-979d-0caa48342852.gif)

**Comment by tanerochris** [comment]
It is a nice start contributing to openstreet map .thanks @bhousel
