### ISSUE TITLE
link to page descriping tag on OSM wiki if able (currently it leads to page describing key)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#2754]
see for example https://www.openstreetmap.org/edit?editor=id#map=18/52.61392/24.36614 and select object.

In section "All tags" select info button (with "i" icon). 

"View on OpenStreetMap Wiki" links page describing key, even for tags where there is a separate page for tag value.

For example for landuse=forest http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dforest is preferable over current target - http://wiki.openstreetmap.org/wiki/Key:landuse .

**Comment by M1dgard** [comment]
I'm working on this issue, and I have a solution working but I am not sure the code is acceptable. Could @jfirebaugh and @bhousel give some advice?

**Highlights of the changes for the devs**:
iD.TagReference→load→(anonymous callback function) heading changed to `function(err, data, softfail) {`.
softfail is a flag that signals to this function that if it doesn't find appropriate documentation in the response, it should `return false` instead of displaying a message to the user.
The return value is picked up by a "callback decorator" in iD.taginfo.docs. If it receives false from the real callback function, it omits the 'value' property from `parameters` and calls taginfo.docs again.
 
The callback decorator just wants to inject the softfail argument, but it has to know the arguments that it should pass on to the real callback. It is written as
```js
function(err, data) {
    var docsFound = callback(err, data, true);
    if (!docsFound) {
        taginfo.docs(_.omit(parameters, 'value'), callback);
    }
}
```
Alternatively one could write
```js
function() {
    var args = _.clone(arguments);
    args[2] = true;
    var docsFound = callback.apply(null, args);
```
or
```js
function(results) { // results = {err:err, data:data}
    var docsFound = callback(_.extend({
        softfail: true
    }, results));
```
and make all necessary changes.

Is the general direction all right? Would one of the ways to signal a soft-fail be a good one? If not, what would you recommend?

Thanks.

**Comment by bhousel** [comment]
Looks like a good approach me.  I guess you have to change [here too](https://github.com/openstreetmap/iD/blob/90bc645e441b27785ef2862ed4fc2cd08cc7d4ce/js/id/ui/raw_tag_editor.js#L88) to pass the tag value?

The first variation of the decorator looks most like how we do this elsewhere in iD code.

**Comment by M1dgard** [comment]
> I guess you have to change here too to pass the tag value?

Yes, and also a true that I called `fallbackToKeyIfNoValueDocs`. I couldn't think of a shorter name that makes it clear what it is supposed to do. Any ideas or is it fine?

**Comment by bhousel** [comment]
I would just change
```
iD.ui.TagReference = function(tag, context) {
```
to
```
iD.ui.TagReference = function(key, value, context) {
```

and do key-only documentation lookup if `value` is something that can't be reasonably used.
