### ISSUE TITLE
Mykonos town problem with layers

### ISSUE THREAD

**Issue by tigresp** [openstreetmap/iD#2757]
Mykonos town
https://www.openstreetmap.org/edit#map=18/37.44563/25.32911
Cannot map it properly as there is a problem when moving around the map. It jumps to various random positions.
Cheers

**Comment by stephan75** [comment]
I can confirm that random position changing when panning the map inside iD with mouse.

Using Chrome portable version 42.x

**Comment by pnorman** [comment]
Confirming on Chrome 44.0.2403.157, Windows 8.1.

About all that seems different there from other areas is the medium-sized [relation 531115](https://www.openstreetmap.org/relation/531115)

**Comment by tyrasd** [comment]
Actually, [relation/3304283](http://www.openstreetmap.org/relation/3304283) should be the culprit here: it pretends to be a `multipolygon`, but it's a relation containing only other multipolygons. This results in some invalid geometry operations [here](https://github.com/openstreetmap/iD/blob/1db51501a58ccc6021bf869ca21ad8e546427443/js/id/svg/labels.js#L368).
