### ISSUE TITLE
Update highway colors to match openstreetmap-carto

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#2764]
RE: gravitystorm/openstreetmap-carto#1736
Discussion seems pretty much settled.

Although the goals of iD and openstreetmap-carto are different, I think we should update our highway styling to match what they are doing.  Blue and green roads can be difficult to see on different backgrounds, and it would be weird for users of iD to see a drastically different road coloring than what is displayed on the main osm site.

That said, I think iD should retain *some* kind of color for `highway=tertiary` to make things less confusing for editing, so I'm planning to just pick something between the yellow `highway=secondary` and white `highway=residential` colors.

**Comment by M1dgard** [comment]
+1

**Comment by Stalfur** [comment]
Thanks @bhousel - some sort of clearer marking of tertiary in iD will help.

**Comment by pnorman** [comment]
You may want to use https://github.com/matkoniecz/openstreetmap-carto/blob/gsoc/scripts/generate_road_colours.py

It allows you to distribute a set of road colours across a range of hues by classification, and compute both fill colours and casing colours.

Even if you end up using different colours, being able to distribute them is very useful, and saves a lot of experimentation.

To customize it, you might want to change `road_classes`, `line_colour_infos["fill"]`, and `line_colour_infos["casing"]`

**Comment by matkoniecz** [comment]
Note, https://github.com/gravitystorm/openstreetmap-carto/pull/1736 was merged and it will be included in the next release (nearest one, [v.2.35](https://github.com/openstreetmap/chef/issues/36) was released before this merge).

> You may want to use https://github.com/matkoniecz/openstreetmap-carto/blob/gsoc/scripts/generate_road_colours.py

This script after merge resides at https://github.com/gravitystorm/openstreetmap-carto/blob/master/scripts/generate_road_colours.py

> Even if you end up using different colours, being able to distribute them is very useful, and saves a lot of experimentation.

Yes, one of my biggest mistakes during developing road colours was not starting from writing this script.

**Comment by bhousel** [comment]
>> Even if you end up using different colours, being able to distribute them is very useful, and saves a lot of experimentation.

> Yes, one of my biggest mistakes during developing road colours was not starting from writing this script.

Can you elaborate?  I'm not clear on what it means to "distribute" colors.

**Comment by matkoniecz** [comment]
Instead of manually selecting colour for every road type (motorway, trunk, primary, secondary in current script configuration) using this script it is possible to set hue, chroma and lightness range.

In script

> road_classes = ["motorway", "trunk", "primary", "secondary"]

sets list of roads over which colours will be distributed 

and for example

> min_h = 10
> max_h = 106

sets hue range

> line_colour_infos["fill"] = ColourInfo(start_l = 70, end_l = 97, start_c = 35, end_c = 29)

will cause set of fill attributes to be generated .

In that case motorway will be lch(70, 35, 10) and secondary lch(97,29,106), with trunk and primary in the middle. Script also converts from lch to rgb. In that case it outputs.

> @motorway-fill: #e892a2; // Lch(70,35,10), error 0.5
> @trunk-fill: #f9b29c; // Lch(79,33,42), error 0.7
> @primary-fill: #fcd6a4; // Lch(88,31,74), error 1.7
> @secondary-fill: #f7fabf; // Lch(97,29,106), error 1.7

So "try everything more saturated" means changing start_c and end_c values, rather than manually tweaking four separate colours trying to keep them equally separated without changing lightness and hue (what is nearly impossible to do in RGB space and taking a long time with manually tweaking lch and converting each new value separately).

I attempted to rewrite script to move setting data to top and it may be slightly more readable: https://github.com/matkoniecz/openstreetmap-carto/blob/clean/scripts/generate_road_colours.py (I am not happy about it and shield generation is still at the bottom with a special case of tertiary).

It seems that this script may be improved by properly separating setting wanted values and processing them. Also, probably some readme should be added at beginning.

**Comment by matkoniecz** [comment]
https://github.com/matkoniecz/openstreetmap-carto/blob/clean/scripts/generate_road_colours.py now has separation of setting data and processing it what hopefully should make more clear what is happening.

**Comment by bhousel** [comment]
@matkoniecz, @pnorman  That sounds so complicated!

Because iD uses SVG for everything, I just adjust styles live in Chrome developer tools:

![id live styles](https://cloud.githubusercontent.com/assets/38784/10144234/80668908-65ea-11e5-8264-2b3a535fc5d5.gif)

**Comment by gravitystorm** [comment]
FYI, I've just tagged the release of openstreetmap-carto that contains these new colours, so I expect it to be rolled out on the OSMF servers at some point soon.

https://github.com/gravitystorm/openstreetmap-carto/releases/tag/v2.36.0 is the release version (2.36.0)
https://github.com/openstreetmap/chef/issues/38 is the ticket for the OSMF server rollout.

**Comment by bhousel** [comment]
> FYI, I've just tagged the release of openstreetmap-carto that contains these new colours, so I expect it to be rolled out on the OSMF servers at some point soon.

Awesome!  I'm finishing up styling our preset icons to match the new colors, and will tag an iD release within the next few days..
