### ISSUE TITLE
In Spanish, the town "Vic" near Barcelona is called "Vique" it should be "Vic"

### ISSUE THREAD

**Issue by tmino** [openstreetmap/iD#2780]
Very sorry but I'm new to this (and not a developer nor any tech skills) I'm sure it's somehow possible to fix this myself just don't know how to do so. If someone could tell me I'd much appreciate it. Thanks!

**Comment by bhousel** [comment]
That's great that you want to get involved!   You don't need any tech skills to improve the map.  You can just find the spot on openstreetmap.org needs to be changed and click "Edit" to make your changes.

It looks like "Vic" already seems to have the correct name:
http://www.openstreetmap.org/node/1470839536

But we have an existing bug where we are showing the `old_name` under the multilingual name section, #2658, so that's why it shows up incorrectly.

**Comment by tmino** [comment]
![img_8394b](https://cloud.githubusercontent.com/assets/14296470/9882105/05e2d890-5bcb-11e5-945c-bbef8d830ae3.jpg)

Thanks for the quick reply. But in Spanish, on my phone, it says "Vique" (see red circle in attached image).

**Comment by bhousel** [comment]
> Thanks for the quick reply. But in Spanish, on my phone, it says "Vique" (see red circle in attached image).

I don't know why your phone shows it that way, that isn't our app.  Also your phone is displaying Google tiles, so I don't think it's OpenStreetMap data either.

**Comment by tmino** [comment]
Ok, thanks for the help!
