### ISSUE TITLE
Remove support for construction=yes without *=construction

### ISSUE THREAD

**Issue by jojo4u** [openstreetmap/iD#2790]
Currently iD renders a highway=unclassified or a building=yes with construction=yes as dashed line.
Using construction=yes without *=construction is considered a bad idea ("trolltag"). On the wiki page there are several advices against it: "deprecated", only "well defined combinations" of railway/highway/building.

http://wiki.openstreetmap.org/wiki/Key:construction

**Comment by bhousel** [comment]
It's obviously not "deprecated" if taginfo shows it used [48 549 times](http://taginfo.openstreetmap.org/keys/?key=construction#values).  So we do need to render it properly.

I agree it's not a very good tag, but iD doesn't have any support for adding construction tags outside of the raw tag editor, and users can add whatever tags they want.

I suppose in unambiguous situations, we could silently "upgrade" the tag.
e.g. `highway=residential + construction=yes` can be changed to `highway=construction + construction=residential`

**Comment by SHARCRASH** [comment]
I think the 2nd proposition is more logic:
- regarding manipulation of tags
- separates clearly the key terms in a database
- gives a shorter process to update the tags (just erase the construction), normal it's more logic in key terms. ^^

**Comment by jojo4u** [comment]
@bhousel 
There are 48 533 construction=yes
38 630 of those are tagged in combination with building=construction. Other combinations like highway or railway are below 1 000 and not shown on Taginfo.
That leaves at most ~10 000 elements of contruction=yes without *=construction.

**Comment by SHARCRASH** [comment]
@jojo4u 
So what do you do of tag combinations such highway: value known + construction:yes ?

**Comment by SHARCRASH** [comment]
@jojo4u 
So what do you do of tag combinations such as highway: value known + construction:yes ? That combination implies that the final construction is known/informed. In my opinion, there must be a step in between so that people can give updates given that the point of a database is to inform.

**Comment by SHARCRASH** [comment]
I decided to dig that tag since i wasn't very familiar with it (i mainly plot natural elements). I see now more clearly the mechanics behind it. Sorry for my previous comments/suggestions then.

So i don't get why there is the tag: construction=yes. This implies that it can be combined to anything and indeed deprecated apparently in the Wiki but rendered anyway despite it saying the contrary. It's confusing...

On another side, i always thought that "subtags" of combination tags (sorry i don't know the exact term usually used) should always be named with some sort of suffix, for example "_type", to avoid misuse, like the "fence_type". If you check its stats of combinations with its normal combo tag "barrier=*" both number are very close, only a few 100s.

**Comment by jojo4u** [comment]
I did some filtering on a recent planet file:
There are 7550 elements with contruction=yes and no *=construction.

@SHARCRASH Subtags (called properties) have very different styles. Read tag design here: http://wiki.openstreetmap.org/wiki/Any_tags_you_like

**Comment by slhh** [comment]
@bhousel Upgrading a tag silently is an automated edit even if the situation is unambiguos. Thus it needs to follow the automated edit policy even if you call your bot an editor. Especially it is not ok to attibute an user for a change who hasn't any chance to decide what he is changing.

I believe the situation isn't unambiguous anyway.
Some of the construction=yes might mean, that some construction work is still done, but the highway is not closed or not closed for all kinds of traffic. In this case construction=yes needs to be changed to construction=minor.

Construction=yes is often used on minor highway objects like steps, footway, or service. In this case the construction period might be too short in order to use construction anyway.
In case of these minor highway objects the official tagging scheme of using highway=construction isn't very useful. At least rendering highway=construction as a road under construction would be very bad in this case.

**Comment by bhousel** [comment]
> Thus it needs to follow the automated edit policy even if you call your bot an editor. Especially it is not ok to attibute an user for a change who hasn't any chance to decide what he is changing.

We already upgrade a small amount deprecated tags, but only in situations where the upgraded tag is functionally equivalent to the deprecated tag.  So it's really not a change.

> Some of the construction=yes might mean, that some construction work is still done, but the highway is not closed or not closed for all kinds of traffic. In this case construction=yes needs to be changed to construction=minor.

If it means that, then the feature is mistagged.  We're not talking about situations like that.

>  In case of these minor highway objects the official tagging scheme of using highway=construction isn't very useful. At least rendering highway=construction as a road under construction would be very bad in this case.

I don't see why it matters.   Upgrading `highway=steps + construction=yes` to `highway=construction + construction=steps` is an equivalent change.  They mean exactly the same thing, but the latter doesn't have a trolltag that is likely to mess up downstream data consumers.

**Comment by abdeldjalil09** [comment]
Hi,
I need also preset for highway=construction and railway=construction.

**Comment by bhousel** [comment]
> I need also preset for highway=construction and railway=construction.

#2341 would let users mark features as "under construction".  It's a hard problem because OSM lifecycle tagging is complicated.
