### ISSUE TITLE
Bug straightening way with coincident start/end nodes

### ISSUE THREAD

**Issue by franco999** [openstreetmap/iD#2792]
I do not know if this bug is already reported. 
Here I embed a video with the error. https://cloud.openmailbox.org/index.php/s/JxecLPR41cL0IsN
The error occurs when I press the S key and then do zoom.

I do not know if the error is general or not. The area that I used to display the error is this: http://osm.org/go/MyGi96i8i

**Comment by SHARCRASH** [comment]
I successfully recreated the issue elsewhere. It occurs because the multipolygon is not closed in its outer line, between this [end node](http://www.openstreetmap.org/node/3751100791) and this other [end node](http://www.openstreetmap.org/node/3751100788). So iD considers the element as a **line** to straighten (see the editing tools), not an **area** to reshape squarly as it should. That might be the reason of conflict in terms of iD programmation. Same for the building, the line ring is not closed/connected in its ends as it should (same position as the schoolgrounds). Once closed the edit tools show the proper tools If you're this [user named franco999 in OSM](http://www.openstreetmap.org/user/franco999), apparently you are new, so i just let you edit it correctly for practice.  :) 

By the way this unconnected node can be easily detected thanks to OSM inspector (in the View:Multipolygon list). See [here](http://tools.geofabrik.de/osmi/?view=multipolygon&lon=-60.65561&lat=-33.00586&zoom=18&overlays=invalid_geometry_hull,duplicate_ways,intersections,intersection_lines,ring_not_closed_hull,ring_not_closed,unconnected_end_nodes,touching_inner_rings_hull,touching_inner_rings,role_mismatch_hull,role_mismatch,duplicate_tags_hull,duplicate_tags). People should really consider checking it time to time.

This rises a constatation: multiple nodes overlapping perfectly not necessarily from the same "way" (line) can't be distinguished from a single node in a way, both are white... If a warning during the edits (node slowly blinking) and during the save process (a message like the untagged line) is reported, it would help preventing this kind of mistake. Myself working much with multipolygons, i would really welcome this as a bliss since i happen time to time to do it even with experience. I even avoid deconnecting nodes/ways during edits of lines to avoid a negligence to reconnect.

**Comment by franco999** [comment]
@SHARCRASH Thanks for answering! 
I do not understand much English but, so understood, and I corrected errors multipolygons not closed.  I did not realize the mistake.
My OSM user is "mweper" and not "franco999". Regards.

**Comment by jfirebaugh** [comment]
I can understand that this has something to do with straightening member ways of multipolygons, but not what the exact issue is. @SHARCRASH, can you provide a specific minimal set of steps to replicate this?

**Comment by SHARCRASH** [comment]
Sorry if i didn't reply directly, had other priorities when you had asked and then forgot.
Here are the steps to recreate the issue even without an MP relation:
1) create a closed polygon with the line tool (no area, no MP), let's say a trapeze/near rectangle.
2) if you reselect the line now, you can see that the square shaper tool is active, normal as it's a closed line, press the S shortcut, it will trigger the square tool. 
3) then cut a node and disconnect it
4) reconnect both lines
5) if you reselect the line now, you can see that the straighten line tool is active, normal as it's an unclosed line, **BUT ** press the S shortcut, the 2 extreme nodes will be actually joined/overlapped and even disappear if you deselect the element or/and zoom. It should be normally avoided since when the line is "too bent", the function won't trigger the straighten tool, but it does propose the straighten line tool function.

Hope this helps! Ask further precisions if needed.

**Comment by bhousel** [comment]
@SHARCRASH thanks for the detailed instructions..
I do see that it's possible to get into a situation where a user can create a geometry that confuses the straighten tool. The end result is a "line" with just 2 points in the same place.  I made a screencast of the steps to cause this.. 

![square_straighten_bug](https://cloud.githubusercontent.com/assets/38784/14943603/5b79fe3e-0fab-11e6-8d43-7ce3dfea5090.gif)

**Comment by bhousel** [comment]
Turns out that the splitting and joining is unnecessary.   You can just disconnect a closed line at its connecting node, and the straighten operation will happily remove all the points in the line.

![square_straighten_bug2](https://cloud.githubusercontent.com/assets/38784/14943653/60f04e08-0fac-11e6-8f6a-2e93321bcd2a.gif)
