### ISSUE TITLE
Always show source tag in edit feature pane

### ISSUE THREAD

**Issue by vespax** [openstreetmap/iD#2821]
Adding sources to data is important.  Currently iD doesn't show the source bar under Edit Features as a permanent tag to include (think name tag).  I would like to see source displayed, not as a requirement, but as a soft prompt to encourage more sourcing of data (whether it be aerial images or other source).  

As it is now, you need to search for source within "Add Field" and not everyone will remember to do this.

**Comment by jfirebaugh** [comment]
Hi, thanks for the suggestion. This has been brought up before -- see #1764. Current consensus is against tagging individual objects with a source, because a single source tag is inadequate when a feature's attributes may have each come from differing source, or when multiple users edit a feature. Instead, iD automatically adds an `imagery_used` tag to the changeset based on what background layers you've had active while editing.

**Comment by vespax** [comment]
I understand that for when digitizing roads or lakes and whatnot.  I’m more concerned about features such as business locations (hotels, restaurants, banks, etc) that can’t easily be derived from aerial imagery and where a specific source tag would provide some validation that it is a correct location with associated tags.  It might be worth considering more in specific case scenarios such as points of interest.

**Comment by stragu** [comment]
If anyone else ends up here, wondering the same thing as @vespax : it is possible to use the `source:geometry` key on the changeset to have this information recorded in the feature's history.

[Current recommendation](https://wiki.openstreetmap.org/wiki/Key:source) is to include the source tag(s) on the changeset instead of single features, for the reasons mentioned above. And to split changesets to avoid including multiple sources, if at all possible.
