### ISSUE TITLE
bicycle_parking tag is not freeform, it has a defined set of values

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#2837]
This set is not strictly closed, but it is stable. It is defined at http://wiki.openstreetmap.org/wiki/Key:bicycle_parking

See also #2835

**Comment by bhousel** [comment]
If it is not a strictly closed set, then a combo field (which it is currently) is the appropriate field type.

Combo fields pull popular suggestions from taginfo, but still allow a user to type their own value in its place.

**Comment by matkoniecz** [comment]
The problem that I am attempting to solve is that as result parts of interface are translated and parts not. Maybe it should be solved by allowing to translate tag values, at least popular ones?

**Comment by bhousel** [comment]
Yes #2708 is our issue for tracking this.  We haven't thought of a good way to display a mix of translated and raw values in a combo box.

**Comment by matkoniecz** [comment]
Displaying mix is not worse that current mix of translated and untranslated...

**Comment by matkoniecz** [comment]
> If it is not a strictly closed set, then a combo field (which it is currently) is the appropriate field type.

I still think that selection panel (for common values) with text field for new/rare values would be better.

**Comment by naomap** [comment]
I strongly agree with matkoniecz. Tag values for keys such as surface and bicycle_parking are translated in JOSM presets, it feels really strange they cannot be translated in iD which is meant to be easier to use. Also, favoring freeform values is not an argument IMHO, as iD enables users to add any key and value in the spreadsheet at the bottom of the edit panel.

**Comment by bhousel** [comment]
> I strongly agree with matkoniecz. Tag values for keys such as surface and bicycle_parking are translated in JOSM presets, it feels really strange they cannot be translated in iD which is meant to be easier to use. Also, favoring freeform values is not an argument IMHO, as iD enables users to add any key and value in the spreadsheet at the bottom of the edit panel.

If the set of allowable values for a field is not fixed, we would end up mixing translated and untranslated strings in the dropdown and that would be more confusing than just displaying all the values be in one language.  The tag editor ("spreadsheet") at the bottom of the edit panel also only shows only raw values and makes no attempt to translate them.

We could maybe display both strings next to each other ("paved - _gepflastert_").  It would mean adding a lot more (many thousands?) strings for people to translate.  This might be even an entirely new project that scrapes the top values from taginfo for certain keys.

(Also, I'm totally ok if you use JOSM if you like the way that it displays value lists better - just because they do a thing doesn't mean we are going to do it in iD).

**Comment by matkoniecz** [comment]
> If the set of allowable values for a field is not fixed

I think that making available values limited to a fixed list would be preferable here.

> This might be even an entirely new project that scrapes the top values from taginfo for certain keys.

BTW, StreetComplete needs project like this for similar reasons - see https://github.com/ENT8R/tags2names/issues/1

**Comment by naomap** [comment]
The set of values is never fixed in OSM. The tag fire_hydrant:type has 141 different values according to taginfo and it can be translated, bicycle_parking shows 330 different values and cannot be translated : where is the threshold ? I would argue that the best of both worlds, is to show translated values in the dropdown, and leave actual DB values in the edit panel. This makes life simpler for beginners, and enables advanced users to go beyond.

The point is not about using JOSM. The point is about explaining to new users why values for a tag such as bicycle_parking, with a fairly short list of well documented values, is not translatable, whereas other tags, such as fire-hydrant:type, are translated. Both tags have the same role - refining the description of some equipment : where is the logic from the user point of view ? 

I realise this is potentially a lot of strings to translate, but the amount of work is not something that ever stop mappers. Also this can be done gradually, things won't stop working if we open up these translations. 

Please do not overlook the language barrier a lot of people face, I'm convinced this puts off a lot of people who can't or don't want to use english words (I'm not talking about me of course ;-)

**Comment by bhousel** [comment]
> Please do not overlook the language barrier a lot of people face, I'm convinced this puts off a lot of people who can't or don't want to use english words

Sure, I agree with you.  The issue was closed before because we thought it was too hard to do.  I reopened and added my thoughts:
 https://github.com/openstreetmap/iD/issues/2708#issuecomment-370112193

**Comment by slhh** [comment]
I wouldn't be able to name many of the bicycle parking types even in my native language. I had to check the wiki, and would find the English value only.
