### ISSUE TITLE
Use standard list of paved tags

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#2847]
Follow-up to #2564

iD currently has
```js
iD.pavedTags = {
    'surface': {
        'paved': true,
        'asphalt': true,
        'concrete': true
    },
    'tracktype': {
        'grade1': true
    }
};
```

The standard [wiki-derived](https://github.com/gravitystorm/openstreetmap-carto/blob/d0d9afae54b6dc79e039b01d6cc339260f8676e8/project.yaml#L511-L515) list for the paved tag is is
```sql
CASE WHEN surface IN ('unpaved', 'compacted', 'dirt', 'earth', 'fine_gravel', 'grass', 
                      'grass_paver', 'gravel', 'ground', 'mud', 'pebblestone', 'salt',
                      'sand', 'woodchips', 'clay') THEN 'unpaved' ELSE 
CASE WHEN surface IN ('paved', 'asphalt', 'cobblestone', 'cobblestone:flattened', 'sett',
                      'concrete', 'concrete:lanes', 'concrete:plates', 'paving_stones',
                      'metal', 'wood') THEN 'paved' 
```

**Comment by bhousel** [comment]
Really?  Wood and cobblestones?  Maybe in OHM that would be considered paved..

**Comment by pnorman** [comment]
As discussed in the osm-carto, you can draw the distinction different ways for different purposes. If you're riding a bike, compacted is better than metal or the stone based options, if you've got a dirt bike, different options are okay, if you're concerned about washout, other options are okay, etc.

This is why we went with the list from the wiki

**Comment by bhousel** [comment]
Ok, I guess we agree that whether or not a surface is "paved" is a subjective opinion.  

My goal for rendering the surface tags in iD is to *call attention to map features that might be mistagged.*  

The [surface wiki page](http://wiki.openstreetmap.org/wiki/Key:surface) also says that "For roads for motor vehicles there there is normally an assumption that the surface is surface=paved unless otherwise stated."

This is helpful because in places like old city Philadelphia, the cobblestoned streets stand out because they have an interesting surface tag.  I can look at this map and know right away that they are tagged correctly:

<img width="550" alt="screenshot 2015-12-01 14 42 37" src="https://cloud.githubusercontent.com/assets/38784/11513912/d3bef9ec-9843-11e5-80b7-cfba96f4ab08.png">

In Addis Ababa where gravel and unpaved streets are normal, this street stands out because it is missing a surface tag:

<img width="550" alt="screenshot 2015-12-01 15 18 33" src="https://cloud.githubusercontent.com/assets/38784/11513951/0a0bcf2a-9844-11e5-9603-8b71d87ae48b.png">

I recognize that it's an opinionated rendering, so what I've done in 0b93fef is now I'm including `surface` and `tracktype` as secondary tag classes.  This means that anyone can override these defaults and make an iD that renders differently surfaced roads however they want to.

Given that the goal is to help people map surfaces correctly (not routing, not urban planning, etc) I'm going to close this issue - but I am totally open to evolving the paved/unpaved list if we get feedback from mappers about how helpful (or annoying) the "bumpy" unpaved style is.

**Comment by matkoniecz** [comment]
> Really? Wood

wood is the most commonly found on smaller footbridges/cyclebridges.
