### ISSUE TITLE
Add country to address field

### ISSUE THREAD

**Issue by g4rpch** [openstreetmap/iD#2852]
Dear all
Would be really appreciate if you could add address:country on the preset Address
![unknown](https://cloud.githubusercontent.com/assets/15292575/11499105/f6cc5c10-9823-11e5-979b-4a8cf0cd648a.jpg)
Thanks a lot
G4rp

**Comment by hannni** [comment]
The address preset has some further problems: for instance it offers no way to set `addr:place` instead of `addr:street`

**Comment by bhousel** [comment]
> Would be really appreciate if you could add `address:country` on the preset Address

Isn't it really easy to know what country a feature is in already?  It's not like state or postal code boundaries which are more arbitrarily drawn.

(Yes I know there are weird situations where [countries swap enclaves](http://www.bbc.com/news/world-asia-33725843) and it is not so clear what country a place is currently in.)

But _generally_ is it encouraged or discouraged to add country tags to addresses in OSM?  Is it a dumb tag like `oneway=no`?

I'm not against the idea, but just want discussion on how necessary it is, and consider how forcefully people will complain if we add it.

**Comment by bhousel** [comment]
> The address preset has some further problems: for instance it offers no way to set addr:place instead of addr:street

Can you open a separate issue for `addr:place`?  I don't know anything about it..

**Comment by jfirebaugh** [comment]
Omitting `addr:country` is intentional. While there isn't 100% consensus on whether or not it's preferable to duplicate country membership information in the database or determine it based on administrative boundaries (see e.g. [this mailing list thread](https://lists.openstreetmap.org/pipermail/talk/2011-May/058094.html)), I'm firmly in the "determine it based on administrative boundaries" camp, and not asking for a country for every address is consistent with iD's philosophy of making contribution as easy as possible. Therefore we aren't planning to change this behavior. If you'd like to add `addr:country` tags, you are of course free to do so using the raw tag editor.
