### ISSUE TITLE
Use user language for default translated names

### ISSUE THREAD

**Issue by planemad** [openstreetmap/iD#2882]
If a user chooses to translate an existing string, default language should just be the user language, and the language list should be ordered according to the OSM user preferences for easy selection.

![screenshot 2015-12-21 12 50 25](https://cloud.githubusercontent.com/assets/126868/11925462/8f44977e-a7e1-11e5-8e73-da1f444639bb.png)

Currently the user needs to pick the language each time from a long dropdown list and is not very convenient especially for those working on non latin scripts which have no alphabetical ordering in the list.

**Comment by yogiks** [comment]
:+1:

**Comment by kepta** [comment]
@bhousel , any head start on this one?

**Comment by bhousel** [comment]
Sure.. `localized.js` contains the code for this field.  It's a normal input field with a '+' button that lets users add a localized value.

[The click handler for the '+' button](https://github.com/openstreetmap/iD/blob/master/js/id/ui/preset/localized.js#L41) calls [`addBlank`](https://github.com/openstreetmap/iD/blob/master/js/id/ui/preset/localized.js#L50-L54).

You can rename `addBlank` to `addNew`, and change the code in there to:

* get user's locale using `iD.detect().locale.toLowerCase()` 
* probably need to split on `'-'` and take only the first part
* use that as the default value for `lang` instead of setting it to `''`
* ^ but don't do that if 
  * the user's lang starts with `en` or
  * an entry for that language already exists in `data`
* if either of those conditions are true leave default new entry as `lang: ''`
