### ISSUE TITLE
Support `addr:place` in the Address preset

### ISSUE THREAD

**Issue by johanneshoehn** [openstreetmap/iD#2898]
Some villages don't have street names, but use the place name instead of a street name in addresses.
This is very common in my region. For instance the village Hohlweiler belongs to the city Scheinfeld and has no street names. Addresses are of the scheme: (name), Hohlweiler (housenumber), 91443 Scheinfeld.

The [OSM wiki recommends](http://wiki.openstreetmap.org/wiki/Key:addr:place) using `addr:place` instead of `addr:street` in those cases. iD only supports `addr:street`. It would be nice to be able to select wether to input `addr:place` or `addr:street` and even better if there was some kind of automatic detection that the name matches up with the place name.

**Comment by stephan75** [comment]
That whenever this feature request should be implemented, please have a validation that addr:place can only be added to an object when addr:street is NOT used. Because according to the OSM wiki definition these two keys should not co-exist on an object!

**Comment by Natsuyasumi** [comment]
I guess it could be solved by adding a tickbox which would _swap_ `addr:street` with `addr:place`.

**Comment by RicoElectrico** [comment]
I second this as very needed (as much as 6M uses of addr:place worldwide). There are many confused newbies, here's one: http://www.openstreetmap.org/changeset/47780046 . They always struggle with it, and it's not even their fault.

@bhousel If you need help on figuring out how to do this properly UX-wise, I think you may ask out on the mailing list. I don't know about other countries, but in our case it would suffice to have "place with street names"/"place without street names" option, or a tickbox with "address without a street name" which as mentioned would change "street" to "place".

**Comment by bhousel** [comment]
> I don't know about other countries, but in our case it would suffice to have "place with street names"/"place without street names" option, or a tickbox with "address without a street name" which as mentioned would change "street" to "place".

Yes, I am ok with sticking a radio button somewhere at the top of the address block in the situation where a country has multiple alternate address formats.  This is extra complicated though because iD would need to:

* Somehow add support for alternate per-country address formats to the address.json field schema (fine)
* Let the user tick the radio button to change the address field between alternate formats (easy)
* Detect how the radio button should be ticked when parsing existing address data (harder)

**Comment by Natsuyasumi** [comment]
So, I think:
`addr:place == * && addr:street != *` --> Place without street names
`addr:place != * && addr:street == *` --> Place with street names
`addr:place != * && addr:street != *` (or simply no tags) --> Place with street names, beacause this kind of places are more common.


The only problem comes when `addr:place == * && addr:street == *` (taginfo shows ~1M combinations).

**Comment by Natsuyasumi** [comment]
@rmikke Of course there is a need for different address formats - you can see how Czech or [Japan](https://en.wikipedia.org/wiki/Japanese_addressing_system) address formats are different from Polish or German formats.

In the article [you provided](https://wiki.openstreetmap.org/wiki/Key:addr:place) there is a big bolded text explaining that addr:place **does not** mean a part of city - addr:suburb should be used instead.

If you want to check addresses with addr:place != addr:city you can play around with [this Overpass query](http://overpass-turbo.eu/s/pCr).
With such examples in Poland it simply looked like addr:city was mistaken with post office.
On the other hand, I have found some addresses in Germany ([like this](http://www.openstreetmap.org/node/3529415712)) where there were no street names in cities, so it means that there are places where addr:city can be different than addr:place, but this does not require any more options - it falls for the `Place without street names` scenario.

**Comment by stefanb** [comment]
We have the same situation in Slovenia. Smaller villages do not have street system and in these places the addresses are name_of_place + number, or in OSM schema: `addr:place` + `addr:housenumber`.

Currently the address format is
https://github.com/openstreetmap/iD/blob/960e896551558b9ea9c3478c33602f57936eab79/data/address-formats.json#L33-L39
but that would need to be changed to easily support setting `addr:place` instead of `addr: street`.

It would be trivial to show both input fields, but users would be confused, and likely set them both to the same value, instead of leaving one empty.

A good compromise would be to introduce a new input type, eg `streetOrPlace` which would list nearby streets and places in the drop-down and autocomplete options, then set the appropriate tag automatically.
