### ISSUE TITLE
UI hint for "best" imagery

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#2902]
from irc @bgirardot

>10:33:35 AM BlakeGirardot: Just letting us know iD has choosen something besides what I consider "default" bing/mapbox and that might be my issue that I consider bing/mapbox "default"
10:33:48 AM bhousel: yeah i think that's reasonable

Open to suggestions here, but my thought for this is to add something next to the imagery name in the background imagery list, like a :star:, and tooltip it with text like "Best known imagery source for this location" with link to our FAQ with more info and link to editor imagery index project..

**Comment by bhousel** [comment]
history: #2841 #2826 #1310

**Comment by bgirardot** [comment]
Thank you for opening this @bhousel 

I like your idea, but would like to think about the whole issue just a bit more and get some feedback from other people who share my use cases related to new mappers and mapping projects with many mappers each selecting their preferred osm editing tool.

I guess that also raises the question of what happens when we (OSM Tasking Manager) pass a specific imagery source to iD and the user moves around the map, would iD maybe not honor that passed in imagery source?

**Comment by bhousel** [comment]
> I guess that also raises the question of what happens when we (OSM Tasking Manager) pass a specific imagery source to iD and the user moves around the map, would iD maybe not honor that passed in imagery source?

That's a fair concern, but no we're not going to do that:
1. If you pass in a specific imagery source in the url, iD will always use it.
2. As the scrolls around, we aren't going to switch imagery for them.

This issue is only for UI hinting in the imagery list, with the goal to provide more transparency to mappers when there might be better imagery for them to use, and some way of telling them more about where the imagery comes from, and sending them to the imagery project for more info or discussion.

crappy mockup:
<img width="254" alt="screenshot 2015-11-24 11 18 16" src="https://cloud.githubusercontent.com/assets/38784/12205424/8849d1de-b608-11e5-8a69-10c9756e1cab.png">

Maybe under there a tiny "Where does this imagery come from?" link...

**Comment by bhousel** [comment]
Note:  don't work on this until #2941 is settled
