### ISSUE TITLE
Address housenumber field loses focus when typing

### ISSUE THREAD

**Issue by Bottaro** [openstreetmap/iD#2903]
The edit field 'housenumber' lost the focus each time a digit is typed in. 
![2016-01-09 19_40_22-openstreetmap](https://cloud.githubusercontent.com/assets/16626314/12217762/7f36f290-b70a-11e5-9721-80896b6f63ad.jpg)
(field is marked red)
Therefore it is not possible to fill in serveral digits in a row.
This happens in Firefox as well as in MS Edge since 1 day, so something must be broken in the meantime.

**Comment by manfredbrandl** [comment]
I can confirm loosing the focus with Chromium Version 47.0.2526.80 Built on 8.2, running on Debian 8.2 (64-bit). It is still possible to type in housenumbers with more than one digit, but you have to refocus with the mouse after every digit.

**Comment by speedbiker** [comment]
I have even opened a thread concering this problem in the OSM forum. http://forum.openstreetmap.org/viewtopic.php?id=53272
I use Mac with Google Chrome and have the same problem as described.

**Comment by bhousel** [comment]
Yes, it's a bug, probably related to 2bbe968.. I'll try to fix it asap.

**Comment by speedbiker** [comment]
I still have the problem with my setup (Mac + Chrome). I made a reload (Command + R), but the problem still occurs.
BTW: is it possible to modify the process of address entering in that way: one click into the field "addr:street" and then jumping to the following fields (addr:housenumber, addr:zipcode etc.) by clicking just the Tabulator button?
This would increase the speed of entering adress data significantly, because now, you have to click into each field separetly, because the browser is loosing the focus. I mean, the process works like this: click into a field, typing in something, then click once again, typing in some stuff, click again. If I could use the Tabulator button, the fous jumps from field to field and I do not have to click every time. Just when starting to fill in the address information and then, when it's finished. Hope it's clear, what I mean.

**Comment by ecatmur** [comment]
speedbiker: It takes time for a bug fix to reach openstreetmap.org (there has to be a release made, and then that release has to be installed).
Once this bug fix is released and installed on openstreetmap.org using the Tab key will work again.

**Comment by bhousel** [comment]
>  the problem still occurs.

@speedbiker I am planning to push a bugfix release today that includes the fix.  In the meantime you can test the latest code at:  https://openstreetmap.us/iD/master/

> is it possible to modify the process of address entering in that way: one click into the field "addr:street" and then jumping to the following fields (addr:housenumber, addr:zipcode etc.) by clicking just the Tabulator button?

Yes, the new code in 23b22fd fixes this also..
