### ISSUE TITLE
add map features master checkbox

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#2904]
For (Shortcut F) map features, there are checkboxes for "points", "major roads",
"minor roads", etc. but no additional checkbox at top to turn them all off or on at once.

**Comment by slhh** [comment]
Hiding all map features seems to be useful in order to make the background imagery more visible, but I believe it is required temporarily while editing the map features (dragging nodes, drawing lines etc.). Idea for the user interface: Hide all map features while spacebar is pressed down.

>For (Shortcut F) map features, there are checkboxes for "points", "major roads",
"minor roads", etc. but no additional checkbox at top to turn them all off or on at once.

I'm not sure what is intended here:
* Additional checkboxes overriding the other checkboxes, which doesn't seem to be useful.
* Buttons setting all checkboxes to on or off, which could save a view clicks.

**Comment by jidanni** [comment]
> Buttons setting all checkboxes to on or off, which could save a view clicks.
Yes.

**Comment by bhousel** [comment]
> Idea for the user interface: Hide all map features while spacebar is pressed down.

I usually just hit 'W' to toggle wireframe mode when I want to see the background a little better.  Occasionally even the 1px lines obscure what I'm trying to see, but then I just zoom in more.  Maybe this is helpful?

Either way I'm ok with adding an "All" checkbox for the feature filters.

**Comment by jidanni** [comment]
Maybe I will try W next time I am editing.

**Comment by bgirardot** [comment]
An easy way to hide all the map features would be great. The 1 key suggestion to quickly hide and then when released they appear again would be great.

I too will try the W next time.
