### ISSUE TITLE
Universal fields (like "address") being applied to features that don't need them

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#2908]
I was seeing that some users are adding `addr:*` to the highways, specially `addr:street` with exactly the same value as `name`.

Looking at iD we can see that it's suggestive to include the address:

![Address suggestion](http://i.imgur.com/qJHOFsK.png)

And when the user clicks on it, of course he fills all the fields:
![Address](http://i.imgur.com/SFA8pFb.png)

What he doesn't understand and what iD doesn't make clear is that the `name` already defines the address of the street and that country, state, city, etc, can be obtained with spatial indexing.

Could iD stop inducing the user to include address on the streets?
*Address* (and maybe *phone* and *website* too?) are fields that shouldn't be available for highways.

**Comment by bhousel** [comment]
Weird, that's not something I would expect anybody to do.  We're certainly not "suggesting" that they add address tags to highways - and it's a bit unfair for you to say that..

What do the users say when you tell them that it's not necessary to add this?   "iD made me do it?"

I feel like we could add all kinds of logic to the "add field" dropdown, but people would just add it anyway in the raw tag editor and iD would still get blamed.

It's definitely one of those things where it would be faster to just talk to the user and remove the data than for me to spend time making changes to iD.

**Comment by naoliv** [comment]
Sorry if "suggesting" was misused (I really lack a better word for this; maybe "inducing" will get misinterpreted as well). Read it as "Should not include 'Address' in  'Add field' with a highway selected", please.

From what I saw this is what happens:
The user inserts all the highway data. Then he looks at "Add field - address" and misunderstand that the street address should be defined there, in the address fields.
The primary issue here is, of course, the lack of knowledge that `name` is the street address itself (and that there is no need to fill `addr:street` with exactly the same information).

Hidding this field should help avoid such cases.

**Comment by bhousel** [comment]
Ok, I understand. 

I have had the opportunity to watch first time users interact with iD and I agree that some people think that every single field must be filled in.  Maybe users have an expectation of how web forms work elsewhere and they are already trained to fill out fields completely, or trained to look at the labels to see which fields are required.  So I can see how a new user might misread a label like "Add field" as "You need to add more fields".   Maybe "More fields" would be clearer.

OSM is weird in that _everything_ is optional, and we don't really communicate this concept well.  

Anecdata:  I once saw a brand new user at an OSM event get really frustrated because they were adding a footpath, got down to the "Lit" checkbox, and couldn't remember whether or not the the path was lit - they wanted to stop editing just because they thought all the fields were required and didn't want to add anything wrong.  

Also worth mentioning that this particular user chose to skip all the help and walkthrough stuff because they wanted to see if they could figure things out on their own.  And if we do our job really well, they should be able to.

**Comment by pnorman** [comment]
I think there's two issues here. One is that we aren't communicating well that fields are optional, not required, and the other is that we shouldn't be suggesting address on all objects, as in some cases it's not normally appropriate to add address tags **and** someone might be mislead into adding them.

**Comment by stephan75** [comment]
issue title now: "Universal fields (like "address") being applied to features that don't need them" ...

Hmmm, I would even say that "applied to features where they are wrong"

Just an example: all OSM keys starting with addr:xxx are logically wrong on objects with highway=* or place=*

JOSM validator is detecting these combinations, and marks them as errors / warnings.

So do we need a kind of validation inside iF before data saving,
or a fine-tuned user interface that prevents (or at least gives no hint to do so) novice users from e.g. adding address data to highways??

**Comment by bhousel** [comment]
> Just an example: all OSM keys starting with addr:xxx are logically wrong on objects with highway=* or place=*

Are you sure?  Taginfo suggests that `highway=services` and `place=farm` are often combined with `addr:xxx` tags.

> So do we need a kind of validation inside iD before data saving,
> or a fine-tuned user interface that prevents (or at least gives no hint to do so) novice users from e.g. adding address data to highways??

iD has a few save-time validations, but given the free-tagging nature of OSM we will never be able to capture all of the currently accepted rules for what tags go with what other tags.

Validation is an important and challenging enough project that it really deserves to live outside of the editors.  If this is something you have a passion for, I do urge you to contribute to keepright or osmium, both of which could use help, or possibly even start a new project that combines the best of both approaches.

**Comment by pnorman** [comment]
5.1k `highway=services` ways, 72 with `addr:housenumber`.

For linear highway features I'd say the false positive rate on addr tags is likely to be **much** higher

**Comment by bhousel** [comment]
Let's not do this.
