### ISSUE TITLE
Better description of "Unclassified Road"

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#2916]
Unclassified is being taken to mean a road they do not know the type of by en_US people at this Seattle Missing Maps event. A more appropriate name should be used, but I'm unable to think of one.

**Comment by bhousel** [comment]
iD has both:
* [`highway=unclassified`](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dunclassified), displays as "Unclassified Road"
* [`highway=road`](http://wiki.openstreetmap.org/wiki/Tag:highway%3Droad), displays as "Unknown Road"

I feel like in the US, "Unclassified" generally means "unknown", and in other parts of the world "Unclassified" sometimes serves an actual purpose as a road with a legally different status than residential.

I really can't think of a better en_US name either.  And if we're using it wrongly here in US by convention, we should probably just leave it as is, rather than trying to rename it and then risk having that wrong thing get mistranslated.

**Comment by pnorman** [comment]
cc @systemed, for a UK perspective

When I get back from vacation I can reach out to some US people asking for words.

I would not assume that a literal translation of the preset name for highway=unclassified would be appropriate for any other language. We have to make sure that translators are aware of what they're translating. In a way, for preset names, **all** languages are a translation from raw tag values, not from en_US.

**Comment by systemed** [comment]
P2 has always called it "minor road" for en_*, even en_GB, and I'd strongly recommend that.

Unclassified is one of those endearing OSM historical artefacts and isn't even a 1-1 mapping in the UK - most highway=tertiary roads in the UK are unclassified, for example, depending how you define it. (Similarly, most highway=trunk roads in the UK aren't trunk roads, and all highway=primary are officially "non-primary".)

**Comment by jfirebaugh** [comment]
I think "Minor Road" is an improvement. Let's use that.

**Comment by julien-noblet** [comment]
Mistake in translation:
In French iD says : "Route secondaire"
It should be "Route mineure".

**Comment by bhousel** [comment]
Thanks @julien-noblet, I think this has already been fixed on transifex here:
https://www.transifex.com/ideditor/id-editor/translate/#fr/presets/11399168
