### ISSUE TITLE
Pedestrian Crossing defaults with crossing=zebra

### ISSUE THREAD

**Issue by DaveF63** [openstreetmap/iD#2918]
Hi
Pedestrian Crossing defaults with crossing=zebra. This is incorrect tagging. It should be crossing_ref. 

As it's predominantly a UK classification I'm uncertain it should even be a default.

**Comment by bhousel** [comment]
Honest question: is there a difference between: 
`crossing=zebra`
and
`crossing=uncontrolled + crossing_ref=zebra`

They seem the same to me.. I really don't see the point of `crossing_ref`.

**Comment by DaveF63** [comment]
Zebra is (mainly) a UK nickname*. Think of it like alt_name or loc_name. I'm sure there are more types of uncontrolled** crossing around the world than just black & white markings.

* A Toucan crossing for bikes & walkers is a play on words, as in 'Two can' cross.

** Not really the proper place to discuss this, but I don't see zebras as uncontrolled. In the UK at least the pedestrian at the kerb acts as a control in the same way a red traffic light would do.

**Comment by bhousel** [comment]
> Zebra is (mainly) a UK nickname. Think of it like alt_name or loc_name

Nope. `crossing=` is the key that says "a crossing is here", and `crossing_ref=` is the "alt name".  The value for crossing says what kind of a crossing it is.  That's really the only way that makes any coherent sense, and falls in line with how other tags in OSM work.  It's very unfortunate that the values for crossing are a mess.

> but I don't see zebras as uncontrolled.

I agree 100%

> Not really the proper place to discuss this

Right here is the only place where I will discuss this.  If you were going to suggest moving the discussion to the wiki or to the tagging mailing list, forget it.  I'm done with those.

**Comment by DaveF63** [comment]
>Nope. crossing= is the key that says "a crossing is here", and crossing_ref= is the "alt name". 

Yes. That's precisely what I'm saying: crossing_ref should contain the alt_names of Zebra or Pelican etc.

>It's very unfortunate that the values for crossing are a mess.

It isn't helped by Mapnik not rendering **stand alone** crossings, which encourages the addition of the incorrect tag of *highway=traffic_signals*

**Comment by bhousel** [comment]
So let's decide on something that makes sense.  Unfortunately whatever we pick will be bucking the current tagging trends.

Here are how the `crossing=*` values look [currently in taginfo](http://taginfo.openstreetmap.org/keys/crossing):

value | count | %
----- | ----- | --- 
uncontrolled | 386 125 | 42.19%
traffic_signals | 319 433 | 34.90%
zebra | 102 719 | 11.22%
unmarked | 53 309 | 5.83%
island | 33 589 | 3.67%
no | 5 432 | 0.59%
unknown | 2 456 | 0.27%
yes | 2 190 | 0.24%
pelican | 1 597 | 0.17%
island;uncontrolled | 1 594 | 0.17%
marked | 1 201 | 0.13%
toucan | 1 188 | 0.13%
controlled | 462 | 0.05%
island;traffic_signals | 447 | 0.05%
traffic_signals;island | 397 | 0.04%
uncontrolled;island | 330 | 0.04%
traffic_lights | 293 | 0.03%

**Comment by manfredbrandl** [comment]
I looked at taginfo again and found that zebra was trending the last 21 hours:

value|count|%|new count|diff
----------|----|----|----|----
uncontrolled|386125|42.19%|386278|153
traffic_signals|319433|34.90%|319584|151
zebra|102719|11.22%|102939|220
unmarked|53309|5.83%|53326|17
island|33589|3.67%|33616|27

uncontrolled and traffic_signals are three to four times in numbers of zebra, but zebra was added most oft in the last 21 hours.

**Comment by DaveF63** [comment]
@bhousel IMO Zebra, Pelican, Toucan (& Puffin) should be used with crossing_ref. The last three are light controlled so should be combined with crossing=traffic_signals. As I said above, I believe Zebra should be combined with crossing=controlled, but I'm unsure I could win that  argument. 

To me an uncontrolled crossing is where there's no markings just a dropped kerb for push chairs & some tactile paving for the blind.

@manfredbrandl Could you do a similar comparison for crossing_ref which, at 171 954 for zebra, is more popular, similar for pelican. 

I'm intrigued how you did the time comparison. Was it via the webpage or a direct api call?

**Comment by bhousel** [comment]
@DaveF63 It sounds like we are mostly in agreement.

My personal preference would be `crossing=` to support `marked` / `unmarked`, and `crossing_ref=` would be a dropdown of the common types of markings.  But I don't think I would win that argument either.

"controlled" is too Dept of Transportation jargony.  Most people don't know what it means.  You and I agree that marked crosswalks are controlling, in that cars legally need to stop at them, but the very first example [here](http://wiki.openstreetmap.org/wiki/Key:crossing#Examples) suggests otherwise.

**Comment by manfredbrandl** [comment]
@DaveF63 
I dont know if these were added in UK? I simply compared the 21 hour older table from @bhousel with the current one.
As I am from Austria and speak german I have to add that "zebra" reads for german-speaking-people like "Zebrastreifen" alias "zebrastrip" which means distinctive white stripes on the road. Cars have to stop if you are crossing there by feet and (at least in Austria) you are not allowed to cross the road somewhere else if a "Zebrastreifen" is within 25 Meters.

@bhousel 
I did not like the wiki when I tried to suggest a new value for man_made (=guy_wire).
Is there a chance that the community gets a reliable source for recommende tagging including discussion/decision of changes?

**Comment by bhousel** [comment]
Can I close this issue by making the crosswalk preset:
`crossing=marked + crossing_ref=zebra`
?

**Comment by bhousel** [comment]
Closing as stale.  This is a problem with OSM tagging, not an iD issue.  

`crossing=zebra` isn't perfect but it's better than the alternatives in widespread use.

**Comment by d1g** [comment]
> This is a problem with OSM tagging, not an iD issue. 

@bhousel this is problem of OSM database, since previous classification uncontrolled/traffic_signals/unmarked/no is now crewed by undefined by crossing=zebra.

http://taginfo.openstreetmap.ru/keys/crossing
http://taginfo.openstreetmap.ru/tags/crossing=zebra

crossing=zebra is only entered because of incorrect iD presets..

**Comment by d1g** [comment]
> crossing=zebra
and
crossing=uncontrolled + crossing_ref=zebra
> 
They seem the same to me.. I really don't see the point of crossing_ref.

@bhousel, yes please read http://wiki.openstreetmap.org/wiki/Approved_features/Road_crossings#Usage VERY carefully

because crossing=uncontrolled + crossing_ref=pegasus

is not crossing=zebra

Key crossing= only defined **3** classes in 2008: where type could be **traffic_signals**, **no** or **uncontrolled** (the default). 

If you ignore 3.73% of crossing=zebra tags, Russian db is relatively close to 2008 proposal:

uncontrolled, 37988, 52.63%
traffic_signals, 27688, 38.36%
unmarked, 2776, 3.85%
no, 515, 0.71%

**Comment by bhousel** [comment]
> crossing=zebra is only entered because of incorrect iD presets..

This is simply not true.   The values in the database are what they are, and they have been that way since long before iD came around.
