### ISSUE TITLE
Universal area cutting tool

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2971]
A universal tool to cut areas would be very useful in particular for landuse mapping.

The tool proposed here need two different set of operand. According to #2970 I call these flagged and unflagged. Both of theses sets can include lines and areas/MPs. Therefore we can differentiate between four types of operands: unflagged lines, flagged lines, unflagged area/MP, and flagged area/MP. The tool is modifiying the unflagged areas/MPs by using all other operands as tools to define the modification.

The tool shall do the following:

1. Temporarily generate areas  surrounding the flagged lines with a little distance. The generated areas are handeld like flagged areas in the next step. This step is intended to allow ungluing landuse from highways.
2. Start to modifiy the unflagged areas by cutting out the flagged areas where they do overlap.
3. Split the resulting areas of the previous step along the unflagged lines. Incomplete cuts of areas are ignored.

I will add application examples later.

**Comment by jfirebaugh** [comment]
Thanks for your suggestions @slhh, but I think you might misunderstand the intended audience and scope of iD. iD is a basic to mid-level editor. We do not intend to add features to it that introduce complicated UI for advanced editing tasks -- that domain is already well covered by JOSM. I'm going to close this and several other of your requests because I believe they fall into this category.
