### ISSUE TITLE
Restore single features from history

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#2975]
Reverting changesets is out of scope of iD, but I feel that an iD user as the typical local mapper should be able to restore single features from the history. This should work for modified and deleted features.

**Comment by bhousel** [comment]
Yes - #537 covers a "revert" operation like this, so I'm going to close this issue as a duplicate.

I implemented most of the code for this in #2611, but that was to solve a specific case where I needed it, and I'm not 100% sure that the implementation is solid enough to support the general case of letting a user click a button and revert any feature back to the way it was when they began their editing session.

**Comment by slhh** [comment]
@bhousel , this is not a duplicate due to different kinds ofr history. I want to restore from the OSM database history instead of the edit session history. Maybe the data can be loaded from Overpass using a user specified time/date.

The application is to restore valueable outlines, which can't be easily redrawn due to being invisible on imagery like boundaries and protected areas.
It might be sufficient to restore just a copy of the feature. A multipolygon could be restored as outline ways only.

**Comment by bhousel** [comment]
> this is not a duplicate due to different kinds ofr history. I want to restore from the OSM database history instead of the edit session history.

Oh, I see what you mean.. That is way out of scope for iD.

That's a hard problem to solve partly because of OSM's data model.  All entities in OSM are versioned separately, so e.g. if you only move the nodes on a boundary, the nodes would get new version numbers but the boundary would not.  Only changes in tags or changes in the nodelist would bump the version on the boundary way.  That makes it a really difficult problem to know "what OSM looked like at a specified time/date" in the past.  To do that well, an app would need to fetch all previous versions of that entity, but also all previous versions of all previous children of that entity.  And if you're talking about a multipolygon relation, then you need to reach down into all previous versions of all previous children of all previous members of all previous versions of the multipolygon.   

Overpass does have some ability to query for past states of objects in the OSM database, but I haven't really thought about connecting iD to it.  You're really better off using one of the specialized revert tools.

**Comment by slhh** [comment]
I know it would be a hard job if you had to start from scatch, but the Operpass API already does everything for you.
For example Overpass Turbo can easily display such a historic boundary relation:
[Old boundary of Spremberg](http://overpass-turbo.eu/s/eov)
Some extra nodes are due to querying by name instead of id.

For comparison: [Current boundary of Spremberg](http://overpass-turbo.eu/s/eot)

I don't see why this should be out of scope of iD. Just because it looked to be complicated to implement at a glance? Of course the complexity of the Osm history has to be hidden from the iD user.
Therefore, my idea was just to copy in the outline.

What would an iD user do without the option to restore from history. Ignore the issue? Try to estimate the outline? The best way would be to call an JOSM expert, but do most iD users really know that these can revert?

**Comment by slhh** [comment]
Overpass query to get the old boundary by id:
```
[out:json][timeout:25][date:"2015-09-12T06:00:00Z"];
(
  relation(1322562);
);
out body;
>;
out skel qt;
```
This does already deliver everything down to the nodes.

**Comment by bhousel** [comment]
So please implement it and submit a pull request if you think it is easy.
