### ISSUE TITLE
Speed up map swipe or fast zoom

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#3006]
Context/user story: http://www.openstreetmap.org/user/d1g/diary/38045

One option is to temporary disable and then enable filling during fast pan or fast zoom. But I'm not sure about thresholds when this option would be beneficial in terms of speed/fps in user browser.

UX: text can be displayed to avoid user confusion: "object fill temporary turned off during fast map move and fast zoom (no action required)"

**Comment by d1g** [comment]
To benchmark this, use some precisely mapped area (as real example I would suggest Moscow Kremlin or Paris or Berlin because they are frequently used and well mapped), but more synthetic tests and remote parts of globe can be found here:

http://www.openstreetmap.org/user/tyr_asd/diary/19549
http://fred.dev.openstreetmap.org/density/

Idea is that fps shouldn't drop below 20-30 during pan/zoom (panning and zooming is more important than loading temporary data, then styling it, then discarding it).

W hotkey is good, but not to the point there user uses it as frequently as he pans a map (in simplest form, we could guess when to press W automatically)


Stats will help understand what exactly "slow" in iD: idea is to use internal counters with following meaningы: (1) "number of objects loaded after last save", (2) "number of objects modified after last save", (3) "number of objects discarded without modification". (4) time iD spent on styling or render (5) time with user activity (6) total time

per each **user**:
* big 3 may mean iD should load data with bigger delay for that user 
* we always want maintain biggest 2/1 ratio, but there many be more parameters in formula
* we want to lower 4 and increase 5 in terms of 6

**Comment by d1g** [comment]
ATM It took 10 seconds to load http://www.openstreetmap.org/edit#map=17/44.49163/11.33979

So 0,1 fps to me :) fred link also contains [a database](http://fred.dev.openstreetmap.org/density/tiles.16) we could re-use in iD:

If we are looking at Bologna, then we don't want to load 6K buildings to hide them right after they were loaded. At zoom level 4 this would mean to load all buildings in multiple countries just in case we would want to edit them, overly optimistic view I would say :)

Instead, we can load only highways (and other surely rare features but also a landmarks) and ask user to _zoom in_ back to 18-19, where we switch to regular iD behavior.

Mappers in Bologna simply cannot edit at z17 because fps is 0,1, so solution would be is to let them comfortable edit at z19+, then do something clever (read above) until they reach their next destination.


Over time there nothing to map at z1, then at z2, then at z3 etc - these zooms become hopping views rather than regular view of an editor.

**Comment by bhousel** [comment]
> ATM It took 10 seconds to load http://www.openstreetmap.org/edit#map=17/44.49163/11.33979
> So 0,1 fps to me :) fred link also contains a database we could re-use in iD:

That's not a very fair way to benchmark.  Obviously the map data will take several seconds to download.  Once fully downloaded in that area I do get around 50-60fps in Chrome and with a fairly recent Macbook Pro.  I'm really proud of iD's performance in this area.

> Instead, we can load only highways (and other surely rare features but also a landmarks) and ask user to zoom in back to 18-19, where we switch to regular iD behavior.

No, we can't just download less data.  The OSM editing API doesn't support filtered downloads, and that's a good thing.  If we were to download, e.g major roads at z15 and minor roads at z18 mappers could break things at the higher zooms that they don't see.

If the OSM editing API could supply data in pbf vector tiles instead of XML, we could probably get it downloaded a little quicker.  This is a big lift though and will probably never happen.

To reduce jank, we could move some of the processing things that iD does into web workers to speed up the main thread.  This is also a big lift that I don't really time to do.

Or we can be better about using `requestAnimationFrame` / `d3.timer` for throttled code.   That's something that I'll probably look into more when I have time.

**Comment by d1g** [comment]
> with a fairly recent Macbook Pro.

That's not a fair way to benchmark things :) Many users have more mediocore hardware, sometimes even basic ones (tablets are very popular today, keep in mind). And in schools you will always see low-end PCs (or just 7yo PCs).

>  e.g major roads at z15 and minor roads at z18 mappers could break things at the higher zooms that they don't see.

Yes but point it that they can only edit at z18+, z15-17 contain only reduced overview data they cannot edit.

> If the **OSM editing API** could supply data in pbf vector tiles instead of XML, we could probably get it downloaded a little quicker. This is a big lift though and will probably never happen.

Why OSM and why use **editing API**? Any read-only technology could be utilized for read-only overview zooms (https://github.com/mapbox/mbtiles-spec/wiki/Implementations)

In simpler version, we could use read only mbtiles at z0-z18, then switch to OSM editing API. Is it possible to implement?

**Comment by bhousel** [comment]
>Obviously the map data will take several seconds to download.
>Yes, it is questionable, but I rather include user wait time, rather than ignore it completely :)

It makes it really difficult for me to take your point seriously when you include wait time in your measurement of iD's fps.  I would love to speed this up, but time spent downloading data from OSM is something that's really far outside of my control.

> Why OSM and why use editing API? Any read-only technology could be utilized for read-only overview zooms (https://github.com/mapbox/mbtiles-spec/wiki/Implementations)

We need to use the editing API because an OSM editor needs the most current database state possible in order to avoid conflicts.  Any vector tile source of OSM data that both contains everything in OSM and is within a few seconds of the current database state would need to come from the OSM API itself, right?  I can't just grab for example Mapbox Streets, which is updated hourly and only contains a useful subset of OSM.

**Comment by d1g** [comment]
> to take your point seriously when you include wait time in your measurement of iD's fps

There many _measurements_ in performance aspect. Yes, I mentioned wrong term, so let's use real terminology then "time to the first frame" and "fps" when editor is ready to use.

11200KB were **loaded** in 5.87s and it took additional time to **render** it in iD (quite fast I would say, 3-4 seconds).

> but time spent downloading data **from OSM** is something that's really far outside of my control.

Again, you are missing point. We can use ANY read-only API: overpass, mbtiles and not main editing (api.openstreetmap.org).

> because an OSM editor needs the most current database state possible in order to avoid conflicts

True, but we only need this at z18+. I also explained why [mappers over time not need higher zoom levels **for editing**](https://github.com/openstreetmap/iD/issues/3006#issuecomment-189726287).

Nobody would notice if you have 2 year old tile at z10 or z4. Very few things change at this zoom level.

Case z15 magic with mbtiles:
- display outdated mbtiles
- allow editing (adding of the new features)
- display info "to edit existing features, zoom in"

Currently, iD simply rejects any of edits at z0-z15. I think this is right behavior because we want more precise coords in data and not because current api.openstreetmap.org disallows huge downloads.

Case z19+:
- regular iD editor, pulls data from api.openstreetmap.org
- no changes in codebase


I'm suggesting solution that will not only allow adding of data at z0-z15 but also simplify map move and panning in data-heavy areas like Bologna.
