### ISSUE TITLE
Unclassified roads rendered too thin

### ISSUE THREAD

**Issue by Janjko** [openstreetmap/iD#3015]
Unclassified roads started being rendered thinner than residential roads. That makes no sense because those roads are more important than residential roads. These are roads that are not classified, but that connect places. That's the description HOT uses when they teach new mappers.

And that's why unclassified roads are rendered more prominent than residential on almost all maps that use OSM. In the standard OSM layer on zoom 12 unclassified roads are darker than residential.

**Comment by Janjko** [comment]
And in case this is a problem only with my browsers, here is a screenshot:
http://i.imgur.com/zXdl0Lx.jpg?1

**Comment by d1g** [comment]
> those roads are more important than residential roads.

There no specific agreement on this. In practice, unclassified used interchangeably with residential class.

http://wiki.openstreetmap.org/wiki/Proposed_features/Highway_key_voting_importance

> These are roads that are not classified, but that connect places.

This is false statement

"is used for minor public roads typically at the lowest level of the interconnecting grid network. Unclassified roads have lower importance in the road network than tertiary roads, and are not residential streets or agricultural tracks"

http://wiki.openstreetmap.org/wiki/Tag:highway%3Dunclassified

"The least most important through roads in a country's system – i.e. minor roads of a lower classification than tertiary"

http://wiki.openstreetmap.org/wiki/Key:highway

**Comment by d1g** [comment]
In Russian version of agreement, "residential" class wasn't used for _roads outside urban areas_. And both residential and unclassified are ranked below "tertiary" _within urban areas,_ but distinction between two is shallow in practice. [highway=* agreement](http://wiki.openstreetmap.org/wiki/RU:%D0%92%D0%B8%D0%BA%D0%B8%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F_%D0%B4%D0%BE%D1%80%D0%BE%D0%B3_%28%D0%B3%D0%BE%D0%BB%D0%BE%D1%81%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%29)

**Comment by bhousel** [comment]
We discussed this a bit on #2916.  It is definitely confusing.

@d1g thanks for digging up the documentation, it's really helpful to see how this tag is used in other parts of the world.

@Janjko from that imgur screenshot, those really do look like what I would call residential roads.  I mean, there are buildings there, people live along those roads.  In that screenshot (Croatia?) does the road network really go primary, secondary, tertiary, unclassified, residential - in order of importance?

I'm not trying to disagree, just trying to understand how the tag is used there.  Why not just use tertiary for roads that connect places?

Consider also, iD has a feature filtering system that makes a distinction between major road (e.g. for travel) and minor road (e.g. for access/parking), and I'd really like to put `unclassified` where it belongs.  It's hard for me to call them "Minor Roads" and then stick them in the "Major Road" filter.

**Comment by pnorman** [comment]
> Unclassified roads started being rendered thinner than residential roads. That makes no sense because those roads are more important than residential roads. These are roads that are not classified, but that connect places. That's the description HOT uses when they teach new mappers.

It sounds like they're being taught wrong.

> And that's why unclassified roads are rendered more prominent than residential on almost all maps that use OSM. In the standard OSM layer on zoom 12 unclassified roads are darker than residential.

The decision was recent, and only for that zoom, and has to do with specific cartographic considerations about density, not road network importance.

**Comment by bborkmiller** [comment]
I'm very confused about unclassified roads then. The wiki says

> highway=unclassified should be used for roads used for local traffic and used to connect other towns, villages or hamlets.

In rural areas I've been applying it to roads that don't meet the definition of tertiary, track, or service, and which don't dead-end in a development (which I would tag residential). Basically, like the wiki also says, "minor public roads typically at the lowest level of the interconnecting grid network." In my understanding, the road might have the occasional house along it (most rural roads do, in my area) but that doesn't make it residential.

In urban settings, I'm not sure where to use them, except in commercial areas. What's a road that is lined with houses, but where most of the traffic on it is using it to travel through the neighborhood, not to get to one of those houses. (Assuming it's not important enough to be tertiary.) [Here's an example](http://www.openstreetmap.org/way/17810447#map=17/44.75560/-85.60185).

The upshot is that, in my mind, unclassified is on a par with residential roads in terms of importance, and I was surprised to see it render like a service road in the latest version of iD.

**Comment by d1g** [comment]
>  I'm not sure where to use them, except in commercial areas.

There dedicated tag for this: http://wiki.openstreetmap.org/wiki/Key:abutters. Yes, don't take them too seriously, IMO unclassified and residential should be merged in single class:
* primary
* secondary
* tertiary
* (real class name here)

But there 33M instances of residential and 9M instances of unclassified...

We some pedantic folks that check primary>secondary>tertiary>(unclassified or residential )>service rule

http://taginfo.openstreetmap.org/keys/highway#values
http://taginfo.openstreetmap.ru/keys/highway#values

Obliviously, residential class is overused in the World or roads with a service class are heavily under-mapped. service should be a top class, not a residential.

**Comment by bhousel** [comment]
Because it's way too late now to change the name of the tag or how people use it... I'm leaning towards:

* Leave `highway=unclassified` called "Minor Road"
* Restore rendering to use wide line like `highway=residential`, but with slightly different color
* In feature filtering.. 
  * Rename "Major Roads -> Traffic Roads", "Minor Roads" -> "Service Roads"
  * Make `highway=unclassified` filter on "Traffic Roads"

**Comment by d1g** [comment]
> In feature filtering..

I also support distinction to 
* common roads or "Service Roads" (service and it's sub-types) and probably other types (tracks)
* top classes or "Traffic Roads" (from motorway down to unclassified or residential)

Current top value in highways=* with 33M residential roughly means that we should have ~40M service roads.

Re-tagging of top classes occurs only in heavily developed areas (new bridges, new motorways) because how we agreed to define a highway=* key.

**Comment by bhousel** [comment]
Feature filters look like this now:

<img width="225" alt="screenshot 2016-03-05 23 33 18" src="https://cloud.githubusercontent.com/assets/38784/13552305/b2b45ee0-e32a-11e5-881c-7a0571542b88.png">

@d1g These filters purpose is so that mappers can hide some data in dense areas.  The filters use these highway tags:

##### Traffic Roads:
* `motorway`
* `motorway_link`
* `trunk`
* `trunk_link`
* `primary`
* `primary_link`
* `secondary`
* `secondary_link`
* `tertiary`
* `tertiary_link`
* `residential`
* `unclassified`
* `living_street`

##### Service Roads:
* `service`  (includes alleys, parking aisles, drive thru, driveway, etc.)
* `road`
* `track`


> Re-tagging of top classes occurs only in heavily developed areas 

We're not proposing re-tagging anything, just want to be clear..

**Comment by d1g** [comment]
@bhousel well, this out of scope of this issue. 

> We're not proposing re-tagging anything, just want to be clear..

I said this because top classes "Motorway" will be suggested as first/top values:

![](http://i.imgur.com/kGxhAPy.png)

Not only users have to travel more pixels after they click "Road features" (yes it wastes time) to most common classes (service, residential). motorway may be confusing as top value.

I recommend to use inverted list of [your sorting](https://github.com/openstreetmap/iD/issues/3015#issuecomment-192805084) but in the presets. It makes sense to place most frequently classes than [classes we change infrequently](https://github.com/openstreetmap/iD/issues/3015#issuecomment-192411036). 

Is it more clear now?

**Comment by canyonsrcool** [comment]
My team and I would also like to see the rendering for "Unclassified" roads back to where it was previously - that is, the same width as residential but just slightly darker.  It is hard to distinguish visually between service and unclassified roads now. Thanks!

**Comment by bhousel** [comment]
Restored `highway=unclassified` to thick line again, similar to residential but slightly darker.

<img width="389" alt="screenshot 2016-03-07 22 42 06" src="https://cloud.githubusercontent.com/assets/38784/13591372/e477462c-e4b5-11e5-8418-57e3d3d042bf.png">
