### ISSUE TITLE
Mandatory Preset Descriptions

### ISSUE THREAD

**Issue by brandonreavis** [openstreetmap/iD#3022]
Between @pnorman and company's backlash about adding "unmaintained" to tracks [here](https://github.com/openstreetmap/iD/commit/6b2a69282e0b274c270f5288765ca3db1c8890f9) and the back-and-forth lately about unclassified roads [here](https://github.com/openstreetmap/iD/issues/3015), I really think that iD needs to always show a short description of a preset in addition to the title for certain types of features. 

Unfortunately, I don't think enough people read the wiki or click the "i" button next to the title if they have doubts.

Below are the short descriptions from the wikis: 

- **Track Road:** Roads for agricultural and forestry use etc
- **Service Road:** Generally for access to a building, service station, beach, campsite, industrial estate, business park, etc.
- **Unclassified Road:** Public access road, non-residential. (Typically at the lowest level of the interconnecting grid network)
etc

The title alone is not enough for people to understand the impacts they have on road hierarchy, and in rural areas where most roads are unpaved or minor, the difference between tracks, service roads, and unclassified roads is so important when making a map that actually makes sense. I was in agreement with @bhousel about the addition of "unmaintained" to the track preset title because, at least in the USA, it would fix the mass problem of people just tagging all dirt roads as tracks and it would help the road hierarchy more than hurting it. I guess this stirred up to many issues elsewhere however.

I'd also propose that the field for the surface tag shows up second (right below the name field) for those three road types. This way it is more obvious that road type is not dependent on surface.

I am willing to put together a pull request for this if it's generally agreed upon. I don't think it needs to take up much extra space.

**Comment by simonpoole** [comment]
@brandonreavis pls "blacklash" is really really not what is happening here, some verbal de-escalation would be in order. If mass downgrading of roads is happening in the US then that is a relatively new phenomenon, historically the opposite has been true  

In any case conveying the nature of the object that is being tagged better is not a bad idea.

**Comment by bhousel** [comment]
@brandonreavis,  No, we already rely too much on the wiki.  If people won't translate the preset names properly, it's safe to assume they also won't translate the wiki properly either.

@simonpoole "backlash" is exactly what is happening here.


I haven't decided what to do, but if I do anything, it will probably be to rename both presets back to what they used to be called and then never change them again.

**Comment by brianreavis** [comment]
> No, we already rely too much on the wiki

@bhousel Want to clarify? How is extra clarity a bad thing?

**Comment by bhousel** [comment]
> Want to clarify? How is extra clarity a bad thing?

Because I think the wiki is wrong in this case. 

We've seen people map any road near a farm or forest as a track.  
We've seen people map any dirt road as a track.
We've seen people map recreational 4x4 tracks *not* as a track because they have nothing to do with forestry or farming.
We've seen HOT tasks where the instructions tell people to map driveways as tracks.
We have routers that currently route vehicular traffic over tracks, which IMO is irresponsible and dangerous.

I'm not really sure what to do about this, but it's clear that renaming "track" in iD isn't the solution.

For sure this most recent backlash will affect how I approach preset renames in this project going forward (i.e. there probably won't be any more).

**Comment by brianreavis** [comment]
> Because I think the wiki is wrong in this case.

Relevant: https://github.com/openstreetmap/iD/pull/2982#issuecomment-185014283 

If you're not into the wiki, what about the earlier suggestion (https://github.com/openstreetmap/iD/pull/2982#issuecomment-181178566):

> Another approach altogether is to not modify the preset at all and instead introduce a "Common Confusion" info box that comes up below the selected preset that can nudge people to the right preset.

**Comment by bhousel** [comment]
> If you're not into the wiki, what about the earlier suggestion (#2982 (comment)):

I also really want people to pick the best preset for every road, but a "common confusion" info box needs content that comes from somewhere, and needs to be translated, and needs to satisfy the OSM community.   The wiki is supposed to be that source..

**Comment by bhousel** [comment]
> I'd also propose that the field for the surface tag shows up second (right below the name field) for those three road types. This way it is more obvious that road type is not dependent on surface.

I realized I forgot to respond to this point.  I agree that moving `surface` up above as one of the first few fields is a good idea.

**Comment by slhh** [comment]
I think a "common confusion" info box would be very useful in some cases, but it should not be mandatory.
The OSM wiki should be the source, but iD specific pages like the iD shortcut lists are required.
The content of the infobox needs to be too iD specific for the normal wiki pages, for example it needs to refer to iD's preset names.
The language specific preset names should be sourced from the same wiki pages. 

The "common confusion" info box might exist for some languages only because something which can be be defined just by the preset name in one language might be less clear in another language.

**Comment by brianreavis** [comment]
> I think a "common confusion" info box would be very useful in some cases, but it should not be mandatory.

Right. Unless I'm forgetting something, I've only found it needed for Track. A new feature for one or two presets might seem silly, but something needs to be done to add some clarity to the Track preset – there's way too much misclassification happening due to its vagueness. I just want a gentle nudge:

  - **Track**<br>*Common Confusion:* For "single-track" hiking/biking trails, use [Path](#). For significant roads, use [Unclassified](#), [Residential](#), or [Service](#) instead.

(Open to wording suggestions) Clicking on the links should change the preset for the user. The notice could be dismissed so it doesn't get in the way of regular users. @brandonreavis and I are happy to develop this.

**Comment by slhh** [comment]
There are more applications of a "common confusion" info box, for example:
* Forest: landuse=forest or natural=wood?
* Swimming pool facility: leisure=sports_centre, leisure=water_park, or leisure=swimming_pool?
* highway=trunk: info box needs to make the user aware that it has a country-specific definition and link the definition.

**Comment by bhousel** [comment]
@brandonreavis & @brianreavis , I really appreciate your offer to develop this.  But I feel like if iD were to embed our own tagging guidelines separate from the OSM, people would complain.   

As flawed as it is, the OSM wiki is really the place for something like this to exist.  I have tried to change the short description on the wiki for `highway=track`, and my changes were reverted within days.  I'm not going to try again.

Unfortunately tagging in OSM is not standard worldwide, so whatever descriptions we come up with would be sure to annoy somebody somewhere.  This is really a problem that needs to be fixed in OSM, not in iD.

**Comment by simonpoole** [comment]
Again the problem with the change to the wiki is that you changed the reference, base version of the docmentation for everybody. There are essentially two ways to handle this: add country specific sections to the page in question (that has been done in the German language version now and then, given that it is often used as a reference in three different countries with sometimes quite different traffic regulations)  or add specific guidance to the country wiki page.

The other possibility that I've been playing with, is country specific presets. This would need to be dependent  on the location of the object being edited not on the location/language of the editor.
