### ISSUE TITLE
Logic for islands should be more complex

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#3037]
When you create place=island or similar "inner" landmass **within natural=water multipolygon**, you should add it with "inner" role to the multipolygon.

Also, there will be complex multipolygons with multiple inner-outer-inner-... circles - logic would be more complex here, but otherwise (if there no mix of "inner", "outer"; only "inner") you can simply assume it's a "inner" object.

**Comment by bhousel** [comment]
iD already supports creating multipolygons by selecting the inner and outer features merging them together with the "+" Merge operation.

Is this what you are asking about?

![multipolygon](https://cloud.githubusercontent.com/assets/38784/13815115/ae143634-eb5f-11e5-83f4-7ec687c1b700.gif)

**Comment by d1g** [comment]
@bhousel, somewhat. First, I don't think it's relevant to landuse=forest. Yes, but this should be done automatically for water bodies, not with "C" tool. 

One user just cratered 4 islands without including them into parent (river multipolygon): http://www.openstreetmap.org/changeset/36957332

**Comment by bhousel** [comment]
> Yes, but this should be done automatically for water bodies, not with "C" tool.

No we won't be making multipolygon merges automatic just because someone draws land on top of water.


> One user just cratered 4 islands without including them into parent (river multipolygon): http://www.openstreetmap.org/changeset/36957332

That's great!  Thank them for their contribution.   If you really want to teach them how to use the merge tool that's cool too, but sometimes it's faster to just show someone what to do rather than tell them.

**Comment by d1g** [comment]
> multipolygon merges automatic just because someone draws land on top of water.

@bhousel not because "someone draws land on top of water" - that's your statement! Why do we need to manually merge multipolygon(s) in the first place?

> If you really want to teach them how to use the merge tool that's cool too, but sometimes it's faster to just show someone what to do rather than tell them.

We don't have so many people to tutor all users for their oversights. I'm definitely not able to tutor all iD users or even all oversights of a singe user.

I don't think I should contact every [other editor after every simple mistake. That's irritating and wastes time that could be used for a better use](https://en.wikipedia.org/wiki/Wikipedia:Harassment#Wikihounding).

Yes, "do correct errors" (<s>and don't cry</s>) is right attitude in wiki-based projects, but at least in iD validator could assist with this [simple case](https://github.com/openstreetmap/iD/issues/3037#issue-141220396).

**Comment by d1g** [comment]
If automatic merge is questionable or will have huge performance penalty, then we could improve validation step since it is called only once in iD.

**Comment by bhousel** [comment]
I'm sorry that my answer above didn't really get into _why_ I think automatically creating multipolygons is a bad idea.

My main concern is that we don't want to introduce too much magic into iD by trying to guess what the user "really" means to do, because in many cases we will end up guessing wrong.

Say a user draws an area on top of a large `natural=water` multipolygon.  Then they select the "Island" preset and we tag it with `place=island`.  Next they say "oops, I really meant to tag that as a Dock" so they change the preset again.  If we had created a multipolygon out of the island, this complicates things - should we undo the multipolygon that we just made?  To get this right, we would need to 1. build in a lot of extra logic to iD about what things can go on top of what other things, 2. alert the user when they make a "mistake" like overlapping land on water.   This is an impossible task because the tags in OSM are made up and constantly changing.

To make editing in iD easy for anybody, I try to adhere to these principles:

* Visuals are better than words.
* Wrong things should look wrong.
* There are no penalties for doing a wrong thing.
* Everything should be fixable.
* People who enjoy mapping will take ownership of the map and improve it.
* It is better to have many people mapping imperfectly than a few people mapping perfectly.
* The map will never be perfect.

I hope this helps better explain my thinking about why I closed this issue.

**Comment by d1g** [comment]
> too much magic into iD by trying to guess what the user "really" means to do, because in many cases we will end up guessing wrong.

JOSM uses dialogues with multiple options to pick what exactly user wants to do.

You can also use "remember my preferences" to avoid guessing/repetitive questions.

> Say a user draws an area on top of a large natural=water multipolygon. Then they select the "Island" preset and we tag it with place=island. Next they say "oops, I really meant to tag that as a Dock" so they change the preset again. If we had created a multipolygon out of the island, this complicates things - should we undo the multipolygon that we just made? 

Editing things back and forth - this is irrelevant at validation/pre-commit step. Yes you can use history of edits during validation, but this is an over-complication. Validator may work on latest data snapshot.

> Wrong things should look wrong.

and how "place=island" object could have "right" look at osm.org if it wasn't cropped out of water multi-polygon? This perfectly tagged island would be invisible.

User did a right thing - but also got negative result (unrendered island) as feedback . At best he would be confused with OSM tools, at worst, he will learn this bad practice as normal.


I will give you idea of "draw an inner object" button/context tool: when a type:relation + type=multipolygon is selected: you will simply switch to drawing "inner" rings of MP (replace draw a line "2" button with another function). If you want to keep things simple, avoid editing of outer-inner-outer-... multi-polygons (with multiple inner rings).
