### ISSUE TITLE
Autocomplete suggestions in change descriptions should be case sensitive

### ISSUE THREAD

**Issue by jancborchardt** [openstreetmap/iD#3039]
So I added a café and want to write a comment on that. The comment is supposed to be:

> add Lowercase café (with wifi) in Singapore

However as soon as I type

> add L

my input gets overwritten with a suggestion from previous edits:
![osm input fail](https://cloud.githubusercontent.com/assets/925062/13876846/f61d4568-ed41-11e5-889f-93ca17c329bc.png)

I understand the intention of being helpful. However there’s 2 problems:

1. It gets overwritten directly without further input (like selecting the suggestion), so I can’ŧ actually put in the description I want, with an uppercase L.
2. It’s very very unlikely that I will ever use the same description twice. I get that it’s helpful when you have lots of repetitive comments though.

**Comment by rubenfilteris** [comment]
![impossible to type service road lowercase with autocomplete](https://cloud.githubusercontent.com/assets/1697731/13882578/b9bf4750-ed2e-11e5-9d0f-3037ee4832b1.gif)

**Comment by rubenfilteris** [comment]
A workaround is to type a garbage string at the start of the comment, then type your comment, then delete the garbage:

1. this is a garbage comment that does not autocomplete
2. this is a garbage comment that does not autocomplete With my actual comment following the garbage.
3. With my actual comment following the garbage.

**Comment by bhousel** [comment]
> A workaround is to type a garbage string at the start of the comment, then type your comment, then delete the garbage:

A better workaround is to just type your comment.

**Comment by rubenfilteris** [comment]
@bhousel maybe I was not very clear in my explanation of how to reproduce the issue, if you just type your comment and it works, it means you are not [yet] effected by this issue.

As far as I can tell you are not affected if you don't have something similar in your comment history compared to what you are trying to type. In particular any new comment that does not start similar to something your user's history does not trigger this issue.

So if I were to try to add the text during save: "Add SAMPLE to show issue" 
and I just try to type my comment it will come out as
"Add sAMPLE to show issue" 

I also cant go back and just change the lowercase "s" to "S" since that then throws away "AMPLE to show issue" and replaces it with the autocomplete. Which forces me back to the workaround explained above. (obviously the start string can be anything like "xxx" that has not been used yet so it does not get autocompleted)

A short gif may help to reproduce the issue more clearly:
![impossible to type add sample](https://cloud.githubusercontent.com/assets/1697731/13884625/797d0eee-ed37-11e5-9074-fa32c101145d.gif)

Hope that helps.

**Comment by jfirebaugh** [comment]
@rubenfilteris Is the issue essentially that the autocomplete is case-insensitive, and you want it to be case-sensitive?

**Comment by rubenfilteris** [comment]
> Is the issue essentially that the autocomplete is case-insensitive, and you want it to be case-sensitive?
No the issue is that the autocomplete does not honour the characters that the user already typed. So yes, the fact that the trigger is case insensitive (which users probably don't mind) triggers the problem that capitalization already made is replaced (which users, including me, mind).

Since the auto complete trigger back-propagates the auto completion to include the _already typed_ character, it means that I have no way to override errors (or valid capitalization of strings that I don't want to type again) of my former self that have crept into my history. 

I forgot to set the GIF above to auto-loop, but you can see half way through that GIF even if I try to change the "s" to "S" then everything I had typed before now is replaced.

So in my mind a fix would be:
1. Honour the characters already typed, i.e. the capitalization 
2. Don't autocomplete if there is already typed text after the cursor (because most likely I am fixing something and don't want to loose everything to the right)

**Comment by rubenfilteris** [comment]
@jfirebaugh just to be clear: I prefer if the autocomplete trigger stays case-insensitive.

Given a single history of one string:
_A Comment from the past_

I would be glad to type:
_A c_

And see the autocompletion as:
_A comment from the past_


Currently the autocompletion would be:
_A Comment from the past_

because the `c` that was already typed was replaced with `C` as part of the current autocomplete.

**Comment by jancborchardt** [comment]
What @rubenfilteris said just now ^ would also solve the issue I had I think. :)

**Comment by jancborchardt** [comment]
@bhousel these nice fixes everywhere make it that more motivating to contribute content to OSM! :)
