### ISSUE TITLE
traffic_signals for pedastrians are missing (1.9.2)

### ISSUE THREAD

**Issue by d1g** [openstreetmap/iD#3050]
highway=traffic_signals - "Required. Indicates traffic signals for cars." (http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals)

crossing=traffic_signals - "Required. Indicates traffic signals for pedestrians." (http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals)

"crossing=traffic_signals
    Position this tag where the crossing-traffic (pedestrian, bicycles) have their own traffic lights.
    Mostly near highway=traffic_signals." (http://wiki.openstreetmap.org/wiki/Key:crossing)

**Comment by bhousel** [comment]
We have a preset for `highway=traffic_signals` already that can be set on junction nodes.

We have a generic preset for `highway=crossing` that can be set on junction nodes or ways.  It displays as "Street Crossing" and allows users to pick the "Type" from any of the commonly used `crossing=*` values (top values currently are: `uncontrolled`, `traffic_signals`, `zebra`, `unmarked`).  I don't like `crossing=traffic_signals` because it breaks [duck tagging](http://wiki.openstreetmap.org/wiki/Duck_tagging) but people can set it here if they really want to.

We have a specific preset for `highway=crossing + crossing=zebra` that displays as "Pedestrian Crosswalk".  We discussed it extensively on #2918 and I'm not planning to change it anytime soon as there is no better alternative at this time.

**Comment by d1g** [comment]
> because it breaks duck tagging 

Nobody except for maybe English speakers support duck tagging in database.

http://wiki.openstreetmap.org/w/index.php?title=Duck_tagging&action=history

User Cartinus or next guy from http://wiki.openstreetmap.org/wiki/Category:Users_against_tag_voting

represent only marginal views (even when counting only wiki users), but force WAY too hard in OSM.

Refer to actual policies, not random Richard phrases.
https://wiki.openstreetmap.org/wiki/Proposal_process
http://wiki.openstreetmap.org/wiki/Good_practice#Document_your_custom-tags

And no @systemed or Richard Fairhurst, an journalist, cartographer and canal person, is nohow experienced in this question. After 10 years in OSM this guy wrote 0 POI catalogues based on OSM data. I don't see why his statements about how to define new tags should be respected.

**Comment by d1g** [comment]
>  I don't like crossing=traffic_signals because it breaks duck tagging but people can set it here if they really want to.

Why they don't want to tag pedestrian crossings?!

crossing=traffic_signals was defined/described as "pedestrian crossing" at [two pages](https://github.com/openstreetmap/iD/issues/3050#issue-143741925)

**Comment by bhousel** [comment]
> And no @systemed or Richard Fairhurst, an journalist, cartographer and canal person, is nohow experienced in this question. After 10 years in OSM this guy wrote 0 POI catalogues based on OSM data. I don't see why his statements about how to define new tags should be respected.

The currency of any open project is measured in meaningful contributions and RichardF has earned more of it than anybody. 

Sorry @d1g I'm banning you from the iD issue tracker for a while.  You're becoming a pest and the rest of us here have important work to do.
