### ISSUE TITLE
handling of wikipedia tags without a prefix is not optimal

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#3071]
We have the [broken wikipedia link count](http://tools.wmflabs.org/wiwosm/wiwosmlog/broken.html) down to zero!
But, right now it is too easy with iD to bring them back (i just corrected 5 of them).
I have no idea how the wrong entry was entered, but when you have a tag:
`wikipedia=London`

It is no visual clue that the language prefix is missing:
![image](https://cloud.githubusercontent.com/assets/2410353/14619303/2cb829de-05b7-11e6-9973-eace3b7aa46e.png)

After selecting the (very nice!) dropdown box the visual appearance is the same, but the problem is solved.
Be aware that sometimes the correct language is not easy to guess.

**Comment by bhousel** [comment]
The only way to add a non-prefixed wikipedia value is through the raw tag editor or through another editor.  The wikipedia control in iD always prefixes the values - so to say that "it is too easy with iD to bring them back" is not fair.

Is the issue that you want our control to show something like "<missing>" instead of "English" when the value was incorrectly set some other way?

**Comment by HolgerJeromin** [comment]
OK, sorry. You are right with the wikipedia control. 
<missing> in the control and a warning on save (i think iD has the infrastructure for that) would be a perfect solution.

**Comment by bhousel** [comment]
Now the language field displays a "Choose language" placeholder value that will show if the language can not be determined from the tag value.  The language field will still default to the user's current language. 

<img width="359" alt="screenshot 2016-04-25 11 25 28" src="https://cloud.githubusercontent.com/assets/38784/14789057/cd29bf38-0ad8-11e6-869f-e15c75b8b20c.png">

**Comment by HolgerJeromin** [comment]
Very nice. Thanks!
