### ISSUE TITLE
Moving relation when type=building

### ISSUE THREAD

**Issue by homersimpsons** [openstreetmap/iD#3078]
I have dicover 3D mapping and starting to do this using iD, but when you create a building in 3D you have got multiple building:part under relation to get the coorrect outdoor/indoor shape. And I this building need to be moved it's long to select one by one the element (furthermore some elements are on the sames lines), then please add an option to move relation member :)

**Comment by bhousel** [comment]
Can you use the lasso tool to select all of the parts of the building that you want moved?
To draw a select lasso, shift-left-click and draw an outline to select all the nodes in the lasso.

**Comment by slhh** [comment]
An operation to move relation members would be too special, but an operation to add relation members to the selection would also have other potential usecases. An operation to move the selection does already exist.

The lasso tool might work for moving the buildung, but unfortunately it doesn't work for copying the building due to #2948 , which is unnecessarily limiting the application spectrum of the lasso tool.

**Comment by homersimpsons** [comment]
Lasso-tool is a way to wait the implementation, thank you :) 
Add an option to select all member of a relation can be a way to make this, but sometimes there are relations as part of the main relation, then this need to be recursive.

**Comment by bhousel** [comment]
Can you share an example of the building you want to move? We do already have some support for grouping multipolygon members, but I don't know anything about the semantics or tagging for building part relations

**Comment by homersimpsons** [comment]
sorry for time to respond, for example this one: [OpenStreetMap.org](https://www.openstreetmap.org/#map=19/48.68817/2.17499) I can move this with lasso, but it could be easier if it was just by selecting the relation...

**Comment by quincylvania** [comment]
I'm not sure this issue is still applicable. We have building part support now so it's possible to manually click on all the parts for a multiselect and move them all at once. You can also select the `type=building` relation via the All Relations section of one of the members and press `M` to move all members of the relation at once. While this isn't accessible via the right-click menu, there's a toolbar button for it in v3.

@bhousel Can this be closed or did I miss the point?

**Comment by bhousel** [comment]
> @bhousel Can this be closed or did I miss the point?

Yes, I think it can be closed if it's easy to select them all..

**Comment by homersimpsons** [comment]
I can confirm that it now works using `M` once the relation is selected. Thank you !
