### ISSUE TITLE
support oneway:bicycle=no

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#3081]
I would expect that oneway tag window would have "except bicycles checkbox" that would allow to easily add oneway:bicycle=no tag.

**Comment by bhousel** [comment]
I don't think it's a good idea to add a field for such a rare tag like `oneway:bicycle` to every highway preset that has a `oneway` field.   The sidebar is already pretty crowded with highway fields that are frequently used.  I think it's reasonable for people that want to set this tag to use the "all tags" section.

**Comment by slhh** [comment]
The tag might by rare, but the situation requiring it isn't rare. At least in Germany it is required by law to exempt bicycles except where is a reason making this impossible.

I agree on adding a field for oneway:bicycle to every highway preset that has a oneway field isn't a good idea.
Instead the field for oneway should have a checkbox to exempt bicycles.This checkbox can be hidden if oneway:bycycle is unset and oneway is not yes or -1.

Fields should define whole properties instead of just keys/tags (#3082).

**Comment by bhousel** [comment]
It really wouldn't be fair for me to spend time adding fields just for Germany, but if the German OSM community wants to fork iD and customize it to handle the special tagging situations that exist only there, I would be happy to assist..

**Comment by matkoniecz** [comment]
> just for Germany

It is typical tagging situation also in Polish cities.

**Comment by quincylvania** [comment]
Thanks to #5582 and #5583, we can now support more "fringe" tags while keeping the default sidebar as simple as ever.

I added a `oneway:bicycle` field in ecec39773692731ec5c5b67fdd4311a0355e1a3c. You can select it under `Add field:` after setting a value for `oneway`. It will also appear anytime there's a pre-existing value. Happy mapping, Europe!

http://preview.ideditor.com/master/#background=Bing&disable_features=boundaries&id=w31916367&map=17.40/51.23333/6.75572

<img width="782" alt="screen shot 2019-01-17 at 10 13 46 am" src="https://user-images.githubusercontent.com/2046746/51328563-ab42f800-1a41-11e9-8344-faf6b766a05a.png">
