### ISSUE TITLE
Add 'direction' key as default to some tags

### ISSUE THREAD

**Issue by homersimpsons** [openstreetmap/iD#3115]
It would be usefull for:
'highway'='stop','give_way','traffic_signals'
to add a field 'direction' with option: 'forward' or 'backward'
for 'traffic_signals' the key need to be: 'traffic_signal:direction' (don't know really why).

**Comment by bhousel** [comment]
`highway=stop`
Yes, any street sign preset should probably have a forward/backward field.  Stop should probably also have an "all way" checkbox.

`highway=give_way`
We don't have a preset for this yet, but yeah, same as stop sign.

`highway=traffic_signals`
This makes no sense.. They kind of need to face all directions, otherwise what's the point?

**Comment by homersimpsons** [comment]
Maybe you can create a "big" category named "sign" to regroup those 3
And same create a 'big' category named "traffic calming" to add all type of traffic calming (island, cushion, hump, bump etc...)

**Comment by slhh** [comment]
> highway=traffic_signals
This makes no sense. They kind of need to face all directions, otherwise what's the point?

I agree in case of tagging traffic_signals on the junction node, but in case of mapping the traffic_signals of an larger junction separately, traffic_signals:direction makes sense, due to typically facing to a single direction for car traffic.

Preferably, traffic_signals:direction should be made available in case highway=traffic_signals is tagged on a virtex of a single non-oneway way.

**Comment by bhousel** [comment]
These were added for `highway=stop` and `highway=give_way`... Not doing `traffic_signals` for now - I think it would confuse people more than help them tag correctly.

**Comment by homersimpsons** [comment]
Yes, I read your comment on PR, can iD detect if it's on a intersection node (>=3 ways) to give the correct preset?

**Comment by bhousel** [comment]
> can iD detect if it's on a intersection node (>=3 ways) to give the correct preset?

Not currently.  `vertex` geometry will tell us that the node is on a line, but not the degree of how many edges connect to it.

**Comment by Codain** [comment]
Hi @bhousel 

Thank you for having put this fields for stops and give ways, very handy because it increases the quality of routings.

I would like to argue in favor of having a direction field proposed also for traffic signals. The only difference between a stop, a give way and a traffic signal is the type of rule imposed by the authorities and the physical "sign". Moreover in term of mapping in OSM it is the same mechanism.

Traffic signals, like stops, are not forced to be on the intersection node, especially when it doesn't reflect reality. In this case one node can be set on each way which has a traffic signal. It is especially helpful for intersections where some ways have a signal while others not, like in a complex intersection:
- http://www.openstreetmap.org/node/3880378388 (traffic lights cover two intersections, not one)
- http://www.openstreetmap.org/node/3880378387 (four one way roads are crossing. Putting the traffic lights on the four intersections would lead to having to cross two traffic lights which is not true at all).

If people are not confused on a stop, I don't see why they would be confused on a traffic light when the mechanism is the same.

Consequently, can you or another dev consider extending this field to traffic lights?

**Comment by bhousel** [comment]
> If people are not confused on a stop, I don't see why they would be confused on a traffic light when the mechanism is the same.

I think people _are_ confused by directional vertices, even stop signs..  But they are a thing, so maybe we can adjust the rendering of vertices that have a direction tag (or can have a direction tag) to make it more clear.  If we do that, then I wouldn't mind adding a direction field to traffic signals.
