### ISSUE TITLE
Area merge to create polygon with hole leaves extra area=yes tag

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#3133]
1. Draw an area and give it some tag (e.g. leisure=park)
2. Draw another inside
3. Select both and merge

The inner area still has an area=yes tag

Expected: There is no area=yes tag

Workaround: Draw the inner area with the line tool

**Comment by bhousel** [comment]
I think this is working as expected, though maybe unintuitive.
Areas will have an `area=yes` tag until you retag them with something else..

![create multipolygon](https://cloud.githubusercontent.com/assets/38784/15524918/9d6d6948-21f3-11e6-8dc7-6d21e95cdde1.gif)

iD differentiates between a mulipolygon with an area outer and area inner (not a hole) - or an area outer and line inner (a hole).

**Comment by pnorman** [comment]
> I think this is working as expected, though maybe unintuitive.

I'd expect to be able to use the area tool for area drawing

> mulipolygon with an area outer and area inner (not a hole)

This is a hole - the hole just happens to itself be another area

**Comment by bhousel** [comment]
> This is a hole - the hole just happens to itself be another area

Isn't a hole more like.. the absence of area?

**Comment by pnorman** [comment]
Assuming way A is inside way B if you have

* way A and way B untagged, a MP with both as members and leisure=park, this represents a park polygon with a hole

* way A untagged, way B with area=yes, a MP with both members and leisure=park, this represents a polygon with a hole and a polygon with no tags coincident with the hole, which is also a data error, similar to a stray untagged node or way

**Comment by 1ec5** [comment]
[Here’s an area](http://www.openstreetmap.org/way/436339482) I drew specifically to knock a hole out of a building area. I had to manually remove the `area=yes` tag after merging it with the building area into a multipolygon relation. I would’ve expected iD to remove this tag upon merging.

**Comment by bhousel** [comment]
> Here’s an area I drew specifically to knock a hole out of a building area. I had to manually remove the area=yes tag after merging it with the building area into a multipolygon relation. I would’ve expected iD to remove this tag upon merging.

But 
1. if you had drawn a closed line instead of an area, then performed the merge, you would have gotten and empty space like what you were expecting
2. if you actually wanted an area feature inside the building (like grass or water) you could pick that preset and still get what you were expecting

I still think this is an example of iD doing exactly what you tell it to, even if it is not necessarily what you want.  

I did fill in the area icon with some shade (see #3109), as a hint that areas are filled with something.  But I'm open to more ideas that might make the area/closed-line distinction more clear?

**Comment by 1ec5** [comment]
> if you had drawn a closed line instead of an area, then performed the merge, you would have gotten an empty space like what you were expecting

Interesting, that’s something I had never even considered. When I learned you could merge something with an area to create a hole, I intuitively expected the area tool to be used for that operation, even if I didn’t want there to be a separate area after merging. I thought of the inner way as a sort of “negative area” rather than a wall that happened to form a ring.

> if you actually wanted an area feature inside the building (like grass or water) you could pick that preset and still get what you were expecting

Absolutely. Although at this point, after merging to create a multipolygon, I would’ve expected to have to draw a coincident area to represent the grass or water (or in the example I linked to above, the pavement in the courtyard).

> I did fill in the area icon with some shade (see #3109), as a hint that areas are filled with something.

That change has been helpful. Before it, I was blissfully unaware of the `area=yes` tag being added. To my knowledge, that tag’s presence on a multipolygon’s inner way doesn’t mess up any data consumers, but the shading irks my inner clean freak. 😉

**Comment by bhousel** [comment]
Closing.. This is working as expected.

**Comment by tyrasd** [comment]
In a presentation about OSM editing with the iD editor on 34C3 @nakaner demoed the creation of multipolygons and considered this behavior a bug: https://media.ccc.de/v/34c3-ChaosWest-21-einfa1_4hrung_in_den_openstreetmap_online_editor_id#t=1800 (around the 30 minute mark, talk is in German though).

Btw: there is some related discussion and possible solution to this (IMHO not very intuitive behavior of iD) in #2259.
