### ISSUE TITLE
Make certain things un-editable for beginners

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#3142]
I heard this suggestion from Dale of the Red Cross -- often at mapathons, people will mistakenly touch or move or somehow mess up things they shouldn't be editing -- an example is a task that's concerned with buildings but new editors goof up the roads. I saw another one where a new editor goofed up the Zambezi River. Maybe it would be possible to make certain things appear but you can't edit them, kind of like when you're zoomed out you can see roads but can't move them. He called it "beginner mode." Might save time for Red Cross/Missing Maps folks too so they can focus on the important features for that tasks and not fixing mistakes.

**Comment by planemad** [comment]
From experience conducting mapathons and training folks on mapping, many newbies have confessed to me that they were actually scared they could do something wrong and did not edit for fear of being reported or banned. 

In terms of UX, this is worth thinking about how to make the first few edits a guided learning process so one understands the basic do's and dont's to become comfortable with the mapping world. Rather than feature level restriction, i'm inclined for a geographic limitation that allows the first few edits around your home locations.

This could be a followup to the existing walkthrough, where `start editing prompts` for a home city/town from the user, and continues on with:
- Lets map an address, browse the map to your home or another address you are familiar with. Add a point...
- Lets draw a building with the area tool..
- Find a missing road or footpath...

Upon completion, the world should be unlocked for mapping!

**Comment by manfredbrandl** [comment]
Maybe we can have a beginners mode, where one can only add new features and cannot delete anything and only do modifictions which are neccesary for addings new features e.g. connect new road to existing one.

**Comment by RAytoun** [comment]
Unfortunately not all beginners are fortunate enough to be able to attend a Mapathon and have people around to help them when they have a problem. 
To that end I have in the past suggested a practice tile that is not connected to the OSM map where beginners could attempt mapping without the fear of messing up the work of others or making horrific mistakes. It could be set up with examples already on the tile such as a few buildings, a residential area, a secondary and tertiary road with residential roads interlaced, a wide river and a boundary in a relation. The walk through would give them the chance to select certain features to see how they are tagged and if they are accidentally moved then this would be brought to their attention. If they correctly drew, squared and tagged a building they would be complemented on that. It could explain the different features then give them the chance to map buildings, roads, farmlands, etc. Each time they save the tile will run a validation and show if something has not been done correctly, such as overlapping buildings, roads that do not join up, etc.
When they have successfully completed the practice tile they could then get the go ahead to move on to the actual OSM map. This would save a lot of work for the validators as the new mappers would be checked for the most common and regular errors that validators have to spend a lot of time amending.

**Comment by mikelmaron** [comment]
In discussion previously, seemed like a combination of setting feature filters by argument, and showing road overlay layer at lower zoom levels, could get most of the way there on this one

**Comment by bhousel** [comment]
I'm not really excited about any of these ideas.  

Our message to new users should be "OpenStreetMap is a safe place and you can't break anything, so have fun", not "Your edits aren't good enough until you prove yourself."

Maybe pro users that do validation and cleanup and reverts need better tools.  But that's not iD's domain.  My main concern is bringing new mappers into the project - and making them pass a course in order to edit is absolutely not the way to encourage people to get involved.

**Comment by slhh** [comment]
@bhousel 
> Our message to new users should be "OpenStreetMap is a safe place and you can't break anything, so have fun", not "Your edits aren't good enough until you prove yourself."

I agree, but iD doesn't provide that safe place yet. The above ideas aren't a solution, but seem to contain some valid points and background.
> My main concern is bringing new mappers into the project

This is important, but another main concern should be not to loose mappers,

- due to negative experience or feedback, 
- due to their work being destroyed by other mappers, or
- due to frustration because of the required amount of cleanup.

There seem to be regional differences of the weight of these concerns because the risk of destroying something is much lower where poor data exist. 
In order to bring more mappers into the project we do need to enable more applications, and destroying data frequently could disable applications.

> Maybe pro users that do validation and cleanup and reverts need better tools. But that's not iD's domain.

I agree, but we should think about what iD can do to support such tools. For example it might be useful to flag critical changesets or to spit large changesets into a critical and non-critical part.
And we should reduce the quantity of critical changeset as much as we can, because a few QA focosed JOSM users can't validate all changesets being generated by iD.

Because iD is usually the tool of the local mapper, iD should support cleaning up the local issues well,
but the non-locally OA focused users should better use JOSM.

**Comment by slhh** [comment]
I don't think it is a good idea to restrict new users to a subset of features to contribute, because this might not match to what the new user wants to contribute. Instead we can do:

- Encourage users to select an application specific mode, which is protecting other features. In this case iD can also give better support due to knowing what the user intends to do.

- Being able to contribute every feature type doesn't necessarily mean to be able to edit the database directly for each feature type. Instead iD could offer a method to generate a change request like a note, which is incorporated into the database by an more advanced mapper, but in addition to a description the change request should be able to contain drawn elements. Some features which might be protected this way are highways with relation and boundarys. In this case incorporating a change request seems to be easier than cleaning up potential damages when editing the database directly.

Using the change request method does also avoid the negative feedback, which the user potentially gets by a revert, changeset comment etc.

**Comment by aawiseman** [comment]
@slhh I like the mode idea too.

**Comment by dalekunce** [comment]
The idea is less of a defined mode for beginners and more of a way to do more  "focused"  editing. This would make the editing faster and easier during these periods. 

It would also ease editors into editing when the mapping is dense. Id already doesn't show all features when mapping in dense areas which is the cause of many many errors during mapathons.

**Comment by RAytoun** [comment]
I am in favour of any way that will help new mappers to get started without the fear of messing things up. While many of us are involved in Mapathons where we are on hand to help them get started ... and they do because they know we are there to help them get out of trouble. But I have been looking on http://www.resultmaps.neis-one.org/oooc and am now aware of how many tried to start up on their own and just got nowhere (little red people). These are the mappers we are losing because they have not got past the first edits.
