### ISSUE TITLE
Please add easy "one-click" square/rectangle option to Area clicking, like in PPT/Microsoft Paint, and a "Building" shortcut

### ISSUE THREAD

**Issue by Kenyat1989** [openstreetmap/iD#3189]
For each building, we now need to click 6 times to create the square/rectangle (clicking the four corners then double clicking to finalize).  Would be MUCH faster if added a one-click square/rectangle-making option like they have in PPT or Microsoft Paint. 

Also, adding a B shortcut rather than having to click B each time on the left would be great.

**Comment by bhousel** [comment]
There is some substantial work in progress on making rectangular buildings easier to draw, see #2699

**Comment by ianp5a** [comment]
_> Also, adding a B shortcut rather than having to click B each time on the left would be great._
I noticed in the animation on 2699 below, the Building attribute was automatic or bzdefault.
https://github.com/openstreetmap/iD/pull/2699
Is there a request or solution to make definign buildings quicker_
