### ISSUE TITLE
save iD editor tags to a new database

### ISSUE THREAD

**Issue by FranciscoCosta** [openstreetmap/iD#3307]
Hello everyone, I am editing iD editor so i can put some more tags on it. i would like to have the my new tags saved in my own database and the tags from OSM saved in OSM database.

After my idea was to display all tags in one webpage using openlayers. Can someone tell me how can i do this?

Thank you for all the help

**Comment by bhousel** [comment]
Sounds like a big project!   There's no easy way to do what you're trying to do.. You're just going to have to do some programming to keep the OSM and custom tags separate.

I'd suggest:
1. Make sure all of your custom tags have some kind of namespace like `NOT_OSM:name`.
2. Edit the [DiscardTags action](https://github.com/openstreetmap/iD/blob/master/modules/actions/discard_tags.js) so that any tag like this is discarded before saving to OSM.
3. [This block of code in save.js](https://github.com/openstreetmap/iD/blob/master/modules/actions/discard_tags.js) is where iD decides whether there is anything worth saving.  I'm not sure how you will split this up to save some tags into OSM and some tags into another database.  Maybe keep `history.changes` as OSM's changes, and make a new function to get the not-osm-changes?

**Comment by FranciscoCosta** [comment]
What if instead of uploading all the tags i only upload mine .
I mean in the "new" iD editor only have the new tags that i need and for the other tags i would simply redirect the user to osm id Editor?
then when i was going to display all the tags i just have to search in my database and in osm ? what do you think?

**Comment by bhousel** [comment]
> I mean in the "new" iD editor only have the new tags that i need and for the other tags i would simply redirect the user to osm id Editor?
> then when i was going to display all the tags i just have to search in my database and in osm ? what do you think?

Yes you could do that too.  It might be easier to make a separate iD editor with separate tags, rather than trying to make one iD editor that does everything and keeps tags separate.

**Comment by FranciscoCosta** [comment]
how can i do to to send the new tags to my own database?
