### ISSUE TITLE
Terms for non-searchable presets are included in translation resource

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#3323]
Take e.g. the new emergency=yes dummy preset, it has [`"searchable": false`](https://github.com/openstreetmap/iD/blob/b3d8d1313882f0a0d8e7c74a76505f294fedf213/data/presets/presets/emergency/_yes.json#L12), but its "terms" is still [in presets.yaml](https://github.com/openstreetmap/iD/blob/b3d8d1313882f0a0d8e7c74a76505f294fedf213/data/presets.yaml#L2181), causing translators to see the string `<translate with synonyms or related terms for 'Emergency Access Yes', separated by commas>` in Transifex.

I think this is unnecessary since it's not searchable anyway.

**Comment by bhousel** [comment]
Even though a user can't create a preset like that directly, an unsearchable preset will be used if it matches real data in OSM, or if a user manually edits the tags.

![emergency_presets](https://cloud.githubusercontent.com/assets/38784/17404558/1cf15cd8-5a2a-11e6-9cbf-306e664b6a37.gif)

So that example - deleting the amenity tag from a hospital with `emergency=yes` - is not likely to happen, but unsearchable presets are also used for displaying many of other deprecated tags (like `landuse=farm` or `craft=tailor`), so we should have the name translated.

Think of these presets as:  things we wish did not exist in OSM, but they do and so we have to recognize them.

**Comment by M1dgard** [comment]
I am aware of everything you just said, but it is not what I asked. Kindly reread my original post more thoroughly.

**Comment by M1dgard** [comment]
I was saying that their *terms* should not appear in the translation resource. Translating those is no use, since you can't find them anyway.

**Comment by bhousel** [comment]
Ok, sorry I did read this quickly.  I agree there is no reason to ask people to translate the `terms`.

**Comment by M1dgard** [comment]
No problem :)

**Comment by bhousel** [comment]
This is done..
