### ISSUE TITLE
Add in "Salvage Yard" or "Junk Yard" area type

### ISSUE THREAD

**Issue by rlerner** [openstreetmap/iD#3387]
For designating automotive scrap yards, steel recycling scrap yards, "U-Pull-It" etc.

**Comment by pnorman** [comment]
What tags are appropriate here?

**Comment by bhousel** [comment]
Recent tagging thread here:  https://lists.openstreetmap.org/pipermail/tagging/2016-January/028178.html
(that didn't really resolve the issue)

Reasonable tags include: 
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_transfer_station

**Comment by bhousel** [comment]
I added a Waste Transfer Station preset.

Let's hold off on `amenity=scrapyard` vs `industrial=scrap_yard` until there is better consensus.
(`amenity=scrapyard` has a few more uses and seemed to be the preferred tag in that [tagging mailing list thread](https://lists.openstreetmap.org/pipermail/tagging/2016-January/028178.html), but `industrial=scrap_yard` is close and has a [wiki page](https://wiki.openstreetmap.org/wiki/Tag:industrial%3Dscrap_yard))

**Comment by pnorman** [comment]
> Let's hold off on amenity=scrapyard vs industrial=scrap_yard until there is better consensus.

Is this a case where they should be added as non-searchable presets?

**Comment by bhousel** [comment]
> Is this a case where they should be added as non-searchable presets?

I don't think so, both tags have such low usage that there is no point at this time.

**Comment by bhousel** [comment]
This has been open for a long time so I'm just adding the `amenity=scrapyard` preset to close it out.

The [OpenStreetMap wiki](https://wiki.openstreetmap.org/wiki/Tag:industrial%3Dscrap_yard) suggests that `landuse=industrial + industrial=scrap_yard` is the tag to use.  I actually tried for a while today to create the preset this way, but it was causing me a lot of problems:

* `industrial=` is not a "toplevel" tag, so it [does not get `tag_classes`](https://github.com/openstreetmap/iD/blob/04cc4d7ec013531cfd6d268f4757ae85847179e4/modules/svg/tag_classes.js#L6) unless the `landuse=industrial` tag is present.  The tag classes are what allow us to adjust the rendering style of all the features and the preset icons.
* All of the `landuse=*` presets are area-only features, not POI style things that can be mapped as either nodes or areas.  A feature that shows fields like `operator`, `address`, `opening_hours` is an amenity/shop/office/etc, not a landuse.
* `landuse=` areas [do not render icons](https://github.com/openstreetmap/iD/blob/04cc4d7ec013531cfd6d268f4757ae85847179e4/modules/svg/labels.js#L72).  If we did that, the map would be full of unnecessary icons.  So to show an icon on this POI-like landuse would require extra hacky code.
* Compound tags need special `addTags` and `removeTags` properties in order to recognize the primary tag `industrial=scrap_yard` even if the other tag `landuse=industrial` is missing. 
* There are only 150 uses of `industrial=scrap_yard` in OpenStreetMap as opposed to 91 uses of `amenity=scrapyard`.  These are both _very low numbers_.   This means that there is still time to "fix" the tag to be something more consistent with how other tags work in OpenStreetMap.

So `amenity=scrapyard` it is...  🔧 

I don't normally write up a long post like this, but this is another situation where we're going against the recommendation of the OpenStreetMap wiki for good reasons, and I think it's useful to explain why in detail so that people who invent new tags or work on the wiki have a better understanding of some of the challenges we face when consuming and writing tools for OpenStreetMap.

**Comment by bhousel** [comment]
per https://github.com/openstreetmap/iD/issues/4466#issuecomment-339187977
We can do the same thing for `industrial=scrap_yard`, even though it might have some of the drawbacks listed above.  I deprecated the `amenity=scrapyard` preset that I created last June, and made an `industrial=scrap_yard` one instead.
