### ISSUE TITLE
All devDeps should be ^

### ISSUE THREAD

**Issue by tmcw** [openstreetmap/iD#3400]
Greenkeeper is making a lot of noise about point releases of rollup, etc. We should switch all devDependencies to ^: major releases of devDependencies will still be unlikely to result in functionality changes to iD or even the bundle contents, and will be automatically accommodated by the version range, thus reducing noise.

**Comment by bhousel** [comment]
No, `rollup` is at semver v0.x and I'm not comfortable using a range for it until it releases a v1.x 

Additionally, container caching on Travis means that our automated processes may be running with outdated dependencies that are still within range.  This is fine for nonessential dependencies like `eslint` or `mocha`, but for something core to iD, I'd prefer the safety of a fixed version.

Finally, if we are going to use a range (and I do for a bunch of dependencies), I'd prefer to use ~ over ^, because that way Greenkeeper lets me know when new things are available, along with a summary in the PR.  I'm not going to follow all those other projects and pay attention to whatever new features or bugfixes they release.

Try to see Greenkeeper more as signal, not as noise.  It's performing a useful service for me that I don't have time to do myself.  It has already found a version of `lodash` that would have broken iD if we were using a ^ semver range (#3343).
