### ISSUE TITLE
Slim down intro_graph

### ISSUE THREAD

**Issue by tmcw** [openstreetmap/iD#3403]
After #3344, iD.min.js is 2mb. Not a terribly large bundle - not top priority to slim it down. But intro_graph.json takes up 25% of that size - 500kb without whitespace. Ideally we can reduce the size of intro_graph significantly.

**Comment by bhousel** [comment]
Yeah, I thought about this.. https://github.com/openstreetmap/iD/issues/1336#issuecomment-166441749

I think it's mostly the river geometries that extend far beyond the parts of town where the tutorial happens.

Check out `imagery.json` - we can probably save some space there too..

**Comment by bhousel** [comment]
One weird but necessary thing `rollup-plugin-json` does is generate "gunky" output when importing json.  (see https://github.com/rollup/rollup-plugin-json/issues/5)

It creates a lot of extra keys -- but only the toplevel ones..

So instead of importing json with a lot of toplevel properties:
```js
{'node1':{stuff}, 'node2':{stuff}, ... many more }
... then ...
import { default } from '../../../data/intro_graph.json';
```
...we get far less "gunk" in the generated bundle if we wrap each json file in a toplevel property:
```
{ 
  introGraphRaw: {'node1':{stuff}, 'node2':{stuff}, ... many more }
}
... then ...
import { introGraphRaw } from '../../../data/intro_graph.json';
```

This might be a good workaround for your issue https://github.com/rollup/rollup-plugin-json/issues/11 too.

**Comment by bhousel** [comment]
Yeah, good suggestion @iandees.. I was actually thinking of adding some "paper streets" somewhere in a farm field and having the user to delete them in the Lines chapter.  Sound good?

**Comment by iandees** [comment]
Yea, that makes sense.

**Comment by bhousel** [comment]
> After #3344, iD.min.js is 2mb. Not a terribly large bundle - not top priority to slim it down.

So an update!

These days iD has grown to be an 11mb bundle, which is now "terribly large" and a "top priority to slim it down".  So I'm doing that.

Most of the bloat is from data files like the presets, imagery, community index, and other stuff.  I made a data loader that will let us fetch these things at runtime and as needed instead of having them bundled in.  

Another side benefit will be that we can even fetch some of these assets from a CDN if we want to.  JSDelivr lets us request a file with appropriate semver range - so that we could have things like the community index or name suggestion index on a separate release schedule from the core iD code.  iD will just fetch the latest compatible version (#4994!)

I did the intro_graph first, and it's kind of nice to see that giant pink box shrink by almost half a megabyte.

#### before
<img width="1362" alt="Screenshot 2020-01-27 17 23 23" src="https://user-images.githubusercontent.com/38784/73219438-21386f80-412a-11ea-9a1f-17bc047a2967.png">

#### after
<img width="1360" alt="Screenshot 2020-01-27 17 23 35" src="https://user-images.githubusercontent.com/38784/73219456-2990aa80-412a-11ea-95c7-f651361deb33.png">

Ok, I admit - pretty underwhelming.  But I'll spend some time on this, and we'll have much smaller and faster builds soon!
