### ISSUE TITLE
Red Buildings aren't visible for Red/Green colorblind folks.

### ISSUE THREAD

**Issue by dalekunce** [openstreetmap/iD#3421]
We have received reports from some colorblind participants at mapathons that the red building color is not visible. Would it be possible to have an option for a colorblind friendly color palate.

**Comment by bhousel** [comment]
Hey @dalekunce, because iD uses CSS and SVG for all its rendering, you can override the colors pretty easily with the Stylish extension on [Firefox](https://addons.mozilla.org/firefox/addon/stylish/) or [Chrome](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe).

I wrote up a tutorial here on how to do it:
https://github.com/openstreetmap/iD/issues/3095#issuecomment-224988925

We don't have an official colorblind style for iD, but if somebody creates one I would happily link to it in our FAQ.

**Comment by dalekunce** [comment]
Awesome job @tallguy.

**Comment by Nick-Tallguy** [comment]
http://learnosm.org/en/hot-tips/enhance/
