### ISSUE TITLE
Jammu Kashmir not shown as a part of India

### ISSUE THREAD

**Issue by Pikesh** [openstreetmap/iD#3426]

**Comment by kepta** [comment]
cc @planemad

**Comment by bhousel** [comment]
Can you share a screenshot? 

If you are talking about the boundary data, iD shows the administrative boundary data as it exists in OSM.

Aside from the OSM data, iD also sometimes displays a raster "locator overlay" that shows some cities and boundaries (e.g. in the minimap or at low zooms) - but any issues with the locator overlay should be reported to a different upstream project.  If this is what you are reporting, I can forward your screenshot to someone who maintains that project.

**Comment by Pikesh** [comment]
Regards,

Pikesh Prasoon

Solution Integrator            | Ericsson India Global Services Pvt Ltd,
Bengaluru <http://www.ericsson.com/>
Ex-Coordinator & Faculty | KIIT Robotics Society
<https://www.facebook.com/kiitroboticssociety/>

*  <https://in.linkedin.com/in/pikesh72prasoon>  **
<http://www.youtube.com/user/pikeshmn> *
+91-809376178

`

**Comment by kepta** [comment]
@bhousel I believe this is related to the Indian law which says that the PoK and aksai chin be shown as part of Indian territory. 
I wonder how that applies to OSM data.

**Comment by planemad** [comment]
Issue might be this:

**OSM Homepage** - Defacto boundaries [as per territory controlled](https://commons.wikimedia.org/wiki/File:India_Pakistan_China_Disputed_Areas_Map.png)
<img width="403" alt="screenshot 2016-09-16 23 23 51" src="https://cloud.githubusercontent.com/assets/126868/18595968/b32105f8-7c64-11e6-81f2-be2cdbf592de.png">
_https://www.openstreetmap.org/#map=6/34.606/77.366_

**OSM India** - as per [Indian law](http://www.thehindu.com/news/national/rs100cr-fine-proposed-for-wrong-india-map/article8562502.ece)
<img width="476" alt="screenshot 2016-09-16 23 24 12" src="https://cloud.githubusercontent.com/assets/126868/18595969/b379e6dc-7c64-11e6-84a5-418602579903.png">
_http://openstreetmap.in/#6/34.742/77.673_

Since the default OSM rendering follows a [neutral policy](http://wiki.osmfoundation.org/w/images/d/d8/DisputedTerritoriesInformation.pdf), the homepage rendering is accurate and cannot be altered to suit a particular bias. The workaround is for users in India to use the tiles from http://openstreetmap.in

The OSM data itself is objective and has appropriate tags to indicate all disputed regions http://overpass-turbo.eu/s/iqq

@Pikesh does this clarify the issue?

cc @bhousel @kepta

**Comment by bhousel** [comment]
Closing as there is nothing actionable here for us to do
