### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by mcnis** [openstreetmap/iD#3446]
The buildings are not showing up in the map is it possible to update the map. When ever i open Bing maps all new buildings are shown 

![image](https://cloud.githubusercontent.com/assets/22354063/18725678/40a3c4b2-800f-11e6-9f4c-fd0ffc308228.png)

**Comment by bhousel** [comment]
Please see [this FAQ item](https://github.com/openstreetmap/iD/blob/master/FAQ.md#how-can-i-report-an-issue-with-background-imagery) on how to report issues with Bing and Mapbox imagery.

iD's background imagery sources come from the [editor-layer-index](https://github.com/osmlab/editor-layer-index) project.  If you know of a better imagery source that is licensed for this use, please open a request there with the link and license details.

Bing might show different imagery at different zoom levels, so that might be why you see inconsistent results?  I'm not sure.  Can you provide a screenshot of what you see in Bing?

**Comment by mcnis** [comment]
Ok what i found is that Bing is using an old map of when no buildings were in some areas i have to go to google map to find the buildings
![image](https://cloud.githubusercontent.com/assets/22354063/18727004/e2ac68ea-8014-11e6-93c1-6ab137d66675.png)

**Comment by bhousel** [comment]
> Ok what i found is that Bing is using an old map of when no buildings were in some areas i have to go to google map to find the buildings

Thanks for looking into this..  We are really not allowed to use Google Maps as a source for adding anything to OpenStreetMap, so the best thing to do is to just wait until newer imagery is available of this location (or to go there personally and record the positions of the buildings with a GPS receiver or some other method).

**Comment by dmgroom** [comment]
It would be a good idea if custom imagery sources which have "google" in the URL were prevented from being used as a background in ID.  I've just come across one user , using ID, making changes to OSM based on  Google imagery

**Comment by bhousel** [comment]
> It would be a good idea if custom imagery sources which have "google" in the URL were prevented from being used as a background in ID. I've just come across one user , using ID, making changes to OSM based on Google imagery

We already do this - [see code here](https://github.com/openstreetmap/iD/blob/9e50af529bc90759e65a86db6e7a92d47508aa82/modules/ui/background.js#L112-L115), however I'm not sure these checks catch all google domains.  If we need to change this code, can you please open a new issue?
