### ISSUE TITLE
Show tooltip for long background names 

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3448]
Similar to #3447 there is also a problem where backgrounds with long names are not fully visible. I notice bing/mapbox/osm have tooltip descriptions which pop-up. Can the same be done with for other backgrounds?

**Comment by bhousel** [comment]
The tooltips for the background imagery sources are taken from the [editor-layer-index](https://github.com/osmlab/editor-layer-index) project.  If the source has a `description` property, we show it in a tooltip.  So the best way to get a tooltip is to update the source description on that project.

For example:  the TIGER2014 layer says "At zoom level 16+, public domain map data from the US Census...." because of [this description property](https://github.com/osmlab/editor-layer-index/blob/1e82d790758f6c343c989d8db8b5308ab73707bd/sources/north-america/us/TIGER2014RoadsOverlay.geojson?short_path=53eacad#L11).

iD adds some descriptions to [global sources that don't have them](https://github.com/openstreetmap/iD/blob/4f733e1b9658992e8892e534abbe52cb26da9f59/data/update_imagery.js#L46-L50) - we should probably move these descriptions over to the sources themselves...

**Comment by boothym** [comment]
So should I just copy the name to the description or come up with a description that mentions the full name? I'm happy to do the latter but since it's iD that is doing the truncating with the CSS padding-right I was hoping it could be solved in iD itself. :)

Perhaps iD could show the name in the tooltip, only if the description is empty and the name is longer than say, 32 characters? That way any new background which appears with a long name and no description can be shown.

**Comment by bhousel** [comment]
hmm, I see what you mean, yes iD should probably show something for long names that are cut off.  Sorry I closed it bc I thought it was just about adding tooltips to sources that didn't have them.

**Comment by boothym** [comment]
Is there somewhere to test this, as https://www.openstreetmap.us/iD/master/ is 404?

**Comment by bhousel** [comment]
@boothym Can you try with  http://id.openstreetmap.us.s3-website-us-east-1.amazonaws.com/master/

The openstreetmap.us server changed, so our mirrors are on s3 now, and I need to update the README.
