### ISSUE TITLE
Presets: Creating Sub-Categories

### ISSUE THREAD

**Issue by ptivel** [openstreetmap/iD#3461]
When Customizing ID editor Presets and how they appear in the UI is it possible to create sub categories (a drop down menu of features within a drop down menu of features)?

**Comment by bhousel** [comment]
This does sort of work, but it's not something we do in the current list and so there may be some odd issues if you try it.

For example, you can edit the [`landuse.json` category](https://github.com/openstreetmap/iD/blob/master/data/presets/categories/landuse.json) to include `category-golf`:

```js
    "category-landuse": {
        "geometry": "area",
        "name": "Land Use Features",
        "icon": "land-use",
        "members": [
            "category-golf",
            "landuse/residential",
            "landuse/industrial",
            "landuse/commercial",
    ... 
```

Rebuild, and then you will get a preset list like this when you use iD:

![nested_categories](https://cloud.githubusercontent.com/assets/38784/19221070/a269c8f6-8e09-11e6-8f39-721a5e379e14.gif)


The javascript code can handle it, but if you look closely you can see that the CSS styling is a little weird when you expand the "Golf" subcategory.  This is probably easy to fix, but since we haven't set the menus up this way, nobody has thought about improving the list styling for nested categories.
