### ISSUE TITLE
amenity=register_office

### ISSUE THREAD

**Issue by artischocke** [openstreetmap/iD#3480]
While translating some strings into Spanish, I noticed this tag but its Wiki page states that its usage is discouraged in favor of `office=government` + `government=register_office`.

**Comment by bhousel** [comment]
Yes, we have [that preset](https://github.com/openstreetmap/iD/blob/master/data/presets/presets/amenity/_register_office.json) marked as non-searchable. This means users can not enter it, but iD will recognize them where they exist already in OSM and display them.  That's why there are translation strings for it.

**Comment by artischocke** [comment]
Good to know! Thanks for the feedback. Now I know to look for `searchable` before opening  an issue. Cheers.
