### ISSUE TITLE
Assisted Edits

### ISSUE THREAD

**Issue by jharpster** [openstreetmap/iD#3502]
Was editing with a small group of developers and they thought it would be possible to create a computer 'assisted edit'. Where a client side algorithm quickly detects building corners from a single click or draws sections of roads by identifying end points.  This would not be automated extraction but rather a method to speed up editing.

Has this or a similar approach been discussed? I couldn't find any open or closed issue on the topic.

**Comment by bhousel** [comment]
I think @tmcw wrote something about this a while ago, but I can't find it now.

This is a tricky problem because the background imagery may not have the right cross-origin headers set, and without that, you can't access the image pixels in client code.  That doesn't mean that assisted editing is impossible, just that there's an extra security hurdle to clear before code running in the iD window can access imagery pixel data.

See [this stackoverflow post](http://stackoverflow.com/questions/23239967/get-pixels-color-from-an-html-image-serving-from-external-url) for more info.

Would love to see someone tackle this problem in a plugin, if we end up building a real plugin architecture into iD.

**Comment by jharpster** [comment]
Thanks for the response @bhousel . I'll bring up the CORS issues with the team and get their take on it. Since Bing hosts the image tiles we might be able to exert some influence on that. Assisted editing might work better as a JOSM plugin, we'll do some more investigation and let you know how it turns out.
