### ISSUE TITLE
Adding points: form for attributes not showing.

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3506]
I am working on a modified version here: https://github.com/osmottawa/CrowdiD
When adding a new point, the form to enter attributes is not showing. I am not sure why.
If anyone has a clue for me, I will be eternally grateful beyond the grave!

**Comment by Monduiz** [comment]
uiz commented 3 minutes ago

After some testing, the difference with a new point added on the map is in the panelwrap div. It receives a style="right: -100%". Other elements have "right: 0%".

**Comment by Monduiz** [comment]
This is very odd. By playing with the styling in console, the form shows up. To fill it you have to search the feature.
![screen shot 2016-10-15 at 5 20 12 pm](https://cloud.githubusercontent.com/assets/8759714/19413481/f436c1ca-931d-11e6-99e3-be48c951b973.png)

**Comment by bhousel** [comment]
Issues like this are going to be tricky to debug, in part because of how you copied the iD code.  It looks like you don't have a true fork of iD, but instead you copied the files somewhere and checked them into git.  It's totally ok for you do this, but it means that our codebases have diverged and you won't be able to accept any new changes to the iD code.

Before you get too far into this project, you should probably read this excellent guide: 
[How to maintain a git remote fork](https://rhonabwy.com/2016/04/04/how-to-maintain-a-git-remote-fork/).

To summarize - it's really hard to keep a fork in sync with the main project.  There are 2 main approaches:
1. Change the iD code, then always rebase your changes onto the end of the upstream project's head.   So your project will always be "iD + some commits".  Whenever you update iD, you'll run `git rebase` or `git cherry-pick` and fix whatever conflicts happen.  [macrocosm/iD](https://github.com/macrocosm/iD) and [strava/iD](https://github.com/macrocosm/iD) work this way.
2. Don't touch the iD code, and instead write scripts that replace things in iD.  You might use `cp`, `sed`, `perl`, or whatever tool to reach into iD and perform surgery on parts of it.  [nationalparkservice/places-editor](https://github.com/nationalparkservice/places-editor/) works this way (see [npmapInstall.js](https://github.com/nationalparkservice/places-editor/blob/master/npmapInstall.js))

So, in cases where your code does something that iD doesn't do - obviously it's from something you did to it!  A good way to figure out what happened is to use the `git bisect` command - it lets you specify a "good" commit and a "bad" commit, and will check out different versions of your code to narrow down which commit introduced the bug.

Hope this was all helpful!

**Comment by Monduiz** [comment]
Thank you, it was very helpful.

My problem is that I had no control over the development. Our IT did this and didn't follow recommendations. I didn't have time to start over.

I was stuck fixing their work. It's been a big headache to work this way. I was in damage control on left on my own to fix a broken app and I had no idea what they did to it.

I plan on starting it from scratch exactly like you suggested which is what should have happened in the first place.

Thanks, Bryan.
