### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3528]
I have setup osm-auth but when a user grants access, when id reloads, the user is not authenticated in iD. The info bar (info-list) at the bottom is not showing the user name (object "userLink").

I am using this to authenticate:

	 var auth = osmAuth({
	    singlepage: true,
            oauth_consumer_key: '5A043yRSEugj4DJ5TljuapfnrflWDte8jTOcWLlT',
            oauth_secret: 'aB3jKq1TRsCOUrfOIZ6oQMEDmv2ptV76PA54NGLL',
            landing: "land_single.html"
        });
    document.getElementById('authenticate').onclick = function() {
            auth.authenticate(function() {
            });
        };

I must be missing something.

**Comment by bhousel** [comment]
Are you calling preauth, [like openstreetmap-website does](https://github.com/openstreetmap/openstreetmap-website/blob/7725cd59b41a622a634a447d33fbda738a472748/app/views/site/id.html.erb#L29-L36) ?  Your `land_single.html` page will need to collect all those tokens and pass them to iD.  You don't strictly need to _have_ a `land_single.html` page - instead you can just check for the cookies to be set with JavaScript and only start iD if they are present.   Let's move this discussion to https://github.com/osmlab/osm-auth/issues/21 and I will try to create a better example in that repository of how to authenticate with a single page instead of a popup.

Also, another issue I see - this is not preventing your authentication from working, but a nice thing to do would be to register your application on openstreetmap-website, rather than reusing the iD oauth tokens.  To do this, go to openstreetmap.org, click on "My Settings" and then click "oauth settings", and scroll to the very bottom where it says "My Client Applications", and register your application.

**Comment by Monduiz** [comment]
I was just looking at that, funnily enough. No, I am not calling preauth. Thank you for the example!

I completely forgot to register the application, thanks for this!

**Comment by Monduiz** [comment]
When clicking on an authentication link and using landing: 'index.html' the app loads with "?oauth_token=" but iD doesnt load with the user's authentication even if oauth_token is in the url.

**Comment by Monduiz** [comment]
The reason why I posted here is because the osm-auth repo doesnt appear to be active and questions asked in the issues are not likely to be discussed.

**Comment by bhousel** [comment]
> The reason why I posted here is because the osm-auth repo doesnt appear to be active and questions asked in the issues are not likely to be discussed.

Its ok, I only just started watching osm-auth 2 weeks ago, but I'm going to assume a more active role in maintaining it..
