### ISSUE TITLE
Need a way to know when map has been loaded

### ISSUE THREAD

**Issue by Monduiz** [openstreetmap/iD#3550]
I am using id.map().centerZoom([-75.7106, 45.4241], 12); to make iD load over a particular area but it doesnt work if the page is not index.html.

It works on my main page but a different name page, it doesnt zoom to the area.

**Comment by bhousel** [comment]
Any errors?  It seems weird that this line of code would fail...

**Comment by Monduiz** [comment]
I am getting a few GET maptiles not found but no errors relevant to id.map.

**Comment by bhousel** [comment]
I checked out your code and `index.html` doesn't work either

You moved assets to an `assets` folder, but `index.html` is looking for them in `/dist`.

![screenshot 2016-11-05 13 19 23](https://cloud.githubusercontent.com/assets/38784/20032139/9e09c250-a35a-11e6-9ff9-887ca9330420.png)

**Comment by Monduiz** [comment]
This is strange because the assets folder is for other ressources. The dist folder is still there.

**Comment by bhousel** [comment]
oh wait, you're still using a Makefile.  Let me try making the assets..

**Comment by bhousel** [comment]
Ok I see what's happening.. This is interesting and has to do with how iD loads itself into the container.

start at [this line](https://github.com/Monduiz/CrowdiD2/blob/733975a91d42377b4bd05e9490977f8e2d0f2330/indexFr.html#L191)..
```js
id.ui()(document.getElementById('id-container'));
```

...calls [here](https://github.com/Monduiz/CrowdiD2/blob/733975a91d42377b4bd05e9490977f8e2d0f2330/modules/ui/init.js#L296-L302)

```js
    function ui(node) {
        var container = d3.select(node);
        context.container(container);
        context.loadLocale(function() {
            render(container);
        });
    }
```

... calls [here](https://github.com/Monduiz/CrowdiD2/blob/733975a91d42377b4bd05e9490977f8e2d0f2330/modules/core/context.js#L322-L333)

```js
    context.loadLocale = function(cb) {
        if (locale && locale !== 'en' && dataLocales.indexOf(locale) !== -1) {
            localePath = localePath || context.asset('locales/' + locale + '.json');
            d3.json(localePath, function(err, result) {
                addTranslation(locale, result);
                setLocale(locale);
                cb();
            });
        } else {
            cb();
        }
    };
```

So this is a weird function.. If the locale is `en`, this locale already bundled in iD.js and so it calls the callback _synchronously_ - `cb()` gets called immediately.  But if the locale is not `en`, we use `d3.json` to load it _asynchronously_ - `cb()` gets called later.

The reason your `indexFR.html` won't change the map location on the next line after calling `id.ui()(container);` is because the map hasn't actually been set up yet. It's waiting for the French language file to finish loading.

I think to make this really work we need to add a callback parameter to that `ui` function, or emit a `loaded` event, or rethink the flow to make it better.

**Comment by bhousel** [comment]
Also worth mentioning that things would probably work ok if you set the location in the url hash before starting iD.

something like
```js
window.location.hash = '#background=Bing&map=12/-75.7106/45.4241';
```

**Comment by Monduiz** [comment]
This is very interesting. I was using this approach before trying to use the map functions. Is tehre a difference in using hash instead of window.location.replace?

**Comment by bhousel** [comment]
> Is there a difference in using hash instead of window.location.replace?

I don't know, to be honest.  `window.location.replace` might be better, by not writing a history entry.

**Comment by bhousel** [comment]
I added an optional callback to `ui` initializer so that you can know when the map is ready (i.e. `loadLocale` is done).   This code works now:

```js
        id = iD.Context(window)
            .presets(iD.dataPresets)
            .imagery(iD.dataImagery)
            .locale('fr')
            .assetPath('dist/');

        id.ui()(document.getElementById('id-container'), function(err) {
            if (!err) {
                id.map().centerZoom([-75.7106, 45.4241], 12);
            }
        });
```

**Comment by Monduiz** [comment]
Awesome!
