### ISSUE TITLE
Turning_loop preset

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3557]
At the moment there is no preset for turning_loop, which is basically a turning_circle with a non-traversable island in the middle. It has 17k uses and is rendered on the standard map.

In the preset list: turning loop should be represented by a circle with a hole in the middle, to show it has an island.

In the actual editor: turning loop should take the icon currently used by turning circle, and a new all-white icon added for turning circle - see image:
![loopcircle](https://cloud.githubusercontent.com/assets/16965772/20034411/4eff3518-a3b5-11e6-9a99-3f35ca7d9981.jpg)
(ignore the fact I wrote turning circle on what is a loop, just a rendering example!)

**Comment by bhousel** [comment]
Haha I did not know that that's what it's called.  I've been drawing circular ways around those things.

Yes, go ahead and add it, you can probably just copy the `turning_circle` preset.

**Comment by boothym** [comment]
Well you can do either it seems, depending on how much work you want to do!

I was going to add it, but didn't know how to sort the images as the preset is just a "circle" at the moment.

**Comment by bhousel** [comment]
> I was going to add it, but didn't know how to sort the images as the preset is just a "circle" at the moment.

Oh I see what you mean about the icon, try to set them like this:

`turning_loop.json` => `"icon": "circle"`
`turning_circle.json` =>  `"icon": "circle-stroked"`

I keep a mirror of the old maki icons [here](https://github.com/bhousel/maki/tree/mb-pages/src).

**Comment by slhh** [comment]
> Haha I did not know that that's what it's called. I've been drawing circular ways around those things.

I believe most user can't sufficiently differentiate between these terms. Translated version of iD would make things even worse, because the translated terms can't be found in the wiki. In some languages different terms for the two types might not exist or might interfere with railway infrastructure.
According to the wiki drawing circular ways seems to be prefered for turning loops.
I see the following options:
1. Make a single preset with a checkbox to select with or without an island. This would likely need some preset infrastructure programming, but it might be worth because of being reuseable for other presets.
2. Make the turning loop preset non searchable, forcing users to draw the loop.
3. Use two presets, make both searchable by the same terms, and use discriptive preset names like:
    "turning loop with non-traversable island" and "turning circle, fully traverseable".

**Comment by bhousel** [comment]
The icons now work like this:
* use open stroked circle for traversable features (turning_circle, mini-roundabout)
* use closed circle for non-traversable features (turning_loop, island)

The icons are meaningful, and although this change makes the suburbs look different, people will get used to it.
<img width="367" alt="screenshot 2016-11-06 22 37 28" src="https://cloud.githubusercontent.com/assets/38784/20045702/a89064b4-a471-11e6-8263-8104259a09bf.png">


<img width="672" alt="screenshot 2016-11-06 22 33 27" src="https://cloud.githubusercontent.com/assets/38784/20045656/1a8a2baa-a471-11e6-96b2-c5b9c0fc4847.png">

**Comment by slhh** [comment]
The icons in the map are good, but the icons in the first screenshot look confusing, more as if they were swapped. This might be due to an invisible outer ring due to using the background color.

I suggest to change "Turning Loop (Island)" to "Turning Loop (w/ Island)".
Otherwise users might use it to tag the island of a turning loop which is drawn by circular way.

**Comment by bhousel** [comment]
> I suggest to change "Turning Loop (Island)" to "Turning Loop (w/ Island)".
> Otherwise users might use it to tag the island of a turning loop which is drawn by circular way.

The preset is only available on a vertex, so it's not really possible for a user to add this as a standalone node in the middle of the circular way.  Let's try it for a while and see if people are confused by it.

**Comment by althio** [comment]
> The icons in the map are good, but the icons in the first screenshot look confusing, more as if they were swapped. This might be due to an invisible outer ring due to using the background color.

:+1:
Maybe add (to icons on list) the same thin outer lines (as the icons on the map)?

**Comment by bhousel** [comment]
> Maybe add (to icons on list) the same thin outer lines (as the icons on the map)?

This is a good idea worth trying, i'll open an new issue for it..
