### ISSUE TITLE
Order of (highway) category presets

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3558]
At the moment to add an unclassified road or track you must scroll down the the highway category of presets.

Although you only need to do this once per session, it's still bit annoying to have to scroll down. Since these are the 3rd and 4th most used highway tags, I think it makes sense to have them above the various *_link presets. 

Also, perhaps the order of both the highway and path categories could be rearranged to put the most used presets nearer the top? For example, the highway category could be changed to list in order from tertiary to motorway. The path category has path and steps at the bottom - they should really be higher up.

**Comment by bhousel** [comment]
We order the highways according to hierarchy, but yes I agree "Unclassified" should be after "Tertiary" and before the link roads.

I don't think we should order highways by frequency of use.  This comes up for discussion sometimes, and we always try to leave the highway preset order mostly hierarchical.  The preset list menu is partly for people to pick presets, but more importantly it's a teaching tool, so we organize it the way the road network is organized.  

We expect that once people learn what presets they use for mapping, they will probably use the search to find them rather than scrolling through menus (and in fact the walkthrough intentionally nudges new users towards searching for presets like this).

**Comment by bhousel** [comment]
I adjusted the order a bit in 08d81c3, hope that's an improvement!

**Comment by boothym** [comment]
Thanks, that's better for the roads. 👍 I saw they were ordered by hierarchy, but wondered if it should instead be the opposite order - i.e. from tertiary to motorway - since that also matches the most-used order.
