### ISSUE TITLE
Replace low valued keys from the sidebar with ones of higher value: capacity, takeaway, smoking -> contact, payment, lunch, internet_access

### ISSUE THREAD

**Issue by bkil** [openstreetmap/iD#3570]
I propose that we remove `smoking` from the sidebar of most amenities (including but not limited to `pub`, `cafe`, `restaurant`). In most countries, smoking has been banned for a long time, so we could default to `no` anyway. If a mapper would like to specify, she always has the choice to add it via the dropdown at the bottom.

https://en.wikipedia.org/wiki/List_of_smoking_bans

Taginfo returns 45% for `no` and 24% for `outside` (which is a different way to say `no`). I have a feeling that many of the `yes`/`dedicated` ones could be mistaggings of `amenity=smoking_area` as well.

https://taginfo.openstreetmap.org/keys/smoking#values

As an alternative, it would be great to have preset side panels which are country specific, or even user specific. For example, neither the `operator` nor the `brand` in a pub is of general interest in Hungary, because most pubs keep many common variants in stock and usually don't identify with a single brand.

Don't get me wrong - it is nice to have a list of brands served a pub, however this can change a lot over the years. So whether to add this should be left to the mapper.

For some other countries, it is more important to know whether a given amenity offers `power_supply` while you are having your drink, or whether it has any chairs at all to sit on.

The same could be told about many other fields present currently. This should be examined for each kind of POI, but let's stay with restaurants.

For example, Taginfo gives the following ranking for `amenity=restaurant` combinations:

* `name`
* `cuisine`
* `addr:*`
* `website` & `contact:website`
* `phone` & `contact:phone`
* `source` (I don't feel that this one should go to the sidebar by default, though, and it's mostly `survey` anyway)
* `opening_hours`
* `wheelchair`
* and only then `smoking` (mostly `no` anyway as per above)
* `takeaway` (not very useful in my experience)
* `email` & `contact:email`
* `operator`
* `internet_access`
* `outdoor_seating`
* `delivery`
* `capacity` (I usually try to fill it in but I see no great use for this, see below)
* ...

https://taginfo.openstreetmap.org/tags/amenity=restaurant#combinations

Note the funny fact that while `takeaway` and `delivery` are used much less than contact information, these options rent a place on the sidebar, while contact information do not. 

Nonetheless, what worth is it in knowing that you can deliver food from a restaurant to your home without having any contact information over which you could order?

If you wanted to organize an event (like a wedding) at such a restaurant, the fact that 200 people could theoretically be seated tells little about whether they have this capacity split over 1 or 2 large halls, over many small rooms, or whether they calculated with using portable garden chairs in the back yard to arrive at this number. (It is most of the times stated on the website) Neither does this tell us whether they have a matching kitchen capacity as well, or if they usually just let rooms for business meetings without food, etc.

Then again, because contact information is deprioritized, we can't ask them to clarify. We could of course check how the rooms look via their Instagram/G+ gallery, if given, but that's also contact information.

I've now realized that the way `iD` arranged its interface affected how I do mapping and where I put my efforts. That, unfortunately had sometimes been proven to be a suboptimal direction.

Others frequently ask what to map for each kind POI, and while we can't usually give a definite answer because they get turned off when told `everything`, there usually exist best practices which should be followed - doing the best bang for the buck.

If I had to prioritize keys, here's my ranking:

* GPS position
* `opening_hours` (I could pay a visit when open and ask for every other key in person)
* `cuisine` (mostly for party tricks, otherwise most of the restaurants could be categorized as mostly international)
* `contact:phone`, `contact:website`, `contact:facebook` (I could check or ask for any other key)
* `payment:*` (FAQ I get every day: can you pay with a debit card, contactless, with an electronic leisure card, or cash only?)
* `name` (changes (bi-)annually at many places, usually more often than contacts!)
* `lunch:*` (it has come into fashion again in the recent decade around here in most restaurants and pubs)
* `delivery` (delivery range would be more useful, though)
* `internet_access:*` (good to know which network to connect to when multiple ones are in range)
* `addr:*` (usually deducible from surroundings, we have coordinates anyway)
* `outdoor_seating`
* `contact:email` (my favorite, though most people would disagree)
* `brand` (I rarely find it useful for restaurants)
* `operator` (even less useful for me)
* `capacity` (see above)
* `takeaway` (are there places which decline to give you your food after you paid for it?)
* `source` (also present in changeset/comments, can be different for different editors)
* `smoking` (let's default to `no`)
* `wheelchair` (it is generally difficult for lay people to assess this correctly, so they should add it manually when obvious)

**Comment by bhousel** [comment]
There's a lot to process in your issue, so I'll try to address all of it.  Happy to discuss your suggestions..

We can't add so many fields to the sidebar - as you can see the Restaurant preset is already pretty full:
<img width="350" alt="screenshot 2016-11-16 10 56 22" src="https://cloud.githubusercontent.com/assets/38784/20354215/71c0aba2-abeb-11e6-8dcb-f8454ee943d8.png">

So, these sidebar fields are really for the "most important" things that we want collected about the feature.  As you go down the list, the fields become less important.  And there will always be disagreements about what "most important" means.  

1. Many of the tags you want to see, re: contact information are available under the universal fields dropdown.  (We don't have 'email', maybe we should add this).  Another potential solution would be for me to build a magic "contact info" field that lets people tag more kinds of `contact` things, like facebook, twitter, google+, instagram.  OSM is not a business directory and there is lower value in tagging this stuff than other things, but I agree that people should have an easy way to contribute it.

1. You may say "replace `smoking` with `outdoor_seating` or `lunch`", but the tags that are there are on that screen because a lot of people want to see them.  For example, the smoking tag is used 87k times..  `outdoor_seating` is used 26k times, so if you want a checkbox for that, sure I'd have no problem adding it.  `lunch` is used 187 times, and I have no idea why - `opening_hours` tells you if a place is open for lunch.

1. iD does not default tags (like `smoking=no`).  This would upset a lot of people if all restaurants automatically got a `smoking=no` tag.

1. We don't show `operator` or `brand` on Restaurants, Pubs, Cafes.. So I'm not sure why you are asking us to remove it?  `brand` is not for the brand of food or alcohol served at these places, it is for the brand of the chain store, like "Applebee's" or "Pizza Hut".

Anyway, if you want to suggest small changes to the sidebar, I'd be willing to consider them, but I can't add a lot of low-value contact info fields and throw away frequently used tags like `smoking` just because you don't want to see it.

**Comment by bhousel** [comment]
Closing as #3568 covers some of these... If you think of additional specific preset improvements that fit iD's design goals, please open individual tickets for them.
