### ISSUE TITLE
Selecting a lot of objects is slow

### ISSUE THREAD

**Issue by emj** [openstreetmap/iD#3571]
When selecting <20 objects CPU usage goes up to 100% and stays there for a short while, when you select >100 objects "a while"  is more than 10 seconds, I didn't wait for it to finnish.

When cpu usage is  at 100% iD does not respond to anything.

**Comment by pnorman** [comment]
probably #2911

**Comment by emj** [comment]
Yes sorry, that sounds about right, thanks! In my defence I did try to search for it..

**Comment by bhousel** [comment]
Yes this is related to #2911, but a bit different.
I think I'm adding the interpolator inefficiently using `selection.each`.  There is probably a better way to do it.

**Comment by quincylvania** [comment]
Turns out the `end` event of D3 transitions is called once for every element in the selection, not once for the whole transition. This meant there was an exponential hit to performance for every additional selected element. While there are doubtless other ways to improve breathe performance, my testing showed that fixing this one issue made it possible to have hundreds of items selected without iD becoming unresponsive.
