### ISSUE TITLE
Imagerie update?

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/iD#3591]
Recently data/imagery.json has been updated in https://github.com/openstreetmap/iD/commit/c85a352c7f13c7cd590d028be7dc55c380c351d3

I would have expected to see recent changes like https://github.com/osmlab/editor-layer-index/issues/157 nom in data/imagery.json but apparently this layer did not made it into the current master.

Is this just because the file was generated with outdated editor-layer-index data, or might this be a problem while generating the file?

**Comment by bhousel** [comment]
Thanks for flagging.. Because `editor-layer-index` is not versioned, it's possible that `npm install` might not update it, resulting in iD bundling an older copy.  The recent 2.0.0 release did include some new imagery, but I'm planning a 2.0.1 patch release to fix a few issues, and will make sure to really refresh the imagery.

**Comment by bhousel** [comment]
This was done in e331bb7, and released today!

**Comment by sommerluk** [comment]
Thanks!

2016-11-17 19:53 GMT, Bryan Housel <notifications@github.com>:
> This was done in e331bb7, and released today!
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/openstreetmap/iD/issues/3591#issuecomment-261351209


-- 
Lukas Sommer
