### ISSUE TITLE
Map moving on mouse wheel click has stopped working

### ISSUE THREAD

**Issue by edpop** [openstreetmap/iD#3612]
Unlike v1.9.7, mouse wheel click has stopped working. It is necessary to draw ways.
I'm trying to find this change in the code...

**Comment by bhousel** [comment]
Yes, unfortunately it's pretty much impossible to do blames/bisects between v1.9.x and v2.0.x code.

This might have been something that changed with the upgrade to d3 v4.  Can you describe a bit more about what the issue is?  I've never tried clicking the mousewheel, so I'm not really sure what the previous behavior was.

**Comment by edpop** [comment]
You could move the map by clicking on the mouse wheel, when you were at draw mode.

**Comment by bhousel** [comment]
Hey @edpop I might have fixed this in 77b78a7.   

The default d3 zoom event filter was doing something like `event.button === 0` (left button only), and I [adjusted it here](https://github.com/openstreetmap/iD/commit/77b78a73ca6343006e089df505a0dec062d1edad#diff-941aa7b2c44d2d015cb63f82424da372R182) to say `event.button !== 2` (ignore right clicks). 

When you get a chance, can you test in http://openstreetmap.us/iD/master and see if mouse wheel clicks are working again, and if so close?

**Comment by edpop** [comment]
Thanks, it works very nice!
