### ISSUE TITLE
Line style of inner and outer of MP differ with no apparent reason

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#3613]
![image](https://cloud.githubusercontent.com/assets/1190866/20584058/fa852680-b1a3-11e6-99f7-95a635d5934c.png)

This is a MP with landuse=residential, no tags on the ways. The outer line is white, the inner one is yellow, but there's no apparent reason.

**Comment by bhousel** [comment]
@pnorman just looking into this today.. Does it correct the rendering when you move the map?  I was noticing that we don't redraw the multipolygon in the correct styling immediately when it's created.

**Comment by pnorman** [comment]
The order things are drawn in might matter.

I did this with two lines, combining them, then adding landuse=residential to the MP

![image](https://cloud.githubusercontent.com/assets/1190866/21846115/5f85c892-d7aa-11e6-8b11-d33cdbe024a5.png)

On move the inner white turned yellow.

**Comment by bhousel** [comment]
Ok, thanks for the info @pnorman... I *think* what's going on here is that we aren't re-drawing the ways after the relation changes so they keep their same style.  This is because the ways haven't actually changed when you modify the parent relation.  Moving the map forces a full redraw to happen and then everything looks right.
