### ISSUE TITLE
Also display tags in the left panel which reference known fields, but may not be part of the current preset

### ISSUE THREAD

**Issue by bkil** [openstreetmap/iD#3618]
Let's take the example of `internet_access`. Although it is not part of `amenity=school`, a mapper could have plausibly indicated that it is physically available by entering it manually. Other mappers using `iD` should see this directly on the left panel, not hidden under the 'all-tags' section.

A much more important use case would be adding fields for `contact:*`, most prominently `contact:phone` and `contact:website` (pull request ready). If a user sees that a POI already has a website given as `contact:website`, they will not enter a `website` redundantly. At present, because `contact:website` is out of sight, many users add the same information again using the legacy key by mistake.

A different workaround for the second use case would involve creating special forms to handle all contact keys which have two accepted representation. A single place would be reserved on the sidebar for the user to enter this information. If none of the keys are present, newly entered data would use the new format. If either form is present, that one would be displayed and edited (optionally: when modified, save in new form). If both are present, display both. Although handling this case should be similar to how phone_1, phone_2, etc is handled.

**Comment by bhousel** [comment]
> Let's take the example of internet_access. Although it is not part of amenity=school, a mapper could have plausibly indicated that it is physically available by entering it manually. Other mappers using iD should see this directly on the left panel, not hidden under the 'all-tags' section.

Maybe.. I'd have to think about that.  There might be good reason to not show certain fields for certain presets, even if they are real fields used on other presets.  #2908 is something that came to mind, where we've received complaints that iD allows users to add universal fields like `address` to features that they should not appear on. 

> A much more important use case would be adding fields for contact:*, most prominently contact:phone and contact:website (pull request ready). If a user sees that a POI already has a website given as contact:website, they will not enter a website redundantly. At present, because contact:website is out of sight, many users add the same information again using the legacy key by mistake.

I thought the `contact:` namespace was generally not used anymore?  The original `phone`, `website` tags far outnumber the `contact:phone`, `contact:website` tags.  My understanding is that the proposal had been dead since even before iD launched 3 years ago.

> If none of the keys are present, newly entered data would use the new format. If either form is present, that one would be displayed and edited (optionally: when modified, save in new form). If both are present, display both.

This feels like a lot of work for me to figure out which field to show, while not really making OpenStreetMap any better.  I definitely don't want to display _both_ `contact:phone` and `phone`.  Is there another way?

**Comment by althio** [comment]
> I thought the contact: namespace was generally not used anymore? The original phone, website tags far outnumber the contact:phone, contact:website tags. My understanding is that the proposal had been dead since even before iD launched 3 years ago.

I think the `contact:` namespace is alive, but it is hard to outnumber such previous common tags without an automated edit AND modified presets in editors. So raw numbers are not that relevant IMO.
![taghistory](https://cloud.githubusercontent.com/assets/9863567/20662071/266f53cc-b552-11e6-8057-876372064084.png)

**Comment by bkil** [comment]
On Mon, Nov 28, 2016 at 6:45 AM, Bryan Housel <notifications@github.com>
wrote:

> Let's take the example of internet_access. Although it is not part of
> amenity=school, a mapper could have plausibly  the
>
> Maybe.. I'd have to think about that. There might be good reason to not
> show certain fields for certain presets, even if they are real fields used
> on other presets. #2908 <https://github.com/openstreetmap/iD/issues/2908>
> is something that came to mind, where we've received complaints that iD
> allows users to add universal fields like address to features that they
> should not appear on.
>
>


> A much more important use case would be adding fields for contact:*, most
> prominently contact:phone and contact:website (pull request ready). If a
> user sees that a POI already has a website given as contact:website, they
> will not enter a website redundantly. At present, because contact:website
> is out of sight, many users add the same information again using the legacy
> key by mistake.
>
> I thought the contact: namespace was generally not used anymore? The
> original phone, website tags far outnumber the contact:phone,
> contact:website tags. My understanding is that the proposal had been dead
> since even before iD launched 3 years ago.
>
>
The ratio is much better for the tags where editors don't default to the
legacy keys (because they don't have outdated presets for them):
* email vs. contact:email: 149k vs. 59k (*)
* fax vs. contact:fax: 79k vs 40k (*)
* facebook vs. contact:facebook: 4k vs. 10k
* google_plus vs. contact:google_plus: 5 vs. 1836
* twitter vs. contact:twitter: 644 vs. 1801
* webcam vs. contact:webcam: 43 vs. 404

I now see that JOSM also has `email=*` and `fax=*` on its forms. The
results are not bad despite all this.

There are two problems with mass conversion. One is that while some of the
keys could be translated painlessly, like email. However, others have been
reused for various purposes because a lack of form capabilities. For
example, website is used for almost anything, and it's a pain to recover
source:url,contact:twitter/facebook/... from website, website_1, website_2,
url, link, etc.

A second, more troublesome issue is that if we mass migrated all of these
legacy keys, the values as displayed by popular editors would instantly
disappear to users. This is unacceptable, so any kind of mass change can
only come after both popular editors and some major data consumers are
adjusted to support both schemes. This is a good time for iD to step up
with a solution.


> If none of the keys are present, newly entered data would use the new
> format. If either form is present, that one would be displayed and edited
> (optionally: when modified, save in new form). If both are present, display
> both.
>
> This feels like a lot of work for me to figure out which field to show,
> while not really making OpenStreetMap any better. I definitely don't want
> to display *both* contact:phone and phone. Is there another way?
>

Well, actually I enter contact:phone together with contact_phone_1, 2, etc.
a lot, because most venues publish a landline along with at least a mobile
phone number as well, so I"d definitely consider displaying such numbered
variants anyway.

However, a bit cheaper solution would be to use contact:phone (and website)
exclusively instead of phone to load and save form information when
editing. If contact:phone is missing, copy the value of phone onto the form
and remove the old tag, hence it will get saved as contact:phone. Although,
it would be great according to the principle of least surprise if this was
reverted when the form is closed without changes.

That doesn't sound like much code, though if you accept this, I could add a
PoC if you wish.

-

What worries me more is that iD in its present state only slows me down,
and something tells me that there could be other experienced contributors
with the same feeling as well. The ratio of me editing a form field and
adding to the all-tags section is about 1:6.

The all-tags editor has some funky look-up, prediction, auto correct and
focus stealing that keep me from typing all data as fast I can, otherwise
random mistakes start to creep in.

Sadly, my workflow of mass adding these tags by tabbing through
key/value/add also got sabotaged by the recently added feature that
instantly sorts the added key.

There is no issue while one is hunt & pecking and using a very fast
Internet connection. However, one is screwed if one can touch type or if
one's connection is a bit high on latency (sometimes 100-200ms?) or
experiences glitches. Sometimes I wished iD had a single big multi-line
text editor box in which I could simply type all data in key=value form one
tag per line and be done with it. I.e., automatically add/update tags when
the user navigates away.

**Comment by bkil** [comment]
Sorry, forgot one answer:

> #2908 <#2908>
>  is something that came to mind, where we've received complaints that iD
>  allows users to add universal fields like address to features that they
>  should not appear on.

So the original proposal above was to show the foreign field only if it has already been populated by others. No new empty field would be displayed to confuse users.

Although, you're right in that I'd be delighted if we added many fields to many presets, though iD probably needs an advanced mode for that or a different UI for unpopulated things.

**Comment by bhousel** [comment]
> What worries me more is that iD in its present state only slows me down, and something tells me that there could be other experienced contributors with the same feeling as well. The ratio of me editing a form field and adding to the all-tags section is about 1:6.

So use JOSM - more efficient editing by experienced contributors is what it's for.  iD is probably not for you.

I spend kind of a lot of time responding to your issues, and I feel like we're going to keep just talking past each other because we disagree on how tags should work in OSM (you think editor software should follow what the wiki says, and I think we should follow actual tag usage), and we disagree on how complexity of OSM tagging should be presented to people who have never edited a map before (you want to see a field for every tag, and I think we already show too many fields).

>A second, more troublesome issue is that if we mass migrated all of these
legacy keys, the values as displayed by popular editors would instantly
disappear to users. This is unacceptable, so any kind of mass change can
only come after both popular editors and some major data consumers are
adjusted to support both schemes. This is a good time for iD to step up
with a solution.

If the OSM community ever did want to mass change a tag like this, I'd be totally fine with it.  Somebody (who?) would say "Hey Bryan we are changing the tag from `phone` to `contact:phone` because good reasons.  This database change will happen on so-and-so-date during whatever-maintainance-window, can you have a new version of iD ready to support the new tag?" and I'd say "Sure that's like a 15 minute change, I will have iD `v2.whatever` ready for you to merge in before you bring the database back online."   (We did a somewhat-coordinated update like this when osm-carto changed their highway colors last year.)

What _doesn't_ work is having someone change a wiki page and expecting data to magically change itself.  This has been known for a long time. 

> Sometimes I wished iD had a single big multi-line text editor box in which I could simply type all data in key=value form one tag per line and be done with it. I.e., automatically add/update tags when the user navigates away.

So fork iD and build this.  I'd be totally happy if somebody made an iD-Advanced.  Or use level0?   

Please be nice and understand that iD is not optimized for people who already know what all the tags are.  I'm happy if somebody just opens the editor and adds a few small details.
