### ISSUE TITLE
Remove "Covered" field in bus stop preset

### ISSUE THREAD

**Issue by virgilinojuca** [openstreetmap/iD#3627]
Currently, the bus stop preset in iD suggests six additional tags. All of them are listed in the [bus stop tag wiki page](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop) as useful combinations, except for “covered”. I think that it should not be on the preset.

“Covered” causes confusion with “shelter”, which *is* the correct tag to indicate if a bus stop offers or is covered by a shelter. Even the [wiki page for `covered=*`](https://wiki.openstreetmap.org/wiki/Key:covered) does not mention anything about bus stops.

For comparison, JOSM does not suggest `covered=*` in its bus stop preset, but instead `bench=*`, `shelter=*`, `bin=*` and `tactile_paving=*`.

**Comment by bhousel** [comment]
looks like it was added in #2451 
Yes I agree the `covered=*` tag is unnecessary here.

**Comment by boothym** [comment]
Didn't realise that it wasn't listed for use in the wiki with the bus stop tag. I've been using it assuming it was correct for the tag, though I'm not the only one - 2384 UK bus stops are now tagged with covered=*. All but 100 have been edited since 2015-02-15 - the date iD 1.7.0 was released with the covered field. 

It seems like the inclusion in iD has meant lots of mappers have added covered and basically duplicated the shelter information. Over 1700 are now tagged either as yes/yes or no/no. Here's a recent example from an iD user: https://www.openstreetmap.org/node/496715014/

But it's also caused confusion, with the definition of both tags. The combination of shelter=no and covered=yes is interesting (used 200 times), as it looks like some mappers are using covered as halfway between a fully enclosed shelter and a half-open shelter.

Here's a few examples, all tagged as covered=yes and shelter=no:
https://goo.gl/maps/tjM7eDFtKKF2
https://goo.gl/maps/gndrYXxhnLU2
https://goo.gl/maps/TQ3AtbJfHuQ2
https://goo.gl/maps/5t8qSTsH7dq

So yes definitely remove this field.

**Comment by bhousel** [comment]
Thanks for looking into it @boothym 
1700 is not too many, somebody could review them with an overpass query I think.

In my mind `covered=yes` is just a way of saying that a building roof is covering a feature.  So for example, if you have a drive through lane running under the roof of a bank, you would put `covered=yes` on that little segment so that you don't trigger validation warnings about the road intersecting with the building.  Or a building that extends out over a waterway, you could put `covered=yes` on the waterway to avoid triggering a warning.

btw, please don't link to Google Streetview (I know it's just for example but I don't want people to make OSM edits based on that).

**Comment by virgilinojuca** [comment]
Exactly, @bhousel. I completely agree with you understanding of `covered=yes`. Because of that, at least the way I see it, a bus stop *still* can be “`covered`” — when it is under a roof of some *other* building (and even so, that might be debatable for each case). However, this is a more specific and rare case that in my opinion shouldn't have a dedicated field on the preset, especially if it can easily cause confusion with a more obvious and direct property of a bus stop, which is `shelter=*`.

Thanks for removing it.
