### ISSUE TITLE
Unable to toggle oneway to yes on highways

### ISSUE THREAD

**Issue by davidchiles** [openstreetmap/iD#3638]
On highways I'm unable to toggle away from `oneway=no` to `oneway=yes` using the checkboxes. 

[Screen recording](https://dl.dropboxusercontent.com/u/622803/id_bug.mov)

macOS 10.12.1 
Chrome 55.0.2883.75 (64-bit)

**Comment by tyrasd** [comment]
confirming (chrome 53 / ubuntu 16.10).

**Comment by bhousel** [comment]
Thanks for the report!  This is something that I accidentally introduced during the iD v2 refactor, and it's a weird side effect of how JavaScript and D3 works.

You could trigger the bug by switching directly from one preset with a oneway to another preset with a oneway.  D3 _does not re-enter_ the field in that situation, and so the existing click handler was getting re-used.  Because that click handler uses a closure variable `value`, that variable would stay around from "the time that the function was first created", i.e. the _original_ oneway field.

The fix is: any handlers that use closure variables need to be assigned on the "update" selection, not the "enter" selection.

bad:
```js
// select the field, join to [0] to create singleton
var field = selection.selectAll('.foo')
  .data([0]);

// create dom elements that don't yet exist
var enter = field.enter()
  .append('input')
  .attr('class', 'foo')
  .on('click', function() { ... do something with value closure variable... });

// merge enter selection into update selection
var input = input
  .merge(enter);
```

good:
```js
// select the field, join to [0] to create singleton
var field = selection.selectAll('.foo')
  .data([0]);

// create dom elements that don't yet exist
var enter = field.enter()
  .append('input')
  .attr('class', 'foo');

// merge enter selection into update selection
var input = input
  .merge(enter);

// update selection runs every time
input
  .on('click', function() { ... do something with value closure variable... });
```
