### ISSUE TITLE
Can't close path in tutorial

### ISSUE THREAD

**Issue by ysangkok** [openstreetmap/iD#3675]
I didn't make my first point the right place, and now I can't close the area, since the first point is outside the 'valid' area...

![screenshot](http://i.imgur.com/ptCKnYf.png)

**Comment by bhousel** [comment]
Thanks for the report!  I think I can change the curtain to track the shape, rather than leaving it stuck that size.

Users can also click the navigation on the bottom of the screen to skip around to different parts of the tutorial if they get stuck, but that's not obvious.  Maybe I can add some text about that..
