### ISSUE TITLE
Merging node and way should preserve node 

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#3683]
JOSM merging of a node and a way (probably with a plugin) moves the node into the way to keep the history.
If the way has unsaved nodes one of them could be reused, otherwise probaby the newest (highest id) node should be replaced by the merged node.

**Comment by bhousel** [comment]
I'm confused and trying to better understand this issue.

In iD as far as I can tell,
- Dragging a node onto a way works as you describe.  The node becomes a vertex along the way and is preserved.
- Selecting a Node and a Way and using the '+' Merge operation:  copies the tags from the node to the way and deletes the node.  I'm not sure why you'd want to preserve the node in this case.

**Comment by HolgerJeromin** [comment]
Me point is your second scenario.
The node can have a long history in the database. 
By deleting the node it is not so easy to find the history of any information which got new in the osm way.

**Comment by slhh** [comment]
I would prefer the more general approch #3694.

**Comment by bhousel** [comment]
> The node can have a long history in the database.
> By deleting the node it is not so easy to find the history of any information which got new in the osm way.

Can you provide a situation where you'd want to look back at the long history of the node?  It's just not something I have ever wanted to do.

I could probably remove all the tags from the original node and insert it along the edge of the target way, swapping out a different uninteresting node, but there is no guarantee that it would stay around very long after that.

**Comment by pnorman** [comment]
Some people do this, but it's not a universal practice and to a certain extent I'm iffy on it.

**Comment by HolgerJeromin** [comment]
Analysing the source of the new information of this way would have been easier:
http://osm.mapki.com/history/way.php?id=428734862
But iD made a new node while destroying the old POI node
http://osm.mapki.com/history/node.php?id=4300974290

**Comment by slhh** [comment]
> Can you provide a situation where you'd want to look back at the long history of the node? It's just not something I have ever wanted to do.

The node contains a part of the tagging history of the real feature. If something looks strange with the tags it doesn't make sense to ask the user who has mergered point and area, instead you have to look who has added the tag to the node, or has removed it from the node. You may also wan't to see the changeset comment. In case you have any doubts that the node has been merged to the right building, you wan't to check where the node was originally. Maybe someone has accidentially moved the node, and the next user has merged it to the building at the new position. 

@bhousel You doesn't seem to have a strong desire to see the OSM history anyway. Could that be due to mapping in regions with low data and user density, or due to mainly adding features? In my opinion access to history is very important when maintaining anything.

**Comment by HolgerJeromin** [comment]
Thanks!
