### ISSUE TITLE
async adding of wikidata does only work with enwiki

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#3684]
I really like adding wikidata, but this seems to work only with English wikipedia entries. At least i had problems with the german
http://www.openstreetmap.org/way/370577766
but not with the English http://www.openstreetmap.org/way/383100293

ref #2732

**Comment by Virtakuono** [comment]
Since @bhousel mentioned this on IRC, I felt like trying this out and added an English wikipedia tag (or rather replaced a Turkish one with its English counterpart) here: http://www.openstreetmap.org/changeset/44882335 seems like there is something going on with also english tags.

**Comment by Virtakuono** [comment]
Ok, did a little more trying out and noticed the following:

If I go directly to the "all tags" section and enter a key wikipedia and a value for it, iD consistently fails to fetch the wikidata tag.

If I go to "add field" and type in Wikipedia, push tab and enter the value and push tab again to move the cursor onwards, wikidata tag fetching fails again.

However, If I go to "add field", type in Wikipedia, push tab, enter the value, wait long enough for the suggestions to appear in a dropdown menu, choose the appropriate suggestion and push enter instead of tab, the wikidata tag is added automatically.

I'm using the same rather slow setup as in https://github.com/openstreetmap/iD/issues/2876, with Chrome updated to  55.0.2883.95 (64-bit).

**Comment by bhousel** [comment]
Thanks @Virtakuono for testing this out!  BTW which language did you test with?

> If I go directly to the "all tags" section and enter a key wikipedia and a value for it, iD consistently fails to fetch the wikidata tag.

Yes, iD doesn't have wikidata lookup code for the all tags section.  I'm open to the idea of adding this, we just didn't do it yet.

> If I go to "add field" and type in Wikipedia, push tab and enter the value and push tab again to move the cursor onwards, wikidata tag fetching fails again.

It's possible you might have moved very quickly (or like you said, slow network) and the wikidata lookup returned after you moved on to something else.

> However, If I go to "add field", type in Wikipedia, push tab, enter the value, wait long enough for the suggestions to appear in a dropdown menu, choose the appropriate suggestion and push enter instead of tab, the wikidata tag is added automatically.

Hmm, enter vs tab shouldn't matter, and I did just try it both ways.  But yes, from this it sounds like it might be the slow network / issue from #2876 re autocomplete.

**Comment by Virtakuono** [comment]
Oh, sorry, forgot to mention that I did the tests above with English wikipedia. Now that I try the things again with Turkish, I get the same result. Turkish wikipedia works too, if I just patiently wait for the dropdown menu to appear. However, the enter vs tab does matter, in both English and Turkish. If I just scroll down the dropdown menu using up/down keys until I reach the right entry and then push tab, the wikidata item will not get added. If I push enter (or choose the appropriate item from the dropdown menu using mouse), all seems to work like it should.
