### ISSUE TITLE
Please explain difference between object and feature

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#3689]
I do translations for iD into German and did up to now translate object and feature with the same german word "Objekt". Maybe there is an important difference between object and feature and there should be different german words for these. Can anybody please help?

**Comment by bhousel** [comment]
Good question.. We don't use these words consistently in our text strings.

Some of the confusion probably comes from [this recent commit](https://github.com/openstreetmap/iD/commit/37534aed0e9af6f456c8b0df31547bbc8fdc4089#diff-314927013736b5fc4ce3abd2a1710db8).

The previous strings said things like:
- "Deleted a point"
- "Deleted a line"
- "Deleted {n} _objects_"
- "This _feature_ can't be deleted because it hasn't been fully downloaded." even for multiple selected things.

A problem with that was that when deleting multiple features, we still printed the "This feature can't..." warning.  Because the word _object_ was there already, I changed the warnings to say:
- single:
  - "This object can't be deleted because..." 
- multiple:
  - "These objects can't be deleted because..."

However, "object" usually means a real thing that you can touch, and lots of things in OpenStreetMap are not real world touchable objects.  They are boundaries or invisible areas around things.  So we should probably use the word _"feature"_ which is more generic.

**Comment by manfredbrandl** [comment]
Thank you for the explanation, language is complicated. There is no good German word for "feature" so I will continue to use "Objekt" for "object" and "feature". In German "Objekt" can also mean "data object" and this is what we edit here as we do not "edit" real touchable objects. You may close this issue. By the way: There was criticism for some of my translations in German forums. I would like to get reviewers for translations. Maybe you could add "review translations" to Contributing.md (Translating)?

**Comment by slhh** [comment]
@bhousel Just an idea: Do we need different terms to describe the real feature (e.g. a landuse) and the circular way or multipolygon member way defining its area?

**Comment by bhousel** [comment]
> Thank you for the explanation, language is complicated. There is no good German word for "feature" to use in iD, so I will continue to use "Objekt" for "object" and "feature".

I'm going to try to standardize on calling everything "features" in the source strings.  I just pushed a change so the new strings should show up on Transifex tonight.  "Object" or "Item" are also fine words to use. 

> There was criticism for some of my translations in German forums.

Sorry to hear that, and I hope that criticism on the German forums doesn't discourage you from continuing your work!  They criticize everything.

> I would like to get reviewers for translations. Maybe you could add "review translations" to Contributing.md (Translating)?

I'm not sure we really want that?  Reviewing on Transifex can only be done by certain users and once a string is marked as reviewed, it is locked and can't be changed except by an admin.  For a project this small, I'm worried that it would introduce extra work for me.
