### ISSUE TITLE
Too long translations are clipped

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#3691]
As a translator, it's hard to foresee when a translation won't fit.

 "You just edited OpenStreetMap!"|Some presets
----|----
![just-edited](https://cloud.githubusercontent.com/assets/4283376/21532995/77b27144-cd56-11e6-8cc1-0954c5af21f3.png)|![presets](https://cloud.githubusercontent.com/assets/4283376/21533003/866890ec-cd56-11e6-97d3-b18cce58e456.png)

I have since made these translations shorter. It's difficult to convey the full meaning of some things concisely though.

**Comment by bhousel** [comment]
> I have since made these translations shorter. It's difficult to convey the full meaning of some things concisely though.

Yes it really is hard to convey a lot of meaning in just a few words, especially for preset names.  I struggle with that in English too.  You can also help by trying to make sure that whatever pops up with the user hits the "i" info icon is useful text.  This text is pulled from the OSM Wiki for the given tag, and is also volunteer contributed.

My best suggestion is to try to keep the translated strings around the same length as the source strings.

**Comment by slhh** [comment]
Chinese and Arabic need less space than English for the same content, but most languages based on latin script seem to need a little more space than English. In addition OSM tags are based on English, therefore, English words will likely fit quite better than words of other languages as preset names in most cases. For this reason we should assume that the current preset name text fields are too short in some cases.

Can we change the preset name field to support multi-line text? I think 2 or maybe even 3 lines of vertically centered text would fit in the same box size. This will look less nice, but only if we do really make use of it. Therefore, we should still try to keep preset names short, but where longer preset names are really required we should not impair function for a nicer look.

In some cases tags definition are too complicated to make it clear even if we were using a three line preset name. Therefore, we should be able to indicate that the preset name is not a sufficient definition for the specific preset, and the wiki needs to be read. For example we can add an attention sign to the "i" button in this case. In most of such cases we will likely need a similar indication on the wikilink too, because the short description from the wiki is still insufficient. We need to make this indication language dependent, because what is quite easy to define in one language can be difficult in another language. In order to make it language dependent we can define an optional  special character (e.g. "!") prefix for the (translated) preset name string, which is automatically striped off for preset name display, but controls the attention indications.
