### ISSUE TITLE
Add a Newbie mode

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3692]
ID should have a newbie mode (task accoring to #3123). This mode should be active by default and can be switched of by the user.
This mode can

- be more protective/limited, e.g. in view of #3681,
- be more supportive, e.g. additional hover text,
- and have a slightly simplified user interface.

For the normal mode this means we do no longer need to care about absolute newbies. This simplifies adding software features which are quite useful for the normal local mapper, but might confuse newbies.

**Comment by bhousel** [comment]
All of iD is designed with newbies in mind, so adding a "Newbie mode" really doesn't make sense.  If anything, we might add an "Expert mode" (#2929) so that power users who really know what they are doing can skip the checks that we've added.

For what it's worth, I try to use the following precedence in all design decisions, and in prioritizing how I spend my time: 

1. People who have never edited a map before
2. People who use iD regularly as their primary map editor
3. Developers who actually use OSM data for something and need the data to be a certain way
4. Developers who have forked iD and built something cool and open with it
5. Developers who have forked iD and built something uncool / secret with it
6. People who don't use iD but pop by our issue tracker and make polite and helpful suggestions
7. Everyone else

**Comment by slhh** [comment]
@bhousel We don't need an expert mode of the kind "I'm an expert, and don't need editor checks". Maybe some users would prefer it, but in my opinion this is not useful even for power-users. We do not need to support power-users, JOSM would be the better tool for them anyway.

Overriding some protections individually by modifier seems to be required for non-power users too. I would not call a local mapper, who wants to remap a junction of his town, where bus lines are, to be a power mapper or expert. The same applies to someone who wants to map the local bus lines intentionally. I think these local mappers deserve full support of iD. Do you agree?

We should not prioritize between newbies and these local mappers in view of design. We need to serve both groups well. If we are not able to do it with a single operation mode, we should provide different modes. I think a good compromise would be possible, but in case you want it extremely simple or some overprotection (e.g. large features) because of the newbies, we seem to need two different modes.
I have analyzed, which phase has most different requirements, and I came to the conclusion that this is the short phase of likely a few hours of playing around to understand the editor. After understanding the basic editor functions, a few more UI elements should not matter anymore.
I have proposed to make this phase a special mode and not the remaining phases for the following reasons:
- The phase is short,
- Finding an active task to switch off is easier than to finding an inactive task to switch on. (at least with your taskbar proposal)
- Later phases do potentially need more additional tasks and therefore space in the taskbar.
- We can hide the taskbar container in newbie mode this way.

**Comment by Slawek234** [comment]
Sometimes there are really beginner mappers.
In the version/mode for beginners, the editor would help to learn editing by a new mapper for a while, for example:

If the new maper would do, for example: 5 skew of houses building composed of 4 or 6, 7 nodes not having right angles because the user did not press the S key then floating info would appear (and in each case) until the user in a row will make 5 corners with straight angles.

another case the maper made a mistake and dragged by mistake the way in such a way that it overlaps other roads and creates sharp angles impossible to overcome on public roads then you could receive info with caution and information that here and here is something wrong and asking whether there was not a mistake?

A similar scheme can be used to finish editing, the editor checks if everything is correct and asks if there has been a mistake because here and here new tags have appeared, or do I want to add them to the map without discussion with the community? New map makers tend not to create new tags. They learn to apply existing ones.

The same area was drawn on the road, for example: forest drawn in the forest (because someone forgot make wisible the hidden layer) Perhaps the question is whether I want it for sure? A bit annoying, but at the beginning someone needs to get a little better when the beginner gets nervous while studying.

First, we would have to find the most common beginner errors, and then add the possibility to find them by the ID editor itself during editing or before sending to the server. Generally, I want the maper to be aware that something is wrong. The editor could help him by relieving other mapers.

Interestingly, it could add information to the set of changes if the new maper make serious mistakes and is unreformable despite many reminders from the ID editor.

Why is the option for super-beginner mapers?
Because I suspect that such an editor will be a bit more heavy, because he will have to devote some of his power to watching the progress in learning the new mapper.

By the way, I don't like option of remembering editor settings.
Spoils, sometimes I forget that something once turned on which favors editing errors
