### ISSUE TITLE
Use improved tag statistics

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#3709]
ID is using tag value suggests based on Taginfo. This is partially misleading.

Example:
The preset for man_made=mast.
The type field suggest values based on tower:type tag statistics.
Unfortunately, most values are not apllicable for man_made=mast features, but for man_made=tower only.
Besides of inconvienience this can led to using man_made=mast where man_made=tower should be used.
A special problem is suggestion the value power, indicating that man_made=mast can be used for power poles, where power=pole should be used instead.

In order to improve, we should use conditional tag statistics instead. For example the statistic of type:tower of all objects containing man_made=mast. We should ask the Taginfo project if such conditional statististics can be provided. All conditional statistics which iD needs will likely be useful for other Taginfo users too. Maybe Mapbox can also generate such statistics. We don't need a very current service. A monthly update is sufficient.

We should also have blacklist suppressing unwanted values, especially deprecated ones.
A whiltelist adding additional values can also be useful, especially if supporting some retagging rules.
For example adding a value power pole automatically retagging power=pole instead of using the man_made and tower:type keys.

**Comment by bhousel** [comment]
> We should ask the Taginfo project if such conditional statististics can be provided. All conditional statistics which iD needs will likely be useful for other Taginfo users too. 

taginfo's apidoc is here: http://taginfo.openstreetmap.org/taginfo/apidoc

I don't think these statistics are available from taginfo, for example, to say which `tower:type` values pair well with `man_made=mast`.

`/combinations` can tell us what keys typically appear alongside which other keys, but not necessarily what values make sense with those pairings.

You could ask on https://github.com/taginfo/taginfo, but I suspect that this feature might be too computationally expensive.  (cc @joto)

Anyway it wouldn't be a problem if OSM tags were better namespaced.  e.g.:
* `man_made=mast` + `man_made:mast:type=*`
* `man_made=tower` + `man_made:tower:type=*`
* `power=tower` + `power:tower:type=*`


> We should also have blacklist suppressing unwanted values, especially deprecated ones.
> A whiltelist adding additional values can also be useful, especially if supporting some retagging rules.
> For example adding a value power pole automatically retagging power=pole instead of using the man_made and tower:type keys.

I suspect that this would upset a lot of people.

Anyway, closing because this is something we can't do.  I'll reopen if @joto says I'm wrong.

**Comment by joto** [comment]
Taginfo does provide tag combinations with other tags, but only if there are "enough" of them. You can look at http://taginfo.openstreetmap.org/tags/oneway=yes#combinations for instance and you can see that the combination `oneway=yes` with `highway=residential` appears about 1.5 million times. At http://taginfo.openstreetmap.org/tags/man_made=mast#combinations you can see that the combination `man_made=mast` with `tower:type` appears about 20,000 times, but it doesn't tell you about specific values of `tower:type` in this combination. Taginfo can't track all combinations because that would need too many resources, so it tries to restrict itself to the most common ones.

The use of statistics for this kind of data is questionable anyways. It works well for very common tags, but there is so much noise in the system that statistics for uncommon tags are often misleading due to a few imports or other problems.
