### ISSUE TITLE
View history link

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#3761]
When editing a feature there is a link at the bottom to "View on opensteetmap.org" - how about adding a link to the history as well? Would save a click!

**Comment by bhousel** [comment]
Per https://github.com/openstreetmap/iD/issues/2273#issuecomment-233331887 ,  I kind of want to add some information about the history of a way to the "secret" <kbd>⌘I</kbd> object inspector.  If we put a link in here does that work for you?  I don't want it to be a permanent UI feature on the sidebar, but the inspector box is a good place for it.

**Comment by boothym** [comment]
![history](https://cloud.githubusercontent.com/assets/16965772/22039816/b0ac716e-dcf8-11e6-9b07-116c8cb03881.jpg)
I was thinking about something like this. Generally the use case is where you can quickly look at the tags between the last two versions, and maybe go back to when it was first created. Not sure you'd be able to do that in the secret menu.

**Comment by slhh** [comment]
The history view of openstreetmap.org isn't really user friendly.
The history view of JOSM is better, but we can't link JOSM.
Maybe we can link the following OSM history viewer, or even integrate it because it seems to be JavaScript:
https://github.com/PeWu/osm-history
Example: https://pewu.github.io/osm-history/#/way/37519344
This one looks very nice, at least for ways and nodes.
For tag history OSM deep history is very useful too, but it is already linked by above OSM history viewer.
Example: https://osmlab.github.io/osm-deep-history/#/way/48005102
