### ISSUE TITLE
Possibility to convert a line into a node

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#3789]
It would be nice to have a possibility to convert a line into a node preserving all tags.
I envision as 
1. dragging a node from a line with some modifier key pressed
2. merging all line nodes into one or deleting all but one line nodes.

**Comment by bhousel** [comment]
I think we could implement #3774 in a way that handles "merging all line nodes into one".

**Comment by slhh** [comment]
@bhousel #3774 is a totally different thing.
@yaugenka Doesn't #839 cover your usecases?

> merging all line nodes into one or deleting all but one line nodes.
Doing it silently would generate much gartbage, especially in case the remaining node is connected to a different way.

Deleting a way with valuable tags (e.g. not just a feature type), iD should generate some kind of warning anyway to avoid deleting valuable information accidently. This warning could offer a copy tags button. This way we can make the warning to appear as a userfriendly wizzard.

**Comment by yaugenka** [comment]
@slhh Yes, the copy-pasting feature as discussed in #839 would let achieve the same result but with extra steps.

Compare the case with copy-pasting:
1. copy tags from a line
2. create a node
3. paste the tags into the node
4. delete the line

to the suggested alternative: just drag a node from a line with some modifier pressed.

> merging all line nodes into one or deleting all but one line nodes.

Currently the line gets deleted silently and a node with not tags is create, so I agree, there should be at least some warning generated.

**Comment by yaugenka** [comment]
BTW it would also be nice to have a possibility to convert a node into a line with all tags copied. This one should be much simler via an extra "+" menu item (same as "continue line" for a line-ending node).

**Comment by bhousel** [comment]
iD mostly doesn't let users switch geometry because it usually doesn't make sense to do so.

You wouldn't want people to easily or accidentally create a single node `highway=residential` or linear `amenity=drinking_water`, etc.  Obviously advanced mappers can create stuff like this by editing the raw tags, but we try to guide users towards creating features that make sense.  This is why iD's preset system uses geometry as a primary criterion for matching an OSM entity to a preset.  We don't want new mappers to have to think about whether the features they draw make logical sense.

Additionally, I have said this before, but I don't see a point to preserving feature history in most cases.  It's nice to do, but aside from a few people who run statistical analysis tools, nobody cares about this.  It's totally fine to delete and redraw things.

I'm closing this because it's not clear to me _why_ anybody would want to convert a point to a line or a line to a point.  I'm willing to reopen if anyone can suggest a situation where they have actually needed this feature.

**Comment by yaugenka** [comment]
Expand place node into an area and collapse place area into locality node.

**Comment by pnorman** [comment]
Node to area isn't something this issue would address, as it's about lines to nodes. It's already possible to turn a node into an area, draw an area, select both, and merge.
