### ISSUE TITLE
Extra nodes added when moving a connected way

### ISSUE THREAD

**Issue by edpop** [openstreetmap/iD#3797]
1. http://preview.ideditor.com/master/#background=Bing&map=17.00/46.28179/-89.12487
2. Select this square https://www.openstreetmap.org/way/146394186 and try to move it ("M" + mousemove)
3. See square deformation and unnecessary nodes.

![bugscreen001](https://cloud.githubusercontent.com/assets/13479292/22318639/f41aee46-e3c7-11e6-9676-8d72d15d279d.png)
![bugscreen002](https://cloud.githubusercontent.com/assets/13479292/22318665/25cc464c-e3c8-11e6-9f44-0c3bf8024838.png)

**Comment by bhousel** [comment]
Why do you think this bug is "serious"?   It just looks like the move action trying to keep the two ways connected at a single point and preserving the shape of the non-moving way.  Because this mostly makes sense for linear ways, we can probably disable this behavior when moving a closed loop way.

**Comment by edpop** [comment]
Ok, I didn't notice this behaviour before.

**Comment by bhousel** [comment]
> Ok, I didn't notice this behavior before.

It's trying to do something like this.  The point where the moving way connects gets slid around on the non-moving way, so that the non-moving way shape doesn't change.  We can call this one "smart move":
![smart_move](https://cloud.githubusercontent.com/assets/38784/22331585/3d9c7374-e39a-11e6-8bc3-cc3e5852491e.gif)

I agree there is at least 1 extra unnecessary vertex getting added, probably 2.  There are always going to be some geometries where it ends up doing something kind of weird, like you found.

The alternative behavior is what happens when you select all the individual vertices and move them.  No attempt is made to preserve the shape of the non moving way.  We can call this one "dumb move":

![dumb_move](https://cloud.githubusercontent.com/assets/38784/22331746/129de8d2-e39b-11e6-9d77-55551782276d.gif)

**Comment by bhousel** [comment]
I fixed this:
0b6183e2c 2018-01-29 Remove any duplicate vertex created during `replaceMovedVertex`
9b200cf51 2018-01-28 Code cleanups, changes to `replaceMovedVertex` in `moveAction`
