### ISSUE TITLE
"School area" appear "school playground" in Korean

### ISSUE THREAD

**Issue by ryush00** [openstreetmap/iD#3802]
"학교 운동장" means "School playground". It should be translated to "학교".

![image](https://cloud.githubusercontent.com/assets/4997174/22362148/d587de44-e4a3-11e6-8454-601c540f101d.png)

**Comment by bhousel** [comment]
Hi, thanks for the report. Our translations are handled through [Transifex](https://www.transifex.com/ideditor/id-editor/dashboard/) and you can fix this yourself if you sign up for an account there. 

[Here is a link to the Korean language translations](https://www.transifex.com/ideditor/id-editor/language/ko/)

Worth mentioning too that `amenity=school` on an area is typically used to tag the property around the school, so that's why in English it says "School Grounds", which probably led to the confusion.

**Comment by ryush00** [comment]
Thank you. I fixed the translation. When the translation will appear on iD service?

**Comment by bhousel** [comment]
> When the translation will appear on iD service?

Next time we release iD, which will probably be any day now.

**Comment by manfredbrandl** [comment]
You can see the translation within a few Minutes on preview.ideditor.com/master.
