### ISSUE TITLE
Prevent untagged ways from uploading (saving)

### ISSUE THREAD

**Issue by cliffordsnow** [openstreetmap/iD#3806]
As I look at new users edits, one that jumps out as an easy fix is to not allow upload (saving) of untagged ways and nodes. I'm not sure of the case that can be made to allow untagged ways, but a new person would not understand it. 

iD does warn when attempting to upload untagged ways, but nothing stops the user from uploading the way. 

Please prevent users from uploading (saving) untagged points, lines and areas.

**Comment by bhousel** [comment]
One problem with this is that although the way might be untagged, it can still be connected to other things that are tagged, or it might contain vertices that are tagged somehow (as crosswalks or junctions with other things).  So if we skip uploading a way in this case, but still upload the "important" nodes along that way, it would be weird.

Also, I think it's unreasonable to expect new users to understand the intricacies of OSM highway tagging.. So if they just draw something and don't know whether it's a service road or a track and want to just leave it for someone else to classify, that should be fine.

Untagged geometry isn't a problem for anybody.  Our message to new users should be that OSM is fun and easy and safe, and they don't need to worry about making mistakes because anything can be fixed easily, and no map is perfect anyway.
