### ISSUE TITLE
iD create one-member relation for node-POI

### ISSUE THREAD

**Issue by stephankn** [openstreetmap/iD#3812]
I observe multiple instances of this weird tagging. All have in common that a new POI was added, typically only a node. 
Weird is that this single node is then the only member of an untagged relation.

Either iD accidentally creates this or the UI makes it easy for the user to do such unintended mistakes in editing.

Version observed: iD 1.9.7
Example: https://www.openstreetmap.org/changeset/42664446

**Comment by tyrasd** [comment]
I believe this must happened by the user clicking on the large *"+"* button in the *"all relations"* section, and then selecting *"new relation"* without then selecting one of the presets (e.g. aborting the process by selecting another object).

There are two potential improvements:
* [ ] there should be a warning in the "save dialog" when creating/uploading an untagged relatin, similar to what's already shown for untagged ways/nodes.
* [ ] I think that the relation should not be created until one of the presets is selected after clicking on *"new relation"* (users can still select the generic "relation" preset if they really wants to create a untagged relation)

**Comment by Paul012** [comment]
Perhaps the _All relations_ section shouldn't be expanded by default also. Having the large + button visible at the bottom of the column does have the potential to confuse new editors.

**Comment by quincylvania** [comment]
Rather than not creating the relation until after selecting a feature type (which would be really hard), I just made iD delete newly-created relations with no tags, memberships, or roles upon deselecting them. Basically this prevents empty relations from persisting if you click New Relation and then click away without doing anything.

> Perhaps the All relations section shouldn't be expanded by default also. Having the large + button visible at the bottom of the column does have the potential to confuse new editors.

This sound fine but it doesn't seem critical now that we have the validation warning and the deletion behavior. If anyone really thinks we should do it then feel free to open another issue!

**Comment by quincylvania** [comment]
I also added a tooltip to hopefully make this button less mysterious 🦹‍♂️

<img width="389" alt="Screen Shot 2019-04-07 at 2 03 01 PM" src="https://user-images.githubusercontent.com/2046746/55689842-87a39580-593e-11e9-8e22-75fd01fd0bdb.png">
