### ISSUE TITLE
Adjust rendering of node/vertex with direction

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3815]
Followup from #3115..

Some node/vertex features in OSM can have a direction.  stop signs, traffic signals, billboards.
The normal method to tag this is `direction=forward` or `direction=backward` (although, this being OSM, there are of course [alternative bizarro tag schemes](https://wiki.openstreetmap.org/wiki/Key:direction)).

Anyway, what we do with directional vertices currently is - the same as any other interestingly tagged vertex, just show it as a circle with a dot (or in some cases a maki icon):

<img width="907" alt="screenshot 2017-02-03 10 35 28" src="https://cloud.githubusercontent.com/assets/38784/22597182/8f59435a-e9fc-11e6-9da6-8f1abbf10499.png">

But maybe we can do something else to indicate that there is a direction:

<img width="137" alt="screenshot 2017-02-03 10 35 28 copy" src="https://cloud.githubusercontent.com/assets/38784/22597342/36ef7b02-e9fd-11e6-949a-18a5992773f8.png">  <img width="137" alt="screenshot 2017-02-03 10 53 21" src="https://cloud.githubusercontent.com/assets/38784/22597779/083e54e8-e9ff-11e6-8b79-800402e46453.png">

**Comment by slhh** [comment]
@bhousel What you call the bizarro tag schemes seems to be current usage of key direction according to the wiki. I think for good reason because this enables usage on any node. Forward and backward values don't have a useful meaning except for the special case of a vertex of a single way.

In case of traffic signals or traffic signs we have to differentiate two types of direction, the facing orientation the direction of the affected traffic.

Facing orientation is described using key direction in both cases using the 'bizarro' values..
Direction of traffic affected by traffic signals is described by traffic_signals:direction=forward or traffic_signals:direction=backward (https://wiki.openstreetmap.org/wiki/Key:traffic_signals:direction).
Direction of traffic affected by traffic signs is described using traffic_sign:forward=* or traffic_sign:backward=* (https://wiki.openstreetmap.org/wiki/Key:traffic_sign#On_nodes).

Therefore, direction=forward and direction=backward seem to be essentially outdated tags.

Facing orientation and direction of traffic seem to be more or less inverse directions in most cases, therefore rendering an arrow seems to be potentially confusing.

Directional tags have always to be combined with tagging a feature on the node, we might want to render the feature which could interfere with a direction indicator.

**Comment by Codain** [comment]
Hi,

As a starting point I would consider to customize the node to, for instance, display a little traffic light, stop sign or give way sign in the node.

Then, speaking of a "direction" indicator the first proposition (the black and thin arrow) can be confused with a one way arrow. The second drawing might be ok in addition with previous point.

A third option to have a lighter symbology would be to replace the node and the triangle by a triangle, centerd on the node, containing the traffic light/sign and oriented to the direction tag.

**Comment by bhousel** [comment]
> As a starting point I would consider to customize the node to, for instance, display a little traffic light, stop sign or give way sign in the node.

Yes, I plan to do that separately of this issue.  There are a handful of traffic control icons that we're really missing from maki.  I'll open a new issue for it.

**Comment by bhousel** [comment]
done in #4602
