### ISSUE TITLE
Uploaded GPS trace is not snown

### ISSUE THREAD

**Issue by andrasfuchs** [openstreetmap/iD#3820]
After I uploaded the GPS trace I made today using OsmAnd 2.5.4, and I tried to edit it with iD 2.1.0 in Firefox 51, but it was not shown on the map.

To reproduce:
1, Upload a GPS Trace
2, Go to http://www.openstreetmap.org/traces
3, Click on the trace's edit button
4, The trace is not shown on the map

Here mine: http://www.openstreetmap.org/edit?gpx=2349339#map=17/9.51274/100.04808

![image](https://cloud.githubusercontent.com/assets/910321/22626347/c4e25fa6-ebdd-11e6-9b28-d32d34e36b90.png)

I have this JavaScript error on the site:
TypeError: e.name is undefined id-7588ac26c2004f0e481c4de2afc866cab9102b4aa46228e67b5b6898f2b2b5c6.js:4:18079

**Comment by boothym** [comment]
I can confirm that if I go to http://www.openstreetmap.org/traces/mine and click on edit, I do not get shown the gpx - however load a local gpx. Tested Firefox and Chrome, Win10.

**Comment by bhousel** [comment]
Thanks for the report.. Traces uploaded to openstreetmap.org might not show immediately.  I'll check what's going on with the `e.name` error, that is definitely a bug.

**Comment by boothym** [comment]
Sorry should've said - none of my traces were uploaded recently. It fails to work with one uploaded in January or months ago.

**Comment by tkansgar** [comment]
Hi,

> Sorry should've said - none of my traces were uploaded recently. It fails to work with one uploaded in January or months ago.
That's the same in my case (the closed duplicate issue #3819 )

tkansgar

**Comment by speedbiker** [comment]
Same here. I have the same problem, running Max OSX with Google Chrome.
I could upload the GPX-file, but it disappears on the screen.

**Comment by bhousel** [comment]
Thanks, I've also heard that gpx traces from the HOT task manager are not showing up.  I'll try to get this fixed quickly. 👍

**Comment by Nick-Tallguy** [comment]
Hi - same problem on TM - a quick workround that has worked for me (so far)


1. Load task in iD

2. return to Task on TM, go back to 'edit with' and select JOSM

3. You will get an error message about JOSM remote control, but it will give you access to a section of the JOSM menu

4. From the section that reads "Tip: Download the following .gpx file and load it in JOSM in order to see the current task boundary" right click on ".gpx file" and select "Save link as" - I put mine in my downloads folder.

4. Back to the iD tab in your browser, and have file manager open as well - drag & drop the downloaded .gpx file onto the window of ID -- then wait...

5. If all goes well you now have the square on your iD screen. It took a while to load on my setup & a message about waiting or closing appeared - but it has loaded each time I've tried.


I'll try to put together a quick howto with images on LearnOSM and make it downloadable. Feedback as to whether this works for everyone would be appreciated in case I have to make amendments.

I'm not sure if this would work with gpx traces from OSM - download it, then load it by dragging & dropping onto your screen.

**Comment by bhousel** [comment]
> I'll try to put together a quick howto with images on LearnOSM and make it downloadable. Feedback as to whether this works for everyone would be appreciated in case I have to make amendments.

Don't you think a nice thing to do would be give me more than a day to fix the bug before changing LearnOSM?

**Comment by Nick-Tallguy** [comment]
Sorry @bhousel 
My initial thought was that I was taking the pressure off for you and those with impending mapathons.

I'll happily wait.

Regards

**Comment by tkansgar** [comment]
Hi bhousel,

could you say, when the fixed version will be available at www.openstreetmap.org for map editing? Currently it doesn't seem to be.

tkansgar

**Comment by bhousel** [comment]
> could you say, when the fixed version will be available at www.openstreetmap.org for map editing? Currently it doesn't seem to be.

I'm preparing the release now, so probably within a day or so.

**Comment by bhousel** [comment]
I just checked and the fix is now live on openstreetmap.org 👍  
Thanks @tyrasd and @tomhughes !

**Comment by tkansgar** [comment]
Hi all,

yes, the pink line is back again. Many thanks to all from Germany too!

tkansgar

**Comment by tkansgar** [comment]
Hi bhousel,

do you know already? This issue unfortunately is back again. The pink line representing my track is missing. Could you see, what is wrong again?

Best regards
tkansgar

**Comment by tkansgar** [comment]
Hi all,

it works again. Many thanks to those, who solved it.

tkansgar
