### ISSUE TITLE
Review traffic signals preset?

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#3838]
When selecting a node and using the traffic signals preset we have a node with `highway=traffic_signals` + `traffic_signals=signal`

I don't see the value `signal` in https://wiki.openstreetmap.org/wiki/Key:traffic_signals nor, at least for me, it makes sense to have a traffic signal of the `signal` type.

Maybe this preset should be reviewed?

**Comment by bhousel** [comment]
Yes, [see on taginfo](https://taginfo.openstreetmap.org/keys/traffic_signals#values) the value is almost always `signal` for a normal traffic light.  Occasionally people will put something in there like `blinker` or  `emergency`, which are useful things to tag also.

<img width="371" alt="screenshot 2017-02-14 10 47 54" src="https://cloud.githubusercontent.com/assets/38784/22936310/1cd862b6-f2a3-11e6-91b8-0acb66e27276.png">

**Comment by naoliv** [comment]
At least from the wiki I have the impression that `traffic_signals` was meant to be used only to specify a different type of traffic signal (ie, by default every traffic signal is a normal traffic signal, unless if specified by `traffic_signals`).
I also have the impression that `signal` was maybe introduced by the iD preset.

If my view is not totally wrong, maybe iD could just simply create a `highway=traffic_signals` without offering a type to select?

**Comment by bhousel** [comment]
> I also have the impression that signal was maybe introduced by the iD preset.

No, `signal` was already by far most frequent value when I added this field to iD in 12409e4 about a year and a half ago.  I really don't invent tags, I prefer to use the ones that are already in widespread use.  

I decided to set the field to default to `signal` because otherwise people would see that field and probably open a ticket to ask why they need to pick the signal type every time they map a traffic signal.  (Really they don't strictly _need_ to set a value, but it is difficult to explain conventions like this to OSM newcomers, and easy to just default things to fill in the 95% case for them).

**Comment by manfredbrandl** [comment]
Maybe we could change "Type" to "Type if not (standard) signal" and leave the value unset  by default?

**Comment by tyrasd** [comment]
> No, signal was already by far most frequent value […] about a year and a half ago.

Yes:

[![taghistory 4](https://cloud.githubusercontent.com/assets/1927298/22969351/8b0f72c6-f36e-11e6-8e30-7269b125f83a.png)](http://taghistory.raifer.tech/)

**Comment by bhousel** [comment]
Wow!  Honestly didn't think so many people used iD.  50,000 new traffic signals mapped is a good thing :)

Let's leave it alone, since the tag doesn't bother anyone, and changing the caption on the type field would only confuse.  We should try to steer OSM away from unspecified defaults is possible.

**Comment by naoliv** [comment]
Of course this is not related with iD, but could somebody give a good explanation for `traffic_signals=signal` in the wiki then, please?

I would use `a normal traffic signal` but I don't think that this description really explains the value.
