### ISSUE TITLE
Mark roads and waterways when they are also part of a region limit

### ISSUE THREAD

**Issue by afmenez** [openstreetmap/iD#3841]
It is very common for city/state/coutry limits to coincide with waterways or roads, but it is impossible to see when editing unless the way is selected and you scroll the sidebar way down to see if it as part of a limit relation.  This should be visible without selecting.

**Comment by bhousel** [comment]
I agree, but I'm going to close this because #2225 already has some discussion about how iD doesn't handle coincident ways very well.

It's kind of a difficult UI problem.  If you think about it, it's also easy to get confused by drawing lines on top of lines in any drawing application, like Illustrator or Sketch. 

We could maybe adjust how hover and select works so that for coincident ways/overlapping polygons you see multiple things in the sidebar (rather than a single hovered thing), and on click you get all those things selected. 

It needs to be smart because it would be really annoying if you click on a road and accidentally get a selection full of "Road", "Other Road", "Big Multipolygon you can't see", "Region", "City", "State", "Country", etc.

**Comment by afmenez** [comment]
What if you could define your editing priority?  If I am drawing limits, I
see them, otherwise I see roads/rivers by default.  This may work for other
coincident features too...

**Comment by bhousel** [comment]
> What if you could define your editing priority?  If I am drawing limits, I
> see them, otherwise I see roads/rivers by default.  This may work for other
> coincident features too...

You can hide things in the Map Data panel by unchecking certain feature types.  This is what I do when the boundaries or big landuse multipolygons get in my way:

<img width="220" alt="screenshot 2017-02-15 11 50 13" src="https://cloud.githubusercontent.com/assets/38784/22984938/f653dbb6-f374-11e6-8e2d-76070bbeddf3.png">

**Comment by afmenez** [comment]
Didn't knew that interface.  Thanks.
