### ISSUE TITLE
Add upload warning for building or other feature connected to road/lake etc

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#3859]
I've seen this a lot at humanitarian mapathons, because of the snapping sometimes buildings get attached to other features they shouldn't be attached to, like roads, lakes, and so on. This could sometimes be ok (like a tunnel or something) but maybe a warning would be good, to at least look at them and disconnect them.

**Comment by aawiseman** [comment]
This is related to point 3 in #3130 (but I explained it more here.) It's not something caught by the JOSM validation tool either so it makes it hard to find aside from just looking around.

**Comment by pnorman** [comment]
Are the users
- not aware of what's happening;
- not aware it's normally wrong;
- or, not aware of how to fix it?

**Comment by bhousel** [comment]
So this is the kind of validation that I'm hesitant to add to iD because it 1. Isn't always wrong, 2. doesn't really damage the map (at least not like connectivity errors or large feature edits that dirty a lot of tiles).  I'm ok with users adding things that are a little bit wrong.

I'm starting to think that the most important thing I can do to improve new mappers edit quality is an overhaul of the walkthrough.  I have a bunch of tickets already tagged [walkthrough-help](https://github.com/openstreetmap/iD/issues?q=is%3Aopen+is%3Aissue+label%3Awalkthrough-help), but I'd really like to extend the walkthrough significantly and refresh the area where it occurs, and give a bit more guidance on basic OSM etiquette.

**Comment by geowOSM** [comment]
>  Are the users
not aware of what's happening;
not aware it's normally wrong;
or, not aware of how to fix it?

Most mappers might be aware that unintentional snapping feels "wrong" somehow. Essentially they are unable to fix it and IMHO more important - they are not aware of how to prevent it, by alt + mouse click. 

Maybe some basic shortcuts could be added to the documentation and/or a link to http://wiki.openstreetmap.org/wiki/ID/Shortcuts

**Comment by manfredbrandl** [comment]
Please do not warn when path are connected to entrances of buildings, see #3906 .

**Comment by aawiseman** [comment]
I think changing the walkthrough and documentation is a good idea, I wasn't aware of the alt- thing and I've been using iD for a long time.

**Comment by bhousel** [comment]
Closing here and I'll work this week on walkthrough improvements.
