### ISSUE TITLE
(Multi)polygon fixing effort

### ISSUE THREAD

**Issue by joto** [openstreetmap/iD#3908]
There is a major effort going on to fix broken (multi)polygons in OSM and also to finally get rid of *old-style* multipolygon relations. This will hopefully lead to simpler and more efficient software. There is no immediate need for you to change anything in iD, but I would expect there to be opportunities to simplify your code and generally make life easier for you once this effort is successful.

I wanted to make you aware of the effort and get you involved in the discussions. We'd also appreciate it if you can support this effort in any way. Find all the details at http://area.jochentopf.com/. We are coordinating with other software project through our issue osmlab/fixing-polygons-in-osm#23.

**Comment by bhousel** [comment]
This is great news!  I really like the [stats page](http://area.jochentopf.com/stats/).

iD supports either old or new style multipolygons for rendering, and iD creates only the new style multipolygons when merging areas or ways, so I agree there probably isn't anything for us to do, and I'll close this here.

It looks like new-style multipolygons would get a slight performance bump in iD, because [`osmIsSimpleMultipolygonOuterMember`](https://github.com/openstreetmap/iD/blob/1ecb456a3c517fcbbcbc3ceb49e975ab98936e06/modules/osm/multipolygon.js#L7) would exit early, avoiding the ring checking and tag merging code.

**Comment by bhousel** [comment]
Update on this:  I decided to render the old-style multipolygons slightly differently. Hopefully it won't bother anyone, and there will be fewer of these over time.

If you see shape like this with little holes along the edge, it's an old multipolygon and you should fix it if you know how.  😁 

<img width="1111" alt="screenshot 2017-04-20 23 28 14" src="https://cloud.githubusercontent.com/assets/38784/25261678/263eb15a-2621-11e7-9177-f170e4f93bff.png">
