### ISSUE TITLE
Search prioritises exact match over relevance

### ISSUE THREAD

**Issue by arschficken** [openstreetmap/iD#3930]
Run a search for "osan korea" (no quotes). The only result is for a bus stop named "Osan", which happens to be the only exact match. iD helpfully zooms in on this bus stop. Unfortunately, it is on the other side of the country to the city of Osan-si and its related Osan Air Base.

The only indication that this might not be the right Osan is the "More results" button, which when clicked, does indeed show the more expected results.

Not sure if this is the right place to file search algorithm bugs (are they in iD or the dataset)?

**Comment by bhousel** [comment]
I did the search and I also get the bus stop.  We just get these results from `https://nominatim.openstreetmap.org/search`, so there could be an issue with Nominatim, or with the data itself.

There is something weird going on though, because I clicked on that bus stop and iD didn't take me there, instead it showed me the place I was already looking at, but with Osan's data in the sidebar.  It does look like a bug..

**Comment by bhousel** [comment]
Fixed the bug in 1486c3d - it was not related to the Nominatim lookup.

Closing here, since the results are outside our control.
FWIW I do get that same bus stop as a result when doing the search on https://nominatim.openstreetmap.org/

**Comment by arschficken** [comment]
Thanks, @bhousel. I take it your patch is for the issue you discovered; should I file the original bug against Nominatim?

**Comment by bhousel** [comment]
> should I file the original bug against Nominatim?

Yes, but when reporting the issue use https://nominatim.openstreetmap.org/ to do the search, not iD.  
They both return the same results, but better to leave iD out of it.

cc @lonvia

**Comment by arschficken** [comment]
Thanks, created as [Nominatim bug 689](https://github.com/openstreetmap/Nominatim/issues/689).
