### ISSUE TITLE
Walkthrough's zoom exercise non-obvious to complete without scrollwheel

### ISSUE THREAD

**Issue by mikini** [openstreetmap/iD#4014]
I am testing the walkthrough on http://preview.ideditor.com/master at my workstation using my trusty trackball which hasn't got scrollwheel emulation.

Getting beyond the zoom exercise proved difficult as the visible zoom buttons in the UI are greyed out. This made me being stuck, not able to comply until trying the keyboard shortcuts (-+) which got me further. A complete beginner might never come that far.

Maybe the keyboard shortcut should be mentioned in the text, or a timeout bring the guide to the next step if it takes too long.

**Comment by bhousel** [comment]
Good point, thanks!   I did not realize this but the curtain also covers up the +/- buttons, so I'll fix this too.

**Comment by mikini** [comment]
No problem. Yes, the curtain was what I meant by "greyed out". That might make sense to put focus on the map area we are working on, but I guess the buttons could be active/in front of the curtain anyway.

**Comment by bhousel** [comment]
> No problem. Yes, the curtain was what I meant by "greyed out". That might make sense to put focus on the map area we are working on, but I guess the buttons could be active/in front of the curtain anyway.

Yeah this makes some sense.  Previously the curtain covered up the buttons because the walkthrough was much more strict about what the user could do - so clicking a button could really get the user stuck.  (e.g. you could zoom in, and then the section asking you to search for "Spring Street" would just not work).

The walkthrough is a lot more open ended now, and it takes care to transition the user to known view states before asking them to perform a task, so I'm not worried anymore about accidental navigation.  In fact I'd prefer for users to explore the user interface in the walkthrough, rather than having them learn this stuff during real editing.
