### ISSUE TITLE
Help should be rewritten and split into smaller chunks

### ISSUE THREAD

**Issue by mikini** [openstreetmap/iD#4018]
The help texts in the application all need to be rewritten to relate to the changed UI with the new right click concept for editing selected features.

Also, I noticed some discrepancies between terminology used in the current help texts and the walkthrough. Here is the most obvious;

- "inspector" vs "feature editor"
- "tool menu" vs "edit menu"
- "edit operations" vs "(merge/move etc.) tool"

Would you accept a PR with patch to data/core.yaml? It looks like the authoritative place to edit by skimming the project structure and build.js.

**Comment by bhousel** [comment]
Yes, also mentioned on #4001.. I'd definitely welcome a PR!  I'd like to wait until after we release 2.2 to merge it, so that we are not changing the translations so soon before a release, but we could update this content later in May.

**Comment by bhousel** [comment]
copying over my comment from #4089 :

The core.yaml file is the correct place to update the help text, however the real problem is that giant blocks of help text are not very friendly for translators. If we just change a few words, I think they need to retranslate the whole block of text on Transifex.

So the right solution is to break up all this text into smaller chunks while we refresh the text with new content. However doing so we might lose all the existing translations (which we would anyway even if we just change a few words here and there), so there's no great solution for fixing this other than just doing it at a time when we won't be releasing iD for a little while and let the translators have some weeks to redo the translations in smaller chunks.

**Comment by bhousel** [comment]
wip at #4453

**Comment by bhousel** [comment]
wip moved to #4468

**Comment by mikini** [comment]
Hi @manfredbrandl, I've taken a note of your work and will try to stamp up some time soon for a review. Thanks for looking into it.
