### ISSUE TITLE
Weekly update of translations in released iD

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4019]
It would be helpfull if it is possible to separately update the code and the translations. Maybe we could have another preview-installation for release. There result of translations could be tested and the released iD could be updated ever week or so.

**Comment by bhousel** [comment]
I do try to release iD roughly once or twice a month, but this current 2.2 release (with the revised walkthrough and right-click menu) has an unusual amount of translation work associated with it. 

Part of the reason we can't easily separate them is because the translations are pinned to the `master` branch of iD, not the `release` branch.  This is necessary so that new features can get translated before they are released. 

Another reason is that, ideally, the translations get some review before a release.  (if we just automatically pulled whatever was available onto the live openstreetmap.org site, people might vandalize the translations)

Some things that will help:
- http://preview.ideditor.com/master will continue to auto-update with latest code and translations
- If anyone really does need a new version of iD released (because of updates to translations or imagery), just ask on IRC or Slack and I will probably do it, even if it's out of the normal schedule.
- return to more frequent releases
