### ISSUE TITLE
v2.2.0 - Cannot create relationship with right clicking

### ISSUE THREAD

**Issue by EwenH** [openstreetmap/iD#4037]
I am adding farmland and want to create relations with scrub areas, Normally I would 

1. click the small scrub area in the farmland 
2. shift-click the farmland,
3. right click and click the plus sign (from memory)

An example I have left in-situ is at https://www.openstreetmap.org/edit#map=19/-34.32432/141.39803

Is there a way to create a relationship like this simply or am I missing something?

**Comment by bhousel** [comment]
What you are doing sounds right... There should be a message explaining why the merge operation is disabled.  For example, see below, the merge might just prevented because the relation hasn't been fully downloaded?

<img width="377" alt="screenshot 2017-05-11 07 54 47" src="https://cloud.githubusercontent.com/assets/38784/25947860/3389891c-361f-11e7-9a38-5f6b7792f67e.png">

**Comment by EwenH** [comment]
Thanks @bhousel - The 'not fully loaded' a common issue I have faced previously with large "back" paddocks of 50sqKM+. I have tried this again and I think it might be that the laptop I am using is a bit flakey and maybe the ui is a bit less giving. It now appears to be working as expected. Thanks again and closed.
