### ISSUE TITLE
Re-selecting line tool removes current line that is being drawn

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#4042]
Not clear if this is intended behaviour, I would suggest doing nothing or completing the current line drawing and re-entering line drawing mode.

See https://help.openstreetmap.org/questions/56174/can-not-add-line-with-id-editor

**Comment by bhousel** [comment]
Yes, I agree we shouldn't remove the user's line.. That's a recent regression caused by [these lines of code](https://github.com/openstreetmap/iD/blob/974db187742f1d6ec5af8ed313654a6cd6f10063/modules/behavior/draw_way.js#L128-L136).  The code is actually useful because it lets us support undo while the user draws (#3530) at the expense of throwing away all the user's work whenever something unexpected happens.

I think I can find a way to handle leaving and reentering the same mode cleanly.
