### ISSUE TITLE
Attribution: Change problem, color

### ISSUE THREAD

**Issue by AllroadsNL** [openstreetmap/iD#4047]
Attribution change;

[link tweak](https://github.com/osmlab/editor-layer-index/commit/cff7c6f5ef98357169d616777f7ecd8b568c9734)

How much time does it take to the new attribution setting.
After 3 days nothing changed on the screen.

![attributtion](https://cloud.githubusercontent.com/assets/8817345/26098704/e0bec810-3a28-11e7-9b19-eacb8e54f448.PNG)
![attributtion2](https://cloud.githubusercontent.com/assets/8817345/26098709/e25567d8-3a28-11e7-8ce4-94195abec2b4.PNG)

**Comment by bhousel** [comment]
I spent some time improving the visibility of the attribution today.  I tried a bunch of tricks like CSS `text-shadow` and `mix-blend-mode` to get the text to stand out from the background better, but nothing really worked great.  This is because the attribution text is pretty small, and we want to keep it that way.  

After all that, I ended up just brightening the color a little bit. You can try it out on http://preview.ideditor.com/master/ - let me know what you think.  There will always be some background colors that make it almost impossible to read the text, but hopefully it is more visible now on the kinds of colors that we typically see in background imagery.

I also added icons for the layers that support them, and refreshed a few of the sources that have new logos.

**Comment by althio** [comment]
Maybe you can move the content of this block `id="attrib"`(?) in the block `id="footer"` or use a similar style with a dark transparent background?

**Comment by bhousel** [comment]
> Maybe you can move the content of this block id="attrib"(?) in the block id="footer" or use a similar style with a dark transparent background?

I'm pretty happy with it as is.  I don't want the text to stand out too much, and I don't want it to take up the entire row, stealing the mouse events and reducing the amount of screen space where users can edit.
