### ISSUE TITLE
iD should not suggest re-directed (incorrect) tags from Wiki

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/iD#4051]
Hi,

I just noticed a potentially unwanted behavior from iD. 

Look at the image below. As you can see, iD suggests a false 

**tourism=tourism-attraction**

as a second option after the correct

**tourism=attraction**

tag.

The problem with this behaviour is that people may start to use such a false, re-directed tag, thinking it is more appropriate than the correct one. As we all know, sometimes the correct keys in OSM have a history, and may not always feel "right" to newbie users. Before you know it, there may be hundreds of uses of such an incorrect tag. In fact, I just fixed about 60 uses world-wide for this tag. Not yet a real problem, but it would be better if iD did not suggest re-directed tags.

Digging into this a bit deeper, the link of the TagInfo page of the incorrect tag is:

https://taginfo.openstreetmap.org/tags/tourism=tourism-attraction#wiki

This will point you to the correct:

https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dattraction

which is OK. 

_**However**_, it does this by an automatic re-direction, the link of which is visible on the Wiki page if you access the tourism=attraction page through the TagInfo link. The re-direct page is in fact this one:

https://wiki.openstreetmap.org/w/index.php?title=Tag:tourism%3Dtourism-attraction&redirect=no

as accessed from the auto-inserted link on the tourism=attraction when it is accessed from TagInfo.

![id_redirected_tag](https://cloud.githubusercontent.com/assets/7635726/26157088/8c5b1a1c-3b18-11e7-8c68-5a204b4ad732.jpg)

**Comment by bhousel** [comment]
Yes this is expected.. iD suggests whatever values that the taginfo service returns.  When there are no more instances of `tourism-attraction` in OSM, then it won't be available in the dropdown anymore.  This is a great incentive to clean up old tags, so thank you for helping with this!

We can't follow the wikipedia redirects to try to guess at whether a tag is deprecated or not, because wiki redirects are used for all kinds of things.  For example, [`internet_access:fee`](https://wiki.openstreetmap.org/w/index.php?title=Key:internet_access:fee) redirects to the page for [`internet_access`](https://wiki.openstreetmap.org/wiki/Key:internet_access) - not because `internet_access:fee` is deprecated, but just because it is documented sufficiently on the other page.

**Comment by mboeringa** [comment]
> Yes this is expected.. iD suggests whatever values that the taginfo service returns. When there are no more instances of tourism-attraction in OSM, then it won't be available in the dropdown anymore. This is a great incentive to clean up old tags, so thank you for helping with this!

To me, this is actually a suggestion to submit an issue on the TagInfo issue tracker... The risk is far to high newbie users will start using the deprecated or re-directed key. It will be near impossible to keep false tags at 0 occurence and not see the tag pop-up in iD. This will also put another burden on already stretched experienced OSM editors doing clean-up work.

Much better to not suggest these at all.
