### ISSUE TITLE
Add BIC field to bank preset.

### ISSUE THREAD

**Issue by hannni** [openstreetmap/iD#4057]
The [openstreetmap wiki article for `amenity=bank`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbank) describes a `bic=` field for the [BIC](https://en.wikipedia.org/wiki/ISO_9362), which uniquely identifies a bank (branch). It would be nice to also have this field in the preset for `amenity=bank`.

**Comment by bhousel** [comment]
This doesn't really seem like something that a casual mapper would be able to contribute.  I'm inclined to say it doesn't really belong, but would like to hear more opinions from others.

**Comment by hannni** [comment]
Maybe this is a bit country specific how easy it is for the casual mapper. Here in the EU and especially in Germany wire transfer and direct debit is a pretty common way of payment. For this reason the BIC stands basically everywhere: your bank-card, the website and I suppose (I haven't checked though) it is probably also often written close to the opening dates.

**Comment by tyrasd** [comment]
Well, what's pretty common here in the EU is the 8 digit [ISO 9362 "BIC" code](https://en.wikipedia.org/wiki/ISO_9362), which represents the whole bank institute. In order to identify an individual bank branch office (in OSM an `amenity=bank` feature), you need the full 11 digit BIC code (which additionally includes a 3 digits *branch code*) though, which is somewhat hard to find out and also a rather rare thing to need if you're not in the financial business, I guess. (I don't even know the 11 digit code of my own bank account. :sweat_smile:)

The more useful 8 digit BIC code, which is related to the whole bank institute should probably be better mapped indirectly by adding a link to the corresponding operator's wikidata object ([`operator:wikidata`](https://wiki.openstreetmap.org/wiki/Proposed_features/Wikidata#operator:wikidata.3D.2A)) which then would contain the respective [BIC code](https://www.wikidata.org/wiki/Property:P2627) (see this example: [Q66048](https://www.wikidata.org/wiki/Q66048)).

**Comment by hannni** [comment]
I think branch does not refer to a certain branch building of a bank company, but a branch company. For instance most of the credit union banks in Germany start out with GENODE (see [this list](https://de.wikipedia.org/wiki/Liste_der_Genossenschaftsbanken_in_Deutschland)). So the first 8 digits might actually be the same: For instance GENODEF1S04 is Sparda-Bank München eG while GENODEF1JEV is the Volksbank Jever.

The problem I see with Wikidata is that it might not contain every small bank. In the list I posted earlier, there are a lot of small banks that do have a BIC, but no wikipedia entry (and no wikidata entry?)

**Comment by tyrasd** [comment]
Ok, thanks for the correction. I think I get it now (was a bit confused after seeing a few banks that gave individual BICs to each of their offices).

Still, I personally don't see the point of adding information in a tag of an osm object that isn't about the particular object itself, but a property of its the operator. That's a bit like for example adding the website mcdonalds.* to all of their restaurants. But apparently, some people seem do exactly that: https://taginfo.openstreetmap.org/tags/?key=website&value=http%3A%2F%2Fwww.mcdonalds.com%2F#overview

> no wikidata entry

Well, get an account and create the missing entries (there's no wikipedia page required to create a new wikidata entry). :)

**Comment by bhousel** [comment]
Let's not add a `bic` field for now.   This is kind of like the recent issue with the biology taxonomy fields:
see https://github.com/openstreetmap/iD/pull/3600#issuecomment-265831513

>We haven't said so before, but I believe that every field in iD should be something that an untrained beginner mapper with local knowledge can understand and contribute to OSM. I think most of our fields meet that standard.

I think it's fine if people who know about BIC or SWIFT codes want to add this data, but they can use the raw tag editor to do it.
