### ISSUE TITLE
All Waterareas have same "i"-Link

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4064]
Lake, Pond, Reservoir all show the info for "natural=water":
![image](https://cloud.githubusercontent.com/assets/5360273/26349784/40c2819c-3fb1-11e7-86be-28177bc057a9.png)

**Comment by bhousel** [comment]
Yes, this is because they all redirect to https://wiki.openstreetmap.org/wiki/Key:water
If they had their own wiki pages, they could all have their own descriptions.

**Comment by manfredbrandl** [comment]
The link https://wiki.openstreetmap.org/wiki/Key:water shows good information.
Now the wiki link points to https://wiki.openstreetmap.org/wiki/tag:natura=water which is not so good.
Could the link get changed? I can change the wiki if neccesary.

**Comment by bhousel** [comment]
Oh yeah I see what you mean.. They all show `natural=water` because if they showed the _other_ key (e.g. `water=lake`) we would just end up with a "This documentation page has been redirected" message.

Ideally all of the types of `water=*` listed on the https://wiki.openstreetmap.org/wiki/Key:water page should have their own separate wiki pages.  Then we can show a good description and image for each one.

**Comment by bhousel** [comment]
#5647 will solve this
