### ISSUE TITLE
Context menus disappeared

### ISSUE THREAD

**Issue by sylvain-m** [openstreetmap/iD#4065]
Sorry if this is not an issue, but for me the contextual menus no longer appear when clicking objects.
For example, I can't find "continue the line", "make this object circular", "merge objects", ...
This, both in FireFox and in Chrome.
Is this linked to an evolution of ID, and if so, where can these functions be found?
Thank you.

**Comment by althio** [comment]
Contextual menu appears now with `right-click` since last deployment, after https://github.com/openstreetmap/iD/issues/3671 https://github.com/openstreetmap/iD/pull/3753 and announced with last version:
https://lists.openstreetmap.org/pipermail/talk/2017-May/077999.html
https://github.com/openstreetmap/iD/blob/master/CHANGELOG.md#220
> 👉 A new right-click editing menu replaces the old radial menu.
The new editing menu gives iD room to grow and won't get in the way of your editing.
Remember: Right-click on map features to use the new menu.

It is explained in the new and more extensive walk-through.

It is a relatively big change interface but hopefully people will switch.

Issue duplicate of https://github.com/openstreetmap/iD/issues/4041

**Comment by sylvain-m** [comment]
Sorry for the duplication !
Thanks a lot : It looks great and actually even more scalable!
