### ISSUE TITLE
Add preset for an elevator

### ISSUE THREAD

**Issue by Manu1400** [openstreetmap/iD#4068]
Specification : https://wiki.openstreetmap.org/wiki/Tag:highway%3Delevator

Now, a node with highway=elevator in ID editor is display as an highway.

Important field for an elevator : 
- level=*

Can be important for an elevator : 
- maxweight=*
- ref=*
- operator=*
- wheelchair=yes/no

**Comment by bhousel** [comment]
I added this and made a simple icon for it.  

Also I made it a `vertex` geometry type because presumably you'd want to connect the elevator node to a footpath or corridor or something. 

<img width="376" alt="screenshot 2017-05-29 14 24 01" src="https://cloud.githubusercontent.com/assets/38784/26558985/9a6dc7ec-447a-11e7-99fc-51f124b83a4a.png">

**Comment by bhousel** [comment]
btw, I added a `maxweight` field too after I took that screenshot
