### ISSUE TITLE
Keyboard shortcuts panel uses some Windows key names on macOS

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4073]
On macOS, the keyboard shortcuts panel displays some Windows key names that differ from what appears on most Mac key caps (although it does get [the symbols](https://support.apple.com/kb/PH18802?locale=en_US) right):

* <kbd>↵ Enter</kbd> should be <kbd>↵ Return</kbd>. (<kbd>⌤&nbsp;Enter</kbd> is a separate key that doesn’t always do the same thing as <kbd>↵&nbsp;Return</kbd>, although it does in iD. On non-extended keyboards manufactured in the last ten years or so, it’s mapped to <kbd>Fn</kbd><kbd>↵&nbsp;Return</kbd>, which is a pain to type.)
* <kbd>⌥ Alt</kbd> should be <kbd>⌥ Option</kbd> (Modern keyboards also say “Alt” in small text on the Option key, and many [localized keyboards](https://support.apple.com/en-us/HT201794) omit “Option”, so this isn’t a big deal.)

**Comment by 1ec5** [comment]
<kbd>↨ Pause</kbd> is inscrutable. I believe you can use <kbd>F15</kbd> on an extended keyboard, but I’m not sure what the equivalent is on a non-extended keyboard, which lacks <kbd>F15</kbd>.

**Comment by bhousel** [comment]
Just so I understand - are you suggesting we change the labels for everyone for better clarity, or adjust the labels depending on detected OS (swap <kbd>Return</kbd> / <kbd>Enter</kbd> or <kbd>Alt</kbd> / <kbd>Option</kbd>).  I'm ok with either choice, as long as it makes things easier to understand.

 <kbd>↨ Pause</kbd> is weird - I've never seen that symbol before but I took it from [iD shortcuts page on OSM Wiki](https://wiki.openstreetmap.org/wiki/ID/Shortcuts).  I guess it doesn't hurt to show it since all the other nearby keys have inscrutable symbols too.  At least they are consistent.

I've never seen a <kbd>F15</kbd> key, so probably safe to leave it off.
(Similarly, I intentionally left off <kbd>☰ Menu</kbd> as Right-click to conserve space)


<img width="786" alt="screenshot 2017-06-01 13 50 24" src="https://cloud.githubusercontent.com/assets/38784/26693197/534f7bcc-46d1-11e7-99b1-6fb8d7e617e6.png">

**Comment by 1ec5** [comment]
> are you suggesting we change the labels for everyone for better clarity, or adjust the labels depending on detected OS (swap Return / Enter or Alt / Option).

The latter: for macOS, show <kbd>↩&nbsp;Return</kbd> and <kbd>⌥&nbsp;Option</kbd>.

> ↨ Pause is weird - I've never seen that symbol before but I took it from iD shortcuts page on OSM Wiki. I guess it doesn't hurt to show it since all the other nearby keys have inscrutable symbols too. At least they are consistent.

The <kbd>↨</kbd> was added in [this edit](https://wiki.openstreetmap.org/w/index.php?title=Template:Key_press/core&diff=1469588&oldid=1468351). I’m not sure where it came from; Wikipedia’s version once used <kbd>⎉</kbd>, but that was [removed](https://en.wikipedia.org/w/index.php?title=Template:Key_press/core&diff=607011515&oldid=591973154) for being apocryphal.

macOS does have [a standard set of keyboard symbols](https://support.apple.com/kb/PH18802?locale=en_US) for display in menus (so “⌘⇧S” instead of “Command-Shift-S”). However, Mac keyboards have no Pause button. A Mac running Windows via Bootcamp can use <kbd>fn</kbd><kbd>⎋&nbsp;Esc</kbd>, but there doesn’t appear to be anything like it in macOS. So I guess there’s a second issue here: the vast majority of Macs have no way to switch parent ways.

**Comment by bhousel** [comment]
> So I guess there’s a second issue here: the vast majority of Macs have no way to switch parent ways.

No its ok, backslash <kbd> \ </kbd> will switch parent ways!  That's actually the original and most convenient way to do it on a US mac keyboard.  

The <kbd>PgUp</kbd><kbd>PgDn</kbd><kbd>Home</kbd><kbd>End</kbd><kbd>Pause</kbd> alternatives were added here https://github.com/openstreetmap/iD/pull/3539#issuecomment-258048973 as a workaround for non-US non-Mac keyboard layouts

**Comment by 1ec5** [comment]
Ah! In that case, we could simply hide <kbd>Pause</kbd> on macOS.

**Comment by bhousel** [comment]
> Ah! In that case, we could simply hide Pause on macOS.

I don't mind showing it.. It probably won't confuse anybody and I sometimes use an external Logitech keyboard with my Mac, which includes that key.

**Comment by bhousel** [comment]
Worth mentioning that this screen does weird things on Windows because of how `iD.cmdUi` substitutes keys.  I'm probably going to just split up the keys and the modifiers and make a new function that produces more display-focused output.

![keyboard_shortcuts](https://cloud.githubusercontent.com/assets/38784/26745010/9b5215b6-47b6-11e7-8e6b-bd9785e65133.png)

**Comment by bhousel** [comment]
done with #4080

**Comment by bhousel** [comment]
> I've never seen a F15 key, so probably safe to leave it off.

Oh look what landed in my email this morning

<img width="708" alt="screenshot 2017-06-06 10 28 54" src="https://cloud.githubusercontent.com/assets/38784/26834373/26677ee0-4aa3-11e7-8035-2774e37744a9.png">

* goes up to <kbd>F19</kbd>
* Still 2 <kbd>delete</kbd> keys 🙄 
* <kbd>fn</kbd> where insert should be?

**Comment by 1ec5** [comment]
Yay, trivia time:

* The macOS standard library can express [key events](https://developer.apple.com/documentation/appkit/nsevent/1535851-function_key_unicodes) up to <kbd>F35</kbd>.
* Whereas most platforms refer to Backspace and Delete, Mac documentation always refers to Delete and Forward Delete.
* <kbd>Fn</kbd> replaced the traditional [Help key](https://en.wikipedia.org/wiki/Help_key) (?⃝) on Mac keyboards a decade ago. <kbd>Clear</kbd> has always been there.
* Also a decade ago, MacBook Pro keyboards had Num Lock and most of the numpad mapped to Fn combinations, while <kbd>Enter</kbd> sat between the right <kbd>Command</kbd> and the left arrow key, where the right <kbd>Option</kbd> sits today.

[More about Macintosh keyboards](https://en.wikipedia.org/wiki/Apple_Keyboard#Layout).
