### ISSUE TITLE
Feature request: show toilets tags on buildings

### ISSUE THREAD

**Issue by gappleto97** [openstreetmap/iD#4076]
I would like to see it that on anything `building=*`, the user is prompted for toilets tag information. Even if it's as simple as a yes/no box.

**Comment by bhousel** [comment]
A related issue (`toilets:wheelchair`) was just discussed on the tagging@ mailing list.  [I commented there](https://lists.openstreetmap.org/pipermail/tagging/2017-May/032421.html):

>The fields that we expose for restaurants and other buildings are already really cluttered with other things.  
>
>I don’t think I would be able to explain to new mappers that they are supposed to use the `wheelchair` tag on anything, but the `toilets:wheelchair` tag on a building that has the toilets in it, unless they want to map the toilets individually within the building as point nodes.  Too complicated.

So to keep the interface simple, I'd rather see people just tag things like toilets as point nodes within the building, rather than adding more attributes to the building presets.
