### ISSUE TITLE
update help text for context menu

### ISSUE THREAD

**Issue by althio** [openstreetmap/iD#4089]
If I understand correctly... I found this text (emphasis mine):
> ### Selecting Features
> **_To select a map feature_**, like a road or point of interest, **_click
> on it on the map_**. **_This will_** highlight the selected feature, open a panel with
> details about it, and **_show a menu of things you can do with the feature_**.

I think that is not true anymore with the new context menu, it requires a right-click.
Then Selecting Features, left-click, right-click and context menu should be explained more precisely somewhere:
https://github.com/openstreetmap/iD/blob/34b773f3e626c2519e6dfa23fb8e5a05551f0ca4/data/core.yaml#L534
https://github.com/openstreetmap/iD/blob/34b773f3e626c2519e6dfa23fb8e5a05551f0ca4/dist/locales/en.json#L628

**Comment by althio** [comment]
already mentioned in #4018
closing as duplicated
(although I will appreciate to know what is the primary place to make the modification)

**Comment by bhousel** [comment]
The `core.yaml` file is the correct place to update the help text, however the real problem is that giant blocks of help text are not very friendly for translators.  If we just change a few words, I think they need to retranslate the whole block of text on Transifex.  

So the right solution is to break up all this text into smaller chunks while we refresh the text with new content.  However doing so we might lose all the existing translations (which we would anyway even if we just change a few words here and there), so there's no great solution for fixing this other than just doing it at a time when we won't be releasing iD for a little while and let the translators have some weeks to redo the translations in smaller chunks.
