### ISSUE TITLE
Terminology "Unmaintained Track Road" causing a lot of problems and work

### ISSUE THREAD

**Issue by solgule** [openstreetmap/iD#4092]
Background:
I know that this issue has been up before, but I feel that the problem has not been fully understood by the answering iD developer.

The problem use case :
Beginner OSM cartographers see "Unmaintained Track Road" in iD, thinks it is and error and changes it to anything that sounds maintained and useful to them.

The resulting problems:

1)  The tag selected by the beginner OSM cartographers is depending on what group they identify themself with the most.  It might end up as a footpath or as a road, since anything "unmaintained" is out of question in their oppinion.

2) A maintained doubletrack will be rendered the same way as all the singletracks in the same area. Example use case: forest areas where there are a both maintained tracks used for recreation (double tracks for trail running, mountainbiking, etc) and a lot of unmaintained narrow paths (=single tracks).

3) In case of (2) the intention of the original cartographer is lost, which was to make it possible for people new to the forest area to use a safe maintained double track instead of the more unsafe network of single tracks. Maybe it is difficult to follow some unmarked singletracks, they are overgrown, maybe dangerous with wrong equipment, etc.

4) In other cases there will pop-up highway tags that should not be used in forest and agriculture areas: footpath, bicycle only, roads for normal cars, etc.

5) If the beginner's cartographer misstake is detected a lot of work might be needed to correct it, since this will happen again and again as long as iD use another definition than the one used by most cartographers. Again and again the cartographer must explain why iD has got it wrong because it restricts a tag without creating new tags to fill the hole they left behind, and that most renderers will make the map almost useless.

6) Track is "de facto" restricted to "unmaintained track road" by a few software developers, instead of a standard created and reviewed by a community of experienced cartographers.

7) Last but not least: A tag for maintained double tracks will be missing in OSM. If the normal procedure had been used: writing a proposal that is reviewed by the OSM community, then the need for new tags would have been detected.

The solution:
It would be helpful to me and all the users of OSM if iD used the same terminology as in the OSM wiki page for track (and of cource this apply to all other tags too). I'm sure that iD developers are trying to make things better, but the "de facto" way is causing a lot of problems for everyone trying to do it correctly by following the OSM wiki. Only restrict tag definitions after going through all steps: proposals, community reviews and if approved, updated OSM wiki.

**Comment by bhousel** [comment]
@solgule Please read through: 

* #2615 
* #2982 
* https://github.com/openstreetmap/iD/commit/6b2a69282e0b274c270f5288765ca3db1c8890f9 
* https://github.com/openstreetmap/iD/issues/3022#issuecomment-194395691 
* #3038 

There is lots of info in there about `highway=track`. 

I wish we could fit a better description into the 300px or so space for the preset name, but this is what we came up with. 

* "Unmaintained" = possibly dangerous to drive along
* "Track" - because we felt it was important to put the original word in there
* "Road" - for vehicles primarily

If some of those words do not describe how `highway=track` is used in your country, feel free to translate it some other way.   

(It's ok to use `highway=service` + `surface=unpaved/grass/dirt/etc` for driveways or other double track roads that receive regular maintenance - e.g. cleared of trees or snow shortly after a storm)

Also, don't read too much into the OSM Wiki.  It's a useful resource - but in many cases it is a poor proxy for how tags are actually used in the real OSM database, and discussions and votes there do not reflect the opinions of people who use OSM, write tools for it, or consume OSM data.

**Comment by pnorman** [comment]
If users are applying highway=track to roads simply because they're unmaintained, I encourage you to contact them via changeset discussions, and if necessary, escalate to the local community or the DWG.

**Comment by brandonreavis** [comment]
Can you give some examples that are improperly tagged as a result of this? I am not doubting you, but I am curious. 

Here is the original pull request where it was changed that explains why it was changed: https://github.com/openstreetmap/iD/pull/2982. Here are some more complaints about it: https://github.com/openstreetmap/iD/issues/3038

In response to your problems:

1) Is there something wrong with leaning towards path or service road? Again, some examples would help. There are cases of temporarily maintained logging roads in the Pacific Northwest that should be tracks but are still maintained, but that is generally more of an exception than the norm from what I've encountered.

2) Two-tracks that are only maintained for mountain bikes and pedestrians and are not drivable are not supposed to tagged as tracks - they are paths. I agree it would be nice to differentiate them, but the highway tag is not the way to do it. That said, it is hard to find clear documentation about this and much of it is contradictory.

For example: http://wiki.openstreetmap.org/wiki/Path_controversy
_"**highway=path** : ... OR where motorvehicles are forbidden (unless otherwise indicated by snowmobile/agricultural=designated or similar)."
"**highway=track** : Implies that it's wide enough for a small motorcar to drive on, even if it's illegal."_

This is probably the best source of information in the wiki about this topic: http://wiki.openstreetmap.org/wiki/United_States_roads_tagging

_"Ways on which most motor vehicle traffic is either legally or physically prohibitive get highway=path, or a more specific tag as appropriate. This category includes roads that normally function as hiking trails because of barricades opened only occasionally or rarely."_

3) Changing a path to a track to indicate it is wider and more followable for mountain bikes or hikers isn't right - there are width / surface tags for this. If it is drivable by a car thats a different story though and would make sense as a track.

4) Paths and service roads in forested areas do make sense. So do tracks, but sparingly (if solely for logging or maintained).

5) Its unfortunate if mistakes are being made but it was changed to try to curb mistakes from just calling it "track"

6) At Natural Atlas we put a lot of attention to detail into cartography of forested areas. It is very misleading to call anything that looks like a two-track a track. A track in OSM is a road and unimportant road. Maps get very unnavigable if every dirt road is made a track – especially ones that aren't drivable by cars. 

At the end of the day i think OSM needs to a much better job of educating mappers about road hierarchy because it is confusing and it is so inconsistent. Another example of this is the aversion to tagging something as an Unclassified Road and large swaths of Arizona are an unnavigable network of tertiary roads. iD can help do this partially, but I think it's a bigger problem of community education.

**Comment by manfredbrandl** [comment]
There was a big discussion in german forums when i translated 'unmaintained track road' literally into German, because 'Unmaintained Road' ('Nicht erhaltene Straße') was wrong for German people. Now it reads 'Feld-/Waldweg' ('Farm/Forest Road'). People using iD do not know, that they tag a road with 'highway=track', they tag it as 'Unmaintained Track Road'. If that text is misleading, OSM data will be tagged wrongly sometimes.

**Comment by solgule** [comment]
Thanks for input.

I find it very useful to use highway=track for all tracks that are wide enough to drive on with at tractor or similar, if the track is in the forest or fields. In the forest singletracks are common near the tracks, and they change a lot from year to year: new singletracks are created, some old singletracks are no longer used and quickly are ower grown. The tracks are more long lived.

Usually tractors are driving on the tracks for maintanance, putting out gravel and so on (when needed, not often). Otherwise the tracks are used for forest recreation (running, walking, mountainbiking, etc). No normal cars allowed on the tracks. Tracks are not very wide, no meeting places, no road signs, too steep and slippery for normal cars in som parts, etc.

Tracktype is helpful to indicate the maintenance grade:
1) grade1 and grade2: implies maintained, but not for sure.
2) grade4 and grade5: implies unmaintained, but not for sure.
3) grade3: implies rarely maintained, but not for sure.

One of the following proposals for a new short description in iD (currently: "Unmaintained Track Road") would help me and save a lot of time (in priority order):
1) "Maintained/Unmaintained Track"
2) "Track"
3) "Track/Unmaintained Road"

Here is a map example, showing a forest area where there are a lot of singletracks nearby maintained tracks. As you can see using path would be a problem in this area, since the information of which are tracks (most maintained, but not all) would be lost in many of the common renderers:

http://www.openstreetmap.org/#map=15/59.3933/13.4663

**Comment by bhousel** [comment]
Thanks @solgule, it does sound like we generally agree on what "tracks" are, and maybe disagree a bit on what "maintenance" is.

For example, a paved grade1 track that goes through an apple orchard may have 1000 visitors a day during October and receive regular maintenance, and then sit empty the rest of the year.  If that track happens to connect two tertiary roads, it would be irresponsible for OSRM to route a car down that way in February, so the track tag is appropriate.

A track might be totally fine to drive down, or it might not.  I see it more as setting an expectation for a data consumer about whether the road is _probably drivable_ (`highway=service`) vs. _unknown / it depends_ (`highway=track`).   

On a personal note, I actually do volunteer with the chainsaw crew for my county park system and we clear debris off tracks and fire roads all the time (yes, maintenance!) but this happens when weather is clear and people are available to do the work.  A track may be impassible for months before we can get to it.  Firefighters have their own chainsaw equipment and can obviously clear trees in an emergency, but their time is better spent at the fire and not stuck clearing a tree that fell.  

We can not put all of this into the preset name, and people are reluctant to change the wiki, so let's leave as is for now.

**Comment by jidanni** [comment]
I needed to do a lot of work also due to this too!

**Comment by julcnx** [comment]
Many countries have different approaches to highway=track, and the renaming to "Unmaintained Track" has caused much trouble, with mappers abusing the tag for anything unpaved including named residential roads, as well as the main link between villages included tertiary roads with references.

The referenced issues used to make the decision only include a few posts and I wish more feedback was collected before making such a change. I still don't understand why a vague "Track" like "Path" would not be sufficient.
