### ISSUE TITLE
Incosistent wording: delete (permanently)

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4097]
There is one place where delete is used with 'permanently' (German: 'dauerhaft'):
![image](https://user-images.githubusercontent.com/5360273/26937708-686f830c-4c72-11e7-9ea2-5d3841870e95.png)
Everywhere else delete is used w/o permanently.
I suggest not using permanently at all.

**Comment by bhousel** [comment]
Hmm, it looks like @simonpoole made this change in b1b3bc7

The reason was to make it more clear to a user that deleting something will remove the it from the map that everyone sees, and not just hides it from their local view.  This is good!

I'm open to the idea of changing the wording here, but new-users-deleting-things-in-iD is a kind of touchy issue going back years, so we need to be extra careful about this message.

**Comment by simonpoole** [comment]
IMHO the other occurrences should be changed if they don't imply the right thing, where are they to start with?

**Comment by manfredbrandl** [comment]
@simonpoole There are many places where delete is w/o permanently. I found them in transifex:
![image](https://user-images.githubusercontent.com/5360273/26943343-85b4466a-4c85-11e7-9c18-64f1fbbab84b.png)
Much more till the end:
![image](https://user-images.githubusercontent.com/5360273/26943384-aaacbb82-4c85-11e7-8395-17295eede60d.png)

**Comment by bhousel** [comment]
I don't want to change all instances of "Delete".  It sounds like just the "permanently" part of the one message is causing confusion.  If it's causing real problems we can change it, otherwise we should just leave it alone.

I think any of these are fine:

- "Delete this feature"
- "Delete this feature from the map"
- "Delete this feature permanently"
- "Delete this feature from OpenStreetMap"

**Comment by manfredbrandl** [comment]
It is not causing real problems, i just want the german translation to be consistent as possible. I just transalted 'delete permanently' to 'Löschen'. Users unaware of the effects of their deletions may be helped more with a warning at the save (upload) menu.

**Comment by simonpoole** [comment]
@manfredbrandl as such things goes, I actually think the wording as is is very consistent, as in both cases when the action is described prior to it been taken, we use "permanently", that could be reinforced in the other messages, but I doubt that would make a difference.

The background for the wording change was and is new users believing that they are editing a personal map for display purposes, this may have been mitigated by improved tutorials and documentation, but I wouldn't bet on it.

**Comment by manfredbrandl** [comment]
@simonpoole I do agree with the problem that people think they are editing local data. Telling them that delete is permanent doesn't make a difference to the local-data-thinking. Maybe 'delete from the global map' will. What do you think?

**Comment by bhousel** [comment]
> Addition: Maybe there should be a message for first time editing which tells that editing is not local data but globally shared data.

We do mention this a few times in the walkthrough text now. 

<img width="588" alt="screenshot 2017-06-10 11 34 11" src="https://user-images.githubusercontent.com/38784/27004059-cb471670-4dd0-11e7-879a-540b912ff18f.png">

**Comment by manfredbrandl** [comment]
I close this issue because I was too focused on consitency. I changed the translation to include 'dauerhaft'.
