### ISSUE TITLE
Moving the map and changing the background causes the line you are drawing to disappear

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4099]
Here is a video, http://i.glideservers.com/u/jam02ffff7b-5907-414f-988d-658a6dd2d279.mp4
Not sure what causes it, but I am using CTRL + B to switch backgrounds.
It also happens when going slower, seen here http://i.glideservers.com/u/jam61fa59fa-d8a6-4ac3-8798-88a333797098.mp4

Using
Google Chrome	58.0.3029.81 (Official Build) (64-bit)
Revision	ac0bae59f0aa5b391517e132bf172144b1939333-refs/branch-heads/3029@{#746}
OS	Windows
JavaScript	V8 5.8.283.32

Thanks

**Comment by bhousel** [comment]
Looks like this is an issue with the code introduced in a18d690.
The idea is to prevent `window.location` from changing while the user is drawing something (to avoid the situation where the user accidentally hit the back button and are transported very far away mid drawing)

The problem is that `window.location` also changes [here](https://github.com/openstreetmap/iD/blob/a727c31221cac5cd2b60b13ffa81dd1b8c4c7feb/modules/renderer/background.js#L86) if the user switches imagery. It fires off a hashchange event - then [this code](https://github.com/openstreetmap/iD/blob/a727c31221cac5cd2b60b13ffa81dd1b8c4c7feb/modules/behavior/hash.js#L17-L20) in `hash.js` checks what changed and if you happened to be moving the map and changing the background at the same time, you are tossed back into browse mode.

**Comment by JamesKingdom** [comment]
Thank you :) @bhousel
