### ISSUE TITLE
Ctrl+Shift+B swaps between the background

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#4153]
As described here https://github.com/openstreetmap/iD/issues/2492#issuecomment-314544711
>using Ctrl+Shift+B as described in the keyboard shortcuts swaps between the background like when using Ctrl+B.

**Comment by kepta** [comment]
I got some time to look into this bug. 

There are two d3keybinding namespaces involved, `info` and `background`.

`info` namespace registers  `Ctrl+⇧+B`
``` Javascript
{
    "event": {
      "key": "b",
      "keyCode": 66,
      "modifiers": {
        "shiftKey": true,
        "ctrlKey": false,
        "altKey": false,
        "metaKey": true
      }
    }
  }
```
and `background` registers  `⇧+B`
```Javascript
{
    "event": {
      "key": "b",
      "keyCode": 66,
      "modifiers": {
        "shiftKey": false,
        "ctrlKey": false,
        "altKey": false,
        "metaKey": true
      }
    }
  },
```

I guess problem seems to lie here https://github.com/openstreetmap/iD/blob/master/modules/lib/d3.keybinding.js#L25 
The `background`'s callback gets called when pressed `Ctrl+⇧+B`, since on [line](https://github.com/openstreetmap/iD/blob/master/modules/lib/d3.keybinding.js#L38) gets executed.

@bhousel what do you think?

**Comment by bhousel** [comment]
> I guess problem seems to lie here https://github.com/openstreetmap/iD/blob/master/modules/lib/d3.keybinding.js#L25
> The background's callback gets called when pressed Ctrl+⇧+B, since line gets executed, believing Ctrl+B was pressed.
> @bhousel what do you think?

Yeah, it does seem like something not quite right in that code.  I would expect `didMatch` should be true after the <kbd>⌘⇧B</kbd>, so that <kbd>⌘B</kbd> would not be tested.

**Comment by kepta** [comment]
@bhousel I might be wrong though, but having a separate `namespace` would have separate instances of d3keybinding? And if that is true they would also have their own `didMatch` variables?

**Comment by bhousel** [comment]
`didMatch` is a local variable to the `testBindings()` function, so every time a key is pressed and iD tries to match a handler, it should start out being `false`.  I think the code can be changed to make it more clear or exit early as soon as a match happens.

**Comment by bhousel** [comment]
I found out what was happening, the key event just gets sent to all of the listeners unless we specifically stop it.  This is normal.

I added some `stopImmediatePropagation()` calls to stop the event from firing after one of the listeners handles it.  

I'm a bit uneasy about this because it means that the code is probably order-dependent.   So it works as long as  <kbd>⌘⇧B</kbd> and <kbd>⌘B</kbd> are registered in the right order, otherwise the <kbd>⌘B</kbd> could potentially override the <kbd>⌘⇧B</kbd>.

I'll think more about this but closing the issue for now..
