### ISSUE TITLE
Add reverse direction box to rivers and streams

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4174]
Similar to how it works with oneway roads, it would be useful to have this for streams/rivers also.
![jam3bc3c4e2-a570-428e-b90b-447ebb4f756c](https://user-images.githubusercontent.com/11473673/28498656-dc2c611c-6f99-11e7-8209-80dac1e5cdf0.png)

**Comment by bhousel** [comment]
Ah, this is a tricky problem.  We can't use the `oneway` field, because: OSM has this idea of what `oneway` means on waterways, and it is for navigation of boats, not for direction of flow of the water.  I have no idea what happens today when people try to tag oneways on waterways in iD, but I wouldn't be surprised if there is an issue.

So if we can't use `oneway` then what?   A field that's just a "Change Direction" button without the checkbox?   Maybe.  

I'd really rather have mappers switch water flow direction the "proper" method, by right clicking on the feature and using the edit menu.

**Comment by bhousel** [comment]
> I'd really rather have mappers switch water flow direction the "proper" method, by right clicking on the feature and using the edit menu.

Closing as wontfix for now..  Users can change waterway direction with the edit menu or reverse keyboard shortcut.
