### ISSUE TITLE
Add Taoist Temple

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4175]
All I could find was "Buddhist Temple", so I marked a lot of Taoist (Daoist) temples as Buddhist.

**Comment by jidanni** [comment]
Or just have Temple. Else many other people will commit the same wasteful mistake and have to edit each one to fix it.

**Comment by bhousel** [comment]
Thanks @jidanni - for now, typing "temple" does bring up "Place of Worship" which is the generic preset to use in this case:

<img width="377" alt="screenshot 2017-07-23 14 57 39" src="https://user-images.githubusercontent.com/38784/28502033-899253bc-6fb7-11e7-994f-f83b07bcd602.png">

Then the user can add "taoist" as the religion:

<img width="373" alt="screenshot 2017-07-23 15 00 33" src="https://user-images.githubusercontent.com/38784/28502038-b91bb916-6fb7-11e7-95b6-3e3ad2dddbd3.png">


I agree we should add a preset for "Taoist Temple" with a yin-yang icon and the `religion=taoist` already filled in, like we do for other major religions.

**Comment by bhousel** [comment]
I ended up adding these 4 because there are icons for them on the [`amenity=place_of_worship` page](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dplace_of_worship).

<img width="370" alt="screenshot 2017-07-24 00 04 14" src="https://user-images.githubusercontent.com/38784/28507905-66f0c602-7004-11e7-8713-d5f09ac0743b.png">
