### ISSUE TITLE
Task area is not visible

### ISSUE THREAD

**Issue by arun-aji-balaji** [openstreetmap/iD#4189]
![screenshot from 2017-07-29 12 56 02](https://user-images.githubusercontent.com/10905492/28743042-9ee38e70-745d-11e7-85b6-0b9342f39476.png)

When I open a task in task manager in firefox browser, the task area is not visible.

![screenshot from 2017-07-29 13 07 29](https://user-images.githubusercontent.com/10905492/28743113-691a9cd2-745f-11e7-929f-1945788bd47b.png)

But it appears when I open the same task area in midori browser

**Comment by JamesKingdom** [comment]
I just tried a HOT task with firefox, and it appears to work for me?
I'm using 54.0 (32 bit)
![screenshotfirefox](http://i.glideservers.com/u/jamb0a25e4c-a07c-47f6-b6c0-aa179ead9ba9.png)

**Comment by bhousel** [comment]
Ah yeah this is a known "mixed content" issue with the HOTOSM task manager, not something we can fix in iD.  Certain browsers will prevent you from loading active content via `http:` from an application loaded via `https:`.  (If you open the Firefox developer console, you'll see a warning about this).

There are 2 ways to fix this:
1. Load iD via `http:`  e.g. task manager can push users to `http://preview.ideditor.com/release` instead of `https://openstreetmap.org/edit` (This is less secure, but should work)
-or-
2. Serve the gpx task boundary file via `https:`  (This is the better fix)

**Comment by arun-aji-balaji** [comment]
Thanx @JamesKingdom. I am using 54.0 32-bit for linux

**Comment by bhousel** [comment]
Looks like this is being tracked here, so I'll close the issue on the iD side.
https://github.com/hotosm/osm-tasking-manager2/issues/988
