### ISSUE TITLE
Not recognizing highway=services

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#4194]
I was noticing an user deleting [highway=services](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservices) here.
Trying to understand why, I took a look on iD and saw that it simply says that the object is a "Highway"

Somehow iD is not recognizing `higway=services` on areas.
Select (or draw) any closed way with `highway=services` and you should see what is happening.

Example http://www.openstreetmap.org/way/414501953
![](https://user-images.githubusercontent.com/982338/28761511-6688e2ae-7585-11e7-81ca-25936e3de5b5.png)

**Comment by bhousel** [comment]
I agree iD should add a preset for it..
However the one in your screenshot should have an `area=yes`.  That's the reason why it just looks like a loop of road.

**Comment by naoliv** [comment]
I guess that `area=yes` was a workaround for https://github.com/gravitystorm/openstreetmap-carto/issues/137 (which was fixed)

See that it gets properly rendered http://www.openstreetmap.org/way/414501953 without `area=yes`

**Comment by bhousel** [comment]
The `area=yes` is needed for any OSM software that doesn't know what a `highway=services` is (this includes iD, until we add the preset).  Because people can invent whatever tags they want, no OSM software has a complete picture of what all the tags are and what area semantics they all imply.

See https://github.com/osmlab/id-area-keys for more on this.  It's the "area guessing" code from iD extracted into its own project.  

As a rule, you should always add an `area=yes` for any `'barrier', 'highway', 'footway', 'railway'` that you want to be an area, because closed loops of these things are assumed to be lines unless the software knows better.

**Comment by naoliv** [comment]
While at it, `highway=rest_area` https://wiki.openstreetmap.org/wiki/Tag:highway%3Drest_area is similar and should get a preset too, if possible.

**Comment by JamesKingdom** [comment]
There's already a preset for rest area, 
![restarea](http://i.imgur.com/uzTX9IX.png)

**Comment by naoliv** [comment]
Hum... I see why iD was not recognizing it here.
It should also support `highway=rest_area` without `area=yes` (otherwise it will only show `Highway` too)

`highway=rest_area` and `highway=services` are the two exceptions in `highway` that should be considered an area by default.

**Comment by bhousel** [comment]
Hmmm.. Looks like we do already have Rest Area and Service Area presets, but they are not recognized without the `area=yes`.  I have to look into our code and see if there is a way to support this.
