### ISSUE TITLE
Name field should not be mandatory for presets

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/iD#4200]
Names are important but there are lots of features in OSM which usually do not have a name. [According to @bhousel](https://github.com/openstreetmap/iD/pull/4196#issuecomment-319183856), iD displays a name input field for all presets and this cannot be turned off. This leads newbies to add names and being later told by experienced mappers that they should only add names which are names.

I would like to suggest to either drop this default and force the authors of the presets to add a name field explicitly if necessary. As an alternative, preset authors could disable the name field. The latter does not require a modification of most presets but is counter-intuitive for preset authors and has the smell of being legacy. :-)

Examples where a `name=*` tag is usually wrong:

* traffic signals
* street lights
* cable distribution cabinets

The world is not simple. There are lots of parking areas which do not have a name in reality but have a pseudo-name in OSM (`name=<supermarket> parking`). But there are parking areas which have a real name. Other examples are intersections (in some regions), trees (most don't have but some have).

**Comment by bhousel** [comment]
I agree, there are definitely a bunch of presets that definitely should not have a `name` field, so we should either 
- add something like a `noname` property for presets that should not have a name
-or-
- don't add name field automatically, and require presets to have a `name` field if they want one

I'm kind of undecided on what to do about it.  The first option would be an easy fix.  The second option would mean a change 99% of the presets, but I kind of like it because it eliminates "magic" from the code.

**Comment by pnorman** [comment]
> I'm kind of undecided on what to do about it. The first option would be an easy fix. The second option would mean a change 99% of the presets, but I kind of like it because it eliminates "magic" from the code.

I prefer the second one, even if it touches a lot of presets. The change is simple, glancing over the presets to see if `name` is suitable is a good idea, and it eliminates magic.

**Comment by manfredbrandl** [comment]
I also prefer the second one. Eventually the presets file can be automagically compared with the taginfo-database and/or the wiki to show the most important (used) missing presets.

**Comment by willemarcel** [comment]
I like this change, but it's strange to have the name field between other fields (and not on the top) in a preset that doesn't have it by default. Would it be possible to set the name field to always appear on the top if it's filled?

**Comment by boothym** [comment]
I went to add a name to natural=wood but noticed the name field wasn't there, can the name field be added back to that preset?

**Comment by JamesKingdom** [comment]
> @willemarcel Would it be possible to set the name field to always appear on the top if it's filled?

I'm not sure, but it would require some other code to be changed, maybe @bhousel has an idea.

> @boothym  I went to add a name to natural=wood but noticed the name field wasn't there, can the name field be added back to that preset? 

Some presets do not come with the name tag by default, because they wouldn't normally have a name - a buffer stop is a good example of this.

I'm not sure why I didn't add name to `wood`, but I will add it back.

Also, if there is a preset and you want to add a name field manually, here's how you can do it:
![](https://i.glideservers.com/u/jamd83d1925-e80d-4940-b8f2-b01de96980a8.gif)

**Comment by boothym** [comment]
@JamesKingdom don't worry, I know how to add a name manually 😉 

Might also want to add it back to landuse=forest.

**Comment by JamesKingdom** [comment]
> Might also want to add it back to landuse=forest.

It was already added to forest:
https://github.com/openstreetmap/iD/blob/d493ee9a8986b6a68d85bea0eeee56e39b65f6bb/data/presets/presets/landuse/forest.json#L1-L7
