### ISSUE TITLE
Coordinate search results should display a marker

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4218]
Search for 25,121.5 using the search box.
Do you see some half ovals?
OK, now where is 25,121.5?
Is it in the lower left corner?
Is it in the center?
And where exactly in the center? The user wonders.
All this could be solved if a marker appeared.
It's not like the user searched for a 7-11 store and its marker appeared in the middle of the screen.
Therefore for coordinate search results, please display a marker.

**Comment by bhousel** [comment]
> OK, now where is 25,121.5?
> Is it in the lower left corner?
> Is it in the center?

Yes it's in the center.

> All this could be solved if a marker appeared.
> It's not like the user searched for a 7-11 store and its marker appeared in the middle of the screen.

That's exactly why we don't show a marker - Because there is no map feature there to edit.  iD is an editor, not a search engine, so we only draw markers where things are.

Most users don't want to do what you are doing.  If you want to know the precise coordinates of where things are, open the Measurement Panel <kbd>⌘⇧M</kbd>, and if you want to know the precise coordinates of your mouse pointer, open the Location Panel <kbd>⌘⇧L</kbd>.

**Comment by jidanni** [comment]
(OK, but it reminds me of some early  GIS where it is returning the whole region 25-26,121.5-122.5.)

**Comment by EvanCarroll** [comment]
Consider my use case @bhousel. I want to edit a polygon which is complex and disorienting. There is no good sat imagery on it. I have geocoded pictures I've uploaded to the wikimedia commons.

Here is the picture:

https://commons.wikimedia.org/wiki/File:Camden_Park_playground_(22886).jpg

Here is the geohack entry:

https://geohack.toolforge.org/geohack.php?pagename=File:Camden_Park_playground_(22886).jpg&params=029.729728_N_-095.571282_E_globe:Earth_type:camera__&language=en

Geohack shows the pin..

<img width="467" height="276" alt="Image" src="https://github.com/user-attachments/assets/6b5952b7-1e38-4862-8f8d-63a75d4de709" />

If I click through I can see the pin.

https://www.openstreetmap.org/?mlat=29.729728&mlon=-95.571282&zoom=15&layers=M

But if I go to edit that I lose the pin...

In this use case, these coordinates are _more_ important than the satellite imagery because it's out of date.

I frequently have this work flow.

That sat imagery isn't entirely useless, I can see the foundations laid for the park, I just need to have an idea of what goes where.

<img width="1058" height="653" alt="Image" src="https://github.com/user-attachments/assets/22356254-f72b-427a-ad21-26be31d0cbe5" />
<img width="1220" height="772" alt="Image" src="https://github.com/user-attachments/assets/3573a3ca-6d03-439d-9e6e-c124121e5b40" />

**Comment by EvanCarroll** [comment]
I think the cross hair approach is a solid idea. But the marker/pin is certainly more socially acceptable.

It's also kind of interesting because for my use case, it's very similar to the street view that bing provides. It would be really cool if we could add the geolocated pictures from wiki commons in the same way.

https://commons.wikimedia.org/wiki/Category:Camden_Park,_Houston (category and all sub-categories) overlaid on the map would give me really great data.

**Comment by tordans** [comment]
@EvanCarroll 
> It would be really cool if we could add the geolocated pictures from wiki commons in the same way.

 Here are a few options to work with geolocated images right now:

a. iD has a Geolocated Photos feature where you can drop local pictures and they get shown similar to Mapillary imagery

> <img width="408" height="219" alt="Image" src="https://github.com/user-attachments/assets/da0a5950-3097-430f-a1ff-5e0b6fa441c8" />

b. Some of the known street level imagery platforms allow uploading single pictures. For examples Panoramax https://panoramax.openstreetmap.fr/ GoMap and MapComplete already allow uploading single pictures from their (mobile) apps to Panoramax. You could add a note and upload the images as part of the Note using the MapComplete Note theme https://mapcomplete.org/notes.html for example. Those images will then be visible in iD as part of the MapComplete integration.
