### ISSUE TITLE
LAS file import for contour generation

### ISSUE THREAD

**Issue by valdisj** [openstreetmap/iD#4225]
I think its time to try to find a way to have a mechanism within OOM for LAS files importing with possibility to configure what contours (incl generalization) are generated as vectors.

**Comment by bhousel** [comment]
@valdisj That sounds like a great research topic, but I'm not sure that OSM is ready for imported lidar data yet.  I could imagine something similar to the Mapillary interface, where iD gives you a small streetview preview window and some overlay data on the map that might be useful for tracing, but it's not something that I can work on right now in the main iD project.  

I'm closing for now, but I do hope you pursue this and build out a proof of concept, because it sounds fun!
