### ISSUE TITLE
Add keyboard shortcut for Upload button

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#4234]
Adding a keyboard shortcut for the Upload button in the Save panel would make it more convenient to save a changeset. Over time, as additional fields are added to the panel, the shortcut would become more important for making the Upload button easily accessible.

Personally as a Mac user, I’m a fan of ⌘↩ as a shortcut for the default action in any modal. But I don’t know whether <kbd>Ctrl</kbd><kbd>Enter</kbd> is similarly intuitive for Windows and Linux users. Another option would be to add `accesskey="u"` or somesuch, which could be more discoverable.

**Comment by bhousel** [comment]
I thought about this more and I don't think we should do it.  I think the risk is too great that a user who is typing stuff in the comment box might accidentally trigger the keyboard shortcut that uploads before they are ready to do it.

Besides, a keyboard shortcut for the upload button doesn't really save any time, since the user will just be sitting there for some seconds waiting for the upload to finish.

**Comment by pnorman** [comment]
> Personally as a Mac user, I’m a fan of ⌘↩ as a shortcut for the default action in any modal. But I don’t know whether CtrlEnter is similarly intuitive for Windows and Linux users

Just to note, the convention from many sites is enter sends, and shift-enter gives a newline.
