### ISSUE TITLE
Fruit tree preset

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/iD#4240]
A possible solution to enable users to correctly map fruit trees would be to add a **Fruit Tree** preset and have a combo field `Fruit` with the options to the most popular fruit species that add the proper `species` value. It would be something like:

![captura de tela de 2017-08-17 17-39-01](https://user-images.githubusercontent.com/666291/29432853-7f45d260-8373-11e7-9cff-e0fe6d8c07dc.png)

I've seen a lot of collaborative projects to map fruit trees in urban environments, it would be nice to make it easy to add this kind of information in OpenStreetMap.

@bhousel if you think this is a good solution, I can add it.

**Comment by bhousel** [comment]
Before we just add this preset, I want to think about this more.

So I was looking at the recommendations here:
https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree
and
https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dorchard
https://wiki.openstreetmap.org/wiki/Key:trees

And they are all kind of strange.
* `natural=tree` uses the scientific names for the trees.  These are inscrutable unless the user is a botanist, or we build a big combo or a lot of presets.
* `landuse=orchard` uses the `trees=*` tag with its weird `trees/plants` values.

These two approaches are incompatible.  This isn't the first time I look at the suggested OSM tagging for a thing and wonder what they were thinking when they came up with it.  I really don't know how to make it easy for normal people who just want to map an apple tree, and maybe say that they are honeycrisps if they want to get specific.

I wonder if there is a wikidata solution for this problem of picking from a big list of things, without actually maintaining big lists of things in the editor itself.  e.g. `brand:wikidata` is a really cool idea and should really replace the `brand` tag.  Could we have something like `species:wikidata`?  Maybe we could make a taginfo-like service that gives us nice lists of things to pick from.

Thoughts @1ec5 ?

**Comment by 1ec5** [comment]
The `landuse=orchard` and `natural=tree` tagging schemes were probably devised and popularized by different people. I guess no one has attempted to unify them yet? Note that [`crop`](https://wiki.openstreetmap.org/wiki/Key%3Acrop) is also a thing.

>  Could we have something like `species:wikidata`? Maybe we could make a taginfo-like service that gives us nice lists of things to pick from.

[`species:wikidata`](https://taginfo.openstreetmap.org/keys/species%3Awikidata) is in use, with 88 unique values. The most common values are [saman](https://en.wikipedia.org/wiki/Albizia_saman), [_Dipterocarpus alatus_](https://en.wikipedia.org/wiki/Dipterocarpus_alatus), and [Japanese cherry](https://en.wikipedia.org/wiki/Prunus_serrulata).

taginfo only tells us the most popular QIDs, but we’d need a mapping to those QIDs’ labels in the current language. The MediaWiki API can give us the labels and aliases for up to 50 QIDs at a time; see [an example query in the API sandbox](https://www.wikidata.org/wiki/Special:ApiSandbox#action=wbgetentities&format=json&ids=Q259500|Q140957|Q165321|Q321437|Q156831|Q7220656|Q179729|Q886511|Q158746|Q156938|Q158776|Q20986885|Q165137|Q26745|Q146149&props=aliases|labels&languages=vi).

Any list based on the current most popular values will be quite esoteric. So we could instead build a SPARQL query against the Wikidata Query Service that returns [all the fruit-bearing species](http://tinyurl.com/y97rw2ld) (for the `landuse=orchard` preset). It’s a little tricky, because Wikidata distinguishes between tree species and the fruit they bear.

I’m not sure how to make a manageable list of tree species for the `natural=tree` preset: how could we determine via Wikidata statements that a species commonly lines streets, for example?

**Comment by bhousel** [comment]
Let's not..  I don't have the energy to spearhead any more tagging initiatives.

**Comment by tordans** [comment]
Thanks for moving https://github.com/osmlab/name-suggestion-index/issues/94 here, @bhousel.

I see two topics here:

**a. How to handle the different tagging schema that exist for very similar things.**

Mainly Tag:natural:tree with Key:genus (…) and Tag:landuse:orchard with its Key:trees values.
My opinion is, that we should spend our energy in making those non-harmonised usable in iD and thereby moving the complexity of the different schemas from the user to the code. This will help faster, than any push to harmonise the tagging.

IMO it is ok to start with one thing, like Tag:natural:tree and adapt this to Tag:landuse:orchard later (or the other way around).

**b. Where to get the data from.**

I understand the appeal of a source like Wikidata. However as far as I understand this ATM the data for trees is not very good yet. Eg there is a ["oak" in Wikidata](https://www.wikidata.org/wiki/Q33036816) but there was no relation to the [Wikidata for "tree"](https://www.wikidata.org/wiki/Q10884) until a minute ago when I added it (I hope I did that correctly…). I would need to understand a lot more about Wikidata, but I agree, it could be a nice Admin-UI for everyone who wants to add to the presets.

Do we need someone with deep Wikidata know how to help here?

However, I can also imagine managing a tree-list the same way other presets are maintained. This system is already in place and works fine. Also with translations.

I prefer the later, since it allows to try the feature out with lees effort.

**Interface:**

I like the idea by @willemarcel to extend the tree-Preset with a special select option. I image this working like the "this street part is a bridge" preset, which adds tags based on the radio button.

This interface would not allow a autocomplete search on the top level like I though about in https://github.com/osmlab/name-suggestion-index/issues/94, but it would still make tagging trees way easier that it is now.

**What would be required to move this idea forward?**

Is it a question of relevance like "do we really need this feature"?
Is it a question of time/effort like "we can only do it if its really easy to do"?

**Comment by bhousel** [comment]
> What would be required to move this idea forward?
> 
> Is it a question of relevance like "do we really need this feature"?
> Is it a question of time/effort like "we can only do it if its really easy to do"?

I think the best way to describe this is... 

If the recommended tags for trees were common English words (like everything else in OSM), this field would have been added in 10 minutes.  `natural=tree`+`tree=apple`.  done.

Because the recommended tagging is the Latin species name, I don't want to add it to iD because most mappers would not be able to fill it in.

Also - I know about `species:en` (ok I guess) and `species:de` (why? no other tag works like this)  and `species:xx` (ugh now everyone else wants one for their language).  But that's not solving the problem, it's just adding more tags.

**Comment by tordans** [comment]
@nyurik can we use the new Wikibase (https://github.com/openstreetmap/iD/issues/5321) feature to solve this?

To sum up the conversation:
- The "genus" (type of tree) tagging is very complex cause its based on latin names – [Example](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree#Tagging_examples)
  > An oak tree (unknown species):
  > leaf_type=broadleaved
  > genus=Quercus (this is the latin genus name)
  > genus:en=Oak

- We need presets that can be chosen based on the local name (ideally) or the english name (good enough)

Wikibase: 
- The preset in Wikibase should allow the user to select the tree-type (like "apple") and then fill the interface with attributes like "natural=tree, leaf_type=broadleaved, leaf_cycle=deciduous, genus=Quercus, genus:en=Oak"
- Ideally, the Wikibase includes translation for the tree names

**Comment by nyurik** [comment]
Yes, I think this can be done very easily with the new system.  In the [presets discussion](https://wiki.openstreetmap.org/wiki/OpenStreetMap_talk:Wikibase#Presets), I looked at one of the presets to see how well it would map. Seems it is very straightforward, and would benefit not just tree species, but the whole of preset system (once understood and agreed, I can quickly import all of it with a bot).

Essentially, there will be a preset with
* English label "oak tree", any English aliases, and up to 250 symbol long English description.  Plus it will have the same label/aliases/description in every other one of the 5000 languages wiki supports.
* a list of keys or tags that are required to add it
* any usage restrictions (e.g. `nodexit=yes` is not permitted on `ways` in the German-speaking countries). We can easily [document that](https://wiki.openstreetmap.org/wiki/Item:Q501) for both individual values and whole presets themselves.
* plus it will have an "equivalent to wikidata item" tag, which will allow automated import of all the translations/species name/... from Wikibase into the dataitem if needed.

All this depends on what properties we want to define. We have about [25 at the moment](https://wiki.openstreetmap.org/wiki/Special:ListProperties), but we can add as many as we need.

**Comment by tordans** [comment]
FYI for anyone who comes across this: There is a discussion at https://wiki.openstreetmap.org/wiki/Talk:Key:species:wikidata if maybe the `species:wikidata` could be used to provide the data for a tree-suggestion-feature.

**Comment by tordans** [comment]
FYI for anyone who comes across this: The MapComplete Theme for Trees now has an option to add Wikidata IDs for Tree species 
- Preview https://twitter.com/pietervdvn/status/1520790868894142464
- Example https://mapcomplete.osm.be/trees.html?z=20&lat=52.47281&lon=13.44765&background=osm#node/9580449850
