### ISSUE TITLE
Disconnect entire landuse areas from lines

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4245]
It would be nice to have a possibility to detach an entire line by for example pressing d shotcut.

**Comment by bhousel** [comment]
I agree, I want this sometimes too.. good suggestion 👍

**Comment by slhh** [comment]
This seems to be a quite unsafe operation. Someone might want to disconnect a highway from landuses, which I see as the main usecase, and miss to repair the highway connections. In addition the operation needs be prevented due to breaking relations in many cases.

How about an operation cutting a surrounding around the selected ways out of the selected areas?

**Comment by bhousel** [comment]
> This seems to be a quite unsafe operation. Someone might want to disconnect a highway from landuses, which I see as the main usecase, and miss to repair the highway connections. In addition the operation needs be prevented due to breaking relations in many cases.

Can you provide a screenshot of an example case?  I'm having a hard time imagining a situation where disconnecting a landuse from a road would break a relation.  

> How about an operation cutting a surrounding around the selected ways out of the selected areas?

Polygonal operations (add, subtract, etc) are coming, probably not soon though.

**Comment by slhh** [comment]
@bhousel 
> I'm having a hard time imagining a situation where disconnecting a landuse from a road would break a relation.

It depends on how the operation works.

-  If the operation disconnects a single selected way from everything else:
   - With the highway being selected it disconnects the way from the next highway ways, which breaks for example any route relations on the highway, and in addition the highway connectivity.
   - With a way, which isn't closed, of a landuse multipolygon being selected, it breaks the multipolygon.
- If it disconnects two selected ways:
Assume we have:
-A residential area multipolygon consisting of ways A, B, and D
-An industial area multipolygon  consisting of ways A and E
-A motorway B
-A tertiary road C which is partially coincident with way E
-A bus rote using ways B and C
![disconnect lines](https://user-images.githubusercontent.com/13684947/32147117-14c0f3d6-bce2-11e7-9cd8-3b300db373f1.png)
What happens if the user disconnects ways E (landuse) and C (highway) in view of the central node
originally used by all features? How can the editor split this node?
Not to break the residential area requires A and B to share the same node.
Not to break the bus route requires B and C to share the same node.
Not to break the industrial area requires A and E to share the same node.
As a result C and E still need to share the same node, and can't be disconnected without breaking a relation.

**Comment by bhousel** [comment]
Thanks for the examples @slhh ..  It makes sense - I wasn't thinking of multipolygons formed of several connected ways.

I guess we will need to disable the operation in cases where the disconnect would break a relation.  The existing disconnect action already does this.

**Comment by quincylvania** [comment]
I did this! You can now disconnect entire individual lines or areas at once. The operation is prevented if not enough of the way is visible or if the way is a member of a relation connected to another member by one of the nodes.

![disconnect area demo](https://user-images.githubusercontent.com/2046746/56439183-14811400-629a-11e9-9c56-8fd5e126d34a.gif)

**Comment by yaugenka** [comment]
Very nice! Thank you @quincylvania

**Comment by bhousel** [comment]
This is so awesome @quincylvania  👏 
I've wanted this for a while....

**Comment by 1ec5** [comment]
Nice! I must admit some trepidation because of personally preferring landuse areas to join up with line features in many instances. But the example you’ve given of disconnecting a parking lot area is a good one: lots of parking lots in my area were long ago joined to nearby buildings or roadways but now need to be detached in order to properly map sidewalks and curbs. I’ll be using this feature a lot.

**Comment by robybully** [comment]
Great, can't wait to usw this function in iD.
Many many thanks! @quincylvania
