### ISSUE TITLE
Street name labeling obscuring node features

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#4271]
See http://www.openstreetmap.org/edit?editor=id#map=21/47.40755/8.54858 there is actually a pedestrian crossing already there, but the node can't be seen (a slightly more prominent icon would address the issue too).

**Comment by bhousel** [comment]
I agree, the label placement should avoid tagged nodes..

**Comment by pnorman** [comment]
![image](https://user-images.githubusercontent.com/1190866/30236358-c3ba382c-94cc-11e7-9ec1-c1e29477f793.png)

![image](https://user-images.githubusercontent.com/1190866/30236369-d5d25cec-94cc-11e7-9081-7ef49e1bfb6d.png)

**Comment by bhousel** [comment]
Relevant code is [here](https://github.com/openstreetmap/iD/blob/master/modules/svg/labels.js#L404) for anyone who wants to work on this..

**Comment by Nitiquita** [comment]
Hi @simonpoole, can you clarify what is being obscured by the street name? Thanks!

**Comment by bhousel** [comment]
Hi @Nitiquita this code is a bit advanced for a get started issue, but I'll try to break down what's happening.

This code in `map.js` draws all the map stuff - `drawLabels` is a render function that gets passed all the map data in an array called `entities`:
https://github.com/openstreetmap/iD/blob/7e98d7f9893068fb8f5a2404df328e9a42f6fa34/modules/renderer/map.js#L296-L302

Inside `drawLabels`, we have a spatial index called `rdrawn` (see the [rbush repo](https://github.com/mourner/rbush) for details) - it will store bounding boxes around where the text labels can go.  There are lots of calls to `tryInsert()` scattered throughout this file - this is how we add labels to the `rdrawn` index as long as they don't collide with anything else.
https://github.com/openstreetmap/iD/blob/7e98d7f9893068fb8f5a2404df328e9a42f6fa34/modules/svg/labels.js#L275-L278

One of the first things the `drawLabels` code does is it loops through all the `entities` to decide which ones get labels:
https://github.com/openstreetmap/iD/blob/7e98d7f9893068fb8f5a2404df328e9a42f6fa34/modules/svg/labels.js#L293-L316

☝️ My thought is that _inside_ the `if (geometry === vertex) { ... }` block,  you could add code like this to block out some space around "interesting" vertices, so that no labels will get drawn on top of there:
```js
if (entity.hasInterestingTags()) { 
  var coord = projection(entity.loc);
  var pad = 5;    // pixels of padding around the vertex
  var bbox = { 
     minX: coord[0] - pad, 
     minY: coord[1] - pad, 
     maxX: coord[0] + pad, 
     maxY: coord[1] + pad 
  };
  rdrawn.insert(bbox);
}
```

To get more insight into what the label placement code is doing, you can open a developer console and type `id.setDebug('collision')` - this will turn on debugging that draws the label placement boxes.

**Comment by bhousel** [comment]
I did some work on this today and it's a lot better..

006ee691b Adds label avoidance boxes for all points
d9e336783 Adds label avoidance boxes for interesting vertices (tagged, selected, child of selected)
This also reverts #3636, because we can draw labels on selected ways now that the labels will avoid the vertices.

This work will land with #4602, which changes a bit how vertices are rendered.

![labels avoid vertices](https://user-images.githubusercontent.com/38784/33967064-e8e228b8-e02f-11e7-8747-e67e6dd7a2a3.gif)

**Comment by bhousel** [comment]
done in #4602
