### ISSUE TITLE
Mapillary icons keep trying to overlay eachother

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4297]
When dragging the map around at a higher zoom level, the mapillary icons seem to fight for who is on top.
![screen](https://user-images.githubusercontent.com/11473673/29823552-e65479f0-8cc6-11e7-90e2-d9beaf9f1711.gif)

cc @kepta

**Comment by bhousel** [comment]
The Mapillary data is stored in an Rbush spatial index and, when redrawing, if too much of it appears in the same place, we only take the top few results.   

Rbush does not guarantee a stable sort in the results that it returns (because that would negatively affect performance).  If we wanted to sort the results before limiting them, we could add sorting to this block of code, as long as performance isn't affected too much.

https://github.com/openstreetmap/iD/blob/be65e1a53cdfe50117c4090142029a23e8b0dfad/modules/services/mapillary.js#L234-L244

**Comment by kepta** [comment]
@bhousel was looking at the performance penalty of adding a `stable sort`. 
I wonder if the `_.compact` is redundant here

https://github.com/openstreetmap/iD/blob/be65e1a53cdfe50117c4090142029a23e8b0dfad/modules/services/mapillary.js#L239

I believe in this case
`rtree.search` always returns an `[]`.
hence, `_map(partitions, function ...)` would be an array of array `[[]]`.

Which I guess make running `_.compact redundant`. I possible guess the intent was to run it after `_.flatten`?

**Comment by bhousel** [comment]
I agree the `_.compact` is unnecessary - I probably added it during development, thinking that `rbush.search` might return `null` instead of `[]`.

**Comment by bhousel** [comment]
I played around with this earlier today and I realize now that we need to change the viewport partitioning code if we want the markers to sort in a stable way.  The viewport is split up in screen coordinates, and needs to be properly tiled in world coordinates, otherwise we will always be selecting from a different set of marker results (so sorting them won't matter much).
