### ISSUE TITLE
Account for word length in sorting

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#4325]
![screenshot_2017-09-08_18-16-16](https://user-images.githubusercontent.com/4283376/30220959-d389b27e-94c1-11e7-83a9-e4b4861499dd.png)

Clearly I'm searching for "huis" (house), it should be the top result. I don't see an issue with the terms/name translations. (Locale: nl)

My idea would be to account for word length while sorting.

**Comment by bhousel** [comment]
I think in this case "house" is sorted below the others because of this `"matchScore": 0.5,`:

https://github.com/openstreetmap/iD/blame/9750fa4d829e6e3c361b30ff38a6fc79ff7fc502/data/presets/presets/building/house.json#L20

This was added for #2793 - which is basically saying that sometimes a feature can be tagged as a building _and something else_, and when that happens, we want to make sure to make rank buildings lower than the other things.

The fix for this would probably be in here - maybe ignore that `originalScore` stuff in the case of an exact match:
https://github.com/openstreetmap/iD/blob/9750fa4d829e6e3c361b30ff38a6fc79ff7fc502/modules/presets/collection.js#L56-L67
