### ISSUE TITLE
Add preset for intermittent streams

### ISSUE THREAD

**Issue by valleyofdawn** [openstreetmap/iD#4337]
In arid countries most of the waterways we trace are intermittent streams.
We manually add the intermittent=yes tag.
Would be useful if a separate entry for these entities existed under water in iD.
It could be called a gully, a wadi, an arroyo, as the names change geographically.

**Comment by bhousel** [comment]
Sounds good to me.. We could add an "Intermittent Stream" preset, with all those other words in the search terms.

**Comment by boothym** [comment]
Or what about an intermittent checkbox field (like oneway) added to the waterway presets?

**Comment by bhousel** [comment]
> Or what about an intermittent checkbox field (like oneway) added to the waterway presets?

That would work too, then we would want to add those search terms to whatever waterway preset might use the field.  I guess we would only add it to stream?  I'm assuming it's probably not really used on river, canal, drain.

**Comment by valleyofdawn** [comment]
The checkbox would also be very relevant to reservoirs and ponds, but I like the preset solution better.

**Comment by valleyofdawn** [comment]
Also "wash" and "gulch" are sometimes used to describe such dry streams.

**Comment by bhousel** [comment]
> The checkbox would also be very relevant to reservoirs and ponds, but I like the preset solution better.

Ok, in that case then I agree a checkbox makes more sense. 👍

**Comment by slhh** [comment]
Streams and ditches seem to be the most frequent intermittent waterways. Drains and reservoirs are quite likely to be intermittent too.

Rivers are less likely, but more than 25000 intermittent ones do exist in the database (2.5% of all rivers).
Aproxiamtely 1% of ponds and lakes are tagged with intermittent=yes, and we can assume that such a secondary tag is used less often than it should be.

We do have 1000 intermittent canals in the database, but most might be mistagged drains.

In addition to the more probable features the intermittent field should be shown for all water/waterway features where the tag is present.

I don't like the preset solution, because it can led to tag a waterway as a stream, just because it is an intermittent waterway.

**Comment by valleyofdawn** [comment]
Fair enough.
The reason I like the preset better is that I often trace tens of those in one changeset and having "Gully" at the top of the list would save me some clicking. Maybe both solutions can be implemented together?

**Comment by bhousel** [comment]
> The reason I like the preset better is that I often trace tens of those in one changeset and having "Gully" at the top of the list would save me some clicking. Maybe both solutions can be implemented together?

Yes, that's what I did - there's now a checkbox that's added to all the waterway presets, along with a few others like "spring", "pond", "waterfall", etc.  And also a preset for "Intermittent Stream" which has the box checked already.

<img width="500" alt="screenshot 2017-09-11 14 15 39" src="https://user-images.githubusercontent.com/38784/30289922-bb76e080-96fb-11e7-896f-1837e2c94a30.png">

closed in fec27a04d
