### ISSUE TITLE
Only basic phone number check

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/iD#4338]
A strikt and full check for phone number formating has been discussed yet at #3495 and #2704. Result: The user should not be forced to use a formatting he is not used to.

A less obstrusive solution might be to not check the full phone number format, but to check only if it actually starts with an international prefix (these things like +225 or +229 or whatever). This would not force the users to use digit separations they are not used to, but it might encourage the contributers to add at least the international prefix.

Data consumers could later strip of every non-digit character and it would be likely (more likely than now) that they get something, that is a valid phone number…

**Comment by bhousel** [comment]
I'm fine with just using a library to format the phone numbers like #3495, @pnorman was 👎 on it.  Maybe he's changed his mind since then?

Either way, this is not an issue I have strong opinions about.

**Comment by pnorman** [comment]
I didn't really think about **formatting** of numbers. Automagically showing standard spaces/etc would be useful. It was the automatic changing which I had issue with.

**Comment by bhousel** [comment]
> It was the automatic changing which I had issue with.

Can you elaborate more on why?  This automatic changing is what I had in mind, and seems to be what people are asking for.

It would be pretty trivial to reformat a phone number with [node-phone](https://www.npmjs.com/package/phone#usage-1x-branch).  This doesn't seem too different from how we already reformat `wikipedia` when the user enters a URL.

**Comment by pnorman** [comment]
> Can you elaborate more on why? This automatic changing is what I had in mind, and seems to be what people are asking for.

Are you thinking of changing to format, or changing to E.164?

**Comment by bhousel** [comment]
> Are you thinking of changing to format, or changing to E.164?

I don't know, and I'm probably not really understanding the issue.

I looked more at that node-phone library and it seems to be specifically for validating mobile numbers for sending SMS, (it throws out non-mobile numbers in countries where it is possible to determine this based on the number prefix) so that's not a good candidate after all.  👎 

There are other heavyweight options like [google-libphonenumber](https://www.npmjs.com/package/google-libphonenumber), but this seems like overkill and I don't really want to pull in a 400k dependency for phone number validation.  👎 

If people want iD to automatically prepend the international calling prefix if it is missing, it's possible we'd guess wrong around the borders of countries, so we shouldn't do it.  👎 

If people want a simple save time validation - not full format validation, but just check to see that a country code is present, I guess we could do that.  👍 

If people want a subtle field warning / highlight - that's #2836 and we don't have that feature yet.

**Comment by manfredbrandl** [comment]
I would prefer two save time validations: (1) Are there only allowed characters (inital '+', numbers and blanks)? (2) Is there a (potentially valid) country code (i.e. does the field start with '+' followed by 1 to 3 digits followed by a space) ?

**Comment by pnorman** [comment]
> I don't know, and I'm probably not really understanding the issue.

Because E.164 isn't what's mappers have decided to use everywhere. 

> I looked more at that node-phone library and it seems to be specifically for validating mobile numbers for sending SMS, (it throws out non-mobile numbers in countries where it is possible to determine this based on the number prefix) so that's not a good candidate after all. 👎

Yes, I had a look at the API it didn't seem like it would work.

> There are other heavyweight options like google-libphonenumber, but this seems like overkill and I don't really want to pull in a 400k dependency for phone number validation. 👎

It's AsYouTypeFormatter looks cool, but that's pretty heavy. libphonenumber-js is smaller, but still moderately heavy. It also doesn't match up with our needs because

> they're supposed to input their personal mobile phone numbers, or home stationary phone numbers if they're living in an area where celltowers don't have a good signal, not their business/enterprise stationary phone numbers)

Whereas we generally don't care about personal mobile phone numbers. google-libphonenumber might have the same problem.

Without a light-weight library much of this discussion might be moot.

Most of the library size seems to be related to the large amount of data needed to identify numbers, and some of that is telling the difference between types of numbers, e.g. premium, toll free, personal numbers, shar5ed cost, etc. We don't really care about that. With libphonenumber-js, that saves [60 kb](https://github.com/catamphetamine/libphonenumber-js#customizing-metadata)

**Comment by bhousel** [comment]
My gut is saying we should just wait for #2836, then write a regex to issue a warning.

**Comment by bhousel** [comment]
Closing here, let's just consider this as one case for #2836 (warn users if a field value looks weird)
