### ISSUE TITLE
make possible to find tourism=field by searching "Attraction"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#4339]
followup to #4323 (thanks for fixing this!)

Expected:

one can find tourism field by searching "attraction"

What happens:

typing "attraction" in "Add field:" at http://preview.ideditor.com/master/#id=n2972298771&map=19.28/49.30898/22.61957 is not finding anything, despite fact that attraction is default value of tourism field.

**Comment by bhousel** [comment]
I don't think I can change the name of the field from "Tourism" to "Attraction".  This is because the field uses the `tourism=*` key, and so it will automatically display for any preset that uses `tourism=*`.  (e.g. museums, hotels, zoos, etc)

For example, see guest house (`tourism=guest_house`):
![tourism](https://user-images.githubusercontent.com/38784/30326964-58ddc068-9798-11e7-8a3b-dccc809a61eb.gif)

**Comment by matkoniecz** [comment]
Field of the name is OK and changing would break handling of other values.

I only propose adding synonym, used only during search, so it will be easier to find.

**Comment by bhousel** [comment]
> I only propose adding synonym, used only during search, so it will be easier to find.

Oh, sorry we can't do that - the dropdown autocomplete just works on display name  :(

**Comment by matkoniecz** [comment]
And there is no way whatsoever to add synonym? Would it be a good idea to open issue requesting this feature?

**Comment by bhousel** [comment]
> And there is no way whatsoever to add synonym? Would it be a good idea to open issue requesting this feature?

I can't think of a way to do it..
