### ISSUE TITLE
Shop=furnace is deprecated

### ISSUE THREAD

**Issue by thetornado76** [openstreetmap/iD#4347]
The Key shop=furnace is deprecated
https://wiki.openstreetmap.org/wiki/Tag%3Ashop%3Dfurnace
The new tag is shop=fireplace
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dfireplace
Please change your preset.

**Comment by bhousel** [comment]
@thetornado76 Who decided this?  Furnace and Fireplace are two completely separate concepts.

**Comment by thetornado76** [comment]
I don't know who decided deprecated furnace.
I understand the wiki:
If you want to buy a oven, you use shop=fireplace. If you want a new heating you have to ask a Craft =plumber

**Comment by bhousel** [comment]
I agree this this is a kind of useless tag (and it is indeed rarely used), but it looks like someone just stuck the deprecation language on the wiki page [in this change](https://wiki.openstreetmap.org/w/index.php?title=Tag:shop%3Dfurnace&diff=1253019&oldid=1039317) with out any discussion or even a comment saying what they changed.

Anyway I'm fine with deprecating the preset (because it's very unlikely that the furnace mappers are going to show up later complaining to me about it) but I do wish wiki editors would be more diligent.
