### ISSUE TITLE
Flexbox the buttons

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4356]
This is like #4349 in that sometimes we should be better at layout long things in narrow space.  The solution is usually to just use [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), which gives us more control over how and whether things are allowed to wrap.

Currently our buttons are just floated things with fixed width, but I think we can use flexbox for layout instead.  If the buttons themselves are also flexbox containers for the icon and text, I think we might be able to drop the text labels when there is not room for them, leaving only the icons.  (This is a bit more elegant than just dropping the labels with a media query).

This is at around 750px wide screen.  It's worse for languages that use longer words:
<img width="689" alt="screenshot 2017-09-18 09 36 11" src="https://user-images.githubusercontent.com/38784/30548762-023f7d8c-9c61-11e7-83f0-b4ec0da33ad0.png">

cc @kepta

**Comment by tridip1931** [comment]
sure @bhousel.

**Comment by tridip1931** [comment]
👋 @bhousel 
Created a pull request of the changes. 

I faced 1 issue while building CSS in dist. I had to run `npm run all` everytime for my CSS changes to go to `dist` iD.css. Is there any way I can cut on that?

**Comment by bhousel** [comment]
> I faced 1 issue while building CSS in dist. I had to run npm run all everytime for my CSS changes to go to dist iD.css. Is there any way I can cut on that?

Not currently, unfortunately the live reload server only rebuilds the .js code bundle.  Even with that, I dont think it catches all the stuff under `/data` properly, like presets.

https://github.com/openstreetmap/iD/blob/ccf452acf6f2d97b8f72bc9e8efca3ea8e2f2b4d/development_server.js#L17-L21

I think there are [rollup plugins](https://github.com/rollup/rollup/wiki/Plugins) that can do this stuff, I just haven't had the time to look into it.

**Comment by bhousel** [comment]
@tridip1931 Looks like a good start - can you see if you can get the buttons to be uniform width?  Also check RTL, looks like they're not centering correctly without the label (like there is some margin remaining in there).

**Comment by tridip1931** [comment]
@bhousel Thanks for pointing out the inconsistencies.  Sorry for overlooking it. 

### LTR
<img width="787" alt="screenshot 2017-09-21 15 48 23" src="https://user-images.githubusercontent.com/7458983/30691301-f1789a84-9ee4-11e7-823c-3f3aa4ac7603.png">

### RTL
<img width="770" alt="screenshot 2017-09-21 15 48 10" src="https://user-images.githubusercontent.com/7458983/30691342-0fdad460-9ee5-11e7-86b0-2cc078df4aa1.png">

---

The icons are slightly misaligned due to the `border-right` applied to them.
<img width="513" alt="screenshot 2017-09-21 13 03 45" src="https://user-images.githubusercontent.com/7458983/30691441-60fdb88a-9ee5-11e7-9933-fe99d161f92b.png">

If we remove the borders, they can be perfectly aligned to center. The buttons are of `40X40` and icons size are `20X20`
<img width="512" alt="screenshot 2017-09-21 13 04 39" src="https://user-images.githubusercontent.com/7458983/30691502-8a72e58c-9ee5-11e7-9604-bb9602c572ef.png">
<img width="510" alt="screenshot 2017-09-21 13 04 45" src="https://user-images.githubusercontent.com/7458983/30691513-969bbc3a-9ee5-11e7-8fff-dbe059322751.png">

---

### Reason for Extra margin in RTL
There seemed to be extra margin applied to the icon because of this css 
```
[dir='rtl'] .icon.pre-text {
  margin-left: 5px;
  margin-right: 0;
}
```
It seems even though direction is RTL, `margin-left` does not inverses it so that there is some space between the icon & label of the button.
<img width="548" alt="screenshot 2017-09-21 15 47 56" src="https://user-images.githubusercontent.com/7458983/30691780-7d4e75f0-9ee6-11e7-9d6e-0217809e09cf.png">

Commenting out the css seems to solve the issue.

---

### Sidebar breaks on RTL

I think iD sidebar breaks on RTL. 
 
<img width="1435" alt="screenshot 2017-09-21 16 07 01" src="https://user-images.githubusercontent.com/7458983/30691969-32348004-9ee7-11e7-968f-4ee3f6f50d29.png">

Should I look around this issue?

**Comment by bhousel** [comment]
@tridip1931  Yes, make sure the changes to the icon layout work RTL too.  The RTL sidebar looks like this in master  (add `&rtl=true` to a local running iD to test this):

<img width="300" alt="screenshot 2017-09-21 09 07 54" src="https://user-images.githubusercontent.com/38784/30697349-b1fbcd46-9eac-11e7-83ef-8428fe29e868.png">

**Comment by tridip1931** [comment]
Sorry, I have tested wrong. 😨  I will make those changes.

**Comment by quincylvania** [comment]
Not sure if this is still being worked on but #5443 would affect the top bar buttons if merged.
