### ISSUE TITLE
HOT task box not shown

### ISSUE THREAD

**Issue by nomoregrapes** [openstreetmap/iD#4381]
* On the HOT tasking manager I choose an area to start mapping and then click "Edit with iD Editor".
* iD starts in a new tab in the correct area (may not be zoomed in as much as normal, I'm not sure)
* The purple box does not show, so I can't tell what area my task is. **This is the bug I'm reporting.**
* OSM data does load.
* When I first observed this: retrying (clicking Edit from the tasking manager again) the problem persisted. It was using Windows/Chrome, but during a workshop and I didn't note any precise details.
* I have now had this occur to me on a different computer, although retrying (clicking Edit from the tasking manager again) the tab opened with the purple outline. Chrome Version 61.0.3163.100 (Official Build) (64-bit). Windows 7 Pro.

I appreciate this bug may not be reproducable for everyone. Is there any helpful info I  can get for debugging why/how it occurs?

**Comment by bhousel** [comment]
Hi @nomoregrapes, this is due to Chrome blocking [mixed content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content).
If iD is loaded via `https` Chrome will refuse to load certain kinds of content via `http:`.  

Each browser has slightly different rules for this, but in Chrome the gpx file is blocked.  Unfortunately, I don't think there is anything we can do about this from within iD.  

The solution is for the task manager to serve the task squares over `https:` (see https://github.com/hotosm/osm-tasking-manager2/issues/988).  In the meantime you can use a browser other than Chrome, or use iD from an `http:` connection, e.g. on `http://preview.ideditor.com/release/`

**Comment by gappleto97** [comment]
There's an additional bug in here. If you do trick them into ignoring the mixed content stuff, then it complains about the CORS header. Is that a thing to change on your end, or is that for the task list?

**Comment by bhousel** [comment]
> There's an additional bug in here. If you do trick them into ignoring the mixed content stuff, then it complains about the CORS header. Is that a thing to change on your end, or is that for the task list?

I think that is a server configuration issue - they would need to allow cross origin requests for the .gpx files.
