### ISSUE TITLE
Don't write "Local GPX" in imagery_used changeset tag if that's not true

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4385]
Some trace ids should be recorded in changesets
https://github.com/openstreetmap/openstreetmap-website/issues/1645#issuecomment-333304771

**Comment by bhousel** [comment]
Right now the `imagery_used` tag always says "Local GPX", but instead it should probably write the name of the file.  

This is because:
* it might not be local (i.e. passed in via url api)
* it might not even be a gpx, as we allow other types like .geojson and .kml now.


The code that does this is here:
https://github.com/openstreetmap/iD/blob/f7b7bd7d5fcfbbdf7fc71e6e37c43f288fd841fd/modules/renderer/background.js#L92-L95

So, a better thing to do would be to add an accessor to that gpx layer, so this code can call something like `gpx.getFilename()`.

**Comment by jidanni** [comment]
I will tell GitHub, that when a 
"This was referenced on Nov 11, 2017" is added to a bug,
they really should notify all people subscribed.

**Comment by jidanni** [comment]
Currently the trace number is still thrown away. I cannot reopen the issue though.

**Comment by HolgerJeromin** [comment]
Because of  issue #4530 
Which you have seen.
Do you have more ideas how to solve this?

**Comment by jidanni** [comment]
> Because of issue [#4530](https://github.com/openstreetmap/iD/issues/4530) Which you have seen. Do you have more ideas how to solve this?

Thanks! I posted a "confirmation dialog" solution there.
