### ISSUE TITLE
Rename "Hashtags" field caption to say "Suggested Hashtags"

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4395]
Some people find this confusing because the hashtags field is not currently used by other tools, so we can change the field caption to de-emphasize its importance.

**Comment by sultrytsardine** [comment]
@bhousel Is this still available to pick up?

**Comment by arka-nitd** [comment]
@bhousel  I have submitted a PR. Please check and inform if my understanding of the issue is correct as this is my first contribution

**Comment by bhousel** [comment]
Sorry @sultrytsardine.. @arka-nitd got to it quickly.. But there are plenty of other great issues to close 👍

**Comment by FountainMapper** [comment]
The label "Suggested Hashtags" is confusing. I dont understand the motivation here! (I work with iD in german language, here its called "Vorgeschlagene Hashtags" which translates to "Suggested Hashtags").
Why is it confusing?

I always thought, when I save my work "Vorgeschlagene Hashtags"/"Suggested Hashtags" means: you are free to (re)use some of the recommended hashtags. Instead it means: These hashtags will be applied.
I guess other users misunderstand this as well.

Background:
I used the OSMco Tasking Manager to work on a tile in Peru. Hashtags are applied automatically. No problem, example changeset: https://www.openstreetmap.org/changeset/56431220
When I start iD again (to do independent work in germany) the hashtags are applied again to the changeset because iD remembers them. Well not nice, but this is the behaviour. Example changeset: https://www.openstreetmap.org/changeset/56453162
So I did a lot of changesets with unrelated hashtags.

**Comment by bhousel** [comment]
> The label "Suggested Hashtags" is confusing. I dont understand the motivation here! (I work with iD in german language, here its called "Vorgeschlagene Hashtags" which translates to "Suggested Hashtags").
> Why is it confusing?

This was added because somebody who runs mapathons found that their participants were confused when the field was just called "Hashtags".  

I guess the difference is that "Hashtags" makes it sound like you must leave it as-is, and "Suggested Hashtags" makes people more ok about changing what appears there.

(I actually don't have a preference what it's called)

**Comment by FountainMapper** [comment]
Ok, I dont know at which places the string is shown at all. (I am just an user here.) But in the Commit Changes dialog the string "Suggested Hashtags" is clearly wrong/confusing. I recommend to change it back.
