### ISSUE TITLE
Content in info panels is not copyable

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#4406]
It would be nice to have current object id displayed somewhere and have a possibility to copy it.
The current workarround is  to open it in the openstreetmap.org and copy from the url, but that's not a comfortable thing.

**Comment by bhousel** [comment]
iD now has a feature called "Panels" to show more information to advanced users:

<kbd>⌘ Cmd</kbd>+<kbd>⇧ Shift</kbd>+<kbd>B</kbd>: Toggle background panel
<kbd>⌘ Cmd</kbd>+<kbd>⇧ Shift</kbd>+<kbd>H</kbd>: Toggle history panel
<kbd>⌘ Cmd</kbd>+<kbd>⇧ Shift</kbd>+<kbd>L</kbd>: Toggle location panel
<kbd>⌘ Cmd</kbd>+<kbd>⇧ Shift</kbd>+<kbd>M</kbd>: Toggle measurement panel

(note if you are on Windows or Linux, change <kbd>⌘ Cmd</kbd> to <kbd>Ctrl</kbd>)

Both the History and the Measurement panels will show you the osm id of the selected feature.  Can you try this and let me know if it's what you are looking for?

I'm leaving this open because I think we have a bug that prevents users from _copying_ the stuff that is displayed in these panels.

**Comment by yaugenka** [comment]
Yes, there is a bug that you cannot copy data from the pannels.
Anyway the pannels seem to be a bit excessive for the purpose of getting just the id.

**Comment by yaugenka** [comment]
When you launch iD from OSM with some object selected, it displays its id in the url. How about changing the id in the url whenever selection is changed?

**Comment by bhousel** [comment]
> When you launch iD from OSM with some object selected, it displays its id in the url. How about changing the id in the url whenever selection is changed?

iD actually does this - but you won't see the url bar change on openstreetmap.org because iD runs in an iframe.  This is what I see when I run iD locally:

![url_with_selection](https://user-images.githubusercontent.com/38784/31347233-a8c0b4c6-ace9-11e7-8b1d-33bbf29e83b1.gif)

Anyway, please just pop open an info panel if you want to look at osm ids.  I added these specifically for users with more advanced needs.

**Comment by yaugenka** [comment]
I noticed that the coordinates in the url change when I move the map in iD on openstreetmap.org, so thought id can be changed as well. But ok if that is not possible.

**Comment by bhousel** [comment]
> I noticed that the coordinates in the url change when I move the map in iD on openstreetmap.org, so thought id can be changed as well. But ok if that is not possible.

It's possible but requires special code to push location updates between the iframe and the parent frame.. I'd rather not complicate that code right now.
