### ISSUE TITLE
shop=trade , shop=tiles presets

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4410]
https://wiki.openstreetmap.org/wiki/Tag:shop=trade
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dtiles

**Comment by iblancasa** [comment]
Could you add more information about what is this issue about?

Thank you :)

**Comment by bhousel** [comment]
Sure @iblancasa, the preset system is explained in [this README](https://github.com/openstreetmap/iD/blob/master/data/presets/README.md).   The presets and fields are all defined in `.json` files under `data/presets/...`

We're looking for:
- [ ] **A new preset file `data/presets/presets/shop/tiles.json`** - it should look like any of the other files inside the `shop` folder.. You can just copy an existing file like `data/presets/presets/shop/tobacco.json` and change the "name" to say `"Tile Shop"` and "tags" to say `"shop": "tiles"`.
- [ ] **A new preset file `data/presets/presets/shop/trade.json`** - same as with tiles, copy an existing shop preset, change "name" ("Trade Shop") and "tags" (`"shop": "trade"`)
- [ ] **A new field file `data/presets/fields/trade.json`** - This will let people pick from a list of common values what trade the "Trade Shop" is for.  You can copy an existing file like `data/presets/fields/tourism.json`, and change the "key" to `"trade"` and label to `"Trade"`.
- [ ] To make the `trade` field appear on the trade preset, open `data/presets/presets/shop/trade.json` that you just created, and add `"trade"` to the "fields" array.  You can put it after `"name"`, since it is kind of important (the order in the array is the order they'll display on the screen).

**Comment by bhousel** [comment]
Done in #4411, #4413
