### ISSUE TITLE
New help contents

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#4450]
The help is a bit outdated. I want it to include all information from the walkthrough that users may want to read again without practising again. I also want to split the texts into smaller parts for easier translation, especially for small changes of texts. The 'chapters' could be:
Help | Navigation | Feature Editor | Points | Lines | Roads | Areas | Buildings | Adresses | Relations | Editing Menu
@bhousel What do you think?

**Comment by bhousel** [comment]
Oh yeah, this is #4018 .. I'm going to close here as a duplicate.

If you want to work on it, that would be great!  I would definitely welcome a PR for this.

The only downside is that it would invalidate a lot of translations.  It would be good to figure out a way that we can make each translation a single paragraph, rather than the entire help chapter.
