### ISSUE TITLE
Rename tourism=chalet and add search terms

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4490]
Currently the name for this tag in iD is Chalet, however (confusingly) this tag is not for tagging chalets as in wooden buildings/cabins but holiday cottages as detailed on the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dchalet). 

For tourism=chalet I suggest the following:
- name: Holiday Cottage
- search terms: holiday cottage, holiday home, vacation home, chalet 
(chalet moved to terms because some users will be used to searching "chalet" when mapping a holiday cottage)

**Comment by bhousel** [comment]
Sounds fine, @lakedistrictOSM  - Because there is some confusion about the word, can you just confirm that the tag really is used to tag holiday cottages and not cabins?   

The osm wiki is often wrong, or just one person's opinion of what they think the tag should mean.  (In other words, I don't want to just change this label just because the osm wiki says so).

**Comment by lakedistrictOSM** [comment]
Of course the wiki is often wrong, but I believe it is correct in this instance. 

I've had a look at the `iD/blob/master/dist/locales` files and the German language version of iD uses the name "Ferienhaus" which literally translates to "holidayhouse" and the French version uses "Gîte" which translates to "holiday home" or "tourist cottage".

I agree it would be good to get more opinions on this before the any changes are made to the name.

**Comment by bhousel** [comment]
Thanks for looking into it @lakedistrictOSM - I just made the change..
(I didn't add "chalet" to the search terms because it is automatically included because it is the tag value)
