### ISSUE TITLE
Bug: shop=car in area with service=dealer, tyres, parts, ...  show road area outline.

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4497]
The [wiki page ](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dcar) allow to use "service=*" tag to specifiy car shop services like dealing, tyres, parts, repair, ... 
See also this [wiki page ](http://wiki.openstreetmap.org/wiki/Key:service#shop.3Dcar_.2F_shop.3Dcar_repair).

**Comment by bhousel** [comment]
Oh yeah, I changed this in #3535 (see that ticket for more context)... 

We couldn't use the `service=*` tag for vehicle services because the values are already overwhelmingly used for highway and railway stuff.  This makes it impossible to suggest good values to a user wanting to tag vehicle services for a car shop.  (see taginfo output below - you can see that `service=*` used for car shops is relatively rare).

<img width="539" alt="screenshot 2017-11-03 10 04 17" src="https://user-images.githubusercontent.com/38784/32377533-60808ff8-c07e-11e7-9e68-c70b293a53fd.png">

Instead we are supporting multikey tags like `service:vehicle:*=yes/no`

(This is similar to, and inspired by, `service:bicycle:*=yes/no`, which [bicycle shops](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle) use)
 
<img width="486" alt="screenshot 2017-11-03 10 10 54" src="https://user-images.githubusercontent.com/38784/32377824-50be3af6-c07f-11e7-87f5-fe61058ef9e6.png">

If you are a wiki editor, please feel free to update the wiki to reflect the new tagging - thanks!
