### ISSUE TITLE
Trailing changeset comment spaces are removed

### ISSUE THREAD

**Issue by ethan-nelson** [openstreetmap/iD#4503]
Testing in Firefox 55.0.3 (32b) and Chrome 61.0.3163.100 (64b) on Windows 7:

When feeding a changeset comment to iD via url with a trailing space on the end, that space is truncated. This is mostly a convenience issue: it causes folks adding extra comments to the changeset to combine their first word with the final word of the supplied comment if they aren't paying attention.

MWE:

1 http://www.openstreetmap.org/edit?editor=id#map=17/18.41464/-66.20121&comment=Test%20with%20space%20
2 Make an edit
3 Save
![Screenshot of resulting save changeset comment field](https://user-images.githubusercontent.com/8998918/32409029-9b63fe7c-c171-11e7-8753-1e3fc5d32cb0.PNG)

No javascript errors were logged in the console.

This originally came up with someone adding a trailing space on changeset comments in the new Tasking Manager (https://github.com/hotosm/tasking-manager/issues/914) but it looks like the trailing space is indeed being sent to iD and I was able to replicate it with this MWE outside of the TM3.

**Comment by bhousel** [comment]
I'll see if this is possible to do. The fields code does contain some extra logic to remove trailing spaces.

A simpler alternative might be for the commit.js ui to just always add a trailing space when it prefills the comment (regardless of what got passed in).  The space will get removed anyway when user leaves the field.

**Comment by bhousel** [comment]
@ethan-nelson, I did some digging into the code and found a few things:

https://github.com/openstreetmap/iD/blob/ed332bbccb3a41fd0a270da60ca5e4206f70419c/modules/ui/changeset_editor.js#L58-L69

1. The first time the comment field is created, we select all of the text for the user.. So anybody not paying attention would end up just typing over the whole comment.  This means that adding an extra space for them wouldn't really help much anyway..
2. We also trigger a "blur" event so that the comment can be "cleaned" (this is the part that trims the space) but also checks for hashtags.  We wouldn't want to remove this code just to keep the trailing space around.

So given these two points, they both have good reasons for being there, so I'm kind of leaning towards not supporting a trailing space.  Sorry!

**Comment by ethan-nelson** [comment]
No problem--thanks for checking, Bryan!
