### ISSUE TITLE
Date filter for street level imagery trips

### ISSUE THREAD

**Issue by mvexel** [openstreetmap/iD#4518]
Broken out from #4512 

Density of OSC / Mapillary traces can be prohibitively high in places. A date filter would be nice to focus on newer images. 

Here's how we do it in the OSC JOSM plugin:

![osc-josm-filter](https://user-images.githubusercontent.com/120452/32613518-58151fb0-c528-11e7-8945-b6eac8b7e2de.gif)

**Comment by 1ec5** [comment]
I wonder if iD could automatically filter by date (or by age?) when the traces get too dense, similar to the feature filters that turn on automatically when (for instance) you view an area of the map with a certain number of buildings.

**Comment by davebrny** [comment]
yea some places are like a jackson pollock painting so any type of filter would be a great help. by date, by user or even filtering out certain users

**Comment by joecaruso** [comment]
Are there any update on this?  In my area (Raleigh, NC) there's starting to be a lot of coverage with both Mapillary and OSC, which is great!  The problem is that there are so many trips that iD is starting to become unusable in certain areas.  I now have to open a separate window with the Mapillary website to use as a viewer (where I can do filtering), and then move them in tandem as I make edits.

**Comment by nickplesha** [comment]
Hi, you can try the date filter in this PR: https://github.com/openstreetmap/iD/pull/7847 let me know if you have any feedback or suggestions.

**Comment by quincylvania** [comment]
Done by @nickplesha in #7847, followup in #8076. ✨📸✨

You can now filter by exact dates. I'd like to add another option later to just show the "most recent", whatever that may be, but this is already a big step forward.
