### ISSUE TITLE
add route=light_rail relation 

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4538]
https://wiki.openstreetmap.org/wiki/Tag%3Aroute%3Dlight_rail

**Comment by Nakaner** [comment]
If you add support for `route=light_rail` you should deal with the difference between Public Transport version 2 and its predecessors. PTv2 does not have a route type `light_rail` while its predecessors have such a type.

**Comment by bhousel** [comment]
> PTv2 does not have a route type light_rail while its predecessors have such a type.

That seems to me like more an accidental omission by PTv2, rather than a designed deprecation.  It does say elsewhere in [the PTv2 proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport) that they are just adding new tags alongside the existing established ones, not deprecating anything.

**Comment by Nakaner** [comment]
I don't want to discuss it in full length here but `light_rail=yes`/`route=light_rail` was added to the wiki page after the voting. It is an exemplary case of wiki fiddling.

**Comment by bhousel** [comment]
> I don't want to discuss it in full length here but light_rail=yes/route=light_rail was added to the wiki page after the voting. It is an exemplary case of wiki fiddling.

Maybe so, but I've checked the map in places with light rail, and they are tagged as `route=light_rail`.  So light rail is a real thing.  🤷‍♂️
