### ISSUE TITLE
Keybind ⌘F to focus search

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#4545]
⌘F currently just activates the browser's find dialog, which is not very useful.  Instead it should focus iD's search field:

<img width="387" alt="screenshot 2017-11-19 23 03 19" src="https://user-images.githubusercontent.com/38784/33001757-eba161a0-cd7d-11e7-8b02-b36195bb6200.png">

**Comment by ajashton** [comment]
There are cases where searching the page text is useful, such as long tag lists and help text. I think overriding default browser shortcuts should probably be avoided in general, but I would guess Cmd/ctrl-F specifically is used commonly enough for page navigation than changing behavior could frustrate a lot of people.

**Comment by bhousel** [comment]
> I think overriding default browser shortcuts should probably be avoided in general, but I would guess Cmd/ctrl-F specifically is used commonly enough for page navigation than changing behavior could frustrate a lot of people.

This is a fair point, and it's good to avoid overriding common browser key shortcuts.  We had some discussion on #4081 about this where I agreed that if we are going to override a common shortcut, it should be only if the user is doing the same kind of thing (copy, paste, save).

Anyway, if people really hate this idea, I'm ok with not doing it.

**Comment by 1ec5** [comment]
Personally, I like this idea. Unlike many other Web applications, iD is centered around non-textual content. The browser’s find bar ends up searching for text in iD’s UI, which I think is less intuitive than searching for visible features by name. It’d extremely rare to need to search through help text, but for that the browser still has a Find in Page command in the menu.

**Comment by eehpcm** [comment]
Yes, it's useful to have a shortcut for this.  It's not nice to hijack a frequently-used browser shortcut for it.

As an example, many years of Linux command-line use have instilled upon me that control-U deletes text from the start of the line to the cursor.  Imagine my joy that browers on Linux kowtow to Internet Exploder's convention that control-U means view source.  Guess how many times I've tried to delete the entire text from the URL box or the search box (without having to type morse on the mouse) and ended up viewing source.  Guess how often I've cursed that behaviour.

After decades I've still not _completely_ trained myself out of it when using a browser.  Because it works the way I expect not just on the command line but within just about every other app.  The browser is the exception, and it's a pain in the donkey.  As it stands, control-F does the same thing in all apps and all web pages.  Having it behave differently on just one web page in one app (a browser) is not something I'd advocte.  If it were an obscure browser shortcut that almost nobody ever uses, then maybe.

**Comment by 1ec5** [comment]
I agree that it’s poor form to hijack a browser shortcut for altogether different functionality. As a Firefox user, it certainly bothers me whenever a webpage assumes I’m using Chrome and overrides ⌘K to insert a link instead of focusing the search bar. But this isn’t about hijacking a browser function, it’s about giving ⌘F (Ctrl+F) something meaningful to find.

When the user presses ⌘F, their intent is to find content in the current document. In this case, the document is the map and its contents are map features. ⌘F currently searches through UI text, which isn’t what ⌘F normally does in any application. It isn’t uncommon for Web applications, especially word processors, to override this shortcut for a custom find feature, because the browser’s find function doesn’t have enough context to do anything useful.

**Comment by slhh** [comment]
I agree to override Ctrl-F for a map feature search at least when the map is focused, but it should generate more benefit than just being a replacement for one or two mouse clicks:

- When in mode select the user should be able to use the shortcut to search a map feature to be added to the selection. Currently it is impossible to add features to the selection which needs to be searched.
- When the map is hoovered while pressing the shortcut, we should prefer nearby features to this position in the search results.

Maybe, Ctrl-F can have a different search behavior when the sidebar is focussed, for example searching a field to be added, or searching in the member list of a relation.

**Comment by bhousel** [comment]
> ⌘F currently just activates the browser's find dialog, which is not very useful. Instead it should focus iD's search field:

I did this, and it's ok.  It would be much better if we get up/down arrow working on the preset and feature lists (#4324), but this is a good start.
