### ISSUE TITLE
iD needs to link to OSM feature object

### ISSUE THREAD

**Issue by nyurik** [openstreetmap/iD#4588]
Please add this functionality:  If I select a single object in iD editor, show object's ID (e.g. w5013364) in the sideabar ~~and that ID should be a link to http://www.openstreetmap.org/way/5013364 .~~

**update** Silly me, I found the link at the bottom of the side bar.  I think it would help to show the feature ID, but otherwise this is exactly what I needed.

Thanks!

**Comment by bhousel** [comment]
Additionally: 
* <kbd>⌘ Cmd</kbd> + <kbd>⇧ Shift</kbd> + <kbd>H</kbd> - toggle the History info panel, which contains the OSM id, who last edited it and when, and a link to the history.
* <kbd>⌘ Cmd</kbd> + <kbd>⇧ Shift</kbd> + <kbd>M</kbd> - toggle the Measurement info panel, which contains the OSM id, also info about the geometry, lat/lng coordinates, measurement info

We have traditionally decided against using the limited screen space to show an osm id, because this data is not useful to casual users.  The Info Panels are designed for more advanced users who need to see this information.  Those tools have a distinct look-and-feel, use more advanced keystrokes, and are disabled by default, but discoverable on the <kbd>?</kbd> menu.
