### ISSUE TITLE
Fix date/time format in imagery and history tools

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#4594]
The Esri imagery in my area is much newer than Bing so I used ctrl + shift + B to check its date. It says:

> Vintage: 6/2/2016

I thought it was a bit strange, as it was clearly not February since there is an annual summer fairground in the imagery!

Please can you change this to an unambiguous date format which can be understood by those outside the USA 😉 Preferably ISO 8601, i.e. 2016-06-02, thanks.

**Comment by boothym** [comment]
Also noticed the history tool (ctrl + shift + H) has the same problem:

>Last Edit: 11/29/2017, 10:10:28 PM

Again this should default to ISO 8601, i.e. 2017-11-29, 22:10:28

**Comment by bhousel** [comment]
Oh interesting - I specifically used `toLocaleDateString` expecting that it would just do the right thing based on your browser and operating system:

https://github.com/openstreetmap/iD/blob/5e19c936f0949d6a1e82ff122b661ba0b2512e8e/modules/renderer/background_source.js#L11-L16

Is your operating system or browser locale set to `en-US`?   

This is a tricky thing to get right in a client side JavaScript app, but I think in all modern browsers I can pass the user's locale to `toLocaleDateString` in order to tell it what to do :

![screenshot 2017-12-05 21 00 58](https://user-images.githubusercontent.com/38784/33640611-828cf786-d9ff-11e7-882f-9d564ea7048a.png)

**Comment by boothym** [comment]
I have everything set as en-gb. I've just tested it in Chrome and it works fine - so seems like it's a Firefox problem. 😒 Edge also works with the test below.

https://codepen.io/ssohjiro/pen/BygXox - change one of the options to en-GB and it should give you 13/04/2015. If your language is en-GB and you remove the country code altogether it remains the same in Chrome. But with Firefox it goes back to 4/13/2015.

**Comment by bhousel** [comment]
I've adjusted the date and time formats a little to include the short month (less ambiguous), and I'm now passing the current locale to `toLocaleDateString()`/`toLocaleString()`, rather than just relying on the browser to guess correctly..  I also made some style tweaks so that long strings would wrap and display better.

I think it's good!

### en-US:
<img width="1026" alt="screenshot 2017-12-06 15 20 00" src="https://user-images.githubusercontent.com/38784/33683538-42a87ae2-da99-11e7-94f7-6a25fe55f018.png">

### en-GB:
<img width="1029" alt="screenshot 2017-12-06 15 21 06" src="https://user-images.githubusercontent.com/38784/33683549-4873e88a-da99-11e7-90ac-bcf1f1a38132.png">

### de-DE:
<img width="1027" alt="screenshot 2017-12-06 15 18 58" src="https://user-images.githubusercontent.com/38784/33683554-4d599cdc-da99-11e7-887e-0b3adfb2df17.png">

**Comment by boothym** [comment]
Nice, thanks!
