### ISSUE TITLE
change value of traffic_signals:direction if changing a way's direction

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#4595]
If there is a way which contains nodes which are tagged with direction=forward or direction=backward, the direction value is being changed to the opposite value if you reverse the way's direction in iD. Could it maybe be possible to transfer this practice (to avoid tagging errors) also onto the key traffic_signals:direction with the values forward/backward?

**Comment by bhousel** [comment]
Why do traffic signals use `traffic_signals:direction` instead of just `direction` like all the other tags?   Can't they just use `direction`?   

Either way, we don't support rendering `traffic_signals:direction` currently in iD (see #3115) so I don't think we'll support reversing them either.

**Comment by Nakaner** [comment]
A node with a traffic signal can also have the tags of a tram signal pointing into the other direction. That's why `traffic_signals:direction=*` and `railway:signal:direction=*` make sense. From my point of view, any value which is `left`, `right`, `forward` or `backward` should be reversed if necessary.

Note: There can occur cases when these direction-dependent tags are ambiguous. These cases a rare and for the start a simple fix would be better than no fix.

**Comment by bhousel** [comment]
Oh sorry @Nakaner and @Lukas458 - I realized after writing my response that this has nothing to do with rendering and is actually easy to do. (I really don't know what I was thinking before).

I just extended the child node reversing code to just match `/direction$/`  (any key that ends in `direction`), and added some tests.
