### ISSUE TITLE
Sidebar options remain clicked

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/iD#4597]
![](https://i.glideservers.com/u/jamef9e4b75-95be-4d36-a354-91d46f3e07a7.png)

**Comment by bhousel** [comment]
Yeah I changed this recently - they stay open on purpose.  I think some people would prefer to leave these open (Background, Data, and Help) while they do other things in iD.  (#4575 includes a change so that only one at a time can be activated).

I'm not sure if we will keep it this way or not.  They are easy to close by clicking again or using the appropriate keyboard shortcut.

**Comment by JamesKingdom** [comment]
I kinda like the way it works, It's just slightly confusing that when you open help and then try to use the other ones that nothing happens on screen.

**Comment by JamesKingdom** [comment]
Reading this again, `(#4575 includes a change so that only one at a time can be activated)` - solves my problem. So I will close this.
