### ISSUE TITLE
Can not use keybindings while in non-Latin keyboard layout

### ISSUE THREAD

**Issue by skfd** [openstreetmap/iD#4618]
iD has a typical minor issue -- it requires to switch to English layout to do hotkeying.

Want to create issue before diving into making a pull request.

[We're bind to character input.][1] But we should bind to keyboard key pressed.

I understand that we do it to support lower-case upper-case letters synonyms. But we checking shift key instead.

Could you please suggest what test module should I add test for keybindings i18n?

### How to test
* Turn on Cyrillic or any other non-Latin layout
* press A (which is Ф for Cyrillic layout)
### Expected
* help pane is open
### Actual
* Nothing happened

### Browsers
Chrome 63, E D G E 4 1

### iD version
latest `master` commit

[1]: https://github.com/openstreetmap/iD/blob/015c8918f6ef1a6e2d8467a09d8b3b7359856729/modules/lib/d3.keybinding.js#L61

**Comment by bhousel** [comment]
> We're bind to character input. But we should bind to keyboard key pressed.

It looks like code exists in `d3.keybinding.js` to do both.  We recently switched to `KeyboardEvent.key` because all international keyboards do not put their keys in the same places, making `keyCode` detection (keyboard key pressed aka "scan code"?) inconsistent.  

I actually think all of our targeted browsers support `KeyboardEvent.key` now, and that `keyCode` stuff might just be legacy in our code for PhantomJS or something.

cc @tyrasd - can you advise on this?  My gut is that what @skfd is asking for is impossible, but I don't know really.

**Comment by skfd** [comment]
> We recently switched to `KeyboardEvent.key` because all international keyboards do not put their keys in the same places

Here is the [commit](https://github.com/openstreetmap/iD/pull/3572), but it has no tests or test cases to go through manually. Will try to come up with something.

Will update this issue as I investigate\prototype.

Generally, I would say iD keybinding should behave the same way the other apps do. I know that Microsoft Word or Gmail work the way I expect in my case. But will have to research the case described above.

**Comment by tyrasd** [comment]
Hmm, tricky issue.

I believe #3572 is not really too relevant for this case. It just tackled the issue of inconsistent behavior when working different layouts of all latin keyboards (if the help says you should press the `x` key to achieve something, it should be the key labeled `x` independently of where this key is located on the different layouts).

Here we have a situation where a keyboard may not have an actual `x` key (likely because in the script the character doesn't exist).

My intuition would say that for such situations it might make sense to bind the event behind the `x` key to additional alternative keys for various scripts (e.g. `Ч` for the cyrillic script - note that this character could again potentially be located on different physical keys depending on the actual keyboard layout).

**Comment by bhousel** [comment]
I tested with US and Russian keyboards here:  http://unixpapa.com/js/testkey.html

```
keydown  keyCode=65  (A)   which=65  (A)   charCode=0        
         key=a char=undefined location=0 repeat=false
keypress keyCode=97  (a)   which=97  (a)   charCode=97  (a)  
         key=a char=undefined location=0 repeat=false
keyup    keyCode=65  (A)   which=65  (A)   charCode=0        
         key=a char=undefined location=0 repeat=false
keydown  keyCode=65  (A)   which=65  (A)   charCode=0        
         key=ф char=undefined location=0 repeat=false
keypress keyCode=1092      which=1092      charCode=1092     
         key=ф char=undefined location=0 repeat=false
keyup    keyCode=65  (A)   which=65  (A)   charCode=0        
         key=ф char=undefined location=0 repeat=false
```

It looks like we maybe can improve this. We're currently binding and matching on `keydown`.  So even though `event.key` does not match 'a', we have other information we can fallback to.  

So, looking at this code:
https://github.com/openstreetmap/iD/blob/8720f7e6d7796046d158b3bc4a45fa3d74a1eaa6/modules/lib/d3.keybinding.js#L54-L68

Rather than an if/else, we could just retest all the matches a third time using `event.keyCode` instead of `event.key`.    (I say "third time" because we already test them all twice for unshifted and shifted).

**Comment by bhousel** [comment]
Here is me testing it.. As with anything related to keyboard detection in browsers, this test applies to Chrome 63 on my Mac and nothing else 😬 

![keyboard_test](https://user-images.githubusercontent.com/38784/34166487-09204e08-e4ad-11e7-865f-7ee18e13f8b7.gif)

**Comment by tyrasd** [comment]
> Rather than an if/else, we could just retest all the matches a third time using event.keyCode instead of event.key.

sounds like a good approach to me. :+1:

**Comment by bhousel** [comment]
I believe I was able to fix this, and it seems to work locally with my pop-up Cyrillic keyboard.

Can you confirm by testing in http://preview.ideditor.com/master ?

I would like to write some unit tests for this feature in `d3.keybinding.js` but [happen](https://github.com/tmcw/happen) doesn't support modern DOM3 events or constructing events with the KeyboardEvent constructor.  So we can't currently test the behavior of conditional fallback from `KeyboardEvent.key` to `KeyboardEvent.keyCode`.

**Comment by skfd** [comment]
@bhousel I played around with it and it works indeed. Thank you!
I got stuck on triggering events through happen too. Maybe raw events without the wrapper could be used here? Will try that approach.

**Comment by bhousel** [comment]
> I got stuck on triggering events through happen too. Maybe raw events without the wrapper could be used here? Will try that approach.

For testing iD, we could probably accomplish the same thing with [d3.selection#dispatch](https://github.com/d3/d3-selection#selection_dispatch), which I believe was added to D3 more recently then when @tmcw built `happen` for this purpose.  I'll open an issue.

**Comment by skfd** [comment]
This was working for some time, but now is broken again. Did not figure out the tests, sorry, just noticed while using.

 @bhousel Can we re-open the issue, please? Or it's ok to create new one?
