### ISSUE TITLE
Closed highway way wrongly displayed as area in combination with junction=circular

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4637]
![screen shot 2017-12-27 at 22 10 45](https://user-images.githubusercontent.com/14875493/34424426-b6e828b2-ec23-11e7-8d3a-8ffd69c073db.png)

**Comment by bhousel** [comment]
Thanks for reporting!  It renders this way because `junction=yes` is an area preset (these are for named junctions popular in Korea and Japan).  We will need to add some special code to make [these new `junction=` tags](https://wiki.openstreetmap.org/wiki/Key:junction#For_usage_together_with_highway.3D.2A_key) render as lines and have oneway semantics like `junction=roundabout`.

H/T @planemad who just told me about this tag about 2 weeks ago..

**Comment by 1ec5** [comment]
Note that, beyond `roundabout` and `yes`, many of the common [`junction` values](https://taginfo.openstreetmap.org/keys/junction#values) are used on either a group of individual ways or [on relations](https://wiki.openstreetmap.org/wiki/Proposed_features/Junction), so they don’t necessarily carry one-way semantics.

**Comment by bhousel** [comment]
> Note that, beyond roundabout and yes, many of the common junction values are used on either a group of individual ways or on relations, so they don’t necessarily carry one-way semantics.

Currently in iD `junction=roundabout` is the only `junction` tag that implies oneway.
(the "implies oneway" list is [here](https://github.com/openstreetmap/iD/blob/master/modules/osm/tags.js#L11))

**Comment by SelfishSeahorse** [comment]
Thank you!
