### ISSUE TITLE
PTv2 station adds building=yes

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#4639]
When applying a PTv2 station to an area, the tag `building=yes` is added. I think this is wrong.

AFAIR I have not once drawn a station outline that perfectly aligned with a building. Frequently, I encounter outdoor bus stations – like [this one](https://www.openstreetmap.org/way/78306275), currently mapped with PTv1. If #4591 makes it through, wouldn't this introduce great errors in the map?

**Comment by bhousel** [comment]
> When applying a PTv2 station to an area, the tag building=yes is added. I think this is wrong.

This is not a new behavior in iD introduced by the PTv2 stuff in #4585 

Before:  
- User draws an area and chooses the "Bus Station" preset.. 
- Tags assigned are `amenity=bus_station` + `building=yes`
- Sidebar shows a field to remove the `building` tag, in case what they really drew was a property.

Now:  
- User draws an area and chooses the "Bus Station" preset.. 
- Tags assigned are `amenity=bus_station` + `building=yes` + `public_transport=station` + `bus=yes`
- Sidebar still shows a field to remove the `building` tag, in case what they really drew was a property.

So - nothing has changed except that iD adds some new tags to what it already did.  Users can still map their stations as property outlines without the building tag, or as building outlines with the building tag (still the default).

> If #4591 makes it through, wouldn't this introduce great errors in the map?

#4591 is about what to do with existing PTv1 stations and other things that the user comes across while editing.  Do we add the new PTv2 tags, and if so what would that look like?

**Comment by M1dgard** [comment]
Ah, wow, I never noticed that it added a building tag. I would make the point that the building property should default to be empty, not `yes`.

In any case this is still relevant to #4591, @bhousel:

* pre-existing bus station in open air
* user converts to PTv2 → this adds the PT tags, and presumably also `building=yes`
* user doesn't see that `building=yes` was added (estimated 99% of the times)
* wrong data introduced (the "Messing with other people's work" I was talking about in #4591 :wink:)

Unless of course you've already thought of this and set up the appropriate guards, in which case you may disregard this comment.

**Comment by bhousel** [comment]
> user converts to PTv2 → this adds the PT tags, and presumably also building=yes

No, the upgrade wouldn't add `building=yes`.  (That tag is not really part of the preset - iD will only add it when you create a new station because there is a "building" field in the sidebar, and for most features that field defaults to the value "yes")

> Ah, wow, I never noticed that it added a building tag. I would make the point that the building property should default to be empty, not yes.

Nah let's leave as is.  I think most stations (train, bus, etc) have some kind of roof over them, and in fact the [reference page for `amenity=bus_station`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbus_station) shows one like that.

There _are_ a few presets where we show a "building" field but don't default it to "yes" - stuff like `leisure=ice_rink`, `power=substation`, `shop=storage_rental`.

To your point about _"I never noticed that it added a building tag."_ ... This comes up occasionally where I hear from someone who is surprised by iD's behavior, and I would like to know more about this.  How we render buildings in iD is a consistent and deliberate design choice.  They are all drawn with a single color that is used only for buildings and nothing else.  

Put another way - I've spent time on this and tried to make it nearly impossible for users to get confused about what is and what is not a building. Seriously asking: _is there a thing I can do to iD to improve this?_

For example, one of these features is missing its building tag - does it jump out at you? (it should):

<img width="805" alt="screenshot 2017-12-30 22 07 02" src="https://user-images.githubusercontent.com/38784/34458816-e0e05a1e-edad-11e7-9bb1-0b2799a9e2c1.png">

**Comment by 1ec5** [comment]
The reddish color on the map is a good choice, but it isn’t as effective in places with few buildings mapped. Less experienced mappers haven’t internalized that a reddish color on the map means the feature is necessarily tagged as a building.

This used to be a big problem with schools and hospitals before separate presets were broken out for “School Grounds” and “School Building” etc. (#2799). I think the preset’s name addressed the problem more than anything. The problem still affects presets that haven’t been broken out this way. For example, the other day, I encountered (and retagged) an `amenity=fire_station` `building=yes` [covering the entire grounds of a fire station](http://www.openstreetmap.org/way/401078811/history).

Perhaps anything that adds `building=yes` should specifically call out that fact in the preset name, even though it would lead to some awkward names like “Bus Station / Terminal Building”.

**Comment by bhousel** [comment]
> Perhaps anything that adds building=yes should specifically call out that fact in the preset name, even though it would lead to some awkward names like “Bus Station / Terminal Building”.

We can't (easily) do that because the building tag is not part of the preset - it's assigned by the building field. The preset code doesn't really know whether the feature will end up with a building tag or not.
