### ISSUE TITLE
Remove building=yes from shop=garden_centre preset

### ISSUE THREAD

**Issue by lakedistrictOSM** [openstreetmap/iD#4648]
In the UK at least, garden centres mainly consist of outside areas, sometimes with just a small kiosk for the checkout. [Taginfo suggests](https://taginfo.openstreetmap.org/tags/shop=garden_centre#combinations) that only 28% of garden centres are tagged with `building=yes`. Can we remove `building=yes` from the `shop=garden_centre` preset?

**Comment by bhousel** [comment]
OSM Wiki says to map it around the "building outline", so that's what we recommend.  There is probably a structure that people can go inside.  We generally map shops and amenities as buildings in osm, not property boundaries (Except in cases like schools and hospitals - for these exceptions we put the word "Grounds" in the preset).

<img width="600" alt="screenshot 2018-01-02 12 57 31" src="https://user-images.githubusercontent.com/38784/34494052-9766010c-efbc-11e7-813b-058bc7bce093.png">

**Comment by lakedistrictOSM** [comment]
I believe that the wiki was incorrect. It has now been updated by another mapper to read:
>Set a node or draw as an area along the shop outline. Add the tag shop=garden_centre. Add name using name=* or use noname=yes to mark that shop has no name.

Can we reopen this and get some more input from other people?

**Comment by bhousel** [comment]
62% of `shop=garden_centre` tagged as ways also have a `building=*` tag [according to taginfo](https://taginfo.openstreetmap.org/tags/?key=shop&value=garden_centre&filter=ways#combinations).

I'd prefer if there were some discussion on the tagging@ list or at least on the wiki before a change like this.  Right now it just looks like one person changed the wiki to suit their opinion without telling anyone, and without numbers to support the change.
