### ISSUE TITLE
Removing area's tags turns it into line

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/iD#4663]
**How to reproduce:**
1. Select a tagged area.
2. In the All Tags section, click the bin for all tags.

**Expected behaviour:** The way is still treated like an area.

**Actual behaviour:** The way is treated like a line.

**Users may be affected:**
* Non OSM experts fiddling with the "All tags" section.
* OSM expert wanted to apply a preset cleanly to see what it does exactly.

Moreover, the line can't be converted back into an area in an obvious way (= #1828).

![Screencast illustrating the issue](https://user-images.githubusercontent.com/4283376/34654719-f1a7e27e-f3ff-11e7-83da-fe9ebb8e7619.gif)

**Comment by M1dgard** [comment]
**Proposed fix:**

Add an explicit `area=yes` when removing the last tag.

If the user then clicks the bin for that tag too, you could do one of three things:
* just let them (converted to line, user should figure out they can change back to area by adding `area=yes`)
* don't let them (force presence of `area=yes`, this would make it proper impossible to convert an area to line by intention, I wouldn't recommend this)
* display a warning with confirmation ("Removing the tag area=yes will change this area into a line. Do you want to do that?")

**Comment by 1ec5** [comment]
> just let them (converted to line, user should figure out they can change back to area by adding `area=yes`)

This would be a pretty intentional action, so I think it would be OK to just let the user convert the area to a line at this point. My hack in https://github.com/openstreetmap/iD/issues/1828#issuecomment-312735038 depends on that, but there are other use cases for converting areas to lines. For example, the user may’ve inadvertently drawn a `highway=pedestrian` as an area instead of a line, and it would be annoying to have to redraw it.

**Comment by bhousel** [comment]
Yes deleting all the tags from an area will turn it into a line.  This is the intentional behavior.. It's just how OSM works (There is no polygon datatype, so linear features can only be polygons if they are tagged with an explicit `area=yes` or some other tag that implies polygon semantics).

Removing the area-ish tag is also the only way currently to convert an area to a line (which is useful, as @1ec5 mentioned).

> Moreover, the line can't be converted back into an area in an obvious way

The user can undo....

Anyway I'm sorry, but I have to close this.. We really can't change how this works in the current version of OSM, even though it probably an unexpected behavior.

**Comment by M1dgard** [comment]
@bhousel to re-iterate, because I've think you've missed it:

# Add `area=yes` when removing the last area-matching tag on an area.

**Comment by bhousel** [comment]
@M1dgard I did see that suggestion, but it would add more complexity to the raw tag editor than I'm comfortable with.  (I should remove "impossible" from the wontfix label.)  

It would be like, if the user removes a `building=yes` tag, we need to add an `area=yes` tag (which they might not want).  I think it's just safer for me to assume that people using the raw tag editor know what tags they want, and not introduce logic to override their decisions.

**Comment by M1dgard** [comment]
Okido. No prob.
