### ISSUE TITLE
Default snap joining of nodes

### ISSUE THREAD

**Issue by DaveF63** [openstreetmap/iD#4692]
https://www.openstreetmap.org/changeset/55426791#map=18/51.38145/-2.37049

This is a common occurrence with new users in iD. 
Why is it the default action to join nodes without pressing a shortcut key? 
Wouldn't it be better to have users press the Alt key *to* snap nodes together?

**Comment by bhousel** [comment]
> Why is it the default action to join nodes without pressing a shortcut key?

Because most things should be joined to something (e.g. roads)

> Wouldn't it be better to have users press the Alt key to snap nodes together?

No, then we'd see a lot of new users not joining things that should be joined.

I say this a lot but - we train users now to know how to snap or not snap in the tutorial, and we train them how to undo.  If you see users snapping things wrongly, just revert their work and kindly tell them why, and remind them to take the tutorial.

**Comment by DaveF63** [comment]
Ah, the pompous arrogance of the immediate close.
So prevalent within OSM, yet programmers are bemused why no one wants to join them.

> I say this a lot but...
Yet no matter how many time you say it it _still_ occurs.

>  just revert their work
I can not emphasis how annoyed I am with this typical response from the repeatedly arrogant @bhousel 
It is *not* my, or anybody else's responsibility to revert the iD induced cock-ups.  Sort out your own mess.

I wish to emphasis how _extremely_ polite I've been in this reply.

**Comment by 1ec5** [comment]
@DaveF63, I understand that you’re frustrated the issue was closed quickly, but please try to keep the discussion civil. This issue was closed as a reflection of the fact that snapping to nearby nodes is a common feature of OSM editors – Potlatch and (if I understand correctly) JOSM also have similar behavior, even if the snapping tolerance may differ. Changing the behavior at this point would be disruptive to the OSM community, as users expecting the current behavior might inadvertently introduce unroutable roads.

As to the changeset above, it seems to me that the main problem isn’t the snapping behavior. Rather, it’s that the user inadvertently dragged this node clear across the window. Other mainstream editors don’t do much to prevent this kind of mess, either, although I’m sure alarm bells would’ve lit up inside JOSM’s validator. What could iD do to proactively prevent mistakes like this? Perhaps a suggestion along the lines of the “nope targets” at the bottom of https://github.com/openstreetmap/iD/pull/4602#issuecomment-353705419 would spark some interesting discussion.

**Comment by DaveF63** [comment]
As I've said, I've been *extremely* civil. This is not the first time I (or others) have received an 'I can't be bothered to sort out my problems, you do it' from him.

Your claim other editors induced similar crap is not true. It is purely down to the inept programming of iD  

> Changing the behavior at this point would be disruptive to the OSM community,

Absolute rubbish. "behaviours" change continuously with OSM, on multiple platforms. 

> Other mainstream editors don’t do much to prevent this kind of mess,

Then how comes it only occurs in iD?
I agree snapping may not be the the sole reason iD created this error, but to tell other mappers to correct it as @bhousel is too lazy is arrogance in the extreme.

I wish to emphasis (again) how extremely polite I've been in this reply.

**Comment by boothym** [comment]
Hi @DaveF63, 

First of all, I wish to thank you for being so polite - I know it's a struggle for you, so I for one appreciate the effort you've put into these posts.

Maybe you have a different version of JOSM or different settings to me, but in my version (13625), if I draw or continue a line then the default behaviour is to snap to any line or node that is already on the map. 

The difference to iD is that dragging nodes across the map does not snap to anything else, and there is more validation when uploading. Though in JOSM you can move lines/areas on the map by just dragging, instead of having to press M in iD (however there is a warning when moving >20 objects).

There's a couple of things that could improve iD in these situations when checking for errors:
- #4173 not allow certain lines to connect to each other, e.g. paths to power lines
- validation for crossing highways (although like JOSM, these warnings could be ignored)
- a warning when moving more than, for example, 20 objects

**Comment by mmd-osm** [comment]
Could it be that snapping is not the real issue here? Assuming the mapper was just panning the aerial imagery looking for the right place to map, and was just unlucky enough to drag a node around instead (probably without even noticing!). The snapping part doesn't really change anything to the story.

While JOSM uses a right mouse click for panning, in iD it's just a left mouse click for both panning and moving nodes around. So yes, this is by design. Educating users to be aware of such issues and use "undo" where appropriate would do, right?

**Comment by simonpoole** [comment]
I've fixed the data problem, and have one observation  (essentially everything else has already been said) the node in question wasn't an end node of either of the two ways it was a member of. 

I can understand the logic of auto joining end nodes, I'm not so sure about other random nodes in a way, Wouldn't it likely be better to make the behaviour dependent on what is being dragged (I know that means that behaviour wouldn't be symmetric, but I doubt that such fine points bother the typical user).

**Comment by althio** [comment]
> Could it be that snapping is not the real issue here? Assuming the mapper was just panning the aerial imagery looking for the right place to map, and was just unlucky enough to drag a node around instead (probably without even noticing!). The snapping part doesn't really change anything to the story.

Indeed. it is all about pan the map & accidental drag a node.

It is a hard design problem, much thought already.
https://github.com/openstreetmap/iD/pull/1079 ; https://github.com/openstreetmap/iD/issues/1351 ; https://github.com/openstreetmap/iD/issues/3824#issuecomment-282421687 ; https://github.com/openstreetmap/iD/issues/3824#issuecomment-297231279 ; https://github.com/openstreetmap/iD/issues/3824#issuecomment-309420689 ; and maybe more...

_off-topic:_
The rest is just abuse.
This is plain wrong (along with some other disrespectful statements):
> It is not my, or anybody else's responsibility to revert the iD induced cock-ups. Sort out your own mess.

We are a community, behind the OpenStreetMap project, and it is everybody's responsibility to help the newcomers.
