### ISSUE TITLE
Preclude combination Way (no waterway) and Intermittent

### ISSUE THREAD

**Issue by jjiglesiasg** [openstreetmap/iD#4716]
We have a problem in Bolivia because several ford areas has been marked as intermittent as well, and trying navigation either OSM of by renders all these ways are not routeables.

Is understood that intermittent tag should be only applied to waterways. Is there any way to do not allow way (road) and intermittent combination

Thanks

JJ

**Comment by bhousel** [comment]
I don't think iD has a preset that would let users add the tags in this combination (`highway=*` + `intermittent=*`)  Can you ask the user who added it what they were trying to do?  Or link me to the feature that shows up this way?

If they were adding tags manually, a user can enter in whatever tags they want to.  I'm not sure if you are requesting us to add logic to the raw tag editor, but I don't really plan to do that, since the rules for what tags are allowed to appear with what other tags are infinite.

**Comment by jjiglesiasg** [comment]
I guess the idea of the combination way+intermittent was to depict Fords, but the waterways are the intermittent, not the ways as such, I manually deleted more than a thousand of these combinations in my Country but seems to remain a lot of them in Peru, Chile and Argentina.
My request was focused to add logic that preclude to have the key combination. One thing is to have a seasonal road, like in floods, monsoon or snow season and another is to have an intermittent roads.
Thanks

**Comment by bhousel** [comment]
Thanks for clarifying @jjiglesiasg - closing here, since I think the best place to add logic like that would be a dedicated QA tool.
