### ISSUE TITLE
oneway:yes is implied for motorway_link

### ISSUE THREAD

**Issue by UncleGene** [openstreetmap/iD#4727]
According to https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_link, there is no implied value for it; and as oneway is a restriction, absence of the value should mean no restriction

**Comment by bhousel** [comment]
Is the issue here that iD treats `highway=motorway_link` without a `oneway` tag as if it had `oneway=yes`, and it should instead treat it as `oneway=no`?  (see "Assumed to be Yes" in the screenshot below)

When creating motorway_link, iD always adds a `oneway` tag - the question here is what to do if the way doesn't have a tag.

<img width="586" alt="screenshot 2018-01-22 14 34 38" src="https://user-images.githubusercontent.com/38784/35240427-6e0abeea-ff81-11e7-98ee-6d291c23c3ce.png">

**Comment by UncleGene** [comment]
Yes.  The issue is with the ones without oneway tag. At this moment iD confuses the user:
- iD shows the way as oneway, so I see no incentive to fix it
- OSRM (or any other routing engine) defaults to oneway:no, producing wrong routes

**Comment by bhousel** [comment]
Gotcha, thanks for clarifying, I'll change what iD does 👍
