### ISSUE TITLE
Information panels hidden by right flyout

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#4733]
At the moment if you press ctrl + shift + B to show the background panel, then press B to get the background list - the background panel is hidden behind the flyout. This is awkward if you want to switch between multiple backgrounds to see which has a newer date.

How about, either: offset the panels to the left when the background/map data is open OR align all the information panels to the left, so they don't interfere with the right flyout at all?

**Comment by bhousel** [comment]
Good suggestions 👍

**Comment by manfredbrandl** [comment]
I use iD with a monitor in portrait mode. I hope it is possible to have non-overlapping panels for this rare use.

**Comment by bhousel** [comment]
It should be possible.. Right now the info panels are in their own flexbox div that doesn’t know about the panes. We would need to group that container into another parent flexbox container with the panes so they can move out of the way.

**Comment by quincylvania** [comment]
I did this! It was harder than expected since the panes were absolutely positioned. Unfortunately I had to remove the slide animation when switching between different panes but I don't think this is a major loss.

![flex demo](https://user-images.githubusercontent.com/2046746/56157663-e6879100-5f74-11e9-86a1-ccc72b7d8a09.gif)

**Comment by bhousel** [comment]
looks great!  👏

**Comment by boothym** [comment]
Nice, thanks.
