### ISSUE TITLE
Tag editor: Value dropdown can be confusing

### ISSUE THREAD

**Issue by slhh** [openstreetmap/iD#4761]
The autocompletion dropdown of the value field can be confusing:
![grafik](https://user-images.githubusercontent.com/13684947/35653489-e101ec84-06e8-11e8-8cc5-d4a333bbe63e.png)
E.g. the sceenshot looks like segregrated were "yes", but in fact it is "no".

The style difference of the value field and the dropdown menue is too small, at least if no scrollbar is shown. When actively typing a value, this is unlikely a real issue, but when just clicking in a value field, it can be confusing.

Maybe, we can reduce the height of the dropdown items to approximately 80%.

**Comment by manfredbrandl** [comment]
Reducing the height of the dropdown would not look as nice as now. Maybe inserting some blanks on the left side of the dropdown values would be enough. Maybe we could make the change the drop-down icon blank for the selected field also. Together with the light blue colour this might be enough.

**Comment by bhousel** [comment]
I made some improvements in 013253e:

This improves the usability of all the comboboxes, but it especially works great when a combobox appears over other rows of fields (e.g. raw tag editor).

1. shrink size on left/right to provide more separation from content beneath
2. adjust box shadow for slightly more visibility
3. shrink size of first combobox row by one pixel, so that the combobox options will never perfectly line up with rows that they cover (sneaky, but nice)

<img width="363" alt="screenshot 2018-02-11 22 23 20" src="https://user-images.githubusercontent.com/38784/36082814-e94a0742-0f7a-11e8-900d-f7fc176aa9dc.png">
