### ISSUE TITLE
Indoor Mapping System saving errors

### ISSUE THREAD

**Issue by ibuddy66** [openstreetmap/iD#4772]
Hello, 
     http://projets.pavie.info/id-indoor/ is functional until you go to save your work and then a pop up comes up but remains blank instead of doing anything at all.  There is also no way to sign in anymore with OSM.  

![screenshot 2018-02-04 at 11 18 16 pm](https://user-images.githubusercontent.com/36145958/35788193-c2f049e0-0a01-11e8-9aa2-af51f7b16715.png)

**Comment by bhousel** [comment]
Thanks for reporting - it probably needs to be `https:` now.. Closing here since I'm 99% sure that's the issue.

@zbycz is this your fork?  If so maybe I can help update it to iD v2.x?

**Comment by zbycz** [comment]
Hi, this is not my "fork", but @PanierAvide's.

Though, i would like to update my https://github.com/openstreetmap/iD/pull/3097 to iDv2.x in near future :)

**Comment by PanierAvide** [comment]
Present ! The fork is hosted here : https://git.framasoft.org/PanierAvide/iD-indoor
But instead of spending time on updating it, it would be better to work on a simple level selector for the main iD editor ;-) Also, JOSM now has one simple level selector by default, so it makes sense to have this in iD.
