### ISSUE TITLE
Selecting "Zebra Crossing" for a node tags crossing:zebra

### ISSUE THREAD

**Issue by mikelortega** [openstreetmap/iD#4788]
![image](https://user-images.githubusercontent.com/3043173/36078464-f72c7420-0f76-11e8-8b33-ad24646019f5.png)

According to [this](https://wiki.openstreetmap.org/wiki/Approved_features/Road_crossings) or the [crossing tag specification](https://wiki.openstreetmap.org/wiki/Key:crossing) the tag should be **crossing_ref:zebra**

**crossing:** should be **traffic_signals**, **no** or **uncontrolled** (the default).

**Comment by bhousel** [comment]
Sorry for not writing up a FAQ entry about this yet.
It comes up for discussion often.. The tl;dr is that
 
- I picked the most reasonable tag I could at the time, based on taginfo usage (`zebra` was 3rd most popular, behind `uncontrolled` and `traffic_signals` - I think this is still true)
- People have changed the osm wiki to promote `crossing_ref` - the wiki unfortunately does not match actual tag usage in this case.  Someone should fix the wiki.  (I don't make wiki edits on tag pages).
- Nobody who works with pedestrian data likes `crossing_ref`.. (because, it's not a `ref`, it doesn't solve an actual problem, and it's not actually widely used)

So I'm not changing the crosswalk preset, sorry.  It still uses the best tag we have in OSM to describe a crosswalk.

see also, 
#4519 and
https://github.com/openstreetmap/iD/issues/4316#issuecomment-327793565

**Comment by bhousel** [comment]
I've decided I'm tired of hearing people complain about `crossing=zebra` so going forward iD will support `crossing=marked` and `crossing=unmarked`.   

`crossing=zebra` is still supported as a legacy, unsearchable preset, so things will still look the same.

This changed in 1ffca3ce8

**Comment by bhousel** [comment]
Oh, they also still have the normal and "raised" variants too.  
"raised" is the same, but it just also adds the tag `"traffic_calming": "table"`

<img width="393" alt="screenshot 2018-10-02 17 08 00" src="https://user-images.githubusercontent.com/38784/46377113-c55cf400-c665-11e8-8c5d-21354af9fd3b.png">
