### ISSUE TITLE
Add phone and website fields to more presets

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/iD#4816]
`phone` and `website` are two of the most important information to someone that is searching for a place or using a map app, but they are not a default field in a large number of presets. I think all shops / education / food related presets should have it as default to stimulate people and make it faster to add phones and website values. I can do this job if you agree.

**Comment by manfredbrandl** [comment]
Contact Information is important, but there are already many default fields for some object types (e.g. restaurant). It's up to @bhousel and others to decide about pull requests. Please read https://github.com/openstreetmap/iD/blob/master/data/presets/README.md anyway.

**Comment by willemarcel** [comment]
@manfredbrandl Sure we have some exceptions, but, for example, the restaurant preset has a `capacity` field that is too difficult to survey and less important. Other example: the cafe preset has a wifi essid field.

**Comment by manfredbrandl** [comment]
@willemarcel Please make a pull request for adding phone and website for restaurants (or some other feature type), put the fields in suitable order and wait if @bhousel or someonelse merges it.

**Comment by bhousel** [comment]
Hmm no, this slipped off my radar over the weekend (there was a _lot_ of activity on other issues, and I get an email for every single thing).  Please don't send a PR for this.   

I'd really prefer not to default display "Phone" and "Website" fields on all the presets.  I think we already show too many fields (I agree that things like "Capacity" and "Wifi SSID" are probably unnecessary).  I sometimes think we should default hide "Address" and "Operator" too.  

The interface for adding more fields is pretty good, but users won't know to use it if they need to scroll past a bunch of unimportant and empty fields to see it.  (We do train people in the walkthrough to use this).

I wonder if it would make more sense to set up the presets up so that we show only the top 4 or 5 fields and then push all the rest of them into the "Add field" dropdown.  

Or create an explicit "Add field" list for every preset instead of relying on "universal" presets (which are honestly not that universal - users shouldn't put wheelchair access on an admin boundary, or a phone number on a traffic signal).

Let's discuss a bit instead of just adding more fields under the rationale that "other less important fields are already shown".

**Comment by manfredbrandl** [comment]
May i suggest, that the object editor shows "Default fields" and "More fields" instead of "All fields" and have "More fields" collapsed first and users can expand them like they can now with "All tags" and "All relations". That would make it easier than selecting fields from a list. Now it looks like:
![image](https://user-images.githubusercontent.com/5360273/36386798-470a820e-1597-11e8-8f22-0a2b55d1b623.png)

**Comment by willemarcel** [comment]
> Or create an explicit "Add field" list for every preset instead of relying on "universal" presets

I really like this idea!

**Comment by manfredbrandl** [comment]
My idea of more fields is just another view on the "add fields list". Being able to add fields-content with as few clicks as possible and seeing many options together is a priority, that's why I would prefer "more fields" with "add fields from specific list" in the end.

**Comment by 1ec5** [comment]
> Or create an explicit "Add field" list for every preset instead of relying on "universal" presets

#4871

**Comment by bhousel** [comment]
Yeah this is moved to #4871 
closing here
