### ISSUE TITLE
Please remove railway=platform from Tram Stop / Platform preset when used as node

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#4820]
... because at many tram stops there is no platform, just a sidewalk or not even that.

**Comment by bhousel** [comment]
This is still the appropriate tag to use even if the tram just stops at a sign or any other random place.
See https://wiki.openstreetmap.org/wiki/Public_transport#Trams

> platforms: `public_transport=platform` + `railway=platform` If the platform is just a pole with a sign and the tram stops on the road without a physical platform, use a single node to map the "platform".

That's why for all the the public transport presets, the caption says "Stop / Platform".  Because it can mean anything.

**Comment by SelfishSeahorse** [comment]
Sorry, I wasn't aware of that. I thought that only `public_transport=platform` is fine for nodes, but `railway=platform` is not. Apparently, the wiki is contradictory in this regard, because according to <https://wiki.openstreetmap.org/wiki/Tag:railway%3Dplatform>, `railway=platform` should not be used on nodes ...

I'll write an e-mail to the tagging list – tagging a tram stop with `railway=platform` where there is no platform seems wrong to me.

**Comment by bhousel** [comment]
No problem, we can definitely split the preset into a node preset and a way preset, if it turns out that it's really wrong for `railway=platform` to be tagged on a node.

I even found an old `railway=tram_stop` node while researching this issue 😆 
https://www.openstreetmap.org/node/360504333/history
Didn't know that was a thing...
