### ISSUE TITLE
Unchecked 'No' box for car parking attributes like Park and Ride

### ISSUE THREAD

**Issue by thomas-hervey** [openstreetmap/iD#4842]
I am not sure if this is intentional or not, but when toggling through a _yes, no, unknown_ attribute like **Park and Ride** under the Car Parking feature, the 'no' option saves but isn't checked. If this is a bug, it seems a quick fix.

This was found while using Firefox 58.0.2 (64-bit) on OSX High Sierra.

![no_check](https://user-images.githubusercontent.com/1840672/36864067-71041c68-1d40-11e8-8ea6-09d2ac2bc425.gif)

**Comment by eehpcm** [comment]
I don't think it means what you think it means. :)

There is a - and a textual explanation that it means "unknown."

There is a check mark and a textual explanation that it means "yes."

There is an absence of a check mark and a textual explanation that it means "no."

To make the interface work the way you're expecting would require three radio buttons (so only one can be selected) labelled "unknown," "yes," and "no."

The wording is an explanation of the icon, not a label for the icon.

What I'd find more useful is if it defaulted to "no" for both park and ride and for supervised, because none of the car parks in my town have those attributes.

**Comment by thomas-hervey** [comment]
@eehpcm, your explanation makes more sense. I will close this issue but feel free to reopen it if you'd like to see a defaulted "no" as a new feature.
