### ISSUE TITLE
Weird results when inspecting certain turn restrictions

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#4869]
I was just testing the new turn restriction editing feature when I noticed a very strange result in the inspection window.
![strange turn restricition image](https://user-images.githubusercontent.com/31667811/37241777-2cbbe5ec-245f-11e8-9033-511c24a1a82c.png)
The responsible node is https://www.openstreetmap.org/node/4996747168 but neighbouring connection nodes also create such results. Is this an issue from the mapping side or from the editor?

**Comment by bhousel** [comment]
Probably an issue in the editor, but I'll check it - thanks for reporting!

**Comment by bhousel** [comment]
The weird rendering was caused by some code that tried to extend the length of short ways.  It wasn't doing a very good job, so I just removed the code and now the ways render as-is.   (@slhh - [you were right](https://github.com/openstreetmap/iD/pull/4768#issuecomment-364670722) 😄)

<img width="964" alt="screenshot 2018-03-10 17 55 33" src="https://user-images.githubusercontent.com/38784/37247639-43e9cb08-248c-11e8-9517-40ed378cf792.png">
