### ISSUE TITLE
missing some fields for railway preset

### ISSUE THREAD

**Issue by abdeldjalil09** [openstreetmap/iD#4919]
https://wiki.openstreetmap.org/wiki/Tag:railway%3Drail
[usage=](https://wiki.openstreetmap.org/wiki/Key:usage)#
[frequency=](https://wiki.openstreetmap.org/wiki/Key:frequency)# (with electrified=contact_line/rail)
[voltage=](https://wiki.openstreetmap.org/wiki/Key:voltage)# (with electrified=contact_line/rail)

**Comment by boothym** [comment]
Plus voltage when selecting electrified=contact_line/rail in the dropdown and also frequency for electrified=contact_line

**Comment by abdeldjalil09** [comment]
> Also frequency and voltage fields should appear when selecting electrified=contact_line/rail in the dropdown

Thanks for more information

**Comment by bhousel** [comment]
> Also frequency and voltage fields should appear when selecting electrified=contact_line/rail in the dropdown

We don't currently support having fields appear and disappear depending on values entered

(Except for certain cases like the structure `bridge=*`/`tunnel=*`/etc field, because those are popular and worth adding the custom code to do it).

**Comment by boothym** [comment]
Is there a lot of work involved in adding the custom code for electrification?

**Comment by bhousel** [comment]
> Is there a lot of work involved in adding the custom code for electrification?

It would not be a lot of work to have the fields show up all the time and I think it's ok to expect the user to know whether to use them.

**Comment by quincylvania** [comment]
> Also frequency and voltage fields should appear when selecting electrified=contact_line/rail in the dropdown

This is now possible with #5583. I did it in 2804ef35fe9760a94eb8b8ff925a2407786288df. Enjoy!

**Comment by boothym** [comment]
Thanks - is it live in the preview to try?

**Comment by quincylvania** [comment]
Yep! Since Frequency and Voltage aren't high priority I moved them to the "Add fields:" section. So first pick and Electrification value and then use the dropdown. If there are pre-existing values then the fields will appear regardless of the `electrified` value. 

http://preview.ideditor.com/master/#background=Bing&disable_features=boundaries&id=w43344423&map=17.73/39.95727/-75.18366

**Comment by boothym** [comment]
Hmm that's a bit of a regression to me. If someone sets a railway to electrified=contact_line or rail then they should immediately be shown the frequency and voltage fields below the electrified field (just like if you select "tunnel" you get more options). 

Though if were are considering low priority thing then how about removing the ford option from the structure field! :)

**Comment by bhousel** [comment]
> Though if were are considering low priority thing then how about removing the ford option from the structure field! :)

Just because you don't use it doesn't mean we need to make someone else unhappy by removing it.

**Comment by quincylvania** [comment]
> Hmm that's a bit of a regression to me. If someone sets a railway to electrified=contact_line or rail then they should immediately be shown the frequency and voltage fields below the electrified field (just like if you select "tunnel" you get more options).

It is an extra step to add these fields but I hope we can give the change a chance. I'm imaging a casual mapper identifying overhead contact lines in imagery and setting that Electrification value. Then two new fields immediately pop up that require research or domain-specific knowledge? Not the best experience.

**Comment by slhh** [comment]
> I'm imaging a casual mapper identifying overhead contact lines in imagery and setting that Electrification value. Then two new fields immediately pop up that require research or domain-specific knowledge?

A mapper who is mapping based on imagery can't  expect to be able to fill in all fields. This also applies to tracktype, maxspeed etc.
Railways are typically mapped by someone who is particularly interested in railways, and who likely knows which value to use.
Starting to map a railway network from scratch is rare, and in case of minor edits the values can likely be copied from nearby features with a little knowledge of the network structure..

**Comment by quincylvania** [comment]
@slhh I came up with #5734 as a potential solution for this and similar advanced-mapping scenarios.

**Comment by boothym** [comment]
(sorry for the delay)

@bhousel think you've misunderstood. I was referring to the **ford** option only in combination with a railway line - which will be a very uncommon situation on the ground! :)

@quincylvania the number of casual mappers who can identify overhead line equipment (or third rail) from aerial imagery *and* would be put off by two extra fields appearing is probably quite small. I'd say it's more likely that they would try to find that information out, similar to the gauge field which is always shown for railway presets..

Plus there's the opposite situation where a mapper who knows about the railways, doesn't get shown the frequency/voltage fields and therefore doesn't realise it can be added to OSM. 

The most likely scenarios are: 

- adding missing info to tracks near already electrified sections, like crossovers or where a second track is drawn instead of being tagged as tracks=2.

- adding info to lines which have been newly electrified. Again this info can be found at either end of the line or by checking wikipedia. It also helps when all heavy rail electrification in Great Britain is 50Hz/25kV for contact line.

Anyway, let's see what happens. :)
