### ISSUE TITLE
Only suggest adding turn restrictions when they make sense

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/iD#4934]
The improved turn restriction editor is very good, however showing for every shared node of a highway is overdoing things and given the suggestive nature of the feature (it implies that you really should be adding a turn restriction, which lots of beginners will do), it should only be shown in cases where there is actually choice.

An example of when it should not be shown 

![grafik](https://user-images.githubusercontent.com/1011860/37861542-364a2b9a-2f3c-11e8-80e1-112d0fc062c3.png)

**Comment by bhousel** [comment]
Thanks for flagging @simonpoole - I agree it should not show the field here.

I think we already hide the turn restriction field at junctions with a single _from_ and _to_.  That rule should probably be be expanded to include any junction with multiple _from_ and a single _to_.

**Comment by slhh** [comment]
In essence I agree, but we should show show the field in case of any existing turn restrictions through the node. It doesn't make sense to hide potentially wrong data.

> I think we already hide the turn restriction field at junctions with a single from and to. That rule should probably be be expanded to include any junction with multiple from and a single to.

In addition that rule should be expanded to any node connecting the ends of two highway ways only, even if bidirectional ones.
It doesn't make sense for data consumers to assume that U-turn rules at the node can be different from the rule along the highway ways in this case.
A U-turn forbidden at the node only would not have a real effect, as the cars can turn nearby.
Assuming such a node allows U-turning, where this is forbidden along the way, would require iD to add U-turn restictions when splitting any highway.

In addition to hiding the restriction editor when such a junction node was selected, iD should also prevent to add a turn restriction in that node, when another node was selected to open the restriction editor. This should also prevent restrictions, where a "via" member way connects to a "from" or "to" member way in that node, because the same could be expressed using a simpler restriction.

Restriction, which have two connecting "via" member ways in that node, are potentially useful. Preferably the two "via" members should be counted as a single one in view of the via count slider. This prevents the restriction editor from becoming useless where the ways a splitted multiple times due to a detailed mapping of lane properties etc. The slider setting would result in the same number of visible restriction levels as before, because uncounted "via" members refer to suppressed restriction levels.

**Comment by bhousel** [comment]
I've expanded this code to catch more trivial junctions..

https://github.com/openstreetmap/iD/blob/a160c00c35e02462a4f91ed77f7e7d01365d7977/modules/ui/fields/restrictions.js#L79-L90
