### ISSUE TITLE
Previously selected background remains highlighted.

### ISSUE THREAD

**Issue by vershwal** [openstreetmap/iD#4947]
As we switch between various background options, the background that was previously selected remains highlighted. For example, if I select 'Esri World Imagery' after 'Bing aerial imagery', the latter is still highlighted.
<img width="244" alt="screen shot 2018-03-27 at 12 00 42 am" src="https://user-images.githubusercontent.com/17474532/37925405-0f7e14dc-3152-11e8-8604-66d4843046d5.png">

It should be something like this:
<img width="237" alt="screen shot 2018-03-27 at 12 01 13 am" src="https://user-images.githubusercontent.com/17474532/37925468-49627b8e-3152-11e8-914b-f9f4cb24309e.png">

**Comment by bhousel** [comment]
Oh yeah that's by design.  It's because the user can switch quickly between those 2 backgrounds with <kbd>⌘B</kdb>.  I know it's a bit strange though.  A nicer solution might be a visual indicator, but we don't have a lot of room on the pane for additional UI, it's already pretty cramped.

Let me know what you think @vershwal ..

**Comment by vershwal** [comment]
I checked ⌘B and it works well to switch between any two backgrounds and then it makes sense. But as a user, I didn't realize it at first.
