### ISSUE TITLE
add yandex.ru tile source

### ISSUE THREAD

**Issue by obama** [openstreetmap/iD#4953]
for russia it has much fresher satelite data.

**Comment by bhousel** [comment]
Hi, thanks for the report. iD's background imagery sources come from the [editor-layer-index](https://github.com/osmlab/editor-layer-index) project, so that is the place to requests about the imagery.

In order to add them as a source, the imagery must be openly licensed, or Yandex needs to grant us a permission to use them for this purpose.  Thanks!
