### ISSUE TITLE
Allow editing a specific object when zoomed out

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#5001]
If on a page like https://www.openstreetmap.org/node/26819236#map=12/37.77927/-122.41919 and clicking edit, iD loads with https://www.openstreetmap.org/edit?editor=id&node=26819236#map=12/37.77927/-122.41919 telling you to zoom in to edit.

We should either load the specific object and display it, or ignore the hash and zoom in to something appropriate, with my preference for the former.

This came up with editing a city place node to add multi-lingual name information, and having difficulty explaining to a user why they needed to zoom in when they had a specific object.

Conflict of interest disclaimer: This arose out of my WMF work.

**Comment by bhousel** [comment]
Yes this makes sense to me that if a calling app passes an entity id (node/way/relation) we should zoom to have it fit in the users viewport (even if that means ignoring the `map=` param)

We're also discussing the same feature here, but for gpx traces: https://github.com/openstreetmap/iD/issues/4796#issuecomment-372086494

However if someone passes both a node id _and_ a gpx, then what would iD do? 🤔

**Comment by pnorman** [comment]
> However if someone passes both a node id and a gpx, then what would iD do?

Fit both in the user's viewport, if zoomed to a higher scale than z16, load the object with an appropriate call, have the object selected, and have the editing pane open.

**Comment by HolgerJeromin** [comment]
> Yes this makes sense to me that if a calling app passes an entity id (node/way/relation) we should zoom to have it fit in the users viewport 
> (even if that means ignoring the map= param)

Often I had viewed an element on osm.org (searched for a feature clicked on it to get the correct position on the map) but lost interest on this element and zoomed/panned away. 

After that I want to edit this region and open iD (which gets the old element in the parameter). 
So with this issue fixed i would be complete confused why iD opened an "old region" and not the new one.

**Comment by quincylvania** [comment]
I implemented this. You can now zoom out with features selected and they will stay visible. Features selected via `id` the URL parameter or via a feature search are fully visible. The "Center" toolbar button is no longer limited to the editable zoom either.

You can only edit the tags and relation members at the moment, since geometry editing at this scale could cause lots of issues.

One caveat is that some relation members might not be downloaded and won't be shown. We should look into downloading all relation members as needed (see https://github.com/openstreetmap/iD/issues/5420#issuecomment-431541278).

<img width="1279" alt="Screen Shot 2019-07-10 at 12 03 18 PM" src="https://user-images.githubusercontent.com/2046746/60985281-332bff80-a30b-11e9-9098-5bb272a91d35.png">
<img width="1279" alt="Screen Shot 2019-07-10 at 12 01 20 PM" src="https://user-images.githubusercontent.com/2046746/60985282-332bff80-a30b-11e9-9baa-c182760f76aa.png">

**Comment by slhh** [comment]
@quincylvania 
When editing is supported on a low zoom level, undo/redo and save should also be supported.

When editing on low zoom levels, using the OpenStreetMap background is quite reasonable, but the selected elements are hardly visible then.

**Comment by quincylvania** [comment]
@slhh Undo/redo is intentionally supported. The buttons are not enabled in the screenshots since nothing had been edited yet.

The user can change the background as need to fit their needs. Though it's a good point that not all backgrounds are suitable at low zoom levels.
