### ISSUE TITLE
car-shop-building shows untypical building outline when sub-tag service is added

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5008]
That means there will be displayed a white/grey line maybe from highway=service to the building outline.

The wiki of shop=car is allowing service=* tag. 
https://wiki.openstreetmap.org/wiki/Tag:shop=car

Could you change behavior of iD-editor, or should we ask the community to change the tagging scheme, 
for example change the sub tag of shop=car from key-name service=* to services=*?

Example osm object:
https://www.openstreetmap.org/edit?way=158075855#map=20/33.78918/-117.91228

building=yes
shop=car
service=tyres
![111](https://user-images.githubusercontent.com/27923772/39225503-080e0a74-484d-11e8-86a6-15c8555629d6.jpg)

building=yes
shop=car
![112](https://user-images.githubusercontent.com/27923772/39225556-65b78d6c-484d-11e8-8e48-43d8c5338996.jpg)

Thanks for reading.

**Comment by bhousel** [comment]
> Could you change behavior of iD-editor, or should we ask the community to change the tagging scheme,
> for example change the sub tag of shop=car from key-name service=* to services=*?

I think the community should just change the tagging scheme for vehicle service.  [The most popular use of `service=*`](https://taginfo.openstreetmap.org/keys/service#values) in this way is `tyres` at 4220 uses, which is really not so many compared to the over 3 millions of `service=driveway` and `service=parking_aisle` each.  That service tag is used for so many other things that it never should have been suggested as a use for vehicle service.

Since #3535 - iD supports an alternative way of tagging vehicle services that doesn't conflict with `highway=service`:

<img width="500" alt="screenshot 2018-04-25 08 52 05" src="https://user-images.githubusercontent.com/38784/39247057-481a13b0-4866-11e8-8904-7a4beb29190d.png">

This approach is the same as the established way of tagging services performed on other things like bicycles:
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle
but uses `service:vehicle:*=*` instead of `service:bicycle:*=*`

**Comment by my-na-me** [comment]
Thanks for information, sorry for double post.
