### ISSUE TITLE
Keep the way selected when navigating by home/end keys

### ISSUE THREAD

**Issue by yaugenka** [openstreetmap/iD#5009]
When you have a way selected and press home/end keys, the first/last node of the way gets selected.
Is it possible to just pan the map to the first/last node but keep the way selected?
It is useful when you want to just check what is going on at the ends.
It would still be possible to get the selection to the end nodes by pressing the keys when a way node is selected.

**Comment by BjornRasmussen** [comment]
This is not the behavior I'd expect - if I pressed home/end, it would be to select the first/part node

**Comment by 1ec5** [comment]
#8264 adds a keyboard shortcut to easily reselect the way after navigating to the endpoint.

**Comment by quincylvania** [comment]
> #8264 adds a keyboard shortcut to easily reselect the way after navigating to the endpoint.

This seems like a reasonable solution for now. If we were starting from scratch we might have considered some endpoint focus step separate from selection, but it wouldn't be great to have a breaking change here.

Also, since 2018 we added a control and shortcut to zoom to the extent of the selection even if it's very large. In most cases this would seem to be a sufficient method to inspect the region around the first or last node without selecting them.
