### ISSUE TITLE
Address preset is using the wrong values for Australia.

### ISSUE THREAD

**Issue by FrakGart** [openstreetmap/iD#5039]
In Australia street addresses are addr:suburb not addr:city and addr:state not addr:province. So for example:
https://api.openstreetmap.org/api/0.6/node/5621132293/1

Moorabbin is a suburb in the city of Melbourne and Victoria is a state not a province.

**Comment by bhousel** [comment]
Hey @FrakGart  - the address formats are defined in this file:
https://github.com/openstreetmap/iD/blob/master/data/address-formats.json

It looks like Australia is currently set to use the same format as Canada.
https://github.com/openstreetmap/iD/blob/837d4b7b32daa9e4ac8e9d31d58c6968eb2751bf/data/address-formats.json#L71-L75

**Comment by tastrax** [comment]
https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-addressing-standards-1999.pdf

 is a great guide but I am no coder maybe this as the most basic form

"countryCodes": ["au"], 
 "format": [ 
     ["unit", "housenumber", "street",], 
     ["suburb", "state", "postcode"] 
 ]

**Comment by bhousel** [comment]
Thanks @tastrax and @FrakGart  - I've added the format to the list.

It shows like this when editing in Australia:
<img width="361" alt="screenshot 2018-05-17 10 11 27" src="https://user-images.githubusercontent.com/38784/40183103-f0e5cccc-59ba-11e8-80a3-f3f0cd21f9e8.png">

**Comment by FrakGart** [comment]
@bhousel Thanks for that. Looks much better.

**Comment by andrewharvey** [comment]
Thanks for catching that @FrakGart! Agreed it's much better now @bhousel with your commit.

**Comment by maraf24** [comment]
Overpass query (http://overpass-turbo.eu/s/zCX) reveals 5500 nodes and ways with addr:suburb in Perth area and 54000 for addr:city tag.
For Melbourne area I got 37000 addr:suburbs and 70000 addr:city, however over 36000 addr:suburbs has also addr:city. Example: https://www.openstreetmap.org/way/44222946

It looks for me that addr:city is widely used in Australia, as addition to addr:suburb or sometimes instead.  The stats show it prevails over addr:suburb.

I would like to suggest to restore addr:city in format address in Australia as it is either used/necessary or needs to be cleaned/moved to suburb field.

Btw, what is rationale for "Address preset is using the wrong values for Australia."? 
The wiki page https://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines doesn't contain any information regarding addr: tags.

**Comment by andrewharvey** [comment]
> It looks for me that addr:city is widely used in Australia, as addition to addr:suburb or sometimes instead. The stats show it prevails over addr:suburb.

@tastrax Linked to the Australia Post reference in https://github.com/openstreetmap/iD/issues/5039#issuecomment-389831953. The postal address must always contain the "Placename/suburb/locality", not the city. So the `addr:city` usage in Australia is technically wrong, but to be honest I don't see it as a big issue since they can all be treated interchangeably as placename/suburb/locality and any data consumers should treat the `addr:city` value as a placename/suburb/locality not a city.

Looking forward though, it's probably not a good idea to say in Australia `addr:city` isn't actually the city, so best we start migrating to `addr:suburb` (valid point that now we're overflowing `addr:suburb` with placename/locality).

It's likely the prevailing tag because `addr:suburb` was only created in 2012 and it's too easy to mistakenly use `addr:city`.

I've used `addr:city` myself, but I've always been tagging the suburb, not the city, so it should have been `addr:suburb`.

> I would like to suggest to restore addr:city in format address in Australia as it is either used/necessary or needs to be cleaned/moved to suburb field.

I think we should leave it as is per this PR, with `addr:suburb` and not `addr:city` for the reasons above.

**Comment by FrakGart** [comment]
The wikki entry https://wiki.openstreetmap.org/wiki/Key:addr#For_countries_using_hamlet.2C_subdistrict.2C_district.2C_province.2C_state has had a note abut the definition of suburb for Australia for a while now.
