### ISSUE TITLE
Quick way to add house numbers

### ISSUE THREAD

**Issue by ADepic** [openstreetmap/iD#5048]
Lack of house numbers is a deal breaker when it comes to navigating on something like your phone, when you want to find a exact house: you can't.

A lot of house numbers are missing in my town, so I would like to add house numbers fast.
I think in most places house numbers go up in increments, especially increments of 2 (I don't know if this is true in other countries but I would assume it is) so it would be good if I could select all the houses I want to add house numbers to, make the increment level 2, and immediatly it will add house numbers to all the houses I have selected.

Currently you have to select one house, then click on the house number box, enter the number and repeat with every house. This is insanely tedious.

The order it would add house numbers (I assume) is the order that the user selected the building / house.

**Comment by eehpcm** [comment]
> I think in most places house numbers go up in increments, especially increments of 2 (I don't know if this is true in other countries but I would assume it is) 

It may not even be true in your country, just common.  It may not even be true in your town, just the parts you happen to have looked at.

In my town there are houses which do not have numbers, just house names.  Organizations (business, churches, whatever) may not have a house name either, just the organization name.  Let me tell you about Quay Street in my town...

Start at the eastern end, south side of the street.  there is 1, Quay Street; 2, Quay Street; New Life Christian Centre, Quay Street; 1, Rock Terrace, Quay Street; 2, Rock Terrace, Quay Street... 5, Rock Terrace, Quay Street (all these buildings face on to Quay Street), [unknown] Royal Oak, Quay Street; [unknown Royal Oak, Quay Street; 2, Royal Oak, Quay Street; 1, Royal Oak, Quay Street (the Royal Oak buildings are on a driveway which connects to Quay Street).  Then there is a car park, then a short track.  At the end of the track is a restaurant on a boat, The Shampan, Quay Street.  Meanwhile, on the north side of the street, opposite 5 Rock Terrace, is 16, Quay Street and the houses on that side increment in number by 1 until you get to 23, Quay Street directly opposite 1, Quay Street.

Actually, it's a little more complicated than that. :)

So your scheme will help some of the time.  Maybe even most of the time.  But sometimes it's going to be annoying because people will have to delete the auto-numbering for a lot of properties.  So it at least needs to be configurable on or off.  And maybe to set the increment to one to account for boustrophedon numbering.

**Comment by bhousel** [comment]
Hey @ADepic, I think that's great that you want to add a lot of house numbers!

iD will probably never be the best editor for this.  It sounds like the sort of thing where a JOSM plugin might already exist to do what you want.  Someday iD might get a plugin system, but that's currently a long ways off, so I'm going to close the issue here as out of scope for iD.

I could imagine a pretty awesome JOSM plugin where you enter values for `start` and `increment`, then just start clicking on things to assign and increment the housenumbers.

If that doesn't already exist, add an issue in the https://github.com/osmlab/osm-planning wishlist repository and maybe someone will build it 👍

**Comment by jidanni** [comment]
Actually one should not add house numbers by hand.

What happens is sooner or later there will be an [import](https://wiki.openstreetmap.org/wiki/Import) done, and then you will be left with double house numbers staring at you on the map, or a [conflation](https://wiki.openstreetmap.org/wiki/Conflation) headache, etc.

It would be better to spend your effort on having the import done.
