### ISSUE TITLE
merging fire_station node and area adds building tag

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/iD#5056]
1. create node with `amenity=fire_station` (or have some to reuse)
2. create new way for the outline of the area.
3. select both
4. merge with the +
5. new way has `amenity=fire_station` AND `building=yes`   8-/

IMO the fire station can have multiple buildings inside and should be tagged on the area and not at the building. [Example](https://www.openstreetmap.org/way/523609075)

**Comment by bhousel** [comment]
Well this is a surprise to me. Up until January the advice on the OSM wiki was to map `amenity=fire_station` as a building, not as a property.

And sure enough, someone changed it recently (January of this year):  https://wiki.openstreetmap.org/w/index.php?title=Tag:amenity%3Dfire_station&diff=1551166&oldid=1401001

This sort of thing happens sometimes where a person will quietly change the OSM wiki with no plan for reviewing all the existing data or communicating this change to the people who write the software, then somebody else will show up on our repo a little while later complaining that "iD is doing a wrong thing".  

Please stop this.  It is never ok to change the advice on the OSM wiki about whether a thing should be mapped as a building outline (the vast majority of things) or as a property outline (a short list of things that I know about and treat specially in iD to not confuse people).

Please put the page back to how it was before January, and accept that many of the fire stations in OSM are already tagged as buildings going back years.

There was a discussion on tagging@ about this as well (not specific to fire stations) but I can't find it now, because mailing lists are a terrible way to discuss things that you want to find later.

Sorry for the tone, but I get kind of angry every time people do this.  I'm not blaming you..
