### ISSUE TITLE
Build of new master (2.9.0) is missing UI icons in the right tool bar.

### ISSUE THREAD

**Issue by LorenMueller** [openstreetmap/iD#5077]

**Comment by bhousel** [comment]
Make sure you `npm install` and then `npm run all` and you should get them!
The way we build the icons has changed a bit.

**Comment by bhousel** [comment]
I'm digging into this today and I can confirm that on windows, the `iD-sprite.svg` is built but empty.

It's almost certainly because of this wildcard glob `'svg/iD-sprite/**/*.svg'` on this line:
https://github.com/openstreetmap/iD/blob/76d21c82939819fa1756a28bc932269df76dbf52/package.json#L20

I'll look for a workaround for telling `svg-sprite` how to find the source .svg files.

**Comment by bhousel** [comment]
Hey @LorenMueller I just pushed a change that fixes this. Wrapping the wildcard glob in double quotes instead of single quotes was needed  😅

**Comment by LorenMueller** [comment]
I confirmed that the update works. Nice work @bhousel !
