### ISSUE TITLE
unwanted not necessary polygon->multipolygon transformation

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/iD#5083]
I see a lot of changeset where a polygon is changed to a multipolygon without any need
- the MP have 2 outer way and those are only used by this MP
- no tag, no change on those way
for ex https://www.openstreetmap.org/relation/8378461
maybe something is wrong in the user interface because I doubt that a newbie really want to split a polygon into a multipolygone with only one outer. it look like a unwanted not necessary split

**Comment by bhousel** [comment]
It looks like the user just use the split command on an area.  It says "split the boundary of this area into two".  iD by design makes a multipolygon out of it rather than leaving the area broken.

![split](https://user-images.githubusercontent.com/38784/41499677-f88c23c8-7151-11e8-8281-b91ffd7cc282.gif)

Splitting this way is the first step for more advanced editing, like if the user did really want to break apart an area, they could do this command and then remove part of the perimeter from relation and move the lines around.  I don't expect a lot of users are doing this, but we try to balance between making it possible and not leaving areas as broken.

**Comment by Marc-marc-marc** [comment]
it's of course a good idea/feature to not broke a polygon and make it possible to create a MP is also a good think.
But I ask myself why soo many newbie split an area without really wanting to.
maybe those users hit the X shortcut: I'll try to talk to the last one.
Because if you look this changeset, the user only want to move some node to align it with the imagery.
So my issue isn't about an "ISATIDL" but about "the user didn't except to do what he do"
Is possible to auto-merge the MP back into a polygon if a user doesn't use the "MP feature" ?
or ask the new mapper if he want or not to enable keybord shortcut ?
or any other idea to avoid "oups, it's valid but unwanted" ?

**Comment by slhh** [comment]
> Splitting this way is the first step for more advanced editing, like if the user did really want to break apart an area, they could do this command and then remove part of the perimeter from relation and move the lines around. I don't expect a lot of users are doing this, but we try to balance between making it possible and not leaving areas as broken.

To make the operation more useful and less likely to be used accidentially, it should require selecting the area and two nodes.
