### ISSUE TITLE
Automatically convert trivial multipolygon back to closed way when merging

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5085]
Hey I was thinking about #5083 more... I realized that users can use the Merge command <kbd>C</kbd> to combine the lines back together into a single line, but this does leave a pointless Relation around with a single `outer`.

When merging like this should iD automatically move the tags back to the way and delete the multipolygon relation?   If we consider "Merge" and "Split" as inverse operations, we should probably do this.

There is also "maybe" a bug where you can Merge lines into a single line that exceeds the 2000 node limit.  I doubt iD checks this at all, but AFAIK, that's the only somewhat useful reason for having a Multipolygon that consists only of outers.

**Comment by mmd-osm** [comment]
> single line that exceeds the 2000 node limit. I doubt iD checks this at all,

No, but the API does and you're getting an error during upload:

![grafik](https://user-images.githubusercontent.com/5842757/41500507-ecf735a2-7192-11e8-986d-4f607672c11a.png)

**Comment by grischard** [comment]
This is an excellent idea. It's something DWG has had to deal with before - someone creating lots of "simple" multipolygons that make edition by newbies overly complicated.

**Comment by slhh** [comment]
Maybe iD can just convert a modified (tags, members, or geometry) multipolygon automatically when saving:
- generate closed way outer and inner rings if the node limit is not exeeded. Original ways which are tagged or used by other relations need to be duplicated with coincident sections of the rings.
- convert the multipolygon into a a closed way area in case of a single outer ring only.

In case we don't want to do this automatically, iD could offer this as a merge operation with the multipolygon being the selected element.

Avoing/simplyfying multipolygons results in more coincidence. Therefore, iD needs become better in handling coincidence.

> When merging like this should iD automatically move the tags back to the way and delete the multipolygon relation? If we consider "Merge" and "Split" as inverse operations, we should probably do this.

This would teach the user a workflow, which is error-prone because iD does not fully protect against merging ways with tag differences (tag is present in one way only).
Example: A landuse multipolygon using a highway as one of its members. Merging the members would result in an unintended highway ring. A highway ring is likely sufficiently visible, but in case of other tags the risk of not detecting the error might be real.

**Comment by BjornRasmussen** [comment]
I think that this is a great idea but think that there is one case where this shouldn't happen: the outer ways being merged are tagged with a key also found in the multipolygon, but with conflicting values.

**Comment by quincylvania** [comment]
I think the proposed behavior is how most users would expect this to work, so I think we should do this.
