### ISSUE TITLE
Preset for amenity=telephone lacks covered=booth

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/iD#5088]
The preset for amenity=telephone offers covered=yes and covered=no.  Most public telephones in the UK (neglecting the emergency phones along motorways) are in booths.

Depending upon which wiki page you look at, either [covered](https://wiki.openstreetmap.org/wiki/Key:covered) is not applicable to telephones or [booth](https://wiki.openstreetmap.org/wiki/Tag:amenity=telephone) is one of three possibilities (the others being yes and no).

In the UK, possibly also in other countries, it would make life easier if covered were one of yes/no/booth instead of just yes/no.

**Comment by bhousel** [comment]
Oh yeah interesting.. I've always thought of `covered=*` as being for highways going under a building part (to avoid triggering building/highway validation)

But I can see [here](https://wiki.openstreetmap.org/wiki/Tag:amenity=telephone) it's being suggested as a way to map phone booths
<img width="184" alt="screenshot 2018-06-17 11 26 02" src="https://user-images.githubusercontent.com/38784/41509429-738e4c20-7221-11e8-81ae-b4ef104e0745.png">

Here is two better options:

1. (I prefer this choice)  Drop the tag `covered=booth` completely.  It doesn't fit in with the more established use of `covered=yes/no` and it's not needed if we have a tag `booth=*`, which people are using [4000+ uses](https://taginfo.openstreetmap.org/keys/booth).   iD could easily add a `booth=*` field to the telephone preset, and that could just be the tag.

2. If we really are stuck on having `covered=booth` be a thing, I could make a separate preset for "phone booth" that adds `covered=booth`?  Rather than adding another state to the `covered=yes/no` field?

I'll ask the tagging@ list what they prefer, then will just decide something if we don't have any resolution after after a few days.

**Comment by eehpcm** [comment]
I'm not fixated on covered=booth.  I used it because that's what the wiki suggested. I suspect the wiki suggests it because that's what people used for lack of anything better.  You're right, it doesn't really fit in with the primary use of covered=*, although a phone could coincidentally be placed where covered=* does apply.

I've no problem with a new tag.  Phones aren't (currently, on OSM carto) rendered differently whether or not they have covered=booth, so a change won't break any rendering expectations.  And it would be ripe for automated replacement at the same time.

The wiki description about booth=k2/k6 isn't that useful.  It's applicable only to the UK (and a few other countries which adopted UK phone booths), and links to a wikipedia article on red telephone boxes.  But the old red phone boxes have been phased out in the UK itself and only a few are left.  These days they're usually in the KX series.  Few people could identify any of the specific models without a reference guide (I couldn't).  Maybe what we need is booth=yes/no and a booth:type=* for those with obsessive mapping disorder. :)

And then to pour cold water on the idea, what about phones in the US which often aren't in booths but have a hood (is that the correct terminolgy)?  And what do other countries have?

**Comment by Nakaner** [comment]
`covered=yes/no/booth` was [added](https://wiki.openstreetmap.org/w/index.php?title=Tag%3Aamenity%3Dtelephone&type=revision&diff=466304&oldid=464455) to the English wiki page by user AssetBurned on 2 May 2010. [Usage](http://taghistory.raifer.tech/) of this tag started in early May 2010. I did not look who used the tag.

**Comment by bhousel** [comment]
Ok we had an extensive discussion on the tagging list that ended up inconclusive.

I've decided to just leave the `covered` field as a `yes`/`no` checkbox.
I've also added a `booth=*` dropdown field, so people can add that detail if they want to.
