### ISSUE TITLE
conveying=forward/backward and priority=* are also combinations with direction-based values

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#5121]
If you change a way's direction to the other one, the values of many keys (like incline=* and all keys with "direction" in it) are getting changed to the opposite value. Conveying=* and priority=* are also Keys with direction-based values. Their usage might be not so common, but I think it's documented clearly, see

https://wiki.openstreetmap.org/wiki/Key%3Apriority

https://wiki.openstreetmap.org/wiki/Key:conveying

Okay, for the key _conveying_, there also two non-directional values documented. But I mean the cases, where for example the escalator's conveying-direction is one all the time (forward or backward).

**Comment by bhousel** [comment]
This is tricky.. Lets talk through it:

I would think that when reversing a way, we want to leave those tags alone.
For example with an escalator:

`highway=steps + incline=up + conveying=forward`
User reverses, now you have:
`highway=steps + incline=down + conveying=forward`  (and nodelist reversed)

If we were to also reverse the `conveying` tag, then it would leave the escalator pointing in back in the original direction.

**Comment by Nakaner** [comment]
@bhousel I don't understand why I you added the considering label. I think you misunderstood something. Both `incline=*` and `conveying=*` refer to the direction of the way. `conveying=*` does not refer to the direction of the incline.

![forward and backward, up and down](https://camo.githubusercontent.com/b15d5832bcf023c63060fd87de4554b41056255a/68747470733a2f2f6b756e64656e2e67656f66616272696b2e64652f62663439613062386538333264306238336364313233613265353430343962362f636f6e766579696e672e737667)

Btw, looking at https://taginfo.openstreetmap.org//search?q=forward#values points out some more keys which have values like `forward`. Some examples are

* `trolley_wire`
* `railway:preferred_direction`
* `overtaking`

New keys can be invented by everyone and that's why I recommend to do it like JOSM and reverse any way tags which have the value `forward` or `backward` and whose key does not match `^.*(_|:)?(description|name|note|website|ref|source|comment|watch|attribution)(_|:)?`. (You don't want to change `name=forward` into `name=backward`)

For reference: The correction is implemented in [org.openstreetmap.josm.corrector.ReverseWayTagCorrector](https://josm.openstreetmap.de/svn/trunk/src/org/openstreetmap/josm/corrector/ReverseWayTagCorrector.java), the list of ignored keys is in [org.openstreetmap.josm.data.osm.AbstractPrimitive.getUninterestingKeys](https://josm.openstreetmap.de/svn/trunk/src/org/openstreetmap/josm/data/osm/AbstractPrimitive.java)

**Comment by bhousel** [comment]
> @bhousel I don't understand why I you added the considering label. I think you misunderstood something. Both incline=* and conveying=* refer to the direction of the way. conveying=* does not refer to the direction of the incline.

Cool thanks for clarifying - this was the thing I was confused about.

**Comment by bhousel** [comment]
I did this - I added the logic per @Nakaner's suggestion, cleaned up some of the code, and added a lot of tests in 416ae66f7
