### ISSUE TITLE
Default building:levels value for kiosks/others

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#5131]
Just tried to edit the preset and failed miserably, so opening an issue to see whether this is something worthwhile.
While kiosks are usually just nodes with `shop=kiosk`, some also have an outline with `building=yes/kiosk` (rarely).
Since I am yet to see a 2 level kiosk, would that be correct to default `shop=kiosk` to `building:levels=1`, despite not all of them having an outline? Could be only applicable to those that are an area (e.g. `building=kiosk`, or a trickier case `building=yes` + `shop=kiosk`, which is what I attempted to catch by setting levels on a node?
Other buildings I could see having default levels value are `building=service,bungalow,static_caravan,cabin,carport,cowshed,garage,garages,shed,sty`
Comments?

**Comment by bhousel** [comment]
I agree that any preset with a `building` field can also have a `levels` field  (which assigns the `building:levels=*` tag).

@vershwal this is like #4905 - can you take care of it?

**Comment by tohaklim** [comment]
Would the `levels` field support a default pre-assigned number of floors?

**Comment by Nakaner** [comment]
@tohaklim wrote:
> Since I am yet to see a 2 level kiosk, would that be correct to default shop=kiosk to building:levels=1, despite not all of them having an outline?

Please do not conclude from your own experiences to the whole world. Missing default values can be added by data consumers easily. For example, OSM2World has its set of default heights (levels) for different types of buildings. Adding default values without an explicit confirmation by the user will lead to wrong data and does not have any benefit.

We have a significant number of new user accounts who add a POI and often choose to add the tags to the building instead of creating a node (nobody tells them before that a node is most likely more correct but that's a different topic). If such a user adds a kiosk which is located in a larger building (quite common here), iD would silently add `building:levels=1`.

**Comment by bhousel** [comment]
> Would the levels field support a default pre-assigned number of floors?

No, I think the assumed default is '1', and people would probably complain if iD started adding an explicit `building:levels=1` tag to every building by default.

**Comment by bhousel** [comment]
> iD would silently add building:levels=1

Just to reiterate to what I wrote above, iD does not do this.
