### ISSUE TITLE
vehicle=* tags aren't shown as vehicle restrictions on the left panel of the editor

### ISSUE THREAD

**Issue by Robot8A** [openstreetmap/iD#5166]
Actual behavior:
![imagen](https://user-images.githubusercontent.com/19521377/43044493-27e04e26-8da7-11e8-8e18-d2ba1bb8b573.png)

Expected behavior:
![imagen](https://user-images.githubusercontent.com/19521377/43044523-c3fdea16-8da7-11e8-9f8e-15f84a99256b.png)

**Comment by Robot8A** [comment]
Maybe horse too?

**Comment by bhousel** [comment]
Oh the `access=*` stuff [on the osm wiki](https://wiki.openstreetmap.org/wiki/Key:access#Land-based_transportation) is just too much to support, so iD supports a small subset of it.  Sorry!

#3945 offers some ideas on how we might change the list to be more open-ended, but I worry that this would make the field unusable to new contributors.  We don't want to make it so that everyone needs to read the wiki in order to contribute meaningfully.
