### ISSUE TITLE
Add logos to name suggestion presets

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5167]
I typed in "blumen" in ID and got this:
(See URL at the bottom of the screenshot for details about the tag, both have the same tag shop=florist)

|  mouseover the first | mouseover the second  |
|---|---|
|  <img width="411" alt="bildschirmfoto 2018-07-24 um 06 22 37" src="https://user-images.githubusercontent.com/111561/43117360-b6f6eda2-8f0c-11e8-8827-0f5589d8291a.png"> |  <img width="412" alt="bildschirmfoto 2018-07-24 um 06 22 32" src="https://user-images.githubusercontent.com/111561/43117361-b70d741e-8f0c-11e8-8b37-682f1c107c18.png"> |
|   |   |
|   |   |

The second one does no make any sense.
And I cannot find the second one in the translation app https://www.transifex.com/openstreetmap/id-editor/translate/#de/presets?q=translation_text%3A'Blumen+Risse'

**Comment by ImreSamu** [comment]
my guess:    "Blumen Risse"  source is the https://github.com/osmlab/name-suggestion-index project.

see : 
* https://github.com/osmlab/name-suggestion-index/search?q=Blumen+Risse&unscoped_q=Blumen+Risse

**Comment by tordans** [comment]
Interesting, I didn't know about this feature. 

And you are right, I compared the two presents and the "Blumen Risse" one also provides a name="Blumen Risse" ans such.

I wonder if this  is worth explaining better in the UI. 

For me this made me quite uncertain about what's going on.

**Ideas**

For a regular preset:

> {Icon} Flowershop (i)
> Shop sells flowers
> Open in Wiki

And for a company/"often used names"-preset:

> {Icon} Flowershop of Company "Blumen Risse" (i)
> Preset for the company Blumen Risse
> Open in Wiki

**Comment by bhousel** [comment]
The name suggestion presets are a lot less confusing now.

**Comment by tordans** [comment]
A few notes, more for myself :-).

--- 

The only change I can see on production and preview is: There is a line break where the " - " was in the preset name.

And maybe I became blind to the issue I experienced before, but _right now I think one can figure it out._

In case we ever revisit this …
- Changing the info-(i) description like skribbeled above still seems like a good idea / starting place
- I wonder if there is a good place to pull logo data from; with a logo we could make very clear that this is a specific brand vs. the general tag. However, the design might be tricky. Maybe something like showing the logo on mouseover instead of the generic tag-icon? So it does not look like an Ad.

**Comment by bhousel** [comment]
> * Changing the info-(i) description like above still seems like a good idea / starting place
> * I wonder if there is a good place to pull logo data from; with a logo we could make very clear that this is a specific brand vs. the general tag. However, the design might be tricky. Maybe something like showing the logo on mouseover instead of the generic tag-icon? So it does not look like an Ad.

Yes, both of those are things I'd like to add.  We can leave this issue open.
- fetching the documentation image and description from wikipedia 
- replacing the preset icon with a logo

We had discussion on both OSM-US Slack, and also https://github.com/osmlab/name-suggestion-index/issues/2116 about strategies for fetching logos.  I think it's possible, but I'd like to start by storing the brands social media accounts in wikidata (some already have this), because the logo images already in wikimedia commons are not consistently usable, especially in that 60x60px preset icon space we have to work with.

An example:

<img width="300" alt="screenshot 2018-12-01 23 14 05" src="https://user-images.githubusercontent.com/38784/50423337-ee82c000-0821-11e9-830f-02da665c3eb1.png">

**Comment by quincylvania** [comment]
I did this thanks to [name-suggestion-index v2](https://github.com/osmlab/name-suggestion-index/releases/tag/v2.0.0)!

<img width="371" alt="Screen Shot 2019-03-28 at 2 21 18 PM" src="https://user-images.githubusercontent.com/2046746/55182829-e90c7d00-5164-11e9-98ff-501dc6bc5572.png">
<img width="374" alt="Screen Shot 2019-03-28 at 2 22 01 PM" src="https://user-images.githubusercontent.com/2046746/55182832-e90c7d00-5164-11e9-9d52-e16ac141d0c3.png">
<img width="381" alt="Screen Shot 2019-03-28 at 2 21 10 PM" src="https://user-images.githubusercontent.com/2046746/55182833-e90c7d00-5164-11e9-89d6-b6a6290353a0.png">

**Comment by simonpoole** [comment]
@quincylvania you have checked with legal?

**Comment by Adamant36** [comment]
simonpoole, I seem to remember reading somewhere that's ok to use brand icons for map use cases like this, or somethings.

**Comment by simonpoole** [comment]
I seem to remember reading somewhere that the earth is flat.

Contrary to that, the IP question is a bit tricky as it involves both copyright and trademark law, and we are subject to copyright law in a country with very low creativity requirements. There are some other more general issues with the provenance of the logos on top of that,  for example just follow back from where the McDonald's was obtained, not to mention using content from FB potentially at odds with their ToU.

In any case this needs to be looked at by a lawyer with relevant experience.

**Comment by Adamant36** [comment]
"Contrary to that, the IP question is a bit tricky as it involves both copyright and trademark law, and we are subject to copyright law in a country with very low creativity requirements." 

Its being used on the back end as reference though, the same way Wikipedia uses, except Wikipedia actually dispays them on their main site, and the logos aren't even used in OSM in anyway. Its not for profit either. So I don't think copyright or trademark is an issue in this particular case. From what I understand trademark is only relevant in cases where its a similar looking product. For instance in American logo copyright says "The Lanham Act allows a non-owner of a registered trademark to make "fair use" of it without permission. Fair use includes using a logo in editorial content, among other situations." Id consider this editorialish in nature. UK law is similar "Fair use is covered if the use is for the purposes of research or private study." Id consider this research (Again, its a reference to figure out what company your tagging. I.E. research purposes. Not to create a product off of. Let alone a similar one). 

I'm not to sure about Facebooks ToU, but I'm pretty sure both @quincylvania and @bhousel wouldn't have just jumped into it without doing the proper research first. I know @bhousel already said it was fine when someone else asked him about it. 

Things like brand logo's are already used everywhere in OSM as it is, for instance in the wiki. So its not like this is anything new either.

**Comment by simonpoole** [comment]
@Adamant36 are you a lawyer with relevant experience?

**Comment by Adamant36** [comment]
@simonpoole, I don't have to be to have an opinion on things do I? Your still have opinions on this when your not one either. As much as it could be an issue, it could also not be one. So I could say the same to you for bringing it up in the first place. Especially since like I said I'm pretty sure they have thought about the legal aspects already. I don't need to be a lawyer to tell you that. Generally speaking, I also find the whole "you can't have an opinion on that because your not a...." argument a little trite. That could just be me though. 

Either way, I highly doubt they would implement something that violated copyright law based on something a random person cut and pasted from a Google search. Plus, as I said, it already came up and @bhousel already said it wasn't an issue, or I wouldn't have gave my opinion on it in the first place. Your 100% free to disregard that though and ignore the fact that it was already discussed. I don't really care either way. Since it's already been implemented, it really doesn't matter.

**Comment by bhousel** [comment]
Hey @simonpoole - If you have actual concerns then loop in the LWG.

I'm not a lawyer either.  We are confident that we're displaying the marks in a way that respects the brands' property and meets the legal standard for non-infringing [fair use](https://en.wikipedia.org/wiki/Fair_use)  (or [fair dealing](https://en.wikipedia.org/wiki/Fair_dealing_in_United_Kingdom_law), as it's called in the UK).

Probably the best precedent for what we are doing is covered by things like the knowledge info boxes on Google search results, but also the searches on Facebook, Twitter, and others. In iD's case, we are not redistributing the images, just pulling them from public sources, and we are using them for identifying the brands in a list, not for commercial purposes or parody, nor deep linking to any brand pages.  Displaying logos makes it easier for our users to confidently identify a branded business and choose it from the list so that it is mapped with the proper tags and name spelling.

[Kelly v Arriba Soft](https://en.wikipedia.org/wiki/Kelly_v._Arriba_Soft_Corp.#Fair_use_analysis) even tested this in the US 9th Circuit Court and found that displaying thumbnail images in a search engine was a fair use of Kelly's intellectual property.

**Comment by simonpoole** [comment]
> 
> 
> Hey @simonpoole - If you have actual concerns then loop in the LWG.
> 
> I'm not a lawyer either. We are confident that we're displaying the marks in a way that respects the brands' property and meets the legal standard for non-infringing [fair use](https://en.wikipedia.org/wiki/Fair_use) (or [fair dealing](https://en.wikipedia.org/wiki/Fair_dealing_in_United_Kingdom_law), as it's called in the UK).

UK fair dealing is not the same as the US fair use even in name, and essentially never applies (outside of some very very narrow cases).
> 
> Probably the best precedent for what we are doing is covered by things like the knowledge info boxes on Google search results, but also the searches on Facebook, Twitter, and others. In iD's case, we are not redistributing the images, just pulling them from public sources, and we are using them for identifying the brands in a list, not for commercial purposes or parody, nor deep linking to any brand pages. Displaying logos makes it easier for our users to confidently identify a branded business and choose it from the list so that it is mapped with the proper tags and name spelling.
> 
> [Kelly v Arriba Soft](https://en.wikipedia.org/wiki/Kelly_v._Arriba_Soft_Corp.#Fair_use_analysis) even tested this in the US 9th Circuit Court and found that displaying thumbnail images in a search engine was a fair use of Kelly's intellectual property.

And, US case law is of exactly zero relevance to this.

**Comment by bhousel** [comment]
> UK fair dealing is not the same as the US fair use even in name, and essentially never applies (outside of some very very narrow cases).
> And, US case law is of exactly zero relevance to this.

Ok.  I'm sure when you ask a real lawyer about this, they will have a slightly more nuanced view of how fair use works.

In the mean time, I'm going to lock this issue, since I really don't have any other tools left in my toolbox, nor energy to respond to your comments.
