### ISSUE TITLE
Notes: Fix a note github style

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5170]
**An idea for [the new notes feature](https://twitter.com/bhousel/status/1019021979117072386?s=21)**

In my commit message, I would like to attribute the note. The note then could then be updated, maybe even closed via special keywords. 

The way this could work is by adding a dropdown to the commit message UI where I can select a note of the vicinity of my change and say "this note was fixed by this" or "this note was updated by this" (if its just one commit of many to fix it).

Github uses a similar pattern for issues. An Pivotal tracker also reads commit messages to update tickets
- https://help.github.com/articles/closing-issues-using-keywords/
- https://www.pivotaltracker.com/help/articles/github_integration/#using-the-github-integration-commits

**Comment by bhousel** [comment]
I find myself doing this too, but I can't imagine a way to implement this and have it be really good.  Part the challenge is that issues on GitHub are easily identifiable and notes on OSM really are not. 

I usually end up copying the link to the note at the bottom of the note editor and pasting it into my changeset comment with a message like 

"Add bollards per https://www.openstreetmap.org/note/1132569" 

[example changeset](https://www.openstreetmap.org/changeset/61002465#map=19/40.71711/-74.01292&layers=N)

I think it could be fun to say in a changeset comment "closes #1132569" but in practice it would be annoying to pick exactly which number goes there.  

Sorry going to close this one to avoid having someone spend time working on it..

**Comment by rugk** [comment]
I strongly disagree…

> is that issues on GitHub are easily identifiable and notes on OSM really are not

What do you mean? Notes on OSM do have a notes **ID**. An unique identifier!
I could not imagine a better way to identify a note technically.

> I usually end up copying the link to the note at the bottom of the note editor and pasting it into my changeset comment with a message like

Yep, me too. That's why we have this feature request here. See https://github.com/openstreetmap/iD/issues/6906 for a full description.

> annoying to pick exactly which number goes there.

I always do. Even with GitHub issues. (or the URL, of course. That should be interchangeable)
Copy ID -> close issue. Simple.

What's worse: As this feature is not implemented, I do have to do even more steps to backlink all things properly. Again see https://github.com/openstreetmap/iD/issues/6906. You'll see with that feature I would save two steps, which are very annoying.

---

Generally said: There is a reason GitHub has implemented this. And it has proven to be very useful in practice on GitHub, so I really don't understand why you don't adapt this for OSM/iD.

**Comment by bhousel** [comment]
> I always do. Even with GitHub issues. (or the URL, of course. That should be interchangeable)
> Copy ID -> close issue. Simple.

If it's so simple, you implement it.  I barely even work on iD anymore.

**Comment by BjornRasmussen** [comment]
Here's how I think it should work: there should be two resolve buttons, one which resolves instantly, and one which resolves on upload.

**Comment by quincylvania** [comment]
@rugk Please be polite and understand that iD has limited development resources—far fewer than GitHub. Also, issues that seem simple to you might be deceivingly complicated and in any case will take time that might be better spend elsewhere.

**Comment by rugk** [comment]
@BjornRasmussen Yeah, also a good idea.

@quincylvania All right, I just wanted to clarify that this is actually an issue people want. (As you can see some jumping in here, too.)
So that's why it should be an open issue in the issue tracker. Otherwise people will not even try to implement it.
