### ISSUE TITLE
Notes: Pressing `4` when not in "OpenStreetMap notes" mode give no visual information

### ISSUE THREAD

**Issue by magol** [openstreetmap/iD#5190]
If I don't have enabled the "OpenStreetMap notes" mode and use the keyboard shortcut `4`, the 'Add note' mode is activated, but you don't get any visual information what is going on. 

Normally when you go in to a add mode, the Point/Line/Area button is marked to indicate what you are doing. The same when you are in "OpenStreetMap notes" mode and adding a note. But if you have not enabled the "OpenStreetMap notes" mode and accidentally hit `4`, you don't know what mode you are in.

**Suggested solutions:**
* Don't allow `4` when "OpenStreetMap notes" are disabled
* Automatic enable "OpenStreetMap notes" when hitting `4` (I prefer this)

**Comment by bhousel** [comment]
Thanks for reporting @magol .. I went with this: "Don't allow 4 when "OpenStreetMap notes" are disabled"

I chose this solution because it's probably easy for users to hit `4` without thinking about it, and if they don't know about the notes layer, they would be confused to have it enabled and put into Add Note mode.  For now, we'll continue to make enabling the notes layer be a thing they need to purposely opt in to.
