### ISSUE TITLE
Wikidata input bug

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/iD#5208]
Hi, it is perhaps an old bug... There are an example of syntax error done by iD, at https://www.openstreetmap.org/node/261615248 where a the Wikidata-ID is "Q10366821)" instead "Q10366821"... 

Will be easy to fix by regular expression validation, `^Q\d+$`.

**Comment by JamesKingdom** [comment]
Are you sure this wasn't just a user input error? I can't seem to recreate this.

**Comment by bhousel** [comment]
I also tried recreating this issue with no luck.
I deleted the tags, and then reentered the below using the Wikipedia field, and the correct Wikidata was automatically added.

I'll close for now - maybe there was a bug that has since been fixed, or it was an issue where the user manually pasted the tag incorrectly.  If it does happen again in a repeatable way, we can reopen and fix!


<img width="372" alt="screenshot 2018-08-06 09 34 45" src="https://user-images.githubusercontent.com/38784/43719542-012dc43c-995c-11e8-8c23-5d28de97dfa5.png">
