### ISSUE TITLE
Toilets preset: missing female=yes + male=yes option

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/iD#5221]
The Gender field in the Toilets preset is missing a Female/Male (female=yes + male=yes) option.

I think that gender-segregated toilets are usually mapped with just one node instead of two (i.e. one with female=yes and one with man=yes). Because there's no female=yes + male=yes option, this could lead that people wrongly tag these toilets as unisex.

**Comment by bhousel** [comment]
Unfortunately iDs radio button field can't set multiple values with one radio button.  If the tag keys were namespaced, we could support it with a multiselect.

A lot of people don't really like the existing gender tagging anyway, and there was a lengthy discussion of these issues on #3954, but I don't think it ever achieved enough consensus in the community to push for all the tags to be changed to something better.

**Comment by SelfishSeahorse** [comment]
> Unfortunately iDs radio button field can't set multiple values with one radio button.

But adding tree separate checkboxes – one for female, one for male and one for unisex – like micahcochran proposed and like it's implemented in JOSM shouldn't be a problem, should it?

**Comment by bhousel** [comment]
> But adding tree separate checkboxes – one for female, one for male and one for unisex

That's confusing because some people check `male=yes` and `female=yes`, and other people check `unisex=yes`.

I'd rather have people drop a point node for each restroom, and pick a single option for what it is.  That's the least confusing way to tag them currently.  

If instead gender field were namespaced and people could pick from many different things in a multiselect, that would be even better, but it's probably not going to happen because nobody can agree well enough on what the existing tags mean in order to do a meaningful tag upgrade.
