### ISSUE TITLE
id prevents from deleting big objects 

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/iD#5236]
When I try to delete a long way I get the error that it is not sufficiently visible on the screen but when I zoom out I get the message to zoom in for editing.
Also I can do all other kind of potentially problematic things like straightening a way, or remove arbitrary tags.

**Comment by bhousel** [comment]
> When I try to delete a long way I get the error that it is not sufficiently visible on the screen but when I zoom out I get the message to zoom in for editing.

Yes this is by design.. #3700 was when we started preventing users from deleting large features.  You can still use other editors like JOSM to delete large features.

> Also I can do all other kind of potentially problematic things like straightening a way, or remove arbitrary tags.

Yeah this will change, I'd like to restrict even further the kinds of "potentially problematic" edits to large features that beginning users can do with iD - see #3681 

The news isn't all bad though, because the plan is to allow power users to override these checks - see #2929
