### ISSUE TITLE
Lines from custom data files block clicking ways underneath them

### ISSUE THREAD

**Issue by JesseCrocker** [openstreetmap/iD#5257]
Im tracing trails from gpx files. When a node from an existing way is under a line from a gpx file it is not possible to select the node when making a new way.

This is a regression in 2.11.0

**Comment by bhousel** [comment]
Yep, you might just have to zoom in more until the data is not exactly on top of whatever is already there.  The external data files are selectable now, so they'll steal your clicks.

**Comment by JesseCrocker** [comment]
Yeah, thats whats happening, gpx line is stealing clicks. It seems weird that the line is selectable, because it doesnt seem like you can do anything with it after selecting. But this might just be a case where im seeing this as a bug because it breaks my particular workflow.

**Comment by tkansgar** [comment]
Hi all,

this new feature is very annoying for me. Sometimes the point I want to click, is really so exakt under the gpx line, that almost whatever zoom level I try, it's not possible to hit the point instead of the gpx line. My proposal is to give a higher sensitivity level to the points of lines than to the gpx lines. The point should get precedence over the gpx line, if both are close together. Is this realisable?

Best regards
tkansgar

**Comment by njohnston** [comment]
Just to provide some more user input, this change has drastically slowed down my mapping, and caused me to accidentally not connect some paths correctly (since the ends of lines don't "snap" to nodes on other ways as easily if there's a nearby track).

For example, when [editing](https://www.openstreetmap.org/edit#map=19/51.74080/-2.21288) with this [sample GPX file](https://drive.google.com/open?id=1goyq3eS9pdcIPsaJufmpr5_QkdyrcpJt), selecting the node I've marked in red is tricky:

![image](https://user-images.githubusercontent.com/638458/44949348-869a0b00-ae27-11e8-818a-87de3dab5a6c.png)

I need to zoom in several times and then click around, aiming very carefully.

I agree with @JesseCrocker: having tracks from GPX files selectable doesn't seem to add any value, except for the marginal benefit of being able to identify different segments/tracks from the same file.

I've had the same problem as @tkansgar when trying to add nodes for stiles and gates to a footpath. While out surveying, I added waypoints/markers for the stiles and gates, but I can't actually add the corresponding nodes in the same locations.

In cases like these, where a track/trace intersects an existing OpenStreetMap way, it's impossible to select the actual point at where the track/trace and way intersect, regardless of zoom:

![image](https://user-images.githubusercontent.com/638458/44949484-4e47fc00-ae2a-11e8-9fad-db2678a95da4.png)

**Comment by tkansgar** [comment]
Hi all again,

I found a second workaround (the first one is zooming in): You can switch off the gpx line temporarily. Display the panel "map data" (hope this is the correct name in english) on the right side and uncheck the setting "user defined map data". The gpx line is gone, and you can make your changes. Then switch on the "user defined map data" to see gpx line again.

But better than any workaround would it be, if the gpx line would get a lower click precedence than the OSM data, as I wrote before.

Br
tkansgar

**Comment by bhousel** [comment]
> Why this issue is not marked "bug" ?

I'm on vacation this week and I'll get to it next week.  Anyway yeah I'll mark it as "bug".

> Not a big problem

I agree

> I cannot understand why is it useful to be able to select the GPX track

There are lots of potential sources of external data (gpx is only one of these).  Being able to select and inspect external data is both useful (#5243) and will unblock more interesting things (#2586 #3773 and #4164 are all related).

There is code in iD to determine "what the user actually clicked on" and it really depends on what order we draw things into the SVG DOM.  The OSM objects in iD (points, lines, areas, midpoints, vertices) all draw invisible touch targets to grab the mouse clicks, so we can control exactly what gets clicked.  The OSM Notes, Data (gpx) and upcoming KeepRight layers don't do this yet and are instead just drawn on top of whatever is there, that's why they steal the clicks.  It's actually not a difficult problem to solve, it just requires some reworking of the layer draw order.

In the mean time, just zoom in and put your point next to where the gpx track is.  Your gpx track is not super accurate anyway, and it's totally ok to just put the point a few centimeters away from where it's actually drawn on the screen.

I'm sorry that it slows you down while editing, and I do understand that it can be frustrating when the developers change some feature of software that you use regularly.  If you really want to be the fastest mapper you can be, it's probably worth your time to install JOSM and get a gaming mouse.

**Comment by Mahabarata** [comment]
Thanks for your answers.
In fact I love ID that why I was frustrated not to be able to work properly.
But I can wait, for the moment I stop to use GPS tracks : there is a lot of other things to do like create rivers, lakes, wetland (when I'm trekking I think it's useful that at some place there is a stream to cross, a beautiful lake not to far or things like that), no need of tracks for that.

I have other pbs with ID, I will see if opened issues talks about these otherwise I will give you some other tasks to do, lol

Best regards

**Comment by HarelM** [comment]
Any updates on this? I agree this slows the tracing process for me as well.

**Comment by jeffrey-friedl** [comment]
> There are lots of potential sources of external data (gpx is only one of these). Being able to select and inspect external data is both useful (#5243) and will unblock more interesting things (#2586 #3773 and #4164 are all related).

Is it possible to make selectability an option, just as one can optionally show or hide the whole thing?

**Comment by tordans** [comment]
I wonder if there could be a button in the left-panel.

Workflow example:
- I show a gpx
- I click it => the left-panel shows info about it
- There is a button "Prevent interaction with this"
- I click the button => The gpx is now non-selectable until … (I reload, I save, …)

**Comment by Mahabarata** [comment]
Yes, great idea.
But I still don't understand why it is useful to be able to select it and to have the data about the gpx on the left
For me, to select the gpx will be very useful if you could select not all the gpx but some points on it and to have the time of the points : sometimes i take a picture of a great thing, i know of course the time of the picture but don't remember the exact place of it. With the time of the picture and the time on the points of the gpx i will find easily the place and create a new POI in OSM
Best regards

**Comment by bhousel** [comment]
This was done!  the OSM objects now take precedence over the non-OSM objects.

**Comment by tkansgar** [comment]
Hi Bryan,

is the version with this fix already working on openstreetmap.org? I can't notice any change there in behaviour.

Best regards
tkansgar

**Comment by bhousel** [comment]
> is the version with this fix already working on openstreetmap.org? I can't notice any change there in behaviour.

It is not yet..

**Comment by Mahabarata** [comment]
Hi,
sorry to come back here but there is still a pb : here with an example.
When you select a way then create a new node on that way or select an existing one, if you move the node on the gpx (to improve the way), on the left you lost the informations about the way and you have informations about the gpx file.
<img src='http://montdm.free.fr/img/donnée%20de%20carte%20personnalisée.jpg'>
In this picture you can clearly see that the way is selected (there is like an aura around it, not easy to capture it because it flashes) but on the left you have lost the information of the way. The gpx is no more  selected on the right which is great but on the left ID works as it was.
Best regards
