### ISSUE TITLE
Add design tag values preset to high-voltage tower 

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#5334]
Hello. Currently the design tag and its values are not available as presets when someone is adding a high-voltage tower to a power line. Is there any way it can be added?

**Comment by bhousel** [comment]
Good suggestion @Adamant36 - This is a great task for anyone who wants to get involved and learn how to add a preset field to OpenStreetMap's iD editor.  I've tagged it as Hacktoberfest, so wait until October 1 to get credit.

For reference here is the [OSM wiki for high voltage power towers](https://wiki.openstreetmap.org/wiki/Tag:power=tower).

That page does suggest a `design` tag with several choices.  Because there are so many, I think we should use a `combo` field configured to pick from the most common choices that mappers have added to OpenStreetMap.  We can use taginfo to see [how the `design` key is currently used](https://taginfo.openstreetmap.org/keys/design#values).

The presets and fields in iD are all defined in .json files under `data/presets/*` folder.  There is also a [README.md](https://github.com/openstreetmap/iD/blob/master/data/presets/README.md) there to explain how to format the .json files.

To complete this task:
1. create a file `data/presets/fields/design.json` that contains this:
```js
{
    "key": "design",
    "type": "combo",
    "label": "Design"
}
```
2. Edit the file `data/presets/presets/power/tower.json` and add `"design"` to the `"fields"` array.  The order of elements here is the order they will appear on the screen, so add it to the beginning.
3. run `npm run build` - this will rebuild the generated files
4. run `npm run start` and test your change locally.  If you draw a line and tag it as a "Power Line", then add a vertex along that line and tag it as a "High Voltage Tower", you should see your new "Design" field offered as a choice here in the sidebar:

<img width="200" alt="screenshot 2018-09-27 11 13 36" src="https://user-images.githubusercontent.com/38784/46155990-859da300-c246-11e8-8f4e-9bc77793ed39.png">

If all looks good, send a Pull Request.  Thanks in advance!

**Comment by boothym** [comment]
Good idea, maybe tower:type as well - though that also contains values for man_made=tower. Unless only the values here can be shown in iD? https://wiki.openstreetmap.org/wiki/Tag:power=tower#Tower_type

What about changing the name to "High-Voltage Power Tower" so it shows up in a search for power?

And is there a tower icon that could be used instead of the dot?

**Comment by bhousel** [comment]
> What about changing the name to "High-Voltage Power Tower" so it shows up in a search for power?

We can add a property `"terms": [ "power" ]` to the preset so that it will show up in a search for "power".

> And is there a tower icon that could be used instead of the dot?

We don't have one currently in any of the supported icon sets.

**Comment by hchho** [comment]
I'll take this! I have a pull request for this
