### ISSUE TITLE
Remove embankment=yes-preset

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5344]
ATM, there are two presets:
1. embankment=yes https://github.com/openstreetmap/iD/blob/master/data/presets/presets/embankment.json
2. man_made=embankment https://github.com/openstreetmap/iD/blob/master/data/presets/presets/man_made/_embankment.json

The way I read the wiki, the first tag is not a top-level-tag but something added to highways. [Source](https://wiki.openstreetmap.org/wiki/Key:embankment).
> Usage
> Add embankment=yes to a way that is already tagged with a highway=*, railway=* or waterway=* tag. When micro-mapping, you can also draw two parallel ways and add man_made=embankment to both.

So, IMO the todo is
- remove presets/embankment.json
- make man_made/_embankment.json searchable (and remove "_" from filename)
- move the translations accordingly

Note: Both presets where added in https://github.com/openstreetmap/iD/commit/9e6eacb6982526b53e5bff407496163f201d9843 but with no special comment about why one is prefered.

**Comment by bhousel** [comment]
It looks like the recommendation was `embankment=yes` until around 2015-ish? 
[see diff](https://wiki.openstreetmap.org/w/index.php?title=Key%3Aembankment&type=revision&diff=1609358&oldid=1251702)

iD's embankment presets were added in 2013, which is why they are like that.

(Not all embankments are `man_made` right?)

**Comment by tordans** [comment]
Thanks, that explains how this came to be.

I agree with the fact that man_made=embankment kind of excludes natural embankment, but for some reason the wiki page does not talk about this :-/. I also feel like `natural=embankment` would be the better tag for the embankment=yes-case (corresponding to [natural=cliff / Wikipage](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dcliff)), but that is [only used 18 times](https://taginfo.openstreetmap.org/tags/natural=embankment#overview).

Usage stats:
- `embankment=yes` is used 146,3760 times but 63.2% of that are on highways, so only **54,212** are stand alone ([Taginfo](https://taginfo.openstreetmap.org/tags/embankment=yes#overview))
- `man_made=embankment` is used **68,1950** times and therefore wins the race just barely

What should be the next step?

Is it helpful to ask on the tagging mailinglist?
Or should both tags be added with description of "embankment (man made)" and "embankment (natural)"?

**Comment by bhousel** [comment]
> What should be the next step?
> Is it helpful to ask on the tagging mailinglist?
> Or should both tags be added with description of "embankment (man made)" and "embankment (natural)"?

Yes ask on the tagging mailing list..  Whatever people decide, they should definitely let the editor and carto developers know.

From reading [here](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dcliff#When_not_to_use),
I guess `natural=cliff`, `man_made=embankment`, and `barrier=retaining_wall` are all similar kinds of things.

**Comment by matkoniecz** [comment]
> embankment=yes is used 146,3760 times but 63.2% of that are on highways, so only 54,212 are stand alone (Taginfo)

embankment=yes is to note that something is on embankment (road, railway). 63% is with highway, 22% is with railway=*, 4% with barrier=wall. 

Remaining usages are 11%, so at most 16k are standalone. Note that 4k (3%) of all usages is with man_made=embankment (double tagging that is more likely to occur with standalone embankments).

**Comment by mboeringa** [comment]
> I guess `natural=cliff`, `man_made=embankment`, and `barrier=retaining_wall` are all similar kinds of things.

No, they certainly aren't. 

The only common thing is that the direction of the way and the definition of what is the lower side, are the same, that is, the right side of the line looking in the direction of the line should be the lower side.

**natural=cliff** is for true natural cliffs, like rocky or sandy eroded outcrops along the coast, or other forms of cliffs of generally natural origin.

**man_made=embankment** is a one sided embankment generally "made by man" (although there is some mis-use for things like river eroded embankment. When people micro tag, they put two man_made=embankment tags on either side of a raised railroad or road.

**embankment=yes** is a kind of shortcut for the above: it kind of implicity assumes a two sided embankment, like a raised railroad of road of a viaduct. Generally, when micro digitized man_made=embankment are added, it is wise to remove any embankment=yes tag, as it no longer provides useful information (and certainly not visually on the map).

**barrier=retaining_wall** is a concrete or stone (masonry) wall holding back a sand body / raised level of soil, like when a tunnel is dug, then entrance roads generally have barrier=retaining_wall structures on both side of the tunnel entrance.

**Comment by mboeringa** [comment]
As to rendering examples (from my personal ArcGIS Renderer for OpenStreetMap):

**natural=cliff:**
![afbeelding](https://user-images.githubusercontent.com/7635726/47011277-cf8cf100-d141-11e8-85ea-ccc4f6540f89.png)

**man_made=embankment** tagged on way features that aren't highways or railways:
![afbeelding](https://user-images.githubusercontent.com/7635726/47011579-96a14c00-d142-11e8-9b26-d5a0ad2b4e5d.png)

**embankment=yes** tagged on highway (AFAIK no my personal ArcGIS Renderer is currently the only renderer supporting this):
![afbeelding](https://user-images.githubusercontent.com/7635726/47011404-27c3f300-d142-11e8-8da3-c6268cb4099f.png)

**barrier=retaining_wall** as, in this case, the reinforced sides of a canal (but retaining wall do not have to be associated with water features)
![afbeelding](https://user-images.githubusercontent.com/7635726/47012321-59d65480-d144-11e8-81f1-1f8684c728e5.png)

**Comment by mboeringa** [comment]
@tordans 

> Hi @mboeringa, I see that you invest quite some time in defining the different tags.

My remarks and definitions are largely based on the Wiki and formost real world usage. For anyone having looked a lot at the data as well, you'll likely come to the same conclusions for the majority of cases.

> The question is at [#5344 (comment)](https://github.com/openstreetmap/iD/issues/5344#issue-365147109) – Should a stand alone embarkment be tagged with `embankment=yes` or `man_made=embankment`.

You should first give an example or show a picture of what you mean with a "stand alone embankment"... 

Most cases of two sided embankments (linear raised feature with two sides going donw) I can think of, especially when man_made, are called "dikes", and should be tagged as **man_made=dyke**. The Wiki definition of man_made=dyke is already broad enough to also include oil/fuel spill containment dikes around **man_made=storage_tank**, e.g. in a harbour:

*"An embankment built to restrict the flow of water **or other liquids(!)**."*
https://wiki.openstreetmap.org/wiki/Tag%3Aman_made%3Ddyke

man_made=embankment is not suitable as a replacement, as it is currently used for single sided embankments. You need to add two man_made=embankment lines to visually represent a man_made=dyke, but why would you want to do that? (Well, actually, I know of a few examples here in the Netherlands of people micro tagging dozens of kilometer long dyke structures like that, with two lines of man_made=embankment, IMO a bit senseless...)

> And as a follow up question: If the correct way is `man_made=embankment`, how would one tag a non-man-made embankment? – see [#5344 (comment)](https://github.com/openstreetmap/iD/issues/5344#issuecomment-425689053), last line

Well, there is the proposal page for the **natural=river_terrace** tag:
https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:natural%3Driver_terrace

Especially the linked Wikipedia page about Fluviual terraces:
https://en.wikipedia.org/wiki/Fluvial_terrace
is what I think many people will currently mistag with either **man_made=embankment**, or **natural=cliff**. 

Of course, besides the action of water erosion caused by a flowing river, there is at least seismic activity or fold lines that may occassionaly lead to an "embankment" or "terrace" like structure as well, but will probably usually be covered by natural=cliff or natural=ridge.

While not official, after some research using Overpass Turbo, I have come to the conclusion that the **natural=river_terrace** tag, where used, is used appropriately for the majority of cases. As a consequence, I have added rendering support for this tag in my own renderer. Unfortunately, the Wiki page for natural=river_terrace does not yet prescribe the same "right side is low side" rule as for embankments and cliffs. I think this should be amended. As a consequence, some of the symbology is off (my renderer assumes the same right side rule). A nice example is this one of the Puerco River in the western US:

![afbeelding](https://user-images.githubusercontent.com/7635726/47035845-40043400-d17b-11e8-8b21-434d68a00a86.png)

> The question is at [#5344 (comment)](https://github.com/openstreetmap/iD/issues/5344#issue-365147109) – Should a stand alone embarkment be tagged with `embankment=yes` or `man_made=embankment`.
...
> What is your take on those questions above?
> Thanks

Back to the original question: I agree that embankment=yes, _when not used on a highway or railway feature_, is less than ideal and should probably be replaced by other tags like **man_made=embankment/dyke**, or **natural=cliff/river_terrace**. 
So if your question pertains to just **embankments=yes** tagged ways without any additional highway/railway tag, than yes, I agree this has little value. Using more descriptive and clearer tags like the ones suggested, is more appropriate.

**Comment by matkoniecz** [comment]
> Unfortunately, the Wiki page for natural=river_terrace does not yet prescribe the same "right side is low side" rule as for embankments and cliffs. I think this should be amended.

Good idea - I would support edit encouraging such tagging (there is no good reason to not encourage this consistency).

**Comment by bhousel** [comment]
Thanks for the great discussion, everyone!  

From reading all your responses, it sounds like `man_made=embankment` is preferred, so I switched the preset to use that tag in c3ac440

I left `embankment=yes` as a non-searchable preset, so iD will still recognize the legacy tag.

**Comment by mboeringa** [comment]
Is OK with me.
