### ISSUE TITLE
Highway nodes should not automatically snap to landuse nodes

### ISSUE THREAD

**Issue by bdxd111** [openstreetmap/iD#5369]
Normally, landuse should almost never be connected to a road. However, a lot of new mappers don't know this. As a result new mappers sometimes connect a road to a bit of land. Ofcourse not on purpose, but it should not be so easy to do this. I feel the user should at least be discouraged to do so. 

Adding a right click option for a node to merge with nearby nodes could easily prevent these accidental errors.

**Comment by 1ec5** [comment]
Just wanted to point out that there are regions where the local mapping community has decided that it is desirable to connect landuse areas and boundaries to roadways in some cases ([a nuanced example](https://wiki.openstreetmap.org/wiki/Ohio/Map_features#Land_use)). That said, iD does filter out boundaries by default, probably to prevent unintentional and extraneous connections to roadways.

**Comment by bhousel** [comment]
I can think of examples where is is ok for a highway node to join to a landuse node.  For example when the highway enters perpendicular, like at this gate node:

<img width="500" alt="screenshot 2018-10-08 22 56 18" src="https://user-images.githubusercontent.com/38784/46644231-6c9dc780-cb4d-11e8-8a99-9899ee384f69.png">

I think instead of making it hard to join a line to an area, we should just make it easier to disconnect them if they are wrong.  (#4245)
