### ISSUE TITLE
Make "search worldwide" look more like a button

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5373]
This link lacks affordance.. It should look more like a button.

<img width="953" alt="screenshot 2018-10-06 14 26 20" src="https://user-images.githubusercontent.com/38784/46574592-b7fc7e00-c973-11e8-9ac7-a0f0eb114138.png">

**Comment by boothym** [comment]
On a related note - it would be good if you could just search for an OSM object id, without specifying if it's a node/way/relation.

For example, when you copy a node id from the OSM website or url, instead of just pasting it in you need to add "n" before it. iD should allow you to search without the prefix, and then display the node/way/relation to choose from if they exist.
