### ISSUE TITLE
Update imagery

### ISSUE THREAD

**Issue by NKAmapper** [openstreetmap/iD#5412]
The owner of the [Helsinki region orthopho](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/fi/hri-orto.geojson) WMS imagery has asked us to change the attribution text and the name of the service. The update was made in ELI 8 September 2018 and they are asking why the updates are not showing up in iD.

Would it be possible to make a special update of iD for this imagery?

It would of course be a lot more flexible if iD could update from ELI automatically, perhaps daily or weekly.

**Comment by bhousel** [comment]
> Would it be possible to make a special update of iD for this imagery?

I'll release another version of iD before the end of October that will include the new attribution text.

> It would of course be a lot more flexible if iD could update from ELI automatically, perhaps daily or weekly.

yep that's #4994 - it can't happen currently because ELI doesn't actually issue stable releases like all the other software that iD depends on.  I'll probably end up rewriting it someday.  Anyway faster turnaround on imagery attribution text changes is not really a huge priority for most people.
