### ISSUE TITLE
Spinoff request: standalone Line editor

### ISSUE THREAD

**Issue by answerquest** [openstreetmap/iD#5426]
Hi, iD editor is fantastic. Amazing to see something like this achieved in a web browser.  
Can we take the line-editing functionality out to a standalone line editing script? For example, I have a map with about 10 polyline features rendered on it. I'd like to edit them the way I can edit lines in OSM. The red glow when you select it, the context menu on right-clicking, the line-extending, line splitting : all of it!

I understand this would be quite some work for the development team which wouldn't necessarily count towards OSM itself, but man the mapping world can really use your tech! If you can even just point out here specifically what functions / classes etc are being used then it could be possible for someone to fork it out. And hey, who knows, maybe someone can add a cool new feature and pull-request it back in here!

**Comment by bhousel** [comment]
Hey @answerquest  - thanks for the kind words. I've also thought about building this.  

Today a lot of people use geojson.io as a generic feature editor.  Unfortunately geojson.io is currently unmaintained.  I'm interested in doing some maintenance on it, but I have realistically about 1-2 weekends/year to devote to it, so it's really just the occasional issue triage and PR merge.  This makes me sad.

Realizing my personal ability and time limitations, it would be easier for me to build a generic geojson editor using iD as a base than it would be for me to maintain another project.  Doing this would also give me insights into how to better modularize iD into the kind of project that can be reused for other things (and there is value in spending time on this).

Hope you understand if I just close this issue here as not really actionable, but something that I'll think about.

**Comment by answerquest** [comment]
Hi @bhousel , thanks for giving the background. No problems.
