### ISSUE TITLE
Filter for panoramic streetlevel images 

### ISSUE THREAD

**Issue by joecaruso** [openstreetmap/iD#5433]
Similar to #4518 it would be nice if there was an option to filter for only panoramic (360) images.  These images should (ideally) be higher quality and more useful for mapping so it would be nice to be able to easily see where they're available, which can be more difficult is high coverage areas.

**Comment by BjornRasmussen** [comment]
I was about to create an issue for this, because of the vast amount of street level imagery that @joecaruso  has been collecting in our area. :grin: Anyway, in [our area](https://www.openstreetmap.org/edit#map=20/35.78266/-78.65526), Mapillary coverage looks like this: 
![image](https://user-images.githubusercontent.com/37753777/53527613-73ee4f00-3ab5-11e9-9c98-133cb1af2a83.png)  
  
... so selecting only the newer 360 photos to view can be very difficult without zooming in a bunch.  Could a small checkbox be added along with #5913 to help with this issue?

**Comment by quincylvania** [comment]
I added the photos section and pano filter options!

![pano photo filter demo](https://user-images.githubusercontent.com/2046746/54381787-face2a80-4664-11e9-8d84-214d8f2dbc9d.gif)
