### ISSUE TITLE
Mention how to lasso all layers

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#5440]
Help says

> Multiselect
> Shift+ left-click to select several features together. This makes it easier to move or delete multiple items.
> 
> Another way to select multiple features is to hold down the Shift key, then press and hold down the  left mouse button and drag the mouse to draw a selection lasso. All of the points inside the lasso area will be selected.
> 

1. Are you sure you want to say All of the **points** or All of the **items**?

2. There still needs to be mentioned a way to select all the areas within the lasso. Or mention if it is not currently possible.

For instance on https://www.openstreetmap.org/edit#map=23/24.18987/120.86389 one sees
"13-059" but there is no way to select the item containing it, lasso or not.

**Comment by bhousel** [comment]
> 1. Are you sure you want to say All of the **points** or All of the **items**?

It selects points only.

> The current behavior is quite confusing due to being unexpected, and it limits applications of the lasso selection significatly.

I don't know what to say.  I just opened iD and tried lasso selecting some things, and it seemed really clear to me that it was just selecting points only.  There are plenty of hints in the UI  how they look selected, and what the sidebar shows, and what things you are allowed to to with the selected points.  Just because you find a thing confusing doesn't mean we are going to change it.

I think users are able to just try out the lasso and see what it does.   We don't need to rewrite the help to describe all the things that lassos don't currently do.

**Comment by jidanni** [comment]
In Help I would make 'points' bold, to show that you really just mean points.
