### ISSUE TITLE
Should type=multipolygon be shown for areas?

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/iD#5450]
When creating a relation and choosing the preset for _type=multipolygon_, the multipolygon preset also appears in the preset dropdown for areas. This is because areas are also marked as valid geometries in the multipolygon preset file:
https://github.com/openstreetmap/iD/blob/05709565f0ccb8d07e31bb23f66122f8d52fb4b1/data/presets/presets/type/_multipolygon.json#L3-L5
 
Does it make sense to remove the area geometry from this preset as this is probably confusing to newbies and can also displace more relevant presets from the suggestion list? [Taginfo](https://taginfo.openstreetmap.org/tags/type=multipolygon) shows that currently 9386 ways have this tag.

![multipolygon on area](https://user-images.githubusercontent.com/31667811/47749147-c301b000-dc8c-11e8-8fdd-ebf73d833017.png)

**Comment by bhousel** [comment]
> Does it make sense to remove the area geometry from this preset as this is probably confusing to newbies and can also displace more relevant presets from the suggestion list? [Taginfo](https://taginfo.openstreetmap.org/tags/type=multipolygon) shows that currently 9386 ways have this tag.

It looks like the multipolygon preset still needs to match `area` geometry in order to select the multipolygon after the shape has been created.  (without it, we will only ever select the outer, not the whole multipolygon relation).

But I agree we should remove non-searchable presets from the preset recently-used list.
