### ISSUE TITLE
Object modified if it is added to and then removed from a relation

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#5458]
It seems that somehow iD set this relation https://www.openstreetmap.org/relation/3359493 (at https://www.openstreetmap.org/changeset/64125080) as `modified`  even though nothing was changed on it.

Nothing can be seen at http://osm.mapki.com/history/relation.php?id=3359493, https://osmlab.github.io/osm-deep-history/#/relation/3359493 or JOSM's history, for example (no tags or members were modified).

Reverting this changeset also doesn't modify the relation (which also corroborates that it was unnecessarily set as `modified`)

Trying to do a quick test I wasn't able to reproduce this, but maybe there is some corner case in the code that caused this.

**Comment by smaprs** [comment]
The problem I see with this issue is that if for any reason iD inadvertedly modifies the version of an objetct even if there's no actual change in it, the confidence in objects stability for any retrieving purpose is lost. It may led to a mess in QA when expecting to distinguish between modified & non modified objects. Thank you naoliv.

**Comment by hikemaniac** [comment]
This happens when adding a member to a relation and deleting it. When the member is removed again and the relation returns to its original status, iD will report it as changed anyway.

![relation without changes](https://user-images.githubusercontent.com/31667811/48083780-5b041a00-e1f6-11e8-8a48-6664eb195c8f.gif)

**Comment by naoliv** [comment]
Yep, I can confirm that it's reproducible in this way.
@bhousel remove the `bug-cant-reproduce` tag? :-)
