### ISSUE TITLE
Add presets to basin tag

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#5497]
It would be cool if there was presets on basins for basin=* tag and also the intermittent=* tag. As it is, only 20,401 out of 212,641 basins are tagged with which type they are and only 2,213 are tagged as intermittent. I imagine the numbers for both would increase a lot if there were presets for them. 

Thanks

**Comment by bhousel** [comment]
Sure - looking here for reference:  https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dbasin

I have questions, and I'm mostly asking because I don't want people to complain later.

> I imagine the numbers for both would increase a lot if there were presets for them.

Is this a thing people really want?  Just "increasing numbers" isn't a good enough reason to provide fields for things in iD.  Maybe the reason the numbers are low is because the the tags are not interesting or useful.

Would people really be able to tag whether it's an `infiltration`/`detention`/`retention` basin?

Aren't all basins really `intermittent=yes`?  They are for when it rains, right?

Trying to see things from the perspective of a casual contributor - I just don't see the point.  If people really want this, I'm ok with adding it, but I don't like to add fields just because someone wrote some things on the OSM wiki.   (This reminds me a lot of the fire hydrants in #5488)

**Comment by Adamant36** [comment]
I can understand where your coming from with the retention type tags. The fire hydrant thing was a little ridiculous also. But I think its important to add intermittent tags to all water bodies in general if they are intermittent because they display differently on the based on it and intermittent is just a useful thing to know overall. More so with basins though because looking at it a from a higher zoom level it might not be obvious what's a basin and what's just a pond. The intermittent tag helps with that to some degree. Id assume there are some basins that aren't intermittent to, like nuclear waste/industrial/agriculture/water works retention basins that are full pretty much all the time. Although they don't seem to be covered in the wiki for basin types for some reason, but people do tag those types of things as basins "shrug." So, leave out the type. I'm fine with that. Intermittent should at least be in there. Or maybe you could make the same argument for removing it from the ponds preset.

**Comment by bhousel** [comment]
I'm ok with adding both `basin` and `intermittent` tags..  Again, just really wanted to discuss it first.

- If somebody is using a tag and they really care about it, then we should try to add it.  (`intermittent` definitely meets this category, and `basin` seems pretty harmless)
- If somebody was just looking through the OSM wiki for things missing from iD - well, we should discuss first.  The OSM wiki is full of opinions and bad ideas.  It's not a spec!  We not going to be able to add everything, and often saying "no" is the right choice. 
- Encouraging tagging for the sake of tagging is not what we do here.  Our main goal is to make people, particularly newbies, enjoy mapping.  Showing too many or too complicated fields works against that goal.

**Comment by Adamant36** [comment]
Thanks for adding the preset and for giving the explanation about the project. Its good to know the purpose of it. I'll try and be more mindful of the projects goals when opening issues from now.
