### ISSUE TITLE
Shrink the directional way markers slightly

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5533]
I would suggest these be much subtler. In particular, guard rails are placed along the roads, which means they will run parallel to the road and the arrows will point at the road. In practice, this means they overlap (some here are in the wrong direction):

![noisy](https://user-images.githubusercontent.com/3857299/49224620-8e4b5a80-f3ea-11e8-8613-aa4b6444dfe8.png)

Here's a more zoomed-in example, which would be a typical "editing zoom":

![noisy2](https://user-images.githubusercontent.com/3857299/49224619-8e4b5a80-f3ea-11e8-8470-1a52edbd9071.png)

I would say the arrows should be no more than half the current size and without a gap between the line.

_Originally posted by @RudyTheDev in https://github.com/openstreetmap/iD/pull/5529#issuecomment-442834695_

**Comment by huonw** [comment]
The reason for the gap is that I couldn't get the version without a gap to look good at all, due to the dashed line. For it to look good, I think the triangles would at least need to be synchronised to the dashes e.g. always attached to the middle of the long section. (It'd be awesome if someone more skilled in the ways of SVG/CSS/D3 could work out how to do this reliably, I couldn't!)

Making them smaller should be simple enough, though. (I don't think I'll personally have time to do anything towards it until at least next week.)

(See also https://github.com/openstreetmap/iD/issues/1475#issuecomment-442368951 for another request for things to be subtler, at least for `barrier=kerb`.)

**Comment by jguthrie100** [comment]
@huonw i've never worked with SVG before, but it should be as simple as working out the length of the repeating pattern of the dashed line and just scaling the arrow SVG so it repeats at the same frequency!

**Comment by bhousel** [comment]
I made them half the height that they were before, and it seems a little better:


<img width="725" alt="screenshot 2018-11-30 01 59 34" src="https://user-images.githubusercontent.com/38784/49273662-bca95400-f443-11e8-86d8-a3e230a64e74.png">
<img width="700" alt="screenshot 2018-11-30 01 59 42" src="https://user-images.githubusercontent.com/38784/49273663-bca95400-f443-11e8-9f63-0608236f1191.png">
