### ISSUE TITLE
Update translations for released version of iD

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#5549]
As there was a longer release cycle: Is it possible to update translations from Transifex for the released Version on a regular basis, e.g. once daily? In that way translators may be more motivated to update translation betreten releases.

**Comment by bhousel** [comment]
Yeah this is #4994.  I tagged it bluesky because I don't think it's actually possible to do directly in iD. 

We might be able to do something like create "merge" translations (start with "release" and overwrite with the keys from "latest" but don't delete anything), and host those files on ideditor.com and have iD look there first before falling back to the bundled ones.

My first duty is really to the users of iD to make sure they are getting a good experience.
