### ISSUE TITLE
Wikipedia above wikidata in add field listing

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5557]
Should be the other way about so that it is in alphabetical order, also telephone shouldn't be above all the "S" fields.

**Comment by quincylvania** [comment]
Thanks for noticing that! The wiki field ordering was intentional. The rationale is that Wikipedia is likely more familiar to casual mappers, and so should appear first. Wikidata is related but is more of an advanced tag, so that field should appear directly afterward. If there's a consensus that alphabetization is more important, we can revisit this behavior.

I'm not sure about the telephone field. Each preset manually defines the order for its default fields and these appear above the automatic fields. Perhaps the S fields were defaults while the Telephone field was automatic. If you provide an example feature I can take a closer look.

**Comment by bhousel** [comment]
Closing here because I think the order is appropriate for _today_.  We may change it. 

People are really familiar with the Wikipedia field, and Wikidata is a newish thing.  I feel like OSM will just  start to switch over to using a `wikidata` tag for everything that's notable or needs a stable id, and we can have Wikipedia sitelinks displayed nearby as a byproduct of that.  We don't even really need a `wikipedia` tag.
