### ISSUE TITLE
Wikidata fields showing non-local language data

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5563]
This city node is showing non-English information in the wikidata fields for my en-GB browsers (Firefox/Chrome):
![capture](https://user-images.githubusercontent.com/16965772/49595791-b39f1200-f970-11e8-8948-28a50ae155be.JPG)
Seems to be coming from the Wu Chinese name and French description here: https://www.wikidata.org/wiki/Q182923

**Comment by 1ec5** [comment]
[Here’s the request](https://www.wikidata.org/wiki/Special:ApiSandbox#action=wbgetentities&format=json&ids=Q182923&props=aliases|labels|descriptions&languages=en-gb&languagefallback=1) I’d expect iD to make in this case; it shows “Stirling” and “city in Scotland” as expected.

I think the problem is that we’re passing the browser’s language directly into the MediaWiki API:

https://github.com/openstreetmap/iD/blob/f8f5b690b74ca1aa78d41d2941f403b358845217/modules/services/wikidata.js#L61

The API expects lowercase language codes (`en-gb`), whereas browsers typically supply the region in uppercase (`en-GB`). An unrecognized language code results in [all the languages being returned](https://www.wikidata.org/wiki/Special:ApiSandbox#action=wbgetentities&format=json&ids=Q182923&props=aliases|labels|descriptions&languages=&languagefallback=1), and iD picks the first item in each object: Simplified Chinese for the label, French for the description.

Case aside, it’s possible for the browser to supply a language that Wikidata doesn’t support, or for the browser’s language code to contain some additional detail that doesn’t match Wikidata. (For example, WebKit on Apple platforms would probably use `zh-Hant-TW` instead of `zh-tw`.) We should supply all the browser’s languages via `navigator.languages` (plural) and also add a fallback for English, which is more likely to be understood than a combination of Chinese and French (or whatever happens to be present on the item).

**Comment by bhousel** [comment]
Ah yeah @nyurik showed me how to fix this the other day.. The MediaWiki API lets up request a list of preferred locales and fallbacks.
