### ISSUE TITLE
Pharmacy preset adds healthcare=pharmacy

### ISSUE THREAD

**Issue by Phyks** [openstreetmap/iD#5567]
Hi,

It seems the pharmacy preset from iD (on openstreetmap.org) is adding both `amenity=pharmacy` and `healthcare=pharmacy` tags. Not sure whether this is expected or not but it seems that `healthcare=pharmacy` is not a documented value in [the OSM wiki](https://wiki.openstreetmap.org/wiki/Key:healthcare).

Thanks!

**Comment by bhousel** [comment]
> It seems the pharmacy preset from iD (on openstreetmap.org) is adding both `amenity=pharmacy` and `healthcare=pharmacy` tags. Not sure whether this is expected or not 

Yes, we actually had a request to add this back in 2017 because it was already in widespread use according to taginfo:  https://github.com/openstreetmap/iD/commit/8d6f59c771c0691f0ef129276ffca87aa7532d14

Somebody should add it to the OSM wiki (I notice that there is already discussion about it on the talk page, but nobody got around to updating the main page).

https://wiki.openstreetmap.org/wiki/Key:healthcare

**Comment by Phyks** [comment]
Sorry, I missed the request to add it in 2017. Thanks for the details!
