### ISSUE TITLE
An existing closed way with no tags presents as a line and its difficult to use area presets

### ISSUE THREAD

**Issue by iandees** [openstreetmap/iD#5569]
Thanks to GitHub's related issues thing this appears to be a dupe of https://github.com/openstreetmap/iD/issues/1214, but I thought I'd bring it up again just in case any new thoughts come up.

I came upon [a stadium](https://www.openstreetmap.org/way/244059282) that had had its `leisure=*` tags removed:

![image](https://user-images.githubusercontent.com/261584/49655444-4e92fd00-fa00-11e8-909b-6f6036402275.png)

iD showed it as a generic line preset and when I tried to change it to a stadium preset it didn't include the area-type presets in the list of suggestions. To fix that, I had to manually add the `area=yes` tag before it would show me any area presets.

![linecantbeanarea1](https://user-images.githubusercontent.com/261584/49655588-a0d41e00-fa00-11e8-92d5-50a930b253e2.gif)

**Comment by bhousel** [comment]
Yeah this is #1828 - I started work on it.. It's complicated but probably doable.

The issue is we don't want to let people convert _non_-closed-lines into areas.  Knowing whether a way is closed is easy and the code is there now, but with multipolygons it's impossible to know whether it is really closed without downloading the whole thing.  Maybe we only allow this for closed ways.

**Comment by iandees** [comment]
👍 Like was said before, I don't think this is worth spending a ton of time on. It's pretty rare.
