### ISSUE TITLE
allow several direction=*-values for some things like highway=street_lamp

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#5570]
Hello,
I wanted to ask whether it would be possible to allow more than just one direction=*-value for the highway=street_lamp preset. It's because one node with highway=street_lamp, can have two or more single lamps on/at it which shine into several directions. So often it might be necessary to tag such objects with something like direction=120;300 (two lamps with an angle of 180 between them). But I know it might be hard to do because in most cases, we want to have just one direction value to avoid mistakes. But even not everywhere, so. Some street lamps also have a kind of "360 degree"-glow, so the direction-value would be "0-360"...

**Comment by bhousel** [comment]
Ah yeah, this does actually work if you type your values in the raw tag editor - but it does not work in the Direction field because of #5438.  The field is setup to be _strictly_ numeric and it throws out the semicolon values.  I'm going to close here because it's really a bug captured on that other issue.

<img width="556" alt="screenshot 2018-12-07 14 50 14" src="https://user-images.githubusercontent.com/38784/49669427-5a49e800-fa2f-11e8-8c33-1f95652246f0.png">
