### ISSUE TITLE
Validate incomplete multipoly relations

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#5597]
There are some multipolygons that will not render if they do not have a closed outside way. `type=multipolygon`+`natural=wood` will show nothing if a small piece is missing from the outside.  
I believe the JOSM validator has something similar.

Could a validation check be added for detecting unclosed multipolygons?

**Comment by BjornRasmussen** [comment]
Sounds like a nice idea.  It might not be easy, though, since iD would need to know when multipolygons where incomplete, meaning that some outer ways have not been downloaded yet.  Also, this would slow down iD quite a bit for people with older computers.   
The benefits might, however, outweigh these drawbacks.  ¯\\\_(ツ)_/¯

**Comment by Mahabarata** [comment]
I of course agree with that issue because I opened almost the same a few month ago : see point 2 of <a href="5080">#5080</a>.
The answer of bhousel was : KeepRight (<a href="3452">#3452</a>) and I was agree with that.
The pb now is : the timing.
My issue was opened 6 months ago, the issue about KeepRight  was opened more than 2 years ago.
So the question is (to bhousel) : do you have an idea of the timing for solving these 3 issues ?
Best regards
Mahab

**Comment by bhousel** [comment]
> So the question is (to bhousel) : do you have an idea of the timing for solving these 3 issues ?

Nope!
