### ISSUE TITLE
Road Closures

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#5599]
I'd like to leave #2341 open for the general problem of tagging lifecycle changes to roads.. 

But as a first step, we should make is easy and obvious for users to tag road closures.  Road closures significantly impact the navigability of OpenStreetMap.

Waze does a really good job of indicating where a road is closed.  I'd like to:
- [x] mimic the Waze rendering style 
- [ ] make a field that lets a user mark a road is closed
- [x] maybe also a field to say a date that it's expected to reopen, or at least check whether the closure is still in effect.

![2018-12-13 20 23 38](https://user-images.githubusercontent.com/38784/49983552-766aef00-ff31-11e8-971a-4772bea696af.png)

**Comment by manfredbrandl** [comment]
Sometimes Road Closures are for vehicles only, passing on foot or bike may still be allowed. Could this possibility be included here?

**Comment by bhousel** [comment]
> Sometimes Road Closures are for vehicles only, passing on foot or bike may still be allowed. Could this possibility be included here?

Probably - I still think we'd show the `access` field, so mappers can set those things.

**Comment by RudyTheDev** [comment]
Wouldn't the problem be that Waze has a very quick turn-around for map updates, but OSM can lag many months behind for some providers? As far as I understand, that is one reason to not tag short-term changes, such as road repairs. Plus, Waze users can very easily provide feedback from the app if it's wrong.

**Comment by bhousel** [comment]
> Wouldn't the problem be that Waze has a very quick turn-around for map updates, but OSM can lag many months behind for some providers?

This is really about mapping medium to long term closures (>1 day).  I don't think OSM will ever be the best place to map short term closures and other realtime incidents (<1 day).

Still, I would like to make OSM as good as it can be.  Several companies currently use OSM for navigation and this is a big problem for them.  Both: mapping closures, but also removing them when the closure is no longer an issue.

**Comment by bhousel** [comment]
Added a road closed preset and style..
I'll leave this open until I've added a new field that can toggle the tags.  Switching the preset alone isn't enough to swap something like `highway=primary` -> `highway=construction + construction=primary`.

<img width="740" alt="screenshot 2018-12-17 18 00 08" src="https://user-images.githubusercontent.com/38784/50121006-6ac74300-0225-11e9-9591-984fe84a9391.png">

**Comment by boothym** [comment]
After mapping some construction areas recently due to updated imagery, I was wishing for a **Highway under construction** preset so that I didn't have to keep manually inputting the tag values!

Similar to the landuse construction preset - a highway construction preset would have a "type" field (e.g. residential) and it would keep all the other highway-related fields.
![cons](https://user-images.githubusercontent.com/16965772/50124933-9adf0800-025e-11e9-8275-b3d44784ac46.jpg)

Also, for this road closed preset - what tagging does it expect?  Because you could have a road which is closed to vehicles but not other users, so that would have access tags but not highway=construction.

**Comment by bhousel** [comment]
> A highway construction preset would have a "type" field (e.g. residential)

Yes, that's the part that's still missing from the preset.  I want to be able to retain the road classification when toggling a highway in/out of "closed" status.

> Also, for this road closed preset - what tagging does it expect?

`highway=construction`
`construction=*`  (the "toggle" field I mentioned above)
`access=no`
Also shows `access` field so that users can still grant access to foot/bike/etc if needed.

**Comment by boothym** [comment]
> Also shows access field so that users can still grant access to foot/bike/etc if needed.

Wouldn't data consumers disallow access for everyone if the road is tagged as under construction? I think access tags would only have an affect if the road is tagged normally?

**Comment by slhh** [comment]
@bhousel 
> This is really about mapping medium to long term closures (>1 day). I don't think OSM will ever be the best place to map short term closures and other realtime incidents (<1 day).

OSM does also need to support applications like printing a map on paper or generating a map for a Garmin. Mapping closures shorter than several month seems to be unwanted for this reason.


> Still, I would like to make OSM as good as it can be. Several companies currently use OSM for navigation and this is a big problem for them. Both: mapping closures, but also removing them when the closure is no longer an issue.

To allow mapping closure down to e.g. 1 day, we need to invent a method to define a tempory state without altering the long term data. 
This seems to need:

- extra features to describe the temporary state, which need a taggging invadating them for applications requiring long-term data.
- extra relations which are invalidating their members (some of the long term data features) for applications requiring short-term data.

For the UI:
Provide a mode to edit a short term graph.
When saving, do not save the short term graph, but calculate extra features and extra relations based on comparision of the short-term graph with the long term graph.

**Comment by bhousel** [comment]
> OSM does also need to support applications like printing a map on paper or generating a map for a Garmin. Mapping closures shorter than several month seems to be unwanted for this reason.

A map that doesn't want to show road closures could just style those ways the same as the companion non-closed way.  E.g. just render `highway=construction + construction=primary` the same as `highway=primary`.

**Comment by bhousel** [comment]
> Wouldn't data consumers disallow access for everyone if the road is tagged as under construction? I think access tags would only have an affect if the road is tagged normally?

The data consumers in this case are engines like OSRM, GraphHopper, Valhalla, yes?  `access` tags are super important for them.

**Comment by boothym** [comment]
Yes but if a road is tagged highway=construction then data consumers will ignore the road for routing purposes. Therefore it doesn't matter what access tags you have.

So in the scenario where nobody is allowed to access the road, highway=construction is all that is needed.

However if you want to still allow some access, you need to keep the road highway=<type> as usual and use the access tags instead.

**Comment by bhousel** [comment]
> Yes but if a road is tagged highway=construction then data consumers will ignore the road for routing purposes altogether. Therefore it doesn't matter what access tags you have.

This seems like a really silly thing to argue about.

**Comment by boothym** [comment]
Sorry if I'm not explaining myself clearly. It was just that you said:
> Also shows access field so that users can still grant access to foot/bike/etc if needed.

I'm just thinking about foot/bike access tags on a highway=construction way. Data consumers (routing engines) will not take them into account because highway=construction means the road isn't considered for routing.

So it's fine if the "Road Closed" preset is shown for a road completely closed, with highway=construction + construction=xxx (+ access=no).

But would the "Road Closed" preset be shown for a road with highway=xxx + access=no?

**Comment by bhousel** [comment]
> But would the "Road Closed" preset be shown for a road with highway=xxx + access=no?

It's only shown for `highway=construction`+`access=no`
This is the specific combination of tags that iD will match to the "Road Closed" preset - hope that answers your question?

If users want to add other things like `foot=yes` that's ok too.  I don't know how every tag is interpreted by every routing engine, but `highway=construction`+`access=no` should do the job of closing a road in any of them.

**Comment by slhh** [comment]
@bhousel
Using access tags for highway construction is potentially ambiguous, users would likely mix planned access after finished construction witth current access during the construction time using the same keys. This would result in useless data.

> It's only shown for highway=construction+access=no
This is the specific combination of tags that iD will match to the "Road Closed" preset 

Preset name and tag combination mismatch in both directions:

- A road might be closed for many other reasons than construction work, e.g. seasonal closures, wheather conditions, events, nature protection, etc.
- highway=construction+access=no can be a still not existent road, just a construction site in an early state. Therefore, it isnt't a clodes road.

> A map that doesn't want to show road closures could just style those ways the same as the companion non-closed way. E.g. just render highway=construction + construction=primary the same as highway=primary.

Modifing tags of the road according to the state under construction (e.g. access tags) would make the long-term data unavailable for such applications.

Constuction of a new road might last many years. Such applications might not want to render these as an existing road. 

>Still, I would like to make OSM as good as it can be. Several companies currently use OSM for navigation and this is a big problem for them. 

I understand the desire, but we need to avoid  conflicts with other applications. Otherwise, there wouln't be a consent in the community to map such closures, resulting in lower data quality due to less complete mapping of closures.

In addition, we do not only need to support full road closures but also closure of one direction etc.
Reconstruction of a highway might not only induce clossed roads, but also additional temporary ones, e.g. temporary motorway links. We do also need a solution to map these without interfering with applications requiring the long-term data.

>Both: mapping closures, but also removing them when the closure is no longer an issue.

To simplyfy removing we should invent something which keeps the long-term data unchanged.

**Comment by magol** [comment]
I think that it is strange to add a access tag to a highway under construction. When I map a way under construction, I  never add a access key. And if I do, it is to indicate what access restriction the way will have when the construction is ready.

To complain a little more, "Road Closed" may not be the best name choice if it is a completely new road that they are building.

My suggestion is to remove the requirement for `access=no` and rename it to "Road under construction"

**Comment by bhousel** [comment]
> My suggestion is to remove the requirement for `access=no` and rename it to "Road under construction"

This preset isn't for a "Road under construction" 
It's for something like a bridge out or other medium-to-long term closure that affects routing.

OSM don't have a tag specifically for this, but I guess I could invent something different from `construction`.

**Comment by manfredbrandl** [comment]
@bhousel You are on a good way, temporarily closing a road is different from (initial) construction. Maybe temporary_closure could be used as as tag/key to express „medium-to-long term closure“. One could add start and end of closure.

**Comment by matkoniecz** [comment]
> I'm just thinking about foot/bike access tags on a highway=construction way. Data consumers (routing engines) will not take them into account because highway=construction means the road isn't considered for routing.

It depends on router. Data consumers are free to allow routing bicycles through `highway=construction` with `bicycle=yes`

**Comment by ignaciolep** [comment]
> It depends on router. Data consumers are free to allow routing bicycles through highway=construction with bicycle=yes
Do you know if any of most known routers do that? I've just read the OsmAnd's routing profile and they penalize "construction" and "proposed" tags.

I support @bhousel proposal. That's the de facto use. For example in Buenos Aires City we have a bridge being demolished to build a new viaduct and the local editors community naturally converted the highway=primary to highway=construction + construction=primary.

https://www.openstreetmap.org/way/648168789

**Comment by tyrasd** [comment]
Closing because modelling the accessibility of a road via a preset is not the right approach: OSM uses the `access` tag for that (which iD already supports), while the [`highway=construction`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dconstruction) tag is meant to be used for roads under construction specifically.

In https://github.com/openstreetmap/id-tagging-schema/commit/dd1705e5a7b1b3e83fe37eeb1ad91a45605c0d04, I've changed the current _Closed Road_ preset into one that matches all `highway=construction` ways titled _Road Under Construction_.

A better way to make mappers aware of using the access field for roads that are closed for non-construction reasons would be to leverage the idea of #8904.
