### ISSUE TITLE
Change PT to PT-PT (Portugal) in Transifex

### ISSUE THREAD

**Issue by xendez** [openstreetmap/iD#5600]
As explained in https://www.transifex.com/openstreetmap/teams/75542/discussions/ by another user, coordinator in Portuguese (PT) translation, "request to change PT to PT-PT (Portugal), to avoid brazilians users to translate PT-PT instead of PT-BR".
Because of that, the previous translations are now "reviewed" and can only be changed by reviewers and coordinators. This is not very convenient.

I could request pt-PT language and then copy/paste all translations, but to my knowledge, that doesn't copy the original authors and I would be the only translator (this is a "bug" in Transifex side).

It is possible to "move" those translations or there is another solution?

**Comment by bhousel** [comment]
Sorry, I think we need to leave 'pt' as the default Portuguese language, otherwise there won't be a default code for iD to fallback to.  The locales really need to match strings that are reported by your browser.

I understand that it's not very convenient to review each translation, but I still think that's the best way to make sure your users are getting good translations.  (this for any language, not just 'pt')

**Comment by xendez** [comment]
Ok. Who should I contact to be a reviewer in Transifex? I've asked a month ago to one coordinator but I didn't had an answer. Unfortunately we have many translators in "pt" but not even 1 reviewer...

**Comment by bhousel** [comment]
> Ok. Who should I contact to be a reviewer in Transifex? I've asked a month ago to one coordinator but I didn't had an answer. Unfortunately we have many translators in "pt" but not even 1 reviewer...

Send me a message on Transifex and I will add you as a coordinator for 'pt'
