### ISSUE TITLE
Fix tanning salon preset

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#5688]
I recently added a tanning salon by typing and selecting the preset, but realised it tags the place as `shop=beauty` and `beauty=tanning`. 

[According to the wiki](https://wiki.openstreetmap.org/wiki/Tag:leisure=tanning_salon) the correct tag is `leisure=tanning_salon`, which is what I remember manually tagging a couple of years ago, and certainly makes more sense as it's not really a "shop".

Of the 851 which are tagged with the shop/beauty combo, 772 were last modified after 2016-11-15, the date iD 2.0.0 was released, which makes it seems like those have come from the iD preset.

**Comment by bhousel** [comment]
[According to this other page on the wiki](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbeauty) `shop=beauty` includes tanning salons too.

[And the talk page for `leisure=tanning_salon`](https://wiki.openstreetmap.org/wiki/Talk:Tag:leisure%3Dtanning_salon) is just people talking about how it doesn't fit under "leisure".

[And the talk page for `shop=beauty`](https://wiki.openstreetmap.org/wiki/Talk:Tag:shop%3Dbeauty) lists tanning as the first example in 2009.

Sorry but since both tags have really low numbers, and I really think it fits more in with beauty shops (like nail salons) than leisure activities (like bowling alleys and sports centers), I'm inclined to just leave it as-is.
