### ISSUE TITLE
Drag-and-drop reordering of relation members

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5727]
The order of the members in OSM relations is non-random and is saved in the database. While the order doesn't matter most of the time (think multi-polygons), it is [critical for some relations such as routes](https://wiki.openstreetmap.org/wiki/Relation:route#Order_matters).

iD should let users re-order members in the list via drag-and-drop.

<img width="374" alt="screen shot 2019-01-18 at 8 41 59 am" src="https://user-images.githubusercontent.com/2046746/51390316-f53ce400-1afc-11e9-890a-c84bc3e8f4a9.png">

**Comment by quincylvania** [comment]
Closing as duplicate of #2283.

**Comment by bhousel** [comment]
This is a great idea!  It would probably be worth rethinking this control to make it more like a table with draggable rows, and less like a list of things.

**Comment by slhh** [comment]
@quincylvania, @bhousel
Let's discuss what drag and drop support means for public transport.

It would enable experienced users to maintain the sequence of stops and platform, and enable the less experieced one to disturb the order of the stop/platform pairs.

A countermeasure could be to glue the stop/platform pairs in the member list together as an atomic unit in view of dragging.
In some rare situations wrong stop/platform pairs can get glued due to a temporarily wrong order. The user needs to be able to fix this. We could define a key to be pressed during dragging to consider all pairs as unglued for this single drag action.

PTv2 does also require the member ways to be sorted. A pure drag and drop sorting would be inadequate.
Routes can have a huge number of ways, this would need long distance drags over multiple page heights. Identifying the position where to insert the dragged items is hard, or at least not fast.

Separating stop and platform members from the other ways could also require nasty long distance drags. Therefore, we should separate them automatically.
