### ISSUE TITLE
open combobox if anywhere on box clicked coming from auto-filled key-box

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5752]
Starting from: 
Usability >> Open the combobox when clicking anywhere in the text field (#5596, #5636, thanks @maxgrossman)

There is a minor additional request for potential usability optimization.

The opening of the combobox is working well for a lot of situations now, but it will not happened when you come before from an auto-filled key box (left-hand side), see movie:
.
![open combo box after autofill](https://user-images.githubusercontent.com/27923772/51664062-cfaa5180-1fb8-11e9-9707-f0cd3563429f.gif)

**Comment by bhousel** [comment]
One of the issues with our combobox control is that - it dispatches `accept` and `cancel` events so that calling components can adjust the value selected (for example to check that the string entered _or autocompleted_ is really a valid thing).  These events fire on a bunch of different triggers, but they do not fire on `blur` (field loses focus), and they probably should be changed to fire there only (not on tab, return, click, etc). 

I did a bunch of work 2 days ago in 4583e2d4d and 0c7b9a631 to fix some issues caused by the event firing and autocomplete and situations that can break places that comboboxes are used.  It's pretty complicated, but before I forget everything I learned, I'd like to spend another day on improving the combobox to be more reliable.

(this comment is probably really only helpful for my own memory and doesn't make much sense to anyone else reading - sorry)
