### ISSUE TITLE
Issues with OSM Wikibase links

### ISSUE THREAD

**Issue by my-na-me** [openstreetmap/iD#5753]
Starting from this:

Localization >> Fetch multilingual tag descriptions and images from the OSM Wikibase (#5647, thanks @nyurik)

I don't like the current way to offering/showing this to the iD-Editor end-user:
When you click on the "i" (i for information?) then I expect to see an instant view to any help* or a wiki* documentation or a direct link to any help* or a wiki* documentation (*human readable) instead of a link to an option or link to edit any documention.

Current view:
![2-osm-wiki-link](https://user-images.githubusercontent.com/27923772/51665553-50b71800-1fbc-11e9-8027-6e8a6a9266a8.jpg)

So the option to edit the documentation should not shown in the "i-information" chapter

Expected view:
![4-osm-wiki-link](https://user-images.githubusercontent.com/27923772/51666659-b4424500-1fbe-11e9-9d60-2262ec97bd86.jpg)

Or at least below the osm-wiki link:
![3-osm-wiki-link](https://user-images.githubusercontent.com/27923772/51665563-557bcc00-1fbc-11e9-8385-b59117c9b369.jpg)

By the way, why it is telling "There is no documentation available for this key" for `highway=service` ?
![5-osm-wiki-link](https://user-images.githubusercontent.com/27923772/51666883-02efdf00-1fbf-11e9-9145-48c5448de7d7.jpg)

**Comment by bhousel** [comment]
@my-na-me I'm ok with the links being how they are, but I am concerned that the documentation isn't filled in and links to wrong pages.

@nyurik any ideas what is going on?
I don't see any description for the [highway=service](https://wiki.openstreetmap.org/wiki/Item:Q4760) tag.
Also the "View documentation" link goes to a Greek page.. the sitelink language looks wrong.

**Comment by nyurik** [comment]
@my-na-me thx for the feedback! I think we should iterate on the design of the edit link, e.g. we could do this (i'm not a designer, suggestions are welcome): 
![image](https://user-images.githubusercontent.com/1641515/51687756-316eb980-1fc1-11e9-89e8-c93290d9804e.png)

I do not want to visually separate description from the link to edit that description, as that may cause confusion.

@bhousel The issue with `highway=service` was due to the incorrect `lang` parameter on the wiki page, I [fixed it there](https://wiki.openstreetmap.org/w/index.php?title=El%3ATag%3Ahighway%3Dservice&type=revision&diff=1780227&oldid=1772999), and it will be fixed in the data item the next time I run my bot.  The wiki docs property (P31) is very new, so some bugs are still lurking. I will also update the bot to ignore the lang param, and instead use the language of the page title. Thx for reporting!

@my-na-me I suspect you didn't see the docs link for `highway=service` because my bot only filled in that data yesterday, and it might have been after the new version of iD has rolled out.

**Comment by nyurik** [comment]
P.S. @my-na-me you can also talk to us directly on OSM Slack - [get an invite](https://osmus-slack.herokuapp.com/).

**Comment by nyurik** [comment]
While on the subject of design, should we:
* if both key & tag data items exist, show description for the key AND description for the tag if both are available?
   * what if tag is described in English, but key has the description in the local language?
* offer two **[edit]** links - for both the tag and for the key data items?

**Comment by my-na-me** [comment]
@bhousel 
Thanks for updating my long title version :-)

I'm not so OK with the link order, I would like to see "View documentation" (=> with link to the osm wiki key=value) as top line.

@nyurik 
![view-docu big](https://user-images.githubusercontent.com/27923772/51754817-93144e00-20bd-11e9-94d5-c295c09b241f.png)
This looks much better, but as mentioned above, I would like to see  "View documentation" (=> with link to the osm wiki key=value) as top line, (as it was - for a long time - before ;-) ).

PS: Thank you for the invitation link, actually I stopped instant-messaging long time ago, after a pause-period I switched to this [system](https://threema.ch/en). Nowadays this is the one I use (also only on low frequency). If you want, we can meet there.

PSS: I opened a thread in the [forum](https://forum.openstreetmap.org/viewtopic.php?id=65202), let’s see if somebody is interested in this topic and we could get some more input.

**Comment by nyurik** [comment]
@my-na-me I do not think we should show a link to documentation before the short description text.  The **[edit]** should be right next to the description, so that users see how they can change that text, hence the proposed design.  Could you sketch what you have in mind?  Also, see my other question about possibly showing key + tag descriptions / edit links. Thx!

**Comment by nyurik** [comment]
P.S.  Maybe we should give a visual indication that the description we are showing is about a key (when there is no tag-specific description is available)... Not sure about the best design for that either.

**Comment by bhousel** [comment]
> @nyurik any ideas what is going on?
> I don't see any description for the highway=service tag.
> Also the "View documentation" link goes to a Greek page.. the sitelink language looks wrong.

Still seeing this today..  @nyurik how often do the cleanup scripts run?

**Comment by nyurik** [comment]
@bhousel sorry, was a bit swamped with another project. Just ran the bot, and got everything updated.  I will work on automating it very soon - so that the moment wiki page is updated, data items reflect that.

**Comment by bhousel** [comment]
> @bhousel sorry, was a bit swamped with another project. Just ran the bot, and got everything updated. I will work on automating it very soon - so that the moment wiki page is updated, data items reflect that.

Thanks @nyurik looks good now 👍 

I ended up replacing the link with a simple pencil icon.. I like this!

<img width="372" alt="screenshot 2019-02-01 11 47 16" src="https://user-images.githubusercontent.com/38784/52136880-28ac6200-2617-11e9-8d65-79bd47c9b4d6.png">

**Comment by nyurik** [comment]
@bhousel thanks, looks good!  What's the tooltip text?

**Comment by bhousel** [comment]
> @bhousel thanks, looks good! What's the tooltip text?

Oh yeah, it says "edit/translate" on the tooltip.. That just didn't get captured in the screenshot.

**Comment by nyurik** [comment]
Thanks! Also, what happens when the data item exists, but it does not have description in either user's language nor English?  I think we should show a big link "add description" in place of the description text?  Note that most likely there will be no "view documentation" link, so it will be the only link shown. Perhaps we should show some big question mark instead of an image too?

**Comment by bhousel** [comment]
> Thanks! Also, what happens when the data item exists, but it does not have description in either user's language nor English?

<img width="372" alt="screenshot 2019-02-01 16 51 10" src="https://user-images.githubusercontent.com/38784/52156708-e0616400-2657-11e9-8608-0eb6365dcb24.png">

this seems fine..
