### ISSUE TITLE
 Enhancement: Presets for turnstile node, monorail and stop_area_group relation

### ISSUE THREAD

**Issue by sguinetti** [openstreetmap/iD#5757]
Hi, I'd like to suggest adding two presets for rapid transit improvising. These features I discovered when I was editing the map of Tokyo.
* "barrier=turnstile" is used to allow one person at a time to pass with a ticket to the metro/subway station ([wiki](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dturnstile)).
* "stop_area_group" relation for agrupation of one and more stop areas. For example a group for 3 subway stations ("stop areas") around Shibuya (see [relation](https://www.openstreetmap.org/relation/9231615) for real reference and [wiki](https://wiki.openstreetmap.org/wiki/Relation:public_transport#public_transport.3Dstop_area_group))
* "type=route" + "route=monorail" in a route relation, like light rails and subway routes. This helps to distinguish that it is a [monorail route](https://wiki.openstreetmap.org/wiki/Tag:route%3Dmonorail), not only used in Disney but in the United Kingdom and Japan (such as Tokyo Monorail).

Thank you.

**Comment by sun-geo** [comment]
@quincylvania - thanks for adding these presets :-)

btw

@sguinetti 
> * "barrier=turnstile" is used to allow one person at a time to pass with a ticket to the metro/subway station ([wiki](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dturnstile)).

In the barrier=turnstile wiki, I can't see the phrase "with a ticket"...

As I watched for tokyo area the tagging of these barriers: https://commons.wikimedia.org/wiki/File:Keisei-Takasago-Sta-Gate-for-MainLine.JPG 

I found, that people are also using: `barrier=toll_booth` instead of `barrier=turnstile`
https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dtoll_booth
For examples see here: https://overpass-turbo.eu/s/I1P

**Comment by sguinetti** [comment]
@sun-geo Right point. I use this preset toll_booth, too. Although my suggestion is barrier=turnstile because It is focused in confined and pedestrian areas. I forget that it should be complemented with key "fee=yes". If someone has another suggestion, I thank you in advance.
