### ISSUE TITLE
New diet field only tags diets as "yes"

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#5767]
I'm glad #5580 was fixed, but it seems right now iD can only tag diets as `yes`. But it's important to know whether a place is `only`, too, as seen for instance in https://wiki.openstreetmap.org/wiki/Key:diet:vegan

**Comment by bhousel** [comment]
> I'm glad #5580 was fixed, but it seems right now iD can only tag diets as `yes`. But it's important to know whether a place is `only`, too, as seen for instance in https://wiki.openstreetmap.org/wiki/Key:diet:vegan

Sorry @picsi - we're not going to be able to support values in the multicombo fields other than `yes`.  

Users can still use other values down in the raw tag editor, and the multicombo will correctly interpret the values (i.e. it understands `no`, and it won't overwrite a value like `only` with a `yes`).

see #5291 for a bit more description of the current behavior.

**Comment by dkniffin** [comment]
@bhousel (cc @tyrasd since it looks like you're a more current maintainer) I know this is an old issue, but I've also noticed the lack of built-in support for `diet:vegan=only`. I've noticed a lot of vegan-only restaurants (where they serve a menu that only includes vegan food options, no animal products whatsoever) are incorrectly tagged as `diet:vegan=yes`. I wonder if having better support for this in iD would help.

### Current behavior
Right now, if I add "Dietary options" and select "Vegan", it looks like this:

<img width="370" height="92" alt="Image" src="https://github.com/user-attachments/assets/58c4fc0b-ccc2-4439-a6fb-c3b6abf9a02f" />

That checkmark represents "yes", which means "this restaurant has some options that are vegan".

If I click the checkbox, it looks like this:

<img width="370" height="92" alt="Image" src="https://github.com/user-attachments/assets/7a904511-d43d-4eea-afd6-6acf43d0066e" />

That would be `diet:vegan=no`.

If I click it again, it goes back to the `yes` version. No UI way to specify `only`.

If I manually enter the `diet:tag=only`, I get this:

<img width="374" height="91" alt="Image" src="https://github.com/user-attachments/assets/33ae72da-ee5f-4c4e-9098-0595ec2a6df6" />

### Proposal

I can think of two ways to support this in the UI.

1. We could augment the combo field to allow for a third state here. So when you click the checkbox, it cycles to a third option that represents "only". I'm not sure what icon we could use for that. A star perhaps? There's no clear icon to represent "only", that I know of.
2. We change out the UI for this from a multicombo to something else. I propose something similar to `access`. However, it looks like that's a custom field, so we'd likely need a custom field for this too. But dietary restrictions are a common enough thing that I feel it would be worthwhile. Here's a mockup I made for what that could look like:

<img width="369" height="203" alt="Image" src="https://github.com/user-attachments/assets/a3530ee8-8497-42cc-ac0b-e765a047462c" />

Maybe we make a more generic field type like access.js, but without as much stuff hard-coded like access.js has, for situations where there's a group of keys that are related, with a specific set of values that are allowed.

Let me know what you think of this. If it's something you'd be okay adding in, I wouldn't mind building it.

**Comment by tordans** [comment]
> If I manually enter the `diet:tag=only`, I get this:
> 
> <img alt="Image" width="374" height="91" src="https://private-user-images.githubusercontent.com/1680080/599847668-33ae72da-ee5f-4c4e-9098-0595ec2a6df6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODAwMjkxNjAsIm5iZiI6MTc4MDAyODg2MCwicGF0aCI6Ii8xNjgwMDgwLzU5OTg0NzY2OC0zM2FlNzJkYS1lZTVmLTRjNGUtOTA5OC0wNTk1ZWMyYTZkZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA1MjlUMDQyNzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY1MTFlZTRhMWM1NzljMDU2ZDEwYzIyNDY1YTY2YTVkNTdmOGQ2ZDNmNjFjMmRjZDhjODU2NzMwZDE2MGQ0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.erAeWqqNgK0dNEf5cX375vb56TjLlt43Db3gaisgSSY">

In other fields like the dropdown or radiobutton Group we show the raw value with special formatting or in quotes `'only'`. I think we should first look into this so we align how our fields behave with unkown values. This would be an iD issue.

For your other ideas: Changing the field type or adding an option is best discussed in https://github.com/openstreetmap/id-tagging-schema. AFAIK both would also require a change to https://github.com/ideditor/schema-builder. The whole thing is not a quick fix…

**Comment by dkniffin** [comment]
I just found this issue asks for the same thing: https://github.com/openstreetmap/id-tagging-schema/issues/1739

I'll continue the discussion over there
