### ISSUE TITLE
Reversing a oneway tagged with "turn:lanes"

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#5828]
Related to #5674 and briefly mentioned in https://github.com/openstreetmap/iD/pull/5826#issuecomment-458578589.

If I understand how these tagging schemes work correctly, when turn lanes are tagged ~~as `turn:lanes:both_ways` or~~ just using `turn:lanes` on a bidirectional road, then when the way is reversed the order of the values (split by `|`) need to be reversed too (as the lane indexes are based on way direction).

If someone else could confirm that I've understood [the tagging](https://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane) correctly, I'll work on a PR to fix this.

Personal note: It seems pretty silly to me to ever tag turn lanes in this way and not just specify `:forward`/`:backward` for clarity.

**Comment by bhousel** [comment]
I could be wrong, but..

My understanding of `turn:lanes:both_ways` is that it's only ever used for a single center turning lane.  You can't really reverse it.  

![turning-center-lane](https://user-images.githubusercontent.com/38784/51930085-c3aefd00-23c7-11e9-8157-075a2746d189.jpg)

So, for right hand driving traffic, `turn:lanes:both_ways=left` no matter which direction the road happens to be drawn.

> Personal note: It seems pretty silly to me to ever tag turn lanes in this way and not just specify :forward/:backward for clarity.

I agree..

**Comment by SilentSpike** [comment]
Based on the original [turn lanes proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/lanes_General_Extension/ProposalPreVoting#Center.2Fmedian_turn_lanes) it looks like you're correct. What's weird is that the actual [lanes page](https://wiki.openstreetmap.org/wiki/Lanes) (which `turn:lanes` refers to) doesn't mention this case at all.

That still leaves the case of simply `turn:lanes` on a bidirectional road. I can't tell what that should mean exactly and looking at cases using overpass turbo I can only find incorrect tagging (missing oneway, etc.).

**Comment by bhousel** [comment]
Although iD doesn't have a user interface for lane tagging yet, @kepta did create code to parse the OSM lane tags (as best we could determine from the wiki at the time):
https://github.com/openstreetmap/iD/blob/master/modules/osm/lanes.js

and a pretty extensive test suite:
https://github.com/openstreetmap/iD/blob/master/test/spec/osm/lanes.js

So I think those provide the best summary of what iD thinks the tags mean 😄

**Comment by 1ec5** [comment]
> Personal note: It seems pretty silly to me to ever tag turn lanes in this way and not just specify `:forward`/`:backward` for clarity.

`turn:lanes:both_ways` is the successor to the [`centre_turn_lane=yes`](https://wiki.openstreetmap.org/wiki/Key:centre_turn_lane) tag that NE2 pioneered, as discussed in [this diary post](https://www.openstreetmap.org/user/mvexel/diary/42432).

There’s an important distinction between `turn:lanes:forward`/`:backward` and `turn:lanes:both_ways`. (It also isn’t the same thing as `turn:lanes:reversible`, which means the lane could go one way or another but not both simultaneously.) Typically, you’d tag `turn:lanes:forward` or `turn:lanes:backward` starting from the point the lane change restriction begins to the intersection where the driver turns. But with `turn:lanes:both_ways`, the driver may turn at any point along the [center turn lane](https://en.wikipedia.org/wiki/Reversible_lane#Turn_lanes_and_flush_medians).

Simultaneously tagging a single center turn lane as a `forward` lane and a `backward` lane would throw off any statistics about OSM coverage by lane miles, and it could potentially cause incorrect timing of voice guidance by a turn-by-turn navigation application.

> My understanding of `turn:lanes:both_ways` is that it's only ever used for a single center turning lane. You can't really reverse it.

There are some examples of `lanes:both_ways` being used to count reversible lanes or as a hack to account for [extra-wide gore areas](https://www.openstreetmap.org/way/564119310), but that’s kind of tagging for the… I’m not sure what. `both_ways` was [originally proposed](https://wiki.openstreetmap.org/wiki/Proposed_features/Suffix_both_ways) for center turn lanes. 🤷‍♂️

> If I understand how these tagging schemes work correctly, when turn lanes are tagged as ~~`turn:lanes:both_ways`~~ or just using `turn:lanes` on a bidirectional road, then when the way is reversed the order of the values (split by |) need to be reversed too (as the lane indexes are based on way direction).

Any `turn:*` tag’s value should remain unchanged when reversing a bidirectional way. When `oneway=no`, the way’s direction has no relation to the physical road. As a contrived example, a mapper may find it convenient to reverse a bidirectional way to make route relation roles consistent with adjoining ways, without the intention of rearranging the lanes on the road or making the lanes represent the opposite maneuvers. (That’s why `:forward` and `:backward` get swapped.)

**Comment by bhousel** [comment]
ok, cool.. if I'm understanding the parts to this issue:

* Does iD reverse `turn:lanes:both_ways` properly?

Yes, because it doesn't need to be reversed, and iD doesn't do anything to it.

* Does iD reverse `turn:lanes` on a oneway road properly?

iD doesn't currently do anything.  We might consider reversing the parts?

* Do we reverse `turn:lanes` on a bidirectional road properly?  

iD doesn't currently do anything to the value, but it's likely most people would consider this style of tagging is wrong anyway.  A bidirectional road should really have separate `turn:lanes:forward` and `turn:lanes:backward`, which iD supports already.

**Comment by slhh** [comment]
We need to distinguish automatic reversing (e.g. due to merging) from manual reversing:

When reversing automatically, iD must preserve the meaning. Any `*:lanes` key without `:forward` or :backward suffix need reversing the order of lanes in the value. Maybe, we can just disallow reversing the way automatically. In case of a oneway, I think iD wouldn't reverse automatically anyway. Right?
In case the way isn't a oneway, using :forward or :backward suffix is required according to the lanes proposal. In case the suffix is missing, iD might show a validator issue and disable the merging etc. operation, which would require reversing the way. Some keys like `witdth:lanes` and `change:lanes` might be considered to be acceptable for bidirectional roads without using a `:forward` or `:backward` suffix.

When initiating the reversing operation manually, the desirable tag handling depends on the usecase.
The user might either wan't to preserve the meaning or to preserve the tags. Id should ask the user which one is desired, or offer two different operations.
Using the wrong variant of tag handling could be quite nasty where significant lane tagging exists.

**Comment by bhousel** [comment]
> When reversing automatically, iD must preserve the meaning. Any `*:lanes` key without `:forward` or :backward suffix need reversing the order of lanes in the value. Maybe, we can just disallow reversing the way automatically. In case of a oneway, I think iD wouldn't reverse automatically anyway. Right?

iD does automatic reverses sometimes:
- when using the intersection editor, iD will automatically reverse any roads with `oneway=-1`
- when joining ways that aren't drawn with the same direction, iD will reverse if needed.

> In case the way isn't a oneway, using :forward or :backward suffix is required according to the lanes proposal. 

Good to know..  I'm not worried about the bidirectional case then 👍 

so that just leaves "Does iD reverse `turn:lanes` on a oneway road properly?"

I can't imagine that anyone would want "reverse" to mean anything other than "make the way go in the opposite direction".  So I don't think we need to provide a separate action for "leave the way alone and reverse the lanes".  I'll change the current behavior so that the oneway reverses, and we'll preserve the lanes.  Someday when we render lanes, this will be much easier for iD users to understand, but for now it's good enough.

**Comment by slhh** [comment]
@bhousel 
> I can't imagine that anyone would want "reverse" to mean anything other than "make the way go in the opposite direction".

I agree, but I was talking about two kinds of making the way go in opposite direction:

1. Reverse the way, but keep the meaning.
    Example usecases: reversing for convienience of tagging or adding routes, reversing automatically
2. Reverse the way, but keep the tags.
    This is how iD currently handles the reverse operation in view of the oneway tag.
    Example usecase: the way has been nicely tagged including lane dependent destinations, turns, and maxspeeds based on an assumption of direction, then you realize that the small arrow on the map is pointing in the wrong direction.

**Comment by bhousel** [comment]
Closing for now.. After talking through it extensively, I think it's safe for iD to leave the actual lanes alone when reversing a way (as long as we reverse the tags in situations described above).
