### ISSUE TITLE
Warning for track with missing tracktype

### ISSUE THREAD

**Issue by martenjj** [openstreetmap/iD#5835]
As stated in #3718 and #3823, tracktype is an important tag for tracks and large numbers of OSM ways currently do not have it.  In the interest of visualising the scale of the problem and reminding the user to set a tracktype when creating a track, could tracks without a valid tracktype be drawn in a different colour so that the missing tag was obvious?  There is already a visual differentiation between grade1 (solid) and other tracks, so maybe this could be extended for unknown tracktype too.

Yes, I know that the forthcoming KeepRight layer will identify missing tracktype, but not every mapper will know about or use this and KeepRight is often days behind the current database.  So having the tracks highlighted on the live editing map would still be useful.

**Comment by bhousel** [comment]
I discussed with @quincylvania today and we feel that once #5830 is live we'll be able to handle issues like this much better.

**Comment by Mahabarata** [comment]
Hi,

I really don't know how big this problem is but, since KeepRight was included in ID, it's cleary the most important problem I can see (maybe because I'm working on maps in south America and there are a lot of very small roads with highway=track).
For me there are so many "bugs" in OSM that it will be not possible to solve all before a very long time.
The first reason is that these roads need to be "seen" to be able to put the correct value : but a lot of roads in south America are on OSM because of satellite view (Bing or others) and a very few people drive on these very small roads to see the grade.

So I think that to wait that a nice guy correct all the missing tracktype is just a big dream.

You really should think about a new solution : 
- when I create a new way, I don't need to indicate that it has 2 lines or that oneway=no : they are the default values. Why not to do the same and to suppose that tracktype=grade2 when there is no indication of the tracktype ?
- when I indicate a tunnel or a bridge, ID automatically adds "layer=-1" or "layer=1" even if a lot of time unnecessary (because not crossing another road) : when I create a highway=track, you could automatically add tracktype=grade2.

I clearly prefer the first solution because the second solution is included in it and because it will solved all the bugs in OSM that nobody will never changed (I'm sure of that : if you do nothing, I will be back here in 2 years to show you I'm right).

For your informations, when I drive on roads (track or others), I never put tracktype but smoothness and maxspeed to tell that the road is ok for normal car or that you need a 4x4 car (for examples) and to tell that the road can be drive at 50 miles per hour or at 10 miles per hour, informations clearly more relevant than the tracktype.

Up to now, when I saw a tracktype missing, I changed the highway=track to highway=unclassified+surface=unpaved to be able to close the KeepRight. But now I will do nothing because the missing tracktype is clarly a false problem.

I put a copy of this message on OSM because I understand that this issue is not really an ID's issue.

Best regards

**Comment by bhousel** [comment]
>For your informations, when I drive on roads (track or others), I never put tracktype but smoothness and maxspeed to tell that the road is ok for normal car or that you need a 4x4 car (for examples) and to tell that the road can be drive at 50 miles per hour or at 10 miles per hour, informations clearly more relevant than the tracktype.
>
> Up to now, when I saw a tracktype missing, I changed the highway=track to highway=unclassified+surface=unpaved to be able to close the KeepRight. But now I will do nothing because the missing tracktype is clarly a false problem.

You should really set the roads to whatever the correct classification is:
- `unclassified` - safe for cars
- `track` - probably not safe for most cars

It sounds like the map around you has a lot of roads classified incorrectly, so defaulting `tracktype=2` in the editor will not help you.  But it's good that you are setting the `maxspeed` and `smoothness` as you review all the data in your area..

> I clearly prefer the first solution because the second solution is included in it and because it will solved all the bugs in OSM that nobody will never changed (I'm sure of that : if you do nothing, I will be back here in 2 years to show you I'm right).

You really don't have to do that, we believe you.

**Comment by matkoniecz** [comment]
> unclassified - safe for cars
> track - probably not safe for most cars

In general it is true, but:

`highway=track` is for roads used primarily as access to fields and forests - and some of them may be high quality asphalt road

`highway=unclassified` are access roads to villages/hamlets/small settlements (bigger settlements and towns generally get `highway=tertiary` or higher). In Europe/USA/some other regions this roads are safe for a normal car, this is not true everywhere.

**Comment by bhousel** [comment]
> `highway=track` is for roads used primarily as access to fields and forests - and some of them may be high quality asphalt roads (for example in big forests with regular logging).
> 
> `highway=unclassified` are access roads to villages/hamlets/small settlements (bigger settlements and towns generally get `highway=tertiary` or higher). In Europe/USA/some other regions this roads are safe for a normal car, this is not true everywhere.

This is an extremely narrow view that just doesn't work at all outside of Europe.

You can look at old issues for why, but iD has many good reasons for rejecting the OSM Wiki and European definition of `highway=track` as being "only for forest and farm roads".  I've given up trying to change OSM's mind about this.

**Comment by matkoniecz** [comment]
So iD deliberately pushes "probably not safe for most cars" definition?

**Comment by bhousel** [comment]
> So iD deliberately pushes "probably not safe for most cars" as a definition for `highway=track`?

Yep

**Comment by bhousel** [comment]
@matkoniecz [editing the OSM wiki page for `highway=track`](https://wiki.openstreetmap.org/w/index.php?title=Tag%3Ahighway%3Dtrack&type=revision&diff=1828062&oldid=1704681) to complain about what iD does is extremely uncool.

It's reasons like this why I'm pretty much done with OSM these days, and I basically just disregard everything on the tagging mailing list and the OSM wiki.  

Try to imagine that there are places in this world where you can drive for many hours, not encounter any farms or forests, then get your car damaged badly enough that you are stuck there to die.  [This really happens](http://www.otherhand.org/home-page/search-and-rescue/the-hunt-for-the-death-valley-germans/).  What tag would you use for a road like that?  

We've been through this many times before, and I'm not interested in debating it anymore today, or ever.
