### ISSUE TITLE
Mapillary: Add new geo positioned object classes

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5845]
Mapillary recently announced new object classes that are geo positioned like the traffic since we already have.

Announcement: https://twitter.com/mapillary/status/1088010250878361601

What would be a good UI to add those to iD?

**Comment by bhousel** [comment]
Nice!  Yes I've chatted with @cbeddow about this.  We'd like to improve iD's custom data capabilities and connect to these new sources like other vector data sources.

**Comment by cbeddow** [comment]
We had the idea of having the Mapillary data layer instead of traffic sign layer, where you could select a layer: `traffic signs`, `points`, `lines` then subfilter like by stop signs only, or trash bins only, or sidewalks only. Still open to UI ideas, though @bhousel and I had discussed using the modal window similar to what adding custom tiles brings up.
