### ISSUE TITLE
Capitalizing first letter of error message cause disjoining first Persian letter

### ISSUE THREAD

**Issue by iriman** [openstreetmap/iD#5877]
![untitled](https://user-images.githubusercontent.com/8467903/52519270-fed5e980-2c6d-11e9-8732-d1d2e59201d1.png)

This is caused by
https://github.com/openstreetmap/iD/blob/6ff381cb28e4b4681c6a79d2939201181382f9b7/css/80_app.css#L2618-L2620

A workaround is to add this rule

```
[dir="rtl"] .error-details-description-text::first-letter {
    text-transform: none;
}
```

But i'm not sure if all RTL languages don't have capital letters!

**Comment by bhousel** [comment]
Thanks @iriman - I added the rule.  We knew this was kind of a hacky rule to begin with, so we might need to find a better way to localize strings like these.

For anyone curious - it's about localizing messages like "This highway is missing a maxspeed tag".  We split out the "this highway" part into a separate translatable string so that we can replace it with the actual name of the highway when/if iD knows it.  We don't know for sure whether the "this highway" part will be at the beginning of the string, so we use a CSS rule to capitalize the first letter of the message.

This relates to #5679 .. cc @1ec5
