### ISSUE TITLE
While editing one tag, click delete button on another tag (raw tag editor)

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#5878]
### Expected behavior
delete line function is working while editing other field 

### Actual behavior
delete line function is not working while editing other field

### Screenshots illustrating the current situation
example: - a 2/1 lane-road gets physical separation and you want change lane attributes
from:
lane:backward=2
lanes:forward=1
to:
lanes=2
So, the idea is to delete from line "lanes:backward=2" only the "backward" string and hit instantly the delete icon of line "lane:forward=1" for removing this entire line.
See here:
![del-del_bottom_line](https://user-images.githubusercontent.com/47290585/52520925-b3bcd600-2c6f-11e9-85d5-e164b61917d5.gif)

btw, I just noticed, it seems working when the supposed line for deleting is **not** the bottom one, see here:
![del-del_not_bottom_line](https://user-images.githubusercontent.com/47290585/52520929-be776b00-2c6f-11e9-8ef2-c5819952e4fa.gif)

**Comment by bhousel** [comment]
You want to be able to hit the delete button on one tag while editing another tag?.... 

Ok, I don't know whether that is possible but I'll see if we can do that.. The problem is that clicking the button will blur the combo field, and I'm not sure whether the tag edit will reliably happen.

Also what browser is this?  I forget if I've asked you before, but for issues like this it matters.

**Comment by bhousel** [comment]
Confirmed in Chrome - I was able to fix this by batching the events so that a combo field change/blur won't conflict with the click on the delete button.

**Comment by sun-geo** [comment]
thank you
