### ISSUE TITLE
Hidden entities remain hidden upon selection

### ISSUE THREAD

**Issue by SilentSpike** [openstreetmap/iD#5880]
This is behaviour exposed by the addition of QA errors where entities are linked in the error description. 

Example where this can be confusing:
`&map=19.20/55.35233/-1.72707`
https://giant.gfycat.com/NervousSnoopyCarp.webm

Some sections of road surface area are incorrectly tagged here which ImproveOSM is flagging as missing one-way tags. Since I'm (theoretically) a user just interested in fixing road issues I have all other features disabled. At first glance it looks like these QA errors are just outdated and already fixed because the highways are definitely tagged "oneway". However, enabling the landuse features shows the real error subject was the badly mapped road area.

I see two possible solutions here:
- Force the currently selected (and hovered?) entity to always be visible regardless of enabled features.
- Disable sidebar editing and show a message to inform that the currently selected entity is not visible.

**Comment by bhousel** [comment]
> * Force the currently selected (and hovered?) entity to always be visible regardless of enabled features.

I did something like this.. The user needs to select the error, but then it will force visible any entities related to the error.  (I couldn't do it on hover because the hover is a css-only effect and the thing being hovered needs to be drawn already)

![force visible](https://user-images.githubusercontent.com/38784/52546210-5ae26000-2d8b-11e9-9ac7-533a4393148b.gif)

**Comment by bhousel** [comment]
cc @quincylvania  - do you need this for anything on the validation branch / #5830 ?   (I'll check too)

**Comment by quincylvania** [comment]
@bhousel Yep, clicking issues issues in the pane selects the features. What do you think of generally showing the selected features no matter where the selection came from? That way we don't have to manually address every instance of feature selection.

**Comment by bhousel** [comment]
> What do you think of generally showing the selected features no matter where the selection came from? That way we don't have to manually address every instance of feature selection.

`modeSelectError` doesn't actually select the entities, it just selects the error, and the added code whitelists any related entities so that they will definitely be drawn.  We put them into a `_forceVisible` object for performance reasons (it's much faster to lookup entity ids this way than in an array, and `isHidden` is very hot code).

In  151e2685d I added this for the main `modeSelect` also, so that if normally entities get selected somehow, they should be shown.  

I haven't checked this, but I can imagine situations in the code where it can happen, such as a user searches for something hidden and clicks on it from the search results, or they click on hidden relation child in the raw member editor.

**Comment by quincylvania** [comment]
> In [151e268](https://github.com/openstreetmap/iD/commit/151e2685d4d75323427c8cdfa7104d264fc6bb36) I added this for the main `modeSelect` also, so that if normally entities get selected somehow, they should be shown.

@bhousel Thanks! I checked, and this suits the case of selecting features via the issues pane in the validation branch.
