### ISSUE TITLE
Move loading indicator out of the top bar

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#5889]
There's not much reason for the loading indicator to be in the top bar since it's not a button. It takes up space that will be even more valuable as we move toward mobile support. It also looks blurry on retina screens. I suggest moving it to the bottom bar with the other status items.

<img width="561" alt="screen shot 2019-02-14 at 11 45 46 am" src="https://user-images.githubusercontent.com/2046746/52802520-1df9c000-304e-11e9-82de-7e4c2e4ce050.png">

Tangentially, can API calls get progress feedback? It'd be cool to show the completed/remaining amounts rather than an indeterminate spinner.

**Comment by bhousel** [comment]
I'm not a big fan of the spinner either 😄 

> Tangentially, can API calls get progress feedback? It'd be cool to show the completed/remaining amounts rather than an indeterminate spinner.

Possibly, and I think this gets easier if we [polyfill Fetch for IE](https://github.com/openstreetmap/iD/pull/4929#issuecomment-375510215), and use that API on modern browsers that have it.  We don't strictly need to, because the spinner is indicating data tiles that are being loaded from OSM API and there are almost always several of them, so we can right now calculate a rough progress like 2 of 6 loaded.

I also was thinking of just sticking a subtle bar somewhere like this to indicate both that data is loading and it's progress, which a lot of sites seem to do now.
<img width="739" alt="screenshot 2019-02-14 12 19 24" src="https://user-images.githubusercontent.com/38784/52804688-d164b380-3052-11e9-88f2-4fa157d105aa.png">

**Comment by quincylvania** [comment]
The long bar seems okay! It's less obtrusive and keeps us from having to reserve an icon-sized space somewhere for a spinner. I'd probably put it right above the bottom bar to mirror the "cannot connect to API" bar.
