### ISSUE TITLE
Validation: Overlapping buildings cause not glued

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#5896]
I added the building but only glued the corners.
Now the validation hit, cause I did not add and clue the node in the middle.

This validation was a bit harder to figure out and not expected.

Maybe it should not hit, if the overlap is tiny? Or could it be more specific and highlight the node that is a problem? Like eg the KeepRight issues highlight elements on the page?

Location: http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries&map=19.21/52.61842/13.35407

Screenshot before:
<img width="891" alt="bildschirmfoto 2019-02-17 um 07 50 29" src="https://user-images.githubusercontent.com/111561/52909570-d8760680-328a-11e9-871b-7988fc27f0dc.png">

After:
<img width="321" alt="bildschirmfoto 2019-02-17 um 08 07 17" src="https://user-images.githubusercontent.com/111561/52909579-1115e000-328b-11e9-912e-660753ee3e50.png">

**Comment by quincylvania** [comment]
A tiny overlap is still an overlap, so I'd say we should still flag the issue. In this particular case I'd be pleased to see that the validator noticed I forgot to glue that vertex.

I agree it's a little confusing since it doesn't look like there's a crossing. Once we show issue on the map (#5905), iD will mark the crossing location, making cases like this easier to see visually.

Eventually we might have a separate validation for detecting disconnected, coincident points that would be a better flag for this issue.

**Comment by quincylvania** [comment]
I opened #5980 as an actionable issue for this scenario. #5905 will also help.
