### ISSUE TITLE
Drive-Through crosses Roof warning

### ISSUE THREAD

**Issue by Susurrus** [openstreetmap/iD#5924]
I was editing a building that has a covered drive-through and got a "Drive-Through crosses Roof" warning. I've followed the [Tag:building=roof](https://wiki.openstreetmap.org/wiki/Tag:building%3Droof) suggestions and made the roof part a separate area with `building:roof` and `layer:1`. The drive-through way has no Structure annotations. See the following pic:

![image](https://user-images.githubusercontent.com/206363/53181271-1a18f100-35ac-11e9-9cff-349bdaf49f16.png)

I'm using 64-bit Firefox 65.0.1 on 64-bit Linux and using iD editor 2.14.1

I think I've done this edit right, but iD is warning me here. Is this a false positive?

Additionally the pop-up descriptive text when you hover over the warning says "Highways crossing buildings should use bridges, tunnels, coverings, or entrances. I searched the OSM wiki for "coverings", to see if that would be what I want to use here, but that term doesn't exist in the wiki. So the descriptive text also led me down the wrong road to resolve this.

**Comment by sun-geo** [comment]
yeah there are maybe some appreciated changes.
btw: the tag for "coverings" is:
https://wiki.openstreetmap.org/wiki/DE:Key:covered

**Comment by quincylvania** [comment]
@Susurrus Thanks for the feedback! "Covering" is a sort of linguistic hack to refer to the [`covered`](https://wiki.openstreetmap.org/wiki/Key:covered) tag, which should fix the warning in this instance. I agree we should find ways to make this less confusing.

**Comment by manfredbrandl** [comment]
@quincylvania Do you mean the issue „way crossing roof“ should not be reported because it is a false positive? I think that way:
![5e7a6e3f-d6ff-4903-96c2-907cd346ea83](https://user-images.githubusercontent.com/5360273/53303353-b02d6f80-3869-11e9-8b36-38bee883f648.jpeg)
![68c69700-2794-48e8-8a22-2f00df11afc6](https://user-images.githubusercontent.com/5360273/53303357-b885aa80-3869-11e9-9758-f2edc9d57a35.jpeg)

**Comment by bhousel** [comment]
I’d prefer for these ways to be tagged with `covered=yes` rather than expecting everyone to whitelist certain kinds of building types as being allowed for ways to intersect them.

**Comment by manfredbrandl** [comment]
@bhousel That‘s okay for me. Do you agree that „Use bridge or tunnel“ should be extended with „or a covered way“?

**Comment by BjornRasmussen** [comment]
If the building has `layer=1` (a different layer tag from the road), no intersection warning should be created.  This is how the JOSM validator currently works.

**Comment by bhousel** [comment]
I’d prefer for these ways to be tagged with `covered=yes` rather than expecting everyone consuming this data to need to evaluate `level` tags for context.

**Comment by 1ec5** [comment]
> "Covering" is a sort of linguistic hack to refer to the covered tag, which should fix the warning in this instance. I agree we should find ways to make this less confusing.

(Not that it makes it any less confusing, but I recently learned that these coverings are properly called [porte-cochères](https://en.wikipedia.org/wiki/Porte-cochère).)

**Comment by Susurrus** [comment]
@1ec5 that different from my example at the beginning. That's for an entrance, like a lot of hotels or hospitals have in the US.  My example is a drive-through, where there's no entrance being protected, rather it's to protect people who are rolling down their windows.

**Comment by SK53** [comment]
@bhousel: the problem of expecting covered=yes to be added is that it is pushing much more work on the contributor (e.g. for gas stations & drive-throughs). The alert will be triggered on (I suspect) the majority of existing mapping, which may be confusing for newcomers. (Of course I realise that making a special case for one type of building is a PITA also).

**Comment by bhousel** [comment]
> the problem of expecting covered=yes to be added is that it is pushing much more work on the contributor (e.g. for gas stations & drive-throughs). The alert will be triggered on (I suspect) the majority of existing mapping, which may be confusing for newcomers. (Of course I realise that making a special case for one type of building is a PITA also).

Yes, well I was kind of against adding a validator for years because of the amount of extra work it pushes onto our contributors, most of whom don't know about what tags go with with other tags, and what default behaviors some tags imply.

Our validator does have the ability to offer one click fixes, and we will soon add "autofix" capability just like JOSM, so it won't be much work for users to just click the action item to add the tag..

**Comment by tordans** [comment]
Suggested next steps:

Adding `covered=yes` in those cases where bridges and tunnels are the wrong solution seems to be the proposed solution.

To do this, IMO those thinks need to change:

a. I should be able to select `covered` somewhere on the preset
b. The warning should also list `covered`
c. We should help users to choose the right solution

**For a: select `covered` on the preset**

I think the fitting place is the structure preset area
<img width="360" alt="Bildschirmfoto 2019-05-04 um 08 03 02" src="https://user-images.githubusercontent.com/111561/57174694-1b378b80-6e43-11e9-9f66-2a5fd9d094d6.png">

**For b: warning**

Current:
> Use a bridge or tunnel

New
> Use a bridge, tunnel or mark as covered

Once the validation can automatically split ways, there are clearer ways to put this. Example in the last quote of https://github.com/openstreetmap/iD/issues/6192#issue-433977097.

**For c: Explaining**

Please let at least extend the small gray (i) text with some text that will help me decide on what to do.

_The help text on the the validation (i)_

Currently it lists options but does not help me decide what to do
> Highways crossing buildings should use bridges, tunnels, coverings, or entrances.

I still think linking to the wiki pages here – see https://github.com/openstreetmap/iD/issues/5900#issuecomment-485909126 – is very helpful.

_The help text on the structure (i)_

Right now the help text is missing for the structure preset (see screenshot above). I would probably also need to link to more than one documentation, since the preset combines multiple tags.

**Comment by cserpell** [comment]
What about a service highway that is over a roof? How would you solve this with this validation and solution? Is this the meaning of covered=no?

**Comment by cserpell** [comment]
Look what new users do because of this: https://overpass-api.de/achavi/?changeset=70707541

A tunnel is clearly not intended.

**Comment by quincylvania** [comment]
I'm pretty sure this was covered by #6911.
