### ISSUE TITLE
Some generic name validation is too strict

### ISSUE THREAD

**Issue by seav** [openstreetmap/iD#5930]
I have added the name "Bacolor Municipal Hall" to a feature tagged `amenity=townhall` and I get the following validation warning with a button inviting me to remove the name:

> Town Hall has the generic name "Bacolor Municipal Hall"

But as you can see, the name is a _proper_ proper name and is not a generic name.

**Comment by quincylvania** [comment]
@seav The generic name validation uses the `discardNames` regex list from [`filters.json`](https://github.com/osmlab/name-suggestion-index/blob/master/config/filters.json) in the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) project. It looks like it flags any name containing "municipal". We should probably change that to only flag exact matches.

Keep in mind that the generic name validation uses imperfect heuristics and you can ignore it! There are bars named "Bar" after all.

**Comment by seav** [comment]
Yup, I know that I can ignore the warnings similar to how I handle validation errors flagged by JOSM. But I am an experienced OSM mapper after all. I fear that newbie OSM mappers who use iD may think that what they are doing is wrong because of these too strict warnings.

**Comment by quincylvania** [comment]
@seav I agree with you 100%. We should fix this case. I was just letting anyone who read this thread know it's okay to ignore warnings 😅

**Comment by matkoniecz** [comment]
> The generic name validation uses the `discardNames` regex list from [`filters.json`](https://github.com/osmlab/name-suggestion-index/blob/master/config/filters.json) in the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) project

Is it importing filters or just copied them as a starting point? Because copying is a bad idea, their purpose is not to detect generic names but to discard all non-brand names.

Other cases that will happily generate false positives from a quick look: "Bank spółdzielczy" (matches `"^bank(| spółdzielczy)$"`), everything from `"^(central|city|europa|grand|palace|park|royal)(\\s)?hotel$"` rule, "okręgowa stacja kontroli pojazdów" (matches `"^(okręgowa\\s)?stacja kontroli pojazdów$"`)...

I would suggest to maintain them as a separate list - maybe with list of filters excluded as too zealous and adopted to make importing new ones easy.

**Comment by bhousel** [comment]
> Other cases that will happily generate false positives from a quick look: "Bank spółdzielczy" (matches `"^bank(| spółdzielczy)$"`), everything from `"^(central|city|europa|grand|palace|park|royal)(\\s)?hotel$"` rule, "okręgowa stacja kontroli pojazdów" (matches `"^(okręgowa\\s)?stacja kontroli pojazdów$"`) and many other non-brand non-generic ones...

Yes, the filters.json list isn't really designed to be a name filter for iD, we are just using it for now.  

We could create a separate list, but it might be faster and more useful to just tweak the filters.json list to move more of the _specific_ names, like those hotels, from `discardNames` (which iD repurposes) to `discardKeys`.

**Comment by ignaciolep** [comment]
The same validation happened with "Municipalidad de Gonzales Chaves" in Buenos Aires, Argentina. 
That's because the word "Municipalidad" (Town hall) contains the string "Municipal"?

![a36130db-1fcf-49d6-a14c-0bb8dd61](https://user-images.githubusercontent.com/13091755/53440056-6025e880-39e2-11e9-85e1-4c6e25c39256.png)

**Comment by bhousel** [comment]
> but it might be faster and more useful to just tweak the filters.json list to move more of the _specific_ names, like those hotels, from `discardNames` (which iD repurposes) to `discardKeys`.

☝️  I did this..  I'm going to close for now, but we can always adjust the filter some more if it turns out to still be too aggressive.
