### ISSUE TITLE
Validation: Dykes should not need to be closed

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/iD#5933]
Copying this from the "tagging" mailing list:

On 22.02.19 12:46, Ulrich Lamm wrote:
> Hi friends,
> 
> if you map a dyke, ID-editor recently gives a warning that a dyke ought to be a closed (circular) line.
> On lowland coasts such as in Germany, this demand is a nonsense.
> Some dyke lines (especially on the North Sea) have a length of several hundreds of kilometers. Nobody can map them in one session.
> Other coasts, such as on the Baltic Sea, but also in England, have very low sections, that are protected by dykes, and hilly sections that do not require dykes. 
> There the dykes end at slopes of natural hills – which are not mapped, unless they are prominent escarpments.
> 
> Ulrich Lamm

**Comment by quincylvania** [comment]
I assume they're using [`man_made=dyke`](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Ddyke)? The updated "area as line" check uses the preset data. Since we don't have a Dyke preset, iD falls back to the generic Man Made preset which should allow lines. Looks like a bug.

<img width="595" alt="screen shot 2019-02-22 at 10 23 58 am" src="https://user-images.githubusercontent.com/2046746/53252042-1066ba80-368c-11e9-8b37-05d2040eaa3e.png">

**Comment by woodpeck** [comment]
Thank you for looking into this and fixing it. I have relayed the good news back to the tagging mailing list.

**Comment by quincylvania** [comment]
@woodpeck Happy to help! Thanks for reporting this.
