### ISSUE TITLE
Crossing highway/railway - exclude railway=tram and railway=construction + construction=tram and railway=disused + disused=tram

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#5990]
Due to various weird geometry issues (`railway=tram` follow tram tracks and `highway=*` follow centerline of road) point where `railway=tram` line and `highway=*` line crosses is often NOT representing point where tram crosses road.

In JOSM for this reason trams are excluded from this rule.

See https://josm.openstreetmap.de/ticket/16889 for partial JOSM equivalent

**Comment by matkoniecz** [comment]
See for an example https://www.openstreetmap.org/?mlat=50.07323&mlon=19.93585#map=19/50.07323/19.93585&layers=N

**Comment by quincylvania** [comment]
> `railway=tram` line and `highway=*` line crosses is often NOT representing point where tram crosses road.

Okay, but the two features are still technically connected and if you're driving north through that intersection you'll still end up driving over the tracks. If that road was mapped bidirectionally it'd be even more accurate. Traffic lights and stop signs aren't mapped where they're physically located either.

Even putting all that aside, trams can still cross roads via bridges and tunnels. People would expect iD to flag these.

**Comment by bhousel** [comment]
> Okay, but the two features are still technically connected and if you're driving north through that intersection you'll still end up driving over the tracks. If that road was mapped bidirectionally it'd be even more accurate. Traffic lights and stop signs aren't mapped where they're physically located either.

Yeah I agree - the purpose of mapping the crossings isn't to make pretty maps of where the crossings are, but more to inform data consumers.  So that a cycling navigation app might flash up a message saying "watch out for tram tracks in 200m" or something.   

I'm inclined to leave this validation as-is..

**Comment by matkoniecz** [comment]
See https://www.openstreetmap.org/?mlat=50.06646&mlon=19.93905#map=19/50.06646/19.93905&layers=N - here there is no self-crossing - tram tracks are embedded in the road.

![selection_001](https://user-images.githubusercontent.com/899988/53496324-1bfa1d00-3aa2-11e9-9de0-102c8c7157ad.png)

https://www.google.pl/maps/@50.0662939,19.9390377,3a,75y,15h,73.79t/data=!3m6!1e1!3m4!1sA865u1CQIVOHTxDQqdaZDQ!2e0!7i13312!8i6656

Or see for example https://www.openstreetmap.org/?mlat=50.07300&mlon=19.93584#map=19/50.07300/19.93584&layers=N

Here cycleway joins road (so it joins centerline mapped as `highway=*`). It crosses `railway=tram`. But it is not not crossing tram tracks!

![selection_002](https://user-images.githubusercontent.com/899988/53496357-32a07400-3aa2-11e9-8ade-b991819f5de9.png)

https://www.google.pl/maps/@50.0728711,19.935888,3a,75y,6.6h,87.95t/data=!3m6!1e1!3m4!1sZDB9ac_5OW_U5AmZX8Pb3Q!2e0!7i13312!8i6656

**Comment by quincylvania** [comment]
> There are multiple crossings of `highway=*` and `railway=tram` lines but no crossings should be mapped.

I fail to see how you would avoid crossing any tracks when turning at that intersection. I suggest mapping the two directions as separate ways if the accuracy matters, or feel free to ignore iD's warnings.

> In JOSM for this reason trams are excluded from this rule.

I appreciate you drawing inspiration from existing work! But just because iD has validation warnings now doesn't mean we're going to do everything JOSM does.

@bhousel:

> I'm inclined to leave this validation as-is..

Sounds good to me.

**Comment by matkoniecz** [comment]
> I appreciate you drawing inspiration from existing work! But just because iD has validation warnings now doesn't mean we're going to do everything JOSM does.

I intend it not in "iD must be JOSM equivalent" but "it is not merely my idea and at least one other person thought in the same way". Also, JOSM validator is quite mature and went through many iterations that removed various false positives so their rules are usually well tested.

I think that it is not useful to mention it explicitly every single time, but I can start doing it.

**Comment by quincylvania** [comment]
> I intend it not in "iD must be JOSM equivalent" but "it is not merely my idea and at least one other person thought in the same way".

@matkoniecz That's fine! As long as you agree with the behavior too 🙂

**Comment by Nakaner** [comment]
@quincylvania wrote:
>  I suggest mapping the two directions as separate ways if the accuracy matters.

In OSM, a road is only split into two parallel ways if there is a physical separation between the two directions. (It's different for railway infrastructure where mapping one way per track is preferred) Therefore, splitting the road into parallel ways as you suggested would be mapping for validator.

**Comment by quincylvania** [comment]
> In OSM, a road is only split into two parallel ways if there is a physical separation between the two directions.

I would argue that using two ways is an option anytime that a single way is insufficient to model the road as it exists in the real world. A physical barrier is one reason. Embedded tracks might be another. It's OSM though, so map them however you think is best!

**Comment by hungerburg** [comment]
Recently I toyed around with a pedestrian router for the blind and sometimes it went crazy detours. Digging into it, I found "railway=crossing" on footways crossing tram rails a major reason. As the tag is very rare in my local area (only 5 occurrences in all of the town), wondering how they came to be I learned, that iD suggests them. So I fired up iD, selected a tram line and clicked "connect" in the validator as long as there was nothing left to click. In the end I had created 27 railway crossings and level crossings on only 1 km of tram line! Further I got a "Your edits look good" green box after "fixing" three more warnings of the same kind in the validator.

I think that is completely overblown:

- Tram rails embedded into a street do not anywhere look like the pictures for "railway=crossing" in the OSM wiki. I am in no way certain, that the tag is actually applicable. One may counter, that the router then should handle railway crossings differently in case the railway is a tram, but beware: the router has no way to know, whether the rails are embedded into the street, if the crossing is protected by a traffic signal on the embedding street, or if the crossing is actually something that looks like shown on the wiki.
- Several of the crossings do in fact not exist at all, e.g. like in the second picture above, or where a footway or a street joins in. The workaround suggested, to map lanes of a street separately though goes against the good-practice principle of one feature on ground to have one entity in OSM, where tram and cars share the same space, a continuous paved carriageway for a bidirectional street that happens to have tram rails embedded.

**Comment by quincylvania** [comment]
@hungerburg Sorry this is causing issues for you! Look at it this way… these are the options I saw for what iD should do about tram and road/path crossings:

- Don't flag them. This leaves the layering and topology ambiguous. 
- When connecting, don't tag the node. Routers wouldn't know there's anything special about these nodes (which seems like a big problem for blind pedestrian routers).
- When connecting, tag the node as a level crossing.

So while I continue to think the last one is the least bad, I agree that tramway crossings are rather different than full railway level crossings. As such, a fourth option comes to mind:

- When connecting, tag the node specifically as a tram crossing.

Turns out there are already tags for this with a few thousands uses, [`railway=tram_level_crossing`](https://wiki.openstreetmap.org/wiki/Tag%3Arailway%3Dtram_level_crossing) and [`railway=tram_crossing`](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dtram_crossing). Seems established enough to use in iD. I wish we'd known about these before!

**Comment by hungerburg** [comment]
@quincylvania Great something came out of this. The fourth option clearly rules. Much better than option 3. It makes explicit what the router implicitly assumes in option 2. This is just a guess though, from reading the text form itinerary. I mapped two of those for control. I do not expect that the router knows about the new tags and will do as in option 2.

That leaves the cases, where there is in fact no crossing at all, or perhaps depending on whether one does a right turn or a left turn…
