### ISSUE TITLE
Confused about crossings

### ISSUE THREAD

**Issue by LaszloEr** [openstreetmap/iD#6004]
I have multiple questions about tagging crossings.

- What exactly does crossing=marked mean? I can't find any documentation for it in the wiki.

- What is the proper way to tag crossings that are controlled by traffic lights, have some markings but no zebras? Unmarked crossing doesn't seem right since there are some markings. Example picture: https://upload.wikimedia.org/wikipedia/commons/8/8c/Amerikanische_Kreuzung_in_Berlin.JPG

- How should zebras without traffic signals be tagged? Why was the entry for crossing=zebra removed?

- Why was the entry for crossing=traffic_signals removed some versions ago?

Thank you

**Comment by bhousel** [comment]
Because nobody can agree on what the legacy tags mean, we are encouraging people to map crossings as either `crossing=marked` or `crossing=unmarked`.  These are tags that have been in use for a while but just not as popular as the `uncontrolled` and `traffic_signals` and `zebra` and other stuff that everyone disagrees about.

There are lots of old issues that you can search for if you want to read the history.  For what it's worth, there is overwhelming support for `crossing=marked/unmarked` among people actually working on apps for pedestrian routing, accessibility, and curb/sidewalk mapping.

I'll try to answer your questions anyway:

> * What exactly does crossing=marked mean? I can't find any documentation for it in the wiki.

It just means a place for people to cross the street with some kind of marking on the ground.

> * What is the proper way to tag crossings that are controlled by traffic lights, have some markings but no zebras? Unmarked crossing doesn't seem right since there are some markings. Example picture: 

`crossing=marked`

> * How should zebras without traffic signals be tagged? 

`crossing=marked`

> Why was the entry for crossing=zebra removed?

Because `crossing=marked` is better.  People complained _a lot_ about `crossing=zebra`.

> * Why was the entry for crossing=traffic_signals removed some versions ago?

iD never supported this, and never will.

**Comment by batyrmastyr** [comment]
@LaszloEr I have no idea what are the "legacy tags" @bhousel mentioned because the were only two small changes in `crossing` values since [2009](https://wiki.openstreetmap.org/w/index.php?title=Key:crossing&oldid=360433) - removal of quite awkward `unknown` and introduction of `island`. Looks like the only one who doesn't agree with `uncontrolled` and `traffic_signals` is bhousel himself.

Also, as of 4th of October 2018 there were quite insignificant amount of "marked" crossings, so I don't believe there was "overwhelming support for `crossing=marked`".
```
uncontrolled    | 661 122
zebra           | 525 573
traffic_signals | 514 832
marked          |   8 422 
```

> People complained a lot about crossing=zebra.

They asked to replace `zebra` with `uncontrolled` (supported since the very [beginning](https://wiki.openstreetmap.org/w/index.php?title=Key:crossing&oldid=98274)) or with `marked` (unapproved, unknown and, thus, unsupported)?

**Comment by cserpell** [comment]
Indeed. Today I used iD after a los of JOSM usage, and it didn't want to submit changes with crossing=zebra. Looking into the wiki page, there is a proposal of using always marked instead of zebra, but it has not been approved! Why is iD forcing a change that has not been approved by the community?

**Comment by quincylvania** [comment]
@batyrmastyr @cserpell Thanks for your concern, a few notes:

- iD isn't forcing changes. Tag warnings are suggestions and do not block upload. There's even an "ignore" button.
- Since OSM does not enforce a tagging schema, there are multiple ways to tag things. Thus editors can be put in the position of making some tagging decisions. In these cases we try to pick tags that are easiest for data consumers and casual mappers to interpret. I understand that this process is imperfect and that not everyone may agree with out decisions. We're taking steps like #6483 to detach iD's presets maintenance from iD's core development

**Comment by tomasokol** [comment]
@quincylvania I think we should have a “Crossing with traffic signals” and an “Uncontrolled crossing” preset by now. As https://wiki.openstreetmap.org/wiki/Key:crossing says, the priority is information about presence of traffic signals, over whether it's got any kind of marking. Which can be specified by crossing_ref=.
