### ISSUE TITLE
Selecting feature type: stuck at "vertex"

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/iD#6026]
Follow up for #6025: I tried to add a bus stopping location, which apparently is related to a "vertex" object type. However, the UI only shows some crosshair cursor and won't let me create any vertex object. Same happens if I enter "vertex" in the search bar. A new icon appears, yet I can't do anything with that vertex.

![vertex](https://user-images.githubusercontent.com/5842757/54047347-21a8de80-41d7-11e9-9111-b0d154c848c0.png)

**Comment by bhousel** [comment]
I'll think about this some more.. Maybe we can change the rendering of the vertex icons to make it more clear that a vertex is a point-on-a-line, or introduce vertices in the walkthrough in a friendly way.

**Comment by SilentSpike** [comment]
Should we not:
- Make vertex a hidden preset which is only created when drawing ways and doesn't show in the search bar (since they can't be created that way anyway).
- Add "vertex" as a synonym for "point" so that the point preset shows up if you do search for vertex.

If you wanted to remove the term "vertex" altogether then I'd personally consider just always referring to them as points (whether on a way or unconnected). It would just mean you have to demonstrate the concept that ways are made up of connected points in the tutorial. Personally I think this is doable and more approachable than introducing a new concept which is just a variation of something already encountered. It would improve understanding of the fact that you can tag a POI which is on a way (like a crossing for example).

**Comment by quincylvania** [comment]
I removed the Other/Vertex fallback preset and added the `vertex` geometry to the Point preset. I think it's easier for users if "all nodes are points but the context varies" rather than "these are two different things to worry about".

I'm leaving this open since we still need to make it clear to users why certain presets must or must not be added to ways.

**Comment by quincylvania** [comment]
In ba7f9db46f373950298e1af43007756f787259de I added a warning that flashes at the bottom of the screen when you attempt to add standalone vertices.
