### ISSUE TITLE
Merge tool / validator not checking waynode max limit

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/iD#6030]
I'm merging a few of Lake Huron's ways and noticed that iD's merge tool won't check the 2000 nodes waynode limit  as per /api/capabilities. This has a few bad consequences during upload, as the API refuses this changeset and somehow iD bails off into an undefined state. Ideally, iD's validator should catch this before it hits the upload.

Testing: https://master.apis.dev.openstreetmap.org/edit?editor=id#map=18/44.87525/-81.34865

* Merge 2 ways
* Upload

![upload1](https://user-images.githubusercontent.com/5842757/54076149-5e90d600-42a8-11e9-95e9-77a5a6d846cb.png)

* Try to upload again

![upload2](https://user-images.githubusercontent.com/5842757/54076150-63558a00-42a8-11e9-9f8f-7d621e0428b5.png)

**Comment by bhousel** [comment]
I think iD should just split these for the user without even bothering them.

**Comment by quincylvania** [comment]
I added a safety check to the merge operation, but there are still other situations where the maximum node limit could be exceeded:

- Continuing a line
- Double-clicking a way
- Dragging a midpoint
- Dragging a node onto a way
- Clicking a way while drawing
- Clicking a way while placing a new node
- Probably more…

Since these only add one node at a time, I expect they're less likely to exceed the node limit than merging long ways, but they still make for future work.
