### ISSUE TITLE
Flag paths with contradictory access tag combinations

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6070]
There are a number of access tag combinations that shouldn't occur on paths. We should flag and offer to upgrade them. Examples:

- Instances like `highway=footway` with `foot=no`, upgrade to `highway=path`
- ~~Instances like `highway=footway` with `bicycle=designated` and no other designations, upgrade to `highway=cycleway`~~ (Skip for now)
- ~~Instances like `highway=path` with `foot=designated` and no other designations, upgrade to `highway=footway`~~ (Skip for now)

**Comment by 1ec5** [comment]
> Instances like highway=footway with bicycle=designated and no other designations, upgrade to highway=cycleway

Or offer to add `foot=designated`.

Along these lines, we should warn when a `highway=cycleway` lacks an explicit `foot` tag (which could be yes, no, or designated). It’s too common in the U.S. for mappers to neglect the `foot` tag because pedestrians are almost always allowed on bike paths in the U.S. (I’ve made this mistake aplenty.)

**Comment by bhousel** [comment]
> Along these lines, we should warn when a `highway=cycleway` lacks an explicit `foot` tag (which could be yes, no, or designated). It’s too common in the U.S. for mappers to neglect the `foot` tag because pedestrians are almost always allowed on bike paths in the U.S. (I’ve made this mistake aplenty.)

This is true that most bike paths also allow foot traffic in the US, but I don't want to get into the situation where we are doing things like US-only validation rules.

**Comment by quincylvania** [comment]
> It’s too common in the U.S. for mappers to neglect the foot tag because pedestrians are almost always allowed on bike paths in the U.S.

@1ec5 @bhousel What do you think about adding a "Cycle & Foot Path" preset for `highway=cycleway` + `foot=designated`? We shouldn't start adding gobs of combinations but this seems like it'd be useful.

**Comment by 1ec5** [comment]
That’d be a sensible addition. The U.S. term would be “multi-use trail”, though note that some multi-use trails also allow `horse` or `carriage` access too.

**Comment by sun-geo** [comment]
I'm not sure if highway=**cycleway** is best choice when foot=designated & bicycle=designated is used for the same way.

In germany, for example we have 2 traffic signs which maybe are related to these situations, for these cases the value is highway="path" instead of highway="cycleway" for this tagging.

see here:
http://osmtools.de/traffic_signs/?signs=240
http://osmtools.de/traffic_signs/?signs=241

With traffic signs there are available in U.S.?
