### ISSUE TITLE
Remove Curb field from crossings

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6078]
The `kerb` tag can currently be used on crossings if both sides of the crossing have the same curb type. This pattern is redundant and less granular than adding curb nodes where they actually occur on either side of the crossing. In order to reduce confusion and encourage consistent, detailed mapping, we should remove the Curb field from crossings altogether.

**Comment by Lukas458** [comment]
but what is when there is no crossing-way in the database where the barrier=kerb nodes can refer to, because the sidewalks are not mapped separately? I think, kerb tags oh highway=crossing are for this purpose...

**Comment by quincylvania** [comment]
@Lukas458 iD is supporting the ongoing trend of mapping sidewalks separately from roads. This enables better routing possibilities for pedestrian and wheelchair users.

**Comment by stragu** [comment]
Hi @quincylvania 

Please see https://github.com/openstreetmap/iD/issues/6429#issuecomment-520273622
I'd argue that the presets should be kept for single-node crossings, as it is still very common to not go into such detail as to mapping sidewalks separately to roads, and removing the presets for those would mean mappers would probably end up not recording valuable information.
I however support this decision for `highway=*` + `*=crossing`, it makes total sense in this case.

The [wiki](https://wiki.openstreetmap.org/wiki/Tag:footway%3Dcrossing) says: "If sidewalks are mapped as property on the street and the road is just a single way in OSM, there is no need for a perpendicular way and this tag." Pushing for tagging kerb details on a perpendicular way to the road would mean the contributor would have to then directly start mapping connecting sidewalks separately, and so on all around the area.
Even though I have been mapping my neighbourhood in quite a bit of detail over the years, I still don't feel like mapping sidewalks separately as the task would be very time-consuming. It is particularly true for large, spread-out residential areas.

What do you think?

**Comment by quincylvania** [comment]
@stragu Thanks for your thoughts. While it's fine to map sidewalks as properties of roads, iD encourages mapping them separately. This makes it easier to achieve higher levels of detail that enable use cases like accessible wheelchair routing. I'm not sure specifying curb info on crossings is actually that valuable if the foot router won't pass through the crossing nodes since the sidewalks aren't mapped as lines.

**Comment by Nakaner** [comment]
@quincylvania There are plenty of regions all over the world where adding pavement to many roads as tags only would improve the usability of OSM data (routing) more just adding pavements as separate ways to a few roads.

In the past 15 years, OSM has followed a something is better than nothing approach for crowdsourcing. For example, we started mapping roads as a single way although a lot of the contributors in the early days weren't blindly focused on car traffic only. We are thankful to everyone adding a POI even if opening hours, website, phone number of similar additional information is missing. Please keep in mind that the work of volunteers is the most important and a limited resource in OSM. We should aim to get as much information as possible with limited work.

I think it is not the task of the developers of one of the most influential OSM editors to decide that mappers should either map something completly (all pavement as separate ways in order to add kerbs) or just skip it.

May I ask you to revise your decision?

**Comment by stragu** [comment]
Thanks for the reply, @quincylvania. The case of routing difficulty with crossings as nodes does make sense, now that you mention it: it would be tricky to route along a sidewalk mapped as a road property while jumping to closeby node crossings on intersecting roads...
I now understand better why iD would want to push for this kind of detailed mapping, but wouldn't a message underneath the kerb presets be more effective? I don't think someone mapping crossings as single nodes would automatically understand that, because the presets are missing, they should change their method to using detailed line crossings.
I agree with @Nakaner that, to some extent, this change might be counterproductive in how it might make people give up on adding extra details. (Other apps use iD presets, like Go Map!!, a mobile app in which contribution of data depends highly on how convenient it is to set tags with the presets.)

**Comment by quincylvania** [comment]
> We are thankful to everyone adding a POI even if opening hours, website, phone number of similar additional information is missing. Please keep in mind that the work of volunteers is the most important and a limited resource in OSM. We should aim to get as much information as possible with limited work.

Sure, but that's not really a fair comparison since such POI tags are widely useful. It's not polite to prompt volunteers to waste time tagging data that won't be used by any data consumers.

Curb mapping is useful for accessible pedestrian routing. I don't know of any router that accounts for `kerb` on `highway=crossing` nodes when footways aren't mapped separately. If someone can point me to a real use case then perhaps we can reconsider this.
