### ISSUE TITLE
Popup doesn't close after changeset is uploaded

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#6092]
Currently on [the live site](https://preview.ideditor.com/master) the `Uploading changes to OpenStreetMap` popup doesn't close itself after a changeset is uploaded. The changeset closes just fine on the server but the page needs reloaded to continue mapping.

Windows 10 64-bit  
Vivaldi 2.3.1440.61

**Comment by BjornRasmussen** [comment]
I am having the same issue with Chrome on Linux.  Here is an image of what iD looks like 5 minutes after uploading has finished: 
![image](https://user-images.githubusercontent.com/37753777/54947814-94bd8f00-4f11-11e9-998d-0524ac6ea4b4.png)

**Comment by quincylvania** [comment]
This is 100% reproducible in Safari from my tests. The issue is with fetching the community index list. When you see the "You just edited OpenStreetMap!" sidebar in the background then your changes were successfully uploaded. The box will never disappear so until we fix this please just reload the page to keep editing!
