### ISSUE TITLE
Do not offer denominations of other religions when religion already set

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/iD#6108]
I am relaying a complaint/suggestion that a German mapper sent to webmaster@fossgis.de (of all places...).

They write that they were surprised to be mapping a "christian church" and then be offered "sunni" and "shia" (among others) in the denomination drop-down. They didn't mention iD but I just tried it out and what they write seems to match iD's behaviour.

I guess this may be related to #5583 where a method was implemented to display a field based on something else being set; maybe this mechanism could be (ab)used to have several different "denomination" fields with different sets of values available in the drop-down. JOSM seems to be using something like that in https://josm.openstreetmap.de/browser/trunk/data/defaultpresets.xml LL283.

Personally I don't consider this a major issue - we don't support dependencies like this elsewhere either, for example I can easily map a power=minor line and add a high voltage or something. But apparently it is important enough for users "out there" to write in ;)

**Comment by bhousel** [comment]
Yes, like you said we don't really support field dependencies in OSM. 

For some fields, iD does include all the correct values, but for others we just fetch whatever the common values are from taginfo.  The religion/denomination fields are the taginfo kind because I don't think we could ever have a perfect mapping of what all the religions and denominations are.. We'd be constantly maintaining it.  Instead I think we can trust the users to just fill in what they know to be correct.

💡 Also - this is one of those situations where Wikidata could do a much better job than OSM can.  If the primary fields were `religion:wikidata` and `denomination:wikidata`  it would be really easy to just look up what all the values are and know parent-child relationships between them.  Users could change this data however they want to.. Online editors like iD could fetch it anytime, and JOSM could build their value lists automatically.

**Comment by jidanni** [comment]
Yes, I had just selected Buddhist as a religion, and was confronted with Roman Catholic etc. choices.
![X6](https://user-images.githubusercontent.com/1230959/72892733-4146e800-3d52-11ea-9bd1-8d4fdc855953.jpg)
No only does offering impossible combination make this an error prone entry form,
one day it will hit on some **very sensitive combination**,  igniting some religious furor... who knows?
(Of course not offering all combinations on the other hand might miss out on some choice, igniting reverse furor, etc.)
