### ISSUE TITLE
add building:part=yes support

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6114]
https://wiki.openstreetmap.org/wiki/Key:building:part

For start it would be nice to render them as areas.

Maybe named "building part" rather than "line".

**Comment by bhousel** [comment]
Ah yeah, this is one of the few exceptions where we render a polygon feature as a line instead of an area. 

In the past, I worried that rendering them as areas would really kill performance around places that have a lot of them.  But I do notice that some of them do render as areas when they are part of a multipolygon (like these ones) and they render fine:

<img width="638" alt="Screenshot 2019-03-27 00 20 39" src="https://user-images.githubusercontent.com/38784/55050273-32a27e00-5026-11e9-82b9-a7818fac816f.png">
