### ISSUE TITLE
Warn when creating objects with tags suffixed with a number

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/iD#6136]
Could iD warn when somebody creates something like this, please?
https://www.openstreetmap.org/way/548632566

```
landuse = grass
landuse_1 = recreation_ground
landuse_2 = recreation
landuse_3 = greenfield
leisure = park
leisure_1 =garden
leisure_2 =grass
leisure_3 =playground
natural = wood
natural_1 = scrub
natural_2 = grassland
```

**Comment by Adamant36** [comment]
Thinks for opening an issue related to this. Its something I've had a major problem with for a while now and planned to open an issue for eventually, but I never got around to it. Things like landuse_1 shouldn't be valid tags in my opinion and its mostly an issue due to Pokemon Go mappers trying to "stack" similar tags onto things for their game. When it doesn't support that kind of tagging anyway. So it would be great if there was a warning or something when someone tries to do it.

**Comment by bhousel** [comment]
I typed out a long response, then deleted it because it doesn't matter.  
Basically, these tags don't hurt anything except in very rare cases (like https://wiki.openstreetmap.org/wiki/Key:fuel) so I'd rather just leave them alone rather than bothering the user to do anything about it.  If they bother you, just delete them with JOSM or level0 or a bot or something.

**Comment by naoliv** [comment]
I am eager to see the same answer for [every other ticket](https://github.com/openstreetmap/iD/issues?q=is%3Aissue+is%3Aopen+label%3Avalidation) asking to annoy the user with unneeded validation stuff.

**Comment by bhousel** [comment]
> I am eager to see the same answer for [every other ticket](https://github.com/openstreetmap/iD/issues?q=is%3Aissue+is%3Aopen+label%3Avalidation) asking to annoy the user with unneeded validation stuff.

If it's something that any user could reasonably make a decision about, I don't mind asking them to fix it.. This issue is not like that.  It's just a bunch of extra tags that nobody cares about.
