### ISSUE TITLE
Update changeset hashtags when removed from comment

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#6169]
When hashtags in a changeset comment are added or changed, iD automatically adds them to the changeset's `hashtags=` tag, which is great. However when all hashtags are removed it does not automatically update and leaves the hashtag tag even if there are no hashtags in the comment.  
This is confusing and I have seen many changesets with hashtags irrelevant to the changes. Groups like HOT use hashtags for tracking and this can cause issues.

Would it be possible to detect and update the `hashtags=` tag when all hashtags are removed from the changeset comment?

**Comment by pnorman** [comment]
> Would it be possible to detect and update the `hashtags=` tag when all hashtags are removed from the changeset comment?

My understanding is the goal is to have the hashtags in the hashtag tag value, and they shouldn't really be in the comment tag, which is supposed to be a good changeset comment.

**Comment by bhousel** [comment]
> When hashtags in a changeset comment are added or changed, iD automatically adds them to the changeset's hashtags= tag, which is great. However when all hashtags are removed it does not automatically update and leaves the hashtag tag even if there are no hashtags in the comment.

I'm not seeing this in http://preview.ideditor.com/master/
When I remove the comment, and change or leave the field, it removes the hashtags too.

Also what @pnorman said is correct.  The purpose of the hashtags field is not to match exactly the hashtags from the comment, but rather so that people can just write a normal comment and store the hashtags somewhere else.  For example, the hashtags can be set via a url parameter when a task manager launches iD.

**Comment by rivermont** [comment]
I am also not seeing this on the live site, only on https://osm.org

I'll close this then as it seems to have been unintentionally solved in the new version.
