### ISSUE TITLE
Allow users to paste several "k=v" tag pairs into the raw tag editor

### ISSUE THREAD

**Issue by famo** [openstreetmap/iD#6185]
It would be nice if we could use the "Add field" textbox to add new tags, e.g. by pasting 
`roof:levels=1` into it.
Currently one has to scroll all the way down to the end of the current tags list, hit + and then paste - this is cumbersome.

Furthermore it would be awesome, if we could enter several tags at once this way, e.g. by pasting: `roof:levels=1 roof:shape=gabled`.

**Comment by bhousel** [comment]
> It would be nice if we could use the "Add field" textbox to add new tags, e.g. by pasting
> `roof:levels=1` into it.

Sorry, but I disagree with repurposing the "Add Field" dropdown for this.  

If you are copy pasting tags like this, you should probably just hide the "All fields" section completely and use the "All tags" section.


> Furthermore it would be awesome, if we could enter several tags at once this way, e.g. by pasting: `roof:levels=1 roof:shape=gabled`.

Yeah this makes sense.. Currently it only supports pasting a single key-value pair, but we could allow people to paste several.

**Comment by famo** [comment]
> If you are copy pasting tags like this, you should probably just hide the "All fields" section completely and use the "All tags" section.

Well, I use both. But I see now that the "Add field" box really belongs to the fields section.

> Yeah this makes sense.. Currently it only supports pasting a single key-value pair, but we could allow people to paste several.

+1
Still tho, really looking for (speed) improvements here. How about an open textbox by default ("Add tags:")? Maybe even on top of the existing tags?

**Comment by bhousel** [comment]
> Still tho, really looking for (speed) improvements here.

I totally understand.. iD has to balance a lot of design concerns and we value simplicity over mapper efficiency and speed, so you might want to use a different tool like JOSM in the mean time.

I do want to make pasting tags work great, but this really is a niche need (most users don't and shouldn't care about what the tags are), so I don't want to just add a textbox for people to paste tags into and close the issue.  This actually is a very good idea and we might build something like that, but make it spark joy, you know?

**Comment by tordans** [comment]
> Furthermore it would be awesome, if we could enter several tags at once this way, e.g. by pasting: `roof:levels=1 roof:shape=gabled`.

This sounds a lot like what I tried to commented/request at https://github.com/openstreetmap/iD/pull/5070#issuecomment-396031571. Maybe this new issue will nudge @AndreasHae to have another look at it :-).

**Comment by AndreasHae** [comment]
Ah, so that's what you meant @tordans. Wasn't quite sure back then 😅
I'll have a look at it!

**Comment by tordans** [comment]
@AndreasHae thanks for working on this!

Since it is merged recently, I tested it at http://preview.ideditor.com/master/#background=Berlin-2018&disable_features=boundaries&locale=en&map=20.00/52.49902/13.39265

Some cases work great, some have issues yet.

Testcase: (the one from above)
`roof:levels=1 roof:shape=gabled`

Result: Problem
<img width="368" alt="Bildschirmfoto 2019-04-23 um 19 30 25" src="https://user-images.githubusercontent.com/111561/56602723-6f01d380-65fe-11e9-91c8-d50be2b0d1af.png">


Testcase:
```
roof:levels=1
roof:shape=gabled
```

Result: Same

Testcase:
```
name=lorem - ipsum
key=yes
```

Result:
Great

Testcase:
```
acces:conditional=private @ (12:00 - 14:00)
key=yes
```

Result: Problem
<img width="371" alt="Bildschirmfoto 2019-04-23 um 19 36 32" src="https://user-images.githubusercontent.com/111561/56603042-20a10480-65ff-11e9-9b91-5013fc860f5d.png">


Testcase:
```
maxspeed=80
maxspeed:hgv=60 @ (weight>7.5)
```
Source: https://wiki.openstreetmap.org/wiki/DE:Conditional_restrictions

Result: Problem
<img width="372" alt="Bildschirmfoto 2019-04-23 um 19 38 59" src="https://user-images.githubusercontent.com/111561/56603229-96a56b80-65ff-11e9-8b21-65feec2adcc1.png">


Testcase:
```
maxspeed=80
lorem=60 @ (weight=>7.5)
```

Result: Problem
<img width="364" alt="Bildschirmfoto 2019-04-23 um 19 39 39" src="https://user-images.githubusercontent.com/111561/56603210-8d1c0380-65ff-11e9-8726-1f216e689fdf.png">

**Comment by bhousel** [comment]
> I do want to make pasting tags work great, but this really is a niche need (most users don't and shouldn't care about what the tags are), so I don't want to just add a textbox for people to paste tags into and close the issue. This actually is a very good idea and we might build something like that, but make it spark joy, you know?

I'm working on this today.  I think I can make the raw tag editor toggle between text and list modes, so that people who who want to copy and paste things can just use the text mode to do it.

**Comment by bhousel** [comment]
Also, kind of amusing, but the code from #6211 which accepts pasted `key=value` pairs allows users to circumvent the readonly tag protection, so I'm removing it.

![edit readonly tag](https://user-images.githubusercontent.com/38784/57081931-b9044c80-6cc3-11e9-80a8-2ba72cc5cc3b.gif)
