### ISSUE TITLE
Don't suggest adding highway=footway to areas tagged with man_made=pier 

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6229]
Try editing around here with the validation set to "Everything, Everywhere:" 
 http://preview.ideditor.com/master/#background=EsriWorldImagery&disable_features=boundaries&map=18.12/35.94659/-79.03258

The issue is that iD suggests fixing every `outdated tags` issue, but then complains about the piers mapped as areas being `disconnected from other features`

**Comment by quincylvania** [comment]
Yep, this was an intentional change in #6042. Routers like OSRM treat `man_made=pier` as routable anyway, so our intention is to make the implied behavior explicit.

For the area you specified, I'd map the informal routes that people would take to get to the piers with `highway=path` + `surface=grass` + `access=private`. Or you can just disable the disconnected highway rule.

For piers in the middle water, it makes sense that they'd be routing islands because you can't really walk there. Maybe we should think of a tag to indicate that a highway cannot be connected back to the network, similar to how `noexit=yes` indicates an endpoint shouldn't connect to nearby highways.

**Comment by BjornRasmussen** [comment]
I really don't think that _areas_ should be given the tag.  I am all in for ways, though.
In that area, mapping all of those piers connections would 
1) be a huge task with little benefit.  
2) be intrusive to people's privacy.  
I just seems wrong to add `highway=footway` to these piers.  It is also annoying to have all of the `disconnected from other highways` warnings.

**Comment by quincylvania** [comment]
@BjornRasmussen With #6242 you can now ignore these issues manually to keep them from showing up while you edit. Perhaps that's an okay solution for this?
