### ISSUE TITLE
Error message: "Fatal error: Couldn't find end of Start Tag tag at :1."

### ISSUE THREAD

**Issue by rene78** [openstreetmap/iD#6232]
**Update**
I found the cause of the error described below: I copied and pasted the Wikipedia link to a sub-heading, which had a dot inside: _**https://de.wikipedia.org/wiki/Geschichtspfad_Friedrichshafen#Ehemaliges_Ledigenheim_-_Tafel_4.10**_
After pasting it to iD the link turned into **_Geschichtspfad Friedrichshafen#Ehemaliges Ledigenheim - Tafel 4_**. This malformed URL lead to the upload error. After changing the URL manually no more problems.

**Original post**
While trying to update [node 6424244344](https://www.openstreetmap.org/node/6424244344) I am getting the following error message:
![image](https://user-images.githubusercontent.com/36115705/56618336-966a9780-6622-11e9-9390-81118eb2e8ab.png)
After clicking on Okay and trying to save again, the login page is displayed:
![image](https://user-images.githubusercontent.com/36115705/56618463-fcefb580-6622-11e9-8009-ddf2b4c04ff0.png)
After a click on "Allow access" the app is greyed out and nothing can be clicked anymore.
Those are the tags that I added to the node (in case this matters in any way):
![image](https://user-images.githubusercontent.com/36115705/56618381-b4d09300-6622-11e9-809a-ba75cedde086.png)

**Comment by mmd-osm** [comment]
I can reproduce the error on http://preview.ideditor.com/master and dev instance: after pasting the string 
`https://de.wikipedia.org/wiki/Geschichtspfad_Friedrichshafen#Ehemaliges_Ledigenheim_-_Tafel_4.10` into the wikipedia field, an u0010 character is automatically appended at the end. This character also appears in the osc file. As it is invalid XML the API refuses the osmChange message.

`<osmChange version="0.6" generator="iD"><create><node id="-1" lon="7.182067064782307" lat="50.100773134692865" version="0"><tag k="shop" v="supermarket"/><tag k="wikipedia" v="de:Geschichtspfad Friedrichshafen#Ehemaliges Ledigenheim - Tafel 4"/></node></create><modify/><delete if-unused="true"/></osmChange>`

**Comment by bhousel** [comment]
Thanks for reporting..  It's a bug in this code:
https://github.com/openstreetmap/iD/blob/a72865e4d85462cf8c071ce31e30b1191de249ba/modules/ui/fields/wikipedia.js#L172-L173

Which is intended to transform "anchorencoded" links but not really working.  This is apparently a thing MediaWiki does ([see link](https://phabricator.wikimedia.org/T160877)).

I'm going to just comment out that code because, as far as I can tell, it shouldn't matter on the OpenStreetMap side whether we store the nice links or the ugly ones - both of them will take users to the right wiki page.  cc @1ec5 who probably knows more about this.  We can put it back later if it really is important.
