### ISSUE TITLE
Make building:levels and height default fields for any building

### ISSUE THREAD

**Issue by famo** [openstreetmap/iD#6238]
I think it would be good to have `building:levels` and `height` field available for any building. Currently it is only available for some selected buildings.

**Comment by westnordost** [comment]
I'd advise against enabling `building:levels` for any building. For certain buildings, it just does not make sense to specify that. (And I think it is better to have a white list rather than a black list)

FYI, StreetComplete shows the "building level quest" currently for these building types only:
```
house,residential,apartments,detached,terrace,dormitory,semi,semidetached_house,bungalow,
school,civic,college,university,public,hospital,kindergarten,transportation,train_station,hotel,
retail,commercial,office,warehouse,industrial,manufacture,parking,
farm,farm_auxiliary,barn,cabin
```

**Comment by bhousel** [comment]
We won't be adding a list of "buildings where it makes sense to specify levels".  If it makes sense for some types, it makes sense for all types.

**Comment by westnordost** [comment]
Not sure if your comment is about what is possible with the iD tagging preset system or about the real world in general. In case it is the latter, for your consideration, here are some examples for buildings where `building:levels` is not applicable because they are not made (for humans) to enter. Picked from taginfo:

<table>
<tr><td>
<img width=300 src="https://upload.wikimedia.org/wikipedia/commons/9/9c/Ehemalige_Tankstelle_von_1957_-_Hannover-Badenstedt_Gabelung_Burgundische_Stra%C3%9Fe-Empelder_Stra%C3%9Fe_-_panoramio.jpg"/>
</td><td>the `building=roof` of this petrol station</td></tr>
<tr><td>
<img width=300 src="https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2F3.bp.blogspot.com%2F-GxJJIoc8Hus%2FUWqpAhqJTKI%2FAAAAAAAAB9M%2FmwLqKAteVmk%2Fs1600%2FDSM_Building_Collapse_2013.jpg&f=1"/>
</td><td>`building=collapsed`</td></tr>
<tr><td>
<img width=300 src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Gylletank30m.jpg/320px-Gylletank30m.jpg"/>
</td><td>`building=slurry_tank`</td></tr>
<tr><td>
<img width=300 src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Sankt-georgen-kaernten.jpg/306px-Sankt-georgen-kaernten.jpg"/>
</td><td>`building=wayside_shrine`</td></tr>
</table>

And more.
(Though, what is conspicuous with these examples is that all of these would be things were `man_made` as the key would have been a better fit)

**Comment by quincylvania** [comment]
> I think it would be good to have building:levels and height field available for any building. Currently it is only available for some selected buildings.

@famo What you're seeing is that features with just a `building` tag have lots of building fields while feature that also have a more specific tags like `amenity=cafe` don't, since they match presets that could be both buildings or non-buildings.

We could actually solve this quite easily by adding the `prerequisiteTag` property to all building fields so they only appear if a `building` tag is present on a feature. We could then add these fields to all kinds of POIs, or even just make then universal.

@westnordost I agree with Bryan on this one. Most `building` values will be fine most of the time, and if not users can decide for themselves when certain data is inappropriate.

**Comment by famo** [comment]
@quincylvania Actually what sparked me to create this issue, was that I missed it for `garage(s)` and `shed` and I fail to see why not enable these preset for every building...

**Comment by quincylvania** [comment]
@famo Oh interesting! Thanks for the further info, I hadn't even realized that some building presets didn't show all the building fields. I changed all the building presets I could see to show all the default fields. Leaving this open since we still might find a way to show some building fields for building POIs.

**Comment by famo** [comment]
@quincylvania Does your change mean that also `name` and `address` are now enabled by default for these /every building?
Because I think those presets are really not needed by default for every building.

**Comment by quincylvania** [comment]
@famo For all the building presets, yes. Not every building may have these but any building could, so I think it's fine to give people those options.

**Comment by quincylvania** [comment]
I added Building Levels and Building Height fields to some POIs when they are tagged as buildings. These could theoretically be added to any preset with a "building_area" field, but I think they're fine for now. We can add them as-needed.
