### ISSUE TITLE
Simpler management of deprecated presets

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/iD#6262]
### Current situation

Currently, when a preset is deprecated, it gets added to the `deprecated.json` but also remains in the `/presets/presets/` directory with an underscore at the beginning, `searchable: false` and possibly `replacement: ...` set.

### Proposal

Couldn't iD also derive the necessary information for a deprecated preset from only the `deprecated.json`? In this case, all the deprecated presets that have an unambiguous replacement could be removed from the directory.

For example, if in the `deprecated.json`, there is the mapping `amenity=embassy` -> `office=embassy`, and the preset for `office=embassy` exists, then iD could as part of it's build process generate an `amenity=embassy` preset out of the `office=embassy` preset (with `searchable: false` etc. set) for the final `presets.json`.

This would have the following advantages:
- less preset definitions to maintain
- easier to deprecate a preset in the future
- translators need to maintain less translations
- and thus: no possible inconsistencies in translations for the deprecated preset and the replacement preset
- better coverage of map features <-> names, because currently not every deprecated preset that is listed in `deprecated.json` also has an accompanying `_some_deprecated_preset.json` in `/presets/presets/`

**Comment by quincylvania** [comment]
This is an interesting idea, but I don't really see an advantage to generating and integrating a ton of presets that we want people to instantly stop using.

Actually, I'd prefer to go there other way and remove more deprecated presets. Now that we have tag upgrading, I think the goal is to encourage that as much as possible. When a user clicks on a feature with `amenity=swimming_pool`, it shouldn't look the same as `leisure=swimming_pool`. It should look kinda wrong until they click "Upgrade tags", because a modern data consumer isn't going to interpret it as a swimming pool until they do that anyway.

**Comment by westnordost** [comment]
Well, it is always possible to make something look "kinda wrong". The deprecated presets generated from `deprecated.json` could have no icon, no description, no fields, no everything except for the name, perhaps all deprecated presets could get a special `maki-deprecated` icon etc.

Of course it is important that iD understands that a feature is deprecated and offers a clear way to "upgrade", but this is nothing this ticket would change. This ticket would only change that iD understands **automatically** without manually defining and translating extra presets what a feature that is deprecated means. 

In prose, it could show _"This is a swimming pool. But the tagging is deprecated, click here to upgrade the tags."_, instead of _"This is a **??? (deprecated)**. Click here to upgrade the tags."_

**Comment by quincylvania** [comment]
@westnordost Hmm I get your points, but again, I don't see much incentive to put in work to make something nicer for the two seconds before the user presses the upgrade button. This ticket would be a lot of work and have to reconcile a lot of unknowns. We can't do this automatically since not every `deprecated.json` entry maps to a current preset.

**Comment by westnordost** [comment]
> not every `deprecated.json` entry maps to a current preset.

Yes, so this would only be about those that do.
