### ISSUE TITLE
Ignored issue is still shown as an issue on the feature editor

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#6325]
http://preview.ideditor.com/master/#background=finds.jp_KBN_2500&disable_features=boundaries&id=w688368653&map=21.00/35.68932/139.78641
![](https://i.imgur.com/VKYqrW3.png)
although the "warnings:unsquare_way" flag is on.
![](https://i.imgur.com/MovE0ix.png)

**Comment by bhousel** [comment]
Yes, iD still will show any issues for each feature, even if they are not issues caused by your edits...  I think the message even says "Your edits look fine but there are issues with 47 other features".

I think the `warnings:unsquare_way` changeset tag just means that in that changeset there was an issue detected on one of your buildings.. However it's not necessarily this one, or if it was, you ignored the warning (which is totally ok to do).

I did notice that if I tried editing the building by dragging a node, it did not count that building as one of my edits.  This is a tricky problem, but maybe we can improve it.

**Comment by sun-geo** [comment]
I was trying the same thing last week, because I was curious if there are added changeset-tags for warnings when I hit the ignore selection for some issues. So far I remember the ignored issues were also flagged in the changeset tags. And maybe the idea should be for those actively ignored cases that they shouldn't monitored. But then I was happy to found the way for not tracking all issue when I uncheck the "disable all" box, before saving/uploading :-)

![image](https://user-images.githubusercontent.com/47290585/57303488-b481ce80-70dd-11e9-8d61-f8a8eb294e5e.png)

**Comment by bhousel** [comment]
> But then I was happy to found the way for not tracking all issue when I uncheck the "disable all" box, before saving/uploading :-)

Yes - unchecking the rules will let you opt out of the validator warnings.
(iD is still running the rules in the background, it just won't show you the results or warn you about them)

**Comment by sun-geo** [comment]
Yes, I had app. 100 issues about not squared buildings, while the validation was "Enable All" of course. I solved app. 95 of them and the remainng 5 were some kind of "false positives" for these 5 I used the ignored status. Because I doesn't wanted to be monitored and flaged for these 5 as changeset tag warming I switched off the validation only while & before saving/uploading the data to the osm-database. So I wonder if this is really wanted by intension. Maybe the ignored issue should also not count for the changeset warning tags...

**Comment by quincylvania** [comment]
@sun-geo I appreciate mappers working to address all validation errors! However, you needn't worry about the ignored warning counts in the changeset tags. It's imperfect derived data based on your public changes. We can't remove ignored warnings from the counts since then they would be unreliable—poor mappers could just manually ignore all the warnings and go unnoticed. In fact, I removed the workaround where disable rules wouldn't affect the counts.

A better solution is to reduce false positives in iD's validator. Let us know when there are ways we could improve it!

**Comment by quincylvania** [comment]
Closing this as stale. iD has been including ignored warnings in the changeset tags for months now without anymore pushback. I still think it's better to do than not do.

Once we do #6459 we can improve the warning tags to only include the issues actually created by the user, not all issues for edited features. For example, if you changed the tags of a nonsquare building it wouldn't flag a warning in the changeset since you didn't make the building unsquare yourself.
