### ISSUE TITLE
Add fix to tag real unsquare buildings as unsquare

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#6332]
We want buildings to have nice square corners in OSM—unless they're not square in the real world. iD should offer a fix like "Tag as accurate" that will add a tag like `unsquare=yes` to indicate a building is known to be truly irregular. This will prevent iD and other tools from continuing to falsely flag the issue in the future.

![Screen Shot 2019-05-07 at 3 19 46 PM](https://user-images.githubusercontent.com/2046746/57326923-93b87980-70db-11e9-8af8-6fbb02a53fb3.png)

Other false validation issues are already tagged similarly in OSM, such as with [`noexit=yes`](https://wiki.openstreetmap.org/wiki/Key:noexit) and [`noname=yes`](https://wiki.openstreetmap.org/wiki/Key:noname).

**Comment by Nakaner** [comment]
Although `noname=yes` is common, it is not that common that it can serve as an argument in favour of introducing `unsquare=yes`. In difference to `noexit=yes`, `unsquare=yes` and `noname=yes` only serve as a workaround for quality assurance tools. `noexit=yes` also conveys information for map users: There road ends here.

Some people prefer to tag as complete as possible and add `oneway=no`, `cycleway=no`, `lit=no` etc. to any way. However, such a practice is not base on a broad consensus and if you dig deep enough in the history of user blocks in OSM, you might find blocks set due to an excessive use of negative binary tags.

I think that iD does not need this tag and should only validate buildings if they have been added or modified in the current session. If doing so, they will be reported once which does not bother that much.

Adding such a tag is not a simple change as it might seem to be and I ask you to discuss it with the broader community on the Tagging mailing list.

**Comment by pnorman** [comment]
I agree that this needs to be proposed to the broader community and discussed before encouraging people to add such a tag.

**Comment by quincylvania** [comment]
I did this! I ended up using `nosquare` for the tag to align it with `noname` and `noexit`. Mappers can now fully resolve all unsquare way issues. If you manually square the feature later, then the tag is automatically removed.

![unsquare demo](https://user-images.githubusercontent.com/2046746/57468685-f6805100-7252-11e9-864e-045feb7b772d.gif)

@pnorman said:

> I agree that this needs to be proposed to the broader community and discussed before encouraging people to add such a tag.

iD development isn't driven by the tagging mailing list nor tagging proposals. Our goal is to help hundreds of thousands of mappers around the world easily create accurate, unambiguous data. Sometimes (very rarely) this may entail making up new tags, but all tags are made up anyway so I don't see an issue here.

**Comment by Nakaner** [comment]
@quincylvania Your behaviour is not commendable.

**Comment by lonvia** [comment]
May I kindly suggest that you consider what this feature does to an average [town older than 300 years](https://www.openstreetmap.org/#map=18/50.08961/14.42366). Right angles are seriously overrated.

**Comment by quincylvania** [comment]
@lonvia Good point! We think we've struck an okay balance to reduce false positives. iD won't flag buildings connected to other buildings nor buildings with lots of points. Buildings with additional tags cannot be fixed without review. In fact, I loaded [that area with preview iD](http://preview.ideditor.com/master/#background=Bing&disable_features=boundaries&map=18.00/50.08961/14.42366) and only saw about a dozen unsquare building warnings.

**Comment by BjornRasmussen** [comment]
The key nosquare makes no sense.  Now it, no name, and others are logical English, but nosquare implies that the building doesn't have a square somewhere to the many mappers unfamiliar with the tag.  Could you use notsquare instead?

**Comment by quincylvania** [comment]
@BjornRasmussen I changed it to `nonsquare`, which is an [actual English word](https://en.wiktionary.org/wiki/nonsquare) and should be more friendly. Thanks!

**Comment by Nakaner** [comment]
For reference, this topic is now discussed on the Talk mailing list. https://lists.openstreetmap.org/pipermail/talk/2019-May/082506.html

**Comment by mmd-osm** [comment]
Interesting proposals out there: https://lists.openstreetmap.org/pipermail/talk/2019-May/082522.html

_it can participate with other solutions like better training to assure that Newbies understand what Building tracing really mean and give then some feedback, like for example saying before save **"You have 10 over 12 buildings that are unsquarred.  If you dont know how to make rectangular buildings, you should ask for help before you continue.  Do you want to send data anyway ?**"_

**Comment by quincylvania** [comment]
I encourage everyone interested in the unsquare buildings validation to try it out for themselves on our [live preview site](http://preview.ideditor.com/master) before jumping to conclusions about how it works.

As with all our validation rules, we put a lot of thought into making unsquare issues contextually relevant and easy to resolve with accuracy.

By default, you only see issues with your own edits. This means new mappers aren't prompted to square random buildings, just their own additions. If you want to be a power-validator—awesome!—you can switch to validating all loaded data in the Issues pane.

![Screen Shot 2019-05-10 at 4 29 48 PM](https://user-images.githubusercontent.com/2046746/57555849-653cd780-7343-11e9-9573-dc96cff91746.png)

If you don't want to use `nonsquare=yes`, or you're not sure if a building is actually square or not, you can select the new "Ignore this issue" option instead. This silences the particular warning for your current session, but it won't convey any information to other mappers.

![Screen Shot 2019-05-10 at 4 51 28 PM](https://user-images.githubusercontent.com/2046746/57556220-6b7f8380-7344-11e9-8ac2-d144c8f5ccb9.png)

And if you don't find unsquare warnings helpful at all, then you can simply turn them off.

![Screen Shot 2019-05-10 at 4 27 13 PM](https://user-images.githubusercontent.com/2046746/57555518-7b966380-7342-11e9-8dc1-ec9635dd97ed.png)

**Comment by mmd-osm** [comment]
"Warning" as a category for non-squared buildings along with a yellow exclamation mark seems a bit strong for the average user. Moving this check to "Information", along with some blue Information icon would probably be more appropriate.

> you can select the new "Ignore this issue" option instead. This silences the particular warning for your current session, but it won't convey any information to other mappers.

I see one major drawback of this approach: as you don't have a dedicated backend service to store "false positive" user decisions (unlike "real" QA tools, like osmose), the warning will resurface the next time you map in that area. Ignoring is really only feasible for a one off mapping event, otherwise this tends to be quite annoying.

I tried this in some rural area in France where imported official cadastre data prevails. Yet, most of the buildings were "to be squared" candidates, making the "power-validator" mode kind of pointless. Adding an extra tag to all those buildings to silence iD seems kind of weird.

**Comment by SilentSpike** [comment]
>Moving this check to "Information", along with some blue Information icon would probably be more appropriate

Having another level of validation is something I've been thinking of suggesting also. 

It could be used for things that aren't guaranteed to always be wrong (such as these nonsquare buildings or the email/website format validation I've had a play around with) - as such never being included in the "fix all" operation.

**Comment by woodpeck** [comment]
I realize this is not a vote but I'd like to register my profound disagreement with editor writers unilaterally inventing new tags they feel are a good idea. Nobody in OSM is so brilliant that they should have that kind of power. Not without discussing it *first*, like we expect of any import or mechanical edit for precisely the reason that what seems like a good idea to the inventor could turn out not so good after a few more people have looked at it from different angles.
