### ISSUE TITLE
Depreciate the preset office=therapist and add quick fix to use healthcare=* instead

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6370]
See https://wiki.openstreetmap.org/wiki/Tag:office=therapist?uselang=en#/issues

**Comment by bhousel** [comment]
I'm not sure about this.. Are `healthcare` tags even rendered yet?

**Comment by BjornRasmussen** [comment]
Sounds fine by me - I just saw the tag in depreciated features and remembered the iD preset, so I decided to open an issue.

**Comment by bhousel** [comment]
We can't just change a thing because someone writes something on the osm wiki.  
Can't stress enough that the wiki is more wrong than right these days.

**Comment by bhousel** [comment]
related https://github.com/gravitystorm/openstreetmap-carto/pull/3731

**Comment by Lukas458** [comment]
I deprecated the office=therapist tag because we "have" now better alternatives which also do more differentiate between the several kinds of therapists, and because the healthcare-tagging scheme just got the "approved" status in the osm-wiki. I discussed with the creator of the office=therapist-wikipage at https://forum.openstreetmap.org/viewtopic.php?id=64980 (in german). I agree that we might wait until healthcare=* tags are rendered at the openstreetmap-carto style (again). I remember healthcare=physiotherapist etc. will get a "dot" then there, but just red insted of blue like the office-features,
