### ISSUE TITLE
Don't complain about a highway crossing a parking garage (building=parking)

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6380]
This is the only false positive for the building/highway crossing validation I see, and I see it a lot.  The issue is that it's not clear at all how to fix the issue, since the parking aisles actually do go _inside_ of the building, which is something the current iD validator doesn't expect.  
Try resolving the issues here to see what I mean: http://preview.ideditor.com/master/#map=19.66/35.93907/-79.01812

**Comment by BjornRasmussen** [comment]
Hmm.  I added covered to the roads underneath, and that fixed the validation complaints.

**Comment by BjornRasmussen** [comment]
Here's a better example: http://preview.ideditor.com/master/#background=EsriWorldImagery&disable_features=boundaries&id=w534103775&map=20.29/35.91620/-79.05727

**Comment by quincylvania** [comment]
@BjornRasmussen This is a tricky instance. iD can handle this if you treat the parking aisles sort of like indoor features. So you can resolve the crossing highway issues by setting the `level` tags on the parking aisles. For the building/highway issues you can connect the parking aisles to the building, possibly with `amenity=parking_entrance`.

I'm closing this since I think we can leave the validator behavior as-is, but we should think of ways to teach people this pattern.

**Comment by BjornRasmussen** [comment]
How should [this issue be resolved?](http://preview.ideditor.com/master/#background=EsriWorldImagery&disable_features=boundaries&id=w623562755&map=21.27/35.91049/-79.04268)

**Comment by quincylvania** [comment]
@BjornRasmussen I'd also connect the parking aisle to the building.

**Comment by BjornRasmussen** [comment]
Sounds good.
