### ISSUE TITLE
Read photo id from query string for street-level imagery 

### ISSUE THREAD

**Issue by cbeddow** [openstreetmap/iD#6398]
Example:

`https://www.openstreetmap.org/edit?editor=id#map=18/39.93450741752976/-105.0910279993947?photo_overlay=mapillary&photo=o6y6pgnHjz7vdEbjY7YCtg`

This link, for example, would make sure the Mapillary photo overlay is turned on, and then initiate the MapillaryJS viewer and execute `moveToKey('o6y6pgnHjz7vdEbjY7YCtg')` which would open that specific image, so a user can start editing right away.

**Comment by planemad** [comment]
This is a great suggestion. I find the Mapillary explorer pretty powerful to navigate through various imagery/filters and would love to jump to iD from a specific Mapillary image and retain context of what i wanted to edit.

**Comment by cbeddow** [comment]
Yes if we can get this working then we'll link directly from Mapillary's website to open the same current photo in iD, ready to edit :)

**Comment by EuropeanWaterProject** [comment]
This would be  very helpful... has any progress been made on this ?

**Comment by quincylvania** [comment]
> has any progress been made on this ?

@EuropeanWaterProject Not yet…

**Comment by quincylvania** [comment]
@nickplesha implemented this for Mapillary photos in #7885!

I'm going to work on achieving parity for OpenStreetCam and Bing Streetside. As part of supporting multiple services, I prefixed the format like `photo=mapillary-eZxLgJ9sHstg0ySKE3plLw`. We can't rely on `photo_overlay=mapillary` since that key supports multiple layers, e.g. `photo_overlay=streetside;mapillary;openstreetcam`. Plus this lets iD open the correct layer automatically if `photo_overlay` is left off.

**Comment by tordans** [comment]
@quincylvania I know I am late to the party, just a quick though: Reading `photo=mapillary-eZxLgJ9sHstg0ySKE3plLw` makes me think of an ID that is actually `mapillary-eZxLgJ9sHstg0ySKE3plLw`. But reading your comment, its more of a identifier/category+ID which IMO could be shown a bit better by something like `photo=mapillary/eZxLgJ9sHstg0ySKE3plLw` or `photo=mapillary;eZxLgJ9sHstg0ySKE3plLw` or `photo=mapillary+eZxLgJ9sHstg0ySKE3plLw`.

**Comment by quincylvania** [comment]
@tordans Hmm, that's a good point. The slash might work better. We can easily change this since we haven't released it yet.
