### ISSUE TITLE
Add preset for ski resorts

### ISSUE THREAD

**Issue by DFyson** [openstreetmap/iD#6403]
I have noticed ski resorts have a history of being mapped using a variety of tags. Documentation for [piste maps](https://wiki.openstreetmap.org/wiki/Piste_Maps) shows tagging the resort area using landuse=winter_sports. It would be nice if that would come up as a preset when searching for _ski resort_ or synonyms such as _ski hill_ or _ski area_.

**Comment by quincylvania** [comment]
@DFyson I added a "Winter Sports Area" preset for `landuse=winter_sports` since it has a fair amount of usage. While this tag works for tagging the land designated for recreation, I'm not sure it fits for tagging the point-of-interest itself. Something under `leisure` or `tourism` might work better, but there doesn't appear to be consensus.
