### ISSUE TITLE
Why there is no more kerb preset for highway crossing ?

### ISSUE THREAD

**Issue by phiphou** [openstreetmap/iD#6429]
Why there is no more kerb preset for highway crossing ?

**Comment by bhousel** [comment]
I believe the recommended practice these days is to assign the kerb ramp tags on the crossing-sidewalk junction nodes, not on the crossing way itself.

see #6078

**Comment by stragu** [comment]
Hi @bhousel 
Just curious: do you have a source for such recommendation?
I think @phiphou was asking about `highway=crossing` specifically, which is used for nodes, rather than `highway=footway` + `footway=crossing`, which you describe.
I think it is rather impractical to assume that everyone is keen to move to tagging sidewalks separately to roads, especially in areas where there is little data mapped. Removing the kerb presets for single crossing nodes might mean that we'll loose useful information because mappers will not want to dive into such a level of detail when they simply want to add a pedestrian crossing.

What do you think?
