### ISSUE TITLE
Violation of code of conduct in https://github.com/openstreetmap/iD/issues/6409#issuecomment-495231649

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/iD#6442]
iD has a code of conduct at https://github.com/openstreetmap/iD/blob/master/CODE_OF_CONDUCT.md and I believe that https://github.com/openstreetmap/iD/issues/6409#issuecomment-495231649 breaks a number of the rules outlined there.  Specifically it

- clearly fails to "Please be respectful to one another."
- does not "assume that the person with whom you disagree is a smart person with good reasons for believing something different"
- includes "Trolling or insulting/derogatory comments"

To be clear, I don't think that anyone doubts that the sometimes iD developers sometimes have to make difficult and unpopular decisions, and sometimes threads need to be locked to keep the same old questions being raised over and over again.  That doesn't however seems to have been what's happened here - there's been relatively little discussion on https://github.com/openstreetmap/iD/issues/6042 and https://github.com/openstreetmap/iD/issues/6409 was closed with what can only be described as something of a rant.

I would suggest that, in line with the "When you make a mistake, apologize." clause of CODE_OF_CONDUCT.md , that a personal apology is made to the people referred to in that comment.  This should include:

- the "people on a mostly dormant mailing list" (the tagging list, I presume)
- people who contribute to the osm wiki
- people who contribute to "the weekly osm tabloid" (http://weeklyosm.eu I presume)

Best Regards,

Andy

PS: For the avoidance of doubt this is written in an entirely personal capacity.  Full disclosure - I do occasionally edit and review http://weeklyosm.eu prior to publication (as can anyone else if they wish to sign up to do so).

**Comment by tastrax** [comment]
Hi Folks,

 

I don’t believe #6409 comment breaks the rules at all and I certainly don’t see it as a rant.

 

The developers seem to be quite clear  in the stance they are taking on this and many other issues with the following statement..

 

“iD is taking a very consistent approach in that for issues like this, where we can replace an implicit rule with an explicit one - we add the extra tag. In cases where a tag has multiple meanings, we only support a single unambiguous use. We don't expect people to "just know" what all OSM's made up rules are.”

 

The other text merely spells out some of the difficulties they have faced over similar issues. To me, this is the nature of the Open source beast. Its fluid, changes over time and has varying opinions, often over time. The fact that it changes regularly must be an issue for all the editor developers.

 

Without OSM having some single authoritative repository of all “tags and rules” that can be used by all developers this type of discussion will continue and help foster the growth of the project. Again, I suspect that a more regimented process for the ‘final acceptance of tags’ may go some way to preventing such angst between enthusiast, users and developers. 

 

Having said that, I am no coder, just a consumer of the maps and a part time editor. Even with the new validation in place I don’t automatically ‘fix all’ and I suspect many others don’t either. If it looks reasonable to me, I will update the tags. Other times I will investigate the tagging.

 

Some people will disagree, and that's ok.

 

Cheers - Phil

**Comment by bhousel** [comment]
@SomeoneElseOSM  I take code of conduct violations very seriously.  I'll ask for an independent volunteer who has been trained to take a report to follow up with you as soon as possible.  This would normally be an anonymous process, but since you have opened up a public issue about it, we can't guarantee that for you.  

Anyway, I'm asking you to limit your interaction with the iD project while the investigation happens, and I'll do the same.

I'm locking this thread - I know people hate when I do that, but further discussion of a CoC complaint is really not a good thing.  (In the previous situation, I locked the thread because people where asked elsewhere to drop in and complain, not because there was a discussion happening).

In the future I'd really appreciate if people follow the part that says "Instances of unacceptable behavior may be reported privately to the project maintainers."   Yes, I know it's about me and I'm the maintainer, but we would still follow the process and try to treat everyone fairly.

**Comment by jonahadkins** [comment]
Hi,

I’m an OSM-US & OSMF community member with prior training in CoC response. I was asked to adjudicate this incident.  Here’s a synopsis of my review:  

I reached out to the reporter (@SomeoneElseOSM) via 1:1 email on May 28th, 2019  to take a report of this incident. I reviewed the details of that report, which included the information in this Github issue above.  

After this review, it is my belief that while the comment goes to great lengths to cordially state the view of the reportee (@bhousel ),  parts of it do contain a derogatory tone. It is recommended that @bhousel  should adhere to the stated iD Code of Conduct guideline of _“When you make a mistake, apologize.”_  Specifically, its asked that an apology is posted below his comment on the [iD Project GitHub issue](https://github.com/openstreetmap/iD/issues/6409#issuecomment-495231649). Both parties received a formal CoC response letter via email and I have personally discussed the response with them over phone/video chat.  

I’d also like to add that this CoC review and report was difficult due to the lack of more formal processes for reporting and reviewing CoC issues. While reviewing,  I consulted with two other community members (not involved with the incident) about CoC procedures in OSM. Therefore, I'd also like to  recommend that the iD Project:

- Creates a safe space for iD Project Code of Conduct reports to be made, such as a standard form available as a link from the CoC.
- Designates individuals not involved with the project to handle Code of Conduct issues, ideally through a committee or working group made of diverse community members.
- Work with other community members to develop a formal iD Project Code of Conduct process/procedure. 

Please feel free to reach out to me with any comments, questions, or concerns.   
Jonah Adkins  
[jonahadkins@gmail.com](jonahadkins@gmail.com)

**Comment by SomeoneElseOSM** [comment]
@jonahadkins I don't see an apology here (or at https://github.com/openstreetmap/iD/issues/6409#issuecomment-495231649 ).  What's the next step?

**Comment by bhousel** [comment]
Thanks @jonahadkins for agreeing to step in as an independent responder.  _I agree that my tone on #6409 and other recent issues has been derogatory and I apologize for that._

When I established the Code of Conduct in #3051 I wrote:
> I'm resolving to do a better job of keeping this project a friendly place where anyone can feel comfortable contributing.
> When I fall short of this goal, please call me out on it. 

Thank you @SomeoneElseOSM for “calling me out on it”.

> I’d also like to add that this CoC review and report was difficult due to the lack of more formal processes for reporting and reviewing CoC issues. While reviewing, I consulted with two other community members (not involved with the incident) about CoC procedures in OSM.

I agree with all of Jonah's recommendations on improving the reporting process and I’m happy to implement these improvements with the help of the wider community.  It would be great to see OSM-US take the lead on establishing an independent and shared CoC reporting process for projects that want to opt in to it.

**Comment by SomeoneElseOSM** [comment]
Thanks Brian.

As suggested above, would it also be possible to apologise on the tagging list directly?  I can see that it would be technically difficult to do so to the OSM wiki as it doesn't really have a place for "announcements", and likewise I'm sure that http://weeklyosm.eu will see your message and can link to it if they want to, but the tagging list is something that it's possible to post to.

**Comment by bhousel** [comment]
> As suggested above, would it also be possible to apologise on the tagging list directly?

It was not suggested above.

I will not be apologizing to anyone on any mailing lists or weekly OSM, not do I expect any apologies from any of them for their behavior towards me.

Knock it off already.  You've made your point.

**Comment by SomeoneElseOSM** [comment]
For the avoidance of doubt, it was suggested in the initial comment at https://github.com/openstreetmap/iD/issues/6442#issue-448868768 (and further comments at https://lists.openstreetmap.org/pipermail/talk/2019-May/082609.html et al reinforced in my mind the need for it).  

As a community we have to work together - sometimes with people who hold different views.  The first step along that road is always trying to engage with people and trying to understand where they're coming from, and that can't really happen if there's a refusal to communicate.
