### ISSUE TITLE
incorrect brand tagging for S-market 

### ISSUE THREAD

**Issue by crimsondusk** [openstreetmap/iD#6449]
[S-market](https://fi.wikipedia.org/wiki/S-market) is a chain of supermarkets in Finland. If I add a node and tag it "shop=supermarket" and "name=S-market", iD wants to fill in brand tags, like so:
![2019-05-28 14_05_30-OpenStreetMap](https://user-images.githubusercontent.com/4590153/58473732-0accb500-8152-11e9-90ce-ba0653fa4de1.png)

You can see that it wants to incorrectly capitalize the "m" in the brand and name tags.

**Comment by Adamant36** [comment]
Hi there. That's because it's capitalized in the name index. If you re-open the issue there it should be fixed fairly quickly. I'll do it tomorrow if know one else does. Although, it might take awhile for the change to show up in iD editor. 

Here's the link to it https://github.com/osmlab/name-suggestion-index

**Comment by quincylvania** [comment]
Yep, iD gets this from the name-suggestion-index project.
