### ISSUE TITLE
"FIXME" vs "fixme"

### ISSUE THREAD

**Issue by userGeph** [openstreetmap/iD#6477]
Both "FIXME" and "fixme" are presets for tags. However a warning is generated in the right pane only when something is tagged with the lower case version. So either the upper case version should be deprecated and removed as a preset or it should be treated the same as the lower case version.

**Comment by quincylvania** [comment]
I would love to deprecate `FIXME`, since it is a duplicate, has nonstandard capitalization, and has 14% the usage of `fixme`. However, `FIXME` still has 186,000 uses so perhaps there's a good reason some people prefer it? We should ask around first.

**Comment by manfredbrandl** [comment]
Even in the "core"-strings on transifex FIXME and fixme are mixed:
![image](https://user-images.githubusercontent.com/5360273/58806585-c8eeb380-8616-11e9-96a9-a715bba05dc2.png)
I just changed FIXME to fixme in the german translations (fixme is not translated).

**Comment by matkoniecz** [comment]
Some time ago I proposed worldwide bot edit and there was some opposition, but all of it was "I dislike cosmetic bot edits" or "I dislike bot edits". See https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/moving_FIXME_to_fixme and discussion linked from that documentation page

For edit limited to Poland that was done see https://wiki.openstreetmap.org/wiki/Mechanical_Edits/Mateusz_Konieczny_-_bot_account/moving_FIXME_to_fixme_in_Poland and discussion linked from that documentation page

**Comment by quincylvania** [comment]
@matkoniecz Thanks for the links! I'm glad this was already discussed since it saves us time. I read through the mailing list discussion and it convinced me that we should definitely deprecate `FIXME` in iD. Most people agreed that `FIXME` is dated and wrong. Another developer even [mentioned](https://lists.openstreetmap.org/pipermail/talk/2018-July/080924.html) how `FIXME` caused them hours of extra work. The disagreements concerned the necessity and effectiveness of the edit. Responding to the primary arguments I saw against your bot edit:

- `FIXME` should purposely cause validator tools to flag it by being all capitalized.
    - A validator tool doesn't need special capitalization to flag something. In fact, having two tags makes it more likely that a validator will miss a fixme.
- Fixmes aren't important enough to create new entity versions over.
    - Users would manually be updating features in iD, so I think creating new versions is warranted.
- A single bot edit won't prevent future uses of `FIXME`. Editors should handle this.
    - This is the part we can address!
