### ISSUE TITLE
Allow for using number keys to escape the Repeat mode

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6481]
When using the new awesome repeat drawing mode, I found myself instinctively trying to escape the mode when done drawing sidewalks by pressing `2`, which is my shortcut for `Unmarked crossing`, the thing I wanted to map next.
What I think would make sense (and be very intuitive) would be to allow using number keys to escape the drawing mode in repeat and start drawing that new feature that the key corresponded to (still in repeat mode for speed).
This would help reduce unnecessary key presses and would make an intuitive way to change between the feature being drawn possible.

**Comment by BjornRasmussen** [comment]
This already works when the mapper is half way through an existing line.  What this issue is about ensuring that the listeners are active in that time between drawing lines.

**Comment by BjornRasmussen** [comment]
This might actually be working as it should now.  Testing today allowed me to switch between different modes with the number keys.

**Comment by quincylvania** [comment]
> This might actually be working as it should now. Testing today allowed me to switch between different modes with the number keys.

@BjornRasmussen This wasn't intentional but I'm glad it's working! I agree it's nice to switch the feature type immediately via hotkeys, especially since I often click the wrong button 😅. The new assistant helps a lot with this, since it tells you what you're drawing.

![Screen Shot 2019-06-04 at 3 16 50 PM](https://user-images.githubusercontent.com/2046746/58907300-d8840000-86db-11e9-94d9-40313714ab0c.png)
