### ISSUE TITLE
Adding a tactile paving as a closed line will make iD render it as an area.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6490]
If you add a tactile paving in iD, and choose `line` type, it will let you draw a line.  If you draw that line as a closed way, however, iD renders it as an area.

**Comment by quincylvania** [comment]
So to fix this I changed the `tactile_paving` preset from matching `tactile_paving=*` to `tactile_paving=yes` ([because `*` is ignored for the `areaKeys` blacklist](https://github.com/openstreetmap/iD/blob/09ea401d55846bdeb299514b7e49bfee98fd5daa/modules/presets/index.js#L145)). But that resulted in #6791, which led to us removing the preset altogether.
