### ISSUE TITLE
Mapillary sign detections shown selectively

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#6510]
Not sure if this is something due to a change on Mapillary's side, but the Signs overlay doesn't always show me the sign which is nonetheless highlighted as a detection in the image window (which remains broken as per [6286](https://github.com/openstreetmap/iD/issues/6286).)
Viewing the image preceding the one with the sign - you can see there is no detection, nothing blocked by the viewer cone
![image](https://user-images.githubusercontent.com/7071423/59153597-d8c22980-8a54-11e9-9d7b-23ab86d3d795.png)
And the image with the sign itself
![image](https://user-images.githubusercontent.com/7071423/59153600-0018f680-8a55-11e9-9f05-969ab4a2b2e7.png)

**Comment by cbeddow** [comment]
I believe this is due to a limit set in the OSM iD code, which allows only so much "tiling" of the traffic signs. When the Mapillary API is called, it tries to paginate through all data (1000 signs per request) but has something in the iD code with a limit of 5, which I am not sure if it's 5 iterations of tiling. This is my theory, but I am not sure exactly why this happens.

See here: https://github.com/mapillary/iD/blob/feature/mapillary-organization-filters/modules/services/mapillary.js#L397

@quincylvania do you know what this `limit` is?

This will be fixed in a future iD version by using vector tiles instead of the API.

**Comment by tohaklim** [comment]
Ah, I mistakenly thought iD transferred to vector tiles already, obviously that's not the case

**Comment by tohaklim** [comment]
Looks like this and #6721 can be merged, as both appear to be caused by the same pagination bug

**Comment by cbeddow** [comment]
Fixed with https://github.com/openstreetmap/iD/pull/6921, pull request pending, can close after testing. I found Chiang Mai in this intersection showed the difference well: https://www.openstreetmap.org/edit#map=19/18.78540/98.99043

before:
![image](https://user-images.githubusercontent.com/10554922/66310915-9c70de00-e90d-11e9-934f-d726a0062fd3.png)

after:
![image](https://user-images.githubusercontent.com/10554922/66310928-a266bf00-e90d-11e9-96d5-5e0595bb7329.png)
