### ISSUE TITLE
Avoid representing certain Christian denominations with a cross

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6512]
At least two Christian denominations, Jehovah’s Witnesses and La Luz del Mundo, consider it inappropriate to use the cross as a symbol for their places of worship. When `denomination` is set to either `jehovahs_witness` or `la_luz_del_mundo`, iD should use a generic icon instead of the ✝️ icon that it currently uses for all Christian churches and church buildings – for example, the same icon that is currently used by the Place of Worship preset. This could be accomplished by a separate preset for these two denominations or perhaps a special case targeting the existing presets’ style rules.

/ref gravitystorm/openstreetmap-carto#1079 gravitystorm/openstreetmap-carto#3800

**Comment by quincylvania** [comment]
I did this by adding presets for those denominations. I also added one for `quaker`, since similarly their places of worship shouldn't be called churches.

I'm open to adding presets for more denominations, but there are quite a few so they could get unwieldy quickly (see #5865). I think it's an okay standard to only add a denomination preset if "✝️ Christian Church" isn't correct.
