### ISSUE TITLE
Key:diaper has been deprecated

### ISSUE THREAD

**Issue by ValorNaram** [openstreetmap/iD#6529]
Hello,

the key described at https://wiki.openstreetmap.org/wiki/Key:diaper has been superseded by https://wiki.openstreetmap.org/wiki/Key:changing_table

I suggest you supporting both keys while the old one is still in use.

**Comment by quincylvania** [comment]
@ValorNaram The new tag looks promising. Interesting idea to support both the old and new tags at once, but iD hasn't really done that in the past and I'm not sure it could or should. I suggest we wait until the new tag gets more usage.

**Comment by carstenhag** [comment]
Hey @quincylvania, what do you mean with consensus/waiting for more usage?

The old one has been deprecated and the new one replaces it. I don't know why we should wait for the usage to increase, as integrating it into ID will do just that.

In my opinion, only `changing_table` should be added, and an automated "do you want to update this detail" message should show up, like it does on other keys.

**Comment by quincylvania** [comment]
@ValorNaram @carstenhag Thanks for your patience on this! We're pretty cautious about implementing tagging changes from the wiki because a few wiki users don't represent everyone who relies on these tags. In this case, it looks like usage of `changing_table` has increased a lot since June and tools like JSOM have adopted it, which puts us in a more comfortable position to adopt it in iD.

**Comment by ValorNaram** [comment]
@quincylvania Wiki pages which describe approved features have a link in the "See also" section to the proposal page. And the proposal (if its approved) itself is an official document.

If you want I can explain our technique on approved tags further and give some tips and hints about that.

**Comment by quincylvania** [comment]
> And the proposal (if its approved) itself is an official document.

@ValorNaram I wish that the tagging proposal process was actually "official". Many mappers have great ideas for better tags but the wiki on its own is bad at actualizing those ideas. There are plenty of "approved" proposals that failed to change practices because they're not enforceable—there's no imperative to upgrade existing data nor prevent new edits using old tagging. This results in fragmentation like `phone` and `contact:phone` existing side-by-side.

I do appreciate efforts to clean up tagging and with iD we'll help where we can, but understand why we have to deal with practical usage rather than paper proposals 🙂

**Comment by Discostu36** [comment]
Well, this is a bit of a hen and egg problem. As long as one of the most popular OSM editors is not updating its presets but instead uses deprecated tags, practical usage won't change.

**Comment by ValorNaram** [comment]
> This results in fragmentation like `phone` and `contact:phone` existing side-by-side.

I'm currently planning to take action. Will discuss it with the tagging community. I will post the link here for you to join the discussion when you feel comfortable to do so :)

@quincylvania It would be good to have you involved because you as iD developer have some experience with presets and how users use iD (especially new users). I hope for a dialogue where we all can together work on a system to instinct such fragmentations or at least fight them.

In fact: If we want to prevent fragmentation of tags, developer, mappers and analysts will and must work hand in hand. Developers because they must know for which tag they have to write a preset for. Mappers because they add data and use or create presets. Analysts because they know how annoying a long query is (fragmentation usually causes longer queries).

**Comment by ValorNaram** [comment]
I promised it and here's the link to my post: https://lists.openstreetmap.org/pipermail/tagging/2019-August/047668.html

On https://lists.openstreetmap.org/listinfo/tagging you can register yourself to be able to participate in the list _tagging_
