### ISSUE TITLE
Add preset for polling stations

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#6542]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpolling_station has a list of combinations for it. It would be good if there was a separate search term for "ballot box" also. 

Thanks

**Comment by quincylvania** [comment]
I'd love support these, but it is somewhat tricky since they are often temporary and in other buildings (at least in the US). Have you seen the [`polling_station=` proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/polling_station)? It actually has more usage at the moment.

I recommend a multi-part solution:
- Add `amenity=polling_station` as a "Permanent Polling Station" preset
    - e.g. dedicated ballot boxes, purpose-built facilities
- Add a "Polling Station" combo field for `polling_station=*` to some presets
    - e.g. schools, places of worship, community centers, public buildings
- Add `polling_station=*` as a "Temporary Polling Station" preset with a low match score
    - non-permanent stations not combined with other features

I think this would be relatively straightforward and in-line with the wiki. What do you think, @Adamant36 ?

**Comment by Adamant36** [comment]
I hadn't thought about temporary polling stations in places like schools. I was mainly concerned with mapping permanent boxes that are placed outside community centers etc. for polling. So, whatever you think works best for that 👍
