### ISSUE TITLE
When selecting a multipolygon, don't render its members with a yellow color

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6558]
A new awesome functionality was recently added by @quincylvania that renders the members of a selected relation yellow.  Unfortunately, multipolygon members are also rendered yellow, even though multipolygons behave as areas in all other ways.

**Comment by quincylvania** [comment]
> Unfortunately, multipolygon members are also rendered yellow, even though multipolygons behave as areas in all other ways.

@BjornRasmussen I actually kind of like this behavior since you can instantly tell if you selected a way or a multipolygon without scrolling the inspector. You can also tell whether you selected the multipolygon itself or one of its members. Further, it makes all relations behave consistently.

Still, there's an argument to be made that mappers shouldn't have to worry about the underlying differences between single-part and multi-part areas.

**Comment by sun-geo** [comment]
I love to new (yellow-display) feature in general. :-)

In some way an off topic question:
Could you please reduce a bit (if it make sense for all) the blinking frequency for the garish/dazzling yellow visualization? ;-)

**Comment by quincylvania** [comment]
> Could you please reduce a bit (if it make sense for all) the blinking frequency for the garish/dazzling yellow visualization? ;-)

Yes, I agree the yellow is a bit overpowering at the moment 💛⭐️🌕🌼🔆😅

**Comment by BjornRasmussen** [comment]
The yellow highlight is, in my opinion, not a great choice for multipolygons, since it sends the message that the area isn't selected, but rather that a parent relation of the area is selected, which is misleading.

**Comment by quincylvania** [comment]
> it sends the message that the area isn't selected, but rather that a parent relation of the area is selected

You're right, I guess this is probably how the average person would see this. Like I said, most people shouldn't have to know that single-part and multi-part areas are different types.
