### ISSUE TITLE
Handle tag to disallow automatic brand tagging

### ISSUE THREAD

**Issue by bikeoid** [openstreetmap/iD#6577]
I have seen several local restaurants with same or similar names to chains being incorrectly upgraded to the chain branding.   I would like to mark these so they don't get re-tagged with branding later.

  The tag not:brand:wikidata has been suggested for this.

**Comment by bhousel** [comment]
> The tag `not:brand:wikidata` has been suggested for this.

This sounds good to me, but can you link a discussion about it?  Just saying "it's been suggested" doesn't mean much.

**Comment by BjornRasmussen** [comment]
It's been discussed on the #poi channel of the osmus slack.

**Comment by bikeoid** [comment]
Also https://osmus.slack.com/archives/C029HV951/p1561427656403000

**Comment by jnicho02** [comment]
We've used the 'not:' prefix elsewhere for 'not:addr:postcode' to flag a common mistake, and i'm sure there must be others. It is probably a fairly acceptable thing to do.

**Comment by quincylvania** [comment]
@bikeoid @jnicho02 I agree 100% that introducing this tag would be acceptable based on historical precedent. However, a few members of the OSM community are dead-set against iD introducing any tag without consulting them, resulting in trivial tag introductions having an outsized negative impact on the health of the iD project (see #6332). As such, a new tag like this needs to receive lots of real-world usage and/or go through the "approval" process before we can support it 🙁

**Comment by 1ec5** [comment]
[`not:*`](https://taginfo.openstreetmap.org/search?q=not%3A) is already a well-used tagging scheme, just not `not:brand:wikidata` specifically yet. For example, #6411 is about [`not:name`](https://wiki.openstreetmap.org/wiki/Key:not:name). But no usage of `not:brand:wikidata` yet, so to kick things off, I tagged a couple independent restaurants that happen to match the name of chains in the same country:

https://www.openstreetmap.org/changeset/71606044
https://www.openstreetmap.org/changeset/71606149

If the validator warning about the missing brand tags could have an option to permanently ignore the warning (adding the `not:brand:wikidata` or `not:brand` tag), then we could potentially remove some disambiguating suffixes from name-suggestion-index that are there just to account for independent stores.

**Comment by 1ec5** [comment]
[Added some additional documentation to the wiki](https://wiki.openstreetmap.org/wiki/Key:not:), for what it’s worth.

**Comment by SK53** [comment]
not:name was originally AFAIK introduced for widespread usage as a way of avoiding false positives when using Ordnance Survey data road names around 2010. At the outset I think the OSM community established 1-2% of the british Ordnance Survey road names were not supported by on-the-ground evidence. Many of these differences were relatively trivial (presence or absence of apostrophes, words split of concatenated), but the utility of helping contributors avoid unnecessary work was invaluable.

In any case where some reputable external source is used to populate an OSM element or tags of an element, there is clearly some need to quickly signal to other contributors that the element as mapped is more accurate than the external source. A generic extension of not:key=* or even further not:key:<source> when there are multiple potential external linked sources has been in use, albeit it at a low level for a number of years in OSM.

Although @tec5's useful write-up describes "not:" as a life-cycle prefix, the usage is not really data about the object itself, but largely metadata about conflicts which may occur when OSM data is linked to external data sources. If we are to incorporate values which do allow linked data queries between OSM & other sources there will clearly be a need for some mechanism for flagging up that known discrepancies may exist. This is currently the mechanism, and it would need to be invented if it did not already exist. 

Therefore although the iD team may feel it politically expedient to suggest an approval process the downside is that the small community who discuss and vote on proposals may choose to reject a tag and approach which has nearly 10 years of active usage.

Note: I'm not sure if not:brand:wikipedia=McDonalds is a good thing, as it may be encouraging sloppy practices in assuming that McDonalds is always a hamburger joint. This is unlikely to apply in Scotland.

**Comment by quincylvania** [comment]
> Therefore although the iD team may feel it politically expedient to suggest an approval process the downside is that the small community who discuss and vote on proposals may choose to reject a tag and approach which has nearly 10 years of active usage.

Again, I'd personally love to just implement this tag in iD. However, I'm being extra cautious here because we came under _heavy_ criticism from that small community when we introduced `nonsquare=yes`, using exactly the same approach as longstanding tags like `noname=yes`. So much criticism that we had to reverse that feature. No one wants that to happen again.

I'm not saying this tag needs to undergo an entire approval process necessarily, but some level of community buy-in would keep people from feeling that iD went behind their back by adding this.

**Comment by batyrmastyr** [comment]
Regarding _nonsquare_ had one huge drawback - it's a hint invented to fight against false-positives in iD, still it was stored in _common_ database. Editor config is the data that should be stored externally.

> an approval process the downside is that the small community
Not consulting with community may lead to garbaging database (useless changing "zebra" to "marked" instead of community approved "uncontrolled" with or without traffic_signals support), massive routing breakage (making everything a highway) to name a few.

Back to the topic - _not:source:identifier_ is fine (IMHO) as it gives some useful information for everyone.

**Comment by quincylvania** [comment]
@batyrmastyr Not to get too off topic, but `nonsquare` is not iD-specific, it specifies on-the-ground conditions and any other tool that examines squareness could use it. iD did not "garbage" the database, did not make everything a highway, and did not cause massive routing breakage.

**Comment by batyrmastyr** [comment]
@quincylvania sorry, I haven't seen other editors proposing to square corners. Seems like I've missed some.
I've added links to the issues I mentioned earlier. The latter is fixed, but the former is't ("thanks" to bhousel's strong NIH-syndrome).

**Comment by 1ec5** [comment]
Let’s keep this discussion on-topic please. I suspect folks here are already aware of the crossing and squaring controversies, and people’s opinions on those matters are unlikely to be changed as a result of the discussion here.

So, about the brand suggestion feature: would it be enough to tag a feature with `not:brand:wikidata`, or would a feature need to be tagged with `not:brand` and `not:brand:wikipedia` too? Presumably the “ignore” button could conveniently add whatever tags are needed to turn off the suggestion, but given that `brand`, `brand:wikipedia`, and `brand:wikidata` are all redundant or complementary to each other, maybe the suggestion could be turned off when any of these tags is negated.

It may be helpful to tackle #6411 first, to understand if there are any problems with supporting the `not:` namespace overall. `not:name` has a longer history, as @SK53 explained in https://github.com/openstreetmap/iD/issues/6577#issuecomment-507060511. Making use of `not:name` could set a precedent for iD supporting other `not:`-namespaced tags in use and potentially other lifecycle tags as well. After all, the point of a namespace is extensibility.

**Comment by 1ec5** [comment]
> Note: I'm not sure if not:brand:wikipedia=McDonalds is a good thing, as it may be encouraging sloppy practices in assuming that McDonalds is always a hamburger joint. This is unlikely to apply in Scotland.

Even if were unsound for a validator to assume brand affiliation based on naming alone, `not:` tags still have value as hints to mappers and data consumers who would be inclined to think otherwise.

Imagine using Overpass turbo to fetch the locations of Burger King locations around the world. But maybe you’re unaware of [the one unaffiliated Burger King in Illinois](https://www.openstreetmap.org/way/165659335), which [predates the international chain](https://en.wikipedia.org/wiki/Burger_King_%28Mattoon,_Illinois%29) and has the right to open additional locations under that name within a 20-mile radius. Without that context, you might be inclined to search for `amenity=fast_food and name="Burger King" global` rather than `"brand:wikipedia"="en:Burger King"` or `"brand:wikidata"=Q177054`, because occasionally someone adds a Burger King without brand tags. It would be nice to be able to add something like `and "not:brand:wikidata"!=Q177054` whenever querying for chain store locations. That way you could at least exclude the locations that mappers have explicitly asked you to exclude.

**Comment by SilentSpike** [comment]
I imagine `not:brand:wikidata` would be the only appropriate and necessary tag since it's the only stable (in theory) identifier.

**Comment by jeisenbe** [comment]
I asked about this on the tagging mailing list, and so far it looks like there are 4 people in favor and only one who was concerned about using the "not:" prefix with "not:brand" or "not:brand:wikidata".

See the discussion at https://lists.openstreetmap.org/pipermail/tagging/2019-September/048189.html

**Comment by quincylvania** [comment]
Seems like there's no major opposition to using this tag and it indeed lines up with accepted usage of the `not:` prefix. Thanks for your patience.

I made it so the validator won't recommend upgrading to brands matching a feature's `not:brand:wikidata` value. We could also consider adding a quick fix for assigning this.
