### ISSUE TITLE
iD is forcing retaging from landuse=reservoir to natural=water+water=reservoir

### ISSUE THREAD

**Issue by tomass** [openstreetmap/iD#6589]
iD is forcing users to retag reservoirs from _landuse=reservoir_ to _natural=water+water=reservoir_.
_landuse=reservoir_ is older and more widely used way to tag reservoirs. _water=reservoir_ is newer and has no advantage over original OpenStreetMap way of tagging reservoirs.

Same thing with _landuse=basin_ and _natural=water+water=basin_.

**Comment by BjornRasmussen** [comment]
See #5591, where a discussion took place on this topic.  The conclusion was that having a ton of different tags for water features makes it harder to use osm data, and that putting them all under `natural=water` + `water=*` is more practical for a wide variety of reasons.

**Comment by tomass** [comment]
Well, why is iD deciding which tags are "better"? Shouldn't OpenStreetMap **community** decide (by tagging, by numbers)?

Me and many other mappers were not participating in #5591 as I do not use iD. I'm here just because now I have more work fixing such mistaggings made by iD. Removing such "advices" from iD would be much more friendly way of solving this than other options.

**Comment by BjornRasmussen** [comment]
What about the older tagging system for `landuse=pond`, `landuse=reservoir`, `landuse=basin`, and `waterway=riverbank` do you think is better than the newer system?  Many people had already switched to the before iD did.  iD was just following a growing trend.  
taghistory.raifer.tech does a nice job of showing this trend.

**Comment by tomass** [comment]
Yes, original scheme with _landuse=basin_, _landuse=reservoir_, _waterway=riverbank_ is good - it allows us tagging everything we want. New scheme has no advantages just one major disadvantage - introduction of duplicate tagging and therefore corresponding havoc for both editors and consumers.

There can be millions of arguments about semantics of keys and values and it will never lead to a consensus (this can be seen from numerous attempts to "solve" forest tagging, which has only led to introduction of even more new tags), so going into that I think is pointless.

New water scheme is **still less popular** (according to tagwatch). Even with iD forcing users to use one way of tagging from the very beginning, while JOSM (most data is created with JOSM) allows both schemes.

**Comment by BjornRasmussen** [comment]
> New scheme has no advantages

Here are the advantages _I_ see:
• Easier for new mappers to learn
• More consistent 
• You don't need to know what kind of water something is to add it: just use `natural=water` 
• Easier to use the data (Overpass queries, taginfo stats, etc) 

I agree with you about the disadvantage, but that's one of the things iD is trying to solve.  iD didn't create this be tagging scheme, nor did it create the "havoc."  It can, however, fix the "havoc" by gradually phasing out the old scheme.

I think that one other very minor disadvantage with the new scheme is that two tags are needed, instead of one, but that shouldn't be too much of an issue.

**Comment by 1ec5** [comment]
`landuse=reservoir` is also used for reservoirs that don’t hold water. A tailings pond or ash pond tagged with `landuse=reservoir` `reservoir_type=tailings` may technically contain some water (as would a `natural=tree` or `highway=track` `surface=mud`), but it’s anything but natural. I’ve ignored quite a few warnings about tailing ponds in iD. It would be nice if iD could exempt features with `reservoir_type` tags, at least until there’s a suitable replacement.

**Comment by Adamant36** [comment]
I tag a lot of water bodies and I'm mixed on this. To me the landuse tag is good for tagging the actual land that contains the water, but there should still natural=water tag for the actual body of water. Otherwise, it just seems like your splitting the streams up that go into and out of the water in a weird way and there's no way to add intermittent to it. I do think the landuse tag is useful for showing the landuse of the area though. So, I don't know 🤷‍♂

**Comment by tomass** [comment]
I do not see how it is "easier" to learn? It is possible to tag everything as _natural=water_ WITHOUT adding _water=***_ (using original OpenStreetMap water scheme). Then people who map more, who know more would come and change it to whatever is better (maybe even having some equivalent to highway=road would be good but it is a different topic). And this is how it has worked from the very beginning and still works today, even with iD ;-)

It is more consistent with iD, not with OpenStreetMap. That is a big difference.

No it is not easier to use data when creating maps. _landuse=basin_ has a very different usage and even different topology rules comparing to natural=water. Even _landuse=reservoir_ has different usage. Same with _waterway=riverbank_. Well unless you're just skimming on cartography and do not care about scale, legibility etc.

Regarding "fixing the havoc". By pushing the new scheme iD is actually helping to create a precedent to introduce other duplicate tagging schemes in the future, because this would show that **it works**.

**Comment by matkoniecz** [comment]
It is hard to describe using `landuse=reservoir` for reservoir water areas as a good tagging scheme.

In this specific case, in my opinion `natural=water water=*` scheme is strongly preferable.

Though it is apparently necessary to exclude `reservoir_type=tailings`.

**Comment by tomass** [comment]
> It is hard to describe using `landuse=reservoir` for reservoir water areas as a good tagging scheme.
> In this specific case, in my opinion `natural=water water=*` scheme is strongly preferable.

  However most people who map have a different opinion even with iD taking sides from the very beginning of its existence and not allowing original OpenStreetMap water tagging schema. (JOSM allows both schemas).

  Note that if iD would not be taking sides then fair solution would be for iD to allow using **both** schemes: original OpenStreetMap and the new one. I'm not asking for that. I'm asking for a minimum - stop pushing people to change tagging to the tagging preferred by iD, not by OpenStreetMap community.

  Old water tagging scheme is already used in a lot of places: maps/cartography rules, data analysis, QA etc. New scheme should have some very serious benefits to justify such a drastic change for such a widely-used tag (which would be almost equal to change of "highway" to something more semantically correct one).

**Comment by matkoniecz** [comment]
> stop pushing people to change tagging to the tagging preferred by iD, not by OpenStreetMap community

Is there some evidence that it is actually iD vs OSM community (like with some validator decisions that were rolled back)? I see no evidence at https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dreservoir or https://wiki.openstreetmap.org/wiki/Tag:water%3Dreservoir and usage count difference is not very large, around 200k vs 410k areas (landuse=reservoir has way more nodes, but I would consider rather as evidence against this tagging scheme).

Note that it may be useful to compare actual usage, who and when added them rather than raw usage count.

> JOSM allows both schemas (...) iD to allow using both schemes

That is because JOSM primary editing method is to input raw tag and in ID is to use presets.

https://taghistory.raifer.tech/ is also indicating that large lead of landuse=reservoir is result primarily of bot edit, likely an import.

Also, since 2016 landuse=reservoir popularity among mappers suddenly decreased.

![Selection_012](https://user-images.githubusercontent.com/899988/60383077-c001ce00-9a6c-11e9-9aa8-ed43c7851a36.png)

Overall, I see no evidence of iD vs others, it looks like decision that could be reasonably taken in both directions. I am planning to request exactly the same deprecation rule in JOSM, if it is not present already.

**Comment by SilentSpike** [comment]
This is an endless problem. No tagging is 100% approved by the "OpenStreetMap community" because there is no centralised community and everyone disagrees with one another.

The issue title is also exaggerated because nobody is being forced to do anything. Raw tag editor is available and other tools are available if people are not happy with what iD provides.

It's true that old tag is widely used, it's currently got double the usage according to taginfo. However, relying on usage magnitude to drive tagging development is inherently biased toward whichever scheme came first (unless a special effort has been made to deprecate the tagging in which case it's biased toward the newer scheme).

Worth mentioning I personally couldn't care which tagging is used at the end of the day. However, this is an infinitely repeating problem for the "OSM community" which carto and tool developers will have to deal with until community driven solutions are developed (if ever).

I think it's fair (in the case that multiple schemes are in use and documented) for iD to have preferred tagging, the old tagging is still allowed and possible to use and they both mean the same thing anyway.

**Comment by tomass** [comment]
By trying to "depreciate" such a prominent tag without giving a benefit iD would be destroying **stability**. For iD it is a minor change, but it would require a lot of work for data consumers: data analysis, data extracts, transformations, topology rules, cartography, documentation, training etc.

There must be a very good reason to single handedly create so much work for so many people.

**Comment by matkoniecz** [comment]
@tomass For your information, iD is not inventing a new tag. This tag is already widely used! All data consumers that want to use this specific detail already need to support both of them!

**Comment by tomass** [comment]
@matkoniecz iD is pushing a **duplicate** tag which introduces havoc, adds a lot of hard work for everybody and gives **no** benefit.

Data consumers have successfully been using original OpenStreetMap water tagging scheme with _waterway=riverbank_,_landuse=reservoir_ etc. from the very beginning of OpenStreetMap project!

By doing so iD also diminishes trust in stability of OpenStreetMap tagging scheme: it is a very bad practice to change such prominent tags after so many years of usage without a benefit.

**Comment by tastrax** [comment]
Tomas,

 

It appears you disliked the original ‘water’ proposal and continue to seek some rolling back of these tags, despite many being in popular use for many years.

 

Things will continue to change, forever, as we all get better at identifying issues that require solving or modification. As I said in a previous post…. It’s the tagging scheme that needs a serious workover to ensure there are policies in place for creation, modification, acceptance and deprecation.

 

That will be of benefit to the entire OSM community….. if they could ever agree on it.

 

Cheers - Phil

**Comment by quincylvania** [comment]
This thread got long and heated so I'm just going to respond briefly to the primary points.

- iD does not force tag upgrades. It does strongly suggest them, but they are always optional.
- iD only supports one way to tag things even if OSM allows multiple conflicting schemes. This reduces confusion for casual mappers.
- `water=reservoir` has over 200,000 uses. It is not a fringe tag.
- Using `natural=water` + `water=reservoir` creates less work for data consumers, not more, since then all water features will consistently have a `natural=water` tag.

In sum, since there are multiple ways to tag reservoirs and iD can only support one, we use the scheme we think has the most benefits. You may disagree, but that's the nature of OSM.

As @tastrax said:

> It’s the tagging scheme that needs a serious workover to ensure there are policies in place for creation, modification, acceptance and deprecation.

I agree. We need better systems for managing the tagging scheme so iD isn't making these kind of decisions.

**Comment by tomass** [comment]
iD is authoritarian because as hilarious as it is, being a POI editor iD coders decided they can be judges and decided to use russian water schema instead of much more popular standard OSM water schema.
Main OpenStreetMap editor - JOSM however did manage to leave freedom to mappers to decide which tagging schema to use.
But no, Mapbox didn't bother assigning anybody with IT experience to this task, instead pure coders were assigned and so we have this terrible semi-automatic data mutilator - iD.

**Comment by bhousel** [comment]
@tomass Please knock it off.  I'm going to just delete your comments if you continue the disrespect.
