### ISSUE TITLE
Rename "Torii" to "Shinto shrine gate"

### ISSUE THREAD

**Issue by picsi** [openstreetmap/iD#6600]
Probably more descriptive to those who don't know 'torii'.

**Comment by quincylvania** [comment]
@picsi Aw I like "Torii" because that's actually what those things are called in English. Searching for "shinto shrine" will bring up this result along with a helpful icon.

However, when the user clicks the info button there's no documentation right now. Someone should add a description and image to the [wikibase item](https://wiki.openstreetmap.org/wiki/Item:Q16749) so users can learn what a Torii is.

Adding preset subtitles would also be helpful here (see #6131).

**Comment by quincylvania** [comment]
Let's just leave this as-is unless more people find this confusing.
