### ISSUE TITLE
Pasting in key=value tag into tags panel should parse out = sign

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/iD#6604]
It would be nice if, upon pasting into the tag panel a `key=value` string, e.g. as copied from the wiki, this is automatically parsed into the key and value parts.

Current result of pasting in a `key=value` string:

![Screen Shot 2019-07-01 at 20 07 44](https://user-images.githubusercontent.com/361423/60460561-fe011c80-9c3b-11e9-87a2-01e0c10b948f.png)

Proposed result upon pasting:

![Screen Shot 2019-07-01 at 20 07 53](https://user-images.githubusercontent.com/361423/60460559-fe011c80-9c3b-11e9-906e-4ed9c9027c31.png)

**Comment by bhousel** [comment]
Does pasting k=v pairs work when you toggle the tag editor to text mode?
see #6302 for details..

**Comment by mvl22** [comment]
> Does pasting k=v pairs work when you toggle the tag editor to text mode?

Yes, that does. (That feature is a great improvement by the way - makes copying common tag sets in an area with a dense path network much easier!).

I still do think this would be a useful optimisation though - often one just wants to add one tag gleaned from the wiki without disrupting others and that's far more likely when using a multiline text box.

> (also #6520)

Ah, I see this has actually been deliberately removed. Was there a particular reason to do so? It seems a nice feature to have.

**Comment by bhousel** [comment]
> Ah, I see this has actually been deliberately removed. Was there a particular reason to do so? It seems a nice feature to have.

Mostly because you can paste the k=v into text mode, and the code for supporting k=v pasting in grid mode had some bugs and it didn't make sense to support it there.

> surely the problem there was that the value was being merged into an existing key, rather than the _1 (etc.) suffix being added - as normally happens if you type in a key?

No, it was not that - the old code just didn't check whether the user was trying to paste a readonly key.  (so for example in the changeset tags, you could paste in `created_by=JOSM` to override that changeset tag).  Also iD doesn't add _n suffixes anymore since last year.
