### ISSUE TITLE
Support leisure=pitch on ways

### ISSUE THREAD

**Issue by jomo** [openstreetmap/iD#6629]
For example, soccer fields without a clear outline can be mapped as ways (a single line from one goal to the other), [according to the wiki](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpitch#How_to_map).

iD doesn't currently support this and warns that "Leisure should be a closed area".

![soccer pitch](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Boisko_w_Trzmielewie_03_ubt.JPG/640px-Boisko_w_Trzmielewie_03_ubt.JPG)

**Comment by Adamant36** [comment]
> For example, single basketball hoops or soccer fields without a clear outline can be mapped as nodes or ways, according to the wiki.

Maybe it can be mapped as nodes according to the wiki, but the wiki also does say a pitch is "an **area** designed for practicing a particular sport." I'd be interested to know where the line is between mapping a pitch as a node versus just tagging a single basketball hoop as a point with sport=basketball or something. Especially in your example where there is no clear basketball playing area. There doesn't seem to be a tag that I could find for mapping single sports related objects like that. At least not for basketball.

**Comment by jomo** [comment]
The wiki pages for both `leisure` and `leisure=pitch` state that these tags are used on **nodes**, **ways**, and **areas** (but not relations). The photo of the basketball hoop above is taken from the examples section, where it is mapped as a node with `leisure=pitch` + `sport=basketball`

**Comment by Adamant36** [comment]
Yeah, I mean, we already established that. Just repeating what we already know doesn't really answer my question. I thought you might have your own opinion about it outside of what the wiki says.

**Comment by jomo** [comment]
I's not about mapping the soccer goals and basketball hoops in particular, but more about mapping the actual pitch which doesn't have a clear boundary, so it can't be tagged as an area. I do like the way the wiki suggest doing this.

Perhaps iD could show a note that an area should be used, if possible.

**Comment by Adamant36** [comment]
> Perhaps iD could show a note that an area should be used, if possible.

That's my only issue. I'm inclined to think that given the option, people will default to mapping all pitches as nodes just because it takes less time and not confine it specifically to ones with unclear boundaries. If there's a warning or note though, that would help.

**Comment by Adamant36** [comment]
Btw, I just placed a node in iD Editor and put "pitch" in the search and it worked. So, this might not be a problem for nodes after all. Looks like it just doesn't work for ways. I didn't any warning about it either. You might want to double check it and update the title of the issue.

**Comment by quincylvania** [comment]
@jomo Sorry, but iD can't really support any kind of landuse features as lines.

Since OpenStreetMap doesn't have different data types for lines and areas, the tags themselves imply whether a way should be an area. Right now `leisure=pitch` implies area. If we allow that tag on lines, then _all_ pitches would be treated as lines until someone added `area=yes`.

Also, I think the existing tagging system for pitches suits all cases. If the direction of play is ambiguous, you can use a point. If the direction is evident, it's okay to estimate the play bounds even if they're not marked.

![Screen Shot 2019-07-08 at 9 26 25 AM](https://user-images.githubusercontent.com/2046746/60814323-69c71600-a163-11e9-829c-c77cb0cb50bd.png)
