### ISSUE TITLE
Add preset for adding buildings as nodes

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#6630]

**Comment by quincylvania** [comment]
@Adamant36 It was an intentional decision to exclude buildings-as-points from the preset browser in order to encourage mapping full footprints. [Less than 1%](https://taginfo.openstreetmap.org/keys/?key=building) of current buildings are nodes. Is there a situation where you need this functionality?

**Comment by Adamant36** [comment]
I guess that makes sense. Where it came up was adding houses that have just been built from ground surveying, but where they are not in the satellite images yet so there's no way to map their areas. they don't have addresses yet either. I don't want a building preset to lead to bad mapping habits though. Plus, it's not like I can't manually add the building tag to a node if I have to. So, whatever you think is best.

**Comment by quincylvania** [comment]
@Adamant36 Cool, let's just leave this for now then. Perhaps eventually we could add a way to browse all presets and indicate which are discouraged.
