### ISSUE TITLE
Modify changeset warning tag fixme

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6658]
I'm fine with showing the "warnings:fixme_tag" while editing in the validator, but I don't like to see especially this one (warnings:fixme_tag=x) for changeset tags. Other are maybe also OK for changeset tags.

noticed while using iD-v2.15.3

**Comment by quincylvania** [comment]
@sun-geo When we do #6459 then the warning tags will represent issues actually created by the mapper, rather than all issues for edited features. This means that `warnings:fixme_tag` should never show up since a warning isn't generated when you yourself add a `fixme` tag.

I'll leave this open but it'll resolve itself after #6459.
