### ISSUE TITLE
presets=https://path/to/presets.json broken

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6664]
It looks to me, that the feature `presets=https://path/to/presets.json` [by](https://github.com/openstreetmap/iD/commits/master?after=b0ed68909149f1879fcebfa338e60258a1ebf489+34&author=maxgrossman) @maxgrossman is broken.

This, or I just don't understand how to use it :-).

What I found out so far:

- In the current master, the `.fromExternal` method gets a `external` variable that IMO is not existent. There  is also a 404-error that points to this, once I try to load an external preset. This commit fixes the 404, but that is not enough https://github.com/tordans/iD/commit/6a0b0d0b18053f03f76cac2b703bb2120784a255
  - Note, in https://github.com/openstreetmap/iD/commit/1b51b8bc573b7afdfddeaf07cb27114a81db5841#diff-8bba9fcee119fbe9ddc618129a7b9cc9R505 the "external" variable was still present

- The "d3_json -> then -> catch -> finally"-chain at https://github.com/openstreetmap/iD/blob/eb0647a4b7023bd9b185d305b05f34d354ea8faf/modules/presets/index.js#L286-L295 seems to be broken. The "then" part is not executed in my tests; its always the catch- + finally-part.
  - Note, initially this used a different try-catch-pattern https://github.com/openstreetmap/iD/blob/d87b1822f7ae92fc8445ca9877f027bfd660ab3a/modules/presets/index.js#L218-L225

I also wonder about the correct format, of an "external_presets.json". In my tests I tried using https://github.com/tordans/iD/blob/master/bicycle_parking_custom_preset.json.
- Is this the right format?
- What would be a good place to document an example file/file-content?

**Comment by maxgrossman** [comment]
@tordans - thanks for the diligence of testing out the feature I wrote :smile:

The format of the preset JSON is intended to match the large hashmap that iD reads, seen [here](https://github.com/openstreetmap/iD/blob/master/data/index.js#L53-L57).
This format of hashmap is what iD ingests in the `non-from-external` scenario. When I added this feature, the intent was to just match that.

That said, looking at the #6553 feature since it seems like the preset above is in the iD source tree, using the comma-delimited list of preset names looks like it should work.

As for your second bullet point question, this feature comes in tandem with working my work on [maprules](https://github.com/radiant-maxar/maprules). So I do not have a document on how to build this json, but am happy to help you get that tool set up w/iD so you can test out what you intended to.

**Comment by bhousel** [comment]
I've change the code flow in `presets/index.js` a bit as a result of working on #4994.  Now _all_ the presets are essentially external, so we are always deferring the build step.  I've renamed `build` to `merge` and I've made this function the sort of thing that we can run several times if we want to.
