### ISSUE TITLE
Add source:population and population:date presets for places

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#6672]
I noticed that when adding places there is a preset field for adding the population. It would be cool if there was also one for the source of the population data. Along with a preset field for the date it was obtained.

**Comment by quincylvania** [comment]
It'd be cool to be able to group fields together for stuff like this. This wouldn't look great:

**Population**
**Population Source**
**Population Date**

Whereas this is workable:

**Population**
- Source
- Date

**Comment by jeisenbe** [comment]
Isn't it better to include this information in the changeset instead of directly on the `place=` node? 

https://wiki.openstreetmap.org/wiki/Key:source 

"With modern editors, the source=* tag is typically added to the changeset when a change is made, not as a tag on a piece of information which may be updated at different times based on different sources."

**Comment by 1ec5** [comment]
For reference, the fields mentioned above would be hooked up to the well-established `population`, `population:date`, and `source:population` tags.

/ref #6678

**Comment by quincylvania** [comment]
> Isn't it better to include this information in the changeset instead of directly on the place= node?

@jeisenbe Yes, that is the case generally speaking for sources.

But `population` is special since it's something people should add that can't be verified on-the-ground. It could also have different values from different agencies, so it's helpful to explicitly specify where the number came from. The `population:source` tag does this without making a consumer delve through changesets.

**Comment by jeisenbe** [comment]
The risk is that a ‘source:population’ tag might not be updated when the
‘population=‘ is edited in the future.

But maybe iD can validate this, so if a user changes ‘population’ then the
date and source tags have to either be deleted or updated?

**Comment by quincylvania** [comment]
> The risk is that a ‘source:population’ tag might not be updated when the
‘population=‘ is edited in the future.

Yes, which is why having a field for this would be helpful by making the tag more visible.

> But maybe iD can validate this, so if a user changes ‘population’ then the
date and source tags have to either be deleted or updated?

The issue here is that the source could be the same year after year (US Census Bureau, etc.).

**Comment by 1ec5** [comment]
>> But maybe iD can validate this, so if a user changes ‘population’ then the date and source tags have to either be deleted or updated?
> 
> The issue here is that the source could be the same year after year (US Census Bureau, etc.).

The validator could require that a change in population be paired with a change in either the date or the source, to account for recurring sources. I have come across cases where the previous value was simply wrong (such as copy-pasta of a different city’s population), but a false positive validator warning isn’t the end of the world.
