### ISSUE TITLE
Suggest tag upgrade for power=cable_distribution_cabinet

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#6686]
It would be helpful if there was an outdated tag warning etc for power=cable_distribution_cabinet. The wiki suggests the tag be replaced with  man_made=street_cabinet + street_cabinet=power. 
There's currently 9,261 instances of it. Including a bunch around where I live that an upgrade warning would help a lot with re-tagging.

**Comment by bhousel** [comment]
Can you link to the wiki where they suggest this?

In my opinion, this one sounds dubious.  Power stuff previously always had a `power=*` tag.  

Also, laypersons usually wouldn't know what's inside a street cabinet.  Many of these street cabinets with power stuff in them are probably just pad mounted transformers and switches, which would better be tagged as those things.

**Comment by Adamant36** [comment]
> Can you link to the wiki where they suggest this?

Its on the power=cable_distribution_cabinet page [here](https://wiki.openstreetmap.org/wiki/Tag:power%3Dcable_distribution_cabinet). There's a quick mention of it on the talk page also. 

> Power stuff previously always had a power=* tag.

Yeah, usually that's the case. I think it's different in this instance though because tagging it as street_cabinet=power instead of power=* allows for more details. in the power=substation article it suggests adding it to street_cabinet=power. Although, the suggestion to do so isn't also made in the man_made=street_cabinet article. So, I don't know. Street cabinets used for power are considered substations in my mind. So adding power=substation to them makes sense to me. 

> Also, laypersons usually wouldn't know what's inside a street cabinet.

I agree with you when it comes to most street cabinets. Electrical ones are pretty obvious though due to their size, shape, color, etc. Plus they usually have a thing on them with the volts and what electric company maintains them. Along with a shock warning. Although that might just be the ones where I live.

**Comment by bhousel** [comment]
Let's not do this

**Comment by flacombe** [comment]
Well, I confirm power=cable_distribution_cabinet was replaced by man_made=street_cabinet for the cabinet part.
It doesn't prevent to combine it with power=transformer or power=switch when appropriate.

cable_distribution_cabinet doesn't mean anything and should be discouraged in favor of man_made=street_cabinet + street_cabinet=power
I think we'll agree on this since it precisely prevents to use more appropriate values like transformer or switch.

utility=power should be considered as well to state it's power stuff.

**Comment by bhousel** [comment]
> Well, I confirm `power=cable_distribution_cabinet` was replaced by `man_made=street_cabinet` for the cabinet part.

What I'm saying is - up until recently, all power features have had a `power=*` tag and this was very helpful.  Actually I think it might be the only class of tags in OSM that was properly namespaced under a single tag key.  Check it out, this is our code for detecting power features:
https://github.com/openstreetmap/iD/blob/857903129896aa92bbe8c101dc57a8d8b4656f28/modules/renderer/features.js#L198-L200

Switching to `man_made=street_cabinet` messes this up and it introduces an ambiguity between many different kinds of things that can be in street cabinets. If we want to hide or show power features, we need to include extra tags into how our software classifies power features.  From my point of view, it's like you just took the one good key in OSM and broke it for no good reason.  Would you consider switching it back?

> `cable_distribution_cabinet` doesn't mean anything and should be discouraged in favor of `man_made=street_cabinet` + `street_cabinet=power`
I think we'll agree on this since it precisely prevents to use more appropriate values like transformer or switch.

"doesn't mean anything"?  There are over 8000 of them!

> utility=power should be considered as well to state it's power stuff.

No, `power=*` states that it is power stuff and always has.  Again, _please_ preserve this convention.

**Comment by bhousel** [comment]
I'm reading https://wiki.openstreetmap.org/wiki/Proposed_features/Street_cabinet surprised that people voted for this.  

(This reminds me a lot of that other conversation about measuring trees by their circumference instead of their diameter.)

Like, there are a few things in the world that I know a lot about, and I feel like in each case OSM has voted to adopt tags that work against the way that people in those industries think about those features.

A pad mounted transformer or switchgear is not a "street cabinet" in the same way that a telecom service area interface or distribution frame is.  They are very different things that happen to be located in street cabinets.  The cabinet is not even the important thing.

**Comment by flacombe** [comment]
> > Well, I confirm `power=cable_distribution_cabinet` was replaced by `man_made=street_cabinet` for the cabinet part.
> 
> What I'm saying is - up until recently, all power features have had a `power=*` tag and this was very helpful. Actually I think it might be the only class of tags in OSM that was properly namespaced under a single tag key.

That will be preserved:
One motivation of man_made=street_cabinet is to free power=* key for features that are directly involved in power infrastructure. The cabinet doesn't transform, transmit or cut power while the switch inside does.

> Switching to `man_made=street_cabinet` messes this up and it introduces an ambiguity between many different kinds of things that can be in street cabinets. If we want to hide or show power features, we need to include extra tags into how our software classifies power features.

Wrong assumption: introducing man_made=street_cabinet didn't encourage to remove power=* from features. The point is only to use it with more meaningful values and generalize concept of cabinet for mappers who are not interested in industrial or power stuff (also important to improve contribution)

> > `cable_distribution_cabinet` doesn't mean anything and should be discouraged in favor of `man_made=street_cabinet` + `street_cabinet=power`
> > I think we'll agree on this since it precisely prevents to use more appropriate values like transformer or switch.
> 
> "doesn't mean anything"? There are over 8000 of them!

This value has two main problems:
* People were using _cable_distribution_cabinet_ for pretty anything: small substations, domestic connection boxes, traffic lights controllers. Data was useless in such circumstances and many more documented terminology was required to encourage people to give more details.
* Having _cable_distribution_cabinet_ in power may encourage to define _cable_transmission_cabinet, cable_switching_cabinet, power_transforming_cabinet, power_holy_grail_cabinet_. It's bad because it's more sentences than words. And when there are several words, several tags are often necessary to get better semantics.
"A power switch inside a cabinet" got a better translation with man_made=street_cabinet + street_cabinet=power (or utility=power) + power=switch than power=my_beautiful_cabinet_with_switch_inside (exaggerated on purpose)

> > utility=power should be considered as well to state it's power stuff.
> 
> No, `power=*` states that it is power stuff and always has. Again, _please_ preserve this convention.

utility=* was introduced for markers. (marker=*).
It's not properly power stuff (sorry my last message lacks of precision), all power devices/facilities will remain in power, no problem with that.
Markers aren't involved in what they are supposed to warn about. It's not a pipeline accessory, a power line/cable accessory or a telecom device. They're not fulfilling any service (instead of a transformer, switch, valve...).

I completely agree it's convenient to have all power devices/networks under the same key and it's also important to preserve consistency.

> Like, there are a few things in the world that I know a lot about, and I feel like in each case OSM has voted to adopt tags that work against the way that people in those industries think about those features.

Mainly because all of those industries work in silos without looking how things run elsewhere (rude but try to change my mind). 
OSM is an opportunity to produce semantics that bring comparability, versatility and generic concepts.
I currently work for a software development company that provide optimization software to utilities network operators. Be sure everyone has its own data model, no one can take benefit of any progress without huge and costly efforts. Is that desirable ? I don't think so.

> A pad mounted transformer or switchgear is not a "street cabinet" in the same way that a telecom service area interface or distribution frame is. They are very different things that happen to be located in street cabinets. The cabinet is not even the important thing.

I agree that street_cabinet could have been _cabinet_ only as to save us street focus.
Depends on who is interested in the data.
Cabinets become the important thing when a disabled person in wheelchair have to go down from pavements each time cabinets are too big to pass beside.
