### ISSUE TITLE
Incomplete translation for preview

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#6693]
I just opened the preview and there are parts in german but also parts  in english:
![3E9D1429-A4D3-4A1E-AD3F-7C5CED287F91](https://user-images.githubusercontent.com/5360273/62008047-1558fa00-b155-11e9-96ba-20c3b817b7af.jpeg)

On Transifex eveything is translated to German:
![97E35465-EDD4-48FF-AE58-DE6C4485199D](https://user-images.githubusercontent.com/5360273/62008055-286bca00-b155-11e9-8cbb-abc992e39723.jpeg)

**Comment by quincylvania** [comment]
@manfredbrandl Yep, thanks for noticing! Transifex is tracking the [2.15](https://github.com/openstreetmap/iD/tree/2.15) branch for awhile since the master branch is undergoing significant breaking changes for v3. We don't need translators to worry about lots of strings for experimental features that might be changed or discarded. Unfortunately this means that preview isn't translatable. We'll switch it back over a month or so before the v3 release so translators have enough time to work on the new strings.
