### ISSUE TITLE
Supprimer des éléments obsolètes et grossir les icônes

### ISSUE THREAD

**Issue by Saint-Ferdinand** [openstreetmap/iD#6726]
Bonjour,

Je suis en train de modifier les éléments pour le village de Saint-Ferdinand (QC), Canada. Des éléments obsolètes tels que l'ancien emplacement du bureau municipal qui est désormais une caserne de pompier ainsi que le Shell ne devraient plus apparaître sur la map. De plus, serait-ce possible de faire en sorte que les icônes des restaurants, hébergements, bibliothèque, etc. soient plus gros? Il faut énormément zoomer sur la map afin de les apercevoir. J'aimerais qu'il soit possible de les voir sans avoir à zoomer à ce point.

**Comment by manfredbrandl** [comment]
I did translate via google:
---
Hello,

I am editing the items for the village of Saint-Ferdinand (QC), Canada. Deprecated elements such as the old municipal office location that is now a fire station and the Shell should no longer appear on the map. In addition, would it be possible to ensure that the icons of restaurants, accommodation, library, etc.? are bigger? You have to zoom a lot on the map in order to see them. I wish it was possible to see them without having to zoom to this point.
---

**Comment by quincylvania** [comment]
Hello @Saint-Ferdinand, thank you for the message. You can update outdated information yourself at https://openstreetmap.org/edit. It can take time for your changes to appear on maps that use OpenStreetMap data.

I am not sure I understand your second question. The map rendering on https://openstreetmap.org is handled at https://github.com/gravitystorm/openstreetmap-carto.

_Autotranslated:_

Bonjour @Saint-Ferdinand, merci pour le message. Vous pouvez mettre à jour vous-même des informations périmées à https://openstreetmap.org/edit. Il peut prendre du temps pour que vos modifications apparaissent sur les cartes qui utilisent les données OpenStreetMap.

Je ne suis pas sûr de comprendre votre deuxième question. Le rendu de la carte sur https://openstreetmap.org est traité à https://github.com/gravitystorm/openstreetmap-carto.
