### ISSUE TITLE
charge placeholder

### ISSUE THREAD

**Issue by roptat** [openstreetmap/iD#6729]
Spotted while translating the presets on transifex: presets.fields.charge_toll.placeholder and presets.fields.charge_fee.placeholder both contain "€1, $5, ¥10…" but the [wiki](https://wiki.openstreetmap.org/wiki/Key:charge) says the key should contain: `charge="amount currency"`, so "1 €, 5 $, 10 ¥…" looks more appropriate here (maybe without spaces if we consider the following examples). What do you think?

**Comment by quincylvania** [comment]
@roptat Interesting observation. Do we know why the wiki recommends that format? It seems user-unfriendly and nonsensical considering that's not how prices are generally written and parsers shouldn't have an issue with the `$5` format. If we change it, I can imagine someone else opening an issue to change it back because it looks wrong.

There's also an argument for using the `5 USD` format instead, since different currencies can use the same symbol. In any case, mappers an put whatever they want in there so consumers should be ready for all kinds of formats.

**Comment by roptat** [comment]
I don't know why the wiki suggests that. It's probably more consistent with units in general. It's also what I'm used to in my language. We say "5 €", and "€5" doesn't really make sense. ¥ also is not great, since the symbol means both Japanese yen and Chinese yuan. It is not even used in Japan (they would say "100円" instead). That's why I felt compelled to check with the wiki.

The three letter code would make a lot more sense, as it's more standard, unambiguous, and the discussion page has some good arguments for it. I think suggesting "1 EUR, 5 USD, 10 YEN, …" would be a good way to solve this issue. However I don't think iD should depart from what the wiki says. I'm not sure what the process is to get this kind of change accepted by the community, but I'll ask and see what I can do to promote that change :)

**Comment by quincylvania** [comment]
> We say "5 €", and "€5" doesn't really make sense. ¥ also is not great, since the symbol means both Japanese yen and Chinese yuan. It is not even used in Japan (they would say "100円" instead).

Thanks for the perspective here. For some reason I assumed the format was based on the currency itself and not the language, but I see I was wrong.

> I think suggesting "1 EUR, 5 USD, 10 JPY, …" would be a good way to solve this issue.

Agreed. I'm going to go ahead and change the placeholders to use currency codes. It should be fine for mappers to tag this way since the currency code format is [already in use](https://taginfo.openstreetmap.org/keys/charge#values). When there are multiple competing tag formats we use the one we think is best for iD mappers. Plus this format was [already discussed](https://wiki.openstreetmap.org/wiki/Talk:Key:charge).

It would be great if someone wrote up more detailed guidance about how to tag `charge` on the wiki.
