### ISSUE TITLE
Un-translatable 131 strings for preset

### ISSUE THREAD

**Issue by higa4** [openstreetmap/iD#6738]
131 untranslated strings for the preset category appeared today that has no or few comment on transifex. Unable to translate these. https://www.transifex.com/openstreetmap/id-editor/dashboard/
![](https://i.imgur.com/0G8FxAB.png)

**Comment by quincylvania** [comment]
Hi @higa4, the new strings are `terms` that we added for #5763. Similar to search terms for presets, these are search terms for fields. You can hover over the `1` tag to get more info:

<img width="315" alt="Screen Shot 2019-08-11 at 11 49 15 AM" src="https://user-images.githubusercontent.com/2046746/62836914-53165200-bc2e-11e9-9a62-bb5b9ff67ded.png">

It isn't super helpful that this text is hidden in this way though. @bhousel What do you think of switching to `[]` brackets instead of `<>` to avoid this?

**Comment by higa4** [comment]
OK, thanks.

**Comment by bhousel** [comment]
dup of #4326 
It's a good idea, but would potentially break a lot of existing translation work.

**Comment by quincylvania** [comment]
> dup of #4326

I was trying to find that 😅

> It's a good idea, but would potentially break a lot of existing translation work.

True. Since we just added it for fields there's no better time to switch those over. Though I'm not sure it's worth losing all the great work done on the German and Japanese localizations over the weekend.

**Comment by bhousel** [comment]
> True. Since we just added it for fields there's no better time to switch those over. Though I'm not sure it's worth losing all the great work done on the German and Japanese localizations over the weekend.

Wouldn't changing this break every `terms` translation going back 6 years?

**Comment by quincylvania** [comment]
@bhousel We could just change it for fields and not for presets. The `terms` for fields I just added last week.

**Comment by bhousel** [comment]
Oh ok!  It is probably good to try switching the field terms now and see how it works with brackets.  Then if it's better, we can think about switching the preset terms and #4326 later.   (For that - we can probably write a script to change and push the replacements to the transifex API so it doesn't just throw out everyone's old work).
