### ISSUE TITLE
Clicking the "covered" preset removes the option

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#6747]
For instance, if you create a foot path, type "covered" in the all tags section and then go to click the yes checkbox for the preset it will just close it. It also happens when you add covered along with yes to the all tags section and then try to cycle through the checkbox's options beyond no.

**Comment by bhousel** [comment]
I don't think we can support letting the user enter partial data (key only) in the "all tags" section and then expecting a ui checkbox above to properly cycle through values.  That checkbox is going to remove the key because it is trying to assign both key and value together.

Anyway I'm going to close this, as it's a pretty minor issue.  I think advanced users can just enter the tags that they want.

**Comment by Adamant36** [comment]
OK. That makes sense. I thought maybe it was a bug or something.
