### ISSUE TITLE
Complain about highway=construction crossing railways and other roads without neither conecting point nor tunnel nor bridge

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6749]
Currently such collision are not detected by validator.

Test case: `highway=service service=driveway` crossed by `highway=construction` and `highway=residential`.

![Selection_002](https://user-images.githubusercontent.com/899988/62882155-90173d00-bd31-11e9-86bd-c5c1625f77c3.png)

**Comment by quincylvania** [comment]
@matkoniecz This is intentional. Highways under construction can be in varying states of completion, including instances where no crossing physically exists yet. Aerial imagery is unlikely to show the latest state, making such warnings difficult to resolve without on-the-ground knowledge. The warnings will appear once a mapper marks a road as open anyway.
