### ISSUE TITLE
Suggest upgrading landuse=garden to leisure=garden

### ISSUE THREAD

**Issue by doublah** [openstreetmap/iD#6758]
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgarden
https://taginfo.openstreetmap.org/tags/landuse=garden

landuse tag is not recommended to use anywhere afaik but still has a significant amount of objects tagged. leisure tag is standard for gardens.

**Comment by quincylvania** [comment]
@doublah Interesting. I've found `leisure=garden` to be a confusing tag since people use it map both individual flowerbeds and entire garden facility POIs (e.g. botanical gardens). I doubt that `landuse=garden` is used any more consistently, so I agree iD should offer a fix.

However, I discovered [`landuse=flowerbed`](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dflowerbed) in the process which already has over 1900 uses. I think we should add a preset for that to iD so people can start to distinguish between garden POIs and landcover.
