### ISSUE TITLE
Power generator preset doesn't show filled generator:source field

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#6763]
Hi all,

I don't understand why power=generator preset is making the field generator:source field not visible once filled.
The preset shows appropriate generator:method and generator:type but no source when not empty. Is there any limit that prevent more than 5 fields to be displayed on iD?
![Capture du 2019-08-16 15-20-16](https://user-images.githubusercontent.com/5690599/63170447-8f382100-c039-11e9-9f44-13798ca1f861.png)

According to wiki, usage of generator:source, generator:method or generator:type requires a power=generator tag on the same object
See :
https://wiki.openstreetmap.org/wiki/Key:generator:source
https://wiki.openstreetmap.org/wiki/Key:generator:method
https://wiki.openstreetmap.org/wiki/Key:generator:type
A warning should be displayed to encourage users to complete such objects with power=generator if missing

All the best

**Comment by quincylvania** [comment]
@flacombe This is happening because once you set `generator:source` to `hydro`, the preset changes to the more specific "Water Turbine" (in English). Because the tag comes along with the preset, we don't need to show a field for it.

I know this isn't always obvious. We should probably find a way to indicate that the preset changed, possibly as suggested in https://github.com/openstreetmap/iD/issues/5611#issuecomment-447674974.

**Comment by quincylvania** [comment]
Here's a demo of what likely happened.

![generator preset change demo](https://user-images.githubusercontent.com/2046746/63173011-942ead80-c004-11e9-883f-c1a7db7e717a.gif)

**Comment by flacombe** [comment]
Thank you @quincylvania to make this clear to me, I didn't noticed the preset changing.
Instead of making the preset label highlight when changing, iD could display lightly which fields are involved in the preset (with an additional section initially hidden ? or when clicking on I ?)

Problem is not only when the preset changes, but when you click on an already defined object and don't see the field in appropriate section. The point is to know what does the preset means exactly (water turbine can also be implied by generator:type=francis_turbine here).

All the best

**Comment by quincylvania** [comment]
> iD could display lightly which fields are involved in the preset

This would be tricky since we generally hide fields that affect the preset (as evidenced by this issue).

If you're interested in what tags a preset requires, I encourage you to browse the preset definition files and exam the `tags` property.

https://github.com/openstreetmap/iD/blob/5edd1080706e8b8eb55db929eff3705bfda95c33/data/presets/presets/power/generator/source/hydro.json#L27-L30

**Comment by flacombe** [comment]
> I encourage you to browse the preset definition files and examine the tags property.
Thanks @quincylvania 

It's not about me, but how users in general may understand presets meaning.
No problem to hide those fields at first, but retrieving them in an additional category on the menu will certainly improve understanding and sharing of mapping practices. Not everyone is able to browse config file or sources of iD.
It can be a special color/icon on the "all fields" section to highlight which fields are actually involved in the preset as well.
Such a feature can prevent to open issues like I did, at a glance.

My 2 cts
