### ISSUE TITLE
make easier to tag collection points of e-waste

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6777]
I think that currently it is not easy to find tags in text-search

add translatable "electronic waste" term that will be recycling container synonym? (see https://www.wikidata.org/wiki/Q327400 translations - many languages have special word for that)

Example: https://www.openstreetmap.org/node/6725166932

```
amenity 	recycling
recycling:electronic_items 	yes
recycling_type 	container
```

**Comment by quincylvania** [comment]
@matkoniecz Thanks for the suggestion. I figured it'd be easier to just add a preset for this so mappers can start using a consistent tag. The key `recycling:electrical_items` already has over 900 uses and seems general so I went with that. Mappers can always use more specific tags like `recycling:mobile_phones` instead of or in addition to this.
