### ISSUE TITLE
Render left/right values of embankment and cutting

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/iD#6818]
The embankment 'hash' texture should be restricted when `embankment=left` or `embankment=right` (or `cutting=left`/`cutting=right`) to the respective side of the way, similar to how guard rails are rendered.

Might tie into fixing #5577.

**Comment by quincylvania** [comment]
@rivermont This might be okay, but `embankment=left`/`right` aren't documented on the wiki and have less than 1% of total `embankment` usage. It'd be nice to have some confirmation that these tags have community support before supporting them in iD.

**Comment by mboeringa** [comment]
If this tag is going to be supported, I would additionally suggest a validity check that warns against using **man_made=embankment** _in combination with_ **embankment=left/right**.

[man_made=embankment](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dembankment) explicitly defines "lower side on right side", which means that a combination of:

**man_made=embankment**

and

**embankment=left**

is ambiguous and essentially wrong. 

Since supporting only **man_made=embankment** & **embankment=right** is probably equally confusing, disallowing the combination of **man_made=embankment** with **embankment=x** is probably most sensible.

**Comment by quincylvania** [comment]
@mboeringa Yeah, we wouldn't support these values for `man_made=embankment`, but possibly on roads and railways.

**Comment by rivermont** [comment]
Closing this since `embankment=left/right` was deprecated by 7598109, and the current `man_made=embankment` rendering only renders the one side.
