### ISSUE TITLE
Add warning or restriction when trying to add a wikidata tag that already exists

### ISSUE THREAD

**Issue by Janjko** [openstreetmap/iD#6823]
There shouldn't be multiple elements with the same wikidata value. Each element in Wikidata can be connected with one, and only one object in OSM.

This has been violated when people try to connect a motorway with a wikidata tag, and then instead on a relation for a route, they put the tag on all the ways. Similarly on railways, brand stores, and other features.

If iD put a warning when it found two instances of the same wikidata tag, that would probably help with peoples awareness of this problem.

**Comment by quincylvania** [comment]
> Each element in Wikidata can be connected with one, and only one object in OSM.

@Janjko I'm not sure this is necessarily true. Can you point to discussion where this was decided? Or otherwise explain the rationale? I don't see much harm in letting people connect component features using `wikidata` tags. There currently appear to be [thousands](https://taginfo.openstreetmap.org/keys/wikidata#values) of Wikidata items linked to multiple features without problems to speak of.

In any case, iD isn't setup to query the OSM database by tag like this, so it'd be a complicated feature to add if it's possible at all.

**Comment by quincylvania** [comment]
@Janjko I've thought more about this validation rule and it really doesn't seem practical or necessary right now. Lacking an argument otherwise I'm going to close this issue. Thanks anyway for the suggestion.

**Comment by Janjko** [comment]
I started a big discussion on tag-talk mailing list, we'll see what comes out of it.
