### ISSUE TITLE
Don't offer to upgrade highway=raceway with sport=motor

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#6826]
For any highway=raceway without sport=* tagged, the iD asks the user to upgrade the tag with sport=motor. This is fine in most cases, however there are other sport tags such as motocross, karting, or speedway which can be used instead. 

Perhaps instead iD can simply highlight the fact a sport value has not been tagged?

**Comment by jeisenbe** [comment]
As [discussed at Openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/issues/3852#issuecomment-525132323), the most common sports tags for `highway=raceway` are:
`sport=motor` - 6551 ways - non-specific, any motorized racing sport
`sport=karting` - 1486 - go-karts
`sport=motocross` - 1417 - dirt track motorcycle racing

It would be quite useful to distinguish these, since a go-kart track is quite different than a NASCAR or Formula One raceway. 

Other sport tags in use:
`sport=rc_car - 114 - radio-controlled cars
`sport=speedway` - 100 - dirt oval track motorcycle racing in England and Europe

There's as yet no common tag to specify auto (car/truck) raceways or paved motorcycle raceways.

**Comment by quincylvania** [comment]
@jeisenbe Thanks for the suggestions. I added presets for karting and motocross tracks to make them easier to tag. We can add more presets as other tags become more popular.

@boothym I think it's fine to recommend `sport=motor` when no other `sport` is present since `motor` is so general. The new presets should help avoid situations where a mapper deletes the `motor` tag before adding another `sport` tag and sees the warnings.

**Comment by Nakaner** [comment]
> I think it's fine to recommend `sport=motor` when no other `sport` is present since `motor` is so general. The new presets should help avoid situations where a mapper deletes the `motor` tag before adding another `sport` tag and sees the warnings.

If the most frequent subtag has 69% share of the top 3 subtags, it should not recommended by the validation rules. It is right to add presets for the other two as well, but the validation rule should be changed from "missing `sport=motor`" to "missing `sport=*`, please select appropriate type". It is like suggesting `suface=asphalt` for residential roads in Europe. Many have that surface but a lot of them have a different one.
