### ISSUE TITLE
Validator: railway=platform / highway=platform

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#6828]
It seems there is a current validation rule which gives help to remove `highway=platform` but not `railway=platform`.
Why?

Example object to test the validator for this case:
https://www.openstreetmap.org/way/142536920

wiki's:
https://wiki.openstreetmap.org/wiki/Tag:railway%3Dplatform
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dplatform

**Comment by quincylvania** [comment]
@sun-geo I honestly don't know. Public transport is one of the most inconsistently applied schemas in OSM. It looks like only recently did the [wiki start recommending](https://wiki.openstreetmap.org/w/index.php?title=Tag:public_transport%3Dplatform&diff=cur&oldid=1883777) tagging also raised bus platforms with `highway=platform`.

Do you think iD should stop supporting `railway=platform` or start supporting `highway=platform`? Or something else?

**Comment by sun-geo** [comment]
_"Public transport is one of the most inconsistently applied schemas in OSM"_ That's true.

For my understanding the old 2008 tags eg. `highway=platform` https://wiki.openstreetmap.org/wiki/Proposed_features/platform (same as `highway=bus_stop`) are still valid. And the 2011 tags https://wiki.openstreetmap.org/w/index.php?oldid=625726 eg. `public_transport=platform` came on top.

So I'm happy for the validation of the old 2008 `highway=platform` and to add `bus=yes` / 2011 `public_transport=platform`, but I wouldn't remove the `highway=platform` tag.

But I'm also not a PT specialist, maybe we should ask for other opinions.

**Comment by bhousel** [comment]
The one in this example is tricky because it looks like a platform that is used for both buses and trams.  That's probably why iD isn't really sure what to do with it.

It is being matched as a "Tram Platform" preset, which I'm guessing is why the validator wants to remove the bus platform tag.

I've never seen the `services` tag before.  That's not part of PT schema.

<img width="374" alt="Screenshot 2019-09-04 11 00 43" src="https://user-images.githubusercontent.com/38784/64266828-44f0e400-cf03-11e9-95dd-9561d1d9b564.png">

**Comment by sun-geo** [comment]
Other example with less tags (only highway=platform):
https://www.openstreetmap.org/edit?way=697619138#map=19/40.71055/-74.01313

current validation rule recommendations are:
+ bus=yes (adding)
- highway=platform (removing)
+ public_transport=platform (adding)

**Comment by bhousel** [comment]
It looks like `highway=platform` was added to the deprecation list in 6e7d217

**Comment by quincylvania** [comment]
>  looks like highway=platform was added to the deprecation list in 6e7d217

Yep. I don't remember adding it specifically but I'm sure there was a reason at the time. It was possibly related to #6042 since a feature can't have `highway=footway` if it already has `highway=platform`.

**Comment by bhousel** [comment]
> Yep. I don't remember adding it specifically but I'm sure there was a reason at the time. It was possibly related to #6042 since a feature can't have `highway=footway` if it already has `highway=platform`.

Ah yeah this makes a lot of sense.  `highway=platform` really doesn't fit with other walkable things.

**Comment by quincylvania** [comment]
> highway=platform really doesn't fit with other walkable things.

Exactly. `highway=platform` might be okay if it was used for all platforms and was considered routable, but that it means "platform for highway-going vehicles" isn't obvious and creates edge cases for routers and renderers. Same with `railway=platform` not referring to train tracks. Personally I think it'd be great to stop using both of these but OSM is OSM.

**Comment by sun-geo** [comment]
> > Yep. I don't remember adding it specifically but I'm sure there was a reason at the time. It was possibly related to #6042 since a feature can't have `highway=footway` if it already has `highway=platform`.
> 
> Ah yeah this makes a lot of sense. `highway=platform` really doesn't fit with other walkable things.

But it seems there are routing engines which are using `highway=platform` for hiking routing, even if there is no `highway=footway` tagged.

Example object:
https://www.openstreetmap.org/way/165239826

Example hiking routing graph:
http://brouter.de/brouter-web/#map=19/52.32551/16.88670/standard&lonlats=16.886048,52.325795;16.887392,52.325195&profile=hiking-beta

**Comment by sun-geo** [comment]
> Exactly. `highway=platform` might be okay if it was used for all platforms and was considered routable, but that it means "platform for highway-going vehicles" isn't obvious and creates edge cases for routers and renderers.

Regarding rendering.
For `highway=platform` there is currently an active rendering rule at osm-carto (https://github.com/gravitystorm/openstreetmap-carto).
They use for `highway=platform` as line this view: https://wiki.openstreetmap.org/wiki/File:Rendering-highway_railway_platform_line.png
They use for `highway=platform` as area this color: https://wiki.openstreetmap.org/wiki/File:Rendering-highway_railway_platform_area.png
 
For `public_transport=platform` there is currently no rendering active at osm-carto.

**Comment by Lukas458** [comment]
>  It looks like only recently did the wiki start recommending tagging raised bus platforms with highway=platform.

It seems to me that this is not to use highway=platform _just_ because the platform is raised. This is just the kerb=raised property, not more. Might be that the wiki has to be fixed for this case.

**Comment by quincylvania** [comment]
@sun-geo That existing routers and renderers might handle this tag is great, but more generally a tag like this is another stumbling block for new OSM apps. A new router has to know that `highway=platform`, `railway=platform`, and `public_transport=platform` all exist and could be used redundantly and are probably routable. If we can't even keep these straight in iD then how can we expect consumers to get it right?

@Lukas458 said:

> It seems to me that this is not to use highway=platform just because the platform is raised. This is just the kerb=raised property, not more. Might be that the wiki has to be fixed for this case.

The page for `highway=platform` currently says:

> This tag differs from the tag `public_transport=platform` which only means a place where passengers board or alight from public transport vehicles; it does not need to be raised.

If this is the case then iD can't assume that all bus/tram platform lines should have `highway=platform` since not all are "raised". This needs to be clarified.

**Comment by sun-geo** [comment]
I agree, osm data consumers should have it so easy as possible to use the osm data. I don't know which source the routing engine developer are currently using for knowing which tags are good for routing. Maybe they look into this tables: https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions
And yes, the `highway=platform` is not mentioned there.
So, I don't know for the moment, how these developers of the above listed services (osrm, graphhopper and brouter) got this information for their routing programs.

**Comment by jeisenbe** [comment]
`public_transport=platform` is used the same as `highway=bus_stop` - it's the place you wait for a bus, but `highway=bus_stop` is still much more popular. `public_transport=platform` on a node or area does not imply the existence of a physical bus platform.

The tag `highway=platform` is for bus platforms, analogous to `railway=platform` which is the most common tag for train station platforms: a (slightly) elevated area where passengers wait.

Back in the day, when `public_transport=platform`, some wiki editors tried to say that `highway=platform` was deprecated or not recommended, but this never really caught on, because `highway=bus_stop` and `highway=platform` are easier to use and better match real-world features than the `public_transport` tags. Unfortunately, this means there is contradicting information in the wiki, not all of which describes the "de facto" situation accurately.

Here's the link to the older proposal that originally added highway=platform and railway=platform in October 2008: https://wiki.openstreetmap.org/wiki/Proposed_features/platform

I'd recommend iD support `highway=platform` for areas as before. It's reasonable for routers should consider `highway=platform` areas and ways to be routable, like `railway=platform` and areas with `highway=pedestrian` + `area=yes`.

**Comment by quincylvania** [comment]
> `public_transport=platform` on a node or area does not imply the existence of a physical bus platform.

I've been thinking more about this and it seems fair to say that in practice the tag `public_transport=platform` means "the place where passengers step onto the vehicle". This means the tag doesn't make a distinction between an unremarkable stretch of sidewalk and a raised, purpose-built structure, and that's okay. The other properties of the platform could be tagged separately.

Considering `highway=platform` appears to be inconsistently mapped and interpreted, I don't think iD can support it.

**Comment by sun-geo** [comment]
> Considering highway=platform appears to be inconsistently mapped and interpreted, I don't think iD can support it.


I agree, so then I would also appreciate to change the current validator rule: 
"check for tags `highway=platform` & `public_transport=platform`"
from current suggestion:
- to add tag: `bus=yes`
- to remove tag: `highway=platform`

to new suggestion:
- to add tag: `bus=yes`
- to **don't** remove tag: `highway=platform`
At least for osm-object which are lines or areas/relations, maybe not for nodes?

Example objects where the current validator rule is telling to do something:
for an area/relation object: https://www.openstreetmap.org/way/449704557
for a line object: https://www.openstreetmap.org/way/671116433

Should I better open a separate issue-ticket for this request?

**Comment by quincylvania** [comment]
@sun-geo Okay, I made it so iD will only add `public_transport=platform` and not remove anything, meaning the mapper can use `highway=platform` as they like without iD having an opinion.

Maybe one day we'll have robust, cohesive public transport tagging in OSM 🤞
