### ISSUE TITLE
allowing to set wikipedia links depending on language without upgrade

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#6829]
Hi,
please just have a look at https://www.openstreetmap.org/way/712696255
it's a supermarket in germany. The brand:wikidata tag is correct, but I wanted to set "brand:wikipedia=de:Aldi" instead of "brand:wikipedia=en:Aldi" because the shop is in Germany.

But if I do that, there comes the dialogue to update the feature, with setting "brand:wikipedia=en:Aldi".

My question is: Does the "*:wikipedia"-language always have to be english as default? At least, I would suggest not to try to upgrade these features with an english wikipedia article when there is already set one in another language.

**Comment by quincylvania** [comment]
@Lukas458 Sorry, but the `brand:wikipedia` is limited to just one Wikipedia language. English isn't the default per se—iD gets these tags from the [name suggestion index](https://github.com/osmlab/name-suggestion-index) and the folks there try to use the predominant or native language for each brand. You can raise specific issues in that repo.

I wouldn't recommend we allow diverging from the NSI tags since its whole purpose is to standardize tags like this.

However, there's no need to worry about the `brand:wikipedia` tag since I don't know of any data consumers that currently use it. It's also much less important than `brand:wikidata`, which is language-agnostic and points to all available Wikipedia articles.

#6471 is related, though I fear discussion wasn't very constructive due to some bad-faith accusations.

**Comment by bhousel** [comment]
Yes, for what it's worth `brand:wikipedia` is really not a very important tag.  It's unstable (url can change), and language dependent.  We mostly just add it because historically people have added it, and it's sort of human readable. 

The more valuable tag is `brand:wikidata`, which is a stable identifier that you can use to find all of the wikipedia articles, in all of the languages, and much more.

(Put another way, we really could remove all of the `brand:wikipedia` tags, and there wouldn't be any data loss as long as `brand:wikidata` is there.)

**Comment by jidanni** [comment]
There should be a warning popup that only a single language wikipedia article is to be used, else users will always think "why does the interface not have a + button to add a second language?"

**Comment by quincylvania** [comment]
> There should be a warning popup that only a single language wikipedia article is to be used, else users will always think "why does the interface not have a + button to add a second language?"

I don't think most users really care, and those who do can read about the tag in the documentation.
