### ISSUE TITLE
Preset: Cycle & Foot Path should produce highway=path rather than highway=cycleway

### ISSUE THREAD

**Issue by naomap** [openstreetmap/iD#6836]
The preset highway/cycleway/bicycle_foot.json produces **highway=cycleway** + foot=designated + bicycle=designated. 

According to the **case S5** in https://wiki.openstreetmap.org/wiki/Bicycle#Miscellaneous, a "Cycle and Foot path" should instead produce  **highway=path** + foot=designated + bicycle=designated.

This bug causes a lot of burden in the Greater Paris area, where a few mappers have damaged a lot of data.

**Comment by sun-geo** [comment]
I agree, same tagging (highway=**path** + foot=designated + bicycle=designated) is a tool recommending for German signs, see:

http://osmtools.de/traffic_signs/?signs=240
highway=path
bicycle=designated
foot=designated
segregated=no
traffic_sign=DE:240

or

http://osmtools.de/traffic_signs/?signs=241
highway=path
bicycle=designated
foot=designated
segregated=yes
traffic_sign=DE:241

**Comment by BjornRasmussen** [comment]
I personally prefer using `highway=cycleway` on any path that is designated for both cyclists and pedestrians, since those paths look more like cycleways than what I would consider a "path".  Although the two methods are equivalent, I think that using cycleway implies that the way is more than just a path in the woods, but rather one that is more formal, and suitable for cyclists.
So really, it doesn't actually matter which tags are used on this preset, because data consumers will interpret them all the same, so I don't think we should change the preset without a good reason.

**Comment by charlesmillet** [comment]
> I personally prefer using `highway=cycleway` on any path that is designated for both cyclists and pedestrians, since those paths look more like cycleways than what I would consider a "path". Although the two methods are equivalent, I think that using cycleway implies that the way is more than just a path in the woods, but rather one that is more formal, and suitable for cyclists.
> So really, it doesn't actually matter which tags are used on this preset, because data consumers will interpret them all the same, so I don't think we should change the preset without a good reason.

This is a long standing subject concerning the path. I used to prefer to chose highway=footway or highway=cycleway rather than use highway=path but I admitted that highway=path was something very generic, justly adapted to those cases where you can't tell and that some additional information like surface, width, segregation, etc. were widely sufficient to distinguish with simple paths.

**Comment by naomap** [comment]
There is a good reason for changing this preset : it lets beginners damage data that have been carefully created by others. The request http://overpass-turbo.eu/s/Mao shows some of the path shared by cyclists and pedestrians, that have been changed to cycleways using iD and this new preset, where this is wrong : these are not cycleways, there are merely wide sidewalks authorized to cyclists.

There has been long discussions in the past on the Tagging list, as well as on the french Talk-fr mailing list, on the meaning of highway=path. Even though I agree with you that that highway=path should refer to "a path in the wood" (words have a meaning !), the agreement of the OSM community is that highway=path describes a "generic path", i.e. a path that cannot be defined as reserved to a specific usage.

Also data consumers may want to make a distinction. For instance in France so called "voies vertes", which are shared by cyclists and pedestrians, are precisely mapped with highway=path + foot=designated + bicycle=designated. The result of this preset is that they may get changed from "voies vertes" to "piste cyclables" (cycleways). However we need to distinguish them on a map, and in statistics.

So please consider changing the preset so that it conforms to the documentation.

Regards,
Antoine.

**Comment by quincylvania** [comment]
So I originally added the Cycle & Foot Path (greenway) preset for use in countries like the US where cycleways generally allow pedestrian access, in contrast to Europe where they generally don't. In the meantime we added a property to presets that lets us limit them to specific countries, so to address this issue I just restricted this preset to North America. Europe can continue to tag greenways as they see fit.

Personally I find it unsustainable for a global map to use different tagging conventions in different places, but if that's the nature of OSM then iD will try to reflect that.

**Comment by systemed** [comment]
highway=cycleway is standard tagging in Britain for this. Could you reinstate this for the UK bounding box?

**Comment by quincylvania** [comment]
@systemed Yes! We can support any number of countries where this preset is appropriate.

**Comment by systemed** [comment]
\o/ Thank you!

**Comment by simonpoole** [comment]
Arghhh.

For starters @naomap any data consumer that doesn't treat the small number of possible cycleway/footway variants either with path or cycleway/footway as the base object as equivalent is IMHO broken. The wiki page in question has been subject to lots of fiddling over the years (because it is a matter of taste and people tend to get upset about such things). [Edit: the page you are referring to is actually not the one I thought of, but leaving out the alternative taggings for cycleways is still wrong, as there is no consensus that only one of the variants is correct, as this issue shows].

Then because it is a matter of taste, and that tends to vary a lot between countries, having a complaint from one country (France) lead to a global change in which it seems to be every country now has to complain to get the what fits them best reinstated (after they have noticed potentially months from now) is just silly. 

@quincylvania is it possible to invert the preset per country selection, aka get one specific for FR and whoever else wants it, and leave the other countries as is?

**Comment by quincylvania** [comment]
> @quincylvania is it possible to invert the preset per country selection, aka get one specific for FR and whoever else wants it, and leave the other countries as is?

@simonpoole Good idea. This is better than whitelisting hundreds of country codes.

I changed the greenway preset to only be blacklisted in France. Mappers should let us know what other places to exclude it, if any.

**Comment by mvl22** [comment]
> I used to prefer to chose highway=footway or highway=cycleway rather than use highway=path but I admitted that highway=path was something very generic, justly adapted to those cases where you can't tell and that some additional information like surface, width, segregation, etc. were widely sufficient to distinguish with simple paths.

> I personally prefer using highway=cycleway on any path that is designated for both cyclists and pedestrians, since those paths look more like cycleways than what I would consider a "path". Although the two methods are equivalent, I think that using cycleway implies that the way is more than just a path in the woods, but rather one that is more formal, and suitable for cyclists.

Co-author of CycleStreets here. Yes, we agree on these two.

We treat `highway=cycleway` as primarily designed for cyclists, which users on foot may sometimes be permitted to use (when `foot=yes` is added), `highway=footway` as a footway that cyclists are sometimes permitted to use (when `bicycle=yes` is added), with the latter considered slower because cyclists using a path designed for pedestrians should be more cautious in cycling. In the UK, typical rubbish shared-use we would expect to see the latter. Even though both end up implying `bicycle=yes`,`foot=yes` - we treat "cycleway" vs "footway" as actually having semantically-different meanings.

`highway=path` we regard as an ill-defined tag and therefore inherently poorer, compared to cycleway/footway which have a much clearer intention. Adding things like surface and width being good really indicates that it it is not a generic path and so should be tagged fundamentally as cycleway/footway in the first place, especially in cities.

Our [notes](https://www.cyclestreets.net/help/journey/osmconversion/) on `highway=path` state: "Horridly complex tag, everyone uses it differently. [...] This includes snowmobile trails, ski trails, hiking trails, horse trails, bike trails and paths, mountain bike trails as well as combinations of the above and other modes of transportation. These routes may have any type of surface."

> So really, it doesn't actually matter which tags are used on this preset, because data consumers will interpret them all the same, so I don't think we should change the preset without a good reason.

No, we think there is a different semantic meaning to these three highway types.

**Comment by mvl22** [comment]
> Mapping cycleways is getting IMHO too complex

+1 ...

> The SOTM talk "Is the OSM data model creaking?" mentions cyclists needs for detailed mapping, I'm looking forward to attending it.

Hope you managed to come to our talk!

The video of it is now at:
https://media.ccc.de/v/sotm2019-1038-is-the-osm-data-model-creaking-

and the slides at:
https://www.cyclestreets.net/blog/2019/09/22/sotm2019/

**Comment by henry4442** [comment]
Please add "de" to the exclusion list: "notCountryCodes" in data/presets/presets/highway/cycleway/bicycle_foot.json
It causes retagging of correct data by new users.
highway=path with *=designated is the existing data in germany:
https://wiki.openstreetmap.org/wiki/DE:Bicycle/Radverkehrsanlagen_kartieren
