### ISSUE TITLE
iD knows about electric poles but not telephone poles

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6848]
iD knows about electric poles and suggests it when we type it in -- alas but not [telephone poles](https://wiki.openstreetmap.org/wiki/Telecoms#Telephone_Poles).

**Comment by quincylvania** [comment]
Hmm this issue speaks to a core problem with tags like `power=pole`. Such a tag inextricably couples a feature's form (a pole) with its function (holds power lines). You can't add utility poles without implying they hold power lines.

While we could add more and more presets for anything a pole could be holding (coaxial cable, fiberoptic line, telegraph wire, clothesline, etc.), this would be confusing to iD mappers ("what type of pole is this? should I care?") and would further complicate the OSM database.

A simpler solution is to say "this is a pole" and then specify its functions with subtags. I'm just now learning about `man_made=utility_pole` and I think we should support it in iD for such situations.

**Comment by jidanni** [comment]
Glad to see poles are getting more attention.
In rural / remote areas they are indeed vital markers.
In fact through my promotion
https://www.jidanni.org/geo/taipower/
they have become a major way of reporting incident locations to 911 /
119 first rescuers in my country.

**Comment by quincylvania** [comment]
@jidanni Nice, I hope this is helpful. I'm closing this since now mappers can add any kind of utility pole. If someone cares a lot about tagging what these poles hold, I recommend coming up with a namespace like `utility:*=yes`, e.g. `utility:communication=yes`. I don't see us supporting tags like `communication=pole` anytime soon.

**Comment by jidanni** [comment]
(Here we see electric poles have an icon, but not telephone poles.)
![X4](https://user-images.githubusercontent.com/1230959/66367221-d8677a00-e9c5-11e9-86ae-3c8354d7f2d8.jpg)
```
communication=pole
name=中埤枝130
telephone=pole
```

**Comment by quincylvania** [comment]
@jidanni Yes, like I explained, iD will support `man_made=utility_pole` instead of `telephone=pole`.

**Comment by flacombe** [comment]
Hi

Sorry for coming here a bit late
Telecom poles is a long run discussion, where no satisfying solution has been found.
Since there are many shared poles, something like man_made=utility_pole would be great.
Have in mind towers, portals and terminals please.

Instead of man_made=utility_pole, would you consider following possibilities please:
* man_made=pole + utility=*
* man_made=tower + utility=*
* man_made=portal + utility=*

Buuuuut this should be discussed on tagging and need a formal proposal to be introduced, there are just so many power towers/poles in the db yet that it can't be addressed with a specific editor issue.

**Comment by quincylvania** [comment]
@flacombe Any coalescing of tags would be appreciated, but I'll leave breaking change up to other channels. A few notes:

- I don't mind `man_made=utility_pole`. Things like flagpoles and lighting poles have different forms
- `man_made=tower` is already used for building-like towers

**Comment by jidanni** [comment]
https://wiki.openstreetmap.org/wiki/Telecoms#Telephone_Poles currently says

> Recommended tagging
> 
> communication=pole
> telephone=pole
> ref=

What should I update it to? (iD just sees this as a raw "Point".)

**Comment by jidanni** [comment]
OK. iD helped me (via hints) make
> man_made=utility_pole
> ref=12345
> utility=telecom

So I will make a note about it on the wiki.

**Comment by jidanni** [comment]
Maybe
```
communication=pole
ref=上埤枝41
telephone=pole
```
should trigger "outdated tags" warning... but... nothing to update them to.

**Comment by jidanni** [comment]
OK, iD has no preset for "telephone pole".
OK, maybe nobody has never seen one by the side of the road these days anymore.
So autopilots needn't bother with them, but only electric poles.
As the latter are made out of concrete often, and not wood.
So are more hazardous or something.

**Comment by flacombe** [comment]
Here is a proposal that isn't mentioned here : https://wiki.openstreetmap.org/wiki/Proposed_features/Utility_poles_proposal

It intends to review man_made=utility_pole + utility=telecom for telephone poles.
To be consistent, power=pole is proposed to imply man_made=utility_pole + utility=power

Feel free to comment this proposal as it is still RFC.
Voting will begin sometimes when I'll have time to prepare it.

All the best
