### ISSUE TITLE
wishlist: recipes feature

### ISSUE THREAD

**Issue by ArloJamesBarnes** [openstreetmap/iD#6852]
[I realise even if others think this is a good idea it would be far-off in the roadmap, but I thought it would be good to put it into tracking regardless (even if it's just "follow this issue instead of asking us about it").]

I'm not sure where the best place to store them would be, but I think it would be useful to have 'recipes' -- bits of mapping that will be largely the same all over the world. For example, regulation sports fields/courts squared and dimensioned to the right size. It seems a logical progression from presets.

Like the brand index, one would have to be careful to make clear what could be considered default (in the example, `sport=[blah]`) and what would likely need to be customised by the mapper (`surface=[material]`).

**Comment by 1ec5** [comment]
Interesting idea! Reminds me of clip art in presentation software and models in 3D modeling software.

I wonder what the workflow would be like: would there be a preset specifically for a regulation baseball field, such that selecting the preset would be equivalent to pasting a prefabricated set of features? Would iD automatically enter move mode, and would the user have a discoverable way to enter rotate mode (since features are rarely north-aligned)?

**Comment by ArloJamesBarnes** [comment]
That's what I imagine, although I realise it reverses the current workflow of `draw ==> tag`.

**Comment by bhousel** [comment]
> I'm not sure where the best place to store them would be, but I think it would be useful to have 'recipes' -- bits of mapping that will be largely the same all over the world. For example, regulation sports fields/courts squared and dimensioned to the right size. It seems a logical progression from presets.

Ok, so - fun fact..  Mercator makes this kind of hard!    (technically _Web_ Mercator, but same idea).

What you're calling recipes aren't really "largely the same all over the world".

Here is a soccer field that I copied from New Jersey, USA at around 40°N: (yes I outlined the soccer markings, not the football markings).

<img width="800" alt="Screenshot 2019-09-13 21 30 16" src="https://user-images.githubusercontent.com/38784/64901987-c700ab80-d66d-11e9-8632-7601d5641141.png">

And here it is pasted into Murmansk, Russia at around 69°N:

<img width="800" alt="Screenshot 2019-09-13 21 30 49" src="https://user-images.githubusercontent.com/38784/64902023-1a72f980-d66e-11e9-8107-c33960c822c3.png">

It's tiny!  This is because, in Mercator, the whole world is stretched out the further towards the poles you go.  

This is a solvable problem - we would need to rescale the "recipes" according to the latitude that they are copied from / pasted to.  

I do think this is maybe of out of scope for iD, but I think it's a neat idea.  I mostly just wanted to demonstrate how the Mercator projection messes things up a bit.

**Comment by quincylvania** [comment]
@ArloJamesBarnes Interesting idea! I wonder if there are other features this would be useful for besides sports pitches. Even those don't seem like a big deal since most are rectangular and easy to draw, particularly once we finish the square drawing tool. The more complex the geometry the more useful these would be. 

This idea does have me thinking… with the v3 toolbar and assistant we could support more preset-specific drawing methods. Like drawing the wedge shape of a baseball field or the pill shape of a propane tank in just three clicks.

**Comment by quincylvania** [comment]
Sitting on this awhile now, I haven't found myself needing this tool. It'd be really hard to build and there just aren't that many types of real-world features with a uniform, non-rectangular shape. How about we focus on general-use drawing tools for curves and right angles instead?

Thanks anyway for the suggestion, @ArloJamesBarnes!

**Comment by TheAdventurer64** [comment]
https://osmus.slack.com/archives/CBK3JLUJU/p1600463850004000

**Comment by ghost** [comment]
> How about we focus on general-use drawing tools for curves and right angles instead?

Is this on the roadmap somewhere?
