### ISSUE TITLE
Remove waterway=riverbank from list of deprecated tags

### ISSUE THREAD

**Issue by jeisenbe** [openstreetmap/iD#6853]
I recommend removing `waterway=riverbank` from list of deprecated tags.

The tag `waterway=riverbank` is not listed as deprecated at the openstreetmap.org wiki, nor has it been for at least the past 2 years.

Currently `waterway=riverbank` is over 306k times, much more frequently than `water=river` which has been used 66k times: https://taginfo.openstreetmap.org/compare/water=river/waterway=riverbank

Tagging a feature with `waterway=riverbank` only require one tag, and is unambiguously the area of a river. Using `natural=water` + `water=river` risks mappers forgetting to add the `water=river` tag, or removing it unintentionally - this will still be interpreted as "water" by all database users, but the information that the water is a river might be lost. 

While some mappers prefer to use `natural=water` + `water=*` for all areas of inland water (not including seas and the ocean), most still prefer `waterway=riverbank` for rivers. This option should not be presented as deprecated, nor should iD suggest replacing the tag when found.

![taghistory-waterway-riverbank-vs-water-river](https://user-images.githubusercontent.com/42757252/64908326-82424680-d739-11e9-9c5b-81834da02d9a.png)

**Comment by SilentSpike** [comment]
This issue is in the same vein as #6589

**Comment by bhousel** [comment]
This was settled in #5591

**Comment by jeisenbe** [comment]
@bhousel stated in #6853 " I do like natural=water+water=* better" and
"I think that the benefit of consistency outweighs the disadvantage of
confusing tag names."

These comments do not address my comments above, where I've provided
evidence why waterway=riverbank is preferred by most mappers, as shown
by usage of the two tags over time.

The main issue is that promoting `natural=water` for rivers has led to
some mappers tagging river areas as `natural=water` only, without
`water=river`, and this is reducing the quality of data. This makes it
more difficult to distinguish between sections of a river which flow
into a lake or reservoir vs sections that are free-flowing rivers.

I would appreciate a well-reasoned response to these arguments.

**Comment by bhousel** [comment]
> I would appreciate a well-reasoned response to these arguments.

1. Can you just put your comments on #5591 instead instead of opening a duplicate issue?
1. There has been plenty of discussion going back years on the talk pages for [`natural=water`](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dwater) and [`waterway=riverbank`](https://wiki.openstreetmap.org/wiki/Tag:waterway%3Driverbank) pages.  You can look a the wiki history and see that the `waterway=riverbank` page has been deprecated and un-deprecated several times.  Anyway you should read those if you want reasoned arguments. 
1. The `waterway=riverbank` page literally says "`waterway=riverbank` is an alternative to `natural=water + water=river` that was proposed as preferable".  So, we're trying to do the thing that is preferable.
1. I said other things on that issue too, but you quoted the "I like this tag better better" part, which feels kind of misleading to me.  I actually did research this.
1. `waterway=riverbank` sounds like a linear feature, and many people have mistakenly used it that way.  (also see wiki discussion)
1. The tag popularity has a lot to do with the iD preset, not because people were preferring one tag over another.  We can't just look at tag popularity to decide what to do.  We need to listen to users and mappers.  (This is an issue where someone asked us to make the change, we considered the alternatives, and we decided to go with what they asked us to do).

**Comment by bhousel** [comment]
Also the real graph looks like this.. you cut out the trend lines.

![taghistory](https://user-images.githubusercontent.com/38784/64915741-5b394400-d73c-11e9-83aa-96ed36f96b27.png)

**Comment by jeisenbe** [comment]
Re: discussing in #5591 instead

That issue is about the preset. I didn't expect to preset to be changed back from `water=river` to `waterway=riverbank`, I would just like `waterway=riverbank` removed from the list of deprecated features, since there is not consensus or evidence from recent usage patterns.

This would mean that new mappers would still be encouraged to use `natural=water` + `water=river`, but not told to switch existing objects to the new tag, if I understand the code correctly?

> the real graph looks like this.. you cut out the trend lines

[Taghistory](https://taghistory.raifer.tech) has not been updated since June or July 2018, so the graph ends there. The "trend line" is just a straight line from the last data point to the current numbers per taginfo, so it doesn't provide any additional information besides what I posted originally, unfortunately. 

It would be interesting to see if `waterway=riverbank` continued increasing until [January 2019](https://github.com/openstreetmap/iD/commit/18ea434d021817505638c42de9802aedcf2937ad)wor if the inflection point was sooner or later, but I don't know of any up-to-date source other than taginfo.

> We can't just look at tag popularity to decide what to do. We need to listen to users and mappers.

I agree. For deprecated features, there should be clear consensus in favor of the new tag. This would be a higher standard than that used to pick a preset.

While a proposal back in 2011 introduced `water=river/etc` and suggested deprecating `waterway=riverbank`, the evidence from 2012 to mid 2018 shows that waterway=riverbank continued to be consistently more popular among mappers during that time period.

**Comment by jeisenbe** [comment]
My main concern is that mappers are still not adding `water=*` to features with `natural=water`. Here's the comparison (till mid-2018 since the data afterward isn't available) - the blue line is all objects with any `water=` tag.

![taghistory-waterway-riverbank-vs-water-river](https://user-images.githubusercontent.com/42757252/64916524-a7769980-d7b9-11e9-9c88-c18daec78174.png)

Most mappers are still not adding `water=*` subtags to `natural=water`, and this is a problem. But perhaps I should open a separate issue about that?

**Comment by 1ec5** [comment]
[Ohsome](https://ohsome.org/apps/dashboard/) shows 14,000 more `water=river` ways and 20,000 fewer `waterway=riverbank` ways since the deprecation went live in openstreetmap/openstreetmap-website#2122:

![count](https://user-images.githubusercontent.com/1231218/64918001-993e6400-d74c-11e9-9f91-6a789bf50c08.png)

Or 4&nbsp;682&nbsp;km² worth of new `water=river` ways and 9&nbsp;663&nbsp;km² fewer `waterway=riverbank` ways:

![area](https://user-images.githubusercontent.com/1231218/64918140-f9cea080-d74e-11e9-8a8a-49a4e8cb5203.png)

(Note that mappers may have intentionally shrunken or deleted some rivers during this time period.)

> Most mappers are still not adding `water=*` subtags to `natural=water`, and this is a problem. But perhaps I should open a separate issue about that?

I don’t see how the omission of `water=*` could be caused by the `waterway=riverbank` deprecation, since the validator warning suggests adding `water=river`.

Are you sure the bare `natural=water` areas are being added by iD users for the most part? It’s just as easy to use that tag by itself in other editors such as JOSM or Potlatch. In iD, only one preset adds `natural=water` without `water=*`: the [Water](https://github.com/openstreetmap/iD/blob/master/data/presets/presets/natural/water.json) preset, which only appears when searching presets for “water”. [Each of the other `natural=water` presets](https://github.com/openstreetmap/iD/tree/master/data/presets/presets/natural/water) adds a `water=*` tag, including the River preset.

**Comment by jeisenbe** [comment]
Wow, thank you for that link! It's very helpful.

> 4 682 km² worth of new water=river ways and 9 663 km² fewer waterway=riverbank ways:

Yikes! That doesn't make sense. 

> Are you sure the bare natural=water areas are being added by iD users for the most part?

No, I think it's unlikely they are being added with iD itself. But perhaps some users now think that `waterway=riverbank` and similar are not needed, but are replacing them with `water=natural`? It's hard to understand why the total area of tagged rivers (`=riverbank` + `water=river`) has declined in the past half year, as your data shows. 

I think we should add a validation rule that suggests adding `water=` if the tag is missing on `natural=water` areas. I'll open a new issue for this here, and check with JOSM too.

**Comment by 1ec5** [comment]
>> 4 682 km² worth of new water=river ways and 9 663 km² fewer waterway=riverbank ways:
> 
> Yikes! That doesn't make sense.

Come to think of it, I’m not sure how much credence to give Ohsome. It’s saying that, during the same time period as above, only 162&nbsp;km² worth of `natural=water` ways were added but a whopping 9&nbsp;074&nbsp;km² worth of `water=*` ways were added:

![natural=water versus water=*](https://user-images.githubusercontent.com/1231218/64923928-ca8e5280-d793-11e9-8c55-eec6d8bf1c11.png)

If Ohsome is to be believed, then we actually have the reverse problem: people adding `water=*` without `natural=water`! 🤷‍♂

**Comment by quincylvania** [comment]
@jeisenbe I agree with @bhousel on this. But to explain why we should't offer the preset without the upgrade, see https://github.com/openstreetmap/iD/issues/6589#issuecomment-507294943:

> iD only supports one way to tag things even if OSM allows multiple conflicting schemes. This reduces confusion for casual mappers.

If a user adds some rivers in iD and then later sees a feature with `waterway=riverbank` but no warning, they may wonder "how is this different?", "why can't I add this?", and "am I even mapping these right?", which is alienating and not user-friendly. I used to think stuff like this all the time when I'd encounter old tags before iD had runtime tag validation.
