### ISSUE TITLE
Buggy Wikidata handling with iD

### ISSUE THREAD

**Issue by Prince-Kassad** [openstreetmap/iD#6875]
How to reproduce:

* Click this link: https://www.openstreetmap.org/edit?way=234938994#map=19/50.14551/9.02485

What is expected:

* iD should display a Wikidata field with the item

What happens instead:

* iD displays an empty Wikidata field with a grayed-out link; clicking on it still works and leads to the correct Wikidata item. iD also displays an empty Wikipedia field (supposedly for German Wikipedia) although the object is not tagged with any wikipedia= tag; clicking on the non-grayed out link does nothing.

Attempting to delete the empty Wikipedia link will actually delete the Wikidata tag with no prior warning.

I have no idea where the issue lies.

**Comment by Prince-Kassad** [comment]
Another thing I just noticed: the address field is grayed out and does not display any address at all, even though the object contains appropriate addr: tags.

**Comment by quincylvania** [comment]
@Prince-Kassad Hmm this is what I see when running iD in German:

<img width="374" alt="Screen Shot 2019-09-24 at 10 06 08 AM" src="https://user-images.githubusercontent.com/2046746/65493412-14251e80-deb3-11e9-90a9-b494fcbcd5e6.png">

iD has to query Wikidata in order to show the name and description, so it's possible that failed or your browser/network blocked the query. We should probably have a better fallback UI.

The Wikipedia field appears if there's a `wikidata` tag. Since there isn't actually a `wikipedia` tag, it appears empty.

The Address field won't load if iD can't tell what address format to use. Weirdly this also isn't working for me, I'll investigate further.

**Comment by quincylvania** [comment]
@Prince-Kassad I tried this again and was able to get both the Wikidata and Address fields to load after a moment. Since these both require network calls, I'm thinking it was a network issue and not a bug with iD.

**Comment by quincylvania** [comment]
@Prince-Kassad However, #4198 might interest you. It's about making the experience nicer when something on the network is unavailable.
