### ISSUE TITLE
Hint also to enter the Building permit number

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#6886]
Similar to #6880, one notices when filling out the details for a new home, even "architect" is hinted.
Well better would be a field for the building permit / licence etc. number. Most permanent buildings usually have one, no matter what the country. And with that the user can get all the rest of the details. (Yes there might not be an OSM tag established yet.)
Anyway if available it would be a shame to not have the user enter it.
And in fact the Building permit number is often a better match for the polygon we are drawing than the street address, if any, that is assigned.
Note also there might be a construction permit, and then later a use permit.

**Comment by quincylvania** [comment]
@jidanni Have you actually wanted this data from OSM? Do you have evidence it would be widely useful? Does anyone else think we should add these?

Property boundaries might also be useful to some people but there's agreement they don't belong in OSM since they're difficult to verify and maintain. These feel like that to me but perhaps others disagree.

**Comment by jidanni** [comment]
Well I just thought since it is hinting the user to enter the architect, it might as well hint for the permit number.

**Comment by quincylvania** [comment]
The `architect` tag has existed in OSM for awhile and is mostly used for important buildings. I'd contend that it's more interesting and easier to verify than a permit number.

**Comment by jidanni** [comment]
Well OK... even though permit numbers may be hard to dig up out of each differing local agency.
