### ISSUE TITLE
problems with trying to add a name for post boxes that are tagged with brand

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/iD#6890]
Hi,
please have a look at https://www.openstreetmap.org/node/2293452747

this post box is tagged with brand=Deutsche Post because it's not just the operator, but a kind of brand acting in the post business in germany. The issue is now that iD wants to add not only the correct brand:wikipedia tag, but also "name=Deutsche Post" which would be clearly wrong for a post box, wouldn't it?

**Comment by quincylvania** [comment]
@Lukas458 This is an effect of [name suggestion index](https://github.com/osmlab/name-suggestion-index) entries needing a `name` tag. (iD gets its brand suggestions from there). I'm not intimately familiar with that project but you could try researching or asking about the issue over there.

If the NSI adds a mechanism to make `name` tags optional or malleable then iD could support it. But again, I'm no expert on this.

**Comment by bhousel** [comment]
I agree that for some entries from NSI we should prioritize `operator` instead of `brand`, and for these we might make `name` optional or exclude it entirely.. `post_box` is a good example of this kind of feature.  (FWIW iD has been using `name` this way for at least 5 years, so it's not really a new issue, but there is a lot more visibility into NSI now that the validator uses it).
