### ISSUE TITLE
Disconnecting selected way should move the new node interactively

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#6904]
When disconnecting a specific way from an intersection node, the newly created node should follow the mouse cursor, similar to the interactive Continue or Move tools.

Steps to reproduce:

1. Select a way.
1. Hold down Shift and select a node along that way that is shared among multiple ways.
1. Click Disconnect.

Actual results: The node along the selected way is duplicated at the same location and the selected way is no longer connected to the other ways. Clicking on the intersection may select the existing node or the new node, seemingly nondeterministically.

Expected results: The node along the selected way is in move mode, following the cursor until the user clicks somewhere on the map. The selected way is no longer connected to the other ways. While in move mode, pressing the Esc key leaves the node at the original location.

The proposed behavior would give the user control over the node’s placement, avoiding the headache of selecting the new node from a pile of coincident nodes. Moreover, if the user accidentally disconnects the node, they get an obvious indication that something has happened. #2206 is similar but for the case where all the ways at a given node are disconnected from each other, without first selecting a particular way.

**Comment by quincylvania** [comment]
So lately I've been doing a lot of work to build touch/stylus support for iD that works as seamlessly as possible with the traditional mouse and keyboard workflows. Unfortunately, the existing move mode doesn't really work for touch input since touches can't move around the map while "up". Thus, two-step operations like the one described are unmanageable and I've actually been thinking about ways to replace them (see #6674 and #7599). While we could theoretically enable this workflow for mouse/keyboard input only, I'd personally prefer to avoid the fragmentation and just fix the general case of disconnected node selection via #2206.

**Comment by quincylvania** [comment]
Regrettably, I still don't see a great way to do this with parity on touchscreens.

#7984 was just opened about making the nodes of the selected way the draggable ones (which I'm sure has been mentioned before but I don't see a matching issue). This should make the scenario a lot more predictable.
