### ISSUE TITLE
Close notes on submission by magic keyword

### ISSUE THREAD

**Issue by rugk** [openstreetmap/iD#6906]
I want to same feature GitHub has (for closing an issue when a PR is merged: https://help.github.com/articles/closing-issues-via-commit-messages/) for notes in OSM/

# Use case

I want to fix a note.

## What do I do now

1. I open id and enable notes view.
2. Check note and copy ID.
3. Change things and include the ID in it's message.
4. Copy the resulting changeset URL/ID.
4. Go back to the note and close it with "closed with <changeset>". 

## What I want to do

1. I open id and enable notes view.
2. Check note and copy ID.
3. Change things and include the ID in it's message.

-> finished.

The note should be closed automatically and possibly automatically backlinked to the changset.
Just as GitHub does.

**Comment by rugk** [comment]
Ah just saw this came up before: https://github.com/openstreetmap/iD/issues/5170

I let you decide which issue to keep open. :smile:

**Comment by matkoniecz** [comment]
Note that #5170 was closed as wontfix.

**Comment by rugk** [comment]
Already commented there.

**Comment by quincylvania** [comment]
Hmm this is really something that OSM's servers should be handling. They host both the changesets and the notes, so it doesn't make sense that this feature would only work in a specific editor. That said, I don't see this happening server-side anytime soon so perhaps we can leave it in the iD queue.

**Comment by bhousel** [comment]
Yes, I already closed this issue.  I don't want to do this because OSM Notes are not like GitHub Issues.

GitHub Issues | OSM Notes
--- | ---
There are maybe a few thousand in a typical repo | There are millions of these in OSM
Human brains can easily hold an issue id like #6906 in working memory | Human brains are not built to remember numbers like note #1059466.  It's just too long of a number and people will mistype them.
Issues have a subject and body and can show the subject in a slick intellisense-style lookup control when you type them on GitHub | Notes are just a bunch of free text.  Can't show a summary or do an autocomplete or lookup when you are typing things in your commit message.
Closes on the server | Would require us to close it client side by issuing a bunch of API calls, and the changeset posting process is already kind of fragile
Everything starting with a # is an issue id | People use # for things like task ids already so we would have to be able to tell the difference between normal hashtags and a note ids

Also like @quincylvania said on #5170 - we really don't have a lot of developer time and resources to spend on things.  Sometimes the best thing to do is say "no" to features that aren't really essential and would be a huge effort to implement well.

**Comment by quincylvania** [comment]
@bhousel Thanks for the detailed perspective. I don't know much about the OSM notes system. Sounds like a good plan not to spend time on this.
