### ISSUE TITLE
Artefacts of a forest where there is no way/line

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#6910]
I don't think this is an important issue. And it might just be broken data and not an iD issue at all. Just wanted to let you know so you can decide on it.

At https://www.openstreetmap.org/edit#map=16/47.6576/12.5825 there are weird artefacts of the forest right through the screen.

![Bildschirmfoto 2019-10-03 um 15 02 42 Kopie](https://user-images.githubusercontent.com/111561/66128827-f496a000-e5ee-11e9-8e78-e1ef2b570def.jpg)

I guess it is likely a problem with this big relation https://www.openstreetmap.org/relation/6526682. But how does one debug this? The road relation debugger http://ra.osmsurround.org/analyzeRelation?relationId=6526682&_noCache=on does not help on this / or it does not have any errors.

**Comment by quincylvania** [comment]
@tordans This is a longstanding bug with multipolygons that aren't fully downloaded. iD can't render the area accurately because it doesn't know its full shape. I don't think there's a GitHub issue about it yet so I'll leave this open.

In v3 some members are downloaded when you select a multipoygon, but eventually we'll need something more comprehensive like #6656 to fix this. You can also manually download each member and watch the rendering correct itself piece by piece.

**Comment by bhousel** [comment]
yep this is #1201
