### ISSUE TITLE
Features with multiple type tags (eg amenity + shop) validation

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#6920]
[Originally ](https://github.com/osmlab/name-suggestion-index/issues/3079) raised over at NSI, this might be something for iD validation rules.
As far as I know, this only applies to fuel stations, where one possible tagging approach for an on-premises shop is amenity=fuel + shop=* on the same node/area. Of course, this creates issues in terms of rendering/processing (eg OsmAnd renders this as amenity=fuel, however shows the shop node in search results, with all the other tags from the amenity=fuel poi (ie opening hours, brand, etc)).

Where the branded feature is in the NSI, iD currently suggests this as non-standard tags (since it only expects amenity=fuel), removing the shop tag.

Would it be possible to tweak/add a validation rule, whereby iD suggests adding a separate shop=* node, possibly copying other tags from the main feature?

**Comment by matkoniecz** [comment]
Potential traps: 

`amenity=ice_cream` + `shop=ice_cream` (though I would personally eradicate `amenity=ice_cream`)

`amenity=cafe` + `shop=books` - some bookstores are trying to survive in this way

and probably other (http://overpass-turbo.eu/s/NiB may help to find them)

**Comment by tohaklim** [comment]
@matkoniecz this raises the question about acceptability of this tagging again - if eg Apple Maps allows multiple poi categories, should OSM do that too?

**Comment by matkoniecz** [comment]
For object that is both cafe and bookstore at the same time such tagging is perfectly fine. Is there any good reason why it would not be?

**Comment by 1ec5** [comment]
> As far as I know, this only applies to fuel stations, where one possible tagging approach for an on-premises shop is amenity=fuel + shop=* on the same node/area.

For what it’s worth, there are legitimate cases for a single feature to have multiple POI tags. These are cases where there’s no physical distinction between the different parts of the business, so it’s OK that a renderer chooses one of the relevant icons arbitrarily and all the secondary tags (like opening hours) apply equally to all aspects of the POI. For example, osmlab/name-suggestion-index#2234 describes a `shop=convenience` `amenity=ice_cream` chain. Such a business could be mapped as two separate POIs, but that would violate the “[One feature, one element](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element)” principle.

That said, `amenity=fuel` `shop=convenience` probably isn’t one of those strong cases for keeping the POI unified. iD effectively takes the position that a gas station and convenience store should always be separate POIs, since you have to go out of your way to create a POI that is both (by either editing raw tags or merging two POIs). A blanket warning about multiple feature tags would likely snag lots of types of combo businesses, but for the particular case of `amenity=fuel` `shop=convenience`, a warning could be appropriate.

> Where the branded feature is in the NSI, iD currently suggests this as non-standard tags (since it only expects amenity=fuel), removing the shop tag.

I think that’s happening is that iD detects a likely NSI brand based on the number of overlapping tags, and the NSI brand is associated with a particular preset, which iD tries to apply along with the NSI tags. If you manually create an `amenity=fuel` `shop=convenience` POI without any brand tags, then change the preset to “Gas Station”, iD does strip off `shop=convenience`.

Preventing dataloss of convenience stores would be ideal. Maybe a narrowly targeted warning about `amenity=fuel` `shop=convenience` could be somehow prioritized above the outdated tags warning?

**Comment by bhousel** [comment]
> Preventing dataloss of convenience stores would be ideal. Maybe a narrowly targeted warning about `amenity=fuel` `shop=convenience` could be somehow prioritized above the outdated tags warning?

Can't people just map them as 2 things?   I really hate when people pile a bunch of tags onto a single feature, expecting the software to just sort it all out.

I think mappers have no idea just how much trouble the "do whatever you want" tag system causes for us developers who need to actually make all this stuff work somehow.

And.. We've done so much with validation already, I kind of wish people would stop asking for special iD validation rules just so they can set the tags up some special way that doesn't work for the other things on the map.  Do we really need to write special rules for.. Gas station - Convenience stores?    Bookstore - Cafes?     And these Ice Cream Stand - Ice Cream Store things?   

I'm closing this just because I really don't want anyone to work on it.  It's ok to keep discussing, but I'm not really reviewing PRs anymore, and I don't want to see someone waste their time trying to build all these special rules just to have a PR sit and be ignored.. It's just too much for us. 

Please everyone stop being overly creative with the tagging.  Keep everything as simple as possible.  Worry more about whether the map is complete and less about whether it's perfect.

**Comment by 1ec5** [comment]
> Can't people just map them as 2 things? I really hate when people pile a bunch of tags onto a single feature, expecting the software to just sort it all out.

I think @tohaklim is asking for a way to alert mappers that they should map them as two separate things.
