### ISSUE TITLE
Don't trigger "show edits" mode when switching geometries with the "G" shortcut.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/iD#6950]
See title.

**Comment by quincylvania** [comment]
@BjornRasmussen Oh right, I forgot we already had this assigned in v3.

**Comment by quincylvania** [comment]
We're quickly running up against good keys to use for shortcuts. "Highlight Changes" (and possibly other future view modes) should theoretically be toggleable at any point, meaning the key can't conflict with any other shortcut. It should also be within reach of the wireframe key, W, since these features are useful in tandem. For now I changed the geometries shortcut to T, which is worse but at least it's available during drawing.
