### ISSUE TITLE
highway=bus_stop area displays like a linear residential road

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#6956]
https://www.openstreetmap.org/way/734228257

![Selection_002](https://user-images.githubusercontent.com/899988/67180784-e90eeb80-f3da-11e9-8098-3f9e8db69284.png)

Tagging in this bus station is a bit questionable (I just fixed `highway=residential` used for all roads there), but iD rendering in this case is quite confusing

**Comment by quincylvania** [comment]
@matkoniecz It looks like iD is ignoring the `highway_bus_stop` tag since that's only supported on nodes. The feature matches the Bus Platform preset since it has `public_transport=platform` + `bus=yes`. This preset can be either a line or an area so it requires `area=yes` to be an area.

Essentially #1828 would fix this. It would also help if iD didn't have to support two transit schemas at once.
