### ISSUE TITLE
uglify-js can't handle country-coder

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#7009]
Rollup uses country-coder's ES6 module but uglify-js doesn't support ES6. We have to reconcile this. 

https://travis-ci.org/openstreetmap/iD/jobs/606070667

**Comment by bhousel** [comment]
I've added the [rollup-buble plugin](https://github.com/rollup/plugins/tree/master/packages/buble) to our build process to transpile everything into ES5 syntax.  

So I think now we can probably _mostly_ write modern javascript in iD and not worry too much about the dependencies we are pulling in.   I'm ok with leaving PhantomJS as the test runner because 1. replacing it would be work, and 2. it remains a good proxy for whether something will run in IE11.

Check out the supported and unsupported feature lists:
https://buble.surge.sh/guide/#supported-features
https://buble.surge.sh/guide/#unsupported-features

**Comment by quincylvania** [comment]
@bhousel Awesome! It'll be so cool to support modern syntax going forward 👏
