### ISSUE TITLE
Advanced Stop Line preset.

### ISSUE THREAD

**Issue by doublah** [openstreetmap/iD#7014]
https://wiki.openstreetmap.org/wiki/Tag:cycleway=asl

Already has JOSM preset: https://josm.openstreetmap.de/ticket/10618

**Comment by quincylvania** [comment]
@doublah I've been trying to think of a descriptive name for this preset that isn't too long. I wouldn't expect most users to figure out what "Advanced Stop Line" means, but maybe that's okay. Perhaps "Bicycle Stop Line"? But then users might start using it for any line where a bike stops.

**Comment by BjornRasmussen** [comment]
I have only ever heard them referred to as "bike boxes".  https://nacto.org/publication/urban-bikeway-design-guide/intersection-treatments/bike-boxes/

**Comment by 1ec5** [comment]
[Advanced stop line](https://en.wikipedia.org/wiki/Advanced_stop_line) is a term of art for a feature that (as far as I know) doesn’t even show up in driver’s handbooks yet. It’s a specific kind of bicycle stop line that has different rules about right of way and signal timing. Either you live in a city that has them and you recognize that term, or you don’t and you don’t.

We name other presets with technical jargon, such as “Buffer Stop”. I think it would be fine to use “Advanced Stop Line”, as long as the icon suggests bikes rather than something like cars or buses. ASLs are popularly called “bike boxes” in the U.S., but I’m afraid that would be confused with bike lockers elsewhere or by translators.

**Comment by quincylvania** [comment]
@1ec5 Good points. Since "Advanced Stop Line" is what these are actually called then we should just call them that. Mappers who encounter these can either learn about them or ignore them. I added the preset.
