### ISSUE TITLE
Brand tag linking to non existend logo picture

### ISSUE THREAD

**Issue by fnordson** [openstreetmap/iD#7028]
brand=Rewe
brand:wikidata=Q16968817
brand:wikipedia=en:REWE

shows a broken image link: 

![rewe](https://user-images.githubusercontent.com/5624605/68403708-ab051c00-017d-11ea-838f-e42fa2cc519b.png)

File seems to link to: https://graph.facebook.com/Rewe/picture?type=large
The logo is also available here: https://de.wikipedia.org/wiki/Rewe_(Markt)

**Comment by scaidermern** [comment]
@developers:
Is it really necessary to tell Facebook about an OSM user currently editing a supermarket? Can you please remove this nonsense? Either host these images on your server or just use a generic icon. But stop linking to Facebook and similar organizations. Respect our privacy, please.

**Comment by bhousel** [comment]
I've seen this reported a few times.. What's probably happening is either your browser or a plugin is blocking the call to facebook to get the image.

We are going to:
* add an `onError` handler to show the fallback preset image
* add an option so that users can disable the brand icons

@scaidermern Please be nice.  Features that give users feedback and improve the quality of the data in OSM are not "nonsense".  Maybe you should have more respect for the work that the maintainers have put into making iD a good editor.

**Comment by scaidermern** [comment]
> @scaidermern Please be nice. Features that give users feedback and improve the quality of the data in OSM are not "nonsense". Maybe you should have more respect for the work that the maintainers have put into making iD a good editor.

I didn't had the intention to insult anybody. iD is indeed a great editor and makes editing really easy for new mappers. However there is no need to link to such external resources and to undermine user's privacy. People aren't expecting automatic calls to Facebook in the background when firing up their OSM editor.

**Comment by bhousel** [comment]
> However there is no need to link to such external resources and to undermine user's privacy.

How do you think the background imagery works?

**Comment by scaidermern** [comment]
> > However there is no need to link to such external resources and to undermine user's privacy.
> 
> How do you think the background imagery works?

The same way. However the user is able to choose which aerial imagery to use.

**Comment by fnordson** [comment]
> I've seen this reported a few times.. What's probably happening is either your browser or a plugin is blocking the call to facebook to get the image.

I agree this is probably it. 

I also agree with @scaidermern on the privacy issue especially because there are better sources and the facebook ping is really unnecessary.

**Comment by bhousel** [comment]
> because there are better sources

What are the better sources of "all the logos for all the brands in the world"? 

> the facebook ping is really unnecessary.

Sure, I mean, all of this is unnecessary, when you really think about it.

**Comment by fnordson** [comment]
> > because there are better sources
> 
> What are the better sources of "all the logos for all the brands in the world"?

The logo is also available here: https://de.wikipedia.org/wiki/Rewe_(Markt)

> Sure, I mean, all of this is unnecessary, when you really think about it.

Please be nice. Features that give users feedback and improve the quality of the data in OSM are not "nonsense". Maybe you should have more respect for the work that the maintainers have put into making iD a good editor.

;)

**Comment by bhousel** [comment]
Look guys.  Today I would just be happy to get this project building again. 

The build is broken, I'm burnt out, and I don't even want to work on it anymore.  I don't have the energy to debate you all on whether it makes sense to fetch logos from Facebook.  I don't like doing this work anymore when it's just become me fixing broken stuff, putting out fires, and responding to unhelpful critics who contribute nothing.  This is an Open Source project and I don't owe you anything. 

If you want to compare logo coverage, check out https://nsi.guide and you'll see that the Wikidata logos are not a sufficient replacement for what we get from Facebook.  (I've put a lot of work into that project too, for what it's worth).

**Comment by bhousel** [comment]
Also please stop editing your comment.  The NSI contains about 4000 entries, and if your browser is blocking Facebook, they will all show up with no images.  You don't need to enumerate the list of all of them.

**Comment by quincylvania** [comment]
I made it so that the vector preset icon is shown if the image fails to load:

<img width="399" alt="Screen Shot 2019-11-07 at 8 11 39 PM" src="https://user-images.githubusercontent.com/2046746/68419711-10b3d100-019b-11ea-9397-9ec7cba45664.png">

**Comment by Bibi56** [comment]
Thanks  @quincylvania for that.
> I'm burnt out, and I don't even want to work on it anymore. I don't have the energy to debate you all on whether it makes sense to fetch logos from Facebook. I don't like doing this work anymore when it's just become me fixing broken stuff, putting out fires, and responding to unhelpful critics who contribute nothing. This is an Open Source project and I don't owe you anything.

Right, you owe something to MapBox and that maybe an issue. Not that working for MapBox is an issue, but that you may loose the contact to the community to make the editor the community wants.
Before developing a feature think about the way this feature can be wanted or offending the community. Otherwise you get what you take as a rough comment. Don't forget the last word of @scaidermern: _please_.

So you think that displaying the logo of a company helps finding the right name.
You check the coverage for logos and you discover that Facebook has the best coverage.
So you want to use that.
Until now, nothing wrong as such.
But you missed to take into account the privacy concern.

iD is used on OpenStreetMap.org and therefore needs to reflect the will/wishes of the community.
Privacy concern, probably more in Germany and France than US is an important topic.
Solutions for that exist: calls to a proxy, hosted for instance by the foundation.
That way you can move forward, not loosing your energy or will in dealing with stuff you don't want to deal with.
Make a break and come back in a good mood, full of energy.

**Comment by ImreSamu** [comment]
@quincylvania :
>I made it so that the vector preset icon is shown if the image fails to load:

imho: 
* the current solutions ( == _"vector preset icon"_) is just a fix for the "word trademark" ;  and we need to find a solution for the "Figurative trademark" problem; 
* it is not an easy problem ... 

just a side note:
* Trademarks and Branding is hard and complex topic.
* as I know 2 big brand type exists  ( http://www.trademarks-blog.eu/word-or-figurative-trademark/ )
   * **"Word trademark"**  ( name is unique )
   * **"Figurative trademark"** ( name is **NOT unique** ; company logo is important!  )

My Example for "Figurative trademark"  ( ~ "Logo Brand" ) is `"amenity/cafe|Caffè Nero" `   
*  https://github.com/osmlab/name-suggestion-index/issues/2116#issuecomment-432225810
In Hungary other `"amenity/cafe|Caffè Nero" ` exist, 
so without a company logo - the osm contributors injecting ["false positive"](https://en.wikipedia.org/wiki/False_positives_and_false_negatives) brand data ..   



disclaimer:
 *  I am biased in this topic  - because I am part of the local community data quality team.  

> A picture of a cute animal (not mandatory but encouraged)

![image](https://user-images.githubusercontent.com/2217320/68660075-ca62c700-0538-11ea-858f-4c9ae38a72aa.png)
( [image source](https://pixabay.com/photos/beach-puppy-dog-finnishlapphund-1790049/)  )
the [docker project](https://github.com/moby/moby/blob/master/.github/PULL_REQUEST_TEMPLATE.md) has a best practice - protecting the maintainers/readers emotions  ...  (  ~  _"A picture of a cute animal"_ )  Maybe we need a similar solutions ...  
We need a a cute factor for the heated debate.

**Comment by pyrog** [comment]
> Solutions for that exist: calls to a proxy, hosted for instance by the foundation.

👍

**Comment by pyrog** [comment]
Logo could be imported to wikidata ?

2081 [brand](https://www.wikidata.org/wiki/Q431289)s and 207 brands with logo (with various quality) https://w.wiki/Bvs
