### ISSUE TITLE
CTRL+V tool skews new line placement

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7114]
Copying a line with CTRL+C and then immediately pasting without moving the cursor places the copy on the map, but skewed:
![16346-2](https://user-images.githubusercontent.com/1230959/70754569-7c78f300-1d72-11ea-9b58-6025cce972db.jpg)

Perhaps this is intentional (so one can clearly see the copied line), but makes it impossible to e.g., make a ridgeline trail the basis for a county boundary.

If we didn't move the cursor then it should drop the new copy exactly on the same spot.
We can still move the new copy with our mouse, or click to drop it right there.

**Comment by jidanni** [comment]
Same I suppose for points, areas.

**Comment by jidanni** [comment]
Apparently iD is somehow using the center of the line, assuming the user wants to grab that.
Anyway, using one's best efforts to place it back where it was, one gets:
![13226-3](https://user-images.githubusercontent.com/1230959/70754684-cd88e700-1d72-11ea-8734-d4d3c2c65a7b.jpg)
So moving it around by hand is bound to fail, as one cannot just make the whole new line snap to the underlying line.

**Comment by quincylvania** [comment]
@jidanni Yes, this is intended. The pasted feature is centered on the mouse cursor, wherever that may be, so the user can then click to place the feature. There isn't a "duplicate in place" operation since most features don't overlap exactly in the real world, and even if they do it makes them difficult to manage if they're mapped that way. I recommend one of these alternatives:

- Place the pasted feature approximately in the same place. OSM data doesn't need to be super precise
- Use a relation to represent the boundary using the existing trail as a member
- Use an editor like JOSM for advanced stuff like this

**Comment by jidanni** [comment]
> most features don't overlap exactly in the real world,

Indeed.

> and even if they do it makes them difficult to manage if they're mapped that way.

Indeed. If ever needing to detach them it might require node by node work (I don't know.) 

> * Place the pasted feature approximately in the same place. OSM data doesn't need to be super precise

(100 years from now: regret.)

> * Use a relation to represent the boundary using the existing trail as a member

Very good idea (except when [the trail is not the legal boundary definition](https://help.openstreetmap.org/answer_link/72094/)).

> * Use an editor like JOSM for advanced stuff like this

Can't! Its hardwired reverse mouse mappings mess up my _muscle memory_ for a month.

OK, I just ended up using a loose approximation (one node instead for each five).
