### ISSUE TITLE
Add second-hand clothes shop preset

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7164]
Because we don't use **shop=second_hand** or **shop=clothes +clothes=second_hand** for second-hand clothes shops, we need a preset for it:
"shop=clothes + second_hand=only"
There are over 1,415 such features on OSM: https://overpass-turbo.eu/s/PdO

**Comment by quincylvania** [comment]
Hi @maro-21, welcome 👋

So iD already has a "Sells Used" field for any kind of shop to specify this tagging. I think it'd be simplest for people to use the field rather than add more presets, though perhaps common secondhand good types like clothing and cars would make sense? What do you think?

![Screen Shot 2019-12-26 at 4 33 11 PM](https://user-images.githubusercontent.com/2046746/71491284-d7dcc380-27fd-11ea-8623-ad5a9dbc2322.png)

**Comment by maro-21** [comment]
But people don't know about it and they map such shops adding `clothes=second_hand`. So the idea of this preset was to prevent such tagging. After adding it we can deprecate presets like `clothes=second_hand` and suggest correct tagging.

It is common to mismatch tags: https://www.openstreetmap.org/node/5757255270/history

If we have a preset Underwear Store, why not this one?
Underwear Store [`shop=clothes` + `clothes=undearwear`] is easier to tag, but for second-hand clothes shop there are three possible ways to tag it.

**Comment by quincylvania** [comment]
@maro-21 Okay, you convinced me! I added Secondhand Clothing Store and also Used Car Dealership.

**Comment by maro-21** [comment]
Thank you :)
