### ISSUE TITLE
Add fields for attraction=animal

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7210]
Add fields `barrier=` and `species=` for `attraction=animal` because they are commonly used with it.

`attraction=animal`: 13411 uses
`attraction=animal` + `barrier=`: 1780 uses
`attraction=animal` + `species=`: 757 uses

https://taginfo.openstreetmap.org/tags/attraction=animal#combinations

**Comment by quincylvania** [comment]
Hmm using `barrier` on areas like this is a bit of a hack and I don't think iD should encourage it. Fences and walls can be mapped separately.

And iD already has a `species:wikidata` field for tagging species information, so a `species` field would appear redundant.

**Comment by quincylvania** [comment]
Yeah I don't see us adding either of these, sorry!

**Comment by maro-21** [comment]
Ok, perhaps `barrier` is not a good idea. It is probably used in zoos where animals are tagged as an area and `barrier` is added to save time without adding another feature with the same geometry.

`species:wikidata` is just a "link" to wikidata
`species=` is a tag to write a latin name for species

And I think we need `species`, to add `species:wikidata`, like we need `brand` to add `brand:wikidata` and they are not the same.
`species` is for human beings while `species:wikidata` is for computers...

Looks like we're not using the key `species=` anywhere in iD! Neither with animals nor with plants. But it is used over 1 million times! https://wiki.openstreetmap.org/wiki/Key:species

**Comment by bhousel** [comment]
> species is for human beings while species:wikidata is for computers...
> Looks like we're not using the key `species=` anywhere in iD! Neither with animals nor with plants. But it is used over 1 million times!

I don't really agree that "`species` is for human beings".. It's not a very easy-to-understand tag.

Some of what follows is my thinking, and it goes back years, and doesn't really matter anymore since I am not deciding things on iD.  But it might be helpful to explain why things are the way they are.

I traditionally avoided adding fields for things like `species` and `genus` to iD because most casual mappers are not really able to fill these in, and advanced mappers or botanists can use the raw tag editor for this.  There is some discussion on #4240 about it.  I would rather not introduce a field if it is likely to confuse people.. Worst case, people actually start using the field enthusiastically and fill it with wrong data.

Also, I don't think tag usage count is a very good metric for whether something should be included as a field.  We should be optimizing for user experience, and particularly for users who are new to mapping, or casually interested in OpenStreetMap.  Many tags have inflated usage because of imports or other campaigns, and that doesn't make them good tags.

Adding too many fields and presets works against this goal of being a friendly editor for new users because:
- all those things take up space in the UI and cause cognitive load.. (I have seen new users get frustrated trying to fill in everything in the sidebar).
- all those things really should be localized/translated for users of different abilities everywhere..

**Comment by quincylvania** [comment]
I agree with Bryan here.

The Species Wikidata field is much simpler than would be a `species` field since users can just type the name of the thing in their local language. Data consumers can use the Wikidata API to get nice labels and linked attributes.

![Screen Shot 2020-01-10 at 9 29 59 AM](https://user-images.githubusercontent.com/2046746/72160167-e09bd080-338b-11ea-8ea9-fe2ef8d1a01f.png)
