### ISSUE TITLE
shop=tailor and craft=tailor

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7218]
Currently we have `shop=tailor` and `craft=tailor` which have the same name "Tailor" and the same icon. It's hard to tell them apart.

Can we also change the icon for `craft=dressmaker` for something that looks like a dress? (if available)

**Comment by quincylvania** [comment]
So these are two competing tags for essentially the same feature type. iD only supports adding `shop=tailor`, which is the older and somewhat more common tag. The `craft=tailor` preset is still there in case mappers come across it. The icon, name, and fields are the same since they're the same thing.

The only real solution I see is to deprecate one of the values, which would require someone to spearhead a proposal.

**Comment by bhousel** [comment]
`craft=tailor` already is deprecated, and has been for as long as I can remember.
It's only in iD as an unsearchable preset.

**Comment by bhousel** [comment]
I added https://github.com/ideditor/temaki/issues/50 for a new dress icon.

**Comment by bhousel** [comment]
oh wow, check it out:
https://wiki.openstreetmap.org/wiki/Talk:Tag:craft%3Dtailor

From 2015-2016 the `craft=tailor` page redirected to `shop=tailor`.  I always thought it was deprecated and then.. people un-deprecated it?  what a mess.

yay osm  😅

**Comment by maro-21** [comment]
Ok, I see.

I noticed presets with the same name on Transifex and there is no information that one of them is hidden :]
One of them is unsearchable so it shouldn't be a problem.
