### ISSUE TITLE
Validation: suspicious name "baguette"

### ISSUE THREAD

**Issue by MarkusGaugg** [openstreetmap/iD#7246]
For some time now, iD has been showing the following warning for cafes called baguette:
Café has the suspicious name "Baguette"

This warning should be removed because there is a larger company in Tyrol called Baguette.
https://www.baguette.at/

**Comment by MarkusGaugg** [comment]
The same warning is also displayed here: shop:bakery

**Comment by quincylvania** [comment]
Hi and welcome @MarkusGaugg 👋

iD gets the data for these warning from the [name-suggestion-index](https://github.com/osmlab/name-suggestion-index), which handles branded businesses. You can open an issue about adding the Baguette company to the index so these features can be upgraded to use uniform tags instead of flagged 👍

**Comment by quincylvania** [comment]
> And thank you for constantly developing the iD Editor.

@MarkusGaugg It's my pleasure! (and my job 😁)
