### ISSUE TITLE
Have "barrier" field always shown on some types of areas

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7271]
There are some types of areas where I always find myself having to "Add field" and add the "barrier" tag. These are Preschool/Kindergarten grounds and Construction area, but I'm sure there are other areas too that are almost always fenced in.

In these types of areas it would be very helpful if the "barrier" tag was not hidden under the "Add field", but was just shown among the regular fields.

I'm not saying to add this ass a standard field to all types of areas, just the types of areas where you _almost always_ should add this tag.

Thanks again for your hard and important work! :)

**Comment by quincylvania** [comment]
@forteller I'm assuming you mean you add the tag under "All tags"? We don't have a field for barriers on areas and I don't think we should add one. This pattern of mapping runs against ["one feature, one element"](https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element) since the barrier and landuse are two different things. We can't expect all data consumers to support it.

Sorry, I know it's convenient to map this way!

Related: #7210

**Comment by forteller** [comment]
Why can we add things that shouldn't be added?

Anyways: My suggestion then is to still do what I said in this issue, but in addition make sure that any time anyone adds a feature in a way they're not supposed to, that iD automatically separates that feature out into its own element.

**Comment by quincylvania** [comment]
> Why can we add things that shouldn't be added?

Good question! The OpenStreetMap database lets mappers use whatever tags they want. This leads to conflicting patterns of mapping, some of which are long-running unresolved debates. That's just the nature of the project. With iD we aim to encourage patterns that are easiest to understand for both mappers and data consumers.

> make sure that any time anyone adds a feature in a way they're not supposed to, that iD automatically separates that feature out into its own element.

We can't do this automatically since some mappers map this way intentionally. We're thinking about general-purpose tools that would make it easier to attach ways together, like #1614 and #6784.

**Comment by forteller** [comment]
> We can't do this automatically since some mappers map this way intentionally.

But you're saying they shouldn't. I don't get this… :D 

But anyway: How about a popup or something saying "We noticed you added an extra feature to this element. This is discouraged because [link to more info]. Would you like to automatically split these features into separate elements? [Y/n]"

**Comment by quincylvania** [comment]
> But you're saying they shouldn't. I don't get this… :D

Yep, iD lets mappers do all kinds of things that we wouldn't necessarily recommend 😆

> How about a popup

We could potentially add a validation issue that flags this pattern. But that opens the door to controversy and so could come at a high emotional cost 🤷‍♂️
