### ISSUE TITLE
checking of conflict object link  

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7330]
The object link which is provided during conflict resolution question sends me to page:
https://www.openstreetmap.org/id#background=EsriWorldImageryClarity
instead of (as assumed) to the osm object which is in charge.

![resolve confict](https://user-images.githubusercontent.com/47290585/73835444-b106a980-480d-11ea-8648-dcd8e248b963.jpg)

**Comment by quincylvania** [comment]
The reason clicking the label doesn't appear to do anything is that iD can't actually select a feature while resolving conflicts. Instead, it's centering the map on the focused feature. But if iD has to zoom too far out then nothing would display. I changed it to render the focused feature at any zoom level, which hopefully fixes some of the confusion.

The conflict resolution UI has lots of room for improvement, but it doesn't get much attention since most users rarely see it.
