### ISSUE TITLE
Mapillary Date Filter

### ISSUE THREAD

**Issue by zlavergne** [openstreetmap/iD#7342]
I'm working on adding a date filter to the Mapillary layer. The plan is to use a calendar date picker similar to the Mapillary web app. I'm thinking it will live inside the current Mapillary box of the `Photo Overlays` list. 

I should have an initial version next week to show off and make sure we're all on the same page of how this will look.

**Comment by tordans** [comment]
Hi @zlavergne this sounds like https://github.com/openstreetmap/iD/issues/4518, right?

Personally, I will be very happy with any kind of filtering!

Just as a suggestion, I wonder if a calendar date picker is even the easiest (first) step.
My personal use cases are all about reducing the clutter of too many images, like …
- only show recent images – last 30 days, last 12 month, last 3 years
- only show images from specific users (only me, only someone; this is https://github.com/openstreetmap/iD/issues/5307)
- ideally there where a "only show images that are taken from sidewalks, not streets – but AFAIK this is not a filter the API provides

But back to the date picker: In my mind the pre defined selections would be faster to choose than the date picker and less complexity. – Depending on the UseCase you have in mind of course.

**Comment by cbeddow** [comment]
JOSM uses this:

> only show recent images – last 30 days, last 12 month, last 3 years

This we've found is not feasible for many users, who need a specific date ranger.

> only show images from specific users

The username filter will be great, but lower demand. 

> ideally there where a "only show images that are taken from sidewalks, not streets

A lot of backend on the Mapillary side to first classify the images this way, based on content and GPS, not reliable to do for now. :) But would be really good.

**Comment by quincylvania** [comment]
#4518 is indeed photo date filtering, but I'll leave this open since Zach seems to be working on something specific to Mapillary.

> >     only show recent images – last 30 days, last 12 month, last 3 years
> 
> This we've found is not feasible for many users, who need a specific date ranger.

I could see how mapping teams might need to see a specific date range, but most iD users just need the photo overlay filtered down to a manageable amount of data. Date pickers are finicky and aren't useful if you don't know beforehand what dates to enter. Filtering by the previous 30/90/365 days is simpler but is blind to the actual data clustering.

I think my preferred solution is a dropdown for filtering to the most recent 1/2/3/5/10 capture sequences in the visible map area. This could be set to something low by default so mappers don't get sequence spaghetti right away. Then we could consider date filtering (or even just filtering to specific sequences) as an advanced option.

**Comment by cbeddow** [comment]
We will test some prototypes and share results!

**Comment by tastrax** [comment]
Hi folks - any movement on this added functionality yet? I would love to be able to reduce the spaghetti effect in popular areas.

**Comment by nickplesha** [comment]
Hi, you can try the date filter in this PR: https://github.com/openstreetmap/iD/pull/7847 let me know if you have any feedback or suggestions.

**Comment by quincylvania** [comment]
https://github.com/openstreetmap/iD/issues/4518#issuecomment-712434240
