### ISSUE TITLE
 Failure when checking "use desktop site" in mobile browser

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7365]
On a cellphone, in the menu of my browser, I checked "use desktop site."

Then, I used iD. However it just doesn't fit inside the window. It should, but it doesn't.

Sure, you might say we do not support cellphones. However I'm not asking you to support a cellphone. I'm just asking you to work correctly when the user picks use desktop site. Thanks!

**Comment by quincylvania** [comment]
> it just doesn't fit inside the window. It should, but it doesn't.

@jidanni Hmm it really shouldn't fit because you told you phone not to scale the UI to the mobile screen size.

> I'm just asking you to work correctly when the user picks use desktop site.

This isn't simple. Making the desktop site work on mobile is the same as building a mobile-responsive site. We aim to continue improving mobile support but a complex app like iD can't just magically work on a phone-sized touchscreen.

**Comment by jidanni** [comment]
All I know is if I do the same thing with www.facebook.com it looks just the same as it does on a giant desktop screen. Of course everything is extremely tiny but that's a choice that I accept.

**Comment by jidanni** [comment]
Of course, if I don't check the box that says use desktop site, then Facebook becomes aware that I'm not really using a giant desktop, and instead tries to accommodate to my mobile device.

**Comment by quincylvania** [comment]
Facebook has a totally separate mobile implementation (https://m.facebook.com), while openstreetmap.org has a single responsive site instead. This is why the "request desktop site" feature works differently.
