### ISSUE TITLE
Delete a big polygon

### ISSUE THREAD

**Issue by ghost** [openstreetmap/iD#7369]
I have some big object (forest), which is a duplicate. I'm sure about it, since I created the mistake.
I can’t delete the object because not enough is visible.
If I scroll out, I can’t delete it, because it says “zoom in to edit”

Therefore: The marked object should always be unlocked for editing.

**Comment by ghost** [comment]
I can't fix the headline error. The edit button doesn't work.

**Comment by quincylvania** [comment]
Hello and welcome, @MaestroGlanz 👋

So iD purposely prevents certain edits to large features in order to reduce vandalism and consequential accidents. We don't want it to be easy to delete Hawaii, for example.

As a workaround, you can delete the individual nodes of the polygon until it is small enough to delete entirely.
