### ISSUE TITLE
Zoom out button 

### ISSUE THREAD

**Issue by sahithiduddukuri** [openstreetmap/iD#7399]
A button same like Zoom in to Edit is there any posibility to create Zoom out after edit. Once zoom out button check it should revert back to basic location(2.00/0.0/0.0)

![zoom-out](https://user-images.githubusercontent.com/22541694/75516236-f50e5800-5a21-11ea-9688-4305fa2ed8cf.png)

**Comment by bhousel** [comment]
Let's talk about zooming!

I've noticed a lot of chatter about the "zoom in to thing" and "zoom out of thing" features.

I introduced this "zoom in to" button in #5169, so that people could focus on a specific geometry, or note, or QA issue.  I wanted a kind of universal "focus on a thing".  Maybe I should have called it "focus" instead of "zoom".

My ideal workflow would be to be able to hover or select things, then press a single key to _focus_ on that thing.  Then press an adjacent key to _unfocus_ which would just pop the view back to whatever it was before focusing.  What I am really talking about is implementing a view stack that can be pushed and popped to (if you use shell commands, think like `pushd` and `popd`).  This is what I wanted to implement but didn't have time.

I don't think users regularly want to unzoom out to 2/0/0.  I also was pretty against the idea of adding UI buttons for everything, but maybe we could work in something like this without it being annoying.  

I personally don't like the existing ➕ and ➖ zoom buttons (it would be great to not add any more buttons like these), and I'm not sure whether anyone even uses these anymore over just plain old mousewheel scrolling or pinch gestures. For comparison, I like the design of Apple's map navigation controls that hang out in the bottom corner out of the way:

<img width="226" alt="Screenshot 2020-02-28 09 55 16" src="https://user-images.githubusercontent.com/38784/75558897-7ceb6680-5a10-11ea-8d03-c67f4736fd2a.png">

**Comment by quincylvania** [comment]
@bhousel There was some discussion of a navigation stack in #6783. I'd agree it'd be great to avoid adding more buttons. One idea is to use the browser's navigation stack for this, but I'm not sure how that'd work on sites where iD is embedded.
