### ISSUE TITLE
Warn about placing a surface marker as member of underground pipeline or cable

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/iD#7402]
Dear maintainers

Markers are currently mapped as nodes with marker=* key. They often warns about the presence of underground infrastructure.
Wiki states it's not recommended to map those markers nodes as members of underground pipeline or cables ways.
​https://wiki.openstreetmap.org/wiki/Key:marker
​https://wiki.openstreetmap.org/wiki/File:Guideline_markers_underground_pipelines.png

Is it possible to add a validation warning please, when a marker is part of a way with
man_made=pipeline + location=underground
power=cable + location=underground

There is no problem for markers to be members of pipelines/cables ways when such pipeline is overground and the marker is installed directly on it.
When pipelines are underground, markers aren't directly linked nor involved in operation (like a valve can be for instance) so the node should be added apart.
(it would be weird to get the marker buried with the pipeline it is supposed to warn about)

Thanks in advance

**Comment by bhousel** [comment]
This seems overly nitpicky.. Can’t consumers (if there even are any) just assume that the markers for underground things are visible?  

Having different rules for whether or not they should be connected puts extra burden on everyone - mappers and developers.

**Comment by flacombe** [comment]
I would agree if pipelines were always right under their markers.

This is often not true actually, markers may be located a few meter away the danger they refer to.
Encouraging to split nodes between underground and surface features is done as to prevent to merge them for wrong reasons. Markers may be retrieved with RTK or GPS on ground while pipeline geometries can be obtained from other odbl complient official sources.

**Comment by bhousel** [comment]
I'm ok with:
* "Markers should be connected to pipelines."
* "Markers should not be connected to pipelines."
* "We don't care whether markers are connected to pipelines or not." (best)

I have a problem with:
* "Markers should be connected to pipelines when they are aboveground, and markers should not be connected to pipelines when they are underground"

I did not build a validator into iD so that we could nag our users over petty stuff like this.  Is it possible to design marker tagging in a way that makes mapping easy for humans and still satisfies the goal of saying where the markers are?  

I feel like we don't have this problem with railway or waterway mileposts - maybe look to those established tags for inspiration.

**Comment by flacombe** [comment]
> I'm ok with:
>     * "Markers should not be connected to pipelines."

If you look at wiki, that's precisely what is explained
https://wiki.openstreetmap.org/wiki/Key:marker#Common_Values

This picture : https://wiki.openstreetmap.org/wiki/File:Guideline_markers_underground_pipelines.png

If it cause too much problems to iD to distinguish between underground and overground, we'd better always warn about a marker as a member of pipeline.

> I feel like we don't have this problem with railway or waterway mileposts - maybe look to those established tags for inspiration.

Most traffic signs I map are always beside the highway or railway.
Placing a milestone in the middle of the road could cause harm to incoming vehicles I think.

**Comment by flacombe** [comment]
As this issue has been clarified and now focused on "Markers should not be connected to pipelines.", could it be reopened please ?
