### ISSUE TITLE
Add a capitalized case converter button in name fields

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#7405]
The OSM Wiki says "Use mixed case with the first letter of each word capitalised, e.g., Church Street, not Church street." (https://wiki.openstreetmap.org/wiki/Names)

A common mistake is to use All Caps (UPPERCASE), so now to fix that one must manually rewrite the name.

Please consider adding a button in the name fields to convert case to mixed case (Capitalized Case).

Suggested button icon: https://fontawesome.com/icons/font-case?style=regular

**Comment by mfbehrens** [comment]
I really like this idea. But I think we have to be careful because this applies not to every name. Right next where I live there is the "DVLA Road". This is an abbreviation for Driving Vehicle Licencing Authority and it should not be spelled "Dvla Road". So I think users have to be aware of cases like that.

**Comment by bhousel** [comment]
> But I think we have to be careful because this applies not to every name. Right next where I live there is the "DVLA Road". This is an abbreviation for Driving Vehicle Licencing Authority and it should not be spelled "Dvla Road". So I think users have to be aware of cases like that.

Yeah I think the number of exceptions to this rule makes it a bad idea.  I think a better place for something like this to live would be if we someday made a dedicated tag cleanup tool separate from iD.
