### ISSUE TITLE
add check_date to some more presets

### ISSUE THREAD

**Issue by Elefant-aus-Wuppertal** [openstreetmap/iD#7414]
Hi,
my idea is to add the check_date field to some presets where things often change quickly, for example many public telephones get removed in these days. Due to this, it would be very great for people too see directly how actual the data are and when the last survey was, so mappers get more encouraged to add this information when the check_date-field is there.

**Comment by quincylvania** [comment]
@Lukas458 Hmm are people really doing this kind of mapping in iD? Almost any feature could have `check_date` but it's pretty advanced to go out surveying based on this tag. I think most iD mappers are just tracing imagery and adding stuff they know from memory.

**Comment by maro-21** [comment]
I agree with quincylvania.
I think it won't be changed often. I know from experience that people don't change this tag even if they update the data.

But I think we can add `check_date` to bus/tram routes - these are the features I used this tag with. Check date here is good because even if the bus route hasn't changed, people often cut roads so it's necessary to check routes from time to time because there might be gaps.

**Comment by quincylvania** [comment]
> Check date here is good because even if the bus route hasn't changed, people often cut roads so it's necessary to check routes from time to time because there might be gaps.

I suppose,  but `check_date` isn't really the best way to manage these. Someone could say "yes, the route still exists" and update `check_date` without looking for gaps. This tag isn't really all that useful because people can interpret it differently. Because of this, I wonder if making it more prominent in iD could be more problematic than helpful. I'd say people can just use the raw tag editor for this for now…
