### ISSUE TITLE
Use ID to update local Nominatim database

### ISSUE THREAD

**Issue by bidabil** [openstreetmap/iD#7417]
Hi, 
We want to make an application used by many people who update our local Nominatim database. 
Can we link ID to our local Nominatim database and use it for updating?

Thanks a lot

**Comment by quincylvania** [comment]
Hi, @bidabil. I'm not 100% sure what you're asking since I don't know a lot about the Nominatim architecture.

You can point iD to any implementation of the OSM API, including a local one: https://github.com/openstreetmap/iD/blob/41e58dc32ed10e2585f25dd5e85b24900e7a182c/index.html#L51

iD also has the ability to generate OSM changefiles from the active changeset, but it might take some hacking to use this for your purposes: https://github.com/openstreetmap/iD/blob/41e58dc32ed10e2585f25dd5e85b24900e7a182c/modules/osm/changeset.js#L50

Hope that helps!
