### ISSUE TITLE
Validator considered harmful

### ISSUE THREAD

**Issue by hungerburg** [openstreetmap/iD#7443]
The yellow warnings that appear, when there is something wrong in the area, offers to "ignore". I understand the policing behind the validator, yet psychologically this can be counterproductive. Looking at changesets by ID users, they e.g. create fords in wrong places. Probably just to please the validator.

The "ignore" option should be given some boost, at least a statement, that it is not a shame being "ignorant" or something like "if uncertain, pick ignore".

**Comment by manfredbrandl** [comment]
„if uncertain, pick ignore„ seems a good idea, similar to „if unsure, leave blank“.

**Comment by quincylvania** [comment]
@hungerburg I think I understand what you're getting at, but I don't see a problem with the existing UI.

<img width="358" alt="Screen Shot 2020-05-18 at 12 51 56 PM" src="https://user-images.githubusercontent.com/2046746/82239436-c019ef00-9906-11ea-86c9-1bde59ea3bbe.png">

If a mapper picks an incorrect fix, I'd say it's probably because they think it's correct, not because they're afraid of ignoring issues. iD doesn't shame anyone's lack of mapping knowledge—if someone's afraid of appearing ignorant then I'd look at the community's treatment of new mappers instead.
