### ISSUE TITLE
"Add a bridge" suggestion missing if stream is selected

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7447]
Here we see the user will miss the very important option to "Add a bridge", depending on which of the two items is selelcted.
![27485-1](https://user-images.githubusercontent.com/1230959/77271500-dbdb8d00-6ce9-11ea-9252-2eee08a190fe.jpg)
![7498-0](https://user-images.githubusercontent.com/1230959/77271514-e433c800-6ce9-11ea-879a-e5b12bf7b7ab.jpg)

**Comment by maro-21** [comment]
As you can see it creates a tunnel or bridge on the selected feature.
It's because a stream can be in a tunnel but not on a bridge...
A road can be on a bridge but... Why tunnel is here? I don't think there are roads under a ditch ;). Even if there are, this is very rare case so this option shouldn't be here.
So there is no missing "add a bridge" but rather "add a tunnel" should be removed.

To not open a new issue:
I would like to suggest reorder "Connect using a ford" and "Add a tunnel" to the following order:
1. Add a tunnel - because this is the most common case. Ditches/streams are usually under the road
2. Connect using a ford - this one shouldn't be on the first position. Before renaming this field from "Connect" to "Connect using a ford" many people using iD connected streams with roads and created many non-existent fords.

**Comment by quincylvania** [comment]
> It's because a stream can be in a tunnel but not on a bridge...

Right. Aqueducts are possible in OSM but uncommon.

> A road can be on a bridge but... Why tunnel is here? I don't think there are roads under a ditch ;). 

Huh, I hadn't thought about this before but it's a good point. Tunnels under waterways are also fairly uncommon.

> Connect using a ford - this one shouldn't be on the first position

Maybe. There are many types of crossing issues where connecting is the desired solution, e.g. road/path, and it's nice to keep the order consistent.

> To not open a new issue

It's okay to open a separate issue if the concern is different than the original post.

**Comment by jidanni** [comment]
All I know is when uploading an edit with nearby missing tunnel/bridges, we get warnings. It seems to always give us the stream's warning  instead of the road's warning.

This is too bad, because where I live these all should be fixed with bridges, not tunnels.
(Bridges are [cheaper](https://en.wikipedia.org/wiki/Bridge%E2%80%93tunnel) for municipalities than tunnels.)

So I must remember to click the road, to get the bridge solution suggestion.

**Comment by quincylvania** [comment]
> All I know is when uploading an edit with nearby missing tunnel/bridges, we get warnings. It seems to always give us the stream's warning instead of the road's warning.

Ah okay, you're trying to add a road bridge instead of a stream tunnel, not a road tunnel.

An issue like this is shared by multiple features but the fixes are specific to the selection. When clicking an issue in the issues list, one of the features is arbitrarily selected. #5897 would make it possible to choose which feature to select.

**Comment by jidanni** [comment]
Well all I know is the warning system should say
"A stream crosses a road.
Add a bridge?
Add a tunnel?
Add a ford?" etc.

The average user is not going to double check which of the two items iD has arbitrarily selected, and hence will always miss out on some valid solution options. (And like me, create lots of tunnels thinking it was the only proper choice!)

Therefore iD should always present all possible solutions. Perhaps in two lists if necessary, all shown on the same screen. (But merged into one list is better.)

So the "Add a bridge" choice would select the road, and add the bridge.
And the "Add a tunnel" choice would select the stream, and add a tunnel.
