### ISSUE TITLE
Fountains shold not need to be connected to anything

### ISSUE THREAD

**Issue by forteller** [openstreetmap/iD#7454]
Yeah, title pretty much says it all. It seems very unreasonable to give an error for this, no?

![Screenshot from 2020-03-23 03-52-14](https://user-images.githubusercontent.com/343561/77317785-22da7a00-6d0c-11ea-94ce-e9e808fb6571.png)

**Comment by kymckay** [comment]
Have you checked the raw tags of the fountain? (Alternatively can you link to this location?)

**Comment by forteller** [comment]
Ah. Huh. Thanks :)

![Screenshot from 2020-03-23 16-45-06](https://user-images.githubusercontent.com/343561/77334890-af456680-6d25-11ea-90f4-2910a71c98ee.png)

Could there be a system to stop this from happening? I did not make this fountain, it was already there, I just fixed it up a bit. Maybe someone made it first as a footpath and then someone else changed it to a fountain? (Makes sense, since the footpaths towards it was connected to it when I found it. Could mutually exclusive tags be dropped automatically when a tag is changed? Or at least a warning be shown ("This element is tagged as a footpath, are you sure you want to make it into something completely different? Would you then like to remove the footpath tag?"

**Comment by quincylvania** [comment]
> Could there be a system to stop this from happening?

Theoretically, yes, but I'm afraid that determining what tags can coexist with other tags would be a never-ending task fraught with controversy. I'm inclined to leave it alone considering this type of issue looks to be relatively uncommon.

> Maybe someone made it first as a footpath and then someone else changed it to a fountain?

If someone did this with iD's preset switcher than the footpath tag would be removed automatically. If they used the raw tag editor then we assume they're being intentional. We can't control what other editors do.
