### ISSUE TITLE
Edit Bus/Tram/Ferry Route presets

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7479]
Remove fields `wheelchair`, `opening_hours`, `level` and `ele` from presets:
`type=route + route=bus`
`type=route + route=tram`
`type=route + route=ferry`
`type=route_master`.

**Comment by quincylvania** [comment]
Doesn't look like the `level` field is present on these. The `wheelchair` and `opening_hours` tags are recommended by the wiki.

The Elevation field is currently "universal", meaning it appears for every preset. This is something we should change.

**Comment by maro-21** [comment]
> Doesn't look like the `level` field is present on these.

I was sure it was there. Maybe it was removed in the meantime.

I don't want to open a new issue because the title would be the same, so I'm writing here.
Can we change the order of fields "To" and "From" to more natural: first "From" and "To" below?
I think this order is more natural, we name bus routes e.g. "222: Start -> Destination".

**Comment by quincylvania** [comment]
> Can we change the order of fields "To" and "From" to more natural: first "From" and "To" below?
I think this order is more natural, we name bus routes e.g. "222: Start -> Destination".

Okay, I did this. Note that the order that feels natural may depend on language and culture. Many non-Romance languages use a "to-from" construction when talking about things like journeys and exchanges. But I'm okay switching it since OSM is English-language-based and it'd be tough to support multiple orders.
