### ISSUE TITLE
Skilift mit unnötigem "public_transport"

### ISSUE THREAD

**Issue by Grenhauser** [openstreetmap/iD#7491]
Mittlerweile bietet der iD-Editor die Funktion dass er Fehler selbst korrigiert. 
Darunter fallen jetzt, oder schon länger auch Berg- und Talstationen in Skigebieten.
Diese werden dann als public_transport=station erfasst, auch wenn sie nur im Winter von den Skifahrern verwendet werden und keine öffentliche Funktion für Pendler, Anwohnern oder Touristen haben.

Mittlerweile sind etliche, wenn nicht alle, Skilifte von Schlepplift über Sessellift bis Gondelbahnen und sogar Materialseilbahnen mit public_transport=station erfasst, da:

1. Ein Mapper den Fehler eigentlich behoben haben möchte welcher vom Editor angezeigt wird.
2. Man beim klicken auf "aktualisiere die Eigenschaften" nicht angezeigt bekommt was von Editor hinzugefügt worden ist.
3. Man nicht davon ausgeht dass der Editor einem einen Fehler vorschlägt.
4. Es keine Nachfrage gibt ob die angezeigte Station zum ÖPNV Natzwerk oder zum Wintersport gehört.

Hier in meiner Region kann ich auf die schnelle 5 "aerialways" nennen die zwar nicht alle Teil des ÖPNV sind aber ausschließlich für den Transport von Fahrgästen auf die Alm oder als Verbindung zu kleineren Ortschaften für Touristen und Anwohner verwendet werden.         
Die restlichen "aerialways" haben ausschließlich die Funktion, dass sie zum Skifahren verwendet werden, oder sind Materialseilbahnen.

Der iD-Editor verschlechter hier doch eindeutig die Daten von OSM.

**Comment by quincylvania** [comment]
Hi and welcome, @Grenhauser. Please excuse me for answering in English, as I do not speak German.

If this translation is accurate, it sounds like you're suggesting iD shouldn't recommend `public_transport=station` on all aerialway stations because many are just for winter sports. This is tricky since transit tagging in OpenStreetMap varies from place to place. I'd argue that all aerialways function as transit—moving people between places in shared vehicles. It's useful if all things that function the same way are tagged the same way.

In any case, the OSM wiki doesn't appear draw a distinction between aerialway stations with different uses, so I don't see an issue with iD's behavior.

https://wiki.openstreetmap.org/wiki/Public_transport#Cable_cars
https://wiki.openstreetmap.org/w/index.php?oldid=625726

You can propose tagging changes on the wiki or on the tagging mailing list, but not this repo.

**Comment by jeisenbe** [comment]
We've discussed this on the mailing list and there is consensus that adding this tag is incorrect. See threads starting in https://lists.openstreetmap.org/pipermail/tagging/2020-March/051850.html and https://lists.openstreetmap.org/pipermail/tagging/2020-April/051885.html

While the old proposal linked above (from 2011) suggested the possibility of using public_transport=station for aerialways features such as chairlifts and ski gondolas, in practice this has not been done by mappers in the past 9 years, since most chairlifts, gondolas etc are private amusements or ski/snowboarding features, and are not used by the public.

There are a small number of gondolas used for public transportation in places like Bolivia, but most of these features are private. It would be better to let mappers add the tag manually but not include it in the preset. 

There's not really anything to change on the wiki, because the pages for [Tag:aerialway=station](https://wiki.openstreetmap.org/wiki/Aerialway) and [Key:aerialway](https://wiki.openstreetmap.org/wiki/Key%3Aaerialway) [Aerialway](https://wiki.openstreetmap.org/wiki/Aerialway) do not recommend adding public_transport=station to this feature. The individual pages like https://wiki.openstreetmap.org/wiki/Tag%3Aaerialway%3Dcable_car also do not mention adding public_transport.

The tag page for [public_transport=station](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstation) does not mention aerialway stations, except in the "See also" section, aka "similar but different tags".

The only page where this combination is mentioned was https://wiki.openstreetmap.org/wiki/Public_transport#Cable_cars which said:

"Cable-cars, drag-lifts and chair-lifts can be modelled using aerialway=*. These can be considered as a form of public transport in that they are shared, operated for fixed times of day at predictable intervals. Some cable cars may operate to a clock-face timetable."

"Aerialway stations are often tagged as aerialway=station. Some mappers add public_transport=station, public_transport=stop_position and aerialway=yes - however this tagging is much less common."

That is not an endorsement of using public_transport=station in addition. However, to clarify the situation, the page has now been edited to say that this combination is not recommended.

In particular, the combination with aerialway=goods would alway be incorrect since these transport goods such as mining products. 

It would generally be incorrect with aerialway=chairlift, =draglift, etc - I am only aware of these being used for recreation, not for transportation. 

Only a few gondola and cable_car features are used for public transport, though these are a small minority - perhaps the preset could offer public_transport as an option, but it should not be the default since this will nearly always be incorrect.

**Comment by bhousel** [comment]
See #4585 and others linked on that ticket for context.

When I did this, I tried following the approved [Public Transport v2 proposal](https://wiki.openstreetmap.org/w/index.php?oldid=625726) as closely as possible, and it does clearly include aerialways in its scope.

These presets landed in [v2.6.0](https://github.com/openstreetmap/iD/blob/develop/CHANGELOG.md#260) so it would have been based off whatever the wiki said back in late 2017.

**Comment by quincylvania** [comment]
@jeisenbe Thanks for the links to the mailing list discussion. Is iD's tagging pattern actually causing issues for any apps using OpenStreetMap?

I personally don't see a clear or important difference "leisure transport" and "public transport". Are we to tag the Disneyland Monorail or Heidelberger Bergbahn differently because they're primarily used for tourism? The aim of iD is to help non-experts create useful data and I'm not sure asking people to make this kind of judgement fits that goal.

**Comment by Grenhauser** [comment]
@bhousel 
Nothing in the proposal say that we should add PT=station to aerialway=station, or that this replace the aerialway tagging.

I find only this link what is talking about **stop area**:     
https://wiki.openstreetmap.org/w/index.php?oldid=625726#The_new_Schema_in_Short      
and this, talking about "considerably bigger than a pair of bus stops or tram stops":     
https://wiki.openstreetmap.org/w/index.php?oldid=625726#Station      


@quincylvania 
> I personally don't see a clear or important difference "leisure transport" and "public transport". Are we to tag the Disneyland Monorail or Heidelberger Bergbahn differently because they're primarily used for tourism? The aim of iD is to help non-experts create useful data and I'm not sure asking people to make this kind of judgement fits that goal. 

Disneyland Monorail is a railway, it is a other discussion if it makes sense to add PT to stations inside a theme park.

A better example is the Seekoogl Sessellift(aerialway). It is generally **not** used by people who have to go to work, but by people as a pastime. 

If you live in a country with a lot of winter sport areas, you will know the difference between "leisure usage" and "public usage" and you will be able to answer the question about "winter sport usage" or "only public transport usage".

Therefore, this preset in iD does not improve the data in OSM in any way.

**Comment by jeisenbe** [comment]
> Is iD's tagging pattern actually causing issues for any apps using OpenStreetMap?

I'm not aware of this, but I believe the burden is on those wishing to add a tag: there should be evidence that adding the tag `public_transport=station` provides some benefit to mappers or database users.

Since most aerialway features are ski lifts which can only be used by buying a very expensive lift ticket (now about $100 a day on weekends), and the lifts only take you in one direction with the requirement to ski or snowboard back down the mountain, they are clearly recreational features, not public transport features. 

Recall that in British English, "public transport" is close to the meaning of "mass transit" or "public transit" in US English: it's a service that transports passengers and is open to the whole public: "public transport (countable and uncountable, plural public transports)

"(Britain, Australia, New Zealand) Any form of transport that can be used by a member of public (who usually pays a fare); as opposed to private ownership of e.g. cars. - Synonyms (US) public transit (US) public transportation" - Wiktionary

"a system of vehicles such as buses and trains that operate at regular times on fixed routes and are used by the public" "(US: public transportation)" - Cambridge 

I don't believe ski resorts are required to serve the public in most countries: they are private businesses, not a public transporation service. 

So, adding a tag which suggests that these are public_transport facilities is incorrect in most cases. 

And certainly, adding this tag to aerialway=goods is always wrong, we can agree?

> I personally don't see a clear or important difference "leisure transport" and "public transport". Are we to tag the Disneyland Monorail or Heidelberger Bergbahn differently because they're primarily used for tourism?

Even the Disneyland/Disneyworld monorails provide some transportation service: you can use them to get from the entrance or your hotel to the amusements, and then back again. This cannot be done on most ski lifts and similar aerialways. These are more like "Space Mountain" or one of the other rollercoaster rides at the theme park.

But I don't think iD should offer this as part of the preset, since this usage is not established.

If there was a tag that clearly specified that an aerialway was used for public transit (perhaps just public_transport=yes/no) it could be beneficial for mappers to add this, but so far there is no consensus in the community that such a tag is needed.

At this time, my request is that the preset be edited so that "public_transport=station" is not added to "aerialway=station" by default.

**Comment by stefanct** [comment]
Once again iD is directly responsible for some wrong tagging enforced upon OSM maintainers. You do have a responsibility and power that you apparently don't comprehend. New(-ish) mappers trust suggestions without thinking about them too long. Giving them wrong ideas leads to completely avoidable work for those who care about the quality of data. If in doubt don't recommend something! I often wonder wtf are people thinking when mapping something... and about half of the time the reason is iD's templates. Over the years this has led me to recommend everybody to stay away from iD as far as possible and AFAICT most experienced mappers in my peer group do the same. Reading the discussion above and the conclusion just makes me sad and angry :(
