### ISSUE TITLE
Is there a hot loading mode for local development?

### ISSUE THREAD

**Issue by clearJSer** [openstreetmap/iD#7505]
1. `cd` into the newly cloned project folder
2. Run `npm install`
3. Run `npm run all`
3. Run `npm start`
4. Open `http://localhost:8080/` in a web browser

Can I see the effect of the code I changed in real time? how to do?
for example   'npm run dev'

**Comment by quincylvania** [comment]
Hi and welcome, @clearJSer. You can't see code changes in real time since iD is a large, compiled app.

Note that you only have to do steps 1-3 from your list the first time you setup iD. Afterward, just run `npm start` to see your changes.

You can also review iD's scripts to see how to build CSS, data, and sprite sheets separately from the code:

https://github.com/openstreetmap/iD/blob/252d5217e570586f95bc3e9f878575550925f448/package.json#L14-L42
