### ISSUE TITLE
Don't suggest bus=yes for highway=bus_stop

### ISSUE THREAD

**Issue by camelCaseSucks** [openstreetmap/iD#7524]
`bus=yes` is an access tag, indicating something is accessible by bus. I can't imagine there is such a thing as a bus stop that is not accessible by bus, so it's completely unnecessary on bus stops. It's not even mentioned in the 'recommended tagging' section of the `highway=bus_stop` wiki page. It's not wrong, but it's not useful either.

**Comment by quincylvania** [comment]
@camelCaseSucks The `bus=yes` tag indicates the type of public transport for `public_transport=platform`. This pattern succeeds `highway=bus_stop`, but iD currently supports both for backwards-compatibility.

**Comment by camelCaseSucks** [comment]
> The `bus=yes` tag indicates the type of public transport for `public_transport=platform`

[This comment on a Carto issue](https://github.com/gravitystorm/openstreetmap-carto/issues/311#issuecomment-544909753) claims that is what `highway=bus_stop` or `railway=tram_stop` are for. I looked up [the original proposal on the wiki](https://wiki.openstreetmap.org/w/index.php?oldid=625726#Platform) which suggests tags like `bus=yes` should be used for `public_transport=stop_position` (a node on the road where the bus stops) but makes no mention of those tags for `public_transport=platform`. This makes sense because the platform (usually on a sidewalk) is not directly accessed by the bus, it only stops nearby and people walk from the platform to the bus.

The [`public_transport=platform` wiki page](https://wiki.openstreetmap.org/wiki/Key:public_transport) makes no mention of `bus=yes`, and the [`bus=yes` wiki page](https://wiki.openstreetmap.org/wiki/Key:bus) only says:

> Since 2011, some mappers have used bus=yes with highway=bus_stop, public_transport=platform, or both, to specify that a feature is a bus stop. This is the most common use of bus=yes.

This does not indicate the tag is required. Please reconsider.

**Comment by maro-21** [comment]
This tag is necessary because `public_transport=platform` gives no information what kind of stop it is.
So
`public_transport=platform` + `tram=yes` is a tram stop
`public_transport=platform` + `bus=yes` is a bus stop

**Comment by camelCaseSucks** [comment]
> This tag is necessary because `public_transport=platform` gives no information what kind of stop it is.
> So
> `public_transport=platform` + `tram=yes` is a tram stop
> `public_transport=platform` + `bus=yes` is a bus stop

Where did this idea come from? As the wiki links in my last comment (including the `public_transport` v2 proposal) show, the access tags are not meant to be used on the platform. 

`railway=tram_stop` is a tram stop
`highway=bus_stop` is a bus stop

`public_transport=platform` is meant to supplement these tags, not replace them. The access tags are not necessary or helpful, and arguably not even correct (see my last comment).

**Comment by kymckay** [comment]
I think the wiki pages have changed over the years as the tagging around public transport has always had conflicting opinions since I started editing. The information probably also differs across all the different pages which discuss public transport tagging.

I know that I remember first reading to use `public_transport=platform` and `bus=yes` (the idea being a platform could serve multiple forms of transport) with no `highway=bus_stop` because it was made redundant by those two tags. People even used to recommend retaining the latter for the renderer as a double-tagging.

You can see for yourself when the wiki pages changed:
- Mention of `public_transport` tagging was eradicated from https://wiki.openstreetmap.org/wiki/Tag:highway=bus_stop in May 2019 by user DaveF63.
- `public_transport=platform` was changed to optional at https://wiki.openstreetmap.org/wiki/Buses#Bus_routes in March 2020 by user Jeisenbe.
- Mention of `bus=yes` was removed from https://wiki.openstreetmap.org/wiki/Public_transport in July 2019 also by user Jeisenbe.

This reflects a common issue in OSM tagging, the wiki may now describe the original tagging proposal intention, but not the way the tags have now been used for some time because it was "wrong" for so long. iD can't just take the wiki as gospel, because not everyone will now agree with it and it says different things at different points in time.

**Comment by maro-21** [comment]
> railway=tram_stop is a tram stop
> highway=bus_stop is a bus stop

This is the old scheme. And because there was no e.g. highway=trolleybus_stop, new tagging scheme that covers other means of transport had to be created, because there are more than bus and tram.
