### ISSUE TITLE
Add COVID-19 Opening Hours Option

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/iD#7529]
Maptime Bmore is [planning a virtual mappy hour on 4/30](https://wiki.openstreetmap.org/wiki/Foundation/Local_Chapters/United_States/Virtual_Mappy_Hours#Upcoming_Events) to update Baltimore carryout restaurants on OSM using a crowdsourced spreadsheet for reference. We'd like to add the pandemic-related `opening_hours` using the newly authored [`opening_hours:covid19` spec on the OSM Wiki.](https://wiki.openstreetmap.org/wiki/Key:opening_hours:covid19).

Can the `opening_hours:covid19` key be added to iD? Before 4/30?

**Comment by 1ec5** [comment]
> Before 4/30?

Not sure what the release schedule is for iD, but even after a new release of iD is published, it may take a little while for it to be deployed on openstreetmap.org. In case it isn’t feasible to release the requested change by then, it would still be possible to host an instance of iD on some website that the mappy hour participants can use instead of the main openstreetmap.org instance.

**Comment by Nakaner** [comment]
> Can the opening_hours:covid19 key be added to iD? Before 4/30?

Yes, you have been ablet the tag with iD for a couple of years already – well without the support of presets. Just select the object to be modified and then go to "All tags" in the left sidebar and enter the tag manually. It is not as comfortable as an additional field in the preset but it works now and does push any pressure on the maintainers of iD (which is not needed because not implementing it quickly is does not harm OSM data).

**Comment by thayeray** [comment]
Thanks for doing this @quincylvania and for requesting the change @talllguy!
