### ISSUE TITLE
Change icon for shop=deli

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7533]
Currently the icon for [`shop=deli`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Ddeli) is the same as for a restaurant. Could we change it to what it is in OSM Carto or something similar?
https://wiki.openstreetmap.org/wiki/File:Deli-14.svg

**Comment by quincylvania** [comment]
Good news, I've already changed this for v2.17.3. Delis are tricky since they're somewhat different types of shops in different parts of the world, but I think meat is a common theme. You can test and map with pre-release iD here: https://ideditor.netlify.app.

<img width="356" alt="Screen Shot 2020-04-27 at 9 52 29 AM" src="https://user-images.githubusercontent.com/2046746/80398895-36c64e00-886d-11ea-962c-8d134b5a178f.png">
