### ISSUE TITLE
The name disappears after entering a dash

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7536]
I wanted to change the name of a bus stop:

![volvo1](https://user-images.githubusercontent.com/57260466/80288756-61fc5080-873a-11ea-800d-1c9c218c85bc.png)

What I wanted to do was change the hyphen to the dash in the name:

![volvo2](https://user-images.githubusercontent.com/57260466/80288759-67599b00-873a-11ea-96f4-bdafe37684fe.png)

No matter what I do or where I click, the name after the dash disappears and only "Volvo" remains:

![volvo3](https://user-images.githubusercontent.com/57260466/80288760-6d4f7c00-873a-11ea-97ae-fae48a8fd399.png)

I can edit the name only in All Tags section.

**Comment by bhousel** [comment]
Thanks for reporting @maro-21 .. The endash is used as special separator character in the name dropdown for a few old reasons.  Name suggestion presets sometimes need to disambiguate between several choices like “7-Eleven – Fuel” and “7-Eleven – Convenience Store”.  Because names can have hyphens in them and the dropdown control only lets us work with a single text value, and the preset part of the name needs to be localized, we are using the endash as a separator. 

It would be ideal if you can use a different separator character in your bus stop names.  For example, it’s common in places like Belgium to represent multilingual names like “French - Dutch” with a standard hyphen between.

**Comment by 1ec5** [comment]
Looks like this bug only occurs if there are spaces surrounding the en dash, possibly due to that conflict with the name suggestion feature mentioned above, but it occurs even if there’s no name suggestion preset.

https://github.com/openstreetmap/iD/blob/60f7dc7c0b58e52e95cbe9a9244fb8e8f939d635/modules/ui/sections/feature_type.js#L102-L103

Assuming it is due to the name suggestion preset feature, could that feature format the disambiguators differently? Some languages, such as Chinese, use en dashes in everyday usage and don’t consider hyphens to be a substitute.

name-suggestion-index already uses parentheses to disambiguate identically tagged presets in different countries. But there are other options for disambiguating tags that would be less likely to conflict with things users may be in the habit of entering manually; possibilities include a swung dash (⁓), bullet (•), or square brackets ([…]).

**Comment by bhousel** [comment]
We could probably delimit on some nonprintable Unicode characters in the string to avoid the issue.  The important thing is that the decorated string looks normal to the user and to html, because it will appear in dropdowns, preset labels, etc, and we will have to find it later to remove the decoration.

**Comment by quincylvania** [comment]
I ended up making `name()` only the brand name and added the parent preset name as a separate `subtitle()` property. The en dashes are still used for suggestion display, but no longer factor into the name value and thus don't need to be discarded. This seems cleaner and avoid bugs like this.
