### ISSUE TITLE
Add building=office, building=supermarket and other buildings

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7539]
Add presets for various popular types of buildings. Office building is what I miss the most because I use it often.

[`building=office`](https://wiki.openstreetmap.org/wiki/Tag:building%3Doffice) ([100322](https://taginfo.openstreetmap.org/tags/building=office) features)
[`building=manufacture`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dmanufacture) ([97767](https://taginfo.openstreetmap.org/tags/building=manufacture) features)
[`building=transformer_tower`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dtransformer_tower) ([22750](https://taginfo.openstreetmap.org/tags/building=transformer_tower) features)
[`building=allotment_house`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dallotment_house) ([21345](https://taginfo.openstreetmap.org/tags/building=allotment_house) features)
[`building=cowshed`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dcowshed) ([10812](https://taginfo.openstreetmap.org/tags/building=cowshed) features)
[`building=supermarket`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dsupermarket) ([9244](https://taginfo.openstreetmap.org/tags/building=supermarket) features)
[`building=sty`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dsty) ([2796](https://taginfo.openstreetmap.org/tags/building=sty) features)
[`building=tent`](https://wiki.openstreetmap.org/wiki/Tag:building%3Dtent) ([1903](https://taginfo.openstreetmap.org/tags/building=tent) features)

**Comment by quincylvania** [comment]
I added `office`, `cowshed`, and `sty` since those seem like common, distinguishable things. I did not add the rest for these reasons:

- I assume `manufacture` overlaps strongly with `industrial`. It would be confusing to have both, especially since it doesn't have English wiki documentation.
- I didn't know what a `transformer_tower` was and I'm afraid others won't either. The tag appears to be used primarily in Europe, perhaps they aren't common elsewhere? It could also be confused for `power=tower`. If people really want to map these maybe we can think of some solution
- `allotment_house` seems too specific to countries with allotments and yet vague about the form of the structure. The wiki itself lists four other tags that could be suitable instead.
- `supermarket` is likely to get confused with `shop=supermarket`.
- `tent` is likely to be misused on transient tents and has pretty low usage anyway.
