### ISSUE TITLE
Untraslatable strings for new Overlays

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7554]
In the changelog for 2.17.3 you didn't mention about two new features: OpenRailwayMap Maxspeeds and OpenRailwayMap Signalling.
Unfortunately these ones are in English, could you make them translatable?

![](https://user-images.githubusercontent.com/57260466/80618359-8cecea00-8a43-11ea-9d5f-a7fca4f61ccd.png)

**Comment by quincylvania** [comment]
@maro-21 So those layers come from the [editor-layer-index](https://github.com/osmlab/editor-layer-index/issues). We usually don't include those changes in our changelog since it's a separate project with its own release schedule, theoretically.

As far as translation goes, looks like something might be wrong with the imagery strings…

**Comment by maro-21** [comment]
It has been corrected
https://github.com/osmlab/editor-layer-index/pull/832/commits/d9eae265809b3387488680036d702dd6d42d4fbc
