### ISSUE TITLE
Remove non-prefixed versions of contact: scheme

### ISSUE THREAD

**Issue by ValorNaram** [openstreetmap/iD#7566]
I request to replace all (hardcoded/in preset) occurrence of the non-prefixed versions of the contact keys like Key:phone, Key:email. Key:website to be replaced with the prefixed ones like Key:contact:phone, Key:contact:email, Key:contact:website . It harms our database in a way that makes our data less useful. In order to be successful we need to standardize to the `contact:` prefix. No more multiple keys for the exact same purpose with just different names! Make tagging more orthogonal! As someone who has experience in database and normalisation it hurts to see that mappers don't know how to take care of a database. It is time to take action and to clean up so OSM data gets more useful.

**Having two keys for the same purpose (the current behaviour) has no advantages but many disadvantages:**
- Data customers need to be aware of both tags to cover all requested and available information. So to get telephone numbers they need to look for Key:phone and Key:contact:phone . This makes a bad impression.
- Normalisation of that data is required. Key:phone must be translated to Key:contact:phone or backwards. It is good to prevent the need of normalisation through standardisation as far as possible to prevent errors and misinterpretations from happening.
- Having two schemes leads to confusion of mappers (especially for newbies) which they should use. Some need clear guidance ( e.g. On request I created a translation table for mappers of the old diaper key to help them to switch to the new Key:changing_table as you can see here: https://wiki.openstreetmap.org/wiki/Key:changing_table#Comparison_with_the_deprecated_diaper.3D.2A_key . I also notified some of the mappers and stakeholders about that change)

**Comment by Nakaner** [comment]
See also https://github.com/openstreetmap/iD/issues/3915 and, if you need the see a voting on that question, https://wiki.openstreetmap.org/wiki/Discussions/tagging/contact:phone_or_phone

IMHO, there is only one thing where iD could improve without taking sides in a never ending dispute and making any party more angry than the other one: If `contact:phone=A` is set, setting `phone=A` makes no sense because data consumers are used to take both keys into account. Not duplicating the value would be an improvement here. (Same vice-versa if `phone` is set and `contact:phone` isn't, and for all other ways of communication, e.g. `website`, `fax`)

**Comment by quincylvania** [comment]
@ValorNaram I can see that you're passionate about this, but it's outside iD's scope. Tagging changes of this magnitude have to be settled at the database level, not the editor level. You're talking about retagging millions of features. If a solution is approved and implemented in the database then we can update iD's presets.

**Comment by maro-21** [comment]
ValorNaram I agree with you that having two keys for the same purpose is bad.
I had many such situations when someone added with iD `phone` key, while `contact:phone` was already there.

If I had to choose, I would choose prefixed version because on the list of tags one can easily see all the contact tags in one place.

I think the one thing we can do is to add a validation rule to check if both "phone" and "contact:phone" (email, fax and website) exist and add a warning. 
@quincylvania, what do you think?

**Comment by Hedaja** [comment]
As @maro-21  mentioned, it would be good if ID would at least recognize that contact:* exists.
JOSM has presets for both schemes but I can understand if you don't wanna have two because it might confuse beginners. 

Most important thing is to show that contact: exists on an object. For exampl if sonething already has contact:phone , simply show it in the phone field and if an email gets added add it as contact:email for this object.

The next higher level would be offering people the choice of what they wanna use by default.
We have people in the German telegram group that would like to use contact: but out of convenience, they simple use the input mask instead of typing the key and value.
So having an option to change what you wanna use would be great.

Should I open a new issue to better represent this 'let's meet in the middle' proposal?

**Comment by Hedaja** [comment]
Any news? What do you think about the compromise @quincylvania?
