### ISSUE TITLE
Add support for isced:level

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#7571]
It would be cool if there was some kind of support for tagging what type of school a school is. The de facto tag seems to be isced:level, but since it isn't supported a bunch of other less used tags are being used for the same thing. Like school, education and training. It would be good  if there was just one tag being that was easily accessible in iD Editor. Maybe iD Editor could support it by having presets that come up when someone searches for "primary school" that add the tags amenity=school + isced:level=1 or something like that.

**Comment by 1ec5** [comment]
At least here in the U.S., there’s very little public awareness of ISCED or how it maps to conventional grade numbers, much less ISCED 1997. Mappers would need to familiarize themselves with [the table on this wiki page](https://wiki.openstreetmap.org/wiki/Key:isced:level). The most appropriate field type for this key would be a list of checkboxes with descriptive labels. (Otherwise, a numeric ISCED field would be just as usable as a numeric [`protect_class`](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dprotected_area#Classification) or [`tracktype`](https://wiki.openstreetmap.org/wiki/Key:tracktype) field.)

Supplying those descriptive labels would be tricky. The groupings ISCED makes don’t always map cleanly to the conventional groupings that mappers would find more intuitive. The conventional groupings differ in name from country to country, creating a lot of work for translators. iD would need to decide whether to follow the wiki’s use of ISCED 1997 or to follow ISCED 2011, which is better documented for more countries but isn’t one-for-one compatible with the 1997 edition.

I’d love to see a freeform [`grades`](https://wiki.openstreetmap.org/wiki/Key:grades) field instead. Ideally, ordinary mappers could just enter conventional grade numbers from local knowledge, surveys, street-level imagery, or imports of authoritative data. Other tags might be necessary to handle countries that don’t number grades, but the point would be for mappers to capture what can be verified on the ground and leave the ISCED normalization to post-processing by data consumers or maybe automated edits.

Unfortunately, the original proposal for `grades` tried unsuccessfully to mold grade numbers into a single universal numerical scheme akin to ISCED, but with less research backing it. That approach was [roundly ignored](http://taginfo.geofabrik.de/north-america/us/keys/grades#values) by American mappers, but it’s possible that mappers elsewhere tried to follow the wiki’s guidance. If iD were to add a `grades` field, I think there would be less confusion if local usage were promoted over the “[international](https://wiki.openstreetmap.org/wiki/Key:grades#International)” scheme in documentation.

**Comment by quincylvania** [comment]
@1ec5 Thanks for the background info here. It looks like `grades` would indeed be friendlier for iD mappers, so I added that for now. It's nice to finally have a field for this—I've been missing it since I first started mapping in OSM.

**Comment by Adamant36** [comment]
I guess grades works. Its better then nothing and isced:level clearly has its own unique problems. Even if it had vastly more usage. Thanks @quincylvania

**Comment by quincylvania** [comment]
I like the idea of potentially using the `isced:level` tag to create presets like "Primary School", at least for some countries. But it's great if people can type in the grades that make sense to them regardless.
