### ISSUE TITLE
ESRI just a lower resolution version of the same MAXAR imagery  

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#7593]
It turns out the ESRI imagery,
![E](https://user-images.githubusercontent.com/1230959/81555481-3b394d80-93bb-11ea-9010-e7989c733881.jpg)
is simply just a lower resolution version of the same MAXAR imagery,
![M](https://user-images.githubusercontent.com/1230959/81555554-5efc9380-93bb-11ea-8e3b-b7e02b51c600.jpg)
at least at https://www.openstreetmap.org/edit#map=18/24.16310/120.82965

**Comment by intgr** [comment]
This is not true everywhere though. In Estonia, where I live, Esri is significantly more detailed than any other provider.

I think it's common practice for imagery providers pick and choose between satellite partners for sourcing their imagery for different areas, and two might end up using the same imagery for some area. I think there isn't anything actionable here.

**Comment by jidanni** [comment]
Ah ha... how about adding to the top of the list
[x] Best
which would be chosen for us via Artificial Intelligence...

Well at least Artificial Intelligence could knock identical imagery out of the list, leaving only the better one, or combining their names in case of a tie... all these are wishlists for the years to come.

**Comment by intgr** [comment]
The iD editor indeed has capability of highlighting a preferred imagery source, but I'm not sure about the details. There's a long discussion at #6736.

It's probably determined somewhere in repositories https://github.com/ideditor/imagery-index or maybe https://github.com/osmlab/editor-layer-index

**Comment by kymckay** [comment]
I may be missing some knowledge here, but I don't believe there is any way iD can programmatically do anything about this (without having a suitable source of metadata about all of the imagery tiles), nor do I think it's actually an issue.

Because the imagery sources can change across very localised regions, the only options that I can fathom would require either an unreasonable amount of routine manual metadata research and entry or real-time imagery processing/comparison, both of which seem like extreme measures just to contextually hide or prioritise imagery in the UI (and thus, not worth doing).

On top of that, I think the end result would actually be worse for the end user with the imagery list changing for contextual reasons that are really hard to convey (at least, by my consideration).

As such, I'm going to go ahead and close this issue as out of scope.

**Comment by quincylvania** [comment]
@SilentSpike Good reasoning, thanks for responding and closing.

@jidanni Sorry, but saying "just fix this minor annoyance with AI" isn't helpful for an open source project like iD with limited development resources.
