### ISSUE TITLE
Translations at Transifex

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#7601]
Hi there.

There are some translation strings at Transifex which don't have any documentation in wiki pages.
For example:
- Cleaning Service ( craft=cleaning): what's this and where is it on wiki.openstreetmap.org?
- Courtyard (man_made=courtyard): this is a proposal, it wasn't voted yet. Why is it being translated?

BTW, what does "Fix Guidelines" mean in "core"?

**Comment by maro-21** [comment]
- Cleaning Service is just a cleaning service... Yes, it's not on the Wiki.
- Courtyard isn't on the Wiki either. I asked myself the same question today when I was translating. More information and pictures you can find here https://wiki.openstreetmap.org/wiki/Proposed_features/courtyard. It would be good to have a Wiki entry though.
- "Fix Guidelines" is, I think, the same as "How to fix" in the Osmose menu

![Fix_Guidelines](https://user-images.githubusercontent.com/57260466/81870613-7df35500-9576-11ea-8afa-60c16ad0b811.png)
- Translation of the above text from Osmose issues you can find here: https://www.transifex.com/openstreetmap-france/osmose/translate/#pt

**Comment by quincylvania** [comment]
@AntMadeira Thanks for translating! Hopefully @maro-21 answered your questions…

> Courtyard (man_made=courtyard): this is a proposal, it wasn't voted yet. Why is it being translated?

Most tags in OSM have never been voted on—iD's presets are based on more factors than the wiki. That proposal is five years old and hasn't gone anywhere, but this appears to be the most established tag for courtyards.

**Comment by AntMadeira** [comment]
I don't think iD should promote tags that are not approved by the community and are not properly documented. I know that a tag doesn't need to have a wiki to be used, but I think that it should be at least discussed and not just pushed like a de facto tag.

About Osmose string, I'm sorry but I still don't understand what it means or where it's going to appear...

**Comment by quincylvania** [comment]
> I don't think iD should promote tags that are not approved by the community and are not properly documented.

@AntMadeira Hmm my understanding is that most OSM tags have grown organically and weren't formally discussed nor approved. I believe `man_made=courtyard` is consistent with this pattern. It's been around for years and has hundreds of uses from mappers who manually added it because they thought it was the most suitable tag. Documenting these types of tags can be a great asset, but is not a requirement for iD 🤷‍♂️

If you feel strongly enough that iD shouldn't support this tag then I invite you to open a pull request to remove the preset. I acknowledge there are differing approaches to tagging and my job isn't to debate this.

**Comment by quincylvania** [comment]
> About Osmose string, I'm sorry but I still don't understand what it means or where it's going to appear...

@AntMadeira The Osmose layer is coming in the next feature update to iD. The "Fix Guidelines" string is a section header on the left here:

<img width="1045" alt="Screen Shot 2020-05-13 at 9 34 48 PM" src="https://user-images.githubusercontent.com/2046746/81882808-9f961180-9561-11ea-8bb1-098a1196e424.png">

**Comment by AntMadeira** [comment]
Thanks for your clarifications, Quincy.
I don't intend to change iD's policy about tags. I just thought it was odd to push for something that it's not approved. I guess I could open the discussion in the tagging mail list, but I'm in too many fronts right now to take the time to do it. If iD thinks this is ok, it's fine by me.

Osmose: Ok, now I get it. I was searching for something that it's not implemented in iD yet. It's good to know I'm not crazy.  :D

Regards.

**Comment by AntMadeira** [comment]
About new strings at Transifex:

"Jetway" - what is `aeroway=jet_bridge`? (it has no wiki)
"Unknown Road Bridge" - The `highway=road` tag is highly discouraged and even considered an error. The wiki states: 

> Mappers should not expect that ways tagged like this will be useful to the end-user in any form. The ambiguity makes this rarely useful for data consumers. This has the following implications:
Do not expect highway=road to be rendered
Do not expect highway=road to be routable
Do expect highway=road to be ignored by applications directed at end users

Does iD really need this?

Regards.

**Comment by quincylvania** [comment]
> "Jetway" - what is aeroway=jet_bridge? (it has no wiki)

A jetway is the walkway between an airport terminal and a plane: https://en.wikipedia.org/wiki/Jet_bridge. We changed the name from "Jet Bridge" since people were incorrectly using it to map road bridges.

> "Unknown Road Bridge" - The highway=road tag is highly discouraged and even considered an error.

Yes, iD warns against usage of the `highway=road` tag and encourages users to pick a more specific highway type. But there are times and places when a highway type cannot be determined (e.g. when tracing rural imagery from a foreign country), so iD has had an Unknown Road preset for awhile.

Unknown Road Bridge is a low-visibility preset intended to help inexperienced mappers discover that road bridges are attributes and not independent feature types. Imagine this workflow for a new mapper:

1. Draw a line representing a road bridge
2. Search "bridge" in presets
3. Select Unknown Road Bridge preset
4. See warning about `highway=road`
5. See Bridge selected in the Structure field
5. Pick a better highway classification
6. Search for highway type next time

**Comment by AntMadeira** [comment]
Thanks, Quincy. That helped.

I didn't realise that `highway=road` tag would show an info box. I think its a fair trade off for having this kind of highway in iD.

**Comment by maro-21** [comment]
Good idea with this bridge, Quincy.
