### ISSUE TITLE
[preset] `highway=footway` described as “car-related equipment”

### ISSUE THREAD

**Issue by Mbodin** [openstreetmap/iD#7612]
In iD 2.17.3, a polygon with `highway=footway` is described in French as “Équipement autoroutier”¹, which can roughly be translated as “car-related equipment”. This is confusing as `footway` states that this place is not meant for cars. I think that it would be better to describe such places it as if it were `highway=pedestrian` as a first approximation.

Here is an example of such a way: https://www.openstreetmap.org/way/728326593
Here follows a screenshot showing the description (top left).
![Screenshot from 2020-05-18 10-54-16](https://user-images.githubusercontent.com/1829786/82200855-74137e00-98f7-11ea-8516-efad12946bbd.png)

If this can be of any help, I am using Firefox 76.0.1.

¹ I tried to look for the string reference in Transifex, but got lost in the website’s interface: I don’t know the string reference.

**Comment by quincylvania** [comment]
Oh I see the issue here. This problem is iD doesn't have a preset for `highway=footway` as an area. It's falling back to the generic `highway=*` preset and thus uses the translation of "Highway Feature". Someone should probably change the translation to indicate this feature includes non-car infrastructure. This can be done [here](https://www.transifex.com/openstreetmap/id-editor/translate/#fr/presets/11399151?q=text%3A'highway+feature').

**Comment by scotmartin** [comment]
Thank you for this very beginner friendly issue. I have changed the translation to "Équipement pour toutes les voies", that makes it applicable to any kind of road, street or path without reference to means of transportation.

**Comment by quincylvania** [comment]
@scotmartin Thanks a bundle!
