### ISSUE TITLE
Don't offer to upgrade tags of railway platforms with access=private

### ISSUE THREAD

**Issue by claysmalley** [openstreetmap/iD#7615]
When a mapper selects a `railway=platform` with the `public_transport=platform` tag missing, the validator will suggest to add that tag ("Train Platform has incomplete tags", "Upgrade the tags"). Currently this also happens on railway platforms inaccessible to the public (e.g. with `access=no`, `access=private`, etc.). In this case adding the `public_transport=*` tag would be misleading—these usually represent platforms of significance to the railway system but not the public transportation network.

For example, [this platform at Boland's Landing](https://www.openstreetmap.org/way/293373637) on the Long Island Rail Road in Queens, New York, is only accessible by railway employees. Official maps omit it and riders are often unaware that it even exists, unless an employee happens to be on board to request a stop there. It certainly fits the definition of an area where people board and exit trains, but the train doors will not open for ticketed passengers at Boland's Landing. So I have it tagged as `railway=platform` + `access=private`.

I like to add access tags to platforms to make it clear which ones are explicitly not for public transportation. If the validator ignores this, new users tempted to Fix All The Warnings will sometimes come across such platforms and upgrade the tags. Potentially I could add `public_transport=no` to these platforms to pre-empt any attempts at upgrading the tags, but I'd rather not have to add another tag into the mix and throw in noise for people consuming `public_transport=*` tagged data.

**Comment by quincylvania** [comment]
Hello and welcome, @claysmalley. This is a tricky issue since transit tagging is applied so unevenly in OSM, but I'm pretty sure what iD is doing is okay.

Despite the name, `public_transport=platform` defines only the place where passengers board or disembark a transit vehicle and doesn't imply "public" access. As you know, that's what the `access` tag is for. Plenty of mass transit infrastructure doesn't fit the literal meaning of "public transport"—theme park monorails, resort ski lifts, Google's employee shuttle buses—but it makes sense to use the same tags for everything that functions the same way.

That said, do you know if this is causing problems for any apps using OSM data? With iD we're much more concerned with practical data usage than theoretical tag definitions.

**Comment by claysmalley** [comment]
Fair enough. I can't think of any data consumers that currently depend on this distinction.

**Comment by quincylvania** [comment]
@claysmalley Great, thanks for understanding!
