### ISSUE TITLE
iD wants to remove internet_access=terminal

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7617]
I added `internet_access=terminal` to a library because there are computers in the library which one can use.
There was a tag `wifi=yes` there.
It was some time ago before adding validation to iD.
When I now open this feature, iD wants to remove important information:
Suggested updates:
```
- internet_access=terminal
+ internet_access=wlan
- wifi=yes
```

**Comment by quincylvania** [comment]
Yes, iD ignores existing values for this type of tag upgrade. While not ideal, I would call this the least bad of all the possible behaviors since it doesn't leave conflicting values and erroneous results are usually glaring.

As for this particular case, `internet_access=wlan` is the widely accepted way to tag the presence of wifi. Regrettably there's no great way to tag multiple types of internet access, but you can try `internet_access=wlan;terminal` or simply `internet_access=yes`.

**Comment by maro-21** [comment]
Why do you think it's not a bug? It suggests removing important information.
I don't see any conflicting values here, it is possible that internet access in a library is terminal together with wifi.
iD could replace it with `internet_access=wlan;terminal`
Semicolon separated values are commonly used https://taginfo.openstreetmap.org/keys/internet_access#values

**Comment by quincylvania** [comment]
@maro-21 I'm talking about the general case of this type of tag upgrade. iD can't know every valid combination of tags. For this specific case it'd be okay to combine the tags, but what if the existing tags were `internet_access=no` + `wifi=yes`? Not upgrading the tags would leave them conflicting, as would upgrading to `internet_access=no;wlan`.

**Comment by maro-21** [comment]
The solution could be
 if `internet_access` exists, do nothing
 else update `wifi=yes` to `internet_access=wlan`
