### ISSUE TITLE
Marker Animation along a Way

### ISSUE THREAD

**Issue by teiszler** [openstreetmap/iD#7624]
Good day,

We have a fork of iD in which we have added our own features and are using the editor to create simulation scenarios. The simulation takes place in a separate system, but we leverage iD to allow the user to generate the content of the scenario (using the osmChange file that is generated as input into the simulation). While the simulation is in progress, we would like to update the pathways that the user has drawn with a marker showing the current location of a object along those paths (based upon the elapsed time and the speed of the object, which is an attribute of the feature).

[This](https://openlayers.org/en/latest/examples/feature-move-animation.html) is a great example from openlayers of essentially what we would like to do in iD.

I have tried using` context.perform(actionAddEntity()) `but this adds a new item to the OSM layer and creates a new diff and I am using the differences to iterate through the ways/nodes that need to track the objects for during the simulation. I think ideally I could use a method that would simply draw an icon at a particular geolocation, but if such a method exists I could not find it. There is ` function svgIcon(name, svgklass, useklass)`, however it seems to mostly be used to add icons to buttons in the toolbars/panes and not onto the map layer.

Do you have any insight on how this could be achieved without serious departure from the current  codebase?

Regards,
Tom

**Comment by quincylvania** [comment]
Greetings and welcome to the repo, @teiszler. Always great to hear from people using iD in interesting ways.

You're right that adding an entity isn't the best way to show a marker. Unfortunately, iD has been designed for a single user case and so isn't easily extendable, but it should be possible to do what you're talking about.

iD has a number of non-OSM layers loaded by `svgLayers`. You can insert a new entry here to have the map render it:

https://github.com/openstreetmap/iD/blob/63aa47f02f06534eb3311ec869659cfdffc74f42/modules/svg/layers.js#L25-L40

The layer [`svgGeolocate`](https://github.com/openstreetmap/iD/blob/develop/modules/svg/geolocate.js) is probably the simplest one for you to use as a reference since it just draws a couple circles. It's controlled by [`uiGeolocate`](https://github.com/openstreetmap/iD/blob/develop/modules/ui/geolocate.js), the button on the right side of the map under the zoom in/out buttons/

**Comment by teiszler** [comment]
Thanks @quincylvania for the quick response. I will take a look at layers.js using svgGeolocate as an example. We have found iD to be fantastic in terms of allowing a user to design a simulation scenario. Originally we were using the existing features that were already present in iD and just coercing them for our use case, but we now have our own custom feature presets that we are using. If I can get the marker(s) to render along the path during the simulation, we can provide visual feedback to the user about how the simulation is unfolding (i.e where each object is along its path), which will go a long way to bridging the gap since the simulation takes place in an entirely separate system.

Best Regards
