### ISSUE TITLE
change displayed text for One Way default

### ISSUE THREAD

**Issue by cebderby** [openstreetmap/iD#7644]
The currently displayed label "Assumed to be [No]" for a selected way is triggering some users to wrongly add explicit oneway=no tags to the OSM database.

This text needs to be changed to "Defaults to [No]" which is the correct description and less likely to invite unnecessary tag addition

**Comment by quincylvania** [comment]
Hi and welcome, @cebderby.

I see your point, but as far as I'm aware there's no harm in explicitly adding implicit tags like this. I've seen plenty of one-way streets left without a `oneway` tag, so adding `oneway=no` gives a stronger indication that the value has been reviewed and is accurate. Sometimes a two-way road was previously one-way, and thus adding `oneway=no` helps avoid an erroneous `oneway=yes` based on old data sources.

That said, let us know if you know of any data consumers that actually have trouble with this, since our primary goal is to help people create useful data.

**Comment by papabeckum007** [comment]
> Hi and welcome, @cebderby.
> 
> 
> 
> I see your point, but as far as I'm aware there's no harm in explicitly adding implicit tags like this. I've seen plenty of one-way streets left without a `oneway` tag, so adding gives a stronger indication that the value has been reviewed and is accurate. Sometimes a two-way road was previously one-way, and thus adding `oneway=no` helps avoid an erroneous `oneway=yes` based on old data sources.
> 
> 
> 
> That said, let us know if you know of any data consumers that actually have trouble with this, since our primary goal is to help people create useful data.
