### ISSUE TITLE
hide piste arrows when pistes are disabled

### ISSUE THREAD

**Issue by mfbehrens** [openstreetmap/iD#7646]
![image](https://user-images.githubusercontent.com/58851724/83546234-a977b880-a500-11ea-8d4f-c47f198e6bd4.png)
![image](https://user-images.githubusercontent.com/58851724/83546266-b4cae400-a500-11ea-8c40-18fe3d10b528.png)
When piste information is disabled the track is still considered as oneway however this should not be the case.

**Comment by quincylvania** [comment]
Yeah pistes on highways are tricky because it essentially produces one feature with two feature types. iD expects a feature to have only one type. A feature is either toggled on or off, there can't be a feature that's "half on and half off". Since this would take a lot of development work to change, and since this piste mapping pattern is relatively uncommon, and since this is only a minor visual annoyance, I'm going to close this as low-impact.
