### ISSUE TITLE
iD performance issue with long lines

### ISSUE THREAD

**Issue by ian727** [openstreetmap/iD#7656]
Hello,

after a short discussion in the OSM Discord group I was referred here to address my problem.

I am experiencing an issue that affects the performance of iD (Windows 10, Google Chrome). When I want to continute drawing a line that already has ~200+ nodes in it, each new node I draw takes about 2-3 seconds to appear. 

This issue only occurs in the specific region I am mainly mapping. Other OSM users confirmed this slow behaviour when they tried to continue drawing lines in this region.

One example would be this: https://www.openstreetmap.org/way/799622518 

Attempting to continue drawing this exact path eastwards will result in a performance drop, taking each newly placed node a few seconds to appear. 

I already tried different computers (including high-end) and browsers. However, the fact that also other users experience the performance issue when trying to edit this line rather points at an iD related issue. When I last mapped long lines (some months back), this has never been an issue. Hence I suspect that it might have come with one of the recent updates.

I would appreciate this being looked into!

Thanks,

ian

**Comment by quincylvania** [comment]
Hello and welcome, @ian727. I've also run into this issue when mapping long rivers…

We'll have to investigate further, but I'd say the most likely cause is the validation engine calculating "crossing ways" warnings. With every node you place, iD is checking for crossings between every segment of that line and the segments of every other way within the line's bounding box. A long line has a large bounding box and lots of segments. The performance will be worse in regions with lots of data. We added the validation system last year, so before then this probably wasn't an issue.

I have a few ideas for how to make this more performant, but for now here are some strategies to reduce the issue:

- Split up long lines into smaller parts. Not only the line you're drawing, but other long lines nearby. You can use route or waterway relations as-needed to group the parts together.
- Zoom in to just the small area you want to map and reload the page. Restore your changes if any. Primarily just data in the visible area is downloaded, so this prevents iD from running computations against far-off data. Avoid navigating to areas of the map you're not mapping.

**Comment by bhousel** [comment]
#4731

**Comment by ian727** [comment]
Thanks for the replies and hints!

However, the line I gave as an example only connects to three other features and is really not that long (hardly 200 nodes). It intersects a couple more features, among them a huge wetland-relation. Could this be the reason for the performance drop?

**Comment by quincylvania** [comment]
Since #4731 triggers at >1000 nodes and predates validation, I'm thinking this is a separate underlying issue. But I'll do some debugging to be sure.

@ian727 The wetland shouldn't make much difference—iD looks for crossing highways, waterways, railways, and buildings. I noticed there are several long roads and a long stream in that area. I'd think these are part of the issue.

**Comment by jjiglesiasg** [comment]
We have the same issue in South America

**Comment by Nakaner** [comment]
@quincylvania wrote:
> * Split up long lines into smaller parts. Not only the line you're drawing, but other long lines nearby. You can use route or waterway relations as-needed to group the parts together.

In OSM, ways may have up to 2000 nodes. Encouraging users to change their mapping behaviour because the in-browser editor is unable to handle a ways with 200 nodes is a poor response. It encourages users to map large landuse features as multipolygons or using multipolygons with more than one `outer` member although it is not necessary. Unnecessary usage of multipolygons is discouraged in at least some local community (e.g. Germany) for a couple of reasons (we even have a draft policy against multipolygon overuse).

I suggest that you run validation after the way is drawn to ensure a smooth drawing experience (which is key for a good usability) and point out self-intersections either immediately after the drawing is complete or prior to upload.

**Comment by quincylvania** [comment]
> Encouraging users to change their mapping behaviour because the in-browser editor is unable to handle a ways with 200 nodes is a poor response.

@Nakaner All software has limitations. This particular issue is a bug that we're going to fix. We often provide temporary, optional workarounds so mappers can continue contributing before the fix is released.

>  It encourages users to map large landuse features as multipolygons or using multipolygons with more than one outer member although it is not necessary.

The issue is primarily about three types of line features, not landuse multipolygon members, so this doesn't seem like an immediate concern. There's also no technical problem with this mapping pattern and it's common throughout the world. If the German community wants to do something different that's up to them, but that doesn't relate to mappers broadly who just want to contribute usable data. Note the original example is in the Democratic Republic of the Congo.

**Comment by quincylvania** [comment]
I made the crossing ways validation a lot smarter about which segments it checks for crossings. Now, when continuing the original example way, each click now takes <250ms instead of several seconds. While there's always room for improvement, the fix makes iD usable here again without reducing validation functionality.

**Comment by quincylvania** [comment]
I was able to optimize performance even more, such that continuing the original example way now feels speedy and indistinguishable from drawing some short way 🤸
