### ISSUE TITLE
Add fields for route relations

### ISSUE THREAD

**Issue by mfbehrens** [openstreetmap/iD#7671]
Additional fields that would by handy:
- `distance`
- `duration`
- `ascent`/`descent`
- `roundtrip` (= yes/no)
- _maybe_ `colour`

**Comment by maro-21** [comment]
distance, duration and colour are already there

**Comment by quincylvania** [comment]
@mfbehrens99 Okay, I added fields for `ascent`, `descent`, and `roundtrip` to the pertinent route presets. We already support the other fields.

Note that iD has limited fields for the generic `type=route` preset since we can't be sure the fields will be relevant to all kinds of routes. For example, `roundtrip` doesn't really make sense for utilities.
