### ISSUE TITLE
No delete button for a point

### ISSUE THREAD

**Issue by gdutkowski** [openstreetmap/iD#7682]
I am trying to delete a bike rental point as it is no longer operating.
OSMID:4334994969
According to the help "To delete a point,  right-click on the point to select it and show the edit menu, then use the  Delete command."
When I do that I only get the options to Downgrade.
What am I doing wrong?
![image](https://user-images.githubusercontent.com/62486564/83981534-20c6a580-a962-11ea-9fe7-b377644af933.png)
Chrome Version 83.0.4103.61

**Comment by quincylvania** [comment]
Welcome, @gdutkowski.

The Delete command only becomes available after you Downgrade. This is helpful since the address is probably still valid even if the business doesn't exist anymore. But we should make this clearer in the help documentation, and possibly consider supporting Delete and Downgrade on the same features via different hotkeys.

**Comment by jidanni** [comment]
(I got used to it as sort of an undocumented safety feature, requiring two steps for complete deletion.)

**Comment by gdutkowski** [comment]
Thanks.
The two step deletion is a useful way of doing it, but I agree that it
needs to be documented.
Greg Dutkowski
+61 0362238495/0408238495
1 Cascade Road, SOUTH HOBART.

**Comment by quincylvania** [comment]
> consider supporting Delete and Downgrade on the same features via different hotkeys.

I ended up doing this. The delete shortcut is the same, but now the deletion occurs immediately. Pressing backspace alone without cmd/ctrl now triggers the downgrade. This setup will let us do #6756 and maybe #6475.

<img width="421" alt="Screen Shot 2020-09-28 at 5 21 06 PM" src="https://user-images.githubusercontent.com/2046746/94487457-07ff2b80-01af-11eb-810c-d2f366fc7f59.png">

Supporting both operations at once should avoid this confusion around not being able to delete features. Since most new users probably press backspace anyway to delete features, we still have the safety of downgrading before deleting, while power users can skip the downgrade step.

See also #6862 about possibly letting backspace alone delete the feature (after downgrading completely).
