### ISSUE TITLE
Add man_made=windpump to presets

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/iD#7709]
Hi there.

I would like to suggest adding [man_made=windpump](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwindpump) to iD's presets.

Regards.

**Comment by Adamant36** [comment]
Mind if I ask how people know it's a windpump from the satellite images, or even on the ground, instead of just a regular windmill? Because the example image on the wiki just looks like a regular windmill to me. It's even called a "windmill" in the file name. So, I'm thinking the distinction between them isn't that clear, likely most (or all) windpumps are also inherently windmills. Therefore that adopting this tag could lead to a lot of needless miss-tagging and fragmentation. If windpumps are just a type of windmill, then something like windmill:type=windpump should be used instead of having a separate man_made tag for it.

**Comment by AntMadeira** [comment]
Hi, Adamant36.
Well, those are two completely different things. One is a pump and the other is a mill. They not only look different (at least here in Europe), they also have different functions and can clearly be distinguished from satellite images or on the ground, just like so many other features. A windpump is a pump powered by wind and windmill is a mill (used to grind something, usually cereals) powered by wind.

**Comment by AntMadeira** [comment]
Well, now that I read more about it, I understand your question better.
This is an issue to debate on the tagging mail list (I see you posted the same question on the wiki), but here in Portugal, windmill is a windmill, it's never confused with a windpump (especially the kind with those metal blades). I don't really think they even should be called windmills, since they don't grind anything, but that's an etymologic question that it's not relevant here.
If you think it worth the try of changing the tag, go ahead and make the proposal on the mailing list, but I was just asking to add a new preset based on what already existed on the wiki.

**Comment by 1ec5** [comment]
I assume you’re discussing this image:

[![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Water_Pumping_Windmill.jpg/320px-Water_Pumping_Windmill.jpg)](https://commons.wikimedia.org/wiki/File:Water_Pumping_Windmill.jpg)

This is a classic design for an American-style windpump. In the Midwest where I’m from, windpumps are colloquially called windmills, even though they’re unrelated to windmills, because actual windmills are rare (pretty much only at minigolf courses). The person who uploaded the image to Commons was probably unaware of this distinction, but Wikipedia and the OSM Wiki only use it as an illustration of a windpump, not a windmill.

Their function aside, windpumps and windmills differ in much the same way that `man_made=mast` differs from `man_made=tower`. Both are colloquially called towers, too, but we still have separate presets for them because one is more structurally substantial than the other.

Windpumps are difficult to spot in aerial imagery because they have such a slender profile, but I’ve been able to spot a few based on the shadows they cast:

OSIP 6in | Mapbox (3in)
----|----
[![OSIP 6in](https://user-images.githubusercontent.com/1231218/86491310-4e173100-bd1f-11ea-82c2-6037b1f1fcc3.png)](https://ideditor.netlify.app/#background=OSIP_6in&disable_features=boundaries&map=20.00/39.28272/-84.28522) | [![Mapbox](https://user-images.githubusercontent.com/1231218/86491308-4c4d6d80-bd1f-11ea-8714-0138b952baed.png)](https://ideditor.netlify.app/#background=Mapbox&disable_features=boundaries&map=21.00/39.28272/-84.28522)

**Comment by quincylvania** [comment]
A good icon should help people distinguish these from windmills. We can add "windmill" as a search term so people will see both and hopefully learn about the distinction. I'd assume windpumps are widely mistagged as windmills in the US.

**Comment by ghost** [comment]
'aerorotor' is a genericised trademark for the punched steel ones that people sometimes call them by in New Mexico.

**Comment by quincylvania** [comment]
I made an icon for this that'll be in the next release of [temaki](https://ideditor.github.io/temaki/docs). It's tough to keep the blades from blurring at small sizes, but the general shape is there.

<img width="181" alt="Screen Shot 2020-10-19 at 10 24 31 AM" src="https://user-images.githubusercontent.com/2046746/96464013-54111f00-11f5-11eb-920f-caa1bb623ce7.png">

**Comment by bhousel** [comment]
oh that's a nice icon 🤩
