### ISSUE TITLE
potential validation: turn restriction with same 'from' & 'to' member

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7759]
So far i understand, the turn restriction relations are only used for navigation routing engines. And it seems that turn restriction with same 'from' and 'to' member makes no sense for these routing engines, because they wouldn't use such a route even without having these restrictions. 

Example object: https://www.openstreetmap.org/relation/7809294

If others agree, please display a warning message while creating and while editing on objects which are involved of such turn-r.-constructions.

**Comment by bhousel** [comment]
The restriction you linked to looks like a typical No-U-Turn restriction.
These are pretty common, and they have the same 'from' and 'to' members.

**Comment by quincylvania** [comment]
> The restriction you linked to looks like a typical No-U-Turn restriction.
> These are pretty common, and they have the same 'from' and 'to' members.

Yep, I don't see an issue here.

I'm sure there are plenty of invalid combinations of relation members, but iD doesn't know enough about the OSM schema (such as it is) to flag them.

**Comment by sorcrosc** [comment]
U-turn restrictions are obviously very common, they apply at least to all intersections and all solid-line roads and in other cases, but we do not use relations for these.
We do not use no_u_turn relations form one way to itself. This would mean that we have to create two relations for each way and two more every time the way is split in two segments... Fortunately, many mappers realize for themselves after a while that there is no point in putting all of these relations in place because navigators simply assume that u-turn is not allowed by default.

Notice OSM wiki now have this note about no u-turn relations:
"to add a no_u_turn restriction relation seems only useful if from-member and to-member are different way objects"
https://wiki.openstreetmap.org/wiki/Relation:restriction

I believe iD should not have that easy add button for these relations as they are not generally accepted or considered useful.
Please reopen and consider this issue. Do you prefer I open another one?

**Comment by 1ec5** [comment]
> they are not generally accepted or considered useful

It’s a bit more nuanced than that. See [this discussion](https://wiki.openstreetmap.org/wiki/Talk:Relation:restriction#u-turns) for context about the note that you quoted and the change I made to make it less proscriptive.

**Comment by sorcrosc** [comment]
Thanks. I just added my thought there
