### ISSUE TITLE
Add preset for information centers

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/iD#7764]
The wiki recommends `tourism=information + information=office`. I see the preset comes up if you specifically search for "tourist information office", but it would be good if it did when searching for "information center." I think the title for the office=guide preset might have to be altered to. Thanks.

**Comment by quincylvania** [comment]
@Adamant36 Looking at this, these tend to be called [visitor centers](https://en.wikipedia.org/wiki/Visitor_center) in the US at least, so I changed the preset name and added a bunch of search terms.

"Tour Guide Office" seems okay for `office=guide` since tour guides are distinct from information centers.
