### ISSUE TITLE
small bug: two edits have the same changesets_count

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7801]
The first two edits of this user have `changesets_count=1`:
https://www.openstreetmap.org/changeset/88161601
https://www.openstreetmap.org/changeset/88162476

**Comment by JamesKingdom** [comment]
I don't really think this is a bug, just the order which iD grabs info about the user.  
It's caused if you open multiple tabs of the editor and make edits in both tabs, because it doesn't redownload the user data (including changeset count) until you refresh the tab.  
I suppose iD could redownload the user data before each commit but that seems a bit wasteful for a small issue.

**Comment by quincylvania** [comment]
I agree with @JamesKingdom here. It seems like an edge case that's not a huge problem and wouldn't be trivial to fix. Changeset tags like this are more of a general reference then a reliable measure anyway, since people can fake them. If someone cares about the exact changeset index then they'll need to examine the database-assigned metadata.

**Comment by danieldegroot2** [comment]
Related #10050

See also https://github.com/openstreetmap/openstreetmap-website/issues/2224

cc: @mmd-osm (for your information that this issue exists)
