### ISSUE TITLE
Rename reflect operation to flip

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#7824]
Over in OSMUS Slack, @TheAdventurer64 was asking about the “Reflect features across the longer/shorter axis” operations. I think these operations would be more discoverable to English speakers if they were called “Flip features across the longer/shorter axis”. Is there a technical distinction between flipping and reflecting?

**Comment by quincylvania** [comment]
> I think these operations would be more discoverable to English speakers if they were called “Flip features across the longer/shorter axis”.

Good idea. I've seen other graphics apps use "flip", which is a better action word. People flip things like pancakes and burgers. People don't reflect anything except the contents of their souls 😱

> Is there a technical distinction between flipping and reflecting?

I haven't heard of one, but I'm happy to round off corners on technical jargon. Like how iD uses "Square" instead of "Orthogonalize".
