### ISSUE TITLE
Imagery max zoom

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/iD#784]
When viewing http://www.openstreetmap.us/iD/master/#layer=bc_mosaic&map=19.00/49.17700/-122.89100 iD does not load imagery beyond z17. This layer should go up to z20

**Comment by nighto** [comment]
Sorry for bringing up such an old issue, but I just found some clouds on the Bing imagery, which I'm used to use in Rio de Janeiro, Brazil, and found out that Mapbox has imagery up to z17. However, when you zoom to z18, it tries to fetch such images and fail. Would it be possible to adjust max zoom on iD, or should I make a pull request on editor-imagery-index so that *in my area* make it go only until z17?

Thanks.

**Comment by nighto** [comment]
The workaround I have been using is zooming in a lot on the browser, which has the inconvenience of having the interface elements huge, but at least I can draw things easily.

![image](https://cloud.githubusercontent.com/assets/397851/5986591/8c1ce5de-a8e5-11e4-9e6f-ec298a96d540.png)
