### ISSUE TITLE
Add Units field to Apartment Building

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7856]
A units field could tell a person how many units are in a apartment, similar to the rooms field for a hotel.
Tag with `building:flats=`.

**Comment by scottdurant** [comment]
Hello, I'm new to open source and would like to try to solve this issue. Would I need to edit the data/presets/presets/building/apartments.json file? If you could point me in the right direction that would be much appreciated, thank you!  @TheAdventurer64 @quincylvania

**Comment by thibaultmol** [comment]
@scottdurant seeing as they haven't responded yet. I also just made my first attempt at a contribution to iD.

So from what I understand, that file is indeed the correct one. Now you should clone iD (but maybe only the latest version as described here https://github.com/openstreetmap/iD#cloning-the-repository ) and make sure to make a new branch in your own repo of iD with a descriptive name of what you're going to change.
See more info about contributing here: https://github.com/openstreetmap/iD#cloning-the-repository

(This last one I'm only like 70% sure about. But build iD before you make your pull request, because you'll that when you change one of the preset files. It will also change the main presets.json file which contains all of them https://github.com/openstreetmap/iD#building-id )

**Comment by quincylvania** [comment]
@scottdurant @thibaultmol Thanks for your interest! Apologies on not getting back to you, but no one has been working on iD full-time recently due to changes in the support model. I'll likely be back soon, at which point I'll be happy to assist with your first contributions 🙂

**Comment by quincylvania** [comment]
Done in  #7896 by @ogbeche77.
