### ISSUE TITLE
Can we change from transifex to translatewiki

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#7870]
Translatewiki does not invalidate a translation when the source string changes. This helps translators a lot, when minor changes  (e.g. spelling, wording, small additions) in the source strings occur.

**Comment by maro-21** [comment]
It's expected behavior, if something has been changed, it means that the translation should be changed too.

Translatewiki is the worst CAT tool from all I've known. It doesn't have as many options as Transifex. It actually doesn't have any options except string search. I wouldn't even call it a CAT tool. And Transifex is really handy.

**Comment by quincylvania** [comment]
#7508 is about the possibility of switching translation platforms. I agree there are times it'd be great to not invalidate all translations for an English string change.
