### ISSUE TITLE
Some fields are too restrictive about units

### ISSUE THREAD

**Issue by BigPeteB** [openstreetmap/iD#7884]
Fields for some tags like `width=*` and `length=*` are given titles "Width (Meters)" and "Length (Meters)". They don't offer a dropdown for selecting units, and they strip units if you enter them. This is contrary to the wiki, which for both of these tags explicitly says units are acceptable. (In fact, `width=5'` is the 25th most common value for that tag!)

One application where this is particularly important is runways, which in North America have their length and width legally given in feet.

Similar issues are #3614, #5658, and #7129.

**Comment by quincylvania** [comment]
Hello and welcome, @BigPeteB.

I agree we should have unit dropdowns for measurement fields like these. OSM makes it tricky since people could put anything in any tag, so iD would have to deal with all types of values. The fields would also have to be localized for different representations of units in different cultures.

Thanks for linking to the other issues. See also #6707. I'm going to close this as a duplicate since I think the other issues cover it.
