### ISSUE TITLE
Implement Ctrl+Enter shortcut to save changes

### ISSUE THREAD

**Issue by nicolasmaia** [openstreetmap/iD#7888]
It would be handy to have.

**Comment by manfredbrandl** [comment]
The shortcut CTRL + S is not enough? Press ? to see all shortcuts.

**Comment by nicolasmaia** [comment]
Thanks for the heads-up. It would be nice to have it as ctrl+enter as so many applications already use it as such (including Github).

**Comment by bhousel** [comment]
This was #4234 and #7108 , which I rejected because I was concerned about people uploading their changes accidentally before they finished writing their changeset comment.

**Comment by quincylvania** [comment]
I agree with the prior assessments that this probably isn't worth the risk. Actions in an app like iD should be hard to do by accident and/or easy to undo. Since uploading is hard to undo, it should be as deliberate as possible.

Keyboard users can pretty easily use tab navigation to focus and press the Upload button without using a mouse.
