### ISSUE TITLE
telecom=line raises validation error

### ISSUE THREAD

**Issue by donalhunt** [openstreetmap/iD#7934]
This seems similar to Issue # [6395](https://github.com/openstreetmap/iD/issues/6395)...

> Line should be a closed area based on the tag "telecom=line"

I suspect this is a result of the tag and value not bring present in [data/taginfo.json](https://github.com/openstreetmap/iD/blob/develop/data/taginfo.json).

Happy to submit a PR to include it.

**Comment by donalhunt** [comment]
Screenshot of the validation error:

![Screenshot from 2020-08-27 22-25-44](https://user-images.githubusercontent.com/5854402/91497553-1dceb780-e8b6-11ea-8652-f83bafb0c1ed.png)

**Comment by quincylvania** [comment]
Hi and welcome, @donalhunt. This was indeed caused by iD not know that `telecom` can be used on lines. I added a fallback preset to clarify this. Looks like `telecom=line` doesn't have much usage yet so I'm holding off adding a preset for that.

Also, the taginfo.json file is derived and just consumed by the Taginfo site. The preset data files are in data/presets.
