### ISSUE TITLE
Show warning if changeset comment is too long

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#7943]
ATM, I can write a very long changeset comment and save, but the comment will get cut off at a limit. Ideally, the Editor would warn me, once I am over the limit.

It seems to 255 Chars max.

Screenshot: No warning ATM
![image](https://user-images.githubusercontent.com/111561/91899246-2865c400-ec9d-11ea-8325-3a538aa2bc49.png)

**Comment by mmd-osm** [comment]
> It seems to 255 Chars max.

Yes. As with any tag key/value pair, the same 255 unicode character limit also applies here.

**Comment by mikini** [comment]
Second this, same just bit me in [changeset 90422778](https://www.openstreetmap.org/changeset/90422778).

In the old days of 90s HTML you`d just set a length/size/limit on the input/textarea and the browser would prevent anymore input than that in the UI.

A quick look seems to suggest that the [maxlength attribute on form elements](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-maxlength) is still supported in HTML5.

**Comment by bhousel** [comment]
> A quick look seems to suggest that the [maxlength attribute on form elements](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-maxlength) is still supported in HTML5.

Yes, a long time ago iD did use maxlength for this: https://github.com/openstreetmap/iD/pull/2411/commits/8b896b8b84e858416b738a64cf17ca179682dd46

But that approach doesn't really work for strings that contain unicode - https://github.com/openstreetmap/iD/issues/6817 has more on why this is a hard problem.

**Comment by mmd-osm** [comment]
... in particular https://github.com/openstreetmap/iD/issues/6817#issuecomment-579758275 and  https://github.com/openstreetmap/iD/issues/6817#issuecomment-642186244

**Comment by quincylvania** [comment]
We might show a remaining character count as your input gets long in textarea fields, instead of some obtrusive warning. These are fairly standard nowadays.

**Comment by danieldegroot2** [comment]
@tyrasd it currently
- has context only on new objects and exceeding limit (no label on hover, otherwise ambiguous 'bar', scroll bar or bug).
(also, a horizontal filling/emptying bar usually indicates ongoing completion or remaining time, not a scale as such)
- is only visible when typing (and may not be noticed by users typing in the plain tags field at the bottom).
- goes outside the input field UI element when exceeding length.

I would suggest using a (standalone) element. Either a (coloured) bar, number, text, or warning (combinations possible). It should be the color/text which changes, not the element itself.

Sidenotes regarding truncation;
- A second input field could be shown for some tags when the user exceeds the limit
(may be undesirable as it users may see this a solution also when the text should be shortened.)
- Some forms will gray out the submit button.
(There is no submit button. Instead of truncation other fields/operations could be locked with hover text to shorten the input. However, this would apply to quite a few areas -excluding plain tags field-, not covering everything and may be undesirable.)
- Translators allow exceeding the limit on the input, but will either truncate or fade out the overflow of the output.
(There does not seem to be a comparable aspect to the editor.)

**Comment by tyrasd** [comment]
hey @danieldegroot2 in parts this is by design:
* the indicator is meant to grow outside the bounds of the containing element, to convey the concept that something is not right. 
* the indicator is hidden when the corresponding input field is not focused, to minimize visual noise/clutter. it's also unnecessary to show on non-focused input fields, as they can by definition never exceed the limit 
* the indicator is meant to convey the concept of "remaining space", that's why it is not shown for input fields which are far from reaching the limit and only shown when it starts to become relevant.

see also #9390

I agree that a tooltip / hover text could be added, such that the functionality of the indicator is more easily discoverable, even before the tooltip for "limit exceeded" is eventually displayed. Thanks for that suggestion!

> I would suggest using a (standalone) element. Either a (coloured) bar, number, text, or warning (combinations possible). It should be the color/text which changes, not the element itself.

I'm not sure I fully understand what you're proposing, exactly. Could you perhaps sketch out what you're thinking of? 

> A second input field could be shown for some tags when the user exceeds the limit

You mean like adding `description_2`, `description_3`, etc. if a description is too long for a single OSM tag? As far as I know this is not an established practice among mappers and I don't know any tools which support this. Therefore I'd really like to avoid this.

> Some forms will gray out the submit button.

This would have the downside of potentially spotting errors pretty late (i.e. on upload to OSM), where potentially a large number of mistakes could have accumulated. I oped for an indicator directly on the affected input fields to avoid this.

> Translators allow exceeding the limit on the input

What "translators" are you talking about?

> […]  will either truncate 

This is what iD currently does and has done for a long while. The only thing that changed is that the users are made aware of this truncation by means of the indicator.

> […] or fade out the overflow of the output.

"Fading out" in the form of highlighting the offending over-the-limit characters (for example in the form of a red font, similar to how twitter implements this) would have been a favorite solution for me as well, but it would  unfortunately have been unreasonably intricate and time-consuming to implement. This is because the UI fields use "regular" html "textarea" input fields, which do not allow this kind of detailed styling.

**Comment by danieldegroot2** [comment]
Adding hover text may suffice, though preferably no interaction is needed to know what it is displaying.

After I think about it more, I've chosen to adjust the most common implementation which [quincy and I both suggested](https://github.com/openstreetmap/iD/issues/7943#issuecomment-703859277):

**Adding a cell in the lightgrey header bar with the character count**
for which the remaining character count (i.e. `10` or `-1`) or a combination of the running character count and total character count (i.e. `260 / 256`), since that'll work also for small input fields. The existing notification when you get over 256 characters can then stay.

It would jump around depending on the field, but I don't think I'd mind it too much if it's only shown when focused.

![image](https://user-images.githubusercontent.com/67521919/216159411-a9083d16-5eab-46db-808b-68a2d9f0ce77.png)
