### ISSUE TITLE
Question: shops and stores

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#7971]
There are 89 "store" and 50 "shop" presets - is there any rule why some of them are shops and some stores?

**Comment by quincylvania** [comment]
@maro-21 These words are generally synonyms, but culturally one may be preferred over the other for a given type of businesses. In the US "store" is more common, while I think "shop" is more common in the UK. To my American ears, "Department Shop" or "Shoe Shop" just sound off.

Since iD's default language is American English, we try to use terms that make the most sense here.

**Comment by maro-21** [comment]
So shouldn't shops be renamed to stores?

**Comment by quincylvania** [comment]
@maro-21 I wasn't clear, but I mean some places are still often called shops even if "store" is more common, and often it doesn't matter which.
