### ISSUE TITLE
Add Tower Viewer Preset

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/iD#7985]
A pair of binoculars (also known as a tower viewer) is a pair of binoculars fixed in place with a pole. It can typically be found on touristic locations, viewpoints, on top of panoramic towers or occasionally on a nature reserve (often in a leisure=bird_hide). Source: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbinoculars

Add the tag `amenity=binocular`.
Fields for this tag could include:
- Fee - Used to specify if the binoculars require a fee to use or not. If `fee=yes` is added, add the Payment Types field to specify what sort of payments the binoculars accept. More info here: 
- Direction Used to specify which way binocular users can see. More info here: https://wiki.openstreetmap.org/wiki/Key:direction

**Comment by quincylvania** [comment]
I fine with this since it's in use and documented, but before the usage grows much more I'd recommend switching to a more generic tag like `amenity=tower_viewer` and then specifying the type with a subtag like `tower_viewer:scope=binoculars` / `tower_viewer:scope=telescope`. Otherwise there's no good way to tag mounted telescopes.
