### ISSUE TITLE
Doesn't recognize vending machine tagging as "Parcel Pickup/Dropoff Locker" when order of values in vending tag is different

### ISSUE THREAD

**Issue by xuiqzy** [openstreetmap/iD#7988]
When an object is tagged with `amenity=vending_machine` and `vending=parcel_mail_in;parcel_pickup` instead of `vending=parcel_pickup;parcel_mail_in` (note the different order of values), it is displayed as only a general`Vending Machine` in the title/type (instead of `Parcel Pickup/Dropoff Locker`) which is a bit confusing for a parcel pickup and drop-off station.
If you rearrange the values, it is correctly recognized.
The order of values in vending (or in most tags, except destination, etc) shouldn't matter for the interpretation as far as I can see.

If this is not a huge thing to fix, I could implement it? But I'm not familiar with the project, so I'm asking here first.

**Comment by matkoniecz** [comment]
> If this is not a huge thing to fix, I could implement it?

Maybe it should be implemented as validator proposing to change `vending=parcel_mail_in;parcel_pickup` into more common form?

Current usage is 211 items ( https://overpass-turbo.eu/s/Y81 ) so support for such rare tag may be rejected - I would wait for decision from maintainers.

**Comment by quincylvania** [comment]
Hi and welcome, @xuiqzy. I agree the order of these values shouldn't really matter, but it's really helpful if they're consistent for tagging presets.

Since [4800 features use iD's order and only 200 use the other](https://taginfo.openstreetmap.org/search?q=parcel_mail_in#values), a validation rule as proposed by @matkoniecz sounds okay. If the uses were closer to even then we'd look at a more advanced solution.
