### ISSUE TITLE
Rotate cones 180 degrees for 'traffic_signals:direction' and 'railway:signal:direction' when using numbers for the value

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#7989]
It's nice to see the cones when using `direction=*`, `traffic_signals:direction=*` and `railway:signal:direction=*`.

For `direction=*` usually the cones point to this direction like a person looks when sitting on a bench or to this direction a face of traffic sign is showing. 

But for `traffic_signals:direction=*` and `railway:signal:direction=*`. the orientation seems to have an oppositional logic. The direction means the flow of the traffic but then the traffic signal is looking in opposite direction. Seems this is also implemented for the forward and backward value. So if you select forward flow the cones points backward. 
But if somebody uses a number for the flow direction, then the cones are also pointing in the flow direction and not as usual in opposite signal direction, hope I don't mixed something. So should we maybe also switch the cones for the number used cases to 180 degrees?

(By the way, the second example is a good one also telling why figures are sometimes better than using `forward/backward`, because on shared nodes (connected residential area), splitted nodes or junction nodes these values like `forward/backward` will be not distinct enough - if you use ``forward/backward` `then you will see 2 cones)

This is a example with probably a correct tagging, but the cones are not showing in the usual signal direction:
https://www.openstreetmap.org/edit?node=2030955570
![image](https://user-images.githubusercontent.com/47290585/93033783-01fa3e00-f638-11ea-8b02-c245f677db1c.png)

This is a example with probably a wrong tagging, maybe it was forced because the cones are drawn opposite:
https://www.openstreetmap.org/edit?node=1684161503
![image](https://user-images.githubusercontent.com/47290585/93033773-f7d83f80-f637-11ea-8e21-819cce7d4e00.png)

**Comment by quincylvania** [comment]
@sun-geo I'm pretty sure iD is doing the right thing here, but the underlying issue is that these tags shouldn't really have numeric values. They're intended for routers to determine which features affect traffic moving along the line in a particular direction. We shouldn't expect routers to guess based on an absolute angle.

The cones look wrong in this type of situation because it's ambiguous.

<img width="629" alt="Screen Shot 2020-09-14 at 8 25 16 AM" src="https://user-images.githubusercontent.com/2046746/93085851-3a177600-f664-11ea-8401-a2b42204c902.png">

So a better alternative is to add detail and place the signals where the traffic actually stops

<img width="600" alt="Screen Shot 2020-09-14 at 8 26 25 AM" src="https://user-images.githubusercontent.com/2046746/93085934-59ae9e80-f664-11ea-9dde-9640a4995bcd.png">

In the case of areas attached to lines, you can either reverse or disconnect the area.
