### ISSUE TITLE
highway=elevator showing "big street" warning instead of "disconnected"

### ISSUE THREAD

**Issue by carstenhag** [openstreetmap/iD#8018]
So while reporting this, I have found #6812, which likely introduced the "Elevator is disconnected" warning.

Just added a point, added highway=elevator and then I got a "Größere Straßen..." warning. Maybe it's due to highway=elevator not being translated to german? "Größere Straßen" is definitely wrong :D

Related, maybe that's also the reason I could not find "Aufzug" via the point search.

![Bildschirmfoto 2020-09-24 um 08 08 21](https://user-images.githubusercontent.com/3776997/94107310-7b1a4200-fe3d-11ea-8630-9d56a86296e2.png)

**Comment by carstenhag** [comment]
After connecting a line to it, it now shows "Aufzug". Weird.

![Bildschirmfoto 2020-09-24 um 08 15 14](https://user-images.githubusercontent.com/3776997/94107579-18757600-fe3e-11ea-8071-8f8fdea38765.png)

**Comment by quincylvania** [comment]
Oh yeah, this happens because preset matching is dependent on the geometry. Since iD only matches nodes with `highway=elevator` to the Elevator preset if they're part of ways, and since the names in the validation messages are based on preset names, the fallback name is shown here.

In this case iD knows that the node should probably be part of a way, so we can show the preset name instead.

Here's what this looks like in English for anyone interested:

![Screen Shot 2020-09-24 at 8 13 55 AM](https://user-images.githubusercontent.com/2046746/94143554-fd0a6b00-fe3d-11ea-8fb1-c2c92efc069d.png)

**Comment by carstenhag** [comment]
Thanks for the quick fix :)

**Comment by quincylvania** [comment]
@carstenhag I'm still not sure why the translation of "Highway Feature" would be "Big Street…" in any language but I'll leave that up to the translators.

**Comment by sun-geo** [comment]
> "Highway Feature" would be "Big Street…"

@carstenhag see [here](https://www.transifex.com/openstreetmap/id-editor/translate/#de/$/11399151?q=text%3A'Highway+Feature')

![image](https://user-images.githubusercontent.com/47290585/94159656-16360a80-fe84-11ea-9c7c-7e59f8eb91fb.png)

**Comment by carstenhag** [comment]
Thank you. Yeah, that translation is not good :D. I can see why the person translated it that way, because a highway is of course a big street usually, but in OSM terms a highway can be a footway of course.

I just changed it to "Straßen/Wege..." which means streets and paths. The "..." were used at other preset names as well, so I kept them.
