### ISSUE TITLE
I have setted up osm for india on my machine using docker ! how can i edit the osm map of india which is in pbf file.  can i use this to edit my changes locally ?

### ISSUE THREAD

**Issue by deveshbamola** [openstreetmap/iD#8033]
i want to edit the osm file of india which is .pbf format and add some custom text or custom location on the map on my local machine! "how can i achieve that" with this

**Comment by quincylvania** [comment]
Welcome, @deveshbamola. You can't edit a pbf file directly with iD, but if you have your own fork of the [OpenStreetMap backend](https://github.com/openstreetmap/openstreetmap-website) then you can [point iD to edit that](https://github.com/openstreetmap/iD/blob/5239017cdfce0f78e9948cc4a58909a8c6948bb8/index.html#L48-L58) instead of the main map.

For more details about setting up your fork, check out the [dev mailing list](https://lists.openstreetmap.org/listinfo/dev), the [osm-dev IRC channel](https://wiki.openstreetmap.org/wiki/IRC), or one of the many other [community resources](https://community.osm.be/).
