### ISSUE TITLE
Background panel could be thinnner

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8043]
Actually if the Background panel could automatically squeeze out the whitespace in itself,
![1610-8](https://user-images.githubusercontent.com/1230959/94883610-a2a48680-049d-11eb-9e26-8c9523ca3a09.jpg)
it could be a lot thinner.
This is important also when making an offset, as more of the screen should be visible while doing so.
Yes the two lines of text at the bottom could be made into three, and then the whole panel could be made thinner.

**Comment by jidanni** [comment]
None of these lines uses up all the width given to them:

```
Esri World Imagery (Clarity) Beta
￼
Mapbox Satellite
￼
Maxar Premium Imagery (Beta)
￼
Maxar Standard Imagery (Beta)
￼
OpenStreetMap (Standard)
￼
OpenTopoMap
￼
Stamen Terrain
￼
NLSC General Map with Contour line
￼
Taiwan Land-Section Data
￼
Taiwan Village Boundaries
￼
Taiwan e-Map Open Data
```

**Comment by manfredbrandl** [comment]
I suggest the white space to be used to stretch the sliders instead.

**Comment by quincylvania** [comment]
> I suggest the white space to be used to stretch the sliders instead.

@manfredbrandl I coincidentally did this already for the next release, along with support for values up to 300% instead of 200%.

<img width="386" alt="Screen Shot 2020-10-02 at 1 44 42 PM" src="https://user-images.githubusercontent.com/2046746/94953384-7694ff80-04b5-11eb-8f1f-b2a5d1fdc7c2.png">

@jidanni There could be longer layer names shown in different parts of the world or in different languages. Sure we could always make things denser, but the point is for the UI to look and feel good, not to fit the most information. The pane isn't monstrous, only 400 pixels wide at most.

We'll need some redesigns for smartphone screen sizes, but we don't need issues for every minor thing.
