### ISSUE TITLE
Disused:amenity transforms area in line

### ISSUE THREAD

**Issue by ferdi2005** [openstreetmap/iD#8051]
If I use disused:amenity as tag and theatre as value, the areas becomes a line.
<img width="1555" alt="Schermata 2020-10-04 alle 11 53 33" src="https://user-images.githubusercontent.com/19609180/95012366-3b6f0980-0638-11eb-9285-13a2d0b2673b.png">

**Comment by sun-geo** [comment]
Which behavior would you expect instead?

**Comment by ferdi2005** [comment]
@sun-geo I’d expect to see it as an area, greyed out or with some indication of disused. I’d certainly not expect to see it as a line.

**Comment by quincylvania** [comment]
Hi and welcome, @ferdi2005. This happens because OSM doesn't have a separate `area` geometry type, so iD guesses what's an area based on the tags. Since iD didn't know whether `disused:amenity` should be an area, it falls back to line. You can add `area=yes` to anything like this to make it an area.

I added an unsearchable Disused Amenity preset to fix this.

**Comment by ferdi2005** [comment]
@quincylvania and can’t you add that iD recognizes disused:amenity as an area tag like amenity?

**Comment by quincylvania** [comment]
>  can’t you add that iD recognizes disused:amenity as an area tag like amenity?

Yes, this is what I did here:

> I added an unsearchable Disused Amenity preset to fix this.

**Comment by ferdi2005** [comment]
@quincylvania Thanks!

**Comment by rhhsm** [comment]
> I added an unsearchable Disused Amenity preset to fix this.

The issue also applies to buildings, both disused: and abandoned: . In addition, these buildings no longer appear on the OSM map. I'm tempted to use building=house & disused=yes instead of disused:house=yes even though this is discouraged, because the issue doesn't occur here. I think disused:house=yes should be displayed the same as building=house & disused=yes (brick red area with dotted perimeter).

**Comment by quincylvania** [comment]
@rhhsm Yes, there are many combinations of `status:key` that people use in OpenStreetMap, but I think it'd be over-the-top to try and support all of them as presets. I'd discourage using the `disused:building` tag specifically, since a building is still a building even when no one is using it.

**Comment by rhhsm** [comment]
Consensus on the OSM wiki is that the simple tag is discouraged in favour of the prefix for reasons given here for instance https://wiki.openstreetmap.org/wiki/Key:abandoned: I think the software should be adapted to the consensus, not the other way around. Probably to create presets for all cases is not the most elegant solution (but I'm not a coder).

**Comment by matkoniecz** [comment]
1) https://wiki.openstreetmap.org/wiki/Key:abandoned is for abandoned, not disused

2) https://wiki.openstreetmap.org/wiki/Key:abandoned specifically indicates that `building=*` + `abandoned=yes` is superior to `abandoned:building` 

3) I just edited [https://wiki.openstreetmap.org/wiki/Key:disused:](https://wiki.openstreetmap.org/wiki/Key:disused:) to indicate that `disused:building` is a bad idea (feel free to discuss it on wiki/tagging mailing list/OSM Telegram/US Slack/...)

**Comment by HolgerJeromin** [comment]
Your link lost the `:`. Right is: [https://wiki.openstreetmap.org/wiki/Key:disused:](https://wiki.openstreetmap.org/wiki/Key:disused:)

**Comment by matkoniecz** [comment]
> Your link lost the :

Thanks, fixed. Github tried to be helpful and delinked trailing :
