### ISSUE TITLE
This can't be done because not enough of this is currently visible

### ISSUE THREAD

**Issue by DujaOSM** [openstreetmap/iD#8068]
I noticed that, with every new release, iD becomes increasingly picky about operations with objects that cannot fit into the current viewport, complaining that "This can't be X because not enough of this is currently visible". While I understand that iD has limitations, many new checks seem arbitrary, and operations that used to previously work just fine seem to be disabled for no apparent reason. And workarounds are clumsy if not outright impossible. Examples:

- You cannot copy (or paste) a long way anymore. Often, I need to split an admin boundary from a river, or draw a landbase multipolygon along a curvy road, which used to be easy by copying the object and pasting it along the original, then changing tags. 
- You cannot delete long lines, even if you take care to untag and disconnect them. I clean up a lot of botched CORINE landbase import, whose forest boundaries are dead wrong and need to be deleted, but I have to do that point by point or dissecting into segments.
- While the recently added "group disconnect" feature is very useful, guess what, long ones "can't be disconnected because not enough of this is currently visible". So I still cannot disconnect a 10-km national park boundary from forest limits that someone has "helpfully" stitched together. 

I'd rather have those features available and live with an occasional bad side effect (that I haven't encountered in my >3000 changeses with iD as far as I remember). Please try to remove or reduce those limitations.

**Comment by quincylvania** [comment]
Hi @DujaOSM. Yes, we've recently filled in a few missing safety checks. These are meant to avoid unintended effects for everyone, but particularly new users. It shouldn't be possible to duplicate Iceland, delete the Nile, or disconnect the Autobahn by accident.

That said, we're also trying to make iD scale to the needs of advanced mappers. #2929 is about manually allowing disabled operations for cases like the ones you mentioned. I think we can focus on that solution.

**Comment by AntMadeira** [comment]
This would be most welcome. Although the safety measure is important, not being able to delete or move an element because of this is very annoying and usually leads to problems like having to zoom to impossible levels or delete a wrong/non existent area piece by piece.
Like @DujaOSM said, I don't remember any bad side effect in thousands of edits, and if anyone deletes the Nile by accident, I'm sure someone will noticed that right away... That, or showing a warning if someone happens to delete a big polygon/line.


> That said, we're also trying to make iD scale to the needs of advanced mappers. #2929 is about manually allowing disabled operations for cases like the ones you mentioned. I think we can focus on that solution.

**Comment by AntMadeira** [comment]
Please, reopen this issue, since this is a major problem in iD right now.
As a safety measure, just add a warning when something out a view is going to be modified. As it is now, it's very problematic and hindering.

**Comment by 1ec5** [comment]
> usually leads to problems like having to zoom to impossible levels

The “Zoom to Selection” button on the right side of the map automatically fits the viewport to the entire feature. You can edit the feature even if the map ends up zooming out to the whole continent. However, deletions aren’t allowed even when the whole feature is visible. This contradicts the error message when trying to delete a feature that’s only partially visible. Zooming to fit the selection is a fairly deliberate and noticeable action, so disabling deletions in that state would potentially prevent casual vandalism but not the accidental breakage that justified disabling this operation in the first place.

I think it would be worth a separate issue or discussion rather than reopening this issue, which was requesting a broader change to allow deletions regardless of visibility.

**Comment by AntMadeira** [comment]
The problem is not only with deletion, it's also with moving, copying, disconnecting or any other operation with the line/polygon.
As I said, a simple warning message when deleting would be sufficient. Moving, copying, disconnecting, straightening, etc. should be allowed.

**Comment by 1ec5** [comment]
Yes, the same considerations apply to these other operations. Again, I suspect these changes were introduced for more reasons than merely preventing accidental large-scale changes. It would be very easy for a casual vandal to make some pretty disruptive changes by allowing a very large feature to be moved, deleted, etc. very easily. But allowing these changes even when zoomed way in, as requested by this issue, would _compound_ this risk with the risk of accidental moves and deletions.

One time, I made the mistake of training a new mapper on JOSM. They immediately moved everything in an entire metropolitan area by almost a mile by dragging with the left mouse button before learning how to pan the map. I only found out about the mess when they complained that all these changes took so long to upload! You’re right that someone would notice, but personally, I was more annoyed at having to clean up this mess than about any of the times iD has prevented me from moving or deleting something large.

New mappers will always make mistakes, but the impact is smaller when the mistakes are confined to fully visible features. That’s why I suggested opening a more tightly scoped request about enabling some of these operations, perhaps with a warning, when fully zoomed out. Consider it a halfway measure.

At the end of the day, it’s a decision about the project’s scope: the kinds of edits you’re probably interested in probably fall under the category of “power editing”. Power editing hasn’t been the primary focus of iD so far – though you can get very far with it! #2929 would attempt to remove some of these guardrails for users who know what they’re doing, but in the meantime, JOSM and Level0 are very good tools to supplement iD.

**Comment by AntMadeira** [comment]
I understand the need to prevent errors and/or vandalism, but I think this many restrictions are not well balanced in iD.
New mappers are welcome and that should be incentivized, but there should be a way to allow "power users" whom, after all, were once newbies and are the main contributors to OSM via iD, to edit the map without such restraints. Yesterday, an operation the should take 10 seconds, took me 5 minutes, because I couldn't disconnect a polygon to erase it.
I do use JOSM for more complex tasks, like big queries and operations with relations, but 90% of what I do is with iD, because I'm a translator and I want to know the editor inside out so that I can help make it more understandable to new mappers.
If "power users" only use JOSM, iD won't evolve as much as it should, because I have the opinion it should be the main tool for editing OSM and should be better suited to receive newcomers.

If you think it will help to open another topic, other than this one and  #2929, I can do that, of course.

**Comment by jjiglesiasg** [comment]
Hi, I disagree with any “on porpoise” limitation in ID editing capacity for users with experience. After 7.4 MILLION changes in OSM 99% made in ID, I do not see why I or other experienced users needs to use JOSM or other editors to do what you call “power editions”. Power Editors are the ones who most contribute to the Map, whatsoever the editor of their choice, and should NOT be capped in any way, by some bunch of purist that believe them as the Gatekeepers of anyone else not using JOSM.

**Comment by DujaOSM** [comment]
![224748868](https://user-images.githubusercontent.com/48584318/160785742-cd1f7a77-afb1-4f6d-9361-1c1f205d4980.png)

Well, this newbie managed to make a mess with iD (2.20.4) just fine, despite limitations and validations. Yes, those are three near-overlapping (but not identical) residential area multipolygons. Boundary ways are glued to adjacent landuse polygons, as well as to a hundred-odd streets, which renders it almost uneditable (granted, it was not all of that newbie's making). I've been staring at this issue in OSM Inspector for almost a month, but I'm really reluctant to tackle it, because I know it would take me a couple of hours I'd prefer spending elsewhere, and iD is not helping _me_ with these arbitrary limitations. I concur with Juan Jose (who was probably harsher than necessary) and AntMadeira that the human cost of those limitations outweighs any benefits, which are by and large theoretical.

**Comment by 1ec5** [comment]
> Hi, I disagree with any “on porpoise” limitation in ID editing capacity for users with experience. After 7.4 MILLION changes in OSM 99% made in ID, I do not see why I or other experienced users needs to use JOSM or other editors to do what you call “power editions”. Power Editors are the ones who most contribute to the Map, whatsoever the editor of their choice, and should NOT be capped in any way, by some bunch of purist that believe them as the Gatekeepers of anyone else not using JOSM.

I’m not unsympathetic to your situation, but I think your point of view would be better served by opening a [discussion](https://github.com/openstreetmap/iD/discussions/) or posting to the talk mailing list. Changing a project’s longstanding scope is not a decision to be taken lightly for any project, even if it would make life easier for experienced mappers who prefer to stick to iD. (I’m in the same boat as you!)

For example, just loosening things up could lead to unforeseen problems over and above the changeset pictured above if we don’t also review the documentation to clarify potential points of confusion. What’s more, iD is already being criticized for what it does to large-scale features like routes and boundaries even without user intervention. Addressing these issues would give the project more breathing room to take on more ambitious workflows.

Once again, you have a valid point of view, but an old closed issue about a requested piecemeal change is not the place to turn it into something actionable.

**Comment by jjiglesiasg** [comment]
Hi, I disagree with any “on porpoise” limitation in ID editing capacity for users with experience. After 7.4 MILLION changes in OSM 99% made in ID, I do not see why I or other experienced users needs to use JOSM or other editors to do what you call “power editions”. Power Editors are the ones who most contribute to the Map, whatsoever the editor of their choice, and should NOT be capped in any way, by some bunch of purist that believe them as the Gatekeepers of anyone else not using JOSM.
