### ISSUE TITLE
LibreJS compatibility

### ISSUE THREAD

**Issue by TechnologyClassroom** [openstreetmap/iD#8084]
It would be nice if iD became [LibreJS](https://www.gnu.org/software/librejs/) compliant.

Instructions:
- [Setting your JavaScript free](http://www.gnu.org/software/librejs/free-your-javascript.html)
- [Setting your JavaScript free from the LibreJS manual](https://www.gnu.org/software/librejs/manual/html_node/Setting-Your-JavaScript-Free.html)

**Comment by matkoniecz** [comment]
What would need to be changed?

Why it would be useful?

See https://github.com/openstreetmap/openstreetmap-website/issues/2886 

Comments such as

> iD editor which is included in this repo has 74 direct dependencies: https://github.com/openstreetmap/iD/network/dependencies and many more indirect ones (some of which are only dev dependencies). Tagging those in the source code doesn’t seem feasible at all.

and

> There are probably a hundred or more different pieces of javascript and they're changing all the time - we're not going to go round trying to catalogue them with some esoteric labels just because you're chosen to shoot yourself in the foot.

by people with experience in making software make me skeptical about this proposal.

**Comment by TechnologyClassroom** [comment]
Some indication that the code is available would be helpful at least.  I did not know the frontend was freely licensed after using the site for several years.  LibreJS is one solution.  Simply adding a link to this repo would solve the need for most people.

When viewing the minified JS, the code is mostly useless and acts more like a binary in practice.  Linking to the unminified version would help this issue.  With minified JavaScript, the comments and variable names are removed making it very difficult to understand.

Can you point me to the process that bundles and minifies the JavaScript so I can get a better grasp on the process?

**Comment by kymckay** [comment]
@TechnologyClassroom The scripts in `package.json` are what you're looking for: https://github.com/openstreetmap/iD/blob/06441e72d7250751cb85ec88cd5e827a5c3973f1/package.json#L26

`dist:min:iD` handles minification (by calling uglifyjs), the file being minified (`dist/iD.legacy.js`) is output by rollup (bundler) via the `build:legacy` script:

https://github.com/openstreetmap/iD/blob/06441e72d7250751cb85ec88cd5e827a5c3973f1/package.json#L20

**Comment by quincylvania** [comment]
> dist:min:iD handles minification (by calling uglifyjs), the file being minified (dist/iD.legacy.js) is output by rollup (bundler) via the build:legacy script:

This is true, but we actually sync the `dist/iD.legacy.js` file directly to openstreetmap-website, and then [they run it through](https://github.com/openstreetmap/openstreetmap-website/pull/2720#issuecomment-661700405) their own minification script. The `dist/iD.min.js` file is for other downstream apps that don't have their own compression workflow.

> Some indication that the code is available would be helpful at least. I did not know the frontend was freely licensed after using the site for several years. LibreJS is one solution. Simply adding a link to this repo would solve the need for most people.

There's info in the help pane. We're not hiding that we're open source, we hope people see this and come contribute!

<img width="588" alt="Screen Shot 2020-10-23 at 12 23 55 PM" src="https://user-images.githubusercontent.com/2046746/97028901-ba19e100-152a-11eb-9641-46565ceabab1.png">

LibreJS sounds like a nice-to-have, but I doubt it affects many mappers at all, so it's really not a high priority. Since [openstreetmap-website isn't pursuing compatibility](https://github.com/openstreetmap/openstreetmap-website/issues/2886#issuecomment-708670520), and since we have a lot of other stuff to worry about, I'm closing this as low impact. I'd still welcome a pull request if anyone is feeling inspired, provided the changes aren't breaking or hard to maintain.
