### ISSUE TITLE
Filter Mapillary sign detections by date and user

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8133]
The street-level imagery filtering feature added in #8076 is incredibly useful for updating signposted details, but it doesn’t appear to filter Mapillary sign detections, so the filter can give a false sense of security when mapping based on sign detections. @cbeddow pointed out that Mapillary’s [map feature API](https://www.mapillary.com/developer/api-documentation/#the-map-feature-object) returns `first_seen_at`, `last_seen_at`, and `detections.user_key` properties that could be useful for client-side filtering.

**Comment by quincylvania** [comment]
@1ec5 Good idea, this makes for a nice enhancement that mappers would expect.

**Comment by cbeddow** [comment]
We are thinking about how to do this a little differently, because the first seen and last seen has to line up a little differently from from and to. So if implementing it now, my suggestion is:

From date must be applied to the traffic sign layer so that there is a date range of FROM and TO, which then must overlap with the date range of FIRST SEEN and LAST SEEN. It's crucial to check for overlapping ranges, and not a timestamp falling within the range. If a crosswalk was first seen March 1, 2020 and last seen March 31, 2020, but the from is January 31 and the to is April 5, then no individual timestamps will match, the range must be considered.

**Comment by quincylvania** [comment]
@cbeddow I'm pretty sure iD is handling the first/last seen ranges correctly. A detection is shown if the last seen date is after the from filter, and if the first seen date is before the to filter.

https://github.com/openstreetmap/iD/blob/82bce000b0dad8a30ee32ebee9bd7b06cab56dd5/modules/svg/mapillary_signs.js#L100-L111
