### ISSUE TITLE
promote the unseen tutoriel if review_request checked

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/iD#8196]
I meet many users who first contribute without the tutorial and then ask for a review_request. The answer is often in the tutorial.
Is it possible, when the user hasn't see it, to propose again the tutorial when the user ask a review_request, before uploading ?
because unfortunately, the answer is often "as you would have learned from the tutorial, ...".

**Comment by Fizzie41** [comment]
Maybe set it that you must work through the tutorial before mapping for the first time?

Of course, if you're an experienced mapper & you change user names, or set-up a new one for a specific purpose, that would unfortunately also get you.

**Comment by quincylvania** [comment]
> I meet many users who first contribute without the tutorial and then ask for a review_request. The answer is often in the tutorial.

Can you give some examples? The walkthrough teaches mappers how to use a few parts of iD, not how to map everything in OpenStreetMap. There are countless reasons someone might be unsure about their edits regardless of whether they did the walkthrough.

> Maybe set it that you must work through the tutorial before mapping for the first time?

I don't think we can really do this. Mappers are given the choice, and those who choose not to do the walkthrough would probably close the tab rather than be forced through 15 minutes of instruction.

**Comment by quincylvania** [comment]
> I meet many users who first contribute without the tutorial and then ask for a review_request. The answer is often in the tutorial.

Can you give some examples? The walkthrough teaches mappers how to use a few parts of iD, not how to map everything in OpenStreetMap. There are countless reasons someone might be unsure about their edits regardless of whether they did the walkthrough.

> Maybe set it that you must work through the tutorial before mapping for the first time?

I don't think we can really do this. Mappers are given the choice, and those who choose not to do the walkthrough would probably close the tab rather than be forced through 15 minutes of instruction.

**Comment by Marc-marc-marc** [comment]
> > I meet many users who first contribute without the tutorial and then ask for a review_request. The answer is often in the tutorial.
> 
> Can you give some examples?

https://www.openstreetmap.org/changeset/94200768 : missing main tag

**Comment by Marc-marc-marc** [comment]
> Can you give some examples?

another https://www.openstreetmap.org/changeset/94216542 ask for review without seeing the tutoriel (how to search for a POI catégory is in the tutoriel).

> Maybe set it that you must work through the tutorial before mapping for the first time?

mandatory isn't a good idea.
I am simply suggesting that a reminder for the tutorial should be show when the user seems to need help.
Obviously this won't cover all cases, but if one or the other says "ha yes, I ignored it but I'll take a look", this will always be pleasant for everyone (both the newcomer who will progress and the person who reviews the review_request and is disappointed with the RTFM usecases").

**Comment by quincylvania** [comment]
> I am simply suggesting that a reminder for the tutorial should be show when the user seems to need help.

I just don't see how iD can know when the mapper needs help and when they're being intentional. If you've already done your editing and are requesting review on the upload screen, it's unlikely you'd want to go all the way back and do the tutorial.

iD has validation warnings to tell mapper about issues with their edits. I suggest we add warnings to detect problems before they're uploaded instead of expecting everyone to know the mapping patterns themselves.

**Comment by Marc-marc-marc** [comment]
> If you've already done your editing and are requesting review on the upload screen, it's unlikely you'd want to go all the way back and do the tutorial.

not necessarily go back, but see the tutoriel and then improve its contribution.
when I tell the user "review_request without tutorial" that the tutorial exists, some of them launch the tutorial and correct their error themselves.

> iD has validation warnings to tell mapper about issues with their edits

indeed, that's also a good idea. but it don't see why this prevent a reminder about the tutoriel
