### ISSUE TITLE
Ominous "cancel" button worries uploaders

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8203]
Here, experienced Internet users all know that pushing a "cancel" button...

![30879-5](https://user-images.githubusercontent.com/1230959/99256031-bd656b80-284f-11eb-8425-26bdf18ba896.jpg)

...could throw away hours of work.

OK, in this case it doesn't. Therefore please add a mouseover "Return back to the editor. All edits still intact."

Or re-label the button "Back" or "←" or "Previous page", etc.

> It is clearly to just cancel the upload.

Clear to some, but experienced Internet users know better from bitter experience.

> Well experienced OSM users know even more better.

OK, then they wouldn't be bothered about a little mouseover message to help others.

**Comment by quincylvania** [comment]
Okay, maybe, but since pressing Cancel doesn't actually discard any edits, and since you can just press the X button to close the screen, I'm not concerned that anyone is getting hamstrung by this. iD mappers should be invited to trust the app's safety and not worry about reading tooltips just to close a screen.

Still, I'm considering ways to make the save screen better, so I'll keep this in mind.

**Comment by jidanni** [comment]
(I'm not saying it's iD's fault. I'm saying it's the fault of the 1000 other apps out there, giving the Cancel Button a bad 'name'/'rep'.)
