### ISSUE TITLE
Transifex offers same translation items again

### ISSUE THREAD

**Issue by manfredbrandl** [openstreetmap/iD#8234]
I habe already translated 15 entries (Pagoda and several Playground presets) and Transifex offers me those entries the third time. Is there maybe something going wrong while sending "new" strings to Transifex?

**Comment by quincylvania** [comment]
@manfredbrandl Thanks for reporting. I think the problem was that Transifex autoupdates the source files every day but Travis CI also pushes them on every successful commit, and they were competing since I only updated one of these for id-tagging-schema.

I think I fixed it but please let me know if it happens again, sorry for the inconvenience!
