### ISSUE TITLE
Diacritic-independent preset search

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/iD#8242]
I'm told that in languages where accents and other diacritic marks are common, software users are accustomed to leaving them off when searching. iD handles some of these cases incidentally when searching presets, either due to fuzzy matching or generous search terms, but in other cases it clearly fails.

Luckily, it's [straightforward in ES6](https://stackoverflow.com/a/37511463) to strip diacritics from strings before comparing them. This will be a great localization improvement and also let translators reduce repetitive search terms.

![Screen Shot 2020-12-09 at 4 22 10 PM](https://user-images.githubusercontent.com/2046746/101690204-39ac3280-3a3b-11eb-9dcf-805d708251eb.png) ![Screen Shot 2020-12-09 at 4 22 23 PM](https://user-images.githubusercontent.com/2046746/101690183-387b0580-3a3b-11eb-9e3f-ed43996a17e6.png)

**Comment by quincylvania** [comment]
I forgot to mention that this has come up before in #3979. At the time the solution was just to add search terms, but now we can solve the general case by taking advantage of modern JavaScript. Thanks to @willemarcel for bringing up this issue.

**Comment by quincylvania** [comment]
So in my implementation I made the search ignore diacritics in names altogether, which I'm afraid could cause issues if there are two preset names that are otherwise identical except for different combinations of diacritics. @1ec5 do you have any idea if this would become a problem? 

I also left search terms alone, but I should probably make them work the same as the preset name.

**Comment by 1ec5** [comment]
> So in my implementation I made the search ignore diacritics in names altogether, which I'm afraid could cause issues if there are two preset names that are otherwise identical except for different combinations of diacritics. @1ec5 do you have any idea if this would become a problem?

This is a concern specifically in Vietnamese, which abounds in minimal pairs after stripping diacritics. There are lots of collisions when stripping diacritics from both the search terms and the preset names, especially when allowing for some edit distance.

I’ve been manually hard-coding diacritic-stripped variants at the end of every list of terms in the Vietnamese localization: https://github.com/openstreetmap/iD/issues/3979#issuecomment-296391231 https://github.com/openstreetmap/iD/issues/3159#issuecomment-229955476. That way, the user can get the behavior you’ve implemented automatically so that “dau” will match both “dấu” and “đậu”, but they can easily turn it into a search for “đậu” to narrow down the results. It isn’t perfect, because Vietnamese has two levels of diacritics – “lô” should match “lỗ” but not “lò”. The weighting was also quite imperfect, because some lists of terms are naturally longer than others. But it was the best I could do with what iD supported at the time.

With this change, iD does yield better results in some cases when omitting diacritics: “sân chơi” returns “sân chơi” first instead of “sân giải trí” (which has “sân chơi” as a synonym). However, if I type in “dau” expecting “đậu”, there’s no way to filter out “dấu” except by typing exactly “đậu”. So the results will be better sometimes but worse in other cases.

It would actually be quite easy to write a small amount of Vietnamese-specific logic to avoid the bloat from hard-coded diacritic stripping while improving results in every case. However, there didn’t seem to be any appetite for language-specific special cases in the past. On native platforms, the CLDR and ICU libraries make it possible to perform searches with more nuance. But the last time I checked, the `Intl` API in JavaScript didn’t expose quite enough ICU-based internationalization functionality for diacritic-insensitive search, only sorting.

**Comment by 1ec5** [comment]
Now that this is in place, the preexisting diacritic stripping is redundant (and probably not as good for performance, given where it is):

https://github.com/openstreetmap/iD/blob/655c3a692cd14cc0aaa6f95e3063179aa7c7a8d5/modules/util/util.js#L415-L416

**Comment by quincylvania** [comment]
@1ec5 Ah, I didn't realize iD was doing this.
