### ISSUE TITLE
Extracting POIs

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8246]
Previously when extracting a point from a building it was moving with the pointer so I could place it where I want.
Currently I can't move the POI because iD decides where to put it.
So I extracted a point here:
![extract](https://user-images.githubusercontent.com/57260466/101919945-7d35a680-3bcb-11eb-9703-0f6cb1daf08f.png)
but couldn't see where it is.
And finally I found it far away:
![extract2](https://user-images.githubusercontent.com/57260466/101919965-8292f100-3bcb-11eb-9f10-33d011cc417b.png)

I think it would be better to go back to the previous behavior.

**Comment by quincylvania** [comment]
Single-step extraction is intentional to facilitate the action on multiselections and on touchscreen devices, see #6674.

However, the point should be placed in the center of the of the area. What you're seeing is definitely a bug. I've noticed a few similar issues since we updated to D3 v6, which changed the implementation for calculating centroids.
