### ISSUE TITLE
iD doesn't load all long ways in view

### ISSUE THREAD

**Issue by ignaciolep** [openstreetmap/iD#8256]
Hi,

It seems that iD doesn't load long road ways in view.

For example:
Using OSM background tiles you can notice that the way #681928822 is missing in iD render. It's a 13,96 km long way.
![image](https://user-images.githubusercontent.com/13091755/102532498-d77aaf80-4082-11eb-97d1-468747fa7479.png)
https://www.openstreetmap.org/edit?editor=id&node=6386252518#map=19/-33.24343/-64.70872

The workaround is to pan the map over the missing road until it loads it. I suppose that this works when a smaller connected way get in view, and loading the smaller way triggers to load the connected larger one.

**Comment by mmd-osm** [comment]
Unfortunately, that's a works as designed and caused by the way the OSM API 0.6 /map call works.

See [this link](https://wiki.openstreetmap.org/wiki/API_v0.6#Retrieving_map_data_by_bounding_box:_GET_.2Fapi.2F0.6.2Fmap): _Also note that ways which intersect the bounding box but have no nodes within the bounding box will not be returned._

**Comment by ignaciolep** [comment]
Thanks @mmd-osm. I wasn't aware of that API limitation.

**Comment by quincylvania** [comment]
Yep. iD could theoretically fetch a wider area of data to reduce the issue, but performance is a concern right now.
