### ISSUE TITLE
Suggest fix for mappers tagging zoo animals to Wikipedia/Wikidata entries directly

### ISSUE THREAD

**Issue by nicolasmaia** [openstreetmap/iD#8260]
This is related to #6652.

We should suggest automatic fixes that change `wikipedia` and `wikidata` tags to `species:wikipedia` and `species:wikidata` when someone uses `attraction=animal`.

This should work 99% of the time, except if it's a really famous individual animal with its own Wikipedia page, or a notable enclosure in a notable zoo. So it should be more of a suggestion that can be dismissed.

**Comment by matkoniecz** [comment]
>  So it should be more of a suggestion that can be dismissed.

What should happen if dismissed? There is no way to tag this so it will appear again and again and sooner or later someone will retag it.

Not sure is it viable (from technical viewpoint and from legal due to copyright issues with what Wikidata includes) - but maybe check whatever target wikidata/wikipedia page is classified as an animal?

**Comment by 1ec5** [comment]
> Not sure is it viable (from technical viewpoint and from legal due to copyright issues with what Wikidata includes) - but maybe check whatever target wikidata/wikipedia page is classified as an animal?

That seems to be the suggestion: checking whether the Wikidata item is tagged as an animal. Not sure how copyright would come into the picture if the result is only that `species:` would be prepended to the key. Copyright covers published works, but Wikidata would only be used here in the validation step.

A given Wikidata item about an animal species won’t necessarily say that it’s an instance of a species, because there can be multiple subclasses between it and the species item. However, it would be possible to check for a property such as [taxon name (P225)](https://www.wikidata.org/wiki/Property:P225) or [taxon rank (P105)](https://www.wikidata.org/wiki/Property:P105).

> What should happen if dismissed? There is no way to tag this so it will appear again and again and sooner or later someone will retag it.

Perhaps add `not:species:wikidata` and a validator warning about `species:wikidata` contradicting `not:species:wikidata`?

**Comment by matkoniecz** [comment]
> Perhaps add not:species:wikidata and a validator warning about species:wikidata contradicting not:species:wikidata?

`species:wikidata` still can be added to a notable enclosure (it would link to what kind of species is inside)

**Comment by quincylvania** [comment]
It looks like the `wikidata` tag is used less than 1000 times with `attraction=animal` (I didn't look up the exact number). Since we don't always want to move the `wikidata` value to `species:wikidata`, we can't use one of iD's existing validation rules. As such, I'm afraid it'd be much more work to write a new rule than to just resolve these all manually.

**Comment by matkoniecz** [comment]
And if someone is interested in fixing this (and other misused `wikidata`/`wikipedia`) manually, with a support from a Python script...

Then I can publish my script that I am using for that (but it requires some actual review and looking at proposed edits, not just blindly pressing "y, edit this").

I can also dig for my overpass query that filters out valid `wikidata` and `wikipedia` tags on `attraction=animal`.

(hopefully this kind of comment is OK)

**Comment by 1ec5** [comment]
> but it requires some actual review and looking at proposed edits, not just blindly pressing "y, edit this"

If you need help reviewing these issues, perhaps you could publish it as a MapRoulette challenge but mark it as an advanced task with instructions on what to look for. I’ve created MapRoulette challenges for QA based on [SPARQL queries](https://wiki.openstreetmap.org/wiki/SPARQL_examples#Quality_control) in the past. Unfortunately, Sophox is currently down (Sophox/sophox#24), so scripts like yours are currently the way to go.

**Comment by nicolasmaia** [comment]
I'd love to tackle a maproulette challenge like that.
