### ISSUE TITLE
Problem with the layers "IBGE - Mapa de setores urbanos" and "IBGE - Mapa de setores rurais"

### ISSUE THREAD

**Issue by GabrielMO-2020** [openstreetmap/iD#8279]
Hello everyone!
When I try to edit a map in Open Street Map and put the layers "IBGE - Mapa de setores urbanos" and "IBGE - Mapa de setores rurais", the maps for that layer don't appear and the screen for editing goes black.
Do you know what may be happening? What would be the solution to this?
Use the link https://user-images.githubusercontent.com/76920627/103488749-30ba4100-4dee-11eb-94c5-9638d83d85ed.png to see how my editing screen of OSM is going.
Any help will be appreciated!
Thanks.

**Comment by 1ec5** [comment]
The map is zoom out quite far in that screenshot. Perhaps the layers don’t support that zoom level – does zooming in further allow the layers to appear?

**Comment by GabrielMO-2020** [comment]
@1ec5 I zoomed in, but the edit screen, which should have the map, remains black.

**Comment by GabrielMO-2020** [comment]
Someone can help me?

**Comment by tordans** [comment]
@GabrielMO-2020 ~~could you add a link to the location and layer using this editor version https://ideditor-release.netlify.app/#background=EsriWorldImagery&disable_features=boundaries&map=2.00/10.7/33.4 which will store location and layer in the URL so we can more easily look at it.~~ – I looked it up, eg here https://ideditor-release.netlify.app/#background=IBGE_Setores_Rurais&disable_features=boundaries&map=14.57/-13.8527/-46.2409

In general, all Layers in iD are pulled from https://github.com/osmlab/editor-layer-index ("ELI"), which is a separate project.
So solving this will most likely have to happen there.

The layer you name, is here https://github.com/osmlab/editor-layer-index/blob/d5bab4f6f6c1a15b9e83d683313570f17dc7fcf7/sources/south-america/br/IBGE_Setores_Urbanos.geojson?short_path=bf8d23f

Some debugging:

When you look at your developer console (https://developers.google.com/web/tools/chrome-devtools) while loading the images, **the error code ist 410 "Gone"** (https://developer.mozilla.org/de/docs/Web/HTTP/Status/410). 

This sounds to me, that this error is not just a temporary hiccup.

Btw, the same is true for the Layers in the JOSM-layer index at https://josm.openstreetmap.de/wiki/Maps, they also throw a 310 for me.

You can look at the history of the files in ELI at https://github.com/osmlab/editor-layer-index/commits/gh-pages/sources/south-america/br/IBGE_Setores_Urbanos.geojson

Maybe the guys from https://github.com/osmlab/editor-layer-index/pull/672 which edited data in Brasil know more (they did not edit those two files directly though).

And in https://github.com/osmlab/editor-layer-index/issues/555 the was an issue with the token that is now part of the URL. That could also be the issue here.

Also, https://wiki.openstreetmap.org/wiki/IBGE_Tile_Layer says "Mapbox kindly hosts this layer" – maybe this changed?

My recommendation is: Open this issue in ELI and see if someone there can help solving it.

**Comment by quincylvania** [comment]
@tordans Thanks for looking into this. It does indeed look like something that needs to be handled in ELI.
