### ISSUE TITLE
rendering for crossing=traffic_signals

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/iD#8290]
Could we change the line pattern/color for `crossing=traffic_signals` to be the same as for `crossing=marked`?
I would say that `traffic_signals` is a subcategory of `marked`. Crossings with traffic lights are usually marked with zebra.

![crossings](https://user-images.githubusercontent.com/57260466/104136241-33400c00-5395-11eb-9a96-f1a304a7c43d.png)

**Comment by quincylvania** [comment]
iD doesn't support `crossing=traffic_signals` right now since it's a [confusing tag with orthogonal meanings](https://wiki.openstreetmap.org/wiki/Proposed_features/Unambiguous_crossings). But if you use this tag, I'd say it's actually convenient that it's rendered differently than `crossing=marked` so you can tell which feature is which at a glance.

**Comment by maro-21** [comment]
But `crossing=traffic_signals` is an approved tag...
https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dtraffic_signals

**Comment by Marc-marc-marc** [comment]
crossing=marked is listed a [Controversial_Decisions](https://wiki.openstreetmap.org/wiki/ID/Controversial_Decisions#Changing_crossing.3Dzebra_to_crossing.3Dmarked) and the meaning if not the same (preset, wiki, ...) : from "ground marked" to "no light but ground marked" 
a more consensual decision is to go back with crossing = describing describing the safety of the crosswalk (light -> no light but marked -> unmarked) and crossing_ref describing the legal reference which has legal implications in many countries..
