### ISSUE TITLE
One grand "connect these features" solution not offered

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8359]
This upload is seemingly facing big problems:
![20210222T032318](https://user-images.githubusercontent.com/1230959/108635978-68c03500-74bd-11eb-9358-2a8840a6163b.jpg)
OK, let's have a closer look:
![20210222T032558](https://user-images.githubusercontent.com/1230959/108636111-35ca7100-74be-11eb-810d-e5355f52c5ee.jpg)
![20210222T032757](https://user-images.githubusercontent.com/1230959/108636117-424ec980-74be-11eb-94b7-0ae389f8ce6c.jpg)
If fact one grand "connect these features" solution, if offered, would solve the entire list in one swoop.
This is mainly due to the overlying path noticing the underlying paths, but the underlying paths not noticing the overlying paths!

Smart users will know about this iD quirk, so will first choose to resolve each of the issues that offers "connect these features",
and then the other issues will go away on their own naturally.

But of course the best thing would be for iD to notice there is a "gran slam" available here of "connect all features" that could be offered.

**Comment by DujaOSM** [comment]
I would hesitate offering this as an option, since it's likely that beginners would apply it as an easy way out instead of inspecting every situation. Multiple issues of this type are often a result of a sheer error (e.g. someone drew or pasted a path over other ones while they were hidden for some reason).

If you really know that you want that, just keep the mouse pointer at the topmost "connect those features", and keep clicking in machine-gun manner until the list is empty. (I do that often with "Set as outer" when drawing multipolygons).

**Comment by quincylvania** [comment]
> I would hesitate offering this as an option, since it's likely that beginners would apply it as an easy way out instead of inspecting every situation.

I agree. Connecting all isn't always the right solution, since some could be bridges or tunnels or incorrect geometry. I could envision a hidden option to connect them all if someone really knows what they're doing, but we don't have an existing workflow for this type of advanced fix and it doesn't seem like a common problem.
