### ISSUE TITLE
Show logo of well know chain store in panel

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8391]
OK, iD already fills in
```
building=yes
shop=convenience
name=FamilyMart
brand=FamilyMart
brand:wikidata=Q1191685
brand:wikipedia=en:FamilyMart
```
Well at this point, how about putting the logo of the store somewhere in
![20210311T110531](https://user-images.githubusercontent.com/1230959/110729589-f2ac2400-8259-11eb-89e8-10b2f8858a44.jpg)
so the user can feel sure that things are working OK.

**Comment by 1ec5** [comment]
It’s working for me in v2.19.6:

<img src="https://user-images.githubusercontent.com/1231218/110748177-353b1580-81f4-11eb-84ae-bae908ed5696.png" width="400" alt="familymart">

**Comment by jidanni** [comment]
I was using iD 2.20.0-dev https://www.openstreetmap.org/changeset/100809042

**Comment by 1ec5** [comment]
It does look like none of the name-suggestion-index presets are showing up in the Netlify preview. Presumably that’s something #8305 would fix, but I’m not sure why the existing integration has broken in the meantime.

**Comment by bhousel** [comment]
This is because the iD presets were extracted to a separate project, [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema), and that repo contains **only** the iD presets.  Name-suggestion-index stuff (i.e. the brand presets) was removed from there in [this commit](https://github.com/openstreetmap/id-tagging-schema/commit/2b15affb77c1b7fe1f8db8b29e905d8eb014384a).

Name-suggestion-index now distributes its presets separately (they are used by iD, GoMap, StreetComplete, JOSM)
@1ec5 is correct, #8305 is the Pull Request to again make them available in iD.
