### ISSUE TITLE
Allow removing individual items from the Save list

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8393]
Take the case of #8392.
Upon hitting Save it says we have made two changes:
> Modified Bus Stop: Qinghai-Henan Intersection
> ￼Created Shop: 正陽光學儀器有限公司

But we realize "What? I modified a bus stop? No way. Must have got dragged around with the cursor or something."

But there is no way to individually undo it. If it was the last item edited, simple: just click undo.

But it is buried in the undo stack. To undo it we must destroy our later edits.

**Comment by jidanni** [comment]
It would be entirely fair to have little X's at the side of each item:

> [x] Modified Bus Stop: Qinghai-Henan Intersection
> ￼[x] Created Shop: 正陽光學儀器有限公司

If clicked they would say "Throw away all your changes for 'Modified Bus Stop: Qinghai-Henan Intersection'"?

Indeed, they can also offer more choices: "temporarily exclude this item from saving." (If not too complicated.)

**Comment by totoroot** [comment]
In my opinion tackling this issue would be vital, as I have often accidently added changes to a changeset I wanted to save and could not do so, since there was no obvious way to remove a single erroneous edit.

In the following example a simple way to remove the change that was erroneously added ("Deleted Foot Path") from the changeset that is about to be saved would be very welcome.

![image](https://user-images.githubusercontent.com/39650930/144443624-5865102e-ba01-4403-8145-fe5a7919fe8e.png)

**Comment by bhousel** [comment]
this is #537
