### ISSUE TITLE
Add Osmose Mid and Low Priority issues

### ISSUE THREAD

**Issue by ZEE6de** [openstreetmap/iD#8447]
When I select "Osmose Problems" in "Map Data", only the problems listed as priority "High" on [https://osmose.openstreetmap.fr ](https://osmose.openstreetmap.fr) are displayed. Couldn't you also add a function to turn on/off whether Mid/Low priority problems can also be displayed and closed?

**Comment by kymckay** [comment]
When I added the Osmose layer my reasoning for limited the issues requested from the API was that a limited number are returned per tile request. The thinking was to target issues with the most significant impact or which are easy for even a new editor to digest. In fact, it's not actually limited by priority, but just by a whitelist you can find here:
https://github.com/openstreetmap/iD/blob/1ee45ee1f03f0fe4d452012c65ac6ff7649e229f/data/qa_data.json#L12-L129

So one possible solution to your request is just adding further reasonable issue types to the whitelist. Note though that limiting the number of issue types is also done to avoid there being an overwhelming variety (without finer user control to limit that).

That said, it's possible further user control could be added to the layer in iD. How complex that is coding wise is a question of how it would be expected to behave and whether the whitelist should still be retained (another reason for it is to provide icons to distinguish issues for a better UX in iD). The existing code also tries to be conservative in use of the API which also becomes harder to do depending on expected behaviour.

**Comment by ZEE6de** [comment]
Oh, ok. Then let's leave it as it is, the effort to change something here is probably not worth the benefit.
