### ISSUE TITLE
Do not set highway=crossing on node when connecting service=driveway

### ISSUE THREAD

**Issue by Strubbl** [openstreetmap/iD#8463]
When there is highway=service + service=driveway, which crosses a footway and has no common node, iD correctly detects this as a data problem. If i use the "connect ways" option of the data problem, both ways get one node, which connects these ways. But also this node gets the tagging highway=crossing automatically. 

In case of a footway (or cycleway or path) crossing a highway=service + service=driveway i think this is not a desired behaviour. It would be better if iD would not do this in this case.

**Comment by lectrician1** [comment]
Why?

**Comment by Strubbl** [comment]
Because it is not a crossing in the sense of https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcrossing
None of the mentioned use cases matches for a private road to a building (highway=service + service=driveway) which crosses a footway

**Comment by lectrician1** [comment]
Just because there isn't a example doesn't mean you can't use it there. The usage definition is "Pedestrians can cross a street here". That definition is valid for service roads since they are also streets.

**Comment by osm-ToniE** [comment]
Strubbl refers to a service=driveway road and I think this is something different than a service road w/o additional service= tags.

- driveways (according to my experience)
  - are usually separated from the other streets by a kerb, i.e. cars have to cross a kerb to enter the driveway
  - pedestrians usually to not have to cross kerbs to cross a driveway
  - footways and driveways therefore usually have the same level
  - driveways usually have the same surface as the footways, precedence is for the pedestrians, not for the cars (they have to watch out)
  - from the overall perspective driveway users cross footways, not vice versa
 
- highways=crossing is an optional tag on crossing nodes, iD makes this a default

I second Strubbl, highway=crossing at service=driveway is really a superfluous tag and shouldn't be set w/o a good reason

**Comment by lectrician1** [comment]
It still functions as a "crossing" though. The primary use case of highway=crossing is for routers to tell cars where to expect pedestrians. When a driveway crosses a footway or sidewalk, vehicles should know that they should expect pedestrians there. This is not a superfluous tag.

**Comment by osm-ToniE** [comment]
highway=crossing is not a superfluous tag at all. It is just the combination with service=driveway.

I just wanted to point out, that by turning into a driveway with a car, **usually crossing a lowered kerb**, the vehicle enters an area which is designated to pedestrians and cyclists.
There shouldn't be the need for routers and drivers with open eyes ((t) "open eyes 2.0") to give hints at every "crossing" on a driveway.
On the other side, cyclists and pedestrians don't have to be warned every 10 - 20 meters (in cities) about cars potentially crossing on a driveway.

Just my 2ct (EUR)

**Comment by hungerburg** [comment]
Perhaps, the problem can be worded differently. Not: Is there a crossing or not? But: Who gets the kerb?
Sometimes will be the cars crossing the sidewalk, sometimes the pedestrians.
Corner cases remain, where neither car nor pedestrian get one, rarely both…
Ah, yes, when talking iD, it always helps to mention accessibility…

**Comment by map-per** [comment]
How about stoping ID from adding highway=crossing altogether and not ony on highway=service, service=driveway. This might be a good idea as the highway=crossing Tag without being specified by crossing=* acually doesn't provide any additional information

**Comment by lectrician1** [comment]
But it does... it tells if there is a crossing. See discussion above too.

**Comment by hungerburg** [comment]
@lectrician1 Nah, when two ways share a node, they cross. No need for tagging the node "crossing". This is just de iD editor wanting to be more specific about the type of crossing. In a quest for topological precision the validator sometimes even adds the node and also a guess for the specifics too. This is wrong, the validator must nag until a valid answer for type of crossing given. And no, just they cross, is not valid, that we already know ;)

**Comment by lectrician1** [comment]
I can see that a router can infer where crossings are by checking every node to see if it shares one with a crossing. However, it could do that with less computation by just checking the tags on the node. I guess the debate comes down to "if we want to make things easier for routers".

**Comment by hungerburg** [comment]
I know of a router aimed at the visually impaired, it just does that, and it is blazingly fast at it. But yes, you are right, in a dozen of years, it will consume less computations, when finally all the crossings are marked on the node, such is true. Until then, the router still needs to read every node. and it will guess the specifics of the crossing for eternity, if they remain left out

**Comment by map-per** [comment]
A second point against adding highway=crossing:
This conflicts with the ideal of OSM that the map sould be produced by people and not by bot scripts that change things according to some assumptions. In my opinion the adding of highway=crossing is quite similar to making a bot that automatically adds tags wherever roads intersect with footways.

**Comment by lectrician1** [comment]
Bots are useful tools when used appropriately and agreed-upon. There's no "OSM ideal" against them. They're used for imports, changing tags, and ensuring the usefulness and sustainability of the project altogether.

Adding "highway=crossing" is also not an assumption.

This statement has nothing to do with debate, I'm just commenting on your statement.

**Comment by hungerburg** [comment]
There is some truth in what map-per says. The validator makes a mechanical edit by adding a tag to a node, where the user only did agree to add a node. I would not be surprised, if routers, when ingesting openstreetmap data, would do exactly the same, add a tag to every node, where highways cross, to speed up computations later on. I would be surprised, if they called the node "crossing", because that would mix with manually entered data.

**Comment by westnordost** [comment]
At least on the German Forum, many people think that a `highway=crossing` should only be set if there is a facility to cross it, i.e. an informal crossing point along a street or a crossing of the sidewalk with a driveway would not be a `highway=crossing`, also not an unmarked one. How much this understanding is shared by mappers around the world, i.e. reflects real-world usage of the tag, is something that would need to be researched.

However, I have one more concern to add towards this automatism, not only for driveways but other roads as well:

Not everywhere where a footway-way a road-way meet, it is possible to cross it as a pedestrian. Just imagine a footway that crosses a 8-laned main road. If it cannot be crossed, `crossing=no` should be set **without** `highway=crossing`. So, the automatism automatically assumes that the road is crossable, but in reality it is something that needs to be found out (surveyed, or maybe it is visible from aerial imagery).

**Comment by hungerburg** [comment]
I just did a bit of research into the use of _hw=crossing_ as a single tag on a node in my hometown: Out of 99 total

- 89 were zebras
- 3 were complete errors (on a landuse, doubling a close by one)
- 7 were _unmarked_ (2 crossing islands with no zebra, rest for the sake of drawing a footway across a street)

The numbers show, that humans set the tag to different measures than the validator of the iD editor, much more to the documentation than to the dictionary. Please make users conscious of the mechanical edit and have them specify crossing type. Especially in assistive technologies based on OSM, type of crossing does make a difference!

**Comment by westnordost** [comment]
@hungerburg one town is not representative. It would be good if you looked at different towns, specifically I'd recommend comparing towns were it is common that sidewalks are mapped wiht separate geometry and those where this is not done.

**Comment by hungerburg** [comment]
Looking at other towns, I rather leave that up to people with local knowledge there :) This is from a town with practically no sidewalks mapped as separate ways - mappers here are damn lazy. I am pretty certain, the conclusion will hold though: type of crossing is what makes the data useful. And iD is not a bot, so it should do more than a bot can do.

UPDATE: mappers are not so lazy after all here! On 1203 nodes tagged "hw=crossing" key crossing is used 1201 times after I filled the 10% or so that were not specified; values are: zebra=69; marked=126; uncontrolled=584; traffic_signals=397; unmarked=25; Additionally, there are 48 "hw=traffic_signals" with a crossing=traffic_signals key.

**Comment by 1ec5** [comment]
To me, 7d8453b1fbcbe16fabf9d78d1246ac1e377ece7b seems like an overcorrection. An ordinary footway crossing a service road is one thing, but a _sidewalk_ crossing a _driveway_ is so unremarkable that `highway=crossing` shouldn’t be the default response to a connectivity warning.

In the U.S., when I come across a bare `highway=crossing` node joining a `footway=sidewalk` to a `service=driveway`, I almost always remove the `highway=crossing` tag because it’s misleading. Typically, the sidewalk continues uninterrupted and there is much less need to “look both ways” across a residential driveway.[^driveway] It’s useful to distinguish these incidental crossings from [designated unmarked crossings at formal intersections](https://wiki.openstreetmap.org/wiki/Special:PermanentLink/2284509#United_States):

[![](https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/73_Grove_Street%3B_Lynbrook%2C_NY-2.jpg/640px-73_Grove_Street%3B_Lynbrook%2C_NY-2.jpg)](https://commons.wikimedia.org/wiki/File:73_Grove_Street;_Lynbrook,_NY-2.jpg)<br>_A sidewalk continuing uninterrupted across a driveway._

If a user has vision impairment and relies on a navigation application for turn-by-turn voice instructions, a crossing alert every few yards would be “crying wolf”, desensitizing them to a subsequent road crossing. For a routing engine, knowing the location of every way-connecting node is a prerequisite to supporting `highway=crossing` anyways.

[![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Mining_company_house.JPG/640px-Mining_company_house.JPG)](https://commons.wikimedia.org/wiki/File:Mining_company_house.JPG)<br>_A typical residential area with a driveway every few yards._

That said, there’s plenty of gray area. It would be useful to tag crossing-related details such as curb cuts where a service road does interrupt the sidewalk:

[![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Nokesville_Post_Office%3B_north_and_west_%28front%29_sides%3B_Nokesville%2C_VA%3B_2014-04-13.jpg/640px-Nokesville_Post_Office%3B_north_and_west_%28front%29_sides%3B_Nokesville%2C_VA%3B_2014-04-13.jpg)](https://commons.wikimedia.org/wiki/File:Nokesville_Post_Office;_north_and_west_%28front%29_sides;_Nokesville,_VA;_2014-04-13.jpg)<br>_A parking lot entrance interrupting a sidewalk._

[![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Eastern_Avenue_alley.jpg/640px-Eastern_Avenue_alley.jpg)](https://commons.wikimedia.org/wiki/File:Eastern_Avenue_alley.jpg)<br>_An alley interrupting a sidewalk. Even though most states have laws establishing implied crossings at intersections, [intersections with alleys don’t always count](https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=VEH&sectionNum=275.)._

If there’s a significant gray area, then the validator doesn’t have enough context to steer the user toward a particular solution. The disconnected ways validator rule recognizes this fact: in addition to “Connect the features”, it offers to create a bridge or tunnel:

<img src="https://user-images.githubusercontent.com/1231218/158054767-2d6260d1-d8bd-4615-8309-ad8928491552.png" width="379" title="Validator">

For service roads, how about adding the option “Add a pedestrian crossing” and making “Connect the features” just connect the features? Then, for roads other than service roads, where there’s more likely to be a formal crossing, we could rename “Connect the features” to “Add a pedestrian crossing” to be more upfront about what the option does.

[^driveway]: In American English, “driveway” is a broad term that can refer to just about any service road. However, here I mean the kind of driveway typically found in front of residences but also found in front of smaller businesses.

**Comment by Woazboat** [comment]
I strongly support the objections voiced here by others. Not every intersection between a footway and another road should automatically be tagged as `highway=crossing`. `highway=crossing` should be used for designated street crossing points or (implicit/unmarked) crossings over roads that are part of the normal street network and not just for every minor driveway. 

If `highway=crossing` is used for absolutely every footway-road intersection, it loses its significance and becomes useless. These intersections can be detected automatically (as proven here), so there would be no point in adding a tag that does not convey any additional meaning.

**Comment by kaligrafy** [comment]
In the Quebec province, we are trying to standardize crossings and here is the consensus so far: add a crossing whenever the probability of a conflict between a pedestrian/cyclist and a vehicle is not negligeable (by conflict we just mean a moment where one has to wait for the other to cross). So for every commercial/industrial/shop/school driveway crossings, we add crossings to the sidewalks and cycleways. For residential driveways, we add them only when there are at least 5 parking places served by the driveway, so that eliminates 90% of all the single house driveways, for which probability of conflict is very low/negligeable during an average day. This serves us well because we can now calculate the probability of accidents by measuring the crossing length/width for pedestrian, the kind of crossing (which type of driveway/street is crossing the sidewalk/cycleway) which is becoming really useful in a Vision-Zero era. I think this is the best middle-ground consensus.
