### ISSUE TITLE
Spanish backgrounds layers are not available over Ceuta and Melilla / #Spain

### ISSUE THREAD

**Issue by JCGF-OSM** [openstreetmap/iD#8510]
The nexts layers are not available to work with they in this two autonomus cities of Spain.
I expect that is a bug, because they work well in others editors like JOSM.

![Background layers in Ceuta and Melilla](https://i.imgur.com/ey5wQrp.jpg)

### List of layers (Not Working):

- PNOA Spain
- Catastro Spain

### Links to the cities boundaries in OSM

- [Ceuta](https://www.openstreetmap.org/relation/1154756)
- [Melilla](https://www.openstreetmap.org/relation/1154757)

**Comment by JCGF-OSM** [comment]
**Similar issue:**

#5264

_**File:**_ [imagery.son](https://raw.githubusercontent.com/openstreetmap/iD/master/data/imagery.json)

**Preview of the poligons coverage of the layers in the area.**

![Preview of the imagery.json file](https://i.imgur.com/WOOeE1m.jpg)

**Comment by boothym** [comment]
I don't think this is an iD issue, because iD gets its background layers from the editor-layer-index project.

You can see that Ceuta and Melilla are missing from the coverage here: https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/es/CatastroSpain.geojson

You should submit an issue over there: https://github.com/osmlab/editor-layer-index/issues
