### ISSUE TITLE
Invisible crossing=traffic_signals

### ISSUE THREAD

**Issue by PiRomant** [openstreetmap/iD#8516]
```
crossing=traffic_signals
highway=crossing
``` 
looks exactly like just `highway=crossing`
![image](https://user-images.githubusercontent.com/29551044/119475594-7bc1fa00-bd77-11eb-997d-abbec5dba0f0.png)
Should be used at least `railway=signal` icon
![image](https://user-images.githubusercontent.com/29551044/119476380-33570c00-bd78-11eb-8bf9-4753b8bf954c.png) 
or `crossing=marked`
![image](https://user-images.githubusercontent.com/29551044/119476991-cb54f580-bd78-11eb-801d-48b666671c30.png)

**Comment by cicku** [comment]
It may happen when the path across the road is not marked crosswalk but just foot path or whatever else.

**Comment by PiRomant** [comment]
This is not a bug, it is a problem of visually checking the point.

**Comment by hungerburg** [comment]
This looks like a case, where iD developers push for a certain kind of mapping style. While I agree, that "marked" is more meaningful than "uncontrolled", in the case of "traffic_signals", "marked" is falling way behind.

C.f. https://github.com/openstreetmap/iD/commit/1ffca3ce85d630539c7ebb11454a91770bd76536 where bhousel says, that `crossing=traffic_signals` never has been supported, in a way, that suggests, that it probably never will?

**Comment by bhousel** [comment]
This was a few years ago (2018), but I remember in the past we ignored the `crossing=traffic_signals` value because mappers different places used the tag to mean very different things.

Sometimes it's a crossing near a traffic light with walk/dontwalk sign (these can be marked or not, with kerb ramps or not), sometimes it's an isolated crossing with a pushbutton to make nearby lights flash, sometimes it's a HAWK crossing.. 

I think even the opensidewalks folks throw out the `crossing=traffic_signals` value and also coalese the other values into marked/unmarked. (It's been years since I synced up with them).

So basically, we had a long discussion about this a while ago with a lot of stakeholders and `crossing=marked/unmarked` was seen as better by data consumers because it's unambiguous, and you can map it easily from aerial imagery. There are other accepted tags if people want to supply information about the lights and buttons and other enhancements.  Please check the tagging mailing list archives too, because I remember a lot of discussion there.

> This looks like a case, where iD developers push for a certain kind of mapping style.

We really just try to support the tagging that the community and data users want.  We're not sitting around thinking up tags to "push" onto people, so please don't spin it that way.  It's an open source project and we are just trying to do right by our users.

**Comment by hungerburg** [comment]
`It's an open source project and we are just trying to do right by our users.` I don't see how the two propositions relate. I see though, that there are 800k crossing=traffic signals mapped on OSM and that the tag is going strong. I think framing the issue like this seriously downplays the inhomogenity among iD users: Perhaps those mappings do not stem from organised mapping efforts, but none by iD users? All the more so, as iD is not a commercial product, where some select users are the customers, and therefore surely earn preferential treatment, but instead is the number one editor of a collaborative experiment, that goes by the name openstreetmap. Additionally, I don't see, how unhiding crossing=traffic_signals would damage their efforts.
