### ISSUE TITLE
validator shouldn't warn about a highway=path crossing building=roof

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/iD#8521]
paths can go under the roof

**Comment by bhousel** [comment]
this was #5924
IIRC, the JOSM validator has special consideration in the code to allow `building=roof` to cross some features without a `level` or `covered` tag.  We instead preferred to not add special code for certain types of buildings (because next people will ask for special code for gazebos or shelters or whatever else).

**Comment by andrewharvey** [comment]
Ah I missed that existing ticket, I'll close this now then, I realised the validator asks you which one is higher/lower and sets a level tag.
