### ISSUE TITLE
Use emergency=designated instead of service=emergency_access

### ISSUE THREAD

**Issue by map-per** [openstreetmap/iD#8526]
The service=emergency_access Tag is controversial as many emergency access roads are foot- or cycleways and not service roads. That's why it would be better to use the access Tag emergency=designated instead to classify something as an emergency access road in iD.
(see https://wiki.openstreetmap.org/wiki/Tag:service%3Demergency_access and https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddesignated as well)

**Comment by bhousel** [comment]
Can you link to a wider discussion on this?  From what I can see of the page history, you just edited those pages today to say that it's the preferred tagging scheme.

**Comment by map-per** [comment]
I took the description of emergency=designated over from https://wiki.openstreetmap.org/wiki/Key:emergency. 
Some discussion can be found here:
https://forum.openstreetmap.org/viewtopic.php?pid=804604#p804604
https://forum.openstreetmap.org/viewtopic.php?id=64114

**Comment by bhousel** [comment]
I realize now you're talking about this preset:

<img width="300" alt="Screen Shot 2021-06-04 at 10 03 18 AM" src="https://user-images.githubusercontent.com/38784/120813678-1ced4500-c51c-11eb-92ab-f0959d0cb10d.png">

`service=emergency_access` is a well-established tag that's been around since 2011:
https://taghistory.raifer.tech/#***/service/emergency_access
<img width="500" alt="Screen Shot 2021-06-04 at 10 06 32 AM" src="https://user-images.githubusercontent.com/38784/120814124-908f5200-c51c-11eb-84b5-56014087881f.png">

If the concern is people are using this preset for footpaths, we could just rename it to something like "Emergency Vehicle Access".

**Comment by map-per** [comment]
Renaming the preset is a good idea. 
For ways that only serve as an emergency access and not as a footway or driveway as well service=emergency_access could be a suitable tag. But how do you call a road that is only used as an emergency access but for nothing else. "Emergency Vehicle Access" doesn't soud like the best option to me but I have no better Idea so far.

**Comment by map-per** [comment]
Maybe "Way exclusively used as an emergency access" or is that to long?

**Comment by cicku** [comment]
The wiki page of this tag was a hell. It was "an access road for firefighters".

Glad it was changed.

**Comment by map-per** [comment]
> Glad it was changed

Thanks, good to get feedback. Wasn't quite sure wather it was a good idea to change the wiki pages until now.

**Comment by map-per** [comment]
> `service=emergency_access` is a well-established tag that's been around since 2011:

You are right and emergency=designated isn't used that often. So imporving the wiki explanation is probably the best solution
