### ISSUE TITLE
Show ref in the name of route relations

### ISSUE THREAD

**Issue by k-yle** [openstreetmap/iD#8559]
from https://github.com/openstreetmap/iD/pull/8276#issuecomment-869580303:

It's quite a pain currently to edit bus routes with similar names, especially since in real life, the name is rarely used and the ref is more commonly used in conversations etc.

![image](https://user-images.githubusercontent.com/16009897/123624235-723e1d00-d862-11eb-93d5-83a84261523e.png)

it would be much more helpful if the ref (the bus route number) is shown

**Comment by 1ec5** [comment]
Showing `ref` could be helpful for other kinds of routes too, not just bus routes. I think we should also include `network` for consistency with other formats that include `ref`. It’s possible that some routes are better known by their names than their reference numbers, but hopefully enough of both will be visible to help the user select the right relation.

My main motivation for #8276 was to provide an alternative to the common and once recommended practice of stuffing `name` with descriptive text. `network`, `ref`, `from`, and `to` could easily crowd out `name`, but in cases where `name` has been tagged descriptively, that should be merely an aesthetic problem rather than a usability problem.

**Comment by 1ec5** [comment]
This issue was closed due to the back-and-forth in #8707, but I’m convinced we should do something along the lines of what was proposed there.

To mitigate the concern about redundancy with the legacy PTv2 `name` format, we can add a special case that avoids pulling in other keys if `name` contains `=>`, `→`, `⇒`, `⇔`, or similar (so much for consistency), or if it already contains the value of `ref`. Besides, this relation formatter is used for all route relations, not just those covered by the PTv2 specification.
