### ISSUE TITLE
iD loading out-of-date Bing Imagery, but only on the osm.org mirror

### ISSUE THREAD

**Issue by hb0nd** [openstreetmap/iD#8601]
This started happening with the v2.20 update

On the openstreetmap.org/edit mirror of iD, I get this: https://www.openstreetmap.org/edit#map=18.83/51.48124/-0.00133
the correct imagery is used on the stable iD mirror: https://ideditor-release.netlify.app/#map=18.83/51.48124/-0.00133

It's not a caching issue (at least on my end), it persists after hard refreshing, and happens on other devices I've never used iD on.

The left imagery is old, and was replaced by the right imagery a few weeks ago
![Screenshot from 2021-07-28 18-00-24](https://user-images.githubusercontent.com/26939824/127366903-9bf3dc48-1e8d-4e29-bf88-fe51063b778a.png)

**Comment by mbrzakovic** [comment]
Thanks for reporting this.

I acknowledge the issue and am working on a solution.

**Comment by hb0nd** [comment]
> Thanks for reporting this.
> 
> 
> 
> I acknowledge the issue and am working on a solution.

Awesome, thank you :)

**Comment by pnorman** [comment]
Sample URLs: osm.org deployment: https://ecn.t2.tiles.virtualearth.net/tiles/a1202020200202000002.jpeg?g=10555&n=z
netlify.app deployment: https://ecn.t1.tiles.virtualearth.net/tiles/a1202020200202000002.jpeg?g=587&mkt=en-gb&n=z

**Comment by hb0nd** [comment]
This seems to be fixed now, thank you :)

**Comment by hb0nd** [comment]
Never mind, it's started happening again

**Comment by mbrzakovic** [comment]
I've applied short term fix on this. bc0c189. This 'playing around' with generation number is not convenient, the core of the problem is that there is an api key quota limit for the call that should pull the latest generation number. (this would also explain why you noticed that the issue was fixed and then not).
- We are working on the long term solution that would solve the quota and remove this 'playing around' of generations. Please expect this in the next month or so.
