### ISSUE TITLE
NSI validator suggests replacing Greyhound and GoBus with BoltBus

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/iD#8606]
[This route relation](https://www.openstreetmap.org/relation/10479463) belongs to GoBus, a brand owned by Barons Bus Lines as part of the Greyhound network. For some reason, the name-suggestion-index validator wants to replace the tags with those of BoltBus, which was operated by Greyhound but just went out of business.

<img src="https://user-images.githubusercontent.com/1231218/127608977-97276164-3379-4ea3-a2e7-3b019a345523.png" width="300" alt="GoBus">

Even [a normal Greyhound line](https://www.openstreetmap.org/relation/10477486) can trigger a warning about BoltBus:

<img src="https://user-images.githubusercontent.com/1231218/127609541-09f408f9-9897-4ed1-a28c-08fa37ee4f51.png" width="300" alt="Greyhound">

**Comment by 1ec5** [comment]
It probably would be reasonable to add an NSI entry for GoBus. Also, `not:operator:wikidata` should suppress the validator warning along the lines of #6577. But the apparent mismatch in the network matching code seems more concerning.

**Comment by mbrzakovic** [comment]
[this PR](https://github.com/openstreetmap/iD/pull/8305) was a great upgrade, however it is possible that it introduced the behavior you described.
@bhousel can you please take a look at this?

**Comment by bhousel** [comment]
> It probably would be reasonable to add an NSI entry for GoBus. Also, `not:operator:wikidata` should suppress the validator warning along the lines of #6577. But the apparent mismatch in the network matching code seems more concerning.

I looked into this today - It's because NSI has Greyhound as `network=Greyhound Lines` not `network=Greyhound`.

These are the tags on the route:

![Screen Shot 2021-07-30 at 12 46 04 PM](https://user-images.githubusercontent.com/38784/127685447-cd2bd8eb-9f06-43e8-9528-cbb3438ff81a.png)

The validator tries matching this route against 4 k/v/n tuples in this order:

![Screen Shot 2021-07-30 at 12 41 32 PM](https://user-images.githubusercontent.com/38784/127685003-2c937899-7701-4e6d-881b-50bfb391a3d6.png)

It doesn't match the primary "Greyhound" so starts falling back to other alternate values.

Q755309 matches both Bolt Bus and Greyhound Lines as an _alternate_ match, and it took the Bolt Bus one.

To fix this right now, I can:
- Add a `matchName` "Greyhound" to NSI item for "Greyhound Lines". 
- Or - rename the item to "Greyhound" and add a matchName for "Greyhound Lines" if that's really how people tag?  I'll check overpass and see.

**Comment by bhousel** [comment]
> To fix this right now, I can:
> 
> * Add a `matchName` "Greyhound" to NSI item for "Greyhound Lines".
> * Or - rename the item to "Greyhound" and add a matchName for "Greyhound Lines" if that's really how people tag?  I'll check overpass and see.

Just following up - it's overwhelmingly mapped with `network=Greyhound` so we'll keep it that way for now in NSI.

**Comment by bhousel** [comment]
Published v6.0.20210730 and I'm getting much more reasonable tag suggestion now:
(older version may be served from the CDN to some users for a few hours more).
 
<img width="377" alt="Screen Shot 2021-07-30 at 4 36 03 PM" src="https://user-images.githubusercontent.com/38784/127709090-b2e07a69-2b18-46a1-912b-736f5daae58c.png">
