### ISSUE TITLE
2.20.0 tag validation issue

### ISSUE THREAD

**Issue by cicku** [openstreetmap/iD#8615]
When adding Internet access tags to a hotel brand:

Before
![image](https://user-images.githubusercontent.com/686438/127787711-694fa116-033e-4ce6-afff-a33b6b1b76df.png)

After
![image](https://user-images.githubusercontent.com/686438/127787721-e40dc89f-2782-46fd-b4dd-4108707aed5c.png)

**Comment by UKChris-osm** [comment]
@bhousel is this an [NSI issue](https://nsi.guide/index.html?t=brands&k=tourism&v=hotel#fairfieldinnandsuites-29a1d7)?

**Comment by bhousel** [comment]
> @bhousel is this an [NSI issue](https://nsi.guide/index.html?t=brands&k=tourism&v=hotel#fairfieldinnandsuites-29a1d7)?

My guess is that there are 2 competing tags for `internet_access` and the NSI entry for "Fairfield Inn and Suites" has a different one than whatever iD's Hotel preset wants to set it to.

I'll look into this and change it on the NSI side if that's what it is.

**Comment by bhousel** [comment]
Ok this issue is a bit more interesting than I initially thought.  

`internet_access=yes` is being considered a "primary" or "toplevel" tag.  (sort of like `amenity=yes` or `emergency=yes`)
The reason this tag is being considered this way is because we have these ["LinkNYC"](https://nsi.guide/index.html?t=operators&k=internet_access&v=wlan) internet access points in NSI.

(This is another situation like what we originally saw in testing #8305 where it would try to [remove `emergency=yes` from hospitals](https://github.com/openstreetmap/iD/pull/8305#issuecomment-778707926) for the same reason)

I'll add some special code to preserve `internet_access` tags, since they can go on almost anything.
