### ISSUE TITLE
iD should not use the Facebook logo for NSI brands

### ISSUE THREAD

**Issue by cicku** [openstreetmap/iD#8703]
Example:

Country Inn & Suites

![image](https://user-images.githubusercontent.com/686438/133890505-58a04c98-b0a0-45c4-9498-ea962f0b10ec.png)

->
![image](https://user-images.githubusercontent.com/686438/133890509-1e546d0e-f7ab-45b6-a10e-cec02b6863a3.png)

->

![image](https://user-images.githubusercontent.com/686438/133890553-bfaf157a-1232-4344-99ad-13fc87d43c53.png)

![image](https://user-images.githubusercontent.com/686438/133890533-c5c13641-8122-46e4-aaf0-b4f03d1d4f3a.png)

The correct logo should be this one on wikipedia:

https://en.wikipedia.org/wiki/File:Country_Inn_%26_Suites_logo.svg

**Comment by 1ec5** [comment]
That isn’t even the Facebook page for Country Inn & Suites. There was an incorrect Facebook ID statement in the brand’s Wikidata item, which was [recently removed](https://www.wikidata.org/wiki/Special:Diff/1499584648). NSI needs to be rebuilt to incorporate that change.

In order for NSI to use the SVG logo that the English Wikipedia is using, the image needs to be transferred to Wikimedia Commons so that Wikidata can link to it. The file is tagged as being in the public domain; if that’s accurate, licensing wouldn’t be an issue.

**Comment by bhousel** [comment]
Thanks - it looks like next time we sync up the NSI project with wikidata we'll pull the correct logo.
