### ISSUE TITLE
display fixme field above others

### ISSUE THREAD

**Issue by ghost** [openstreetmap/iD#8730]
When checking problems it is always useful to read the fixme field first and it should be shown first above the other fields. Right now it will somewhere at the bottom and I need to scroll down every time to read it.  
The field 'note' should probably be second since it is also important information that is typically empty anyway.

**Comment by 1ec5** [comment]
Good idea. If I remember correctly, this was the original motivation for spelling the key `FIXME` instead of `fixme`, but fields give us extra flexibility without requiring capitalization hacks. Sorting is controlled by [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema/) in general, though I’m unsure if it would be straightforward to always put a “more” field on top of all the default fields for all the presets.

**Comment by boothym** [comment]
Think this is basically #7206?

**Comment by ghost** [comment]
Exactly like that. Must've totally missed that one.
