### ISSUE TITLE
Validator: Why are golf=* features "incomplete" without landuse=grass?

### ISSUE THREAD

**Issue by DaveF63** [openstreetmap/iD#8748]
Why are golf=* features flagged as "incomplete" without landuse=grass?
 
 https://www.openstreetmap.org/edit?way=841794494#map=18/51.38320/-2.33330
 
Was this include as a 'tag incorrectly for the renderer' to get it to do so before OSM-Carto included golf features?

 landuse=grass in not required. It is for specific areas as indicated in the wikipage's first sentence:
 https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dgrass
 
The landuse of golf features is 'golf' not grass.
To distinguish any differences the 'surface' tag should be used.

golf=* are a specific sport subset of leisure=pitch. 
The tag to distinguish it's playing finish is 'surface'
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpitch
 
I believe this validation check is an error & reduces the quality of the OSM database. 

Same for golf=bunker &  natural=sand. Use surface=sand

**Comment by bhousel** [comment]
The fairway and green golf presets included `landuse=grass` when they were added about 8 years ago in 56d9ac56, see issue #2013 .

> Was this include as a 'tag incorrectly for the renderer' to get it to do so before OSM-Carto included golf features?

I definitely wouldn't frame this as "tag incorrectly for the renderer" or "reduces the quality of the OSM database".  We should rather assume that the iD team added it this way with good intent.

If you are really interested in these tags, you could look at what the various OSM guides (Wiki, Potlatch, JOSM) recommended back in 2013 when John added the presets.  Maybe it said to add the tag?  Maybe we can stop adding it today?  Tagging evolves and that's ok.

**Comment by DaveF63** [comment]
I'm interested in preventing false data from being added into OSM.

Landuse is a primary tag - it works on it's own, without other tags - landuse=residential, commercial etc.

#2013 & the validator incorrectly implemented it as a secondary/adjective tag ie describing what the golf features look like. 'Surface' is the correct tag to do that in this instance. This has led to inaccurate data being added to the OSM database. It needs to be rescinded ASAP.

**Comment by jpotas** [comment]
These items are tagged as Golf because that is the land use. They are not tagged incorrectly, they are all associated with a golf course. This tagging method allows for programs to pull in golf course features from OSM. They certainly are not tagged incorrectly, it actually adds value to the item tag by creating more detail and making it more accurate. Please do not flag these items.

**Comment by DaveF63** [comment]
@jpotas 
To counter most of what you said I refer you to my original comment.
"This tagging method allows for programs to pull in golf course features from OSM. "
By 'programs' are you referring to 'The Golf Club 2019' game? My understanding is that it only imports 'golf' tag, ignoring any that are descriptive .

In general all data consumers have to accept the database as is, which includes adapting to any changes to correct database errors, of which using landuse, in this instance, is one.

**Comment by jpotas** [comment]
@Dave F

Strictly your opinion.  I have reported you to OSM for changing spline labels.

**Comment by DaveF63** [comment]
Ooh, excellent. 
Unsure what you mean by 'spline labels' as OSM doesn't use splines, but look forward to reading replies.
Where is your report? Can you provide a link or why not paste it here for all to see?

Hardly just my opinion. I've provided two wiki links explaining why.
Here's a third, defining it categorically:
 "Do not use the tag landuse=grass in order to make the rendering more appealing. Use surface=grass" 
 
 https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgolf_course

**Comment by davidpnewton** [comment]
https://wiki.openstreetmap.org/w/index.php?title=Tag:leisure%3Dgolf_course&diff=1006704&oldid=983655

This is the changeset where alterations were made to the wiki page. The date is 26th March 2014, and the commit to ID referenced above was 26th November 2013. So the change to the wiki was made four months after the commit to ID was made.

Now the old version of the wiki page did talk about tagging for the renderer that is true, however it also mentioned describing "the bunker a little more" in the context of natural=sand and similarly for landuse=grass.

The reality is that instead of mass-reverting edits (like 1895 changes to golf course features over the whole of southern England in one edit a couple of days ago), the change should have been argued through for ID first. See people like me tend to get a little cheesed off when lots of validator corrections get reversed. I have re-done a local golf course twice after DaveF decided to do his mass reverts.

Now I happen to agree that landuse=golf is an appropriate tag for an entire golf course. However the landuse tag is _not_ used entirely for actual landuses. Landuse=grass and landuse=forest say hello. It should also be pointed out that nested uses of landuse as a tag are not out of the question.

To me the opening paragraph of the landuse=grass wiki page is most apropos, "A tag for a smaller areas of mown and managed grass for example in the middle of a roundabout, verges beside a road or in the middle of a dual carriageway." So what are fairways, greens and tees? Smaller areas of mown and managed grass. Sheer weight of usage also comes down on favouring it. Taginfo has surface=grass used in combination with golf=* 81,157 times, whereas landuse=grass is used in combination with golf=* 643,144 times. I don't know how much of that is down to having it set in the tagging preset in ID, but I suspect a fair amount of it is because of that. The combination of landuse=grass and golf=* is used nearly as many times as the whole usage of surface=grass.

Much as purists might like a complete conceptual distinction between landuse=* and surface=*, in reality that does not exist.

**Comment by bhousel** [comment]
Anyway this is an issue with the presets and is being tracked on https://github.com/openstreetmap/id-tagging-schema/issues/203 
That repo is where the fix would need to go.

**Comment by SK53** [comment]
> https://wiki.openstreetmap.org/w/index.php?title=Tag:leisure%3Dgolf_course&diff=1006704&oldid=983655
> 
> This is the changeset where alterations were made to the wiki page. The date is 26th March 2014, and the commit to ID referenced above was 26th November 2013. So the change to the wiki was made four months after the commit to ID was made.
> 

I made that change because the advice on the wiki was incorrect.  I doubt if I had any awareness of what was in iD's presets as I did not use it as an editor until several years later.

The golf tags were explicitly introduced after a lengthy discussion by quite a number of participants in 2009/10, precisely because people were mapping golf courses using other tags in order for them to render. Subsequently, Richard Weait made an overlay rendering of golf features based on the tags. Unfortunately Richard's original blog and the rendering have long gone. Unfortunately, I can't find the original discussion which included an example of someone trying to render a golf course in South India (IIRC) where grass tags would have been incorrect on some features.

**Comment by EdLoach** [comment]
> Unfortunately Richard's original blog and the rendering have long gone.

I found the blog post via a [help.openstreetmap.org reply](https://help.openstreetmap.org/questions/5642/disappearing-golf-course) containing the link, and [archive.org](https://web.archive.org/web/20111126110120/http://weait.com/content/golf-course-style-openstreetmap)
