### ISSUE TITLE
validator could consider a `public_transport=platform` way as routable

### ISSUE THREAD

**Issue by stragu** [openstreetmap/iD#8760]
Hi all

This is clearly related to the discussion in #6409, but I haven't followed the discussion in detail and I am not aware of what made the developers change their mind on the suggested addition of explicit `highway=footway` tags by the validator.

In any case, I came across the `disconnected_way` issue in [this object](https://www.openstreetmap.org/way/683341103), because its connection to the whole network goes through [a way tagged as `public_transport=platform`](https://www.openstreetmap.org/way/683341106).

I'm wondering if the validator should consider the way tagged as `public_transport=platform` as a routable way. It seems to me it would be quite common to have detailed public transport stations in which, to cross from one side to the other of the building, you would have to walk on sections of platforms. The debate might be more relevant for areas, but isn't this straight-forward for a way?

And just taking the opportunity to thank you all for the great work on the editor :+1:

**Comment by 1ec5** [comment]
It would help to know which routers consider `public_transport=platform` on its own to be routable. The validator rule is essentially designed to inform the user about problematic routing that could occur, so it ideally wouldn’t get ahead of actual router support. I didn’t see any explicit references to this tag in the [OSRM](https://github.com/Project-OSRM/osrm-backend/), [Valhalla](https://github.com/valhalla/valhalla/), [OsmAnd](https://github.com/osmandapp/), and [OpenTripPlanner](https://github.com/opentripplanner/OpenTripPlanner/) repositories, but I’m not as familiar with the OsmAnd and OTP codebases.

**Comment by stragu** [comment]
@1ec5 OsmAnd does seem to use it:

![8D12505B-A63B-4DF2-BA53-2D355FC4D17A](https://user-images.githubusercontent.com/1747497/138089178-cc757477-0b96-4efc-a8c5-071b6ada0219.png)

The only other mobile app I have is Organic Maps, which doesn’t even render a way tagged as such in its default rendering (and doesn’t use it in routing).

**Comment by 1ec5** [comment]
Thanks for looking further into the matter. I’m not fully caught up on the discussion in #6409 either, but this does seem like a tricky situation.

Your example of [Greenslopes platform 1](https://www.openstreetmap.org/way/683341099) is tagged as `highway=bus_stop` on a way. This is invalid tagging, or at least not recommended, according to the wiki’s [`highway=bus_stop`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop) and [`public_transport=platform`](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform) pages. I wonder if OsmAnd happens to route along this platform by coincidence due to the presence of a `highway=*` tag, but not because of `highway=bus_stop` or `public_transport=platform` specifically. OsmAnd doesn’t route over other ways tagged `public_transport=platform` without `highway=bus_stop`. The inconsistency may be a bug worth reporting in the appropriate [OsmAnd repository](https://github.com/osmandapp/) (I’m not sure which).

I tested some popular OSM-based routing engines on this way and two others with different tag combinations. The consensus among routers seems to be that platforms aren’t inherently routable. Some come up with very circuitous routes, going out of their way to avoid the platform, while others come up with no route at all, suggesting an as-the-crow-flies path between two waypoints.

&nbsp; | [Greenslopes 1](https://www.openstreetmap.org/way/683341099) | [San Antonio 2](https://www.openstreetmap.org/way/125742123) | [Meadowview](https://www.openstreetmap.org/way/239378377)
----|:--:|:--:|:--:
_Tags_ | `public_transport=platform` `highway=bus_stop` | `public_transport=platform` `railway=platform` | `public_transport=platform`
[BRouter](https://brouter.de/brouter-web/) v0.16.0 | [✅](https://brouter.de/brouter-web/#map=19/-27.51097/153.04018/standard&lonlats=153.040026,-27.510795;153.040307,-27.511217&profile=hiking-beta) | [❌](https://brouter.de/brouter-web/#map=19/37.40771/-122.10753/standard&lonlats=-122.108094,37.407835;-122.10775,37.407616&profile=hiking-beta) | [❌](https://brouter.de/brouter-web/#map=19/38.48366/-121.46762/standard&lonlats=-121.467684,38.483607;-121.467623,38.483468&profile=hiking-beta)
[GraphHopper](https://www.graphhopper.com/) | [❌](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=-27.51118%2C153.04041%3B-27.51076%2C153.04001)  | [✅](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=37.40760%2C-122.10776%3B37.40731%2C-122.10738) | [❌](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=38.48360%2C-121.46768%3B38.48346%2C-121.46763)
[Magic Earth](https://apps.apple.com/us/app/magic-earth-navigation-maps/id1007331679) v7.6.7 | [❌](https://user-images.githubusercontent.com/1231218/140811695-199b4f5d-6cc1-4e9a-9caf-65451ab465da.jpg) | [❌](https://user-images.githubusercontent.com/1231218/140811745-6f760d66-15f5-4662-af3a-e547518abd21.jpg) | [❌](https://user-images.githubusercontent.com/1231218/140811791-99ca706e-26c8-4d6c-9eb7-8cc112a505c2.jpg)
[Openrouteservice](https://maps.openrouteservice.org/) | [❌](https://bit.ly/3m2Try5) | [✅](https://bit.ly/3B4OdWC) | [❌](https://bit.ly/3CgcJWt)
[OsmAnd](https://apps.apple.com/app/osmand-maps-travel-navigate/id934850257) v4.0.6 | [✅](https://user-images.githubusercontent.com/1231218/138217871-4d80bc15-d1af-4933-bee9-2ad5a07049c2.jpg) | [❌](https://user-images.githubusercontent.com/1231218/138217922-74d22d6b-8632-447a-978b-c303e30210b1.jpg) | [✅](https://user-images.githubusercontent.com/1231218/140603403-f0078efa-bd57-4c48-8ea4-89bb965bce13.jpg)
~~[OSRM](http://project-osrm.org/) v4.6~~ ([Organic Maps](https://apps.apple.com/app/organic-maps/id1567437057)) | [❌](https://user-images.githubusercontent.com/1231218/138218054-3230c452-b6b2-49db-ba07-049985b8ccdf.jpg) | [❌](https://user-images.githubusercontent.com/1231218/138217922-74d22d6b-8632-447a-978b-c303e30210b1.jpg) | [❌](https://user-images.githubusercontent.com/1231218/140603403-f0078efa-bd57-4c48-8ea4-89bb965bce13.jpg)
OSRM v5.23 ([FOSSGIS](https://routing.openstreetmap.de/about.html)) | [❌](https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=-27.51118%2C153.04041%3B-27.51076%2C153.04001) | [✅](https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=37.40760%2C-122.10776%3B37.40731%2C-122.10738) | [❌](https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=38.48360%2C-121.46768%3B38.48346%2C-121.46763)
[Transit](https://apps.apple.com/app/transit-subway-bus-times/id498151501) v5.10.4 | [✅](https://user-images.githubusercontent.com/1231218/140605106-b6c9cf5a-be4f-49be-a3ab-310c5139fbb0.jpg) | [✅](https://user-images.githubusercontent.com/1231218/140605144-de33af80-96ff-4a99-83eb-8ae289c3d85e.jpg) | [❌](https://user-images.githubusercontent.com/1231218/140605159-276a992e-6f53-4fde-b216-7b7efc4a27a0.jpg)
[Valhalla](https://valhalla.readthedocs.io/) ([Mapbox](https://docs.mapbox.com/api/navigation/directions/)) | [❌](https://user-images.githubusercontent.com/1231218/140605735-fb54200a-fb5d-4d13-9bed-2f5b6f2616b3.png) | [❌](https://user-images.githubusercontent.com/1231218/140605738-aee12fe7-e203-4a44-a359-afb2a4d7897f.png) | [❌](https://user-images.githubusercontent.com/1231218/140605743-b210741f-ef1d-4bc4-ba11-c87e7e64cab9.png)

<details>
<summary>Magic Earth v7.6.7</summary>
<img src="https://user-images.githubusercontent.com/1231218/140811695-199b4f5d-6cc1-4e9a-9caf-65451ab465da.jpg" width="250" alt="Magic Earth Greenslopes 1">
<img src="https://user-images.githubusercontent.com/1231218/140811745-6f760d66-15f5-4662-af3a-e547518abd21.jpg" width="250" alt="Magic Earth San Antonio 2">
<img src="https://user-images.githubusercontent.com/1231218/140811791-99ca706e-26c8-4d6c-9eb7-8cc112a505c2.jpg" width="250" alt="Magic Earth Meadowview">
</details>

<details>
<summary>OsmAnd v4.0.6</summary>
<img src="https://user-images.githubusercontent.com/1231218/138217871-4d80bc15-d1af-4933-bee9-2ad5a07049c2.jpg" width="250" alt="OsmAnd Greenslopes 1"> <img src="https://user-images.githubusercontent.com/1231218/138217922-74d22d6b-8632-447a-978b-c303e30210b1.jpg" width="250" alt="OsmAnd San Antonio 2"> <img src="https://user-images.githubusercontent.com/1231218/140603403-f0078efa-bd57-4c48-8ea4-89bb965bce13.jpg" width="250" alt="OsmAnd Meadowview">
</details>

<details>
<summary><del>OSRM v4.6</del> (Organic Maps)</summary>
<img src="https://user-images.githubusercontent.com/1231218/138218054-3230c452-b6b2-49db-ba07-049985b8ccdf.jpg" width="250" alt="Organic Maps Greenslopes 1">  <img src="https://user-images.githubusercontent.com/1231218/138218106-ac4c0399-0317-40a9-a697-e0984bc2df17.jpg" width="250" alt="Organic Maps San Antonio 2"> <img src="https://user-images.githubusercontent.com/1231218/138218158-9af0dd1e-c72b-4e3a-9e40-3167d31efcbd.jpg" width="250" alt="Organic Maps Meadowview">
</details>

<details>
<summary>Transit v5.10.4</summary>

Note: Basemap is Apple Maps, but pedestrian route geometry is reportedly OSM-based.

<img src="https://user-images.githubusercontent.com/1231218/140605106-b6c9cf5a-be4f-49be-a3ab-310c5139fbb0.jpg" width="250" alt="Transit Greenslopes 1"> <img src="https://user-images.githubusercontent.com/1231218/140605144-de33af80-96ff-4a99-83eb-8ae289c3d85e.jpg" width="250" alt="Transit San Antonio 2"> <img src="https://user-images.githubusercontent.com/1231218/140605159-276a992e-6f53-4fde-b216-7b7efc4a27a0.jpg" width="250" alt="Transit Meadowview">
</details>

<details>
<summary>Valhalla (Mapbox)</summary>
<img src="https://user-images.githubusercontent.com/1231218/140605735-fb54200a-fb5d-4d13-9bed-2f5b6f2616b3.png" width="250" alt="Valhalla Greenslopes 1"> <img src="https://user-images.githubusercontent.com/1231218/140605738-aee12fe7-e203-4a44-a359-afb2a4d7897f.png" width="250" alt="Valhalla San Antonio 2"> <img src="https://user-images.githubusercontent.com/1231218/140605743-b210741f-ef1d-4bc4-ba11-c87e7e64cab9.png" width="250" alt="Valhalla Meadowview">
</details>

&nbsp; | [Airport](https://www.openstreetmap.org/way/386347380) | [Windward](https://www.openstreetmap.org/way/334554290)
----|:--:|:--:
_Tags_ | `public_transport=platform` `railway=platform` | `public_transport=platform`
[OpenTripPlanner](https://www.opentripplanner.org/) v1.5.0 ([MARTA](http://itsmarta.com/planatrip.aspx)) | [❌](http://itsmarta.com/planatrip.aspx#plan?fromPlace=33.64136%2C-84.44679&toPlace=33.64037%2C-84.44678&date=11%2F06%2F2021&time=1%3A59%20AM&optimize=QUICK&mode=TRANSIT%2CWALK&numItineraries=3&wheelchairAccessible=false) | [❌](http://itsmarta.com/planatrip.aspx#plan?fromPlace=34.08621%2C-84.26049&toPlace=34.08584%2C-84.26077&date=11%2F06%2F2021&time=1%3A59%20AM&optimize=QUICK&mode=TRANSIT%2CWALK&numItineraries=3&wheelchairAccessible=false)

Maybe this is just a matter of routers being slow to take up the `public_transport` tagging scheme, which was introduced relatively late compared to the tags that they do consider inherently routable. OSM is stuck in a yearslong limbo of `public_transport=platform` being widely dual-tagged with legacy tags – thanks in no small part to #4585 adding it to presets – but few data consumers supporting that tag on its own as an alternative to the legacy tags. Project-OSRM/osrm-backend#5410 and valhalla/valhalla#3691 request support for routing over platforms; there may be similar requests against other routers and renderers. If you’ll excuse the pun, I think more traction on these issues would make editor and validator developers feel a lot more comfortable treating platforms as inherently routable.

Another possibility is that data consumers are expecting platforms to be mapped as areas only. In the absence of area routing (osmlab/osm-planning#17), they may also expect the likely paths through those areas to be mapped as footways, just as in pedestrian plazas.

Even though tagging for the ~~renderer~~ router is frowned upon, the mere presence of this routability validator rule means some mappers will rely on it to be informed about any potential routing issues. So even if a mapper does care that the station they’re mapping is usable by the current generation of routers, the lack of this warning may lull them into a false sense of security.

What if the validator rule’s warning message were more transparent about what’s considered routable? Maybe it could determine that a particular `public_transport=platform` way is the gap in the routing network and point out that some routers may not consider it routable. This would have a side benefit of making the warning more actionable.

https://github.com/openstreetmap/iD/blob/1ee45ee1f03f0fe4d452012c65ac6ff7649e229f/modules/validations/disconnected_way.js#L163-L176 https://github.com/openstreetmap/iD/blob/49f5d03e55a230ce8f04289c818ff36fb0d08569/data/core.yaml#L1756-L1763

----

<img src="https://user-images.githubusercontent.com/1231218/138195888-e10e9b78-e68a-4a08-9a57-a265e394a3a9.png" width="48" align="right" alt="Get directions"> By the way, osm.org also has a routing feature that you may find convenient in debugging routing issues. Click the  Get Directions button next to the search bar. You can select from a couple different providers to reduce the temptation to tailor your tagging to a particular routing engine’s quirks.

**Comment by stragu** [comment]
@1ec5 : thank you, this is the most thorough testing and review I have seen anyone do for any bug report I have ever created! It paints a very clear picture of the situation. :slightly_smiling_face: 

Thanks for the reminder to use osm.org to test the different routing engines, I should have thought of that earlier (especially given that I have done it in the past!).

So, if I understand it well, in a nutshell:

* The tag `public_transport=platform` is not currently widely used as a routable element by routers
* The warning is useful to notify mappers that the section will unlikely be routable in apps
* Furthermore, routers might assume all public transport platforms to be areas, and will therefore ignore them when routing
* The situation might change in the future, as many people think ways and areas tagged with `public_transport=platform` could logically be used by pedestrians

Is that an accurate summary?

I am wondering, as a small improvement to the validator message, if the text could be changed slightly, for example: 

> "{count} _commonly_ routable features are connected only to each other" 

Or, in a more verbose way:

> "{count} routable features are connected only to each other _(or are connected to the rest of the network by a feature not commonly considered by data users as routable)_

In any case, I have [reported the wish to see public transport platforms to be routable by OsmAnd](https://github.com/osmandapp/OsmAnd-iOS/issues/1549), as it was not mentioned on any repository. Curious to see what the developers think of this one.

**Comment by 1ec5** [comment]
I think this is a good summary overall. I honestly don’t know if or when the situation might change, since it depends on a number of software projects that don’t move in lockstep, some of which are no longer actively maintained (like the outdated version of OSRM embedded in Organic Maps). There may also be downsides or technical constraints that hadn’t occurred to us mappers. Since compiling the table above, I discovered that Openrouteservice does route over `public_transport=platform` ways – but curiously, it only works with the wheelchair profile, not the pedestrian profile. Filing feature requests against the routing engines, as you’ve started to do, is the best way to get everyone on the same page and move past the handwaving that took place in the past.

> "{count} _commonly_ routable features are connected only to each other"

I think this would be a good and easy stopgap fix. The explanatory text below it could elaborate if “commonly” is too ambiguous. This should just be a matter of modifying the strings here; please feel free to open a PR with suggested wording:

https://github.com/openstreetmap/iD/blob/49f5d03e55a230ce8f04289c818ff36fb0d08569/data/core.yaml#L1756-L1763

> Maybe it could determine that a particular public_transport=platform way is the gap in the routing network and point out that some routers may not consider it routable. This would have a side benefit of making the warning more actionable.

To elaborate on this idea, `routingIslandForEntity()` would maintain two `routingIsland` sets and two `waysToCheck` queues. It would store the gap way (a `public_transport=platform` way or perhaps any other way that’s likely to be undertagged) in a local variable and add it to the alternative routing island:

https://github.com/openstreetmap/iD/blob/1ee45ee1f03f0fe4d452012c65ac6ff7649e229f/modules/validations/disconnected_way.js#L106-L110

And check both queues in parallel:

https://github.com/openstreetmap/iD/blob/1ee45ee1f03f0fe4d452012c65ac6ff7649e229f/modules/validations/disconnected_way.js#L97-L103

In addition to the main routing island’s members, it would also return the gap way that resulted in populating the alternative routing island:

https://github.com/openstreetmap/iD/blob/1ee45ee1f03f0fe4d452012c65ac6ff7649e229f/modules/validations/disconnected_way.js#L140-L141

This would give the warning code the opportunity to identify the gap way explicitly, which would be helpful in case of a large routing island:

https://github.com/openstreetmap/iD/blob/1ee45ee1f03f0fe4d452012c65ac6ff7649e229f/modules/validations/disconnected_way.js#L25-L32

This extra checking could significantly impact performance, but it would only be active under limited circumstances.

**Comment by stragu** [comment]
> Since compiling the table above, I discovered that Openrouteservice does route over `public_transport=platform` ways – but curiously, it only works with the wheelchair profile, not the pedestrian profile.

Have you reported the issue to OSRM? Sounds like something they would want to sort out.

> This would give the warning code the opportunity to identify the gap way explicitly, which would be helpful in case of a large routing island

That would be a great improvement. I did end up spending some time trying to figure out where the issue was as it all looked connected at first sight.

Regarding a potential PR, I will give that a go! Cheers :slightly_smiling_face:

**Comment by 1ec5** [comment]
> Have you reported the issue to OSRM? Sounds like something they would want to sort out.

Touché. I think you meant Openrouteservice, though. It seems to be a different routing engine: GIScience/openrouteservice#1081.

**Comment by stragu** [comment]
@1ec5 I think there might be an inaccuracy in the testing of OsmAnd routing. I tested it and I got:

* routable on ways with both `public_transport=platform` and  `railway=platform` (test with [Corinda station](https://www.openstreetmap.org/way/890668385))
* I noticed that your third screenshot uses the car profile instead of the pedestrian profile. However, I found a way with only  `public_transport=platform` in my area and could confirm that OsmAnd does not route over it. For example: [Normanby platform](https://www.openstreetmap.org/way/480017426)

Cheers

![image](https://user-images.githubusercontent.com/1747497/140064441-c802596d-1dc6-4099-80b1-b2cabd82edad.png)
![image](https://user-images.githubusercontent.com/1747497/140064465-c886eaac-7745-44d9-a9e3-1023627745d4.png)

**Comment by 1ec5** [comment]
Ah OK, that would be consistent with what I saw with OSRM 5.3 on the FOSSGIS server then: `railway=platform` is routable but not `public_transport=platform`.

**Comment by stragu** [comment]
@1ec5 do you want to amend your table in https://github.com/openstreetmap/iD/issues/8760#issuecomment-948196855 ? It's a great summary to point to in other reports :)

**Comment by 1ec5** [comment]
> I noticed that your third screenshot uses the car profile instead of the pedestrian profile.

I reran the test and corrected the table above. But now I’m confused, because OsmAnd is definitely routing over `public_transport=platform` ([Meadowview](https://www.openstreetmap.org/way/239378377)) but not `public_transport=platform` `railway=platform` ([San Antonio 2](https://www.openstreetmap.org/way/125742123)).

> routable on ways with both `public_transport=platform` and  `railway=platform` (test with [Corinda station](https://www.openstreetmap.org/way/890668385))

This way is part of a `railway=platform` `foot=yes` [multipolygon](https://www.openstreetmap.org/relation/12116137), which is weird. I’m not sure it necessarily disproves the results I got with the platform at San Antonio above.

> However, I found a way with only  `public_transport=platform` in my area and could confirm that OsmAnd does not route over it. For example: [Normanby platform](https://www.openstreetmap.org/way/480017426)

Your destination got snapped to [a footway](https://www.openstreetmap.org/way/480017417). Here’s OsmAnd routing over the platform:

<img src="https://user-images.githubusercontent.com/1231218/140603824-1ba7987b-3ffe-4b01-9abe-cc2cd2b303e6.jpg" width="250" alt="Normanby">

Contrast this with the San Antonio platform, where moving the waypoints closer together allows the origin to snap to the platform but still doesn’t convince the router to traverse the platform:

<img src="https://user-images.githubusercontent.com/1231218/140603958-2811089d-c4a3-451a-93e9-6a79b5b9f306.jpg" width="250" alt="San Antonio 2">

Anyways, my point stands that `public_transport=platform` isn’t _reliably_ routable yet, which is the point of the validator warning, even if it’s worded in absolute terms. Even if OsmAnd were to achieve consistency across all these cases, the validator rule isn’t intended to cater to OsmAnd over all the other routers.

**Comment by peternewman** [comment]
Somewhat linked to this, GraphHopper seems to still be the only one of the routers on the OSM website to route over a platform when I've just tested, however it does raise an alternative issue, they seem to ignore the ticket gates (at least one tagged as barrier=turnstile). For some stations there are footbridges or underpasses you can access from either end, but you need a validated ticket (e.g. tap in on a contactless card) to be on the station, yet GraphHopper will happily route me across this without so much as a warning.

**Comment by 1ec5** [comment]
How was the platform tagged? So far I’ve only found it to route over `railway=platform` when walking: https://github.com/openstreetmap/iD/issues/8760#issuecomment-948196855.

**Comment by jidanni** [comment]
All I know is currently a path connecting Railway Platform A to Railway Platform B creates a warning.
All I know is a railway platform is like a big block of butter.
I shouldn't need to create arbitrary paths across it to silence the errors.

**Comment by 1ec5** [comment]
It’s just a warning, not an error. If you don’t have adequate local knowledge, imagery, or traces to resolve the warning, leave it to someone else to resolve the warning.

**Comment by jidanni** [comment]
All I am saying is I know every inch of that Railroad platform, and it's just a solid platform that you can walk in any direction across. Any path that I would make going across it would be just as valid as any other path in any other random direction going across it.

It's just like if I put an ant in the middle of a dish and then made a path on the map whatever way the ant walked: it's just as valid and, just as invalid as any other path across a random blank area.

It's just like the electrons are passing along a wide copper strip.
Saying that there is an additional wire laid on top of that is simply
not the Ground Truth.

**Comment by jidanni** [comment]
I just did a test: would a one dimensional (line (unclosed way)) platform also get the error? Yes.

Well, how could that be? Why is a one dimensional platform different than a one dimensional footpath? Both should be routable.

**Comment by 1ec5** [comment]
That would be a question for the routing engines listed above – potentially a good bug report to their developers.

**Comment by Dimitar5555** [comment]
@jidanni There is a reason for routers to try to avoid platforms. In some countries platforms are part of the paid zone (i.e. you have to validate your ticket/card/travel pass at a machine to enter). You can fix the routing problem by adding `highway=footway` to the platform. See https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=42.69467%2C23.31501%3B42.69226%2C23.31046#map=17/42.69382/23.31350 for such example.

**Comment by jidanni** [comment]
Well a footway could also pass through a fare gate or a custom gate. So the router should be sensitive to gates. And the mapper should remember to put the gates on the map.

I mean we're supposed to map the things that are on the ground. And there's no path going across a big piece of pavement that's all the same.

No matter if it's people, or electrons, they all can figure out ways of going across a plane.

But okay, I guess I should start thinking of this in terms of suggested routes.

If I suggest a person take these routes across these items, then I guess I'll start feeling better about it and get used to it. Thanks
