### ISSUE TITLE
Option to Remember or Change Default Background Layer.

### ISSUE THREAD

**Issue by DicePenguin** [openstreetmap/iD#8777]
I have been mapping my area for about a few years currently. The default background I have been using is the Bing areal imagery. However, recently today there was a change in the background imagery lists, because a new local image layer being added. I would have found this alright, but I found that the imagery layer is of a lower resolution and harder to see features than the Bing areal imagery I've been using. 

   I found that the ID editor doen't remember my decision to use Bing aerial imagery every time I click the "Edit" button. Is there a way for ID editor to remember what background layer I prefer when I want to make another edit, and if not can a method be added to the user interface?

**Comment by 1ec5** [comment]
Where is this area (generally speaking)? It could be that one of the recently added layers covers your area and has been marked as `best`. If it’s of lower resolution, it probably shouldn’t be marked `best`. You can visualize the coverage areas of various layers using [this tool](https://osmlab.github.io/editor-layer-index/).

**Comment by tordans** [comment]
I think this is https://github.com/openstreetmap/iD/issues/8665.

**Comment by DicePenguin** [comment]
This is for the area New Jersey, United States. It is indeed marked as best, but as you say it's a much lower resolution.

**Comment by DicePenguin** [comment]
Specifically, central New Jersey south of the the Raritan River in Sayreville, NJ.  I agree that it shouldn't be marked as "best".

**Comment by DicePenguin** [comment]
More specifically I'm referring to the area of Central NJ where the towns such as East Brunswick, Sayreville, South River, South Amboy are located.

I used the tool 1ec5 mentioned and found the background I am referring to is:
US / NJGIN Orthoimagery 2020 - Natural (1ft leaf off)

It is outlined in gold meaning is has been tagged as "best". Can this be fixed or changed?

**Comment by tyrasd** [comment]
Closing as this duplicates the existing issue #8665. I've forwarded the question about this specific layer to the editor-layer-index: https://github.com/osmlab/editor-layer-index/pull/1244#issuecomment-967031660

**Comment by cicku** [comment]
I added this imagery into the index because it is a statewide imagery captured in 2020 and it has compatible license. Bing cannot be updated at the same frequency level and in fact it is quite notorious in many US states (for example Pennsylvania) for stale data. Just because it is your default imagery does not mean the rest of the community holds the same opinion.

If you are concerned about the resolution, I do agree that 1ft could be troublesome but it is not unusable. Keep in mind that many countries in the world still have 30cm satellite images which is roughly double, it does not prevent them drawing on openstreetmap.

I’m ok to remove the best flag because 2022 is coming, but not because of any reason you listed above. In fact, statewide orthoimagery often takes more effort in the post-processing, it deserves “the best”.

**Comment by andrewharvey** [comment]
The best flag is always a bit controversial because it tries to cover both resolution and currency at the same time. If Bing in an area is more recently updated and has good enough resolution, then can agree removing the best flag from local ortho imagery if it's not as good for mapping. But given it's subjective there won't be a right answer, you can always manually change the imagery used.
