### ISSUE TITLE
Maxar the same as Bing?!

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8798]
### URL

https://www.openstreetmap.org/edit#map=18/24.16419/120.71242

### How to reproduce the issue?

Choose Maxar or Bing and the imagery is the same.
Well if the companies have merged then there is no more need for two buttons.
Maybe related to #8732?

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by TheAdventurer64** [comment]
It should be noted that in Hawaii Maxar, Bing, and sometimes Esri all use the same imagery, but have different offsets and overlays.

**Comment by jjiglesiasg** [comment]
The original provider of several of such pictures is Airbus Aerospace, so is normal that the 3 services have the same aerial imaginery, dosent means that is the same case all around the world...

**Comment by jidanni** [comment]
All I know is Bing used to be frozen forever, only showing 10 year old imagery.

So maybe OpenStreetMap could express to the Bing Corporation that we are
still interested in that old imagery. Upon which Bing might say 'OK,
sure.' and then "Bing" could be retitled "old Bing", and then it
wouldn't just be a near copy of the rest.

**Comment by jjiglesiasg** [comment]
In Highlands areas, Bing however old, is the less distorted and less offset imaginery, in comparison with Maxar and Esri. Why? I really dont know

**Comment by bhousel** [comment]
> Choose Maxar or Bing and the imagery is the same.

Yes, it's expected that in some places the different imagery layers may look the same.  As @jjiglesiasg said, they might have purchased from the same vendor in that part of the world.  Also different locations or zooms might show different imagery, and it can change at any time (Bing might buy new imagery tomorrow), so it's good to have a few options to compare.

> So maybe OpenStreetMap could express to the Bing Corporation that we are still interested in that old imagery. Upon which Bing might say 'OK, sure.' and then "Bing" could be retitled "old Bing", and then it wouldn't just be a near copy of the rest.

"Esri World Imagery (Clarity)" should be a near identical match for "Old Bing".  This is actually important for iD because we used that imagery when we made the walkthrough, so it's good that it's still available and hopefully will be for a while.
