### ISSUE TITLE
Split, divide: be consistent

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#8819]
### Description

Perhaps be consistent:
use only one of "divide" or "split".

### Screenshots
![20211119T032358](https://user-images.githubusercontent.com/1230959/142484691-05f0c317-bf7a-4b20-945b-899043b2dbe2.jpg)

**Comment by tyrasd** [comment]
As far as I can tell, this is on purpose. The description uses a synonym or different wording to make the functionality clear to users who might not fully understand from the title alone what it does. For example, if I as a non-native speaker don't know what "Split" means, I will still no grasp it, if the description just repeats the same term.

**Comment by tyrasd** [comment]
I see that many of the other tooltips use some repeated wording in their title and description. I would however rather reword those descriptions. For example, instead of `Square | Square the corners of this feature.` it could say something like `Square | Make the corners of this feature rectangular.`

**Comment by jidanni** [comment]
Oh no, my bug report is now headed in the opposite direction.
I better quit while I'm ahead!
