### ISSUE TITLE
Make a higher starting level of privacy for new iD-users

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/iD#8831]
### Description

Follow up of task "Privacy Policy" #7040 changing the order of logic when third party data is used, see also message/comment https://github.com/openstreetmap/iD/issues/7040#issuecomment-568723720 
("_What about changing the default to opt in, rather than opt out? That's often viewed as better security & privacy_?")

**Comment by bhousel** [comment]
I gave people an option to opt out of showing the icons, but forcing everyone to take that option is unfair, and hides the work being done by the [NSI](https://github.com/osmlab/name-suggestion-index) team to canonicalize the brands, transit and other features.  We regularly get people showing up to contribute to NSI because they "want an icon to show up in iD", and OpenStreetMap POI and transit coverage has improved a lot directly because of this work and showing these icons in the user interface.  People are very motivated by this.

Also as discussed on that other ticket, there is far more of a privacy concern in how we use background imagery in iD and OpenStreetMap.  When you map, iD, Potlatch, JOSM is sending these requests to Microsoft, Esri, Mapbox, etc, and people have been fine with this for like 15+ years.  

We've tested using GET urls to fetch these NSI icons and it doesn't affect your social profile in any way.  You can log out of these sites, delete your account, and it still works - it's no different than fetching a gravatar image.  If your browser or an extension blocks the request, iD will fallback to showing the normal preset icon.

**Comment by tyrasd** [comment]
I agree with @bhousel (partially) in that defaulting to an opt-out for this setting would significantly lower the user experience while mapping POIs.

I do however think that the privacy settings are too hidden in the preferences menu. In 4658df64e902ad26f3d28aa2abd97ddaf7faa2c7 I have added a section to the splash screen, which is shown to every user when they load up iD for the first time, so that users who want to can make an informed decision about disabling the setting or leaving the setting enabled. It looks like this now:

<img src="https://user-images.githubusercontent.com/1927298/144644750-f09e5e4c-1e14-4a00-aebf-698adf579378.png" width=400>

I feel that this is a good compromise for all user groups: those who are are concerned about privacy, as well as those who prefer the best possible user experience.

**Comment by bhousel** [comment]
> I feel that this is a good compromise for all user groups: those who are are concerned about privacy, as well as those who prefer the best possible user experience.

Thank you - this is perfect 👍
