### ISSUE TITLE
Custom Background option has been removed from iD

### ISSUE THREAD

**Issue by Martin868** [openstreetmap/iD#8853]
### How to reproduce the issue?

Simply open the layer menu, the Custom option is gone

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Safari

**Comment by boothym** [comment]
The custom background option is still available for me, in version 2.20.2 (see bottom right corner).

You are best to take a screenshot to show the problem.

**Comment by Martin868** [comment]
Here is a screenshot. The Custom option is used to ne next to None
<img width="1440" alt="screenshot_490" src="https://user-images.githubusercontent.com/34344860/146079617-80f18ff9-7dd8-4b14-b454-aa0e4eff08f3.png">

**Comment by Martin868** [comment]
I cleared the Brower Cache in Safari and the Custom option is back. Something strange happened and I have no idea how. But it is back to normal now. Cheers.

**Comment by tyrasd** [comment]
this is quite odd. I think there must be a bug (to be fixed) which is only triggered in very specific situations. sadly, since you have already deleted your cache, we can't reproduce it anymore. If it happens again, could you please check if there are any error messages in the browser "javascript" console (https://webmasters.stackexchange.com/a/77337/53086 has some instructions for how to do that)? That would help a lot to investigate the issue.
