### ISSUE TITLE
Refactor core/ into module

### ISSUE THREAD

**Issue by tmcw** [openstreetmap/iD#891]
This is the 'holy grail' goal of post-launch refactoring - a module that's only reliant on d3 and/or a few other libraries and can be tested / used separately.

**Comment by gmaclennan** [comment]
Any interest in revisiting this and https://github.com/openstreetmap/iD/pull/889?

We've been forking iD editor for different applications - offline, custom databases outside OSM - but the lack of modular structure makes modifications and re-use hard. It would be great to meet some of iD's [early goals](https://github.com/openstreetmap/iD/blob/master/ARCHITECTURE.md#core) of being "a reusable, modular library to kickstart other JavaScript-based tools for OpenStreetMap".

I know that [Moabi](http://moabi.org), [Development Seed](https://developmentseed.org/) and [American Red Cross](https://github.com/AmericanRedCross) are all looking at using customized iD for different use-cases. Perhaps we could coordinate an effort to refactor iD to make it more re-usable / modular / hackable?

@kriscarle @hallahan @smit1678

**Comment by bhousel** [comment]
Yes let's make it happen.  Lets coordinate over email and pick a time in the next month or so for me to come down to DC for a few days of code sprint.

**Comment by hallahan** [comment]
We're currently heads down on doing some mods on iD to handle fetching OSM XML from OpenMapKit Server, applying filters on that data, staging it, and then submitting it to either the main OSM or a Macrocosm API.

I'm making do with being as plugin-y like as I can. Breaking things down into modules and creating a plugin architecture, I think, would be a great idea. I'd like to make sure that our work leverages developments with this, because right now I have to inject in some less than ideal spots to make things happen.

We're working on a _staging concept_ where we sort of "fast forward" the history graph model to have a given save based on what came from our data edit source ready for submission. With that, we are having to do some interesting stuff with generating SHA-1 checksums on properties of OSM entities, since new elements have negative IDs and these will be rewritten by the OSM server they are submitted to.

https://github.com/AmericanRedCross/iD/tree/omk2macrocosm/js/id

**Comment by tmcw** [comment]
Merging into newer issue #3118
