### ISSUE TITLE
Concatenate `source` values when paste tags

### ISSUE THREAD

**Issue by divulgacheur** [openstreetmap/iD#8943]
### Description

When pasting tags, the `source` tag is always overridden. I propose to concatenate the different values of `source` tag to keep history the object.  

### Screenshots
![Peek 2022-02-03 16-21](https://user-images.githubusercontent.com/36365881/152380622-9bcd2d99-e7e3-47ce-bc0e-150089ae2f40.gif)

**Comment by tyrasd** [comment]
Hi. Thanks for the suggestion. It's an interesting one.

My concern about this one is that it could be somewhat confusing that the pasting of tags would lead to different behaviors depending on the tags that are pasted. I'm wondering what makes the `source` tag special to warrant this special treatment. Should it apply to other semicolon-separable tags as well (e.g. `cuisine`, `ref`, `alt_name`, `vending`, etc.)? And how should a user act if they really want to override an existing tag value?

One could also argue that osmose is at fault here, because it apparently suggests to overwrite the existing `source` tag with the value `IGN …`. Couldn't osmose just offer you the combined value of both sources in this case (i.e.  `source=cadastre…;IGN…`)?

:thinking:

**Comment by divulgacheur** [comment]
You are right, it's on the side of osmose to combine values of both sources and not inside iD. Thanks for your help !
