### ISSUE TITLE
Validator consistency over rivers and layers

### ISSUE THREAD

**Issue by nc011** [openstreetmap/iD#8944]
The validator is currently inconsistent in how it flags features mapped over waterways (e.g., river) when the waterway is tagged as ```layer=-1```.

- ```building=*``` mapped over ```waterway=river``` throws validator warning 
- ```building=*``` mapped over ```waterway=river``` + ```layer=-1``` removes warning
- ```highway=*``` mapped over ```waterway=river``` throws validator warning 
- ```highway=*``` mapped over ```waterway=river``` + ```layer=-1``` still throws validator warning 

[Real world example](https://www.openstreetmap.org/way/1027402577). In this case, I haven't mapped the river as a tunnel because the building is actually an old mill. So the building has been built over the river but with access for the milling wheel in the water. Perhaps there is a better way to map, but the validator should probably be consistent in whether it's happy with ```layer=-1``` or not.

**Comment by tyrasd** [comment]
Hi. As far as I can tell, this is the intended behaviour. See https://github.com/openstreetmap/iD/blob/v2.20.4/modules/validations/crossing_ways.js#L112-L114:

```javascript

        if (featureType1 === 'building' || featureType2 === 'building') {
            // for building crossings, different layers are enough
            if (layer1 !== layer2) return true;
        }
```

I think this was implemented like this because of examples like the one you provided above, where the building is raised or forms a bridge like structure. For waterway/highway intersections, the check can be a bit more strict because it is always possible to add either a tunnel or bridge tag to at least one of the two map features to map the situation properly. This behavior seems fine to me. I also don't think that it is too confusing to have the validator to trigger at slightly different levels of detail in these two cases.

**Comment by nc011** [comment]
Hmm. How about the case of indoor mapping? Tagging an indoor walkway using ```level=*``` still results in the same issue, yet the walkway is in the building which doesn't get a validator warning. Seems kinda odd.

I think ```layer=*``` is enough to demonstrate that something is not connected to something else on a different layer, therefore no validator warnings are needed.

**Comment by tyrasd** [comment]
I think indoor features should just being handled like buildings in this case. :arrow_right: 6a9e0997c

> I think `layer=*` is enough to demonstrate that something is not connected to something else on a different layer, therefore no validator warnings are needed.

This is a valid standpoint, which I do understand. But one can argue that hinting users to add structures like bridges or tunnels where they are obviously missing is also a valuable suggestion to improve data quality which the validator can provide. Combining the layer-missing with structure-missing "validations" is IMHO a win-win situation without any real downside, or am I overlooking something?
