### ISSUE TITLE
Name change suggestion despite `preserveTags`?

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/iD#8968]
### URL

https://www.openstreetmap.org/edit?node=5579307932

### How to reproduce the issue?

After clicking the link, iD suggests changing the name.

### Screenshot(s) or anything else?

_Originally posted by @kjonosm in https://github.com/osmlab/name-suggestion-index/issues/6085#issue-1105024965_

I get a suggestion to also change the name of an office=association [despite preserveTags being set in NSI](https://github.com/osmlab/name-suggestion-index/blob/499eca616b198ba32749cef051fca4081c25eb9d/data/brands/office/association.json#L4), see screenshot.

<img width="439" alt="Bildschirmfoto 2022-01-16 um 12 16 33" src="https://user-images.githubusercontent.com/51236777/149657786-231cbaa8-f9c7-45e5-9b70-3cacbba1938a.png">

### Expected behavior

The `name` should not get suggested to be changed, similarly to how brands for [`tourism=hotel`](https://github.com/osmlab/name-suggestion-index/blob/499eca616b198ba32749cef051fca4081c25eb9d/data/brands/tourism/hotel.json#L4) also preserve names.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

**Comment by tyrasd** [comment]
:thinking: 

As far as I can tell, it works [as intended](https://github.com/openstreetmap/iD/blob/v2.20.4/modules/services/nsi.js#L519-L520):

The nsi entry defines its own `preserveTags` on [line 73](https://github.com/osmlab/name-suggestion-index/blob/499eca616b198ba32749cef051fca4081c25eb9d/data/brands/office/association.json#L73), which doesn't include the `name` tag. This overwrites the value specified for the nsi category (defined on [line 4](https://github.com/osmlab/name-suggestion-index/blob/499eca616b198ba32749cef051fca4081c25eb9d/data/brands/office/association.json#L4)). The [NSI](https://github.com/osmlab/name-suggestion-index/wiki/Category-Property-Reference#preserveTags) [documentation](https://github.com/osmlab/name-suggestion-index/wiki/Item-Property-Reference#preservetags) isn't super clear if the values for  `preserveTags` should be combined in such cases or not, but since @bhousel wrote the code of this module in iD, I would assume the way iD handles it is correct. FWIW, the way it is implemented in iD does seem to make sense, because otherwise there would be no way for an nsi entry to override any `preserveTags` value set as default for the whole category.

**Comment by bhousel** [comment]
Yes thanks for investigation @tyrasd , this is indeed working as intended - it looks like the `preserveTags` properties should be adjusted in the NSI data.
