### ISSUE TITLE
Closed ways tagged with `public_transport=platform` should be rendered as areas

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#8985]
### URL

https://www.openstreetmap.org/edit?way=470027608#map=19/42.64961/23.39364

### Screenshot(s) or anything else?

See https://wiki.openstreetmap.org/wiki/Tag:railway=platform

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by tyrasd** [comment]
As far as I can tell, this is a regression from 309bfacf74737d381cb19e8c149ebdf4b7f1d815, which essentially flipped the logic how tags of presets which can be used on both lines and areas are handled: before they defaulted to areas, now they are lines by default. This change was not unreasonable, since there exist some commonly used tags which should be handled in such a way: e.g. `leisure=track` or `barrier=wall`.

But then there are also examples where the inverse logic should be used: `waterway=dam` would be an additional example to the already mentioned `public_transport=platform`. :thinking:
