### ISSUE TITLE
Allow unglue action on areas

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#9053]
### Description

UseCase I need to unglue an area from a road or other area to fix its shape, maybe add another area in between (…).

Right now, I have to select all notes, then uglue, then select them one by one to move them.

I can try to speed up the select with the lasso tool, but in densely mapped areas that does not help.

I can try select + moving them together with the move-shortcut, but since there is not reliable way be sure which node (of a stack of nodes) I select, I end up moving the other border/area/notes in stead of mine, so I have to move them one by one.

Moving them one by one made more tedious since I still don't understand (or cannot remember…) how to reliably specify which note of a stack is selected.

All in all, a unglue-all and them move (shortcut) (and maybe shrink) would make this a lot easier.

**Comment by 1ec5** [comment]
The Disconnect operation already works when you select an area: https://github.com/openstreetmap/iD/issues/4245#issuecomment-484986865. Perhaps it was disabled because not enough of the area was visible?

Another thing you can do is to select the area, then hit Ctrl+DownArrow (⌘↓) to recurse down to its nodes, then remove all but the nodes you want to disconnect from the list of selected features, then Shift-select the area again to disconnect just the area at those nodes.

**Comment by tordans** [comment]
>The Disconnect operation already works when you select an area: https://github.com/openstreetmap/iD/issues/4245#issuecomment-484986865.

You are right. No idea why I did not see this…

>Ctrl+DownArrow (⌘↓)

Thanks, that is great as well. Will finally need to remember that shortcut!

Thanks for the help => Closed.
