### ISSUE TITLE
Wikidata field displays `[object Object]`

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9067]
### URL

https://www.openstreetmap.org/edit?way=172049896#map=18/42.68426/23.33316

### How to reproduce the issue?

1. Go to the specified URL
2. Add a field for wikidata
3. Enter anything in it

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/19364673/162403655-a71297ad-4c45-47f8-94c4-5b3ce4902b3e.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by 1ec5** [comment]
This is due to a “[significant but not breaking change](https://lists.wikimedia.org/hyperkitty/list/wikidata-tech@lists.wikimedia.org/thread/3LA6FDOZGSK6HSQY73XCFNT4BTYWOY64/)” to the Wikibase API’s response format, which was recently deployed on Wikidata.

iD expects the `wbsearchentities` response’s `search` items to contain objects with `label` and `description` properties that directly contain strings:

https://github.com/openstreetmap/iD/blob/7b0127f5e7b98214782574698c5fc8c970ed8caa/modules/services/wikidata.js#L47 https://github.com/openstreetmap/iD/blob/7b0127f5e7b98214782574698c5fc8c970ed8caa/modules/ui/fields/wikidata.js#L159-L168 https://github.com/openstreetmap/iD/blob/7b0127f5e7b98214782574698c5fc8c970ed8caa/modules/ui/fields/wikidata.js#L357-L371

However, these properties themselves now contain objects with `value` and `language` properties. Also note that the legacy `label` and description` properties in the root item object will eventually [go away](https://phabricator.wikimedia.org/T304878) too.

**Comment by nontech** [comment]
Hi all, I think Wikidata field display broke because a `display` property has been added which is not a string but an object in this case.

I created a PR - https://github.com/openstreetmap/iD/pull/9080
I think it fixes the bug.
Please have a look and let me know.
Looking forward to the feedback. Thanks.

**Comment by tyrasd** [comment]
fixed in 4770dc877
