### ISSUE TITLE
`Uncaught TypeError: e is undefined` when selecting Keepright-problems

### ISSUE THREAD

**Issue by crosspolar** [openstreetmap/iD#9068]
### How to reproduce the issue?

Try to tick "Keepright problems". Then window freezes and parts of app are not clickable anymore. I had chinese languange pack for firefox installed but not anymore.

### Screenshot(s) or anything else?

The console shows the error appearing when ticking Keepright Problems and a warning (?) I get when hovering the map
![image](https://user-images.githubusercontent.com/18083323/162509823-77ecf08b-9642-4772-a347-29f8d3c38f9d.png)

This is how window freezes, which doesn't dissapear after unselecting Keepright-problems:
![image](https://user-images.githubusercontent.com/18083323/162509453-9da04f22-b692-430a-a9a6-451d2b21cafa.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by st-anton** [comment]
Appears also on Edge, happens without chinese language pack as well.
Page has to be reloaded to run again.
Working with KeepRight is not possible with this bug.

**Comment by arch0345** [comment]
This might be a duplicate of #8963, check to see if this issue is still present when using https://ideditor.netlify.app/ (includes unreleased features)

Note that the version of iD on openstreetmap.org/edit is using the [latest release](https://github.com/openstreetmap/iD/blob/develop/CHANGELOG.md#2204) which doesn't include any of the [unreleased features](https://github.com/openstreetmap/iD/blob/develop/CHANGELOG.md#Unreleased) listed in the changelog

**Comment by arch0345** [comment]
The version on osm.org just got updated to v2.21.0. KeepRight seems to be working now:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/85302075/172659864-aec04cdd-e7bc-49bd-8735-d4eb5ff8ff5c.png">

**Comment by crosspolar** [comment]
Yes, I can confirm it's working
