### ISSUE TITLE
When hovering over a note, text goes beyond the border

### ISSUE THREAD

**Issue by BubbaJuice** [openstreetmap/iD#9070]
### URL

https://www.openstreetmap.org/edit#map=20/32.16334/-110.99066

### How to reproduce the issue?

1. Go to a note with a large amount of text in the first message. (Varies by formatting, etc.)
2. Hover over the note in the editor.
The issue should be present by going through these two steps.

I was not able to test the issue on Safari. 

### Screenshot(s) or anything else?

![Screenshot](https://user-images.githubusercontent.com/68205167/162633781-86842c10-e07f-43fa-9556-3f47231638ce.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.com, RapiD version at mapwith.ai/rapid

### Which browsers are you seeing this problem on?

Firefox, Chrome, Microsoft Edge

**Comment by danieldegroot2** [comment]
https://github.com/openstreetmap/iD/blob/ad67f81cfde96bfa17488ccb14b51a8655f81681/css/80_app.css#L2860

adds a scroll bar when the note is displayed.

https://github.com/openstreetmap/iD/blob/ad67f81cfde96bfa17488ccb14b51a8655f81681/css/80_app.css#L4020

when hovering leaves overflow visible and does not add a scroll bar.

**Comment by draunger** [comment]
hey @danieldegroot2 @BubbaJuice is this is still doing someone else i start doing this ?

**Comment by 1ec5** [comment]
I just tried this again and it seems to already have a scrollbar that looks good. It looks like this issue was fixed in #9074. I should’ve double-checked before adding the https://github.com/openstreetmap/iD/labels/good%20first%20issue label.

<img width="399" alt="Text clipped to border" src="https://github.com/user-attachments/assets/ede9af5b-2c97-42f0-9f0e-f37ec8d9b4ba">
