### ISSUE TITLE
Keep `building` tag when changing the preset from building to substation

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9104]
Currently the `building` tag is removed.

**Comment by tyrasd** [comment]
Agree, but this is rather a bug in the iD code handling the changes of presets (I've therefore moved it from the tagging repo): If the new preset includes a field for the old preset's tag, the tag should be preserved.

**Comment by Hufkratzer** [comment]
I think this is a duplicate of https://github.com/openstreetmap/iD/issues/5883 which (unfotunately) was closed and locked in Sept. 2019.

I have often observed iD users removing building tags from buildings when they have changed them to leisure=horse_riding. Of course, in almost all cases it makes not much sense to tag a building with leisure=horse_riding, but it also makes no sense to silently remove the building tag from a building. A better solution should be found .

EDIT/ADDITION:
Instead of automaically removing a building tag you could add a warning/issue with some explanation and the options:
* remove the building tag
* extract the feature tags to a new node
* ignore this issue

This way the user would be aware of the problem and what will happen.
