### ISSUE TITLE
Only make single splits on a closed way

### ISSUE THREAD

**Issue by BertMule** [openstreetmap/iD#9216]
### Description

When splitting a closed way, what  I really want to do, is do that at 2 specific points by 2 **single** splits. But it seems I can only do a **double** one, which creates 2 at once.

I can exactly select the first desired point, but the other is determined automatically, and by definition is not where I want it. Even unnoticed where it unpredictably appeared. And maybe causing trouble.

So I end up making a second split on the second desired point. This time singly. Maybe fix the undesired one afterwards, if possible, and found.

I did not find an option to make single splits. Or am I overlooking something?

If not, I would appreciate to have that as an option, defaultly.

**Comment by tyrasd** [comment]
:thinking:

What would be your expected outcome of a "single" split of a circular way? Since a split operation always needs to result in more output ways than input ways, at least two split points are necessary. Sure, one could use the "implicit" first/last node of the OSM way as the second auxiliary split point, but that wouldn't be any better than the current implementation, would it?

> And maybe causing trouble.

Can you please give some examples how a (potentially unnecessary) extra split point can cause problems?

> Or am I overlooking something?

Maybe the fact that one can select more than one vertex before invoking the split operation? That way you get the result of the split operation along the exactly chosen points. I notice that there is currently a bug which causes the result of the two-node split operation result to result in one extra split (i.e. a third split point), which shouldn't be there.

**Comment by BertMule** [comment]
All right, selecting 2 points would be exactly what I want!
I did not know of its existence. (I hope it does.)
I will try that next time.

**Comment by BertMule** [comment]
Update. 

Yes, that worked.
Happy with that 🙂
