### ISSUE TITLE
Bing Streetside shows white box

### ISSUE THREAD

**Issue by boothym** [openstreetmap/iD#9230]
Recently Bing Streetside has been showing a white box when you click on one of the blue dots. The following error is in the console (the second error only appeared when I ticked the high resolution box). If I click on the "view on bing maps" then I can see it on bing.com without any problems.
![bingerror](https://user-images.githubusercontent.com/16965772/182726860-e1995b84-344e-462d-b595-680dfa77737d.PNG)

**Comment by dobatovkin** [comment]
I'm having the same problem. Noticed that it affects mainly new (2019-2021) pictures and doesn't affect old ones (2014-2015).
<img width="498" alt="Screenshot 2022-08-17 at 14 36 56" src="https://user-images.githubusercontent.com/94719693/185109099-8b5d17e5-342e-44df-9954-25ee120654c5.png">
<img width="474" alt="Screenshot 2022-08-17 at 14 37 45" src="https://user-images.githubusercontent.com/94719693/185109631-f3423a5c-4be6-45bc-ab60-c7ffce4090fd.png">

**Comment by DujaOSM** [comment]
It might be caused by a different Firefox extension, check out #9211.

**Comment by boothym** [comment]
@DujaOSM I'm using Chrome so...

**Comment by AnonymousAlligatorOSM** [comment]
I'm getting this error in the console:

![image](https://user-images.githubusercontent.com/101657206/188760247-5c59c17e-9277-4bf0-8f90-fd82ee4ba4e4.png)

Which looks like it's referring to this line of code: https://github.com/openstreetmap/iD/blob/e66edcbc997a33963b108153da6d0f88d8a11573/modules/services/streetside.js#L285

**Comment by 1ec5** [comment]
> Which looks like it's referring to this line of code:

Thanks for pinpointing the error. This is the callback for a request to https://dev.virtualearth.net/mapcontrol/HumanScaleServices/GetBubbles.ashx . All the items in `data` look like this:

```
{
  "data": {
    "face": "01",
    "url": "https://t.ssl.ak.tiles.virtualearth.net/tiles/hs1003022022233211010.jpg?g=6338&n=z",
    "x": 0,
    "y": 0
  },
  "status": "error"
}
```

Each of these image URLs returns HTTP 200 with an empty response body.

As microsoft/MicrosoftStreetsidePlugin#8 shows, this issue is not specific to any extension or browser, but it is limited to the newer images that Microsoft has sourced from TomTom.

[This article from the other day](https://learn.microsoft.com/en-us/bingmaps/articles/getting-streetside-tiles-from-imagery-metadata) documents an official API for getting Streetside images and metadata. [This support answer](https://learn.microsoft.com/en-us/answers/questions/585970/osm-ltgt-bing-integration-not-working.html?childToView=590871#comment-590871) confirms that the “bubble” API endpoint we’re hitting is unsupported:

https://github.com/openstreetmap/iD/blob/cb1202883f907ae9a89b479ea04da10956a45711/modules/services/streetside.js#L20

**Comment by boothym** [comment]
There's been changes made in RapiD by @bhousel to apparently fix this issue: https://github.com/facebook/RapiD/commit/602cb771761f3e40dda0709b0b73dee515a61407 - can the same be done for iD?

**Comment by tyrasd** [comment]
I've applied the workaround used in RapiD… It's not really a good solution, because we should actually replace the undocumented API calls with Bing streetview's v8 API (see https://github.com/openstreetmap/iD/issues/8747#issuecomment-945669204). But it seems to do the job for now.

**Comment by 1ec5** [comment]
406c1a0690377de93715765c8628d470d4bab90c works, but it does no good without a release (#9729). Over the past several months, I’ve had to show scores of new mappers how to work around this bug (or switch to Rapid) just to be able to contribute productively in an urban area where Mapillary and KartaView have insufficient side-facing coverage.
