### ISSUE TITLE
Use `sector:name` as the label for `cemetery=sector`

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/iD#9232]
### Description

A preset for [`cemetery=sector`](https://wiki.openstreetmap.org/wiki/Tag:cemetery%3Dsector) was added in https://github.com/openstreetmap/id-tagging-schema/pull/517, which also added a field for [`sector:name`](https://wiki.openstreetmap.org/wiki/Key%3Asector%3Aname) for the section's dedicated name as suggested on the wiki. I would expect the value for `sector:name` to be the label for features tagged with `cemetery:sector`.

### Screenshots

```
cemetery=sector
sector:name=Garden of Reflection
```

Current:
![image](https://user-images.githubusercontent.com/85302075/183125812-77323200-1dc4-45d6-a218-7f1f9282badf.png)

Expected:
![image](https://user-images.githubusercontent.com/85302075/183125906-e0d99d6d-84a4-415c-bda5-c64fdad1f831.png)

**Comment by 1ec5** [comment]
I think we should remove the `sector:name` field and stick to `name`.

What’s the rationale for there being a separate `sector:name` for `cemetery=sector`? This doesn’t seem like `flag:name`, where the name is of the flag rather than the flagpole it’s tagged on. What does it mean if a single feature has both `name` and `sector:name` set? Should `ref` be replaced by `sector:ref`?

The original proposal for `cemetery=sector` proposed `name`, as with any other feature. `sector:name` appears to have been introduced en masse in [a single changeset](https://www.openstreetmap.org/changeset/113195631) on October 31, 2021, and [documented](https://wiki.openstreetmap.org/wiki/Special:Diff/2214273) the same day by the same mapper.

[Currently](https://overpass-turbo.eu/s/1kMS), `name` is used on 10,625 `cemetery=sector`s, while `sector:name` is used on only 714 `cemetery=sector`s, an almost 15:1 disparity. The vast majority of uses are in combination with `cemetery=grave`, to indicate the sector that a grave is located inside, not to name the sector itself.

If there’s a technical reason why `name` should not be used on `cemetery=sector`, that should be stated somewhere on the wiki before iD puts its weight behind `sector:name`. But I think this is just a case of the wiki page having a misleading definition that was obscured by high usage on a different feature type.

**Comment by arch0345** [comment]
Thanks for looking into this. I'll update the wiki article and the Cemetery Section preset to use `name` instead
