### ISSUE TITLE
Support social media links (`contact:facebook`, `contact:instagram` etc.)

### ISSUE THREAD

**Issue by hb0nd** [openstreetmap/iD#9252]
### Description

It would be good to have support for these tags to speed up adding info to POI, compared to having to manually type-out the tag each time.

I'm aware of https://github.com/openstreetmap/iD/issues/5538, however social media link tagging overwhelmingly uses the `contact:` prefix.

**Comment by danieldegroot2** [comment]
See linked https://github.com/openstreetmap/iD/issues/3915#issuecomment-595818412,
Anyhow, since then, there's now a tagging repository, so
- https://github.com/openstreetmap/id-tagging-schema/issues/434
- https://github.com/openstreetmap/id-tagging-schema/issues/121

@tyrasd Edit: has since been closed as duplicate.

**Comment by hb0nd** [comment]
> Anyhow, since then, there's now a tagging repository, so

ah right, thanks 👍
