### ISSUE TITLE
Automaticly Split up pasted tag

### ISSUE THREAD

**Issue by paulklie** [openstreetmap/iD#9267]
### Description

Currently, when the user wishes to paste a tag from the wiki, they need to individually copy the part before and after the equals (key and value), and paste them individually.
This could be made more simple: if the user pastes a key with an '=' into the key field, the key is split up, and the value moved into the correct field.

### Screenshots

Before:
![image](https://user-images.githubusercontent.com/73854742/187795132-8312c9f1-5546-46c8-8f10-e1d0db856762.png)
After:
![image](https://user-images.githubusercontent.com/73854742/187795179-c3aa6c91-2b37-4173-a331-72f03a8a4b41.png)

This works because the equals symbol is discouraged as a key: https://wiki.openstreetmap.org/wiki/Any_tags_you_like#Syntactic_conventions_for_new_tags

**Comment by lefuturiste** [comment]
Do you wish to implement this feature your self? This looks like a "Good first issue".

**Comment by bhousel** [comment]
If you switch the raw tag editor to text mode, pasting "k=v" strings should just work?

<img width="366" alt="Screen Shot 2022-09-01 at 3 25 37 PM" src="https://user-images.githubusercontent.com/38784/187996362-3f0a7f72-a6fd-4cd3-adc4-e6c18441b31a.png">

**Comment by paulklie** [comment]
> If you switch the raw tag editor to text mode, pasting "k=v" strings should just work?
> 
> <img alt="Screen Shot 2022-09-01 at 3 25 37 PM" width="366" src="https://user-images.githubusercontent.com/38784/187996362-3f0a7f72-a6fd-4cd3-adc4-e6c18441b31a.png">

Oh thanks, I am a bit embarrassed to say that I did not know that mode existed.
Though I would still suggest implementing the feature as it saves a click.

**Comment by bhousel** [comment]
> Oh thanks, I am a bit embarrassed to say that I did not know that mode existed.
> Though I would still suggest implementing the feature as it saves a click.

This is a sticky toggle - meaning, if the user prefers to be in text mode, it will always be that way.  
We don't need to save clicks here.

Mostly I'm pushing back because, a long time ago iD used to allow pasting like this and it did have some problems, and the text-mode entry just works better.

https://github.com/openstreetmap/iD/issues/5024
https://github.com/openstreetmap/iD/pull/5070
https://github.com/openstreetmap/iD/issues/6185
https://github.com/openstreetmap/iD/pull/6302
