### ISSUE TITLE
OSM ID preview.ideditor.com/master

### ISSUE THREAD

**Issue by GPSOruxMaps** [openstreetmap/iD#9295]
### Description

Does anyone know why the OSM ID development mirror is not working?
This was the best alternative to OSM ID to use on smartphones, it was very well optimized for small screens.
https://preview.ideditor.com/master

**Comment by tyrasd** [comment]
the problem is that the "v3" prototype was abandoned a relatively long time ago, meaning that it had outdated (in parts buggy) presets and tag deprecation rules, offered outdated imagery layers and also accumulated a number of bugs over time.

My goal is to bring some of the features of the prototype back into the maintained version of iD. Improved support for small screens is one of them.
