### ISSUE TITLE
Wiki says crossing=marked should not be used on ways?

### ISSUE THREAD

**Issue by EvanCarroll** [openstreetmap/iD#9303]
### URL

https://wiki.openstreetmap.org/wiki/Tag:crossing=marked

### How to reproduce the issue?

The wiki says crossing=marked should not be used on ways, only on nodes.

I saw someone do this, and I've been following it for a month now before I saw the wiki.

We shouldn't allow this if it should not be used on ways.

![Screenshot_2022-09-24_22-55-08](https://user-images.githubusercontent.com/19922/192127624-f45c09bb-f7d1-4fb1-b013-f7686861ef09.png)

**Comment by 1ec5** [comment]
Thanks for pointing out the discrepancy. It was most likely copypasta on the part of this page’s authors, or they overlooked the possibility of tagging it on `highway=footway`/`cycleway`. It was inconsistent with a number of other pages, such as the pages for [`crossing=*`](https://wiki.openstreetmap.org/wiki/Key:crossing) and [`crossing=traffic_signals`](https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dtraffic_signals), not to mention [this approved proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Sidewalk_as_separate_way). I [fixed the mistake](https://wiki.openstreetmap.org/wiki/Special:Diff/2273241/2400377).

**Comment by kaneap** [comment]
@1ec5 It may be worth discussing how much information we want to duplicate into the way. Funnily enough, the original proposal for separate way sidewalks never mentions adding a `crossing=*` value to the way with `footway=crossing`.

**Comment by 1ec5** [comment]
Proposals from that long ago weren’t often very comprehensively written, certainly not with the care that would be required for individual details to age well more than a decade later. In fact, [the original approved `crossing=*` proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Road_crossings), for all its warts, was supposed to be applied to ways (“linear”), not nodes.

The purpose of this validation warning is to indicate when a tag is used on an element type that’s invalid. If it truly is invalid, then there needs to be a much broader discussion about the practice of tagging crossing ways beyond iD. Introducing a warning in iD first would be needlessly disruptive. After all, `crossing=*` ways make up a quarter of all `crossing=*` elements, and `crossing=marked` ways make up 40% of all `crossing=marked` elements. My understanding is that, when crossings are mapped as ways, the redundant crossing node is only present for backwards compatibility, or perhaps for ease of processing for data consumers that only care about the road network.

**Comment by kaneap** [comment]
It's always interesting to see how the tags tend to evolve :smile: 

I think it is probably out of the scope of this proposal, so I'd be happy to carry this conversation somewhere which isn't a closed issue for a tangentially related issue.

**Comment by EvanCarroll** [comment]
> It may be worth discussing how much information we want to duplicate into the way. 

I think that's a great question. I don't have anything to add, except that the behavior of iD shouldn't be assumed to be correct. If a marked crossing goes four ways, should that be one marked crossing (four lines) be merged?

* If so, the street names can't be carried through from the sidewalk connections. The wiki notes (and testing has confirmed) that this means narration on apps can't tell you what streets to turn from. This isn't desirable.
* If not, it seems weird to go from a named sidewalk to an unnamed crossing.

One of these should be chosen and iD should pressure users into the right action.

> My understanding is that, when crossings are mapped as ways, **the redundant crossing node is only present for backwards compatibility**, or perhaps for ease of processing for data consumers that only care about the road network.

If so, there should be an advisory or chance to update it. I have no opinions on this though.

**Comment by 1ec5** [comment]
> If a marked crossing goes four ways, should that be one marked crossing (four lines) be merged?

It’s common to map it as either as a closed way or as four individual ways. Four individual ways would be required in cases where the crosswalks are connected by sidewalk segments. This is a good question, but it’s best asked in a less software-focused OSM support channel.

> If so, the street names can't be carried through from the sidewalk connections. The wiki notes (and testing has confirmed) that this means narration on apps can't tell you what streets to turn from. This isn't desirable.

This is a well-known issue, often debated on the tagging mailing list, the [community forums](https://community.openstreetmap.org/t/is-there-consensus-on-mapping-pavements-sidewalks-separately-to-roads/1067/), and elsewhere (e.g., OpenSidewalks/OpenSidewalks-Schema#2). However, this is usually brought up as an argument for not mapping crossings and sidewalks as ways to begin with, not as an argument to map crossings as ways without `crossing=marked`. As I mentioned, that particular wiki page was also inconsistent with related wiki pages, so I fixed the wiki’s internal inconsistency. The wiki shouldn’t be assumed to be correct, either. 😉

> If not, it seems weird to go from a named sidewalk to an unnamed crossing.

It depends on the situation and possibly user preference. valhalla/valhalla#3694 for instance takes the position that it’s fine to say “the crosswalk”, but I agree that there are situations where naming the street being crossed would be preferable, as in “Cross Main Street”. Fundamentally, most routers would have to transfer any node tags to a way in order to represent it in the routing graph anyways; that’s how routing graphs work.

As far as backwards compatibility, I was mainly referring to renderers that want to place an icon at the location of the crossing, but I think the hesitancy to ditch crossing nodes is mostly that some mappers would prefer to ditch crossing ways instead. 🤷‍♂️
