### ISSUE TITLE
Multiselecting highways with different Structure values is broken

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/iD#9369]
### URL

https://www.openstreetmap.org/edit#map=18/42.77859/-123.27859

### How to reproduce the issue?

1. Select the segment of highway that has `bridge=yes`
![image](https://user-images.githubusercontent.com/85302075/201435268-178b9b05-b144-4bea-a5bd-edf0ec110709.png)

2. Select another segment of highway

### Expected
Both highways selected should be pulsing red. (Screenshot from [v2.21.1](https://ideditor.org/id-2.21.1/#map=18.00/42.77859/-123.27859))
![image](https://user-images.githubusercontent.com/85302075/201435544-99be0971-e125-4248-b831-4575ad0d7a68.png)
### Actual result
The highways don't appear to be selected, however the selected features do show up in the Inspect/Edit Features menu. 
![image](https://user-images.githubusercontent.com/85302075/201435575-2082c3f4-d12c-4ddd-a3d0-739622e6338d.png)
Scrolling in/out will make the second highway look like it's only selected:
![image](https://user-images.githubusercontent.com/85302075/201435406-de277802-9412-4676-82b6-aa4ef59c642d.png)

3. Add/edit a tag in the Tags section (ie add `lanes=2`)
### Expected
Both highways should have the new tag

### Actual result
Only the first highway selected has this new tag. This same thing happens when adding a new/existing relation to both highways (only the first selected item gets added to the relation). Adding/changing tags in Fields however still works. 

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.23.1

**Comment by vmicho** [comment]
Have same problem from today.
It is not limited only to different structures. I cannot select even similar adjacent ways (like main road + service road).
When adding some unrelated objects to the mix (e.g. grass area to road+service road) then everything is selected again - after removing e.g. grass the 2 remaining ways are not selected again (listed but not highlighted).
On the listed but not highlighted ways, I cannot do any mass operations -> only one (1st selected I think) way will get the changes. It is now very difficult to edit relations (also tags like surface/bridge/layer) as it needs multiple selections, otherwise you have to work one way at once :(
Removing all relations from the affected ways does not fix the problem -> seems to be not related to relations list.

**Comment by polychloriert** [comment]
Can confirm the same bug as OP described but with regular streams and tunneled streams:
Stream object #1:
`natural=stream`

Stream object #2:
`natural=stream`
`tunnel=culvert`
`layer=-1`

If both objects are selected, then neither will appear highlighted on the map. This behavior is independent of the order they are selected. Selecting only one works just fine.

**Comment by Zyolix** [comment]
Just came across the issue while trying to edit (Windows 10 21H2 + Edge or Chrome) and can confirm the findings of the previous posters. When trying to select multiple line-based items, the highlighting of the selected object collection disappears. It still works in rare cases if certain attributes (did not evaluate in detail) of the selected objects match.
Multi-selection of area-based objects does not seem to be affected.
This is an ultimate showstopper. ID is not usable in this state.

**Comment by tyrasd** [comment]
I had overlooked in 635c4985482048d0b51d2a20a192e95455c242ec that this doesn't work for multiselections. I'll prepare a bugfix release. :bow:
