### ISSUE TITLE
Warn users about editing in Ukraine

### ISSUE THREAD

**Issue by 501Ghost** [openstreetmap/iD#9438]
In a discussion on the forum, linked below, it was suggested to warn users about the guideline against editing in Ukraine when they are about to create a changeset in the country. Would it be possible to do this?

Discussion: [​https://community.openstreetmap.org/t/mapping-activities-in-active-war-zones-in-ukraine/7221](https://community.openstreetmap.org/t/mapping-activities-in-active-war-zones-in-ukraine/7221)
Relevant guideline: [​https://wiki.openstreetmap.org/wiki/Russian%E2%80%93Ukrainian_war](https://wiki.openstreetmap.org/wiki/Russian%E2%80%93Ukrainian_war)
JOSM ticket on the same topic: https://josm.openstreetmap.de/ticket/22598

**Comment by Adamant36** [comment]
calling a random Wiki article that's only been edited by 2 people in the last six months a "guideline" is rather ridiculous. I know there have been several discussions about this in the past, but the article doesn't even link to them and they weren't proposals or anything. Especially since from what I remember there wasn't any consensus not to map in Ukraine in either of the discussions I saw. Really, something like this should be done through a proposal that involves the actual parties effected by it. Not some random user who isn't from the area opening a Github issue.

**Comment by 501Ghost** [comment]
Off-topic. This discussion is being held on the forum, no need to duplicate it here.
