### ISSUE TITLE
Uploading is complete, so don't still say uploading

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9467]
Push Save.
In the middle of the screen a spinner appears, and it says uploading changeset...

Then in the left panel we see "You just edited OpenStreetMap!", and even the changeset number.

OK, but the spinner in the middle of the screen still says uploading changeset for a few more seconds.

So it would be more accurate for it to say just "Upload complete. One (more) moment please..." now at that stage.

**Comment by bhousel** [comment]
> OK, but the spinner in the middle of the screen still says uploading changeset for a few more seconds.

This 2.5 second pause is an intentional workaround to let the OSM servers apply the changeset that just got uploaded.
https://github.com/openstreetmap/iD/issues/2678

With the community info in the side panel, the user has something else to look at for 2.5 seconds so they shouldn't notice the delay, and changing the message here just to remove it 2.5 seconds later seems unnecessary.
