### ISSUE TITLE
City/country name is not localised

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/iD#9499]
### How to reproduce the issue?

1. Change your locale Bulgarian (bg)
2. Go to 42.69093, 23.33091 and make some edit
3. Upload it
4. Notice the text on the left panel ("Благодарим ви за подобряването на картата около Sofia, Bulgaria.")

### Screenshot(s) or anything else?

The text should be using the features' names in the selected locale. The text in this case should be "Благодарим ви за подобряването на картата около София, България"
![image](https://user-images.githubusercontent.com/19364673/217494499-eeeb3a5c-3ec7-419d-aa6a-c8eb236fc585.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.24.1

**Comment by k-yle** [comment]
The english part (`Sofia, Bulgaria`) comes from [Nominatim](https://nominatim.openstreetmap.org), which uses your browser's locale, whereas the rest of iD uses [the settings for your OSM account](https://www.openstreetmap.org/preferences/edit). I have a similar problem, text from Nominatim is in te reo māori or spanish, but the rest of iD is in english. This is fixed in #9501
