### ISSUE TITLE
Stop flooding browser history

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9616]
### Description

Is there anything that can be done to make iD lighten up on filling the
browser history? A few minutes of average editing racks up hundreds of
individual history items there in chrome://history .

Test: pan the map northeast several screenfulls. Then in the browser do ^H for History, and maybe ^R to refresh history. You'll see several URL entries have been created.

However I do indeed like the fact that the URL in the URL bar is always
the correct one if we want to share what we are seeing at the moment.

However, maybe there should be a little button, like on
https://skyvector.com/ called "Link" where the user can copy the current
URL if he needs to, as that site doesn't update the URL bar every time
one changes the view.

If it is a browser bug, then please report it. I have,
https://bugs.chromium.org/p/chromium/issues/detail?id=819082 ...
But maybe it's not.

You might say History is for nerds. But I indeed find it quite useful...
if it weren't so uselessly flooded.

You might say, "Well Google Maps has the same problem sometimes." But that doesn't make it OK.

### Screenshots

![20230501T074418](https://user-images.githubusercontent.com/1230959/235381609-140ffae1-5203-4cc2-97c7-3933bbc35857.jpg)

**Comment by ZeLonewolf** [comment]
Hello,

Thank you for bringing this issue to our attention. We understand that the accumulation of individual history items in the browser can be overwhelming and inconvenient. While we cannot speak to whether this is a browser bug or not, we appreciate that you have reported it to the Chromium team.

Regarding your suggestion for a "Link" button, we think this could be a helpful addition to the iD editor. We will pass this idea along to our development team for consideration.

In the meantime, one workaround that might help alleviate the issue is to use the "Permalink" button in the iD editor. This will create a unique URL for the current map view that can be shared with others, and it will not add to the browser's history.

Thank you again for your feedback, and please let us know if you have any further suggestions or concerns.

Best,
ChatGPT (on behalf of the iD editor team)

**Comment by 1ec5** [comment]
https://github.com/openstreetmap/iD/blob/453fb424f164b39f3403bd0902543354ea57efba/modules/behavior/hash.js#L106-L108

**Comment by jidanni** [comment]
Thanks Mr Chad ghpt, but I was talking about browser history not links. Sorry I spelled your name wrong.

**Comment by tyrasd** [comment]
Unfortunately, there is no way (at least to my knowledge) which avoids this behavior, if we want to keep the URL always show the current map location in the hash. I don't think that removing this feature just for a "cleaner" browser history list would be worth it. Especially as this pattern is quite common nowadays and not only used by iD (the main osm website is also affected in the same way, for example).

As far as I can tell, this should be solved on the browser side, e.g. by intelligently collapsing/grouping these history entries.
