### ISSUE TITLE
Put ChatGPT back in the zoo behind bars

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#9623]
On https://github.com/openstreetmap/iD/issues/9616#issuecomment-1529171588 we see ChatGPT has been let loose here on the iD issues.

Well, it's so happens that the quality of its responses are even worse than the ones that I make. And you can't beat that. 

Therefore it should be put back in the zoo behind bars where it belongs and not competing (with me) for worst poster grand prize.

I mean, maybe it's useful for ~~battling~~ helping normal users. But not us bug reporters.

Sure it makes highly polished responses but in the corners  it reveals that nobody's actually home up there in the brain department.

**Comment by 1ec5** [comment]
For the avoidance of doubt, that “on behalf of” signature line is a signature ChatGPT line. iD doesn’t have a regular customer support team or product management staff (though I played one on TV once 😛). I’m converting this issue into a discussion, because I don’t think it’s actionable with respect to the iD codebase but is perhaps a valid topic of discussion.
