### ISSUE TITLE
`*traffic_sign` should not lowercase values

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#9640]
For the key `traffic_sign` all values are allowed to be upper case, like `DE:123`.

However, for more edge case keys like `cycleway:right:traffic_sign` the value gets transformed to `de:123` by iD.

Is there a way, to apply the "do not lowercase" rule to all keys that follow a pattern like `*:traffic_sign`?
Or is there another feasible workaround?

---

Context https://www.openstreetmap.org/changeset/135924000

**Comment by 1ec5** [comment]
Huh, it shouldn’t be doing that due to:

https://github.com/openstreetmap/id-tagging-schema/blob/8d45c78e651c588fab208c391525c49b98e38644/data/fields/traffic_sign.json#L5-L6

Wonder if there’s a bug in iD preventing that combination from keeping the value intact.

**Comment by tordans** [comment]
I assume this setting is per tag but those are sub tags which do not have the setting.

**Comment by 1ec5** [comment]
Oh, I should’ve read more carefully. iD doesn’t have a field for `cycleway:right:traffic_sign`. The automatic lowercasing (or snake-casing) only applies when entering text into a field, but not when editing the raw tags. Maybe iD’s autocompletion feature matched `DE:123` to a `de:123` that already occurs in the database according to taginfo.

**Comment by tyrasd** [comment]
Yep, it's a bug in iD's autocomplete feature. I'll move this issue over to the iD repo

**Comment by tyrasd** [comment]
To be precise: this is to a small part also an OSM data quality issue: in the raw tag editor, iD's autocomplete does no offer "nonstandard" tag values (e.g. ones with capital letters), because it assumes that these are typically spelling errors. But for the `cycleway:right:traffic_sign` tag there are enough values with the lowercase spelling of `de:237` that it is included in the combo box of tag suggestions (see [taginfo](https://taginfo.openstreetmap.org/tags/cycleway%3Aright%3Atraffic_sign=de%3A237#overview)). Now, if one starts to type `DE…`, the combo box in iD temporarily selects the value `de:237` which changes the spelling of the previously typed `DE` to lower case. I assume this was programmed like this on purpose to reduce the number of misspelled tag values (e.g. when someone types `Yes` in a field of the raw tag editor, it automatically snaps it to the most likely intended value of `yes` if `yes` is a common value of the tag key in question).

A superficial solution for this particular problem would be to clean up the OSM data to use the intended spelling of this particular value. However, this does not really solve it, as other similar issues still persist: For example, it is currently also cumbersome to enter values starting with `CH:` in the raw tag editor for the tag `traffic_sign`, as iD will offer to autocomplete the initial `C` to `city_limit` and thereby changing the initial `C` to a `c` if one does not type faster than the autocomplete can fetch the values from taginfo.

An easy fix would be to always use case sensitive tag matching in the raw tag editor, but this would disable the automatic fixing of potentially common misspellings of tag values. :thinking: I'm not sure how big the tradeoff would be for that.

To keep the tag "snapping" feature, but also be work properly for all case sensitive tags, a solution would require us to maintain a list of tag keys (or tag key patterns) in iD for witch the combo box should use behave in a case sensitive manner.

**Comment by bhousel** [comment]
> To keep the tag "snapping" feature, but also be work properly for all case sensitive tags, a solution would require us to maintain a list of tag keys (or tag key patterns) in iD for witch the combo box should use behave in a case sensitive manner.

Maybe you are looking for this
https://github.com/openstreetmap/iD/blob/a35653d35d07e7d122a77e04489aa23df8dd05e0/modules/services/taginfo.js#L311-L317

**Comment by tyrasd** [comment]
Thanks for the pointer, @bhousel! Adding `traffic_sign` to the `allowUpperCase` pattern does indeed solve the `DE:123` issue. Unfortunately, it doesn't go all the way, as for the other example mentioned above of entering `CH:123` in the `traffic_sign` tag, the result is somewhat counterproductive. But I think this should be solved relatively easily by reusing the same pattern also in the `combo` field's _input to taginfo-suggestion_ matching. :+1:
