### ISSUE TITLE
Latest iD 2.24 not working anymore on tablets

### ISSUE THREAD

**Issue by julcnx** [openstreetmap/iD#9693]
### How to reproduce the issue?

I've found iD to be incredibly efficient on larger touch devices and tablets, especially when using a pen to realign roads and areas based on GPS traces and imagery. However, I've encountered an issue recently. When trying to access iD on my two iPads, all I get is a blank page. I've tested it on Chrome, Safari, and Edge browsers, but the problem persists.

I was wondering if anyone else has experienced this issue and can confirm it. Additionally, if anyone has any pointers on how to fix it, I'd be more than happy to help and even submit a merge request if needed.

Thanks in advance for any assistance!

### Screenshot(s) or anything else?

<img width="1878" alt="image" src="https://github.com/openstreetmap/iD/assets/2485196/c91f04af-acd1-42a6-9900-3934f57c923c">
<img width="2088" alt="image" src="https://github.com/openstreetmap/iD/assets/2485196/4a9b0966-6036-4833-b628-66f50e7408be">

**Comment by 1ec5** [comment]
What version of iOS are you running? The JavaScript error looks like potentially a case of syntax that’s too new for the browser environment. On iOS, all browsers have to use the same JavaScript engine, so it’s unsurprising that it would affect Chrome and Edge too.

**Comment by julcnx** [comment]
> What version of iOS are you running?

13.3. Could someone using a newer iOS version kindly verify if it truly functions?

**Comment by 1ec5** [comment]
I don’t have an iOS 13 device around to test in, but if I’m not mistaken, iOS 13 runs Safari 13, which is also what comes with macOS 10.13 High Sierra. I am able to load iD in Safari 13 on High Sierra. Can you try opening iD in https://ideditor.netlify.app/ instead of openstreetmap.org? That way you’re more likely to get an error that points to a specific line in unminified code.

**Comment by julcnx** [comment]
> Can you try opening iD in https://ideditor.netlify.app/ instead of openstreetmap.org? That way you’re more likely to get an error that points to a specific line in unminified code.

Web page says "Sorry, your browser is not currently supported. ..."

Console shows and error but still points to minified code.

<img width="997" alt="image" src="https://github.com/openstreetmap/iD/assets/2485196/cfc25178-ae5c-4b17-8653-a6810c0c923f">

**Comment by 1ec5** [comment]
`npx browserslist` lists `safari 13`, so it isn’t a case of iD’s build system intentionally breaking this configuration. What if you set a breakpoint on uncaught exceptions – what does the stack look like?

**Comment by julcnx** [comment]
Strangely there seems to be no uncaught exceptions. My stacks stop on "All exceptions" but they are all contained within try/catch statements.

**Comment by 1ec5** [comment]
My bad, it wouldn’t be an exception because it’s a syntax error. Unfortunately I’m not quite able to proceed without being able to reproduce the error in a development environment. Perhaps you could clone and build iD, then `git bisect` between v2.24 and the last release you were able to use to attribute the breakage to a particular commit?

**Comment by julcnx** [comment]
I finally upgraded to IOS 16 and it works fine so we can close this issue.
