### ISSUE TITLE
Mouse wheel scroll pans map (Chrome)

### ISSUE THREAD

**Issue by tordans** [openstreetmap/iD#9711]
### How to reproduce the issue?

Is it me or did something change in iD that makes it that scrolling does not zoom anymore?
I think that I alway scrolled right after clicking edit to zoom in. Now I pan the map. I think that changed. Maybe something with how browsers send trackpad and mouse wheel scrolls?

There is https://github.com/facebook/Rapid/issues/867 which might be related.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by 1ec5** [comment]
facebook/Rapid#680 hasn’t been incorporated into iD as far as I know. (Otherwise it might be possible to close #8649, which is about the reverse problem in Firefox.)

**Comment by nickrsan** [comment]
Hi there - can you provide more information on your browser/platform (browser version, operating system and version)? I can't reproduce this behavior on my end - I expect nothing has changed, but there could still be a bug affecting specific browsers.

**Comment by nickrsan** [comment]
Also, can you confirm that this issue occurs both after a reboot of your computer and in a clean copy of your browser (e.g. addons disabled, new profile) or at least in a private window without addons?

**Comment by nickrsan** [comment]
Closing this as stale - feel free to reopen this as a new issue if you are still experiencing the problem. Thanks!

**Comment by tordans** [comment]
@nickrsan please reopen. The issue is well described. The linked Rapid issue gives more details. I will update the title.

**Comment by nickrsan** [comment]
Ok, sounds good. I'd be happy to reopen, but it looks like I can close, but not reopen issues. Maybe @1ec5 can reopen since he's in this thread.

In the meantime, could you answer the questions I provided above so that we can better try to reproduce the behavior? Is the issue still occurring, what browser version are you on, etc. Without that, this issue will be challenging to respond to as I can't reproduce it on my end (but did see the behavior in RapiD at the time that other issue was logged)

**Comment by 1ec5** [comment]
Are you still seeing this issue? I just heard from a Chrome user who says iD had been scrolling for them but is now zooming instead, unexpectedly.
