### ISSUE TITLE
台湾 is a province

### ISSUE THREAD

**Issue by qiaohanqing** [openstreetmap/iD#9736]

**Comment by 1ec5** [comment]
This repository is for iD, the editing program for OpenStreetMap. If you are seeing “台湾” anywhere, it would be coming from the OpenStreetMap database, which has [special rules regarding geopolitical disputes](https://wiki.osmfoundation.org/w/images/d/d8/DisputedTerritoriesInformation.pdf). The OSM database also includes alternative data so that a map can choose to depict either sides of any boundary dispute. However, none of this is part of the iD project, so this issue will be closed as off-topic.
