### ISSUE TITLE
Why id Editor can't use else customized images

### ISSUE THREAD

**Issue by MyeongSaeHo** [openstreetmap/iD#9796]
### How to reproduce the issue?

dame.

**Comment by nickrsan** [comment]
Hi there - we can't respond to your question without additional information - I'm closing this issue now because it doesn't have any details, but if you wish to ask a general question rather than report a specific bug or a feature request, please open a new thread in the [Discussions section](https://github.com/openstreetmap/iD/discussions) with as many details as possible about what you're trying to do, what you're expecting iD to do, and what it's doing instead of what you expected. Thank you!
