### ISSUE TITLE
does not work with Firefox 78.15.0esr any more

### ISSUE THREAD

**Issue by traut21** [openstreetmap/iD#9930]
### URL

https://i.ibb.co/bzk1hTz/Screen-Shot-2023-10-06-at-15-17-58.png

### How to reproduce the issue?

1) open openstreetmap.org with (outdated) Firefox 78.15 (a newer version is not available for this computer)
2) open edit
3) headers appear, but the editor does not open

### Screenshot(s) or anything else?

<img width="1280" alt="Screen Shot 2023-10-06 at 15 17 58" src="https://github.com/openstreetmap/iD/assets/25948981/64e5f860-0965-4b47-b260-c3efc3cf90b3">

When I inspect the element I see 

"The page’s settings blocked the loading of a resource at data: (“media-src”)." 

Uncaught SyntaxError: expected expression, got '='

https://www.openstreetmap.org/assets/id-859874f88bc2e65931793d0d2edfb626917168cd008d86196e5b6fe2c88b39d5.js

:29:19029

It does work with a current FF version

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by k-yle** [comment]
~~This seems to be intentional,~~ the supported browser versions are defined here:

https://github.com/openstreetmap/iD/blob/68ff64b01d5a125950474dbf567bc0a9fa3b9edd/package.json#L129

The Norway-specific code (#9509) introduced the `??=` operator, ~~so FF 79 is now the minimum supported version~~<sup>[[1]](https://caniuse.com/mdn-javascript_operators_nullish_coalescing_assignment)</sup>

EDIT: Seems like there's a bug in the build system that's causing the code above to be ignored
