### ISSUE TITLE
Turn Restrictions Editor does not appear when I need it to

### ISSUE THREAD

**Issue by Vectorial1024** [openstreetmap/iD#9983]
### URL

https://www.openstreetmap.org/edit#map=19/22.34097/114.13254

### How to reproduce the issue?

1. click on this node
2. realize there is no Turn Restrictions Editor

![image](https://github.com/openstreetmap/iD/assets/17726797/2bd4821c-5f3f-4442-90ed-4d0f888d10e5)

### Screenshot(s) or anything else?

This issue was found out because of another issue elsewhere: https://github.com/graphhopper/graphhopper/issues/2907

Basically, I need the Turn Restrictions Editor to appear to describe the following valid paths:

![image](https://github.com/openstreetmap/iD/assets/17726797/956e75a4-176d-4c79-a83d-afbecb06cd69)

Source A may only reach destination 1, and source B may only reach destination 2. No crossing paths allowed.

Clearly, the existing iD editor can handle turn restrictions via 1 way. What needs to be done here is very simple: make the Turn Restrictions Editor appear.

Someone else added the relevant turn restrictions to this area possibly via JOSM. Curiously, the iD editor knows about this added turn restriction, because it refuses to delete the node at source A saying how this would damage an OSM relation.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.27.3

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
The restriction editor was hidden because the intersection only had a single outward pointing way. But you are right, for restrictions with _via_ ways(s), it should be shown. The commit above addresses this.

Note that in the particular situation above, the _via_ way is unfortunately longer than 50 meters, which is the maximum radius the turn restriction editor allows to set. This means in order to edit the restrictions at this point, you'd have to move the start or end vertex of the way such that the whole "intersection" fits into the 50 m radius.
