### ISSUE TITLE
Enhancements in OpenStreetMap iD Editor for Improved Representation of Social Aid Facilities

### ISSUE THREAD

**Issue by Asteliks** [openstreetmap/iD#9984]
### Description

Hi iD Editor Team,

I hope this message finds you well. I'm an avid mapper on OpenStreetMap with some limitations in my capabilities. If I'm reaching out in the wrong place, kindly guide me to the appropriate channel for support.

I am currently focusing on mapping social aid facilities, especially during the colder months when these facilities are frequently sought by those in need. I have noticed a few areas for improvement in how we handle these facilities on OSM, particularly in the iD editor.

I would like to request enhancements that allow for a more nuanced representation of social aid facilities. Currently, during the winter season, the demand for such facilities increases significantly. It would be immensely helpful if the iD editor could support the addition of multiple types of services within a single facility. For instance, a facility might function as both a food kitchen, a legal aid center, and a shelter, each with potentially varying operating hours.

Moreover, I've observed a lack of predefined categories in iD, such as 'food kitchen.' Presently, one must select a general 'social aid facility' category and then specify further details. This process can be cumbersome and might lead to inaccuracies. It would be beneficial if iD had predefined categories, making the mapping process more intuitive and accurate.

I appreciate your dedication to continually improving the OpenStreetMap ecosystem, and I believe these enhancements would greatly contribute to better mapping of essential social aid facilities, especially during critical times.

Thank you for considering my request, and I look forward to the continued success of OpenStreetMap.

**Comment by DujaOSM** [comment]
Hi @Asteliks,
Issues related to iD presets have been recently (well, some 2 years ago) moved to the repository [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema/issues). I hope someone with sufficient privilege can move this one there (so that we do not have to repost). 

At the moment, the only existing preset seems to be "Social facility", from which a sub-type can be selected. Searching for "kitchen" does not find anything of relevance, and what you're looking for would be a [social_facility=soup_kitchen](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dsoup_kitchen) with some relevant attributes to be filled in. The related preset "Food bank" does exist  [social_facility=food_bank](https://wiki.openstreetmap.org/wiki/Tag:social_facility%3Dfood_bank) though.

**Comment by nickrsan** [comment]
> each with potentially varying operating hours.

Someone better than I am at tagging may have a more useful suggestion, but if each of these services has different services *and* hours, I'd recommend a workaround of entering each service as a separate point and adding the relevant information to each point. Even if they're positioned close to each other, you'd still be able to enter the data that way.

**Comment by tordans** [comment]
Hey! This sounds like a discussion for the already mentioned https://github.com/openstreetmap/id-tagging-schema repo. I will close this here.
